### ISSUE TITLE
further npm_umd_bundle improvements

### ISSUE THREAD

**Issue by Toxicable** [bazelbuild/rules_nodejs#1006]
# 🚀 feature request

## Relevant Rules
`npm_umd_bundle`

## Description
We could improve this rule by replacing the underlying bundler from `browserify` with `webpack`.
There are 2 distinct advantages to this:

### automatic ignoring of dynamic requires

Currently we have an attribute `excluded` where the downstream users must manually provide a list of modules which should not be resolved at runtime, these usually appear as dynamic require for native nodejs modules which shouldn't be bundled into browser bundles in the first place.
Wepack has support for automatically ignoring these imports.
Meaning the user dosen't have to define their own `npm_umd_bundle` to specify the `excluded` modules.

### externalised implementation of mainField priorities

Since webpack knows how to resolve and prioritise main fields we can remove our implementation and replace it with a entrypoint that imports the lib we want to turn into a umd, then bundle that instead and let webpack resolve the main fields

There is some risk in that vendoring webpack may prove challanging.

**Comment by alexeagle** [comment]
it's amusing that we use ncc to vendor browserify, which itself uses webpack, so I've had a great time debugging module loading problems where it's hard to distinguish the browserify code from the webpack wrappers...

It's hard for me to imagine how this would be worth the effort to switch...

**Comment by Toxicable** [comment]
@alexeagle Yeah I know, I think this is more of a quality of life change more than a required one.
Since it would just avoid users needing to write their own umd targets npm deps.

**Comment by Toxicable** [comment]
Just took a quick gab at vendoring `webpack`, in the process of doing so it produces a `fse.node` artifact, which is a binary file, so we'd have to find a way avoid this binary dep in order to vendor webpack
