### ISSUE TITLE
`npm_install` fails with 'Process terminated by signal 6'

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#101]
Reported at https://github.com/alexeagle/angular-bazel-example/issues/67

**Comment by alexeagle** [comment]
I think the problem here was the system node version. Try `nvm use 8.9` to switch.
Root cause is https://github.com/bazelbuild/rules_nodejs/issues/77

**Comment by gregmagolan** [comment]
#77 fixed with #105 which resolves this issue
