### ISSUE TITLE
node_loader.js error message doesn't match Node's own error message

### ISSUE THREAD

**Issue by bweston92** [bazelbuild/rules_nodejs#1015]
# 🐞 bug report

### Description

The loader script `rules_nodejs` uses a custom error message for failed package resolution. Some users/packages match against the error message that Node's official loader script provides.

## 🔬 Minimal Reproduction

https://github.com/bweston92/debug-gatsby-bazel-rules-nodejs

**Rules version (SHA):**

<pre>
  <code>
f98fa199c034850eb5be750011f306deacf645ea
  </code>
</pre>

**Anything else relevant?**

Discussion on Gatsby: https://github.com/gatsbyjs/gatsby/pull/16573

Message in Slack from @alexeagle 
> seems like a rules_nodejs bug to me. commented on that issue - I think we just need to make our error message look more identical to the one vanilla nodejs would print and that gatsby expects.

**Comment by alexeagle** [comment]
Was fixed in #1016
