### ISSUE TITLE
ts_devserver: ibazel livereloading if concatjs bundle is not used

### ISSUE THREAD

**Issue by devversion** [bazelbuild/rules_nodejs#1036]
# 🐞 bug report

### Affected Rule

ts_devserver (`@bazel/typescript`)

### Is this a regression?

No

### Description

In some scenarios the concatjs bundle is not desired/used. e.g. for lazy loading. 

One could say that in that case the concatjs bundle can be just empty.. but that doesn't work because the `deps` attribute will be used to add the lazy input files to the servable runfiles (that's a different issue though).

## 🔥 Exception or Error

The livereloading script from `ibazel` is currently served at a non-static URL. Meaning that we can't just add a script import to the livereload script in the `index.html`.

If the `ts_devserver` uses the concatjs bundle it works because the devserver go implementation currently reads the `IBAZEL_LIVERELOAD_URL` environment variable and adds the script to the concatjs bundle.

**Anything else relevant?**

One easy solution would be to provide a proxy URL in the devserver that always redirects to the URL specified in the `IBAZEL_LIVERELOAD_URL` environment variable.

I will have a look into this.

**Comment by devversion** [comment]
Well, another reason to use `ts_devserver` besides the ibazel integration is the runfile resolution that makes it the only devserver implementation that also works on windows.

Surely we could implement our own devserver but `ts_devserver` works great for most cases right now and only lacks live-reloading for some targets right now (due to this issue). Happy to work on our own implementation of the `ts_devserver` if needed, but I feel like it restricts use-cases a lot if `ts_devserver` is only intended to be used with ConcatJS.

Additionally the use of concatjs is not ideal for lazy-loading. Otherwise we'd have used that.

**Comment by alexeagle** [comment]
As stated, we aren't going to do this. `ts_devserver` should be better named `concatjs_devserver`.

I think a better FR is probably "show how to make my devserver do ibazel livereload and handle runfiles"
