### ISSUE TITLE
Upgrading to 0.36.0 from 0.32.2 does not work

### ISSUE THREAD

**Issue by fejta** [bazelbuild/rules_nodejs#1041]
See https://github.com/kubernetes/test-infra/pull/13997, "System is not defined"

**Comment by alexeagle** [comment]
Sorry for the breakage!
I don't see "System is not defined" referenced from that issue anywhere. Can you point me to the failure?

**Comment by fejta** [comment]
@Katharine @stevekuznetsov do you have any more details describing the problem?

There were some discussions about this on #testing-ops in kubernetes.slack.com (see screenshot)

We believe we fixed the issue (by disabling `enable_code_splitting`) in https://github.com/kubernetes/test-infra/pull/14006


![screenshot_from_2019-08-20_17-10-17](https://user-images.githubusercontent.com/940341/63475992-06075c80-c434-11e9-86fd-346d1b560b93.png)

**Comment by alexeagle** [comment]
Ah yes, that makes sense.
https://github.com/bazelbuild/rules_nodejs/releases/tag/0.35.0 described that as a breaking change, so I'd suggest when doing the updates in the future, to scan through the breaking changes
(we should also include these in the CHANGELOG.md - looks like we've had bad hygiene there)

anything else I can do to help or avoid this next time?

**Comment by Katharine** [comment]
The release notes describe it as a breaking change, but give no hint as to what you're supposed to do if you don't want to be broken by it. I couldn't find it in the documentation either. What is the recommended way of doing this now? The examples I checked seem to either explicitly disable the feature or use `web_package`, which seems to be internal.

**Comment by fejta** [comment]
Thanks for the info!

If we know that having `additional_entry_points` in `rollup_bundle` is a problem, ideally there would be some upgrade tool we can run which a) flags this as a problem and b) ideally refactors things for us.

Another thing that would be helpful is if changes like this somehow caused `bazel build` or `bazel test` to break until we take corrective action -- that is annoying, but definitely less annoying than passing tests and then cutting a bad release.

**Comment by alexeagle** [comment]
I see that the rollout of the feature is pretty annoying. I suppose your application has a dynamic import() statement somewhere? That means it now is multiple chunks and expects a runtime loader. The es2015 output uses the browser's native loader but you probably got the default output which is still targetting older browsers and expects the system.js loader to be on the page.

There's not much I can do to enhance your tests in this case. The dev sources still work fine and all the tools run successfully -  the output of the optimizer is only used in your app, so you ought to have a protractor test or some other e2e test that verifies that the app works.

**Comment by alexeagle** [comment]
Since we're still pre-1.0, we advertise that breaking changes are likely. I don't think there's more to do on this issue - sorry again you had to firefight this.
