### ISSUE TITLE
Modules without typings can't be found

### ISSUE THREAD

**Issue by yohcop** [bazelbuild/rules_nodejs#1046]
I have a project that compile fine with Webpack. However I get `error TS2307: Cannot find module 'deepmerge'.` -like errors when building with Bazel. I use the same tsconfig and node_modules, etc.

It seems that this package (deepmerge) doesn't come with types. In this case (deepmerge), there is `@types/deepmerge` available. Installing it fixes things more or less. But it is not the case for every package out there. (plus I can't make `@types/deepmerge` work correctly.... so let's assume it doesn't exist for now)

It's odd that things build with Webpack, but not with Bazel. Here's a sample repo that build as is. But remove or comment the test/test.d.ts file, and the build fails:
https://github.com/yohcop/rules-typescript-test

```
> bazel build test
INFO: Analysed target //test:test (0 packages loaded).
INFO: Found 1 target...
ERROR: /tmp/test/test/BUILD:3:1: Compiling TypeScript (devmode) //test:test failed (Exit 1)
test/test.ts(1,20): error TS2307: Cannot find module 'deepmerge'.
```

The tsconfig.json has `"noImplicitAny": false` of course. Typescript should be able to handle those js-only packages since 2.1 or something like that. I suspected some of the overridden tsconfig `compilerOptions`, maybe `module`. In the end I couldn't make things work without the `declare module 'deepmerge';` in `test.d.ts`.

Any ideas? Or suggestions for me to try? Thanks!

**Comment by alexeagle** [comment]
Note, one possible "escape hatch" is to use plain `tsc` rather than `ts_library`, see https://github.com/bazelbuild/rules_nodejs/blob/master/packages/typescript/docs/install.md#alternatives

**Comment by yohcop** [comment]
This was a while back, and I *think*, I made it work by creating an empty library, with an empty defs.ts and a defs.d.ts containing "declare module deepmerge" (to follow my example above). In libraries using those packages, I just depend on my //...:defs ts_library.

**Comment by Serginho** [comment]
@yohcop Same problem. Could you explain it in more detail?

**Comment by yohcop** [comment]
Sorry, I just found this again. I basically have a defs.d.ts file that looks like:

```
declare module "identicons";
declare module "rc-progress";
declare module "react-textarea-autosize";
declare module "recharts";
```

I also have an empty def.ts next to it, probably to make the BUILD rule happy.

Then, I have:

```
ts_lib(
    name = "defs",
    srcs = [
        "defs.d.ts",
        "defs.ts",
    ],
)
```

(where ts_lib is just a typescript_library, with some defaults)

So whenever I need to use one of those libraries, say recharts, I add to my dependencies something like:

```
ts_lib(
    name = "dashboard",
    srcs = [ ... ],
    deps = [
        "//fitzenith/web:defs",
        ...
    ],
)
```

Hope that helps!
