### ISSUE TITLE
reduce dependence on browser tests

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#1059]
For the most part, we don't really care about having a real browser for our integration tests. `domino` DOM is good enough to test our bundles in nodejs. I tried this out in the new kotlin example https://github.com/bazelbuild/rules_nodejs/pull/1057/files#diff-4716ec1aafc58bef461bb32d4349afe3 and it works great.

Should make our tests faster.

**Comment by Toxicable** [comment]
I tried at one stage to run Angular unit tests with on nodejs with jasmine and domino, but didn't managed to get it running.
https://repl.it/@Toxicable/angular-jasmine-nodejs

**Comment by gregmagolan** [comment]
No longer in scope for rules_nodejs which only supplies the Node.js toolchain as of [v6.0.0](https://github.com/bazelbuild/rules_nodejs/releases/tag/v6.0.0-beta0).

Downstream canonical JavaScript + Node.js ruleset is now https://github.com/aspect-build/rules_js.
