### ISSUE TITLE
Module resolution in ts_library seems to be broken

### ISSUE THREAD

**Issue by marcus-sa** [bazelbuild/rules_nodejs#1065]
# 🐞 bug report

### Affected Rule
The issue is caused by the rule: `@npm_bazel_typescript`

### Is this a regression?
I suppose it is, since I've never had this issue before with mono repositories in the past...
I've spend almost 2 days just trying to get this to work.

### Description
I keep hitting a `Compiling TypeScript (devmode) ... error TS2307: Cannot find module ...` whenever I try to build a `ts_library` which references another `ts_library` which has a `module_name` defined.. you know the drill.

## 🔬 Minimal Reproduction
Just clone https://github.com/marcus-sa/bazel-ts-monorepo which is the minimal setup for a TS monorepo and run
```
$ yarn install
$ yarn build
```

Or a more complex repository (where this issue first occurred)
https://github.com/marcus-sa/ng-qt/tree/feat/bazel

## 🔥 Exception or Error

<pre><code>
$ bazel build //...
INFO: Analyzed 2 targets (26 packages loaded, 669 targets configured).
INFO: Found 2 targets...
ERROR: /home/marcus-sa/Documents/test/monorepo/packages/core/BUILD.bazel:5:1: Compiling TypeScript (devmode) //packages/core:core failed (Exit 1)
packages/core/src/index.ts:1:22 - error TS2307: Cannot find module '@test/common'.

1 import { TEST } from '@test/common';
                       ~~~~~~~~~~~~~~

INFO: Elapsed time: 0.805s, Critical Path: 0.10s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
error Command failed with exit code 1.
</code></pre>


## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu Budgie 19.04
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 0.28.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 19 15:19:51 2019 (1563549591)
Build timestamp: 1563549591
Build timestamp as int: 1563549591
Done in 0.09s.
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>
        "@bazel/bazel": "latest",
        "@bazel/buildifier": "latest",
        "@bazel/ibazel": "latest",
        "@bazel/typescript": "latest",
        "@types/node": "^12.7.2",
        "typescript": "~3.4.0"
  </code>
</pre>

**Comment by Toxicable** [comment]
You don't have anything exported from the top level of your module.
if you did `import { TEST } from '@test/common/src';` it would work

**Comment by marcus-sa** [comment]
Ah @Toxicable that makes sense.. 🤦
