### ISSUE TITLE
rename es6 outputs and collect_es6_sources to es2015

### ISSUE THREAD

**Issue by IgorMinar** [bazelbuild/rules_nodejs#107]
ES6 is an unofficial name for ES2015. The official name of the spec is ES2015. Since then we've also ratified ES2016, ES2017, and [just recently ES2018](http://2ality.com/2017/02/ecmascript-2018.html).

let's use the official name to pave the path supporting newer versions of the spec.

**Comment by alexeagle** [comment]
It's in rules_typescript too which is shared with google3...

**Comment by IgorMinar** [comment]
you know what my answer to that is :-)

@mprobst can we do rename the output in typescript rules? it's either now or in 12 months when we are moving the baseline to ES2017 or newer. At that point there will be even more places using it.

**Comment by alexeagle** [comment]
If we move prodmode to ES2017 that will naturally solve the issue, right?

**Comment by alexeagle** [comment]
I don't think this is ever going to be high enough priority to do it.
The problem will solve itself eventually when es2015 is old and forgotten.
