### ISSUE TITLE
Examine all public APIs

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#1070]
Make sure the APIs are consistent, eg. attribute named the same
- rename ts_devserver#static_files to assets to match web_package

Should go through all the rules with a comb, and find any other APIs that we don't want to commit to supporting in 1.0

**Comment by alexeagle** [comment]
TODO: remove transitive_js_ecma_script_module_info alias before 1.0 release
-> should remove

**Comment by gregmagolan** [comment]
If you search to the repo for `1.0 release` then there are 7 results for things to remove.

**Comment by gregmagolan** [comment]
Just about done. All PRs for this either landed or queued.

Queued up are:
* https://github.com/bazelbuild/rules_nodejs/pull/1481
* https://github.com/bazelbuild/rules_nodejs/pull/1470
* https://github.com/bazelbuild/rules_nodejs/pull/1465

**Comment by gregmagolan** [comment]
#1488 and #1490 landing shortly and cutting 1.0 after that
