### ISSUE TITLE
Drop support for Node 10

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#1071]
https://github.com/nodejs/release says that Node 12 Active LTS is scheduled to start 2019-10-22 (one month from now)

Since our 1.0 release will be after that, we don't need to support Node 10 at all. Things like worker threads are relevant for us and we don't want to support two different ways to do it.

(Note that this doesn't mean we intentionally make it impossible to use Node 10. But bugs related to Node 10 are outside our scope and we don't support it.)

**Comment by gregmagolan** [comment]
Once we do that we can assume that --preserve-symlinks-main is available as well and remove node version check. It was added in node 10.2.0 (https://nodejs.org/api/cli.html#cli_preserve_symlinks_main)

**Comment by kylecordes** [comment]
It's great to see this item out here for dropping the now-old Node 10. But the published docs:

https://bazelbuild.github.io/rules_nodejs/install.html

mention `10.13.0` as the default (and newest) supported Node version. It seems that dropping 10 implies adding (or having added already) support for 12?

**Comment by igilham** [comment]
Not all users will be able to drop non-latest Node immediately upon its release. This may be a little premature. Most cloud environments take a long time to support new Node LTS releases (App Engine, Cloud Functions, AWS Lambda, etc)

**Comment by alexeagle** [comment]
Only thing to do is to update doc
