### ISSUE TITLE
rollup_bundle requires indirect deps[] to be specified

### ISSUE THREAD

**Issue by jbedard** [bazelbuild/rules_nodejs#1074]
In some cases `rollup_bundle` requires indirect `deps[]` to be specified. I think all cases have been angular deps so far.

One example was `@npm//@angular/material` being required in `rollup_bundle(deps)` even though it was not a direct dependency. The rule deps were:
```
rollup_bundle => ng_module => ng_module => @npm//@angular/material
```

The angular `@NgModule` deps were essentially the same:
```
AppModule => FeatureUsingMaterialModule => MatTooltipModule
```

The `rollup_bundle` rule would fail unless `@npm//@angular/material` was added to `rollup_bundle(deps)`.

**Comment by alexeagle** [comment]
We should see if this problem exists in the new implementation. IF not, we might not bother back-porting a fix.

**Comment by alexeagle** [comment]
new `rollup_bundle` is released, can you check if it's fixed?

**Comment by ajbouh** [comment]
I believe I have also been experiencing this issue, and am using 2.0.0.

I had been thinking it was because I was not properly propagating my LinkablePackageInfo provider somehow, but after a day of trying to debug it, I now suspect the issue is elsewhere (e.g. perhaps in rollup_bundle)?
