### ISSUE TITLE
Support code splitting in ts_devserver

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/rules_nodejs#1081]
# 🚀 feature request

### Relevant Rules

ts_devserver

### Description

Loading megabytes of JS into the browser can be substantially slow, especially in development mode with unminified libraries. Code splitting breaks up the code into asynchronously related chunks, which are loaded on-demand.

This is currently supported only for prod mode:

@gregmagolan Sep 2018 https://medium.com/@gregmagolan/code-splitting-and-lazy-loading-with-bazel-9b11ac4de20b

> The development server rule, ts_devserver, in rules_typescript does not yet support code-splitting and does not serve a code-split bundle.

> Development mode requires a fast RTT (round-trip-time) from when a developer makes a change to a source file to when the application is reloaded in the browser. The RTT should be short and proportional to the size of the change. Our intent is that the median RTT is less than two seconds, even for a large application. ts_devserver uses in-memory, on-the-fly bundling to generate the development bundle in order to accomplish this. Getting code-splitting to be fast and proportional to the size of the change in development mode is challenging and we have not developed a solution to this problem to date.

Develop a solution for development mode code splitting.

### Describe the solution you'd like

I imagine there is some preprocessing step to generate manifests of file-level dependencies. IMO there's no need to beyond file-level analysis.

Apparently, Google has done some internal work along this direction:

@alexeagle Aug 2019 https://github.com/bazelbuild/rules_nodejs/issues/1036#issuecomment-524892022

> we do have some experimental code in ts_devserver to support lazy-loading but it's not in the open-source version. It depends on a manifest file format that describes which sources go into which chunks. @evmar worked on that - I could imagine this might make some progress as we work on our dynamic bundling solution for production which relies on concatjs too.

### Describe alternatives you've considered

Some homebrewed solution.

**Comment by alexeagle** [comment]
Yes this is on the roadmap for after 1.0 - but one observation: at Google we have huge apps and use `ts_devserver` to pump megabytes of JS into the browser and it works fast enough. Our motivation for codesplitting in dev mode is to let you debug lazy-loading issues without having to switch to a slower optimized production build.

**Comment by jmclen** [comment]
I have a very large app I'm working on with nearly 2,500 components. The ts_scripts.js file generated is around 675mb and won't load completely in any browser. In production mode with code splitting, it works fine. I know you guys have apps of that scale at Google. Do you even bother with ts_devserver and in a related question, do you have a way to use rollup over multiple cores? Rollup seems to only be single-threaded and is by far biggest bottleneck in production mode when building incrementally.
