### ISSUE TITLE
Rename/move ts_devserver

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/rules_nodejs#1082]
# 🚀 feature request

Nit, but "ts_devserver" is a rather misleading name, as it doesn't touch TypeScript at all. Ideally, it'd be named something like `js_devserver`.

Also, funnily enough, it's in rules_typescript. (I suspect this simply the world being exposed to some internal Google organizational concern?)

**Comment by alexeagle** [comment]
You caught our organizational concern!

if I were to name this today, I'd call it concatjs_devserver since it's tied to that particular bundler (and requires named AMD/UMD inputs or goog.module which is unusual)

We are thinking of some renames internally too. Googlers: http://b/140889721

**Comment by alexeagle** [comment]
Let's rename to `named_amd_devserver` or `concatjs_devserver` since it's restricted to JS modules whose paths can be lost

**Comment by alexeagle** [comment]
landed in #2239
