### ISSUE TITLE
Windows: Remove Bash dependency

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/rules_nodejs#1102]
# 🚀 feature request

### Description

Rules released in rules_nodejs should not depend on Bash on Windows.

### Describe the solution you'd like

We currently depends on Bash in the following places:

- [x] sh_binary/sh_test: To be removed by https://github.com/bazelbuild/rules_nodejs/pull/1078
- [ ] shell script for launching nodejs binary, [node_launcher.sh](https://github.com/bazelbuild/rules_nodejs/blob/master/internal/node/node_launcher.sh) and [launcher for protractor_web_test](https://github.com/bazelbuild/rules_nodejs/blob/c96b470bff11f204c7f287730cb4a46b81b71f94/packages/protractor/src/protractor_web_test.bzl#L89)
We can re-implement the logic in this file in nodejs, then use a simple Bash script to run the node script on Linux and a Batch script to run it on Windows. (In a similar way we use a Batch script to run Bash currently, see [windows_utils.bzl](https://github.com/bazelbuild/rules_nodejs/blob/master/internal/common/windows_utils.bzl#L70))
- [ ] ctx.actions.run just to `cp` files at https://github.com/bazelbuild/rules_nodejs/blob/843d8e48f763d4a9efce49d260c1e65529985586/third_party/github.com/bazelbuild/bazel-skylib/rules/private/copy_file_private.bzl#L50

`ctx.actions.run_shell` API in [rollup_bundle.bzl](https://github.com/bazelbuild/rules_nodejs/blob/848065ec532cc825dd152238b7d132a0293e489f/internal/rollup/rollup_bundle.bzl#L365) will go away since the legacy rollup_bundle will be deprecated/removed by 1.0.

I checked in the release artifact of rules_nodejs, we don't have any usage of genrule, so that's nice. In the rules_nodejs repo, we still use some genrules, but I believe that's fine.

To test we can set `BAZEL_SH=C:/not/exist/bash.exe` or pass `--shell_executable=` during the build.

/cc @alexeagle

**Comment by mrmeku** [comment]
This is a great tracking bug to have. I have a party interested in running rules_nodejs on windows so if you can utilize this tracking bug or something else to keep track of windows incompatibilities I would be happy to make PRs to fix some of them which affect my client

**Comment by meteorcloudy** [comment]
Hi @mrmeku , this bug is intended to track the progress of making rules_nodejs Bashless on Windows. Do you want to contribute to it? The main blocker is to replacing the `node_launcher.sh` script.

**Comment by gregmagolan** [comment]
No longer in scope for rules_nodejs which only supplies the Node.js toolchain as of [v6.0.0](https://github.com/bazelbuild/rules_nodejs/releases/tag/v6.0.0-beta0).

Downstream canonical JavaScript + Node.js ruleset is now https://github.com/aspect-build/rules_js.
