### ISSUE TITLE
Always rebuilds despite no changes

### ISSUE THREAD

**Issue by evmar** [bazelbuild/rules_nodejs#1106]
# 🐞 bug report

### Affected Rule
ts_library

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
yes, not sure when regressed

### Description

 A clear and concise description of the problem...
In tsickle:
$ yarn run bazel build test:unit_test
always rebuilds the project

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
$ yarn run bazel version
yarn run v1.15.2
$ /home/evanm/projects/tsickle/node_modules/.bin/bazel version
Build label: 0.28.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 19 15:19:51 2019 (1563549591)
Build timestamp: 1563549591
Build timestamp as int: 1563549591
Done in 0.23s.
  </code>
</pre>

**Rules version (SHA):**

Not sure how to tell that
<pre>
  <code>

  </code>
</pre>

**Anything else relevant?**

```
$ yarn run bazel build --verbose_explanations --explain log test:unit_test
[...]
$ cat log
Build options: --experimental_allow_incremental_repository_updates --worker_sandboxing --verbose_explanations --explain=log
Executing action 'BazelWorkspaceStatusAction stable-status.txt': unconditional execution is requested.
Executing action 'Creating runfiles tree bazel-out/k8-fastbuild/bin/test/unit_test.sh.runfiles': Effective client environment has changed. Now using
  PATH=/tmp/yarn--1567812800468-0.10845596877819497:/home/evanm/projects/tsickle/node_modules/.bin:/home/evanm/.config/yarn/link/node_modules/.bin:/usr/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/bin/node_modules/npm/bin/node-gyp-bin:/home/evanm/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
.
Executing action 'Creating runfiles tree bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.runfiles [for host]': Effective client environment has changed. Now using
  PATH=/tmp/yarn--1567812800468-0.10845596877819497:/home/evanm/projects/tsickle/node_modules/.bin:/home/evanm/.config/yarn/link/node_modules/.bin:/usr/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/bin/node_modules/npm/bin/node-gyp-bin:/home/evanm/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
.
Executing action 'Compiling TypeScript (devmode) //src:src': Effective client environment has changed. Now using
  PATH=/tmp/yarn--1567812800468-0.10845596877819497:/home/evanm/projects/tsickle/node_modules/.bin:/home/evanm/.config/yarn/link/node_modules/.bin:/usr/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/bin/node_modules/npm/bin/node-gyp-bin:/home/evanm/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
.
Executing action 'Compiling TypeScript (devmode) //test:test_support': Effective client environment has changed. Now using
  PATH=/tmp/yarn--1567812800468-0.10845596877819497:/home/evanm/projects/tsickle/node_modules/.bin:/home/evanm/.config/yarn/link/node_modules/.bin:/usr/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/bin/node_modules/npm/bin/node-gyp-bin:/home/evanm/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
.
Executing action 'Compiling TypeScript (devmode) //test:unit_test_lib': Effective client environment has changed. Now using
  PATH=/tmp/yarn--1567812800468-0.10845596877819497:/home/evanm/projects/tsickle/node_modules/.bin:/home/evanm/.config/yarn/link/node_modules/.bin:/usr/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/bin/node_modules/npm/bin/node-gyp-bin:/home/evanm/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
.
```

**Comment by evmar** [comment]
This seems related to running under `yarn run bazel ...`

**Comment by a-ignatov-parc** [comment]
> This seems related to running under `yarn run bazel ...`

`yarn run` always add random `temp` dir in `$PATH` which results in bazel's cache invalidation. We end up running bazel with npm which don't do this.

**Comment by alexeagle** [comment]
Bazel's "strict action env" is the feature you need that prevents random environment variables from polluting the action key.

They had to turn it off as a default because of some regression, and haven't re-enabled, so you need it in the `.bazelrc`
https://github.com/angular/angular/blob/master/.bazelrc#L32-L33

**Comment by alexeagle** [comment]
I verified that a new workspace created with `npx @bazel/create` will have this option set, so I don't think there's anything more we can do
