### ISSUE TITLE
Allow to set max-old-space-size for rollup or set it to a higher value by default

### ISSUE THREAD

**Issue by dddent** [bazelbuild/rules_nodejs#1110]
Running rollup_bundle on large projects results in node running out of memory. Setting `templated_args = ["--node_options=--max-old-space-size=SOME_SIZE"]` for the rollup nodejs_binary can prevent that. I'd suggest either setting this to a higher value by default, or making it configurable from the rollup_bundle rule.

**Comment by alexeagle** [comment]
the `templated_args` applies to every execution of the binary, so we would need a different mechanism to allow the memory settings to be applied per-rule.

I think creating your own `nodejs_binary` to run rollup is the right solution for this. We already document that for `ts_library`: https://github.com/bazelbuild/rules_nodejs/blob/master/docs/TypeScript.md#customizing-the-typescript-compiler-binary
so I think we should document this for other rules as well

**Comment by dddent** [comment]
Makes sense, but as far as I can tell there is no attribute to set the rollup executable on the rollup_bundle rule.

**Comment by jfaust** [comment]
For anyone else who stumbles on this, `rollup_bundle` now takes a `rollup_bin` argument, so you can now do:
```
nodejs_binary(
    name = "rollup_bin",
    entry_point = "@npm//:node_modules/rollup/dist/bin/rollup",
    node_modules = "@npm//:node_modules",
    templated_args = ["--node_options=--max-old-space-size=<SOME_SIZE>"],
)

rollup_bundle(
    ...
    rollup_bin = ":rollup_bin",
)
```

**Comment by alexeagle** [comment]
I just ran across this myself at work - I'll add this snippet to the docs thanks @jfaust
