### ISSUE TITLE
all nodejs_binary programs should be protected from argv spilling over

### ISSUE THREAD

**Issue by devversion** [bazelbuild/rules_nodejs#1120]
# 🐞 bug report

### Affected Rule

`internal/rollup`.

### Is this a regression?

No

### Description

The exposed function for running rollup does not work on Windows if there
are too many arguments which are passed to rollup. This can happen if someone
specifies too many `globals` (as it happened within the `angular/components` repo).

Depending on what flags are getting through and the amount of characters which
are accidentally omitted from the arguments, this can either cause an exception to
be thrown, or a successful build which misses some flags.

### Proposed solution

There are two options:

* Use a parameter file for passing arguments to rollup
* Pass the specified globals as part of the rollup configuration (through substitution)

In my opinion, applying both options would be the most reasonable and robust solution.

## 🌍  Your Environment

**Operating System:**

Windows

**Comment by Toxicable** [comment]
I think a solution here might be writing the config to a file https://rollupjs.org/guide/en/#configuration-files then just using the cli arg to pass config file location

**Comment by devversion** [comment]
@Toxicable We already do write a config file. Just the globals are passed through the action arguments. Hence my proposal to pass the globals to the config through substitution

**Comment by Toxicable** [comment]
oh! my mistake, thought we were doing it all via the CLI, sounds good to me then!

**Comment by alexeagle** [comment]
I think the new rollup_bundle rule solves this by letting you pass your own config file, and you could put the globals and externals settings in there, right?

But we should maybe still use a paramsfile to spill these arguments. @soldair points out that if we keep the concept of a `loader.js` then we could always unpack the paramsfile into `process.argv` before we call the main.

**Comment by devversion** [comment]
@alexeagle I like that idea. Somehow I'm slightly concerned about too much magic though. Especially since the format of how the params file is passed to the action can vary based on the `args` configuration.

**Comment by devversion** [comment]
And yes. I think the new rollup bundle rule will solve this for us. Thanks Alex!
