### ISSUE TITLE
Document that TypeScript code must build with declarations enabled

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#1133]
Moved from 
https://github.com/angular/angular-bazel-example/issues/522#issuecomment-530985895
since that repo was archived.

@mikolaj-leszczynski asks "but I'm not getting this error when I'm building my app without Bazel, only using standard ng build with default architect. It's not a problem with my TS then , right ?"

You don't indicate if you had `declarations` enabled when compiling without Bazel?

**Comment by mikolaj-leszczynski** [comment]
@alexeagle , `declarations` are disabled.

**Comment by alexeagle** [comment]
You can't migrate to Bazel until your app builds with `declarations` enabled, that's what I was trying to say in the linked issue.

(the reason is that we avoid a cascading rebuild/re-type-check of the whole transitive dependency tree when implementation is changed but interface is not. that's a fundamental property we want to preserve under Bazel)

**Comment by mikolaj-leszczynski** [comment]
@alexeagle, it would be helpful then to have `declarations` set to `true` in the `angular-bazel-example`. Do you want me to create a PR for this ? 
Even when adding `declaration: true` to tsconfig.json I am still getting the same error.

**Comment by alexeagle** [comment]
I suppose we could add the `declaration: true` to the tsconfig.json in the example, but it doesn't matter. We always set that option when `ts_library` invokes `tsc` regardless of what appears in `tsconfig.json`. (run the build with `--subcommands` and you'll see it prints a path to a generated `my_target_tsconfig.json` where we override some settings)

I expect you'll get the error, and need to resolve it, before you can use `ts_library` to build that code.

**Comment by mikolaj-leszczynski** [comment]
Hmm, it is super misleading to me that ts_library override some of my tsconfig.json settings. It would be great to have it documented and told explicitly. Or am I missing something and it is already mentioned somewhere in the docs?

**Comment by alexeagle** [comment]
Yes its briefly mentioned
https://github.com/bazelbuild/rules_nodejs/blob/master/docs/TypeScript.md#tsconfig

We used to warn whenever ts_library overwrote one of your settings, but it was a terrible UX. Also in this case there would be no warning since we just add a setting that wasn't present in your file.

**Comment by mikolaj-leszczynski** [comment]
Thank you :) Even with `--subcommands` I'm not seeing the reason of my bug. Should my repo be somehow prepared for `declaration: true` ?

**Comment by alexeagle** [comment]
You can leave your code alone and build it with plain `tsc`: https://github.com/bazelbuild/rules_nodejs/blob/master/packages/typescript/docs/install.md#alternatives
of course there are tradeoffs with doing that

In that doc I say that `--declaration` is required for `ts_library` so I think that resolves this issue as best we can.
