### ISSUE TITLE
Errors when compiling modules in AOT mode with Bazel

### ISSUE THREAD

**Issue by mikolaj-leszczynski** [bazelbuild/rules_nodejs#1134]
### Description

In `angular-bazel-example` in app.module in `NgModule` decorator whenever I'm using StoreModule.forRoot(...) or JwtModule.forRoot(...) with some cofnig I'm getting these kind of errors:
```
Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler.
```

I'm not getting these errors when building the angular app without Bazel. I assume `ng build` does something under the hood with my code and then pass it to ngc. ng_module rule seems not to do those transformations hence the error.

**Comment by kylecordes** [comment]
Does `ng build` compile it without error when you enable AOT/production, with `--prod=true` (or one of the other ways of doing that)?

**Comment by mikolaj-leszczynski** [comment]
No error when running with `--prod`

**Comment by alexeagle** [comment]
How do we reproduce?

**Comment by mikolaj-leszczynski** [comment]
@alexeagle e.g. in `angular-bazel-example` repo
1. `yarn add @auth0/angular-jwt`
2. In `src/app` create e.g. `environment` directory with `environment.ts` and `BUILD.bazel`
3. In `envrionment.ts`:
```
export const environment = {
    okUrl: 'some/ok/url'
};
```
4. In `BUILD.bazel`:
```
package(default_visibility = ["//visibility:public"])
load("@npm_bazel_typescript//:defs.bzl", "ts_library")

ts_library(
    name = "environment",
    srcs = [
        "environment.ts",
    ],
    tsconfig = "//src:tsconfig.json",
)

```
5. In `app.module` add: 
```
import { JwtModule } from '@auth0/angular-jwt';
import {environment} from "./environment/environment";
```
and in `imports` array add:
```
    JwtModule.forRoot({
      config: {
        whitelistedDomains: [environment.okUrl],
      },
    }),
```
6. In `//src/app` target add two new targets to deps array:
```
        "//src/app/environment",
        "@npm//@auth0/angular-jwt",
```
7. Add `"node_modules/@auth0/**/*",` to `angular-metadat.tsconfig.json`
8. Run `bazel build //src/app`

**Comment by mikolaj-leszczynski** [comment]
@alexeagle I solved the problem but I still do not know what is the exact source of the error. 

Instead of using `config` in JwtMoudle `forRoot` I used the InjectionToken and I followed the steps from https://github.com/auth0/angular2-jwt from `Using a Custom Options Factory Function` section. 

Shouldn't both approaches work with Bazel? I will say it once more - using `ng build` with default angular architect compile this code successfuly both in prod and dev mode with no errors.

**Comment by alexeagle** [comment]
Thanks for the repro and for noting your workaround. Under Bazel, ngc runs a little differently, it finds ngsummary.json files.
@kyliau have any time to investigate?

**Comment by mikolaj-leszczynski** [comment]
@alexeagle can you give me any hint (files to start looking for, other repos) so I can also make my investigation?

**Comment by mikolaj-leszczynski** [comment]
@alexeagle ^^

**Comment by Serginho** [comment]
Same problem defining animations

```typescript
export const slideInHorizontal: AnimationReferenceMetadata = animation([
  style({transform: 'translate3D({{start}}, 0, 0)', opacity: 0}),
  animate('{{timing}}'),
]);
````

```typescript
@Component({
   ....,
  animations: [... useAnimation(slideInHorizontal, {params: {start: '100%', timing: '500ms ease'}}),
          {optional: true}) ]
});
```
