### ISSUE TITLE
CircleCI config.yml is both valid and invalid

### ISSUE THREAD

**Issue by kylecordes** [bazelbuild/rules_nodejs#1138]
This is a "appears to be a bug but somehow works anyway" report.

The current master CircleCI `config.yml`:

https://github.com/bazelbuild/rules_nodejs/blob/master/.circleci/config.yml

Contains two different entries at the top, used to define blocks for right later reuse, both under the key var_8. For reasons I cannot explain, when the repository is forked and the fork is attached to CircleCI, it detects this invalidity (duplicate keys) and refuses to run. Yet the CircleCI on **this** repository has been successfully running in spite of that problem for months.

(Wild guess: there's something interesting behind the scenes at CircleCI around backward compatibility to somehow make this work.)

In any event, this appears to be inadvertent, and at least in some sense a bug. It takes a trivial one line change on that file to fix it, if someone can confirm this is not crazy I will be happy to make the trivial PR.

**Comment by alexeagle** [comment]
Yeah, looks wrong to me. We are trying to move away from CircleCI in the long-term since Bazel team maintains the BuildKite instance so I'm fine patching this up without understanding why it's working when it shouldn't. Thanks @kylecordes !
