### ISSUE TITLE
Under --define=VERBOSE_LOGS=1, print the URLs where node/yarn were downloaded

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#1146]
maybe look around the repository rules for other things we ought to print in verbose mode, to help users file actionable issues

**Comment by alexeagle** [comment]
@Toxicable is considering contributing this

**Comment by Toxicable** [comment]
My idea here was to put something here: https://github.com/bazelbuild/rules_nodejs/blob/master/internal/node/node_repositories.bzl#L319 
Such as:
```
if ctx.var["COMPILATION_MODE"] == "dbg":
  print('using urls ${yarn_urls}')
```

But it would appear that a repository_ctx isn't able to read `--compilation_mode` https://bazelbuild.slack.com/archives/CDCMRLS23/p1575660548008100

Not sure where else you could do this.
