### ISSUE TITLE
How to build a nuxt.js app

### ISSUE THREAD

**Issue by albttx** [bazelbuild/rules_nodejs#1147]
Hello,

I can't manage to build a nuxt.js application.

running `yarn run build` create a dist/` directory for production.
- run yarn start will start the webserver (production mode)
- run yarn run dev start the webserver in dev mode

this is my BUILD file

```bzl

filegroup(
    name = "nuxt-srcs",
    srcs = glob(
        [
            "assets/**",
            "components/**/*.vue",
            "middleware/*.js",
            "pages/**/*.vue",
            "plugins/*.js",
            "static/*",
            "store/*.js",
        ],
        # specifically exclude test files
        exclude = [
        ],
    ),
)

filegroup(
    name = "package_json",
    srcs = glob(["package.json"]),
)

nodejs_binary(
    name = "app",
    data = [
        ":package_json",
        "nuxt.config.js",
        ":nuxt-srcs",
    ],
    entry_point = ".nuxt/index.js",
)
```

running: 

```sh
$ bazel build //webview:app
INFO: Analyzed target //webview:app (2 packages loaded, 37 targets configured).
INFO: Found 1 target...
Target //webview:app up-to-date:
  bazel-bin/webview/app_loader.js
  bazel-bin/webview/app.sh
INFO: Elapsed time: 4.063s, Critical Path: 3.70s
INFO: 0 processes.
INFO: Build completed successfully, 4 total actions
```

What should i do next ?

**Comment by Toxicable** [comment]
Running `bazel build //webview:app` where `//webview:app` is a `nodejs_binary` will only gather together the files to make your target ready to run, you'd need `bazel run //webview:app` to actually execute the program.

If you want `bazel build` to execute a program then you need to make your own rule which has an action that does the work, similar to how `terser_minified` works https://github.com/bazelbuild/rules_nodejs/blob/master/packages/terser/src/terser_minified.bzl#L149

**Comment by alexeagle** [comment]
@albttx could you point us to a nuxt.js example app, or send a PR adding yours under `examples/nuxt` in this repo, then it will be easier for us to wire up the example for you.
I think you're getting a bit confused between what yarn does and what Bazel does.
