### ISSUE TITLE
End support for node_modules attribute

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/rules_nodejs#1153]
We have limited test coverage for filegroup based node_modules and it may cause issues with upcoming module loading change and the linker.

For user-managed npm deps users should use node_module_library instead of filegroup in the future. We need to promote node_module_library to the public API for this.

**Comment by mattem** [comment]
[Done in 3.0.0](https://github.com/bazelbuild/rules_nodejs/wiki#removal-of-node_modules-attributes-on-rules)
