### ISSUE TITLE
Promote web_package to the public API

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/rules_nodejs#1155]

**Comment by alexeagle** [comment]
need to drop or move the diff loading html injection feature first

**Comment by alexeagle** [comment]
remove index_html attribute, remove injector.js and unwire it from the rule. already not depending on this ourselves

**Comment by alexeagle** [comment]
need to document that if you use `ts_devserver` you'll need two index.html files

**Comment by sahilprasad** [comment]
@alexeagle why are two index.html files needed?
