### ISSUE TITLE
[tracking] Docs for 1.0

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/rules_nodejs#1157]
Tracking issue for docs for 1.0 milestone

Some areas that need attention:

* Building from source (using //:index.from_src.bzl)
* Patching rules in npm packages
    * doc & example of how to use patch-package
* Changing npm repository to mirror
* Need one for install / how you get your deps
* Bring your own dev server (ts-devserver not doing what you want)
* Debugging / reporting
    * We should add note for users to re-run with `--define=VERBOSE_LOGS=1` in issue template
* install_bazel_dependencies (https://github.com/bazelbuild/rules_nodejs/issues/1118)

**Comment by alexeagle** [comment]
Building from source is still not documented but isn't a critical user journey for 1.0

External repos docs are now at https://bazelbuild.github.io/rules_nodejs/repositories.html

Patching is at https://github.com/bazelbuild/rules_nodejs/blob/291772622306b8d199139359e72c4fab341a91b7/docs/index.md#patching-the-npm-packages

Bring your own devserver - we don't have a working example of something other than ts_devserver working with the ibazel workflow for 1.0

issue template is updated

I think we have covered the bases here.
