### ISSUE TITLE
Handle peerDependencies a bit better.

### ISSUE THREAD

**Issue by bweston92** [bazelbuild/rules_nodejs#1162]
# 🚀 feature request

### Relevant Rules

- `yarn_install`
- `npm_install`

### Description

Currently creating a React without using TypeScript will require adding many peer dependencies that React has for TypeScript even though it is not used at all however Bazel will fail the install.

### Describe the solution you'd like

Either have some sort of `ignoreDepedencies` in `package.json` which are read and will no longer fail, this will mean you've acknowledged and are ok with these dependencies being ignored.

Or we can just not hard fail at all on peer dependencies assuming the developer knows best.

### Describe alternatives you've considered

You have to add peer dependencies of all packages and sub packages that have them as dependencies in your own `package.json`

**Comment by alexeagle** [comment]
Latest release no longer errors when peerDeps are missing
