### ISSUE TITLE
don't have both e2e/webapp and examples/webapp

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#1167]

**Comment by gregmagolan** [comment]
No longer in scope for rules_nodejs which only supplies the Node.js toolchain as of [v6.0.0](https://github.com/bazelbuild/rules_nodejs/releases/tag/v6.0.0-beta0).

Downstream canonical JavaScript + Node.js ruleset is now https://github.com/aspect-build/rules_js.
