### ISSUE TITLE
run terser in parallel with worker_threads

### ISSUE THREAD

**Issue by Toxicable** [bazelbuild/rules_nodejs#1177]
@bazel/terser can be run with worker_threads when working on a directory.
This should net us some small performance gains since we don't need to spin up a whole new process for each chunk.
Instead we can use a pool of persistant worker threads.

**Comment by gregmagolan** [comment]
No longer in scope for rules_nodejs which only supplies the Node.js toolchain as of [v6.0.0](https://github.com/bazelbuild/rules_nodejs/releases/tag/v6.0.0-beta0).

Downstream canonical JavaScript + Node.js ruleset is now https://github.com/aspect-build/rules_js.
