### ISSUE TITLE
demo minifying app with closure (adv mode) instead of terser

### ISSUE THREAD

**Issue by Toxicable** [bazelbuild/rules_nodejs#1179]
Since closure is pretty difficult to integrate into current build pipelines I think this would be a good opportunity to show off how we can minifiy with closure instead of terser.
I know there's some work to be done here in terms of tsickle.
Would be good to list of out the steps needed on this.

**Comment by ashi009** [comment]
Just a random thought. Is it even feasible with all kinds of weird npm packages around?

**Comment by alexeagle** [comment]
Closure compiler doesn't work with most npm packages, that is true, but that issue doesn't belong here. Our job should just be to call closure compiler and not introduce any bazel-specific bugs or limitations.
