### ISSUE TITLE
npm_umd_bundle issues

### ISSUE THREAD

**Issue by eachirei** [bazelbuild/rules_nodejs#1188]
Hello!
I'm trying to migrate a ~200 components Angular project to bazel. After restructuring most of my project I found that there were still issues with the external libraries.
I got the "anonymous define()..." error, so I started digging and I've come to the conclusion that I should use npm_umd_bundle.
I have used the "short" version, by specifying "@npm//trouble-package:trouble-package.umd.js" in ts_devserver, but I'm still encountering the same error. 
Trying to move on, I skipped those dependencies to find out that most of my other dependencies have issues as well, but this time just a script error about not finding the file in the console of the browser. I tried the same trick with those (the umd thing) and it threw an error on build about some missing file. I dug deeper into that module, and noticed that the file is actually missing, but now I don't understand how that module works in the no-bazel build.
So in the end, my question is: should I keep trying to migrate to bazel or should I wait till the system is mature for Angular?

**Comment by Toxicable** [comment]
A bit of background: The reason why we use UMD/AMD based modules in dev mode is because that's the only module that our dev server supports.
The reason for this is that all the dev server does is concats them altogether, something you can only do with AMD.
The result is that it's super fast and scales really well.

There's been a bit of conversation around allowing a slower but more compatible dev server at some point, but that wont be till we're at least 1.0, meaning towards the end of Q4.
@josephperrott

So for now if you want to continue forward with bazel, the best thing you can do is to provide us with examples of broken packages.
What we can do with this is maybe look at our rules that produce UMD's and make a fix if there's a bug or maybe we push back at those npm deps and get them to fix it at the source.

**Comment by eachirei** [comment]
Thanks for the fast response!
This is one of the packages with problems: https://www.npmjs.com/package/ngx-mqt.
If I just import it I get the anonymous define error. If I try to umd it, it complains that it's missing a store file, referenced in vendor/mqtt.js.

**Comment by alexeagle** [comment]
https://unpkg.com/browse/ngx-mqtt@6.12.0/vendor/ 
shows that `mqtt.min.js` is the only file distributed in that directory, but it contains 
`var Store=require("./store");`
so this seems to be a broken package.

I guess the real question here is why you didn't get an error when using this package outside of Bazel?

**Comment by alexeagle** [comment]
the general answer here is we should stop being different - if you're not a high-requirements user with a large number of js inputs, you probably don't care that our `ts_devserver` has such great performance thanks to concatjs

https://github.com/angular/components/pull/16937/files shows one way to write your own devserver that interops nicely with `ibazel`

I think we need a more general way to run an existing popular devserver.

**Comment by Toxicable** [comment]
Ok so I think the long term answer here is for us to ship two dev servers
1 - highly compatible but not as scalable
2 - only AMD compatible but highly scalable

If you're good with that @alexeagle ill put together an issue describing some requirements?
This would be a post 1.0 feature I think

**Comment by eachirei** [comment]
So about the broken package, from what I debugged, I don't think that module actually uses the code that requires the store file. I'll try to use the dev_server you mentioned above and come back with the results. Thanks!

**Comment by filipesilva** [comment]
@alexeagle although `var Store=require("./store")` looks like a broken import, within that file this is also found:
```
,{"./store":6,"./validations":7,_process:92,"end-of-stream":17,events:78,inherits:80,"mqtt-packet":85,"readable-stream":106,reinterval:107,xtend:120}
```
later followed by
```
6:[function(require,module,exports){(function(process){"use strict";var xtend=require("xtend");var Readable=require("readable-stream").Readable;var streamsOpts={objectMode:true};var defaultStoreOptions={clean:true};var Map=require("es6-map");function Store(options){if(!(this instanceof Store)){return new Store(options)}
// ...
```

This seems to be an encoding saying that in this particular format the `./store` import is found at the key `6` of a map. So it is there. It's mostly a matter of interop I think? When this UMD is loaded it might not be playing well with other UMD definitions and manifests.

If that's the case it's not about the server per se but about the bundling step and it's interop facilities. Concatenating might not be enough.

**Comment by eachirei** [comment]
Ok, so I've tried to follow your example @alexeagle.
After fumbling a bit with the paths to the server binary, I managed to start it up. I couldn't configure the assets folder, but trying to move on I got into another rabbit hole with system.js and that whole new configuration system.
So, I've noticed the scripts aren't auto injected in index.html and I'm supposed to configure the system-config.js file by hand(this doesn't seem very feasible, but I can go on with it just to see the app starting for once). But I think the example you have is based on an older version of system.js as initially I was getting an System.config is not a function error and now it can't fetch main.js (404).
It is a bit frustrating to follow all the file mappings (the devserver launcher required some location to find the binary; and I don't even know the real folder from which it's actually serving the files).
How should I proceed?
P. S. I have no experience with system.js.

**Comment by kylecordes** [comment]
Here's an alternative approach to think about - maybe useful, maybe not.

As I understand the challenge here is the loose set of practices around how code is shipped in an NPM package. Of course the Angular team produces a fantastically coherent and well organized set of files in each package they ship… but many projects out there, especially ones that are been around a long time, have a bespoke bundling apparatus, so we get a wide variety of NPM package output to consume.

Any popular bundling tool (for dev or prod) must deal with what is out there and somehow produce working results. In practice this means slogging through numerous edge cases and rough parts until there is enough heuristic floating around in the tool to make most packages work.

Here's the most important part. Once somebody else did that work, most likely just a little flip of a switch at the end to produce UMD/AMD at the end (with a known/sane name inside the bundle) likely produces what is needed here.

Therefore, the idea:

* Borrow From Angular CLI, the config it passes to webpack to get things to come out correctly.
* Make the minimum change to make that configuration instead emit a workable UMD/AMD for a given package.
* Have this available as a fallback path to produce a UMD/AMD that could be passed to the existing dev server and all of the existing ways.

The user experience might be something like this: if things fails with the NPM package X, add a line of config somewhere that says "bundle up package X with webpack instead”. It should work most of the time.

**Comment by alexeagle** [comment]
We should have something that works all the time. If you were able to load `ng serve` we should do exactly the same thing under Bazel. Anything else will prevent us making Bazel the default later.

Yesterday I played with it. There are other nice devservers like John Papa's lite-server but they don't have the magic to read every known npm package and transpile the module format.

webpack-dev-server is really heavy as it requires webpack and webpack-cli for some reason, but it's probably the right dev server to use for compatibility.

**Comment by eachirei** [comment]
Question: can I just use the old and non-Bazel dev server for development and use Bazel just for production builds?
I mean, this is actually the main reason I wanted to switch to Bazel: 10 minutes production build time. I know that the build systems would be different and I accept that risk. But this would give me the best of both worlds: faster build time and no more hassle with the dev_server.
The question is, how do I tackle lazy loading?
[routing.module.ts](https://github.com/bazelbuild/rules_nodejs/blob/master/examples/angular/src/app/app-routing.module.ts) - here you reference some script that autogenerates routes. What's that about?

**Comment by eachirei** [comment]
Nvm, still doesn't work: some external packages have imports written with `import * as x from 'x'` syntax so rollup fails...

**Comment by kylecordes** [comment]
@alexeagle  Ah, yes, of course. Fallback  settings and options would be more complexity for users - no good.

Here's another variation / idea:

For development builds, use webpack to bundle the external dependencies as AMD/UMD. It is likely to do so with the same success that it currently delivers in the webpack-devserver is used by Angular CLI.

Thus the change would only be to substitute out a piece in the middle (how external dependency code is gathered), keeping the rest of the (scalable, fast, efficient) ts-devserver workflow in place.

I wonder if this might be less work (and/or more scalable) than moving totally to webpack-devserver.

**Comment by alexeagle** [comment]
@kylecordes I suppose you could do that but it seems like such an optimization could live completely in the webpack and webpack-dev-server and we don't need to think too hard about it in Bazel.

@eachirei sure, you can run your same devserver as before. You could have Bazel build its inputs so you still have a single build. But you'll have to understand how the build was getting its artifacts into the devserver, and you lose ibazel support.

The next release has a better rollup_bundle rule which I suspect will let you fix issues like the import syntax.

**Comment by Toxicable** [comment]
What about a dev server that's similar to the material one except it runs rollup in watch mode to do the bundling.
This has a lot of advantages
- It'll be fast (not as fast as `ts_devserver` though)
- It means that dev and prod builds will be consistant
- not custom bundling
- highly compatiable with module formats (with right plugins) (you'd probably want to share config between prod and dev builds)

**Comment by alexeagle** [comment]
There's already a rollup plugin for serving. Our job should just be to hook up the watch mode to ibazel, not to write another devserver. We are maintaining too many of them already :)

**Comment by Toxicable** [comment]
Right, fair point, in that case looking at the usage here: https://www.npmjs.com/package/rollup-plugin-serve
The dev server would be a very simple `nodejs_binary` that just calls the serve function like that.
I could put in a PR to add this... if it actually works the way we want? or is that too simple to add as a rule/package to rules_nodejs?

**Comment by Toxicable** [comment]
I've opened up https://github.com/bazelbuild/rules_nodejs/issues/1209 
and would advise any further discussion around our dev servers to go there.
bringing this issue back on the top of issues with the UMD bundles.
