### ISSUE TITLE
Node Linux installation 404s

### ISSUE THREAD

**Issue by connorjclark** [bazelbuild/rules_nodejs#1190]
# 🐞 bug report

### Is this a regression?

idk

### Description

```
WARNING: Download from https://mirror.bazel.build/nodejs.org/dist/v10.16.0/node-v10.16.0-linux-x64.tar.xz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
```

https://mirror.bazel.build/nodejs.org/dist/v10.16.0/node-v10.16.0-linux-x64.tar.xz is a 404.

https://github.com/bazelbuild/rules_nodejs/blob/7e3e6be38e1cf3c6c99d8dc8829377a2beacbb53/internal/node/node_repositories.bzl#L79

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux, running via RBE in GCP
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
bazel 0.29.1
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>

  </code>
</pre>

**Anything else relevant?**

**Comment by robinp** [comment]
Occurs here. Fetching manually the nodejs url seems the file is present.

**Comment by robinp** [comment]
Note: can use 

```
node_repositories(
    package_json = ["//:package.json"],
    node_version = "10.16.0",
    node_urls = [
        "https://nodejs.org/dist/v{version}/{filename}",
    ],
)
```
to override the urls used to fetch nodejs binaries. See https://bazelbuild.github.io/rules_nodejs/Built-ins.html.

**Comment by alexeagle** [comment]
Got my setup for mirroring fixed and ran
```
$ bazel-mirror https://nodejs.org/dist/v10.16.0/node-v10.16.0-win-x64.zip
$ bazel-mirror https://nodejs.org/dist/v10.16.0/node-v10.16.0-darwin-x64.tar.gz
$ bazel-mirror https://nodejs.org/dist/v10.16.0/node-v10.16.0-linux-x64.tar.xz
```
