### ISSUE TITLE
Install source-map-support for all nodejs binary/test executions

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#120]
Currently we do this in the jasmine runner:
https://github.com/bazelbuild/rules_nodejs/blob/master/internal/jasmine_runner.js#L5

@mhevery points out there's nothing jasmine-specific about this behavior - any node binary might have been produced from some compile-to-JS language, so we should just always do this.

The tricky part will be providing the source-map-support dependency always...

**Comment by mhevery** [comment]
Perhaps we could make it autodetect? If dep present use it, otherwise nothing?

**Comment by alexeagle** [comment]
Fixed in https://github.com/bazelbuild/rules_nodejs/pull/121
