### ISSUE TITLE
Hybrid apps (Copy dist (angular statics and js) into apk)

### ISSUE THREAD

**Issue by salim-boudriiya** [bazelbuild/rules_nodejs#1241]
Hi @alexeagle,

I wanted to ask you, if the angular rules with bazel have the possibility of copying / converting the output file to / in an android application in the case of hybrid applications.

Best regards

**Comment by alexeagle** [comment]
Generally speaking, sure you can do that. Take a look at https://www.nativescript.org/blog/building-nativescript-apps-with-google-bazel for some background. The `android_*` rules can depend on the output of typescript/Angular rules.

**Comment by salim-boudriiya** [comment]
Thank you for your response.
I will try to make a test project.
Best regards
