### ISSUE TITLE
New rollup_bundle not working with Angular ViewEngine

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/rules_nodejs#1249]
Two issues with the generated .ngfactory/.ngsummary ViewEngine files create problems with the new rollup bundle.

1) Some of the requires in those generated files have `external/` in their paths. I think I can work around this with some rollup.config code that fixes these import paths

2) I ran into a flake where rollup complained that `default is not exported` from the commonjs named-AMD generated `.ngfactory/.ngsummary` files. I'll need to debug this. One possible resolution is to generate esm files in the ngc postinstall step and then use babel to transform them to named-UMD which is required for ts_devserver.

**Comment by alexeagle** [comment]
fixed by #1252
