### ISSUE TITLE
rollup_bundle does not see external dependencies

### ISSUE THREAD

**Issue by mikolaj-leszczynski** [bazelbuild/rules_nodejs#1254]
### Affected Rule

The issue is caused by the rule: rollup_bundle (the old one, did not check if new one also fails)

### Description

In one of my `ng_modules` I have `@npm//lodash` in its `deps` array. When building this  `ng_module` everything works fine - no compile error. The last and the biggest `ng_module` also compiles with no error. However, when trying to run the `rollup_bundle` rule I'm getting the build error: 
```
Use --sandbox_debug to see verbose messages from the sandbox
[!] Error: 'isNull' is not exported by bazel-out/k8-fastbuild/bin/src/bundle.es6/external/npm/node_modules/lodash/lodash.js
https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-
bazel-out/k8-fastbuild/bin/src/bundle.es6/src/app/...

```
## 🔬 Minimal Reproduction

Just add lodash to the angular-bazel-example and try bundling the app with the old `rollup_bundle`. This is my `rollup_bundle`:
```
rollup_bundle(
    name = "bundle",
    entry_point = "main.prod.ts",
    deps = [
        "//src",
        "@npm//@angular/common",
        "@npm//@angular/core",
        "@npm//@angular/material",
        "@npm//@angular/platform-browser",
        "@npm//@angular/router",
        "@npm//@auth0/angular-jwt",
        "@npm//@ngrx/store",
        "@npm//rxjs",
    ],
)
```
where `//src` is my final `ng_module` which embrace the entire angular app

**Comment by jbedard** [comment]
Does adding lodash to the `rollup_bundle(deps)` fix it?

I assume this is https://github.com/bazelbuild/rules_nodejs/issues/1074 ?

**Comment by mikolaj-leszczynski** [comment]
It does not help : ( @alexeagle  ?

**Comment by alexeagle** [comment]
I assume there is something about our hard-coded rollup.config.js that makes the https://unpkg.com/lodash@4.17.15/lodash.js file not appear to export symbols.
And the new rollup_bundle rule is 100% ready now, we are about to deprecate the old one, and you now get complete control over the rollup.config
So if lodash works with rollup, it should do so under Bazel as well.
So I think we'll close this soon. see https://github.com/bazelbuild/rules_nodejs/wiki#migrating-off-internalrollup

**Comment by mikolaj-leszczynski** [comment]
@alexeagle thanks for the response. I will migrate to newest rollup_bundle and check if this error is still there.

**Comment by alexeagle** [comment]
great thanks, please report new issue if it's still a bug
