### ISSUE TITLE
cannot include extensionless files with included_files

### ISSUE THREAD

**Issue by Toxicable** [bazelbuild/rules_nodejs#1257]
If you specify `included_files`, it will exclude files without extensions, meaning that you cannot include files such as binary entry points.

**Comment by gregmagolan** [comment]
You should be able to add a "" to the list of included_files for that. It's in the docstring:
```
An empty string in the list is a special
string that denotes that files with no extensions such as `README` should
be included in the package targets.
```

**Comment by Toxicable** [comment]
ah! sorry, missed that, thanks
