### ISSUE TITLE
typescript: unexpected type definition output when referencing third-party types

### ISSUE THREAD

**Issue by devversion** [bazelbuild/rules_nodejs#1265]
# 🐞 bug report

### Affected Rule

ts_library

### Is this a regression?

No

### Description

Consider you have a TypeScript compilation unit where you rely on
global symbols from a `@types/` package. Let's use `@types/youtube` for now.

We now have a source file in our compilation unit that declares a public function which
uses a symbol from the `@types/youtube` package in its function signature.

The generated `d.ts` output will be in Bazel:

```ts
export declare function hello(instance: Youtube): void;
```

while it should actually be:

```ts
/// <reference types="youtube" />
export declare function hello(instance: Youtube): void;
```

Notice the triple-slash directive in the expected type definition file. This is necessary to ensure that the type definition is actually correctly resolving the global `Youtube` type. This seems to be the expected behavior in TypeScript: https://github.com/Microsoft/TypeScript/issues/11634#issuecomment-253944200

**The problem**:

The problem is that Bazel uses a different way of loading types into a compilation unit. Usually in TypeScript, the needed types are added to the `compilerOptions#types` option. e.g.

```json
"compilerOptions": {
  "types": ["youtube"]
}
```

Unfortunately it's slightly different in `ts_library` because the types are loaded like actual input files. e.g.

```
"files": [
      "../../../../../external/npm/node_modules/@types/youtube/index.d.ts",
]
```

This causes different type definition output and makes the type definition more difficult to use outside of compilation units that have the youtube types set up as input.

**Comment by alexeagle** [comment]
We tried to move types to the program inputs to match google3 and make the strict dependencies check work. Evidently we should go back to being closer to typescript.
