### ISSUE TITLE
uncaught error in linker

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/rules_nodejs#1278]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 

`rollup_bundle`

### Is this a regression?

Not sure

### Description

 A clear and concise description of the problem...
In case the build depends on a module that has more than 2 segment name (See #1261), linker throws, but exit with zero. Hence, the build will succeed but generate bad code.

## 🔬 Minimal Reproduction

N/A

## 🔥 Exception or Error

<pre><code>
$ bazel build ecnova/www/frontend:bundle
INFO: Analyzed target //ecnova/www/frontend:bundle (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
INFO: From Bundling JavaScript ecnova/www/frontend/bundle.js [rollup]:
(node:49238) ExperimentalWarning: The fs.promises API is experimental
(node:49238) UnhandledPromiseRejectionWarning: Error: module xrc/ecnova/common/frontend/runtimeconfig/store has more than 2 segments which is not a valid node module name
    at /private/var/tmp/_bazel_xiaoyi/2258f168242f85dcc9f2c0d3e9d2258a/external/build_bazel_rules_nodejs/internal/linker/index.js:272:27
    at Generator.next (<anonymous>)
    at fulfilled (/private/var/tmp/_bazel_xiaoyi/2258f168242f85dcc9f2c0d3e9d2258a/external/build_bazel_rules_nodejs/internal/linker/index.js:3:58)
(node:49238) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:49238) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

bazel-out/darwin-fastbuild/bin/ecnova/www/frontend/index.mjs → bazel-out/darwin-fastbuild/bin/ecnova/www/frontend/bundle.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
xrc/ecnova/common/frontend/googleanalytics (imported by bazel-out/darwin-fastbuild/bin/ecnova/www/frontend/index.mjs)
xrc/ecnova/common/frontend/navigator (imported by bazel-out/darwin-fastbuild/bin/ecnova/www/frontend/index.mjs)
xrc/ecnova/www/frontend/app/loader (imported by bazel-out/darwin-fastbuild/bin/ecnova/www/frontend/index.mjs)
react (imported by bazel-out/darwin-fastbuild/bin/ecnova/www/frontend/index.mjs)
react-dom (imported by bazel-out/darwin-fastbuild/bin/ecnova/www/frontend/index.mjs)
created bazel-out/darwin-fastbuild/bin/ecnova/www/frontend/bundle.js in 29ms
Target //ecnova/www/frontend:bundle up-to-date:
  bazel-bin/ecnova/www/frontend/bundle.js
INFO: Elapsed time: 106.641s, Critical Path: 32.73s
INFO: 366 processes: 305 darwin-sandbox, 61 worker.
INFO: Build completed successfully, 440 total actions
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS 10.15 (19A583)
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
$ bazel version
Build label: 0.27.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jun 17 13:03:58 2019 (1560776638)
Build timestamp: 1560776638
Build timestamp as int: 1560776638
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>
urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/0.38.3/rules_nodejs-0.38.3.tar.gz"],
        sha256 = "ad4be2c6f40f5af70c7edf294955f9d9a0222c8e2756109731b25f79ea2ccea0",
  </code>
</pre>

**Anything else relevant?**

**Comment by gregmagolan** [comment]
Thanks for the detailed info. I'll post a fix for this today.
