### ISSUE TITLE
Updating to 0.38.2 causes errors with missing files.

### ISSUE THREAD

**Issue by igilham** [bazelbuild/rules_nodejs#1279]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: Probably `ts_library` but I'm not certain.

### Is this a regression?

Yes, the previous version in which this bug was not present was: 0.38.1

### Description

Since upgrading to 0.38.2, there seems to be a problem with missing files in the dependencies. Something in `npm_bazel_typescript/internal/build_defs.bzl`is looking for `@build_bazel_rules_nodejs//internal/common:node_module_info.bzl`, but it does not exist in this release (or the combination of this release and the dependency tree I have in my project).

## 🔬 Minimal Reproduction

[See this PR](https://github.com/igilham/bazel-example/pull/9) for the change in my example repo.

## 🔥 Exception or Error

<pre><code>
ERROR: error loading package '': in /github/home/.cache/bazel/_bazel_root/3ef6b2ad9cc100f006a5d4a7217ff063/external/npm_bazel_typescript/index.bzl: in /github/home/.cache/bazel/_bazel_root/3ef6b2ad9cc100f006a5d4a7217ff063/external/npm_bazel_typescript/internal/build_defs.bzl: Unable to load file '@build_bazel_rules_nodejs//internal/common:node_module_info.bzl': file doesn't exist
ERROR: error loading package '': in /github/home/.cache/bazel/_bazel_root/3ef6b2ad9cc100f006a5d4a7217ff063/external/npm_bazel_typescript/index.bzl: in /github/home/.cache/bazel/_bazel_root/3ef6b2ad9cc100f006a5d4a7217ff063/external/npm_bazel_typescript/internal/build_defs.bzl: Unable to load file '@build_bazel_rules_nodejs//internal/common:node_module_info.bzl': file doesn't exist
</code></pre>

[See the build output](https://github.com/igilham/bazel-example/pull/9/checks?check_run_id=264304337).

## 🌍  Your Environment

2 environments:

* MacOS 10.14.6 running Bazel 1.0.0-homebrew
* Docker image `openjdk:8` running Bazel 0.29.0 (in the PR link)

**Rules version:** 0.38.2

**Anything else relevant?**

The work-around from the release notes of upgrading all dependencies with `yarn upgrade --scope @bazel` did not help.

**Comment by gregmagolan** [comment]
Looks like you have a version skew between the

    "@bazel/jasmine": "^0.37.0",
    "@bazel/typescript": "^0.37.0",
in your package.json and the version of build_bazel_rules_nodejs in your WORKSPACE. These two should match for at least the minor version right now (with semver minor versions are breaking changes when the version is 0.x.x).

Updating to

    "@bazel/jasmine": "^0.38.2",
    "@bazel/typescript": "^0.38.2",
should fix your issue.

**Comment by igilham** [comment]
Thanks for the help, @gregmagolan. That gets a little further. New errors:

```
ERROR: /github/home/.cache/bazel/_bazel_root/3ef6b2ad9cc100f006a5d4a7217ff063/external/npm_bazel_typescript/internal/devserver/ts_devserver.bzl:17:1: file '@build_bazel_rules_nodejs//:providers.bzl' does not contain symbol 'NpmPackageInfo'
ERROR: /github/home/.cache/bazel/_bazel_root/3ef6b2ad9cc100f006a5d4a7217ff063/external/npm_bazel_typescript/internal/devserver/ts_devserver.bzl:205:24: Traceback (most recent call last):
	File "/github/home/.cache/bazel/_bazel_root/3ef6b2ad9cc100f006a5d4a7217ff063/external/npm_bazel_typescript/internal/devserver/ts_devserver.bzl", line 147
		rule(implementation = _ts_devserver, at..."))}, <2 more arguments>)
	File "/github/home/.cache/bazel/_bazel_root/3ef6b2ad9cc100f006a5d4a7217ff063/external/npm_bazel_typescript/internal/devserver/ts_devserver.bzl", line 202, in rule
		attr.label_list(doc = "Targets that produce Java...", <2 more arguments>)
	File "/github/home/.cache/bazel/_bazel_root/3ef6b2ad9cc100f006a5d4a7217ff063/external/npm_bazel_typescript/internal/devserver/ts_devserver.bzl", line 205, in attr.label_list
		node_modules_aspect
global variable 'node_modules_aspect' is referenced before assignment.
ERROR: error loading package '': in /github/home/.cache/bazel/_bazel_root/3ef6b2ad9cc100f006a5d4a7217ff063/external/npm_bazel_typescript/index.bzl: Extension file 'internal/devserver/ts_devserver.bzl' has errors
ERROR: error loading package '': in /github/home/.cache/bazel/_bazel_root/3ef6b2ad9cc100f006a5d4a7217ff063/external/npm_bazel_typescript/index.bzl: Extension file 'internal/devserver/ts_devserver.bzl' has errors
```

I've noticed your issue to improve error messages. It may also be worth improving the release notes to make sure the migration guidelines are correct.

**Comment by gregmagolan** [comment]
That new error looks like a version skew as well between @bazel/typescript 0.38.3 and build_bazel_rules_nodejs 0.38.2. Looks like we should stay on the safe side and do minor releases if there is a chance of version skew right now as we're making quite a few changes so we can reach a clean stable API for 1.0 which we're planning to release in a month.

If you update to 0.38.3 in both your package.json and your WORKSPACE that will fix that issue.

```
"@bazel/jasmine": "~0.38.3",
"@bazel/typescript": "~0.38.3",
```

```
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "ad4be2c6f40f5af70c7edf294955f9d9a0222c8e2756109731b25f79ea2ccea0",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/0.38.3/rules_nodejs-0.38.3.tar.gz"],
)
```

I'll make a note in the release notes. Thanks!

**Comment by igilham** [comment]
It looks like that has fixed it. Thanks for your help.

**Comment by alexeagle** [comment]
Sorry about this - we are trying to be better about having upgrade instructions tell you to keep WORKSPACE and package.json in sync

**Comment by httpete** [comment]
I had to purge my ~/.cache/bazel directory and it seems to fly.
