### ISSUE TITLE
Better error message when package.json and WORKSPACE versions skew

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/rules_nodejs#1280]
Could use a better error message with the resolution path when the versions of @bazel/foobar packages that are published from this repo skew from the version of build_bazel_rules_nodejs in a WORKSPACE file.

Currently, the error message will be random depending on the failure mode. For example #1279.

**Comment by Toxicable** [comment]
Main issue for implementation is "How do @bazel/* packages get the version of build_bazel_rules_nodejs"

My though is to add `environment` to here https://github.com/bazelbuild/rules_nodejs/blob/master/internal/npm_install/npm_install.bzl#L362 
Which when the @bazel/* packages run they'll have access to, then they can just check their package versions against the environmental one
