### ISSUE TITLE
Docs site search not working

### ISSUE THREAD

**Issue by pshields** [bazelbuild/rules_nodejs#1282]
# 🐞 bug report

### Affected Rule

Not a rule, it's a documentation bug.

### Is this a regression?

Not sure.

### Description

The search box on the docs site doesn't work.

## 🔬 Minimal Reproduction

1. Visit https://bazelbuild.github.io/rules_nodejs/
2. Type in any search term, such as "ts_library" or "abc"
3. Press Enter
4. See 404 "Page not found" error

## 🔥 Exception or Error

After pressing enter, I was directed to https://bazelbuild.github.io/rules_nodejs/search.html?cx=008327220137350982602%3A0mpaowwcmvg&cof=FORID%3A10&ie=UTF-8&q=abc, which showed the error:

<pre><code>404
File not found

The site configured at this address does not contain the requested file.</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>Windows / Chrome</code>
</pre>

**Anything else relevant?**

It looks like a `search.html` page is missing. I looked through the repo history for a few minutes but wasn't able to figure out the issue.

**Comment by alexeagle** [comment]
I borrowed the layout of the docsite from some other rules but didn't even test the search box. Sorry, sloppy job! I guess we should just remove it - you can search the repo since the GH pages site is just a mirror of the docs/ folder with some extra styling
