### ISSUE TITLE
Delpoy single Angular module

### ISSUE THREAD

**Issue by dhondiramjawade** [bazelbuild/rules_nodejs#1289]
Feature Request.

Is there any way to deploy a single angular module?.
Actually I haven't understood bazel output.   
It create dist/bin/src/app/ ......  module structure and dist/bin/src/prodapp/ 
i think build is served from dist/bin/src/prodapp/ folder.  if i separately build a specified module then-new change will reflect in dist/bin/src/app/  but not in dist/bin/src/prodapp/.

it would be great if we build an app using bazle then the output of each module will be in the respective folder. like all bundles related to the billing module will be in dist---/billing/ folder.
so that I can replace the billing folder from the server with new one.

@bazel-io

**Comment by alexeagle** [comment]
I'm not sure what you're asking for. Whatever you ask Bazel to build, it will do and print the resulting path in the dist folder. If you want it to produce `dist/bin/src/prodapp/` then you need to `bazel build src:prodapp` probably.

**Comment by dhondiramjawade** [comment]
I want to build separate bundle each module. If we have billing module then respective bundle will be billing.bundle.js .
Is this possible with bazel ?

**Comment by dhondiramjawade** [comment]
I think what i asking is not possible with @Angular , because it has different building Mechanism because of **Webpack** and **rollup**.

Webpack and rollup is generating single bundle for whole app. but what we want is to generate single bundle for each module and load then on request. so that for next deployment we build only modified modules and replace it with old one.
