### ISSUE TITLE
rules_typescript update breaks new builds due to from_src.bzl

### ISSUE THREAD

**Issue by yoonjesung** [bazelbuild/rules_nodejs#1300]
# 🐞 bug report

```
every rule of type nodejs_binary implicitly depends upon the target
'@build_bazel_rules_nodejs//internal/linker:index.js',
but this target could not be found because of: error loading package
'@build_bazel_rules_nodejs//internal/linker': Unable to load file
'@npm_bazel_typescript//:index.from_src.bzl': file doesn't exist
```

Current version of @bazel/typescript (0.39.0) has no reference to the from_src.bzl target, so builds subsequently fail.

## 🌍  Your Environment

**Output of `bazel version`:**

`Build label: 0.29.1`

**Comment by alexeagle** [comment]
curious why you closed it? if someone else runs into the same problem they'll want to know how to resolve it.

**Comment by yoonjesung** [comment]
@alexeagle -- I initially thought this issue was due to the recent upgrade to v0.39.0, but after doing more digging it seems that this persists even when downgrading to previous versions. So I've closed for now until I can investigate more what's causing a reference to the source.
