### ISSUE TITLE
Address --incompatible_restrict_string_escapes errors

### ISSUE THREAD

**Issue by mmikitka** [bazelbuild/rules_nodejs#1301]
### Affected Rule
/build_bazel_rules_nodejs/internal/node/node.bzl

### Is this a regression?
No. Compatibility with latest Bazel version.

### Description
I'm seeing the following errors
```
external/build_bazel_rules_nodejs/internal/node/node.bzl:86:45: invalid escape sequence: \/. You can enable unknown escape sequences by passing the flag --incompatible_restrict_string_escapes=false
```
## Minimal Reproduction

```
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "26c39450ce2d825abee5583a43733863098ed29d3cbaebf084ebaca59a21a1c8",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/0.39.0/rules_nodejs-0.39.0.tar.gz"],
)
```
```
$ bazel version
Build label: 1.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Oct 21 08:44:00 2019 (1571647440)
Build timestamp: 1571647440
Build timestamp as int: 1571647440
```

## Exception or Error
See above

## Your Environment
See above

**Comment by alexeagle** [comment]
Hmm, it reads `escaped = mn.replace("/", "\/").replace(".", "\.")`
I guess this means the line is currently a no-op because the backslashes are treated as escape characters. So it should either be `replace("/", "\\/")` to restore the developers intent or just remove the line to preserve current semantics.

**Comment by mattem** [comment]
This was addressed in https://github.com/bazelbuild/rules_nodejs/pull/1747
