### ISSUE TITLE
Address --incompatible_no_rule_outputs_param errors

### ISSUE THREAD

**Issue by mmikitka** [bazelbuild/rules_nodejs#1303]
### Affected Rule
/build_bazel_rules_nodejs/internal/npm_package/npm_package.bzl

### Is this a regression?
No. Compatibility with latest Bazel version.

### Description
I'm seeing the following errors
```
external/build_bazel_rules_nodejs/internal/npm_package/npm_package.bzl:173:15: parameter 'outputs' is deprecated and will be removed soon. It may be temporarily re-enabled by setting --incompatible_no_rule_outputs_param=false

external/build_bazel_rules_nodejs/defs.bzl: Extension file 'internal/npm_package/npm_package.bzl' has errors
```
## Minimal Reproduction

```
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "26c39450ce2d825abee5583a43733863098ed29d3cbaebf084ebaca59a21a1c8",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/0.39.0/rules_nodejs-0.39.0.tar.gz"],
)
```
```
$ bazel version
Build label: 1.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Oct 21 08:44:00 2019 (1571647440)
Build timestamp: 1571647440
Build timestamp as int: 1571647440
```

## Exception or Error
See above

## Your Environment
See above

**Comment by alexeagle** [comment]
hmm, I need to check with @c-parsons about how we can switch to the recommend wrapper macro without ruining our docs generation.

**Comment by gregmagolan** [comment]
No longer in scope for rules_nodejs which only supplies the Node.js toolchain as of [v6.0.0](https://github.com/bazelbuild/rules_nodejs/releases/tag/v6.0.0-beta0).

Downstream canonical JavaScript + Node.js ruleset is now https://github.com/aspect-build/rules_js.
