### ISSUE TITLE
nodejs_binary incorrectly chooses the target platform with RBE

### ISSUE THREAD

**Issue by josephperrott** [bazelbuild/rules_nodejs#1305]
It appears that `nodejs_binary` incorrectly chooses the platforms for execution of its outputs.

I believe this is currently controlled by the block found [here](https://github.com/bazelbuild/rules_nodejs/blob/10d136adbca8e4d3fef90c2068ac44bbda223a18/toolchains/node/BUILD.bazel#L74)

I created a demo/proof in this commit: https://github.com/josephperrott/angular/commit/8dbec8cfac8801a1dbbdb887434109dde8589859

Running `yarn bazel run //tools/rbe-test:bin` locally, everything builds and executes as expected and you get the expected console.log message.
```
$ yarn -s bazel run //tools/rbe-test:bin
INFO: Invocation ID: ce95d7c0-b0d2-4c30-a280-25d015ed331c
...
INFO: Build completed successfully, 1 total action
run!
✨  Done in 1.55s.
```
When running `yarn bazel run //tools/rbe-test:bin --config=remote` to force remote execution, everything builds but then on attempted execution it fails as it can't run the binary
```
$ yarn -s bazel run //tools/rbe-test:bin --config=remote
WARNING: Option 'tls_enabled' is deprecated: Deprecated. Please specify a valid protocol in the URL (https or grpcs).
WARNING: option '--jobs' was expanded to from both option '--config=remote' (source command line options) and option '--config=remote' (source command line options)
INFO: Invocation ID: 26cf4261-e1fb-4b2b-a68f-8f1dc762d7ac
...
INFO: Build completed successfully, 60 total actions
/private/var/tmp/_bazel_jperrott/104b07d8216361462e08a3d288166690/execroot/angular/bazel-out/darwin-fastbuild/bin/tools/rbe-test/bin.sh: line 151: /private/var/tmp/_bazel_jperrott/104b07d8216361462e08a3d288166690/external/nodejs_linux_amd64/bin/nodejs/bin/node: cannot execute binary file
/private/var/tmp/_bazel_jperrott/104b07d8216361462e08a3d288166690/execroot/angular/bazel-out/darwin-fastbuild/bin/tools/rbe-test/bin.sh: line 151: /private/var/tmp/_bazel_jperrott/104b07d8216361462e08a3d288166690/external/nodejs_linux_amd64/bin/nodejs/bin/node: Undefined error: 0
error Command failed with exit code 1.
```

As you can see from the error message, it is attempting to run the node binary from nodejs_*linux*_amd64 rather than nodejs_*darwin*_amd64.  This is controlled by line 118 of the `bin.sh` script that is created for the build:
```
readonly node=$(rlocation "nodejs_linux_amd64/bin/nodejs/bin/node")
```

Interestingly the line below, 119, correctly identifies the platform:
```
readonly repository_args=$(rlocation "nodejs_darwin_amd64/bin/node_repo_args.sh")
```

**Comment by gregmagolan** [comment]
I took a quick look at this and its definitely a bug that need fixing. The launcher template is expanded on the linux RBE where the node tool path is `readonly node=$(rlocation "nodejs_linux_amd64/bin/nodejs/bin/node")` but the run command is run on the local OSX machine which fails.

The solution would seem to be to have the launcher template check the platform and call the appropriate node tool which can work for the subset of node toolchains defined already but how would that work with user defined toolchains?
