### ISSUE TITLE
npm permissions error when running in bazel

### ISSUE THREAD

**Issue by Nikamura** [bazelbuild/rules_nodejs#1309]
# 🐞 bug report

### Affected Rule

Not sure

### Is this a regression?

Not sure

### Description

permissions error is received when running in bazel, because it tries to access my user's _cacache directory.

## 🔬 Minimal Reproduction

https://github.com/Nikamura/paint-by-words/pull/5

`bazel build //... client`

## 🔥 Exception or Error

<pre><code>

ERROR: ...client/BUILD.bazel:3:1: Bundling JavaScript client/index.html [parcel] failed (Exit 1) parcel.sh failed: error executing command bazel-out/host/bin/external/npm/parcel-bundler/bin/parcel.sh build client/src/index.html --out-dir bazel-out/darwin-fastbuild/bin/client --no-cache

Use --sandbox_debug to see verbose messages from the sandbox
/bin/sh: sysctl: command not found
Unhandled rejection Error: EPERM: operation not permitted, open '/Users/sssss/.npm/_cacache/tmp/3bfca066'
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
Unhandled rejection Error: EPERM: operation not permitted, open '/Users/sssss/.npm/_cacache/tmp/39c1b09d'
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
🚨  /private/var/tmp/_bazel_sssss/b0ed4c445e0912d447166e35f8dcc683/sandbox/darwin-sandbox/1/execroot/pbw/client/src/index.ts: Failed to install typescript.
    at PromiseQueue.install [as process] (/private/var/tmp/_bazel_sssss/b0ed4c445e0912d447166e35f8dcc683/sandbox/darwin-sandbox/1/execroot/pbw/bazel-out/host/bin/external/npm/parcel-bundler/bin/parcel.sh.runfiles/npm/node_modules/parcel-bundler/src/utils/installPackage.js:46:11)
Target //client:client failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 26.736s, Critical Path: 20.44s
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
OS X Catalina
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 1.1.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Oct 21 08:47:13 2019 (1571647633)
Build timestamp: 1571647633
Build timestamp as int: 1571647633
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>

  </code>
</pre>

**Anything else relevant?**

https://github.com/parcel-bundler/parcel/issues/3701

**Comment by Nikamura** [comment]
I am using https://github.com/bazelbuild/rules_nodejs/blob/master/examples/parcel/parcel.bzl as a starting point

**Comment by rcarcasses** [comment]
Greetings @kellycampbell , I'm on the same situation right now, did you find a way around? Thanks in advance!

**Comment by alexeagle** [comment]
Maybe this goes away now that Bazel is removing the `managed_directories` feature.
