### ISSUE TITLE
NPM version doesn't match git tags 

### ISSUE THREAD

**Issue by achew22** [bazelbuild/rules_nodejs#1316]
### Affected Rule

On the [NPM releases page](https://www.npmjs.com/package/@bazel/bazel/v/1.1.0?activeTab=versions), the versions seem to have gone out of alignment with the Github tags.

The page as I see it now says:

## Current Tags

```
1.0.0-rc2 next
1.1.0 latest
```

## Version History
```
1.1.0              6 days ago
1.0.0             19 days ago
1.0.0-rc2          2 months ago
1.0.0-rc1          2 months ago
0.29.0             2 months ago
```

Interestingly 

### Is this a regression?

Yes, `0.29.0` seems to have had a matching tag uploaded to NPM.

Additionally the version up on NPM is > 1.0, so people may not be expecting breaking changes on it.

**Comment by alexeagle** [comment]
I'm a little confused. Are you just pointing out that `next` is behind `latest`? That is unfortunate but pretty common.

Or maybe you're asking about the tags on this repo? Those are for the rules_nodejs releases - we don't have any tags here for the mirroring of Bazel itself. That is, the only code in rules_nodejs for bazel, buildifier, and buildozer is the mirroring script. The tags are on whatever repo has the source for that tool.

**Comment by achew22** [comment]
Oh geez... This one is totally on me. `@bazel/bazel` is the repo that contains bazel itself, not the repo that contains the nodejs rules for bazel. I totally parsed this wrong. Sorry about that!
