### ISSUE TITLE
Bazel does not work with @auth0/angular-jwt

### ISSUE THREAD

**Issue by mikolaj-leszczynski** [bazelbuild/rules_nodejs#1321]
### Affected Rule
`ng_module`

### Is this a regression?
No
### Description

Whenever I add `JwtModule`(from @auth0/angular-jwt) to my app, when I try to build the `ng_module` target which contains `"@npm//@auth0/angular-jwt"` in `deps` array my build fails. 
## 🔬 Minimal Reproduction

1. Add `@auth0/angular-jwt` to your dependencies in `package.json`.
2. In `app.module` configure it by adding:
```
import { JWT_OPTIONS, JwtModule } from '@auth0/angular-jwt';

export function jwtOptionsFactory() {
  return {
    tokenGetter: () => 'fake-token,
    whitelistedDomains: ['fake-domain'],
  };
}
```
and in @NgModule imports array:
```
    JwtModule.forRoot({
      jwtOptionsProvider: {
        provide: JWT_OPTIONS,
        useFactory: jwtOptionsFactory,
      },
    }),
``` 

## 🔥 Exception or Error

<pre><code>
external/npm/node_modules/@auth0/angular-jwt/index.d.ts(19,48): error TS-996005: JwtModule.forRoot returns a ModuleWithProviders type without a generic type argument. Please add a generic type argument to the ModuleWithProviders type. If this occurrence is in library code you don't control, please contact the library authors.
src/app/app.component.html(2,3): error TS8001: 'router-outlet' is not a known element:
1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
</code></pre>

## 🌍  Your Environment

**Output of `bazel version`:**

<pre>
  <code>
Build label: 1.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Oct 21 08:44:00 2019 (1571647440)
Build timestamp: 1571647440
Build timestamp as int: 1571647440

  </code>
</pre>

**Anything else relevant?**
1. When I remove JwtModule reference the build is successful.
2. I tried to add the generic type annotation to `ModuleWithProviders` but this gives me another error:
```
src/app/app.module.ts(79,12): error TS-991010: Value at position 6 in the NgModule.imports of AppModule is not a reference: [object Object]
src/app/app.component.html(2,3): error TS8001: 'router-outlet' is not a known element:
1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```
3. I logged a bug for it in `@auth0/angular-jwt`: https://github.com/auth0/angular2-jwt/issues/629
4. I'm on the newest angular:
```
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.0-next.14
Node: 10.16.0
OS: linux x64
Angular: 9.0.0-next.14
... animations, bazel, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.18
@angular-devkit/build-angular     0.900.0-next.18
@angular-devkit/build-optimizer   0.900.0-next.18
@angular-devkit/build-webpack     0.900.0-next.18
@angular-devkit/core              9.0.0-next.14
@angular-devkit/schematics        9.0.0-next.14
@angular/cdk                      8.2.2
@angular/material                 8.2.3
@bazel/bazel                      1.1.0
@bazel/bazel-linux_x64            1.1.0
@bazel/benchmark-runner           0.1.0
@bazel/buildifier                 0.28.0
@bazel/buildifier-linux_x64       0.28.0
@bazel/hide-bazel-files           0.36.2
@bazel/ibazel                     v0.10.3
@bazel/karma                      0.38.3
@bazel/rollup                     0.38.3
@bazel/terser                     0.38.3
@bazel/typescript                 0.38.3
@ngtools/webpack                  9.0.0-next.18
@schematics/angular               9.0.0-next.14
@schematics/update                0.900.0-next.14
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

```
5. The most surprising is the fact that when I do not run `ngcc` as a part of my `postinstall` script the `ng build` command builds (with builder: `@angular-devkit/build-angular:browser"`) the entire app successfully. However when I run `ngcc` and then `ng build` one more time I'm getting the same errors which I mentioned above. I have a feeling that `ngcc` which is run by `ng build` and `ngcc` which is run in `postinstall` script produce different artifacts.

**Comment by alexeagle** [comment]
@alan-agius4 has been investigating how the Ivy compilation of third-party node_modules differs under `ng build` than under `ngcc`

**Comment by mikolaj-leszczynski** [comment]
@alan-agius4 can you give me some hints where I should start looking for the source of this bug ?

**Comment by alan-agius4** [comment]
@mikolaj-leszczynski, for starters I would check what is the difference in `node_modules/@auth0/angular-jwt/index.d.ts` when running the postinstall hook and not.

If you have a repo that I can take a quick look at it would be great.

**Comment by mikolaj-leszczynski** [comment]
> Also, are you calling the NGCC binary with any arguments?
No args. Just `ngcc`
> If you have a repo that I can take a quick look at it would be great.
I am not on my "work" machine. However I think that just adding angular-jwt and configuring it in your app.module will produce the error.

**Comment by mikolaj-leszczynski** [comment]
@alan-agius4 any progress on this one?

**Comment by mikolaj-leszczynski** [comment]
@alexeagle how is the progress in regard to this bug?
