### ISSUE TITLE
Use `--compilation_mode=dbg` instead of `--define DEBUG=1`

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/rules_nodejs#1323]
# 🚀 feature request

### Relevant Rules

All rules with debug capabilities

### Description

`--compilation_mode=dbg` is the canonical way of creating debugging outputs.  Different compilation mode uses dedicated execroots, therefore unlike setting `--define DEBUG=1`, changing compilation mode won't flush caches. So rebuilding a target in debugging mode will be much faster.

### Describe the solution you'd like

Use `ctx.var.get("COMPILATION_MODE")` instead.

### Describe alternatives you've considered

N/A

**Comment by gregmagolan** [comment]
Resolved in #1329 and fixes made in https://github.com/bazelbuild/rules_nodejs/pull/1521
