### ISSUE TITLE
terser_minified produces a single file when using a filegroup input

### ISSUE THREAD

**Issue by Toxicable** [bazelbuild/rules_nodejs#1327]
"how do you create a dir of inputs files for `terser_minified` to use without `rollup_bundle`"
For example if your `.js` files are actual source code.
The first thing that comes to mind is `filegroup`, however, when you used the files will be handed to `terser` as a command deliminated list which will concat them, I don't think this is intended.
```
  inputs: packages/terser/test/directory_input/input1.js,packages/terser/test/directory_input/input2.js
```
One solution would be to split by `,` in `index.js` then create a dir and treat it like we do dir input, but the issue with that is we don't know if all the files taken as input will go into that dir.
Maybe we take the files `basename`s and put them into that dir? ignoring any pathing?

example:
```
filegroup(
    name = "dir2",
    srcs = glob(["input*.js"])
)

terser_minified(
    name = "out.min2",
    src = ":dir2",
    sourcemap = False,
)
```

**Comment by ashi009** [comment]
Unless you are using the `declare_directory` rule to make input files a tree artifact, `terser_minified` won't be able to tell what's the intended behavior based on the filenames passed in, unless additional options are added.

Given that you already have a known list of input files, just use multiple `terser_minified` targets for each of them. There will be no need to change the rule and you will get faster builds.

**Comment by alexeagle** [comment]
`terser_minified` is just mirroring what terser itself does. 
https://terser.org/docs/cli-usage:
> For example:
> terser js/file1.js js/file2.js \
>         -o foo.min.js -c -m \
>         --source-map "root='http://foo.com/src',url='foo.min.js.map'"
> The above will compress and mangle file1.js and file2.js, will drop the output in foo.min.js

@ashi009 is right, if you can enumerate (glob for example) the input files you may as well have separate action for each one so it's more parallel/incremental.

That said I do think Bazel should have some built-in rule that takes `srcs` and yields a TreeArtifact (directory) so that what Pete tried to do is easier. TreeArtifact support is generally weak.

**Comment by petebacondarwin** [comment]
Thanks @ashi009  - I didn't think of that. I'll give it a try.

**Comment by petebacondarwin** [comment]
Actually @ashi009 - how would I refer to the output of such a rule?

**Comment by alexeagle** [comment]
Bazel is generally allergic to inputs having the same path as outputs, since that makes it ambiguous which one to provide to rules that depend on that file.

**Comment by petebacondarwin** [comment]
So the question remains... what is the best way to take a "well defined" set of files (e.g. all the `.js` files in a directory), minify them and add them (with the same name) to an npm package?
