### ISSUE TITLE
Cannot use rollup_bundle rule inside corporate network

### ISSUE THREAD

**Issue by KeshavRathi** [bazelbuild/rules_nodejs#1328]
# Cannot use rollup_bundle rule in corporate network

### Affected Rule

Rule affected: rollup_bundle

### Description

The build system in the company I work in, does not have internet access for downloading libraries. We use internal artifactory for all the node libraries. yarn.lock file in this repo has all the url's pointing to internet and my build fails. We have strict policy to not connect to internet even via proxy for builds.

yarn.lock location: https://github.com/bazelbuild/rules_nodejs/blob/master/internal/rollup/yarn.lock

Example:
"@buxlabs/amd-to-es6@^0.12.0":
  version "0.12.5"
  resolved "https://registry.yarnpkg.com/@buxlabs/amd-to-es6/-/amd-to-es6-0.12.5.tgz#18c12479512ae09106fc6f60ad1b4b9eb8e8eb62"
  integrity sha512-RaZQrUhSl+IPIn3tBdMlDAb20jcWcBGQpnmUth9Jf9Bx1c7zGPQAxTzuag5UBLGBEBAKGr5fxvwGGdF+C/mDjQ==
  dependencies:
    "@buxlabs/ast" "^0.9.5"
    "@buxlabs/utils" "^2.2.2"
    array-uniq "^1.0.3"
    commander "^2.13.0"
    glob "^7.1.2"
    mkdirp "^0.5.1"

Is there a way to forward these requests to corporate repo? If not, Please provide a support for using **registry.corporate.com** instead of **registry.yarnpkg.com**.

## 🔬 Minimal Reproduction

Use rollup_bundle rule for bundling a angular project on a machine with no internet connectivity.

## 🌍  Your Environment

OS: centos7
Internet connectivity: No

**Comment by KrauseStefan** [comment]
We have a similar requirement.
You can patch the yarn.lock file.
See https://bazelbuild.github.io/rules_nodejs/#patching-the-built-in-release

I believe this dependency will disappear soon and become a peer dependency that you manually install in your own node_modules folder.

**Comment by KeshavRathi** [comment]
@KrauseStefan Thanks for the reference. I had done something similar by creating a patch of yarn.lock with all the urls replaced with my internal repo. I was looking for what's the best recommendation to achieve this? 

I also feel that files like yarn.lock should not be committed to open source rules or have a generic way to redirect requests to the internal artifactory so that patching may not be required. So I had opened this issue.

**Comment by alexeagle** [comment]
yeah you shouldn't use the rollup rule from internal/rollup anymore, it is deprecated and will be removed soon

**Comment by KeshavRathi** [comment]
@a-ignatov-parc I tried setting the registry but it didn't work. @alexeagle I am using rules_nodejs 0.34.0 which supports internal/rollup. When I tried upgrading to the latest was issues: https://github.com/bazelbuild/rules_nodejs/issues/1347 .
