### ISSUE TITLE
Cannot find module 'rollup-plugin-node-resolve'

### ISSUE THREAD

**Issue by jmclen** [bazelbuild/rules_nodejs#1336]
I noticed the currently deployed example does not load except for the static index page. When I try running this example in production mode, the modules specified in rollup.config.js can't be found. I get the following error:

Error: Cannot find module 'rollup-plugin-node-resolve'. Please verify that the package.json has a valid "main" entry

I see they are specified in the deps for rollup_bundle, but it's not working.

**Comment by gregmagolan** [comment]
Can you be more specific about which example you're referring to?

**Comment by Toxicable** [comment]
@gregmagolan the angular one, i've seen this issue as well running it locally

**Comment by jmclen** [comment]
Sorry for not being clear about that. Yes, angular. I was able to work around it by running rollup separately from the command line. this was for version 0.39.1. In the latest version, it seems to have been resolved.

**Comment by alexeagle** [comment]
Sounds like it's resolved and not reproducible (I removed the `dynamic_deps` feature which was probably one of the causes)
