### ISSUE TITLE
Building using supplied example/angular rules, internal/common:sources_aspect.bzl does not exist

### ISSUE THREAD

**Issue by jasonh-logic2020** [bazelbuild/rules_nodejs#1337]
# 🐞 bug report

I have a nodejs / angular build which is attempting to follow the rules provided in the example/angular directory, but i get a missing internal file and I'm not sure ow to proceed

### Affected Rule
my src/BUILD file is copied in form from 
https://github.com/bazelbuild/rules_nodejs/blob/master/examples/angular/src/BUILD.bazel

I removed babel because I don't need to support older browsers but other than that it's the same rule chain.

Here is the relevant section of my WORKSPACE
```
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "3d7296d834208792fa3b2ded8ec04e75068e3de172fae79db217615bd75a6ff7",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/0.39.1/rules_nodejs-0.39.1.tar.gz"],
)

load("@build_bazel_rules_nodejs//:index.bzl", "node_repositories")

node_repositories(
    package_json = ["//ui:package.json"],
    node_version = "8.11.1",
    yarn_version = "1.5.1",
)

load("@build_bazel_rules_nodejs//:index.bzl", "npm_install")

npm_install(
    name = "npm",
    package_json = "//ui:package.json",
    package_lock_json = "//ui:package-lock.json",
)

load("@npm//:install_bazel_dependencies.bzl", "install_bazel_dependencies")
install_bazel_dependencies()

load("@npm_bazel_typescript//:index.bzl", "ts_setup_workspace")
ts_setup_workspace()
```

Here is devDependencies part of my package.json:
```
    "devDependencies": {
        "@angular-devkit/build-angular": "^0.803.13",
        "@angular/cli": "^8.3.13",
        "@angular/compiler-cli": "^8.2.12",
        "@angular/language-service": "^8.2.11",
        "@bazel/bazel": "^1.1.0",
        "@bazel/buildifier": "0.28.0",
        "@bazel/ibazel": "0.10.3",
        "@bazel/karma": "^0.38.0",
        "@bazel/protractor": "^0.39.1",
        "@bazel/rollup": "^0.38.0",
        "@bazel/terser": "^0.38.0",
        "@bazel/typescript": "^0.38.0",
        "@types/applicationinsights-js": "^1.0.9",
        "@types/jasmine": "^3.3.5",
        "@types/jasminewd2": "^2.0.6",
        "@types/node": "^10.12.18",
        "codelyzer": "^5.2.0",
        "flatted": "^2.0.1",
        "history-server": "^1.3.1",
        "install": "^0.12.2",
        "jasmine-core": "^3.3.0",
        "jasmine-spec-reporter": "^4.2.1",
        "karma": "^3.1.4",
        "karma-chrome-launcher": "^2.2.0",
        "karma-coverage-istanbul-reporter": "^2.0.4",
        "karma-jasmine": "^2.0.1",
        "karma-jasmine-html-reporter": "^1.4.0",
        "protractor": "^5.4.1",
        "rollup": "^1.21.4",
        "rollup-plugin-commonjs": "^10.1.0",
        "rollup-plugin-node-resolve": "^5.2.0",
        "terser": "4.3.1",
        "ts-node": "^7.0.1",
        "tslint": "^5.11.0",
        "typescript": "~3.4.0"
    }

```

### Is this a regression?
Unclear.

### Description

```$ bazel build ui```

```
INFO: Writing tracer profile to '/home/[user omitted]/.cache/bazel/_bazel_[user omitted]/f2dd2bfb2974a88433ae0424106ea3d1/command.profile.gz'
ERROR: /home/[user omitted]/[repo omitted]/ui/BUILD:8:1: error loading package 'ui/src': in /home/[user omitted]/.cache/bazel/_bazel_[user omitted]/f2dd2bfb2974a88433ae0424106ea3d1/external/npm_angular_bazel/index.bzl: in /home/[user omitted]/.cache/bazel/_bazel_[user omitted]/f2dd2bfb2974a88433ae0424106ea3d1/external/npm_angular_bazel/src/protractor/protractor_web_test.bzl: Unable to load file '@build_bazel_rules_nodejs//internal/common:sources_aspect.bzl': file doesn't exist and referenced by '//ui:ui'
ERROR: Analysis of target '//ui:ui' failed; build aborted: error loading package 'ui/src': in /home/[user omitted]/.cache/bazel/_bazel_[user omitted]/f2dd2bfb2974a88433ae0424106ea3d1/external/npm_angular_bazel/index.bzl: in /home/[user omitted]/.cache/bazel/_bazel_[user omitted]/f2dd2bfb2974a88433ae0424106ea3d1/external/npm_angular_bazel/src/protractor/protractor_web_test.bzl: Unable to load file '@build_bazel_rules_nodejs//internal/common:sources_aspect.bzl': file doesn't exist
INFO: Elapsed time: 97.186s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 2 targets configured)
    currently loading: @io_bazel_rules_k8s//k8s
    Fetching @subpar; fetching
```

I can't find any trace of '@build_bazel_rules_nodejs//internal/common:sources_aspect.bzl' so I'm not sure what to do next. 

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Fedora 30
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
$ bazel --version
bazel 1.1.0
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "3d7296d834208792fa3b2ded8ec04e75068e3de172fae79db217615bd75a6ff7",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/0.39.1/rules_nodejs-0.39.1.tar.gz"],
)
  </code>
</pre>

**Anything else relevant?**

**Comment by jasonh-logic2020** [comment]
Additional info: seeing protractor mentioned in the log output, i tried removing ```bazel/protractor''' from ```package.json``` but it still returns the same result.

**Comment by gregmagolan** [comment]
This looks like version skew between your build_bazel_rules_nodejs version in your workspace and the @bazel/foo packages in your package.json. The versions should match on at least the minor version.

In your package.json, can you try setting these packages to match the version in your WORKSPACE:
```
        "@bazel/karma": "^0.39.1",
        "@bazel/protractor": "^0.39.1",
        "@bazel/rollup": "^0.39.1",
        "@bazel/terser": "^0.39.1",
        "@bazel/typescript": "^0.39.1",
```

**Comment by gregmagolan** [comment]
Ahh, looking at your error log your @angular/bazel version needs to be updated to the latest. Try updating that to `9.0.0-rc2`. The version of `@angular/bazel` doesn't need to match the versions of the other `@angular` packages.

**Comment by alexeagle** [comment]
Please comment again if Greg's suggestion didn't fix it for you. In the run-up to our 1.0 launch we are making more breaking changes that need precise versioning with Angular, sorry for the churn.

**Comment by jasonh-logic2020** [comment]
Trapped on another task, trying to get back to this ASAP.

**Comment by httpete** [comment]
I hit a similar issue and updating to   "@angular/bazel": "9.0.0-rc.3" fixed it.
