### ISSUE TITLE
Linker may mutate node_modules in workspace

### ISSUE THREAD

**Issue by clintharrison** [bazelbuild/rules_nodejs#1340]
# 🐞 bug report

### Affected Rule

Any rule using the linker -- I linked a repo below that has a small webpack wrapper using the `run_node` helper.

### Is this a regression?

No

### Description

When a rule using the linker is not sandboxed, it will create a `node_modules` symlink in `execroot/$wksp`. When not sandboxed, this may be itself be a symlink to the workspace's `node_modules`, or a symlink to `external/npm/node_modules` (which is then a symlink to the one in the workspace).

This can unfortunately be a huge problem if recursive globs are used in the package containing the `node_modules` directory, because of https://github.com/bazelbuild/bazel/issues/7433.
The fix for this hasn't made it to any releases yet, so _even though_ `node_modules` is in `.bazelignore`, this symlink can cause Bazel to exhaustively recurse through the entire `bazel-bin` directory.

I've seen this fail in a few ways: an output with runfiles that contain a symlink to the workspace (causing an "infinite symlink expansion" error), or it recurses so much that it exhausts the Bazel server's heap space.

## 🔬 Minimal Reproduction

https://github.com/clintharrison/nodejs_linker_sandboxing has a small rule that wraps webpack to use the linker.

`bazel build --spawn_strategy=standalone //...` creates some symlinks in the root `node_modules`, but will succeed the first time.

Run it again, and it fails.

This is a bit contrived, and it's tempting to say "don't use `--spawn_strategy=standalone`", but the default for persistent workers is to run without sandboxing, and it's seemingly unlikely for that default to change any time soon, per https://github.com/bazelbuild/bazel/issues/6111.

## 🔥 Exception or Error

<pre><code>
❯ bazel build --spawn_strategy=standalone //...
INFO: Writing tracer profile to '/private/var/tmp/_bazel_charrison/59e32b2662cefe402a6eec94fa20ce25/command.profile.gz'
ERROR: /Users/charrison/code/tmp/nodejs_linker_sandboxing/app/BUILD.bazel:3:1: in srcs attribute of py_binary rule //app:app: file name 'src/app.py' specified by 'main' attribute matches multiple files: e.g., 'app/node_modules/nodejs_linker_sandboxing/app/app.runfiles/nodejs_linker_sandboxing/app/src/app.py' and 'app/src/app.py'
ERROR: Analysis of target '//app:app' failed; build aborted: Analysis of target '//app:app' failed; build aborted
INFO: Elapsed time: 0.111s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 6 targets configured)
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre><code>
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226
</code></pre>

**Output of `bazel version`:**

<pre><code>
Build label: 1.1.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Oct 21 08:47:13 2019 (1571647633)
Build timestamp: 1571647633
Build timestamp as int: 1571647633
</code></pre>

**Rules version (SHA):**

Release tar, 0.39.1

**Anything else relevant?**

I mentioned this in Slack; primarily creating this to track the issue.

**Comment by soldair** [comment]
thanks for the report. i expect the new fs patches to fix this behavior because nodejs will find links pointing outside of the root as if they were not links but the file/directory they point to.

**Comment by evahowe** [comment]
@soldair @clintharrison - did this happen?
