### ISSUE TITLE
Unable to load file '@npm_bazel_typescript//:index.from_src.bzl': file doesn't exist

### ISSUE THREAD

**Issue by KeshavRathi** [bazelbuild/rules_nodejs#1347]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: No specific rule, WORKSPACE setup

### Is this a regression? Yes

 Yes, the previous version in which this bug was not present was: ....

### Description

I am trying to upgrade angular app built using rules_nodjs 0.34.0 to 0.39.1. 

When I trigger the command "bazel build //src:prodapp" I am receiving an error:

`npm/@angular/bazel/bin/BUILD.bazel:10:1: every rule of type nodejs_binary implicitly depends upon the target '@build_bazel_rules_nodejs//internal/linker:index.js', but this target could not be found because of: error loading package '@build_bazel_rules_nodejs//internal/linker': Unable to load file '@npm_bazel_typescript//:index.from_src.bzl': file doesn't exist
ERROR: Analysis of target '//src:src' failed; build aborted: error loading package '@build_bazel_rules_nodejs//internal/linker': Unable to load file '@npm_bazel_typescript//:index.from_src.bzl': file doesn't exist`

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
    Mac OS Mojave
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
   Build label: 1.1.0-homebrew
   Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
   Build time: Mon Oct 21 21:09:45 2019 (1571692185)
   Build timestamp: 1571692185
   Build timestamp as int: 1571692185
  </code>
</pre>

**Anything else relevant?**
Package.json dev dependencies:
`"devDependencies": {
    "@angular/bazel": "9.0.0-next.11",
    "@angular/cli": "8.3.10",
    "@angular/compiler": "8.2.11",
    "@angular/compiler-cli": "8.2.11",
    "@babel/cli": "^7.6.0",
    "@babel/core": "^7.6.0",
    "@babel/preset-env": "^7.6.0",
    "@bazel/bazel": "^1.1.0",
    "@bazel/benchmark-runner": "0.1.0",
    "@bazel/buildifier": "0.28.0",
    "@bazel/ibazel": "0.10.3",
    "@bazel/jasmine": "^0.39.1",
    "@bazel/karma": "^0.39.1",
    "@bazel/protractor": "^0.39.1",
    "@bazel/rollup": "^0.39.1",
    "@bazel/terser": "^0.39.1",
    "@bazel/typescript": "^0.39.1",
    "@types/jasmine": "3.4.0",
    "@types/node": "6.14.6",
    "core-js": "2.6.9",
    "firebase-tools": "7.1.0",
    "history-server": "^1.3.1",
    "patch-package": "^6.2.0",
    "terser": "4.3.1",
    "typescript": "3.4.5"
  },`

It could be a very minor mistake somewhere but I am unable to figure out how to resolve it.

Thank you,
Keshav.

**Comment by gregmagolan** [comment]
If you're pulling in @bazel/typescript from npm the load path is `"@npm_bazel_typescript//:index.bzl"`. For example, https://github.com/bazelbuild/rules_nodejs/blob/master/examples/app/BUILD.bazel#L7.

`index.from_src.bzl` is used if you're pulling in `npm_bazeL_foo` using http_archive in your WORKSPACE file such as https://github.com/bazelbuild/rules_nodejs/blob/master/examples/user_managed_deps/WORKSPACE#L41.

**Comment by gregmagolan** [comment]
Your WORKSPACE for npm_bazel_typescript should look like this: https://github.com/bazelbuild/rules_nodejs/blob/master/examples/app/WORKSPACE#L40

**Comment by KeshavRathi** [comment]
My WORKSPACE file does contain:
`load("@npm_bazel_typescript//:index.bzl", "ts_setup_workspace")`

In BUILD.bazel I am loading using: 
`load("@npm_bazel_typescript//:index.bzl", "ts_config", "ts_devserver", "ts_library")`

All rule imports are using `git_repository`.

I still have the same error

**Comment by alexeagle** [comment]
There must be some other code in the `WORKSPACE` file that is causing the transitive dependency on this file. I think I saw a similar issue from someone using `rules_sass` maybe? We need some help to track down what might be transitively loading this.

**Comment by KeshavRathi** [comment]
Sorry for the delay. Due to some reasons I didn't get time to work on this issue. Closing it for now. Thank you.

**Comment by hristozov** [comment]
FWIW, I got the exact same error when trying to consume rules_nodejs with a `git_repository`, instead of the recommended way with `http_archive`. Seems the sections between `BEGIN-INTERNAL` / `END-INTERNAL` are breaking workspaces which try to use rules_nodejs directly from source with `git_repository`. 
Unfortunately, these problems are not immediately obvious (e.g. `npm_install` works OK) and the build breaks with obscure messages like the one about `from_src`, causing GH issues like the current one (also reported in #1300).
Since I'm quite a newbie in Bazel, is it possible to add a guard which causes the whole workspace to break in a friendly way when someone tries to consume rules_nodejs from source and not from archive? Also, mentioning in the documentation that this is unsupported is worth considering.
