### ISSUE TITLE
Running `nodejs_test` with a output from `ts_library` fails when using TSX

### ISSUE THREAD

**Issue by joeljeske** [bazelbuild/rules_nodejs#1351]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 

`nodejs_test` using output from `ts_library`

### Is this a regression?

Not sure, probably not. 

### Description

 
I want to compile TSX files into JS for executing tests in NodeJS. Using the output from `ts_library` as input to `nodejs_test`. What is interesting is that **if the file was just `.ts` instead of `.tsx` then the test would properly find the file.**

## 🔬 Minimal Reproduction

```
# BUILD.bazel

load("@npm_bazel_typescript//:index.bzl", "ts_library")
ts_library(
    name = "compile_tests",
    srcs = glob(["some.test.tsx"]),
)

load("@build_bazel_rules_nodejs//:index.bzl", "nodejs_test")
nodejs_test(
    name = "run_tests",
    entry_point = "some.test.tsx",
    data = ["compile_tests"]
)
```
## 🔥 Exception or Error

<pre><code>
Error: Cannot find module 'some.test.tsx'. Please verify that the package.json has a valid "main" entry
/// stack trace
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS 10.14.6
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 1.1.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Oct 21 08:47:13 2019 (1571647633)
Build timestamp: 1571647633
Build timestamp as int: 1571647633
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>
3d7296d834208792fa3b2ded8ec04e75068e3de172fae79db217615bd75a6ff7
  </code>
</pre>

**Anything else relevant?**

**Comment by joeljeske** [comment]
It would seem as though it works with TS files is because of 

https://github.com/bazelbuild/rules_nodejs/blob/cc11b202e3fc70e0dab5e02a701a453510fdab6c/internal/node/node.bzl#L101

This seems a bit fragile to me and special cased. Is there a better way that "aliases" or "transforms" could be specified so the translated file could be derived from the request?

**Comment by alexeagle** [comment]
Thanks for tracking down the root cause.

A simple answer is that if the rule which transpiles to JS were to give a label to the outputs, you could just do `entry_point = "some.test.jsx"` and we wouldn't need this logic in node.bzl. But `ts_library` currently doesn't give labels for its outputs.

I think there are few enough cases of transpile-to-JS languages that we can just add missing cases here. Sending a PR...

**Comment by joeljeske** [comment]
@alexeagle Thanks for the reply. I have left a comment on that commit with a question regarding the changing of TSX to JSX. 

https://github.com/bazelbuild/rules_nodejs/commit/313d484865e0ea9c38ee3548a8014766be665053#commitcomment-36012644

Essentially, I am worried that your change assumes that TSC is outputting JSX as opposed to JS. tsconfig.json can be configured to preserve the XML or to transform it.
