### ISSUE TITLE
Recipe for a `jasmine_node_test` that depends on running `ts_devserver`

### ISSUE THREAD

**Issue by joeljeske** [bazelbuild/rules_nodejs#1367]
# 🚀 feature request

### Relevant Rules

* jasmine_node_test
* ts_devserver

### Description

 

It would be helpful to be able invoke a `jasmine_node_test` that would depend on `ts_devserver` actively running. 

For my scenario, I want to write jasmine tests in node that open puppeteer to the devserver running my application. 

### Describe the solution you'd like

I would like to be able mark devserver as a dep of the test 

### Describe alternatives you've considered

I attempted this my add the devserver label to either `data` or `deps` on `jasmine_node_test` but neither one seem to appropriately rely on the deverserver; it never gets spun up. 

Please advise if I am approaching this problem incorrectly.

**Comment by joeljeske** [comment]
What I am currently doing, is marking the dev server target as a data label for the jasmine test, and then invoking the loader shell script during the node process. 

This may be considered the proper bazel solution, I am not sure. I am somewhat new to bazel.

**Comment by alexeagle** [comment]
First of all, do you really want to write tests against the development mode? It's wise to have a single one of those to ensure that commits don't break the devserver, but generally you probably want test coverage against the production server.

We do have tests that run against the ts_devserver, for example https://github.com/bazelbuild/rules_nodejs/blob/master/examples/angular/e2e/BUILD.bazel#L23-L28
you can pick through that example a bit to see how the server gets launched - in our case we use an integration test runner (protractor) that knows how to manage a server under test. The `protractor.on-prepare.js` file has the logic.

I'd like to add an example with Cypress as the e2e test runner, I imagine it similarly knows about managing a test binary.

Maybe we should have an example using puppeteer specifically, but I think the shape of your solution sounds reasonable. Maybe there's a cleaner mechanism to launch the server than the shell script but I think that's a small difference.
