### ISSUE TITLE
Clean up pkg_web tests

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#1372]
they are basically no-op tests for removed injector feature

**Comment by gregmagolan** [comment]
No longer in scope for rules_nodejs which only supplies the Node.js toolchain as of [v6.0.0](https://github.com/bazelbuild/rules_nodejs/releases/tag/v6.0.0-beta0).

Downstream canonical JavaScript + Node.js ruleset is now https://github.com/aspect-build/rules_js.
