### ISSUE TITLE
linker assumes node_modules goes in workspace root

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#1373]
in #1332 @soldair introduces a nested package.json which is npm_install'ed in the workspace

```
managed_directories = {
        "@npm": ["node_modules"],
        "@npm_node_patches": ["packages/node-patches/node_modules"],
    },
```

When running a node program using this `@npm_node_patches` workspace, the linker ought to lay out `$PWD/packages/node-patches/node_modules` but they go in `$PWD/node_modules` instead.

**Comment by excavador** [comment]
Do you have any estimate to fix?
