### ISSUE TITLE
output_dir in rollup_bundle does not put bundle under specified dir

### ISSUE THREAD

**Issue by wimzyLive** [bazelbuild/rules_nodejs#1379]
# 🐞 bug report
### Affected Rule
rollup_bundle exported by `load("@npm_bazel_rollup//:index.bzl", "rollup_bundle")`

### Is this a regression?

 Not sure, since I was using `rollup_bundle` exported by `build_bazel_rules_nodejs`  before

### Description

Not really sure if this is a bug or documentation problem, I am trying to bundle up some code under specific `dir` using `rollup_bundle`  rule. 
My BUILD and rollup.configs.js looks like this. 

BUILD
```
load("@npm_bazel_rollup//:index.bzl", "rollup_bundle")
rollup_bundle(
    name = "bundle",
    entry_point = ":index.ts",  // this depends on other ts_library target 
    output_dir = True,
    srcs = [
        "//:package.json"
    ],
    deps = [
        ":library",
        "@npm//rollup-plugin-node-resolve",
        "@npm//rollup-plugin-node-builtins",
        "@npm//rollup-plugin-auto-external",
        "@npm//rollup-plugin-commonjs"
    ],
    config_file = "//:rollup.config.js",
)
```

rollup.config.js
```js
import resolve from "rollup-plugin-node-resolve";
import commonjs from "rollup-plugin-commonjs";
import builtins from "rollup-plugin-node-builtins";
import autoExternal from "rollup-plugin-auto-external";

export default {
  output: {
    dir: "resources"
  },
  plugins: [
    resolve(), // resolve internal deps
    commonjs(), // handle external cjs modules
    autoExternal(), // do not include external module in bundle
    builtins() // exclude builtin modules i.e(path, fs)
  ]
};

```

I want bundled js code to be available as `resources/bundle.js` instead of `bundle.js`

## 🔥 Exception or Error

Code compiles and bundles but rollup_bundle does not respect `dir`  option provided in rollup.config

## 🌍  Your Environment
**Operating System:**
MacOs

**Output of `bazel version`:**

<pre>
  <code>
Build label: 1.2.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Nov 20 15:08:12 2019 (1574262492)
Build timestamp: 1574262492
Build timestamp as int: 1574262492
  </code>
</pre>

**Rules version (npm):**

<pre>
  <code>
 "@bazel/rollup": "^0.40.0",
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
See documentation https://github.com/bazelbuild/rules_nodejs/blob/master/docs/Rollup.md#rollup_bundle
about "setting options that Bazel controls will have no effect"

the output file is named after the target so you can just use `rollup_bundle(name="resources/bundle")` if you want the output to go in `dist/bin/path/to/package/resources/bundle`

another option is to use some `pkg_*` rule later in the build to move resources around from the source tree layout to the distribution layout.
