### ISSUE TITLE
ts_devserver does not work with React Hooks

### ISSUE THREAD

**Issue by sahilprasad** [bazelbuild/rules_nodejs#1383]
# 🐞 bug report

### Affected Rule

`ts_devserver`

### Is this a regression?

Not that I'm aware of.

### Description

Running `ts_devserver` with a React app using Hooks does not work. The server compiles and runs, but when viewing the `index.html`, shows the following error:

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component.
```

Commenting out the `useState` call in my repro works as expected, so the issue is isolated to the usage of React Hooks.

## 🔬 Minimal Reproduction

https://www.github.com/sahilprasad/bazel_hooks

## 🔥 Exception or Error

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.umd.js:1952)
    at Object.useState (react.umd.js:1979)
    at App (index.tsx:5)
    at renderWithHooks (react-dom.umd.js:3272)
    at mountIndeterminateComponent (react-dom.umd.js:3546)
    at beginWork$1 (react-dom.umd.js:3849)
    at HTMLUnknownElement.callCallback (react-dom.umd.js:520)
    at Object.invokeGuardedCallbackDev (react-dom.umd.js:540)
    at invokeGuardedCallback (react-dom.umd.js:555)
    at beginWork$$1 (react-dom.umd.js:4793)

```

## 🌍  Your Environment

**Operating System:**

Ubuntu 19.04

**Output of `bazel version`:**

<pre>
  <code>
Build label: 1.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Oct 21 08:44:00 2019 (1571647440)
Build timestamp: 1571647440
Build timestamp as int: 1571647440
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>
9901bc17138a79135048fb0c107ee7a56e91815ec6594c08cb9a17b80276d62b
  </code>
</pre>

**Comment by hperl** [comment]
I think the autogenerated react.umd build is creating issues. Your example works when using the `react.development.js` and adding a `bootstrap.js` to teach require.js how to reach it:

```js
var require = {
  paths: {
    "react-dom": "npm/node_modules/react-dom/umd/react-dom.development",
    react: "npm/node_modules/react/umd/react.development",
  }
};
```

See https://github.com/sahilprasad/bazel_hooks/pull/1

**Comment by AnatoleLucet** [comment]
@hperl it seems to work well on `0.40` but when I clone your PR and update everything (archive and yarn) to `1.0.1`  ([see](https://github.com/bazelbuild/rules_nodejs/releases/tag/1.0.1)) and replace the `index_html = ":index.html"` by `additional_root_paths = ["bazel_hooks"]` it doesn't seems to work. The devserver is not adding any scripts to `index.html`.
Any ideas why?

**Comment by SamanShafigh** [comment]
I also getting errors with "@bazel/typescript": "^1.1.0". In the same repo I just update the version of @bazel/typescript and getting these errors: 

The ts_devserver is used as follow
```
ts_devserver(
    name = "devserver",
    entry_module = "bazel_hooks/index",
    index_html = ":index.html",
    port = 9999,
    serving_path = "/bundle.js",
    static_files = [
        ":index.html"
    ],
    deps = [
        ":src",
	"@npm//react:react__umd",
	"@npm//react-dom:react-dom__umd"
    ]
)
```

With following error 

```
Error getting Bazel info exit status 2
error setting higher file descriptor limit for this process: invalid argumentQuerying for files to watch...
Loading: 0 packages loaded
ERROR: error loading package '': in /private/var/tmp/_bazel_saman/571db09d7daae307b731855188fbc17f/external/npm_bazel_typescript/index.bzl: in /private/var/tmp/_bazel_saman/571db09d7daae307b731855188fbc17f/external/npm_bazel_typescript/internal/devserver/ts_devserver.bzl: Unable to load file '@nodejs//:index.bzl': file doesn't exist
Loading: 0 packages loaded
Loading: 0 packages loaded
Bazel query failed: exit status 7
Loading: 0 packages loaded
ERROR: error loading package '': in /private/var/tmp/_bazel_saman/571db09d7daae307b731855188fbc17f/external/npm_bazel_typescript/index.bzl: in /private/var/tmp/_bazel_saman/571db09d7daae307b731855188fbc17f/external/npm_bazel_typescript/internal/devserver/ts_devserver.bzl: Unable to load file '@nodejs//:index.bzl': file doesn't exist
Loading: 0 packages loaded
Loading: 0 packages loaded
Bazel query failed: exit status 7
Runing //:devserver
Loading: 0 packages loaded
ERROR: error loading package '': in /private/var/tmp/_bazel_saman/571db09d7daae307b731855188fbc17f/external/npm_bazel_typescript/index.bzl: in /private/var/tmp/_bazel_saman/571db09d7daae307b731855188fbc17f/external/npm_bazel_typescript/internal/devserver/ts_devserver.bzl: Unable to load file '@nodejs//:index.bzl': file doesn't exist
Loading: 0 packages loaded
Loading: 0 packages loaded
Error running Bazel exit status 7
error Command failed with exit code 4.
```

Any chance we can get this fixed.

**Comment by AnatoleLucet** [comment]
@SamanShafigh Did you updated the `http_archive` with:
```python
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "c97bf38546c220fa250ff2cc052c1a9eac977c662c1fc23eda797b0ce8e70a43",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/1.1.0/rules_nodejs-1.1.0.tar.gz"],
)
```
in your `WORKSPACE`?

**Comment by CoopeyB** [comment]
Adding my two cents, since we also hit this issue. My theory is that the Bazel generated UMDs are bundling multiple instances of React, which don't cause issues until hooks are called.  I solved our issue for using hooks in our code using @hperl's [comment above](https://github.com/bazelbuild/rules_nodejs/issues/1383#issuecomment-559021631) (Thanks!). I still ran into issues when I bundled libraries that use hooks (e.g. react-router-dom).  To solve this, I used the same solution (hoisting the UMD for the library), but I had to explicitly define the library in `static_files` for them to be hosted by ts_devserver. To be safe, I threw react and react-dom there as well:

```
    static_files = [
        ":index.html",
        "@npm//react",
        "@npm//react-dom",
        "@npm//react-router-dom",
    ],
```

and added an entry for react-router-dom to the bootstrap script:
```
var require = {
    paths: {
        "react-dom": "npm/node_modules/react-dom/umd/react-dom.development",
        react: "npm/node_modules/react/umd/react.development",
        "react-router-dom": "npm/node_modules/react-router-dom/umd/react-router-dom",
    },
};
```
The above works for us on rules_nodejs v1.1.0.

I think the real long-term fix here is to improve the logic of UMD generation to treat all dependencies as peer dependencies, and generate modules for each dependency in the tree. That way any libraries that depend on instances of themselves (e.g. React) will only be loaded once.

Another potential solution (that would likely be easier lift) is to generate a single UMD for all deps in the deps list that includes all libraries.

Either way, we got our solution working with the workarounds above - Thanks!

**Comment by bjchambers** [comment]
I ran into a similar problem trying to use redux with an example in this PR:

https://github.com/bazelbuild/rules_nodejs/pull/1076#issuecomment-543251311

react-router-dom actually has a check to make sure that react-router was loaded from the same kind of module. But it was failing, because react-router was loaded from a UMD and also embedded in react-router-dom (as `cjs`), which caused it to not work.

**Comment by joprice** [comment]
I'm seeing the same issue, but the suggestions don't work in my case. I can see 3 of the same version of react in the bundle served by the dev server.

**Comment by joprice** [comment]
It seems that my issue was caused by `@apollo/client`. I was able to use the above technique along with using npm_umd_bundle to remove react and react-dom to get it to work:

```python
npm_umd_bundle(
    name = "apollo_client_umd",
    package_name = "@apollo/client",
    entry_point = "@npm//:node_modules/@apollo/client/index.js",
    excluded = [
        "react",
        "react-dom",
    ],
    package = "@npm//@apollo/client",
)

ts_devserver(
    name = "devserver",
    bootstrap = [
        "bootstrap.js",
    ],
    entry_module = "index",
    static_files = [
        "@npm//:node_modules/react/umd/react.development.js",
        "@npm//:node_modules/react-dom/umd/react-dom.development.js",
        ":@apollo/client.umd.js",
        "index.html",
    ],
    deps = ["client"],
)
```

Where `boostrap.js` contains:

```js
var require = {
    paths: {
      "react-dom": "npm/node_modules/react-dom/umd/react-dom.development",
      react: "npm/node_modules/react/umd/react.development",
      "@apollo/client": "graphql-client/@apollo/client.umd"
    }
  };
```
