### ISSUE TITLE
Use host nodejs and yarn/npm

### ISSUE THREAD

**Issue by duarten** [bazelbuild/rules_nodejs#1389]
# 🚀 feature request

### Relevant Rules

node_repositories()

### Description

Add the option to use the host installed npm, yarn and node. While similar to the local version, this allows building on multiple platforms without having to check-in the platform-specific executables. 

Similar to the [Go rules](https://github.com/bazelbuild/rules_go#how-do-i-run-bazel-on-travis-ci): 

> [...] To avoid downloading a Go SDK, you may request a container with a preinstalled version of Go in your .travis.yml file, then call go_register_toolchains(go_version = "host") in a Travis-specific WORKSPACE file.

**Comment by marcus-sa** [comment]
Yeah this feature would be nice.
For instance running `bazel` and `yarn bazel` doesn't result in the same behavior.
