### ISSUE TITLE
npm_package should produce a tar.gz file

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/rules_nodejs#1392]
# 🚀 feature request

### Relevant Rules

npm_package

### Description

We should have a pre-declared `{name}.tar.gz` output from npm_package. 

This is often useful and the current pattern of:

```
npm_package(
    name = "some_package",
    ...
)

pkg_tar(
    name = "some_package_archive",
    srcs = [":some_package"],
    extension = "tar.gz",
    strip_prefix = "./some_package",
    tags = ["manual"],
)
```

would be simplified.

With the current solution it is also impossible to get a `some_package.tar.gz` as the target names of the `npm_package` and `pkg_tar` would collide in that case.

### Describe the solution you'd like

Ideally we'd use the internal pack feature of `npm` to ensure the generated package is the same as what would be published to npm.

**Comment by alexeagle** [comment]
pkg_npm has a .pack verb now
