### ISSUE TITLE
@bazel/inject-html is not published on npmjs.org

### ISSUE THREAD

**Issue by zaucy** [bazelbuild/rules_nodejs#1393]
I noticed while using the angular example as reference for starting a project that the package `@bazel/inject-html` was not published (at least publicly) on npm.

https://www.npmjs.com/package/@bazel/inject-html

**Comment by alexeagle** [comment]
yeah, sorry, we are in a transition where that rule is used to make our example work, but we don't want to publish/maintain such a thing. We are switching to the npmjs.com/html-insert-assets package by @jbedard see https://github.com/jbedard/rules_nodejs/commit/da53e28ae5a68319762c3dd5672965bc8ec39e5b
Hopefully can land that today.
