### ISSUE TITLE
Node realpath crashs when executing jest inside of Bazel

### ISSUE THREAD

**Issue by mrmeku** [bazelbuild/rules_nodejs#1401]
# 🐞 bug report

### Affected Rule
`npm_package_bin`

### Is this a regression?
No

### Description
When executing jest inside of bazel, Node crashes. Specifically it crashes when trying to resolve real files on this line: https://github.com/nodejs/node/blob/master/src/node_file.cc#L1336

This line tries to ensure that the number of arguments passed to `fs.realpath` is greater than or equal to 3. But somehow, this is not the case when running jest within bazel. Not the most useful hint as to what's going on. 

My best guess as to what's happening here is that jest makes heavy use of node's fs.realpath.native. Unlike all the other realpath functions, this one is not being patched by https://github.com/bazelbuild/rules_nodejs/blob/master/packages/node-patches/src/fs.ts

fs.realpath vs fs.realpath.native: The maximum number of symbolic links is platform-independent and generally (much) higher than what the native realpath(3) implementation supports.

It could be that bazel's heavy use of symlinks causes fs.realpath.native to choke as it may go over the threshold for symlinks it supports. 

## 🔬 Minimal Reproduction
I've made a branch here: https://github.com/mrmeku/prototype-nx-bazel/tree/demo-jest-error
which can reproduce the error. 

Run `bazel build //apps/angularapp:test`. This will invoke `jest` and produce the error.

## 🔥 Exception or Error

<pre><code>
ng test angularapp[25682]: ../src/node_file.cc:1337:void node::fs::RealPath(const FunctionCallbackInf
o<v8::Value> &): Assertion `(argc) >= (3)' failed.
 1: 0x10007e743 node::Abort() [/private/var/tmp/_bazel_mrmeku/2862b1b0ca0f4fada19488b52142c2e3/sandbox/darwin-sandbox/13/execroot/prototype_nx_bazel/bazel-out/host/bin/external/npm/@angular/cli/bin/ng.sh.runfiles/nodejs_darwin_amd64/bin/nodejs/bin/node]
 2: 0x10007e4eb node::AppendExceptionLine(node::Environment*, v8::Local<v8::Value>, v8::Local<v8::Message>, node::ErrorHandlingMode) [/private/var/tmp/_bazel_mrmeku/2862b1b0ca0f4fada19488b52142c2e3/sandbox/darwin-sandbox/13/execroot/prototype_nx_bazel/bazel-out/host/bin/external/npm/@angular/cli/bin/ng.sh.runfiles/nodejs_darwin_amd64/bin/nodejs/bin/node]
 3: 0x10008bfe0 node::fs::RealPath(v8::FunctionCallbackInfo<v8::Value> const&) [/private/var/tmp/_bazel_mrmeku/2862b1b0ca0f4fada19488b52142c2e3/sandbox/darwin-sandbox/13/execroot/prototype_nx_bazel/bazel-out/host/bin/external/npm/@angular/cli/bin/ng.sh.runfiles/nodejs_darwin_amd64/bin/nodejs/bin/node]
 4: 0x1001e1480 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/private/var/tmp/_bazel_mrmeku/2862b1b0ca0f4fada19488b52142c2e3/sandbox/darwin-sandbox/13/execroot/prototype_nx_bazel/bazel-out/host/bin/external/npm/@angular/cli/bin/ng.sh.runfiles/nodejs_darwin_amd64/bin/nodejs/bin/node]
 5: 0x1001e0a5f v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/private/var/tmp/_bazel_mrmeku/2862b1b0ca0f4fada19488b52142c2e3/sandbox/darwin-sandbox/13/execroot/prototype_nx_bazel/bazel-out/host/bin/external/npm/@angular/cli/bin/ng.sh.runfiles/nodejs_darwin_amd64/bin/nodejs/bin/node]
 6: 0x1001e0160 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/private/var/tmp/_bazel_mrmeku/2862b1b0ca0f4fada19488b52142c2e3/sandbox/darwin-sandbox/13/execroot/prototype_nx_bazel/bazel-out/host/bin/external/npm/@angular/cli/bin/ng.sh.runfiles/nodejs_darwin_amd64/bin/nodejs/bin/node]
 7: 0x10092fcd9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/private/var/tmp/_bazel_mrmeku/2862b1b0ca0f4fada19488b52142c2e3/sandbox/darwin-sandbox/13/execroot/prototype_nx_bazel/bazel-out/host/bin/external/npm/@angular/cli/bin/ng.sh.runfiles/nodejs_darwin_amd64/bin/nodejs/bin/node]
Target //apps/angularapp:test failed to build
</code></pre>

**Output of `bazel version`: 1.1.0

<pre>
  <code>
Build label: 1.1.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Oct 21 21:09:45 2019 (1571692185)
Build timestamp: 1571692185
Build timestamp as int: 1571692185
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "c612d6b76eaa17540e8b8c806e02701ed38891460f9ba3303f4424615437887a",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/0.42.1/rules_nodejs-0.42.1.tar.gz"],
)
  </code>
</pre>

**Anything else relevant?**

**Comment by marcus-sa** [comment]
Did you add the patches required for jest to work?
https://github.com/bazelbuild/rules_nodejs/tree/master/examples/jest/tools/patches
