### ISSUE TITLE
Ability to control the extension of entrypoints 

### ISSUE THREAD

**Issue by thesayyn** [bazelbuild/rules_nodejs#1404]
# 🚀 Feature request
With node 13 es modules have become supported without the flag. However, to able to run a file as "es module" instead of commonjs you need to change the extension of the js file to .mjs which is not supported by rollup_bundle currently.

### Relevant Rules
rollup_bundle 
-->

### Description

Currently, the rollup_bundle rule doesn’t have the ability to output files with different extensions (.cjs or .mjs) rather than .js.

### Describe the solution you'd like
I've thought about a solution that simply checks if the output file name already has an extension before putting the .js extension as a suffix. If it does it won't append '.js' as a suffix.

The logic will be done at https://github.com/bazelbuild/rules_nodejs/blob/master/packages/rollup/src/rollup_bundle.bzl#L227
 

### Describe alternatives you've considered

- Write a genrule that renames the output files

**Comment by gregmagolan** [comment]
That would be a useful feature to allow for an `.mjs` output.

The API shape for that would have to be:

```
rollup_bundle(
    name = "bundle",
    entry_points = {
        "index.js": "bundle.mjs"
    }
)
```

as

```
rollup_bundle(
    name = "bundle",
    entry_point = "index.js",
)
```

assumes a `bundle.js` output.

To test if the output file has an extension we'd have to test for a set of expected extensions such as `['.mjs']` since the output filename could be `my.bundle`.

Finally, the `.map` output file key just below L227 would need to take into account the extension `out`:

```
        if sourcemap == "true":
            result[out_without_extension + "_map"] = "%s.map" % result[out]
```

@alexeagle May have some better ideas but I think this would be a useful addition.

**Comment by thesayyn** [comment]
@gregmagolan I would like to work on if @alexeagle eagle has no other ideas.

**Comment by marcus-sa** [comment]
@thesayyn what would be the reason for allowing this behavior ?
In any environment you'd use differential loading, so the extension difference wouldn't really make sense.
The node and browser resolution doesn't have the same behavior anyway.

**Comment by evahowe** [comment]
@thesayyn and @gregmagolan - what is the status of this?

**Comment by alexeagle** [comment]
Sorry I didn't see this earlier, that proposal sounds fine to me!

**Comment by thesayyn** [comment]
@evahowe @alexeagle I would happily send a PR for this. Probably this a few days later.

**Comment by thesayyn** [comment]
this is still relevant IMHO. This shouldn't be closed.
