### ISSUE TITLE
Jest's example but with Typescript

### ISSUE THREAD

**Issue by AnatoleLucet** [bazelbuild/rules_nodejs#1405]
This is a following to [this Stackoverflow post](https://stackoverflow.com/questions/59059699/testing-with-jest-in-typescript-using-a-bazel-custom-rule) I've asked two days ago, but I can't find any answer.

Basically I'm trying to test some Typescript code using Jest. I thought I could compile my Typescript files with the `ts_library` rule then pass the label to the Jest rule I've found in [this example](https://github.com/bazelbuild/rules_nodejs/tree/master/examples/jest) but the Jest seems to only receive the `.d.ts` files.

You can find all the code on the Stackoverflow post so you can reproduce the issue.

Here's my `WORKSPACE` file which I haven't shown on Stackoverflow:
```python
exports_files([
    "tsconfig.json",
    "package.json"
], visibility = ["//visibility:public"])
```

And also my root's `BUILD.bazel` (my `tsconfig.json` is empty):
```python
exports_files([
    "tsconfig.json",
    "package.json",
    "jest.config.js"
], visibility = ["//visibility:public"])
```

**Comment by AnatoleLucet** [comment]
Fixed: https://stackoverflow.com/a/59110339/8990411

**Comment by WesleyYue** [comment]
Did you also figure out how to import another typescript module within `src/foo.test.ts`?

**Comment by AnatoleLucet** [comment]
@WesleyYue I haven't tried. Did you include it in `ts_library`?

**Comment by WesleyYue** [comment]
I actually figured it out. Example repo [here](https://github.com/WesleyYue/ts-jest-repro) for any future ppl stumbling across this.
