### ISSUE TITLE
Cannot use rollup_bundle on ts_library because of .externs.js files.

### ISSUE THREAD

**Issue by sly010** [bazelbuild/rules_nodejs#1416]
# Affected Rule
ts_library -> rollup_bundle

### Description

I am trying to `rollup_bundle()` a `ts_library()`. `ts_library` by default provides `.d.ts` files, so I am requesting `es6_sources` with a `filegroup` as documented.
Even if I separate my entry point to a single-file `ts_library` es6_sources produces 2 files:
```
bazel-bin/bar/appfoo.mjs
bazel-bin/bar/appfoo-ts.externs.js
```

Specifying `generate_externs = False` for ts_library didn't effect anything.
That second file is empty.

### Is this a regression?
Maybe. Possibly related to: https://github.com/bazelbuild/rules_nodejs/issues/757

## 🔬 Minimal Reproduction

```
ts_library(
    name = "libfoo-ts",
    srcs = glob([
        "libfoo.ts",
    ]),
)

filegroup(
    name = "libfoo-es6",
    srcs = ["libfoo-ts"],
    output_group = "es6_sources",
)

ts_library(
    name = "appfoo-ts",
    srcs = ["appfoo.ts"],
    deps = [
        "libfoo-ts",
    ],
)

filegroup(
    name = "appfoo-es6",
    srcs = ["appfoo-ts"],
    output_group = "es6_sources",
)

rollup_bundle(
    name = "appfoo-bundle",
    srcs = ["libfoo-es6"],
    entry_point = "appfoo-es6",
)
```

## 🔥 Exception or Error

``` In entry_point attribute of rollup_bundle rule //bar:appfoo-bundle: '//bar:appfoo-es6' must produce a single file```

**Operating System:**
```macos```

**Output of `bazel version`:**
```
Build label: 0.26.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue May 28 08:38:24 2019 (1559032704)
Build timestamp: 1559032704
Build timestamp as int: 1559032704
```

**Rules version (SHA):**
c612d6b76eaa17540e8b8c806e02701ed38891460f9ba3303f4424615437887a

**Comment by gregmagolan** [comment]
The ts_library targets should get added to the `deps` of rollup_bundle like so:

```
ts_library(
    name = "libfoo-ts",
    srcs = glob([
        "libfoo.ts",
    ]),
)

ts_library(
    name = "appfoo-ts",
    srcs = ["appfoo.ts"],
    deps = [
        "libfoo-ts",
    ],
)

rollup_bundle(
    name = "appfoo-bundle",
    deps = ["libfoo-es6"],
    entry_point = "appfoo.ts",
)
```

The rollup_bundle rule handles selecting the correct outputs from ts_library. The entry_point can be specified as the `.ts` file and `rollup_bundle` will handle the mapping to the `.mjs` output file.

I'm assuming here you're using the new rollup_bundle rule from `@bazel/rollup` and not the legacy rollup_bundle rule. Migration guide is here if needed: https://github.com/bazelbuild/rules_nodejs/wiki#migrating-off-internalrollup

**Comment by sly010** [comment]
It makes total sense and is very ergonomic.

There should probably be a note in the documentation about this.
I had a hard time understanding rollup_bundle.bzl, but knowing this makes it all clear.
