### ISSUE TITLE
Jest modules resolution

### ISSUE THREAD

**Issue by AnatoleLucet** [bazelbuild/rules_nodejs#1418]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: `jest-cli`

### Is this a regression?

No, it isn't.

### Description

`jest-resolve` can't resolve files compiled by `ts_library`.
Maybe this is related to #1408 and #1385 but I'm not sure.

## 🔬 Minimal Reproduction

Clone: https://github.com/AnatoleLucet/issue-bazel-jest
And do a `bazel run //src:test`

## 🔥 Exception or Error

<pre><code>
Executing tests from //src:test
-----------------------------------------------------------------------------
FAIL src/myModule.test.js
  ● Test suite failed to run

    Cannot find module 'issue_bazel_jest/src/myModule' from 'myModule.test.js'

      at Resolver.resolveModule (../npm/node_modules/jest-resolve/build/index.js:259:17)
      at ../../myModule.test.ts:1:1
      at src/myModule.test.js:3:13
      at Object.<anonymous> (src/myModule.test.js:8:3)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.815s
Ran all test suites within paths "src/myModule.js", "src/myModule.test.js".
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Distributor ID: LinuxMint
Release:        19.2
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 0.29.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Sep 10 13:44:39 2019 (1568123079)
Build timestamp: 1568123079
Build timestamp as int: 1568123079
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "16fc00ab0d1e538e88f084272316c0693a2e9007d64f45529b82f6230aedb073",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/0.42.2/rules_nodejs-0.42.2.tar.gz"],
)
  </code>
</pre>

**Comment by alexeagle** [comment]
You need the latest release 0.42.3 to get the "linker" to run inside jest_test - this should create `$pwd/node_modules/issue_bazel_jest` directory for the jest-resolve plugin to find.

I did that update in your repro and run with `--define=VERBOSE_LOGS=1` to get more info:

```
==================== Test output for //src:test:
[link_node_modules.js] module manifest: workspace issue_bazel_jest, bin bazel-out/darwin-fastbuild/bin, root npm/node_modules with first-party packages
 { issue_bazel_jest: [ 'bin', 'issue_bazel_jest' ] }
[link_node_modules.js] found legacy_external_runfiles, switching root to external/npm/node_modules
[link_node_modules.js] resolved root npm/node_modules to external/npm/node_modules
[link_node_modules.js] cwd /private/var/tmp/_bazel_alexeagle/05143d19e34b69a608c14aa921f8d324/execroot/issue_bazel_jest/bazel-out/darwin-fastbuild/bin/src/test.sh.runfiles/issue_bazel_jest
[link_node_modules.js] symlink( node_modules -> external/npm/node_modules )
[link_node_modules.js] grouped mappings [[{"name":"issue_bazel_jest","root":"bin","modulePath":"issue_bazel_jest"}]]
[link_node_modules.js] symlink( issue_bazel_jest -> /private/var/tmp/_bazel_alexeagle/05143d19e34b69a608c14aa921f8d324/execroot/issue_bazel_jest/bazel-out/darwin-fastbuild/bin/src/test.sh.runfiles/issue_bazel_jest/bazel-out/darwin-fastbuild/bin )
bazel node patches enabled. root: /private/var/tmp/_bazel_alexeagle/05143d19e34b69a608c14aa921f8d324/execroot/issue_bazel_jest/bazel-out/darwin-fastbuild/bin/src/test.sh.runfiles symlinks in this directory will not escape
FAIL src/myModule.test.js
  ● Test suite failed to run

    Cannot find module 'issue_bazel_jest/src/myModule' from 'myModule.test.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at ../../myModule.test.ts:1:1
      at src/myModule.test.js:3:13
      at Object.<anonymous> (src/myModule.test.js:8:3)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.571s
Ran all test suites within paths "src/myModule.js", "src/myModule.test.js".
================================================================================
```

So that's disappointing; I expected that would fix it.

**Comment by AnatoleLucet** [comment]
Strange, I've also tried it on my side but rule doesn't seems to create a `$pwd/node_modules/issue_bazel_jest` folder. I've also checked in the cache but I can't find it.
Is it the same for you?

**Comment by alexeagle** [comment]
in this case $pwd is in the runfiles - see the path printed by the linker, in my case it was `/private/var/tmp/_bazel_alexeagle/05143d19e34b69a608c14aa921f8d324/execroot/issue_bazel_jest/bazel-out/darwin-fastbuild/bin/src/test.sh.runfiles`

**Comment by marcus-sa** [comment]
What you need to do is put your workspace name in `moduleNameMapper` in your jest config and then it'll work.

**Comment by AnatoleLucet** [comment]
@marcus-sa I've already tried that. It return me this exception:
```
Executing tests from //src:test
-----------------------------------------------------------------------------
FAIL src/myModule.test.js
  ● Test suite failed to run

    Configuration error:

    Could not locate module issue_bazel_jest/src/myModule mapped as:
    /home/anatole/.cache/bazel/_bazel_anatole/877c8a3378006f03794d52d3d67f7256/execroot/issue_bazel_jest/bazel-out/k8-fastbuild/bin/src/test.sh.runfiles/issue_bazel_jest.

    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/^issue_bazel_jest\/(.*)$/": "/home/anatole/.cache/bazel/_bazel_anatole/877c8a3378006f03794d52d3d67f7256/execroot/issue_bazel_jest/bazel-out/k8-fastbuild/bin/src/test.sh.runfiles/issue_bazel_jest"
      },
      "resolver": null
    }

      at createNoMappedModuleFoundError (node_modules/jest-resolve/build/index.js:501:17)
      at ../../myModule.test.ts:1:1
      at src/myModule.test.js:3:13

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.907s
Ran all test suites within paths "src/myModule.js", "src/myModule.test.js".
```

With this in my config file:
```js
moduleNameMapper: {
  '^issue_bazel_jest/(.*)$': '<rootDir>'
}
```

I assume `jest-cli` is already doing this.

**Comment by marcus-sa** [comment]
@AnatoleLucet you need to provide it with `<rootDir>/$1` and not `<rootDir>` my bad.
This has nothing to do with Jest, but the way TypeScript flattens your require paths.

**Comment by AnatoleLucet** [comment]
That worked. Thanks you! So in the future there will be no more need to add the `moduleNameMapper` in the config?

**Comment by marcus-sa** [comment]
@AnatoleLucet if you use `module_name` in your `ts_library` you'd still have to do the same, because the module mapped paths doesn't get resolved to their prior path at compile time.
```
module.exports = {
  testEnvironment: 'node',
  testMatch: ['**/*.spec.js'],
  collectCoverage: true,
  moduleNameMapper: {
    '@sa/prisma/(.*)': '<rootDir>/libs/prisma/$1.js',
    '@sa/prisma': '<rootDir>/libs/prisma/index.js',
    'sa_dashboard/(.*)': '<rootDir>/$1',
  },
};
```
