### ISSUE TITLE
rules_nodejs broken with Bazel@HEAD+Downstream

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/rules_nodejs#1424]
rules_nodejs is broken with Bazel@HEAD+Downstream on buildkite and has been for about 3 weeks

Recent failure:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1296#780c785d-f69f-4c75-b003-1fc9be09a577

I ran a [bisect](https://buildkite.com/bazel/culprit-finder/builds/242#_) for around [the time of first failure](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1278#0f898d90-6a0b-4897-8fbd-a5e0f79ea9c0), and was unable to reproduce the failure in a bisect...

**Comment by alexeagle** [comment]
`dist/rules_nodejs/dist/rules_nodejs/dist/rules_nodejs/dist/rules_nodejs/dist/rules_nodejs/dist/rules_nodejs/dist/rules_nodejs/dist/rules_nodejs/dist/rules_nodejs/dist/rules_nodejs/dist/rules_nodejs/dist/rules_nodejs/dist/rules_nodejs/dist/rules_nodejs/dist/rules_nodejs/p` looks like we got recursive symlinks somehow. the `dist` folder is in `.bazelignore` so maybe something changed there?
We are busy getting our 1.0 out and doing bazelcon prep so it will be hard to dig into this for a little while.
