### ISSUE TITLE
karma: karma_web_test rule executable is not working on windows

### ISSUE THREAD

**Issue by devversion** [bazelbuild/rules_nodejs#1429]
It looks like the executable produced by `karma_web_test` is a simple Bash script. This does not work on Windows because Bazel just launches tries to spawn the script while it does not have the `.sh` extension (which would slightly help windows figuring out how to launch it).

Ideally though, either a `.bat` script is created (as done in other executable IIRC), or the script is wrapped by `native.sh_test`.

**Comment by KrauseStefan** [comment]
I also experience this issue, I don't think the documentation is very clear on when to use `karma_web_test` and when to use `karma_web_test_suite`.
There is no example where `karma_web_test` is used either as far as I can tell.

In general I've found the karma documentation quite hard to understand and use.
