### ISSUE TITLE
karma: allow overwriting default reporter

### ISSUE THREAD

**Issue by devversion** [bazelbuild/rules_nodejs#1431]
Currently when specifying a custom karma configuration file in a `karma_web_test` target, the configured reporters will be used _in addition_ to the `progress` reporter. `@bazel/karma` always sets up the progress reporter.

This has implications because if multiple browsers run as part of a single Karma instance (e.g. running on saucelabs), the output will be very unreadable as every reporter prints a new line on spec completion.

**Comment by evahowe** [comment]
@devversion - What exactly are you looking to happen here?

**Comment by devversion** [comment]
@evahowe I expect the default karma configuration to not add any reporter if reporters have been explicitly set in the user karma configuration: https://github.com/bazelbuild/rules_nodejs/blob/stable/packages/karma/karma.conf.js#L170
