### ISSUE TITLE
Allow alternate JSX modes for ts_library

### ISSUE THREAD

**Issue by joeljeske** [bazelbuild/rules_nodejs#1434]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule:  `ts_library`

### Is this a regression?

 No

### Description

 I would like to set "jsx: preserve" in my tsconfig. It would appear that this option is always overridden to "jsx: react" in the generated tsconfig.

## 🔬 Minimal Reproduction

* Set "jsx: preserve" in your tsconfig.json
* Compile a TSX file that has JSX in it
* See that the outputted file does not contain the JSX, but is converted to the function form

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS 10.14.6
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 1.2.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Nov 20 15:08:12 2019 (1574262492)
Build timestamp: 1574262492
Build timestamp as int: 1574262492
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>

  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
The easiest way to solve it is to patch the package, I like to use https://www.npmjs.com/package/patch-package which makes it really easy to capture your edits in node_modules in a way that's reproducible for co-workers and CI.
(note that you might need to `bazel clean --expunge` to force the npm package to be reinstalled into `@npm_bazel_typescript` workspace)

**Comment by joeljeske** [comment]
This is unfortunate; but I did end up patching your package as you suggested. Would you accept a PR? It was mostly straight-forward, with a couple of changes to rename .jsx files from TSC to the proper .mjs or .js depending on context.
