### ISSUE TITLE
Where is the source code of @bazel/typescript/devserver/devserver-linux_x64 binary?

### ISSUE THREAD

**Issue by ouchuji** [bazelbuild/rules_nodejs#1437]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 
@npm_bazel_typescript/internal/devserver/ts_devserver.bzl:ts_devserver

### Is this a regression?

 No

### Description

 I have already used `@build_bazel_rules_typescript ///devserver:devserver-linux` to replace the binary at ts_deverser attr `devserver` and `devserver_host`, but it can not run as expected. So I think the code at `@build_bazel_rules_typescript ` is not the source code of the devserver binary, can you tell me where I can find the souce code of the devserver binary? I want to build it from the source code in order to add some custom features. Thanks!

## 🔥 Exception or Error
The error when use the binary built from `@build_bazel_rules_typescript ///devserver:devserver-linux`
<pre><code>

Could not find runfile logi/../npm_bazel_typescript/third_party/npm/requirejs/require.js, got error Runfile logi/../npm_bazel_typescript/third_party/npm/requirejs/require.js: could not locate fileFailed to read script logi/../npm_bazel_typescript/third_party/npm/requirejs/require.js: open : no such file or directory
Could not find runfile logi/examples/angular/helloworld/_app.dev_launcher.amd_names_shim.js, got error Runfile logi/examples/angular/helloworld/_app.dev_launcher.amd_names_shim.js: could not locate fileFailed to read script logi/examples/angular/helloworld/_app.dev_launcher.amd_names_shim.js: open : no such file or directory
Could not find runfile logi/tools/build_rules/ng/rxjs_shims.js, got error Runfile logi/tools/build_rules/ng/rxjs_shims.js: could not locate fileFailed to read script logi/tools/build_rules/ng/rxjs_shims.js: open : no such file or directory
Could not find runfile logi/../npm/node_modules/rxjs/bundles/rxjs.umd.js, got error Runfile logi/../npm/node_modules/rxjs/bundles/rxjs.umd.js: could not locate fileFailed to read script logi/../npm/node_modules/rxjs/bundles/rxjs.umd.js: open : no such file or directory
Could not find runfile logi/../npm/node_modules/tslib/tslib.js, got error Runfile logi/../npm/node_modules/tslib/tslib.js: could not locate fileFailed to read script logi/../npm/node_modules/tslib/tslib.js: open : no such file or directory
Could not find runfile logi/examples/angular/helloworld/__app_require.config.js, got error Runfile logi/examples/angular/helloworld/__app_require.config.js: could not locate fileFailed to read script logi/examples/angular/helloworld/__app_require.config.js: open : no such file or directory
Server listening on http://chuji:5432/
could not resolve path logi/examples/angular/helloworld/_hello_world_bootstrap.dev.ngfactory.js. Runfile logi/examples/angular/helloworld/_hello_world_bootstrap.dev.ngfactory.js: could not locate file

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubutu18.04
  </code>
</pre>

**Output of `bazel version`:**
<pre>
  <code>
1.2.1
  </code>
</pre>

**Rules version (SHA):**
0.42.2

<pre>
  <code>
16fc00ab0d1e538e88f084272316c0693a2e9007d64f45529b82f6230aedb073
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
Sources are at https://github.com/bazelbuild/rules_typescript/tree/master/devserver

does that solve your problem?

**Comment by ouchuji** [comment]
Thank you for your confirming, but my problem is not solved, I use the command

 `bazel build @build_bazel_rules_typescript//devserver:devserver-linux`

to build the linux devserver binary,  and use it to replace of the binary at 
`build/output_base/external/npm_bazel_typescript/devserver/devserver-linux_x64`

and the devserver is not run as normaly, it print the error below:
```bash
 $ bazel run   examples/angular/helloworld:app.dev
INFO: Invocation ID: 5ecb2b9b-841c-46da-8d5c-9730f6e311cf
INFO: Analyzed target //examples/angular/helloworld:app.dev (999 packages loaded, 41906 targets configured).
INFO: Found 1 target...
INFO: Writing explanation of rebuilds to 'build/logs'
Target //examples/angular/helloworld:app.dev up-to-date:
  build/bin/examples/angular/helloworld/app.dev_launcher.sh
  build/bin/examples/angular/helloworld/app.dev
INFO: Elapsed time: 2.094s, Critical Path: 0.09s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Could not find runfile logi/../npm_bazel_typescript/third_party/npm/requirejs/require.js, got error Runfile logi/../npm_bazel_typescript/third_party/npm/requirejs/require.js: could not locate fileFailed to read script logi/../npm_bazel_typescript/third_party/npm/requirejs/require.js: open : no such file or directory
Could not find runfile logi/examples/angular/helloworld/_app.dev_launcher.amd_names_shim.js, got error Runfile logi/examples/angular/helloworld/_app.dev_launcher.amd_names_shim.js: could not locate fileFailed to read script logi/examples/angular/helloworld/_app.dev_launcher.amd_names_shim.js: open : no such file or directory
Could not find runfile logi/tools/build_rules/ng/rxjs_shims.js, got error Runfile logi/tools/build_rules/ng/rxjs_shims.js: could not locate fileFailed to read script logi/tools/build_rules/ng/rxjs_shims.js: open : no such file or directory
Could not find runfile logi/../npm/node_modules/rxjs/bundles/rxjs.umd.js, got error Runfile logi/../npm/node_modules/rxjs/bundles/rxjs.umd.js: could not locate fileFailed to read script logi/../npm/node_modules/rxjs/bundles/rxjs.umd.js: open : no such file or directory
Could not find runfile logi/../npm/node_modules/tslib/tslib.js, got error Runfile logi/../npm/node_modules/tslib/tslib.js: could not locate fileFailed to read script logi/../npm/node_modules/tslib/tslib.js: open : no such file or directory
Could not find runfile logi/examples/angular/helloworld/__app_require.config.js, got error Runfile logi/examples/angular/helloworld/__app_require.config.js: could not locate fileFailed to read script logi/examples/angular/helloworld/__app_require.config.js: open : no such file or directory
Server listening on http://chuji:5432/
```
It seems like that the binary build from the source code is not correct, so I want to know how can build the correct binary from the devserver souce code.

**Comment by alexeagle** [comment]
Sorry I dropped this, it looks like you've got a rules_go helper for Runfiles that doesn't work with ts_devserver. My guess is you're missing this patch https://github.com/bazelbuild/rules_typescript/blob/master/revert_rules_go_commit_4442d82a001f378d0605cbbca3fb529979a1c3a6.patch
(there was a breaking change in rules_go that dropped a feature we need, and no one has had time to re-implement on the latest rules_go so I reverted the commit locally)

**Comment by alexeagle** [comment]
Please let me know if you're still working on this, I know the issue is from a long time ago
