### ISSUE TITLE
Allow data files to rollup_bundle

### ISSUE THREAD

**Issue by duarten** [bazelbuild/rules_nodejs#1444]
# 🚀 feature request

### Relevant Rules

rollup_bundle()

### Description

Rollup can be used with certain plugins that depend on files. For example, `rollup-plugin-babel` requires a `.babelrc` file in the src directory.

### Describe the solution you'd like

A data attribute like other rules have.

### Describe alternatives you've considered

I tried using a `filegroup` as a dependency, but that didn't work:

```python
filegroup(
    name = "babel-config",
    srcs = ["src/.babelrc"],
)

rollup_bundle(
    name = "bundle",
    config_file = "rollup.config.js",
    entry_point = "src/index.ts",
    format = "iife",
    output_dir = True,
    sourcemap = "inline",
    deps = [
        ":lib",
        ":babel-config",
        "@npm//@rollup/plugin-node-resolve",
        "@npm//rollup-plugin-babel",
        "@npm//rollup-plugin-commonjs",
    ],
)
```

**Comment by marcus-sa** [comment]
Babel can only resolve configuration files at workspace level.

**Comment by duarten** [comment]
I haven't tried that yet, seems like a good workaround.

According to https://babeljs.io/docs/en/config-files, `.babelrc` is loaded relative to the file being compiled. Indeed, it works fine outside of the Bazel sandbox.

**Comment by marcus-sa** [comment]
I had to put my `.babelrc` at the root (when invoking `@babel/cli` otherwise it just couldn't find it.

**Comment by joeljeske** [comment]
Another option is to pass the values of .babelrc directly to the rollup-plugin-plugin when configuring it for rollup.

**Comment by alexeagle** [comment]
Remember that to benefit from Bazel's incrementality, you may want to run babel independently of rollup. This way, if the babel output doesn't change during a re-build, rollup doesn't have to be invoked at all.

**Comment by duarten** [comment]
Babel and rollup are both invoked as part of the source files changing (or dependencies changing), so it's not clear to me how we could benefit from incrementality. 

Besides, https://github.com/rollup/rollup-plugin-babel presents some arguments why using the plugin is preferred to running Babel then Rollup or vice-versa.

**Comment by marcus-sa** [comment]
I use Babel for differential loading.
I use `rollup-plugin-babel` specifically for their `@babel/preset-modules` and then for differential loading I compile ES2018 down to ES5 and use SystemJS

**Comment by evahowe** [comment]
@duarten - Can we close this?  Is it resolved?

**Comment by duarten** [comment]
@evahowe It's not resolved per se, but there's a workaround, which is to use the src attribute.

**Comment by evahowe** [comment]
ok, then I will mark it appropriately :)
