### ISSUE TITLE
NPM modules can be required from npm/node_modules

### ISSUE THREAD

**Issue by mrmeku** [bazelbuild/rules_nodejs#1447]
Reproduction:
https://github.com/mrmeku/prototype-nx-bazel/commit/0b090725039fe597db1afeccf757d6e136576ccb

Checkout the repo at the above commit.
Run `bazel test //apps/cart:test`

Examine the stacktrace to see the following lines of interest

`at batchedUpdates$1 (../../../npm/node_modules/react-dom/cjs/react-dom.development.js:24328:12)
      at act (../../../npm/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1120:14)
      at Object.render (../../node_modules/@testing-library/react/dist/pure.js:82:26)
      at Object.<anonymous> (src/app/app.spec.tsx:12:29)`

Notice that the following has occured:
  - A linked npm module `@testing-library/react` attempts to import a library called `react-dom` (here is the line of interest: https://github.com/testing-library/react-testing-library/blob/c48b501bf683faae6fcf9cadb7ee96fc0da319ba/src/pure.js#L2)
  - The resolved module comes from `npm/node_modules` rather than from the linked node_modules directory

This causes problems in many packages. For react, an invariant of a workspace is that you only have one version of react installed. Because we have one linked copy and one copy within `npm` we have two copies and break that invariant.

I'm still confused how modules can be required from `npm` since the node modules resolution algorithm would not allow for that.

**Comment by evahowe** [comment]
@mrmeku - can this get closed since it was addressed in #1505?
