### ISSUE TITLE
Right way to exec nodejs_binary from sh_binary

### ISSUE THREAD

**Issue by lazdmx** [bazelbuild/rules_nodejs#1451]
Is there a **right** way to exec `nodejs_binary` from `sh_binary` script? I didn't find any examples or hints about how to do it so  I've spent some time digging in guts of `rules_nodejs` and I successfully executed `electron` along with other tools, but I think that my solution it is not correct.

Problems come from RUNFILES since they are resolved in context of main script, so I have to `cd` into tool's directory before I call it (and don't forget to feed `*/external/*` paths to `$(rlocation ...)`). Also, it is important to note that Bazel do not prepares RUNFILES for tools  we depend on (I mean `data` attribute of `sh_binary`) so these tools have to be executed  upfront in order to get theirs RUNFILES in context.

So, these inconveniences make me think that:

- possibly I'm trying to use Bazel and `nodejs_binary` rule in wrong way, actually making things up side down and it is better to call Bazel and run `nodejs_binary` targets from Shell-script, OR

- it is right way to have only Bazel `build/run` but calling  `nodejs_binary` from `sh_binary` script is somehow blocked and waiting to be implemented in future, OR

- it actually is a right way  to exec `nodejs_binary` from `sh_binary` (for today), OR

- something that I didn't mention in that list

So I'm not sure if there is an issue for this repo, but at least there are some things that have to be clarified in documentation.

**Comment by alexeagle** [comment]
Bazel runfiles are certainly complex and hard to hold correctly.

I'm not sure what bug is reported here though. I think you're reporting that 

```
nodejs_binary(
    name = "my_nodejs_binary",
    data = ["data.json"],
)

sh_binary(
  data = [":my_nodejs_binary"],
)
```

the data.json file doesn't appear in the runfiles manifest of the sh_binary? I'm surprised from reading the return value of _nodejs_binary_impl which seems to propagate everything into the runfiles of the result.

Can you give a bit more detail about your use case? Maybe we can add an example in the repo that illustrates how to solve that problem.

**Comment by lazdmx** [comment]
Here is a use case snippet:

```python
sh_binary(
    name = "starter",
    srcs = ["starter.sh"],
    data = [
        ":app_files",
        "@bazel_tools//tools/bash/runfiles",
        "@npm//electron/bin:electron",
        "@npm//json-schema-to-typescript/bin:json2ts",
    ],
)

sh_library(
    name = "app_files",
    srcs = [
        "main.js",
        "package.json",
    ] + glob(["src/**"]),
)
```


And here is a part of `starter.sh`
```shell
set -eu -o pipefail
...
...
# --- end runfiles.bash initialization ---

cd $(dirname $(rlocation <workspace>/external/npm/electron/bin/electron))
$(rlocation <workspace>/external/npm/electron/bin/electron) <...ARGS>

...

cd $(dirname $(rlocation <workspace>/external/npm/json-schema-to-typescript/bin/json2ts))
$(rlocation <workspace>/external/npm/json-schema-to-typescript/bin/json2ts) <...ARGS>
```

As I said before it is important to execute tools from directories where theirs runtime files exist, so I do `cd` as workaround. But, I would accept this behaviour as inconvenient but reasonable since in other way Bazel would do a host of work of bringing tool's context info context of main script, which will affect build speed and disk usage. Most suspicion point here is that build reproducibility is suffered, since orders of target execution becomes significant. For instance, this commands will lead to error

```shell
bazel clean
bazel run //abcde:starter # >>>> FAIL: RUNFILES environment variable is not set. <<<<
```

But if I do

```shell
bazel clean
bazel run -- @npm//electron/bin:electron -v
bazel run -- @npm//json-schema-to-typescript/bin:json2ts -h
bazel run //abcde:starter # OK now
```

**Comment by lazdmx** [comment]
I forget say that I use `rules_nodejs@0.34.0`. Didn't check this code with latest version.

```
Build label: 1.2.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Nov 20 15:08:12 2019 (1574262492)
Build timestamp: 1574262492
Build timestamp as int: 1574262492
```

**Comment by alexeagle** [comment]
why do you use a shell script to orchestrate these two tools rather than
```
load("@npm//electron:index.bzl", "electron")
load("@npm//json-schema-to-typescript:index.bzl", "json2ts")

electron(
srcs
outs
)
json2ts(
data
outs
)
```
 or so, such that Bazel orchestrates the two binaries?

The bazel approach is incremental but your shell script always does all the work

**Comment by lazdmx** [comment]
> why do you use a shell script to orchestrate these two tools rather than

It was just an excerpt, where only execution of nodejs binaries were shown. Such scripts, usually are short-lived creatures and used right after appearing of new workflow (process) I need to integrate/orchestrate since It is much faster and easier to tweak and log executions in shell. Finally, when all things are validated and all `--define` flags and configurations are known I move to implementing these scripts in Bazel. 

Usual use-cases are:

- I need to run two or more instances simultaneously (setting up test environment)
- I need to run binaries of different kinds (debug/release) simultaneously
- I want to validate new approach of doing something (chore)

**Comment by alexeagle** [comment]
Makes sense, I feel like we need a repro in one of the examples here and then to study it a bit to get the right usage pattern. I don't see a place where we currently call nodejs_binary from shell

**Comment by lazdmx** [comment]
I could make one for test. I'll post here a link later

**Comment by lazdmx** [comment]
Hi! There is an example repo https://github.com/lazdmx/rules_nodejs_1451

**Comment by lazdmx** [comment]
Still interested in it. Sorry for noise, but this comment is to prevent the issue being closed by the bot.
