### ISSUE TITLE
Jest Example fails on Windows

### ISSUE THREAD

**Issue by zjkipping** [bazelbuild/rules_nodejs#1454]
# 🐞 bug report

### Affected Rule

jest_test

### Is this a regression?

no

### Description

The jest_test rule fails on windows with the following error:

```
Error: Can't find a root directory while resolving a config file path.
Provided path to resolve: ./jest.config.js
```

## 🔬 Minimal Reproduction

https://github.com/bazelbuild/rules_nodejs/tree/master/examples/jest

running `bazel test ...`

## 🔥 Exception or Error

see above in explanation

## 🌍  Your Environment

**Operating System:**

Windows 10

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.1.0
Build label: 1.2.1
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Nov 26 15:24:17 2019 (1574781857)
Build timestamp: 1574781857
Build timestamp as int: 1574781857
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>
a54b2511d6dae42c1f7cdaeb08144ee2808193a088004fc3b464a04583d5aa2e
  </code>
</pre>

**Comment by alexeagle** [comment]
I suspect you need to copy jest.config.js to the output folder and then reference that copy.

See https://github.com/bazelbuild/rules_nodejs/blob/master/docs/Built-ins.md#copy_to_bin

**Comment by Socolin** [comment]
Hello

I got the same error, on windows trying to run jest tests.

So I tried to add `copy_to_bin` as you suggested @alexeagle but after some digging I found that jest is executed in `C:\users\$USER\_bazel_$USER\u3lrkeg4\execroot\<workspace-name>\bazel-out\x64_windows-fastbuild\bin\test.bat.runfiles\<workspace-name>` which is empty.

The directory `C:\users\$USER\_bazel_$USER\u3lrkeg4\execroot\<workspace-name>\bazel-out\x64_windows-fastbuild\bin\` seems well populated.

I found in the source, there is a comment about Windows

https://github.com/bazelbuild/rules_nodejs/blob/master/examples/jest/BUILD.bazel#L14

So I tried to add this argument and ran `bazel test test --enable_runfiles`. Then I get another error

```
INFO: Invocation ID: edecd830-ef9a-4fca-adc0-a20e5c3f1b25
INFO: Analyzed target //:test (503 packages loaded, 10582 targets configured).
INFO: Found 1 test target...
INFO: Deleting stale sandbox base C:/users/$USER/_bazel_$USER/olmlednd/sandbox
FAIL: //:test (see C:/users/$USER/_bazel_$USER/olmlednd/execroot/examples_jest/bazel-out/x64_windows-fastbuild/testlogs/test/test.log)
INFO: From Testing //:test:
==================== Test output for //:test:
ERROR: Manifest file C:\Users\$USER\_bazel_$USER\olmlednd\execroot\examples_jest\bazel-out\x64_windows-fastbuild\bin\test.bat.runfiles\examples_jest\test.bat.runfiles_manifest does not exist.
================================================================================
Target //:test up-to-date:
  dist/bin/test.sh
  dist/bin/test_loader.js
  dist/bin/test_require_patch.js
  dist/bin/test.bat
INFO: Elapsed time: 7.752s, Critical Path: 0.45s
INFO: 2 processes: 1 remote cache hit, 1 local.
INFO: Build completed, 1 test FAILED, 3 total actions
```

Do you have any hint, about what could go wrong ?

**Comment by lukasholzer** [comment]
@alexeagle When I go the folder `examples/jest` in the **rules_nodejs** and running `bazel run :test` it is working fine on macos and linux but on windows it is failing with:

![image](https://user-images.githubusercontent.com/11156362/92208284-28c3b200-ee8b-11ea-9d63-dfe691ea9622.png)

**Comment by lukasholzer** [comment]
Addition:

When I run it with verbose logs you can see that in the failing case it uses the `module_mappings.json` from a different location:

### Failing:

```
[link_node_modules.js] manifest file C:/users/administrator/_bazel_administrator/rgyky3dz/execroot/examples_jest/bazel-out/x64_windows-fastbuild/bin/_test.module_mappings.json
```

### Passing
```
[link_node_modules.js] manifest file c:/users/admini~1/_bazel~1/rgyky3dz/execroot/exampl~1/bazel-out/x64_windows-fastbuild/bin/test.bat.runfiles/examples_jest/_test.module_mappings.json
```
