### ISSUE TITLE
npm_package_bin - stdout as the output file

### ISSUE THREAD

**Issue by kylecordes** [bazelbuild/rules_nodejs#1466]
# 🚀 feature request

### Relevant Rules

`npm_package_bin()`

### Description

The documentation for this rule states “It must produce outputs. If you just want to run a program with bazel run, use the nodejs_binary rule.”

### Describe the solution you'd like

I'd like it to allow the stdout of the executed program to become the output, if no output file is specified. This could handle a variety of useful cases where the tool being executed does not produce a file.

### Describe alternatives you've considered

This could be done with a `gen_rule()` as usual. Ugh.

**Comment by alexeagle** [comment]
yeah that's interesting. Bazel does a bad job with programs that produce their result on stdout.
I would imagine there should be an boolean attribute similar to `output_dir` like `output_stdout` so we know to have this behavior. It also means we have to do something fancy to wrap the program, and you have to declare a path in the output tree where you want that stdout to go.

**Comment by alexeagle** [comment]
@mattem is interested to possibly contribute this.

**Comment by mattem** [comment]
The idea is to have `nodejs_binary` optionally output stdout / stderr to a file, provided by the user for the `bazel run` case, while also having the file as an output when `nodejs_binary` is used as a tool - this would allow downstream actions to depend on the stdout and stderror of the binary, useful for tools that don't support outputting files, without needing the wrap in a genrule.
`npm_package_bin` is a small wrapper around `nodejs_binary`, so should expose the same API.

This will later aid with #1483 where a downstream binary could post process TSC diagnostics and output them with buildozer or fixit annotations.

**Comment by alexeagle** [comment]
It's done! Thanks @mattem
