### ISSUE TITLE
Augment TS diagnostic for missing module to point out deps

### ISSUE THREAD

**Issue by applmak** [bazelbuild/rules_nodejs#1483]
# 🐞 bug report

### Affected Rule
The issue is caused by the rule: ts_library

### Is this a regression?
Yes, I have had prior success getting nodejs + typescript to work in the past.

### Description
I get:
```
file.ts:1:21 - error TS2307: Cannot find module 'fs'.

1 import * as fs from 'fs';
                      ~~~~
```
from `blaze build ...` on a simple workspace.

## 🔬 Minimal Reproduction
I did the following:
```
$ brew tap bazelbuild/tap
$ brew install bazelbuild/tap/bazel
$ npm init @bazel root && cd root && npm install && npm run build
$ npm install --save-dev typescript @bazel/typescript @types/node
$ echo "import * as fs from 'fs';
console.log('yo');
"> file.ts
$ echo "load(\"@npm_bazel_typescript//:index.bzl\", \"ts_devserver\", \"ts_library\")

ts_library(
  name = \"file\",
  srcs = [\"file.ts\"],
)" > BUILD.bazel
$ touch tsconfig.json
$ bazel build ...
```

## 🔥 Exception or Error
<pre><code>
$ bazel build --define=VERBOSE_LOGS=1 ...
INFO: Invocation ID: c47d9bba-b3c0-416e-878b-8a5f07491536
INFO: Build option --define has changed, discarding analysis cache.
INFO: Analyzed target //:file (0 packages loaded, 795 targets configured).
INFO: Found 1 target...
ERROR: /Users/applmak/root/BUILD.bazel:3:1: Compiling TypeScript (devmode) //:file failed (Exit 1)
file.ts:1:21 - error TS2307: Cannot find module 'fs'.

1 import * as fs from 'fs';
                      ~~~~

Target //:file failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.441s, Critical Path: 1.91s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
</code></pre>


## 🌍  Your Environment

**Operating System:**
Mac OS 10.15.1

**Output of `bazel version`:**
```
Build label: 1.2.1
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Nov 26 15:27:31 2019 (1574782051)
Build timestamp: 1574782051
Build timestamp as int: 1574782051
```

**Rules_nodejs version:**
```
# Bazel workspace created by @bazel/create 0.42.3

# Declares that this directory is the root of a Bazel workspace.
# See https://docs.bazel.build/versions/master/build-ref.html#workspace
workspace(
    # How this workspace would be referenced with absolute labels from another workspace
    name = "root",
    # Map the @npm bazel workspace to the node_modules directory.
    # This lets Bazel use the same node_modules as other local tooling.
    managed_directories = {"@npm": ["node_modules"]},
)

# Install the nodejs "bootstrap" package
# This provides the basic tools for running and packaging nodejs programs in Bazel
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "a54b2511d6dae42c1f7cdaeb08144ee2808193a088004fc3b464a04583d5aa2e",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/0.42.3/rules_nodejs-0.42.3.tar.gz"],
)

# The npm_install rule runs yarn anytime the package.json or package-lock.json file changes.
# It also extracts any Bazel rules distributed in an npm package.
load("@build_bazel_rules_nodejs//:index.bzl", "npm_install")
npm_install(
    # Name this npm so that Bazel Label references look like @npm//package
    name = "npm",
    package_json = "//:package.json",
    package_lock_json = "//:package-lock.json",
)

# Install any Bazel rules which were extracted earlier by the npm_install rule.
load("@npm//:install_bazel_dependencies.bzl", "install_bazel_dependencies")
install_bazel_dependencies()
```
**Anything else relevant?**

This is probably trivial to fix; I just can't seem to make it work given the current documentation!

**Comment by Toxicable** [comment]
You need to add a `dep` on `@npm//@types/node` - that's the package that provides the nodejs types such as the `fs` module

**Comment by applmak** [comment]
That worked! Thank you!

I wish that such a thing were documented in the ts_library documentation.

**Comment by marcus-sa** [comment]
@applmak I don't see how it's any different from adding dependencies on other types, so doesn't really seem like it belongs in the documentation.
The behavior is exactly the same outside Bazel, because you'll have to install the missing types no matter what (unless you disable this of course)

**Comment by alexeagle** [comment]
Even better, we should augment the TS diagnostic TS2307 so that every time the error is printed we remind you what the deps are and how to add a new one

**Comment by mattem** [comment]
@alexeagle If this is something we still want, then I can take this on, fits nicely with the work done already on build file generation.

**Comment by alexeagle** [comment]
yeah, it will be specific to `ts_library` and not work for `ts_project` but seems like a good feature.

Note, if you print a command that works in the general case (ts_project prints `Run npx @bazel/buildozer 'some_command' //that:target`) then it might not make things work neatly under ibazel and also google-internal probably wants their own message too. You'll have to find someone to review/merge the rules_typescript change which is also a challenge.

**Comment by alexeagle** [comment]
note, this is unblocked now that actions can intercept stdout/stderr from other actions in #1466
