### ISSUE TITLE
bazel 2.0 breaks one of our tests

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#1486]
we do `bazel run @fine_grained_deps_yarn//typescript/bin:tsc` in our CI. starting with Bazel 2.0, this program discovers all the inputs from some other workspace it seems, and fails after a long time by printing:

```
Target @fine_grained_deps_yarn//typescript/bin:tsc up-to-date:
  /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/execroot/build_bazel_rules_nodejs/bazel-out/k8-fastbuild/bin/external/fine_grained_deps_yarn/typescript/bin/tsc_loader.js
  /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/execroot/build_bazel_rules_nodejs/bazel-out/k8-fastbuild/bin/external/fine_grained_deps_yarn/typescript/bin/tsc.sh
(22:52:32) INFO: Elapsed time: 0.279s, Critical Path: 0.02s
(22:52:32) INFO: 0 processes.
(22:52:32) INFO: Build completed successfully, 6 total actions
(22:52:32) INFO: Build completed successfully, 6 total actions
../../../../../../../../../e2e/ts_devserver/app.ts:1:22 - error TS2307: Cannot find module 'date-fns'.
 
1 import {format} from 'date-fns';
                       ~~~~~~~~~~
```

This seems fishy, somehow it discovers `.ts` files in the outer workspace which aren't meant to be part of the test.

**Comment by gregmagolan** [comment]
No longer in scope for rules_nodejs which only supplies the Node.js toolchain as of [v6.0.0](https://github.com/bazelbuild/rules_nodejs/releases/tag/v6.0.0-beta0).

Downstream canonical JavaScript + Node.js ruleset is now https://github.com/aspect-build/rules_js.
