### ISSUE TITLE
Performance: tsc type discovery causing long compiles

### ISSUE THREAD

**Issue by Toxicable** [bazelbuild/rules_nodejs#1497]
# 🐞 bug report

### Affected Rule
`ts_library`

### Is this a regression?
Maybe, yet to confirm, but it's likely that it happened after this change https://github.com/bazelbuild/rules_nodejs/commit/bbcfcdd0914da6aa39b57193e5f609fe0b0a31fb which is on 0.32.0

### Description
`ts_library` attempts to execute costly failed type look ups within the rxjs package.
See the related discussions below for more detailed information
It's unknown if this affects other packages.

## 🔬 Minimal Reproduction

**Rules_nodejs version:**
`1.0.0`

**Anything else relevant?**
links (sorry not all of these are publicalyl accessible)
https://github.com/angular/angular/pull/33786
https://bazelbuild.slack.com/archives/GMADCN4ES/p1576608220012800
https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1575320602080200

**Comment by alexeagle** [comment]
I think the answer here is to
1) run the linker before tsc actions (by switching typescript build_defs.bzl from ctx.actions.run to the run_node helper)
2) make sure all the `@types` packages are getting linked (might need to adjust the aspect that gathers the packages from transitive deps? maybe it already picks them up)
3) drop logic from the tsconfig generation that explicitly includes `@types` in the `files` of the program

IIRC this reverts us to earlier behavior where we can't ensure you have strict dependencies on third-party libs, but it's more node-idiomatic and avoids these de-opts and also simplifies our code.

Bigger project would be to make the `tsc` target have the better behavior like being a concurrent worker.
