### ISSUE TITLE
Maybe invoke npm with `--scripts-prepend-node-path=true`

### ISSUE THREAD

**Issue by mmorearty** [bazelbuild/rules_nodejs#151]
Somewhat similar to https://github.com/bazelbuild/rules_nodejs/issues/77, in the sense that the wrong `node` is being used, but this is a different issue.

Sorry I don't have time to write up a detailed repro case. But I think that sometimes `npm` child processes up running `node`, and currently they can run the "wrong" one.

As per the docs for [npm run](https://docs.npmjs.com/cli/run-script), if `npm` is going to run `node`, you can specify `--scripts-prepend-node-path=true` to tell `npm` to change `PATH` to start with the location where the "correct" `node` is — that is, the one that goes with this version of `npm`.

Although this is not on the docs page, it turns out that `npm install` also allows `--scripts-prepend-node-path=true`. This is useful because some downloaded npm packages will end up running commands. I think `node-sass` does this.

In my case, on my Linux machine, I have the "wrong" version of node on my path, so my bazel `npm_install` fails with a bunch of cryptic node error messages. If I do `npm config set scripts-prepend-node-path true`, which modifies `~/.npmrc`, then my `npm_install` works.

So... in order to fix `rules_nodejs` without having to modify `~/.npmrc`: In `internal/npm_install/npm_install.bzl`, near line 57, which has this:

```
  result = repository_ctx.execute(
    [repository_ctx.path(node), repository_ctx.path(npm), "install", repository_ctx.path("")])
```

I think you can add `--scripts-prepend-node-path=true`, and I think that would fix my problem:

```
  result = repository_ctx.execute(
    [repository_ctx.path(node), repository_ctx.path(npm), "install", "--scripts-prepend-node-path=true", repository_ctx.path("")])
```

If there are any other places that call `npm install/run/test/start/restart/stop`, do the same thing in those places.

**Comment by mmorearty** [comment]
I tested this on a fork, and confirmed that the above suggested fix did work correctly for me — my `npm_install` works now.

I don't have a PR for you, because I didn't search your sources for other npm commands. Also, it occurred to me, I don't know if yarn has similar issues or not. https://github.com/yarnpkg/yarn/issues/4375 has some discussion; I haven't read it carefully.

**Comment by gregmagolan** [comment]
Thanks @mmorearty. Put up #160 to fix this.
