### ISSUE TITLE
pkg_npm is not behaving as described or documentation is outdated 

### ISSUE THREAD

**Issue by whimzyLive** [bazelbuild/rules_nodejs#1512]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 
 **pkg_npm**

### Is this a regression?

Don't know, since this is the first time I needed to use this rule. 

### Description

 A clear and concise description of the problem...
As detailed in documentation, `pkg_npm` rule should be able to create directory that needs to be published to npm and after that it should be pretty straight forward to do dry-run of publishing using `bazel run :my-package.pack`.

when building pkg_npm it without any errors and looks something like this:
![Screenshot from 2019-12-25 20-30-35](https://user-images.githubusercontent.com/22066605/71551574-3bebcb80-2a3a-11ea-8041-3974692e1396.png)

but when running `bazel run :doostrapper.pack`, it fails to find package.json under doostrapper dir. 
I am not sure what could be wrong, since package.json is clearly there.

## 🔬 Minimal Reproduction
This repository contains reproduction of a bug describe above.
https://github.com/whimzyLive/bazel-npm-repro/tree/master

## 🔥 Exception or Error

<pre><code>
bazel run :doostrapper.pack "--define=VERBOSE_LOGS=1"

INFO: Invocation ID: 1c5da710-7be3-4ca2-b449-f0d6689e5a05
INFO: Build option --compilation_mode has changed, discarding analysis cache.
INFO: Analyzed target //:doostrapper.pack (0 packages loaded, 78 targets configured).
INFO: Found 1 target...
INFO: From Assembling npm package doostrapper:
[packager_loader.js] running @build_bazel_rules_nodejs//internal/pkg_npm:packager with
  cwd: /home/rushi/.cache/bazel/_bazel_rushi/bdc2ec592574456aabbac8bc768eaa62/sandbox/linux-sandbox/3/execroot/doostrapper
  runfiles: /home/rushi/.cache/bazel/_bazel_rushi/bdc2ec592574456aabbac8bc768eaa62/sandbox/linux-sandbox/3/execroot/doostrapper/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/pkg_npm/packager.sh.runfiles

  BIN_DIR: bazel-out/host/bin
  ENTRY_POINT: build_bazel_rules_nodejs/internal/pkg_npm/packager.js
  GEN_DIR: bazel-out/host/bin
  INSTALL_SOURCE_MAP_SUPPORT: false
  MODULE_ROOTS: [
  {
    "module_name": {},
    "module_root": "build_bazel_rules_nodejs/third_party/github.com/gjtorikian/isBinaryFile/src/index"
  }
]
  NODE_MODULES_ROOT: build_bazel_rules_nodejs/node_modules
  TARGET: @build_bazel_rules_nodejs//internal/pkg_npm:packager
  USER_WORKSPACE_NAME: doostrapper

[packager_loader.js] try to resolve in runfiles /home/rushi/.cache/bazel/_bazel_rushi/bdc2ec592574456aabbac8bc768eaa62/sandbox/linux-sandbox/3/execroot/doostrapper/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/pkg_npm/packager.sh.runfiles/build_bazel_rules_nodejs/internal/pkg_npm/packager.js
[packager_loader.js] resolved file /home/rushi/.cache/bazel/_bazel_rushi/bdc2ec592574456aabbac8bc768eaa62/sandbox/linux-sandbox/3/execroot/doostrapper/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/pkg_npm/packager.sh.runfiles/build_bazel_rules_nodejs/internal/pkg_npm/packager.js
[packager_loader.js] resolved build_bazel_rules_nodejs/internal/pkg_npm/packager.js within runfiles to /home/rushi/.cache/bazel/_bazel_rushi/bdc2ec592574456aabbac8bc768eaa62/sandbox/linux-sandbox/3/execroot/doostrapper/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/pkg_npm/packager.sh.runfiles/build_bazel_rules_nodejs/internal/pkg_npm/packager.js from undefined
[packager_loader.js] try to resolve in runfiles /home/rushi/.cache/bazel/_bazel_rushi/bdc2ec592574456aabbac8bc768eaa62/sandbox/linux-sandbox/3/execroot/doostrapper/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/pkg_npm/packager.sh.runfiles/build_bazel_rules_nodejs/third_party/github.com/gjtorikian/isBinaryFile/src/index
[packager_loader.js] resolved file /home/rushi/.cache/bazel/_bazel_rushi/bdc2ec592574456aabbac8bc768eaa62/sandbox/linux-sandbox/3/execroot/doostrapper/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/pkg_npm/packager.sh.runfiles/build_bazel_rules_nodejs/third_party/github.com/gjtorikian/isBinaryFile/src/index
[packager_loader.js] try to resolve in runfiles /home/rushi/.cache/bazel/_bazel_rushi/bdc2ec592574456aabbac8bc768eaa62/sandbox/linux-sandbox/3/execroot/doostrapper/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/pkg_npm/packager.sh.runfiles/nodejs_linux_amd64/run_npm.sh.template
[packager_loader.js] resolved file /home/rushi/.cache/bazel/_bazel_rushi/bdc2ec592574456aabbac8bc768eaa62/sandbox/linux-sandbox/3/execroot/doostrapper/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/pkg_npm/packager.sh.runfiles/nodejs_linux_amd64/run_npm.sh.template
[packager_loader.js] resolved nodejs_linux_amd64/run_npm.sh.template within runfiles to /home/rushi/.cache/bazel/_bazel_rushi/bdc2ec592574456aabbac8bc768eaa62/sandbox/linux-sandbox/3/execroot/doostrapper/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/pkg_npm/packager.sh.runfiles/nodejs_linux_amd64/run_npm.sh.template from /home/rushi/.cache/bazel/_bazel_rushi/bdc2ec592574456aabbac8bc768eaa62/sandbox/linux-sandbox/3/execroot/doostrapper/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/pkg_npm/packager.sh.runfiles/build_bazel_rules_nodejs/internal/pkg_npm/packager.js
Target //:doostrapper.pack up-to-date:
  dist/bin/doostrapper.pack
INFO: Elapsed time: 0.460s, Critical Path: 0.14s
INFO: 1 process: 1 linux-sandbox.
INFO: Build completed successfully, 2 total actions
INFO: Build completed successfully, 2 total actions
npm ERR! code ENOLOCAL
npm ERR! Could not install from "../../../.cache/bazel/_bazel_rushi/bdc2ec592574456aabbac8bc768eaa62/sandbox/linux-sandbox/3/execroot/doostrapper/bazel-out/k8-fastbuild/bin/doostrapper" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rushi/.npm/_logs/2019-12-29T02_25_40_374Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! doostrapper@0.1.0 pack: `bazel run :doostrapper.pack "--define=VERBOSE_LOGS=1"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the doostrapper@0.1.0 pack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rushi/.npm/_logs/2019-12-29T02_25_40_398Z-debug.log
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 2.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 19 12:30:18 2019 (1576758618)
Build timestamp: 1576758618
Build timestamp as int: 1576758618
  </code>
</pre>

**Rules_nodejs version:**
<pre>
  <code>
rules_nodejs-1.0.0
  </code>
</pre>

**Comment by alexeagle** [comment]
Yes, this is documented as a known issue on the 1.0.0 release, will be fixed this week when https://github.com/bazelbuild/rules_nodejs/pull/1494 is released

**Comment by alexeagle** [comment]
Fixed in 1.0.1
