### ISSUE TITLE
No TypeScript transpilation when running a nodejs_binary rule from npm_package_bin

### ISSUE THREAD

**Issue by mthurlin** [bazelbuild/rules_nodejs#1522]
# 🐞 bug report

### Affected Rule

Not sure, probably `nodejs_binary` or `npm_package_bin`

### Is this a regression?

I have not tested older versions.

### Description

Combining ts_library / nodejs_binary / npm_package_bin does not work as expected

I'm not sure if I'm doing something wrong, or if there is an issue in either `nodejs_binary` or `npm_package_bin`.

I'm trying to run a TypeScript script as part of my build.
So, what I want to do is to transpile (and typecheck) a couple of TypeScript files to JavaScript. 
Then, I want to run these files as a build script (providing some input files and accessing the resulting output files).

I have a minimal repro of the issue: https://github.com/mthurlin/typescript-bazel-issue

The two typescript files form my build script (reading the text in the input file and outputting it in upper case into the output file).

Running it through `nodejs_binary` works as expected:

```bazel run //:compile -- `pwd`/data.txt `pwd`/output.txt && cat output.txt```

But, running it programmatically via Bazel and `npm_package_bin` fails:

`bazel build //:output`

The files are being run as raw TypeScript, causing syntax errors in node.

I have tried various combinations of entry files and filegroups. 

I can get it to work using a `filegroup` with `output_group="es5_sources"`, providing the filegroup label as `entry_point` to `nodejs_binary`, but that only works as long as there is only one file. (That's why I have `utils.ts` in this minimal repro)

## 🔬 Minimal Reproduction

https://github.com/mthurlin/typescript-bazel-issue

## 🔥 Exception or Error

<pre><code>
bazel build --verbose_failures --sandbox_debug //:output 
INFO: Analyzed target //:output (46 packages loaded, 870 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /private/var/tmp/_bazel_mthurlin/ec48bece5bead1c227eef9e0a6b38b98/sandbox
ERROR: /Users/mthurlin/projects/typescript-bazel/BUILD.bazel:21:1: Action output.txt failed (Exit 1) sandbox-exec failed: error executing command 
  (cd /private/var/tmp/_bazel_mthurlin/ec48bece5bead1c227eef9e0a6b38b98/sandbox/darwin-sandbox/1/execroot/typescriptbazel && \
  exec env - \
    TMPDIR=/var/folders/0f/wxf_f50526l3ym__n_bn91d81vlns9/T/ \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_mthurlin/ec48bece5bead1c227eef9e0a6b38b98/sandbox/darwin-sandbox/1/sandbox.sb /var/tmp/_bazel_mthurlin/install/4f12cbbb3a294bfa314e578758559d54/process-wrapper '--timeout=0' '--kill_delay=15' bazel-out/host/bin/compile.sh ./data.txt bazel-out/darwin-fastbuild/bin/output.txt '--bazel_node_modules_manifest=bazel-out/darwin-fastbuild/bin/_output.module_mappings.json' --nobazel_patch_module_resolver)
/private/var/tmp/_bazel_mthurlin/ec48bece5bead1c227eef9e0a6b38b98/sandbox/darwin-sandbox/1/execroot/typescriptbazel/mycompiler.ts:1
import * as fs from "fs";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
Target //:output failed to build
INFO: Elapsed time: 5.733s, Critical Path: 0.63s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>Mac OS X 10.14.6</code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 2.0.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 19 12:33:30 2019 (1576758810)
Build timestamp: 1576758810
Build timestamp as int: 1576758810</code>
</pre>

**Rules_nodejs version:**
<pre>
  <code>1.0.0</code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
Thanks for the very clear issue report!

The bug is here:
https://github.com/bazelbuild/rules_nodejs/blob/1.0.0/internal/node/node.bzl#L218
where we refer to the execroot path of `ctx.file.entry_point` without going through `.ts`->`.js` translation logic.

In the first case where you `bazel run :compile` we do pick up the logic, because the binary uses the loader.js script using this codepath https://github.com/bazelbuild/rules_nodejs/blob/1.0.0/internal/node/node.bzl#L102-L105

But under npm_package_bin we shed the extra layer of the loader.js script and try to run the entry point directly. That's why the behavior is different.

It's tricky to fix. In the case of `run` or `test` we have a runfiles tree and manifest, so we can translate a `.ts` path which came from the input tree to a `.js` path that lives in the output tree. However under `build` we have an execroot layout instead, and the translation has to account for input tree -> output tree in addition to just picking up a different extension.

I had the same problem here:
https://github.com/bazelbuild/rules_nodejs/pull/1455/files#diff-1bb60783a47c8215e03d0fce367f0ff3
you can see the workaround is to use the filegroup trick to select out the entry point js as a label.
However as you observed, if there are multiple files this trick doesn't work, as the entry_point attribute expects a label which resolves to a single file.

**Comment by djabry** [comment]
I ran into the same problem and found a workaround:

1. Split the problem into two `ts_library` parts: one for the entry-point and one for all the other sources
2. Select out the `es5_sources` javascript for both parts using `filegroup`s
3. Use the entry-point javascript `filegroup` for the `nodejs_binary` target
4. Add the javascript `filegroup` from all the other sources to the `npm_package_bin` `data` input

This is how the `BUILD.bazel` file looks from the minimal example with the workaround applied:

```
load("@npm_bazel_typescript//:index.bzl", "ts_library")
load("@build_bazel_rules_nodejs//:index.bzl", "npm_package_bin", "nodejs_binary")

ts_library(
    name = "utils",
    srcs = ["utils.ts"],
    deps = ["@npm//@types/node"],
)

ts_library(
    name = "mycompiler",
    srcs = ["mycompiler.ts"],
    deps = ["utils", "@npm//@types/node"],
)

filegroup(
    name = "utils.js",
    srcs = ["utils"],
    output_group = "es5_sources"
)

filegroup(
    name = "mycompiler.js",
    srcs = ["mycompiler"],
    output_group = "es5_sources"
)

nodejs_binary(
    name = "compile",
    data = ["mycompiler.js"],
    entry_point = "mycompiler.js",
)

filegroup(
    name = "data_to_compile",
    srcs = ["data.txt"]
)

npm_package_bin(
    name = "output",
    tool = ":compile",
    data = [":data_to_compile", "utils.js"],
    args = ["$(location data_to_compile) $@"],
    outs = ["output.txt"]
)
```
Not sure if this can be simplified further.

**Comment by longlho** [comment]
I use `npm_package_bin` with `ts-node` as a workaround for this
