### ISSUE TITLE
[Question]  Generate Node Script Rules

### ISSUE THREAD

**Issue by t-rad679** [bazelbuild/rules_nodejs#1525]
This is just a question following up on a suggestion in https://github.com/bazelbuild/rules_nodejs/issues/362.

In particular, I tried using `generate_build_file.js` to create Bazel rules for my package.json scripts in BUILD, but I could not seem to get it to work. There is also not any documentation around how to use this script. Can you provide more information about how this should work?

Thanks!

**Comment by alexeagle** [comment]
It doesn't have that feature yet, sorry. Replied on the other issue.
