### ISSUE TITLE
Inconsistency with ts_library, module_name, and rollup

### ISSUE THREAD

**Issue by herman-rogers** [bazelbuild/rules_nodejs#1537]
# 🐞 bug report

### Affected Rule
`ts_library`
specifically `module_name`

### Is this a regression?

I don't know.

### Description
Essentially when we use the `module_name` from `ts_library` we get resolution errors with rollup:

`
(!) Unresolved dependencies 
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@lib/environment
`

This only happens in a production bundle of the project - the development server works fine.

What's causing this, as far as we can tell, is the naming of the module.

For example, if we are to call the module `@lib/environments` Bazel will resolve this correctly however rollup throws the unresolved dependency error and the app won't load.

If we were to change the module name to `@lib_environments` then both Bazel and rollup work as expected. Additionally, if we were to use `@lib/environments-test` then we'd get the unresolved dependency again. If we change it to `@lib/environments_test` then everything works as expected.
 
There seems to be some correlation with usage of the underscore.

Further, our app is setup as a monorepo so we have projects/project-one projects/project-two and if we have a module_name `@lib-test/environments/test` then we get the unresolved error again. If we change it to `@lib_test/environments/test` then it works again but **only** for project-one, project-two is unable to find `@lib_test/environments/test` unless we change the name to `@lib_test_environments/test` - we found a workaround (I'll post below) but clearly these solutions were brittle and we didn't want `@lib_test_environments_test` as the module name.

Is there some best practice/guidelines we're missing here when naming our modules?

## 🔬 Minimal Reproduction

I believe the issue is just to name a module `@lib/environments` and see if it imports correctly during a rollup build. Also using `@lib-test/environments` should also break things.

I can provide a repo if necessary to get reproduction.

## 🔥 Exception or Error

<pre><code>
(!) Unresolved dependencies 
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency 
@lib/environments
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
    Mac OS Catalina
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 1.1.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Oct 21 08:47:13 2019 (1571647633)
Build timestamp: 1571647633
Build timestamp as int: 1571647633
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
RULES_NODEJS_VERSION = "0.40.0"
  </code>
</pre>

**Anything else relevant?**

To get around this issue for now is to create our own alias in the `rollup.config.js` that manually resolves the file for us.

This is what our config looks like:

```javascript
import amd from 'rollup-plugin-amd';
import commonjs from 'rollup-plugin-commonjs';
import html from 'rollup-plugin-html';
import node from 'rollup-plugin-node-resolve';
import replace from 'rollup-plugin-re';
import alias from '@rollup/plugin-alias';

module.exports = {
  plugins: [
    html(),
    alias({
      entries: [
        {
          find: '@lib/environments',
          replacement: `${__dirname}/../../packages/environments`,
        },
      ]
    }),
    replace({
      patterns: [
        {
          match: /\.ngfactory\.mjs/,
          test: 'workspace/external/npm/node_modules/',
          replace: '',
        },
      ],
    }),
    node({
      mainFields: ['browser', 'es2015', 'module', 'jsnext:main', 'main'],
    }),
    amd({
      include: /\.ngfactory\.js$/i,
    }),
    commonjs(),
  ],
};
```

**Comment by marcus-sa** [comment]
You don't have to use aliases actually, you can workaround it by using `replace` as well.
Here's what I do:
```js
replace({
      patterns: [
        {
          // Work-around for the generated Angular ViewEngine ngfactory imports that
          // starts with `sa_dashboard/external/npm/node_modules/`.
          match: /\.ngfactory\.mjs/,
          test: 'sa_dashboard/external/npm/node_modules/',
          replace: '',
        },
        {
          // Work-around for https://github.com/bazelbuild/rules_nodejs/issues/1380#issuecomment-558631283
          match: /\.mjs/,
          test: '@sa/frontend/',
          replace: 'sa_dashboard/libs/frontend/',
        },
      ],
    }),
```

**Comment by herman-rogers** [comment]
Yea I saw this issue but wasn't entirely sure if you had the similar weirdness with the underscore or not. And yea replace should work as well - not sure if there's a specific advantage to the different approaches? (minus the extra lib). Good to know we're not alone in this though.
