### ISSUE TITLE
Documentation for stamping is incorrect

### ISSUE THREAD

**Issue by mmorearty** [bazelbuild/rules_nodejs#156]
In the readme, the explanation of how to do stamping is wrong. Basically, if you are writing a genrule that has `stamp = True`, that genrule will only work as expected if it has at least one file in its `srcs`. See https://github.com/bazelbuild/bazel/issues/4842 for a full explanation.

**Comment by alexeagle** [comment]
Ooh, thanks for finding that Mike. Silently stamping with an old value is a nasty bug!
