### ISSUE TITLE
ts_library: resulting files should be pre-declared outputs

### ISSUE THREAD

**Issue by devversion** [bazelbuild/rules_nodejs#1563]
It should be possible to declare the resulting files of a `ts_library` rule, as pre-declared outputs (unless I miss something). This would allow references to generated files through a label.

https://docs.bazel.build/versions/2.0.0/skylark/rules.html#outputs

> A generated file that is addressable by a label is called a predeclared output. Rules can specify predeclared outputs via

**Comment by joeljeske** [comment]
Predeclared outputs are declared at the time when the rule is created, not invoked. Their label is not dynamic based on parameters.  

They are typically used for outputs known ahead of time, for example, a rule always creates a script and a manifest file for that script. Both the script and the manifest file could be predeclared outputs, allowing those files to be referenced by a label. 

It could only work for ts_library if it was only ever invoked with a single input TS file. Then the well know resulting outputs would be, “declaration” “es5_source” “es6_source”. Typically, you want to have a larger set of input files making this not practical. 


What are you wanting to do exactly?

**Comment by devversion** [comment]
@joeljeske Pre-declared outputs could be generated based on specified source files. The global `rule` function, seems to provide a way to generate a dictionary of pre-declared outputs through a function that has access to attribute values (i.e. `srcs`).

https://docs.bazel.build/versions/2.0.0/skylark/lib/globals.html#rule

This method seems to be deprecated, but there might be an alternative. Though in general, unless I miss something here, it should be possible to generate a list of pre-declared `.js` input files for each TS source file passed to `srcs`.

**Comment by joeljeske** [comment]
Ah you’re right! I was not aware of the function form of that attribute. 

In any case, you are right that that attribute is deprecated. But I doubt this team will be interested in adding a new feature based on a deprecated api

**Comment by devversion** [comment]
The attribute has been deprecated for quite some time, but they might have not thought of the [implicit outputs function](https://github.com/bazelbuild/bazel/blob/553dc6c9af2d38e4e3d356bf50e09ea7b008f25c/src/main/java/com/google/devtools/build/lib/packages/ImplicitOutputsFunction.java#L61). I added a comment to their outputs API refactor design document that seems related to this.

It's unclear whether there is an alternative to the implicit outputs function. I don't know of an alternative yet, but there _might be_.

The use case in general is that it should be possible to reference individual built `.js` files. This improves the overall build rule correlation and ergonomics of `ts_library`. e.g.

```bzl
circular_dependency_test(
  name = "circular_deps_test",
  entry_point = ":index.js",
)

ts_library(
  name = "my-pkg",
  srcs = ["index.ts", ...]
)
```

This is currently not possible, and the output can only be referenced through a manifest/runfile path (which ergonomically is bad DX and doesn't fit into the idiomatic way of passing files between targets). Also, helpers like `$(location :index.js)` won't work.

**Comment by alexeagle** [comment]
Yes, I agree with the feature request, you should be able to address the .js outputs with a label.

(If they do deprecate the outputs function we just refactor it into a wrapper macro that calculates the expected .js outs and passes it to an outputs attribute on the rule)
