### ISSUE TITLE
pkg_npm .pack doesn't work with vendored_node

### ISSUE THREAD

**Issue by aherrmann** [bazelbuild/rules_nodejs#1565]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: `pkg_npm`

### Is this a regression?

Unknown

### Description

The `.pack` script produced by the `pkg_npm` rule fails due to an invalid path to `npm-cli.js`.

## 🔬 Minimal Reproduction

Use a `vendored_node` like so
`WORKSPACE`:
```
http_archive(
    name = "vendored_node_10_12_0",
    build_file_content = """exports_files(["node-v10.12.0-linux-x64/bin/node"])""",
    sha256 = "4eba2e9a6db95745b769915d58e57df6ca6724ec1f023f76556fce30ceca2367",
    urls = ["https://nodejs.org/dist/v10.12.0/node-v10.12.0-linux-x64.tar.xz"],
)

load("@build_bazel_rules_nodejs//:index.bzl", "node_repositories")

node_repositories(
    package_json = ["//:package.json"],
    vendored_node = "@vendored_node_10_12_0//:node-v10.12.0-linux-x64",
)
```
And define a `pkg_npm` target like so
`BUILD.bazel`:
```
load("@build_bazel_rules_nodejs//:index.bzl", "pkg_npm")

pkg_npm(
    name = "pkg",
    srcs = ["test.js", "package.json"],
)
```

Then execute `bazel run //:pkg.pack` and observe the following error:
```
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '.../external/vendored_node_10_12_0/node-v10.12.0-linux-x64/lib/node_modules/npm/bin/npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

See aherrmann/repro_nodejs_binary_arg_escape@d4c621e73833e0f8cdc38893e59ffac1a2f367f2 for the full code.

## 🔥 Exception or Error

```
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '.../external/vendored_node_10_12_0/node-v10.12.0-linux-x64/lib/node_modules/npm/bin/npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 1.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Oct 21 08:44:00 2019 (1571647440)
Build timestamp: 1571647440
Build timestamp as int: 1571647440
  </code>
</pre>

**Rules_nodejs version:**

<pre>
  <code>
1.1.0
  </code>
</pre>

**Anything else relevant?**

[This patch](https://github.com/digital-asset/daml/blob/359e5c350c415878941c492f13555333c92da580/bazel_tools/rules_nodejs_npm_cli_path.patch) works around the issue.

**Comment by alexeagle** [comment]
thanks - looks like the patch is specific to the vendored_node use case so we have a bit more work to fix this properly

**Comment by Samywamy10** [comment]
Hi, I am running into this issue. The patch doesn't seem to work for me, and I'm on `rules_nodejs` v 3.3. Any ideas?
