### ISSUE TITLE
rollup_bundle should differentiate build config deps and application deps

### ISSUE THREAD

**Issue by joeljeske** [bazelbuild/rules_nodejs#1568]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: rollup_bundle

### Is this a regression?

 No

### Description

Currently there is a single "deps" attr that is used to specify both deps used while bundling the code, and deps used in the rollup config file. The issue is that es6 sources are preferred when extracting sources from the deps. That results in es6 sources being loaded during the rollup config file phase instead of es5 sources. 

Note: Although rollup's CLI does do on-the-fly transpilation of the rollup config files, it does not handle npm imports (non relative imports); it expects those imports to resolve and load properly on their own inside a node environment.

## 🔬 Minimal Reproduction

```python
# in practice, this is in a separate package, and thus cannot import as a relative inside rollup.config.js
ts_library(
  name = "my-rollup-plugin",
  srcs = ["my-rollup-plugin/index.ts"],
  module_name = "my-rollup-plugin",
)

ts_library(
  name = "app-compile",
  srcs = ["app/index.ts"],
)

rollup_bundle(
  name = "app-bundle",
  entry_point = "app/index.ts",
  config_file = "rollup.config.js",
  deps = [
    "app-compile",
    "my-rollup-plugin",
  ],
)
```

```js
// rollup.config.js
import myRollupPlugin from 'my-rollup-plugin';
export default {
  plugins: [
    myRollupPlugin()
  ]
}
```

## 🔥 Exception or Error

<pre><code>
[!] Error: Must use import to load ES Module: /private/var/tmp/_bazel_user/abc123/sandbox/darwin-sandbox/1/execroot/ws/node_modules/my-rollup-plugin/index.mjs
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /private/var/tmp/_bazel_user/abc123/sandbox/darwin-sandbox/1/execroot/ws/node_modules/my-rollup-plugin/index.mjs
    at Object.Module._extensions..mjs (internal/modules/cjs/loader.js:1007:9)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/private/var/tmp/_bazel_user/abc123/sandbox/darwin-sandbox/1/execroot/ws/bazel-out/darwin-fastbuild/bin/packages/react-http-client/_bundle.rollup_config.js:3:23)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.require.extensions.<computed> [as .js] (/private/var/tmp/_bazel_user/abc123/sandbox/darwin-sandbox/1/execroot/ws/node_modules/rollup/dist/bin/rollup:840:24)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS 10.14.6
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 1.2.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Nov 20 15:08:12 2019 (1574262492)
Build timestamp: 1574262492
Build timestamp as int: 1574262492
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
1.1.0
c97bf38546c220fa250ff2cc052c1a9eac977c662c1fc23eda797b0ce8e70a43
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
Looks to me like you need to select the ES5 downleveled outputs of the plugin ts_library to pass to rollup: https://github.com/bazelbuild/rules_nodejs/blob/master/docs/TypeScript.md#accessing-javascript-outputs - I think this is the right workaround, it makes more explicit which JS files you want to get from the ts_library and pass to rollup_bundle.

You're right that by default we try to pull in the .mjs files for rollup, whether they are application sources or plugin code. I suppose we could differentiate them with different attributes. I think we discussed a design where you could have a rule like `rollup_plugin` and list that as a plugin[] of `rollup_bundle` but really we want the bazel layer to be as thin as possible on top of just invoking tools, and other than selecting which JS code to request from dependencies, there's nothing different in invoking rollup between plugins and application dependencies (in theory you could even have an npm package both used as a plugin and whose code gets bundled into the app)

**Comment by joeljeske** [comment]
Thanks for the info. Yes, I can do what I need using the output group. Apologies as this is clear in the docs. I think your future plans of simplifying the ts_library rules will avoid this issue in the future. Thanks!
