### ISSUE TITLE
yarn_install fails to load

### ISSUE THREAD

**Issue by bugzpodder** [bazelbuild/rules_nodejs#1587]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 

```
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "ecaa54955b314b5e33948bd8f39e35c35ee89e905d8de1c03868100293510573",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/1.2.1/rules_nodejs-1.2.1.tar.gz"],
)

load("@build_bazel_rules_nodejs//:index.bzl", "yarn_install")
```
### Is this a regression?

Upgrade to 1.0+ seem to have this error.

## 🔥 Exception or Error

<pre><code>
ERROR: /private/var/tmp/_bazel_/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:293:13: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 292
		repository_rule(attrs = dict(COMMON_ATTRIBUTES, ...)}), <2 more arguments>)
	File "/private/var/tmp/_bazel_/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 293, in repository_rule
		dict(COMMON_ATTRIBUTES, **{"args": attr...)})
got multiple values for keyword argument 'args', for call to function dict(args = [], **kwargs)
ERROR: /private/var/tmp/_bazel_/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:376:13: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 375
		repository_rule(attrs = dict(COMMON_ATTRIBUTES, ...)}), <2 more arguments>)
	File "/private/var/tmp/_bazel_/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 376, in repository_rule
		dict(COMMON_ATTRIBUTES, **{"args": attr...)})
got multiple values for keyword argument 'args', for call to function dict(args = [], **kwargs)
ERROR: error loading package '': in /private/var/tmp/_bazel_/external/build_bazel_rules_nodejs/index.bzl: Extension file 'internal/npm_install/npm_install.bzl' has errors
ERROR: error loading package '': in /private/var/tmp/_bazel_/external/build_bazel_rules_nodejs/index.bzl: Extension file 'internal/npm_install/npm_install.bzl' has errors

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
catalina 10.15.3
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
0.28
  </code>
</pre>

**Rules_nodejs version:**

<pre>
  <code>
1.0.1, 1.2.1
  </code>
</pre>

**Anything else relevant?**

**Comment by Toxicable** [comment]
Can you post your usage of `yarn_install`?

**Comment by bugzpodder** [comment]
I removed all calls of yarn_install from my WORKSPACES and still get this error.  It's the load command that seem to cause this error.
```
yarn_install(
    name = "npm",
    package_json = "//third-party/npm:package.json",
    use_global_yarn_cache = False,
    yarn_lock = "//third-party/npm:yarn.lock",
)
```

**Comment by gregmagolan** [comment]
Try updating to Bazel 2.0.0. You're on a very old version of Bazel that is not supported by rules_nodejs.

**Comment by bugzpodder** [comment]
Thanks, makes sense!
