### ISSUE TITLE
Feature request: support `npm ci`

### ISSUE THREAD

**Issue by mmorearty** [bazelbuild/rules_nodejs#159]
See [this blog post](http://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable) for an introduction to `npm ci`. It would be nice if rules_nodejs had a `npm_ci` command in addition to its `npm_install` command.

**Comment by alexeagle** [comment]
Is there any reason we would want both? Just for updating the package.lock file? In that case you could run `bazel run @nodejs//:npm` 
I think we should just change the behavior of npm_install to run `npm ci`
@gregmagolan  ?

**Comment by mmorearty** [comment]
I'm not aware of a reason we would want both, but I haven't thought about it too deeply. Certainly it seems that Bazel is the kind of context where you might be fine with just `npm ci`, and not having `npm install` at all.

**Comment by gregmagolan** [comment]
Yes. `npm ci` is a better fit for bazel. Not sure about changing the behavior of `npm_install` as users may expect it to run `npm install`. If its going to break compatibility anyway (since the package_json attribute will be removed and the package_lock_json attribute made mandatory) then may as well just make an `npm_ci` rule and possibly remove `npm_install` or mark it as deprecated for future removal.

**Comment by gregmagolan** [comment]
`npm ci` was added recently with npm v5.7.0. This doesn't ship with node yet but it could be updated in Bazel with `npm update -g npm@5.7.1`.

**Comment by gregmagolan** [comment]
Not as easy as I hoped to update npm to 5.7.1 within Bazel. Also, there are some issues with npm 5.7.1 which kept node from including it. They are waiting for npm 5.8.0 before including it in node 8.x LTS. See https://github.com/nodejs/node/issues/19271. That should be coming soon.

**Comment by zkat** [comment]
`npm ci` is very new, so one reason you might want to support both is so you're not stuck with `npm ci` if you find an incompatibility (while we fix it)

**Comment by alexeagle** [comment]
Agreed we shouldn't run binaries that aren't distributed with the LTS of
node itself.

**Comment by gregmagolan** [comment]
Still waiting on a node 8.x.x release with npm 5.7.x. Release list with npm versions are published here: https://nodejs.org/en/download/releases/

**Comment by alexeagle** [comment]
we now default to node 10 so I think this is unblocked, we should change `npm_install` to have the `npm ci` behavior

**Comment by alexeagle** [comment]
fixed in #2328
