### ISSUE TITLE
ts_library rule is not compatible with "noEmit" ts compiler option

### ISSUE THREAD

**Issue by zgagnon** [bazelbuild/rules_nodejs#1592]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: ts_library rule

### Is this a regression?

Unknown

### Description

adding "noEmit":true to compiler options in tsconfig.json causes the build to fail, with:

`output 'myTsFile.js' was not created`

## 🔬 Minimal Reproduction

https://github.com/zgagnon/bazel-typescript-example
Running `bazel build /...` in this repo will cause the bug.

## 🔥 Exception or Error

From example repo:
<pre><code>
ERROR: /Users/zgagnon/workspace/bazel-typescript-example/BUILD:3:1: output 'date.js' was not created
ERROR: /Users/zgagnon/workspace/bazel-typescript-example/BUILD:3:1: output 'date.d.ts' was not created
ERROR: /Users/zgagnon/workspace/bazel-typescript-example/BUILD:3:1: not all outputs were created or valid

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
MacOS
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 2.0.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 19 12:33:30 2019 (1576758810)
Build timestamp: 1576758810
Build timestamp as int: 1576758810
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
rules_nodejs-1.2.0
  </code>
</pre>

**Anything else relevant?**

A simple resolution of this bug may just be to document that tsconfig.json must not contain this option.

**Comment by Toxicable** [comment]
What would you use ts_library for if it's not producing outputs?

**Comment by zgagnon** [comment]
I'm converting a non-bazel repo to use bazel, and this took me a bit to figure out. I figure since this compiler option is not compatible with the rule, it should either be documented or ignored by bazel.

**Comment by alexeagle** [comment]
Hmm, we used to have a feature where we warned on any setting in the tsconfig that was overridden by Bazel, but that was annoying - the warning appears in contexts where you don't want to do anything about it.

Want to send a PR against the docs? There's a note about `declarationDir`, it could go next to it.
https://github.com/bazelbuild/rules_nodejs/blob/master/packages/typescript/docs/install.md#compiling-typescript-ts_library
or possibly earlier where we say that you have to enable `--declarations` https://github.com/bazelbuild/rules_nodejs/blob/master/packages/typescript/docs/install.md#alternatives

**Comment by zgagnon** [comment]
I read through the install documentation again, and it felt like the best place to put it was near the instructions about exporting `tsconfig.json`. 

PR https://github.com/bazelbuild/rules_nodejs/pull/1611
