### ISSUE TITLE
Bazel Angular example dev serve doesn't work on windows

### ISSUE THREAD

**Issue by alan-agius4** [bazelbuild/rules_nodejs#1604]
# 🐞 bug report

### Is this a regression?

Yes

### Description

https://github.com/bazelbuild/rules_nodejs/tree/master/examples/angular doesn't work on Windows

Run `ng serve`, not that `ng serve --prod` has different kind of errors due to https://bazelbuild.slack.com/archives/GMADCN4ES/p1580896704106300

## 🔬 Minimal Reproduction

Run `ng serve` in https://github.com/bazelbuild/rules_nodejs/tree/master/examples/angular using Windows as OS.

## 🔥 Exception or Error
In browser console
<pre><code>

l108498/:1 Refused to apply style from 'http://l108498:5432/bazel-out/x64_windows-fastbuild/bin/src/styles.css?v=1580898021431' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
l108498/:1 Refused to apply style from 'http://l108498:5432/external/npm/node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css?v=1580898021431' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
zone.min.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
ts_scripts.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
l108498/:1 Refused to apply style from 'http://l108498:5432/bazel-out/x64_windows-fastbuild/bin/src/styles.css?v=1580898021431' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
l108498/:1 Refused to apply style from 'http://l108498:5432/external/npm/node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css?v=1580898021431' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

</code></pre>

## 🌍  Your Environment

**Operating System:** Windows
**Output of `bazel version`:**

<pre>
  <code>
Build label: 2.0.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 19 12:31:16 2019 (1576758676)
Build timestamp: 1576758676
Build timestamp as int: 1576758676
  </code>
</pre>

**Anything else relevant?**

It seems that most of the regressions comes from `html-insert-assets` package were with `0.4.0` most of the above errors have been introduced. However with `0.2.0` there is still the below error;
```
2l108498/:12 GET http://l108498:5432/_C:/Program%20Files/Git/ts_scripts.js?v=1580897804942 net::ERR_ABORTED 404 (Not Found)
```

The paths for `ts_scripts` seems to be none-the-less wrong

html-insert-assets  0.2.0
```html
<!DOCTYPE html><html><head>
    <title>Angular Bazel Example</title>
    <base href="/example">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" href="/styles.css?v=1580897804942"><link rel="stylesheet" href="/npm/node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css?v=1580897804942"></head>
  <body>
    <!-- The Angular application will be bootstrapped into this element. -->
    <app-component></app-component>    
  

<script src="/npm/node_modules/zone.js/dist/zone.min.js?v=1580897804942"></script><script src="/_C:/Program Files/Git/ts_scripts.js?v=1580897804942"></script></body></html>
```

html-insert-assets  0.4.0
```html

<!DOCTYPE html><html><head>
    <title>Angular Bazel Example</title>
    <base href="/example">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" href="./bazel-out\x64_windows-fastbuild\bin\src\styles.css?v=1580894103844"><link rel="stylesheet" href="./external\npm\node_modules\@angular\material\prebuilt-themes\deeppurple-amber.css?v=1580894103844"></head>
  <body>
    <!-- The Angular application will be bootstrapped into this element. -->
    <app-component></app-component>    
  

<script src="./external\npm\node_modules\zone.js\dist\zone.min.js?v=1580894103844"></script><script src="./_C:\Program Files\Git\ts_scripts.js?v=1580894103844"></script></body></html>

**Comment by alan-agius4** [comment]
//cc @gregmagolan as I mentioned this offline yesterday.

**Comment by alan-agius4** [comment]
Okay, so most errors excluded `2l108498/:12 GET http://l108498:5432/_C:/Program%20Files/Git/ts_scripts.js?v=1580897804942 net::ERR_ABORTED 404 (Not Found)
` should be fixed by https://github.com/jbedard/html-insert-assets/pull/6

**Comment by alan-agius4** [comment]
Seems like there is something wrong when resolving paths; (Notice the last item)
```
[  'C:\\users\\alag\\_bazel_alag\\rj2iva3m\\external\\build_bazel_rules_nodejs\\internal\\node\\_node_bin\\node',
  'C:\\users\\alag\\_bazel_alag\\rj2iva3m\\execroot\\examples_angular\\node_modules\\html-insert-assets\\src\\main.js',
  '--html=src/example/index.html',
  '--out=bazel-out/x64_windows-fastbuild/bin/src/index.html',
  '--roots=.',
  'bazel-out/x64_windows-fastbuild/bin/src',
  '--assets',
  'bazel-out/x64_windows-fastbuild/bin/src/styles.css',
  'external/npm/node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css',
  'external/npm/node_modules/zone.js/dist/zone.min.js',
  '_C:/Program Files/Git/ts_scripts.js'
]
```

**Comment by ubergeoff** [comment]
Still seems broken on windows..?

Current version is using: "html-insert-assets": "^0.6.0",

Everything seems to "serve" fine... but site is "blank"...

**Comment by alan-agius4** [comment]
@ubergeoff, unfortunately I no longer have a Windows machine to check why this has regressed. Maybe someone else on the team can take a look 

//cc @alexeagle.

**Comment by ubergeoff** [comment]
Anyone else - able to get this Angular example to run on Windows..?
