### ISSUE TITLE
Deprecation for @bazel/hide-build-files package

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#1613]
Bazel 2.1 supports .bazelignore files in external repos (thanks @meteorcloudy !)
Our workaround for this can now be deprecated.

I just merged a change which removes our own dependency on it (https://github.com/bazelbuild/rules_nodejs/commit/82599e605e606b28f6ab58a7b82fe422baa21eb2)

Next steps:
- [ ] remove the https://github.com/bazelbuild/rules_nodejs/blob/82599e605e606b28f6ab58a7b82fe422baa21eb2/docs/Built-ins.md#hide_build_files attribute (first flip default to False, but keep using this flag for our own packages until most users are on 2.1)
- [x] mark the npm package as deprecated
- [ ] remove the https://github.com/bazelbuild/rules_nodejs/blob/82599e605e606b28f6ab58a7b82fe422baa21eb2/docs/Built-ins.md#always_hide_bazel_files and equivalent one for yarn 
- [ ] delete the hide-bazel-files package code
- [ ] delete the code in generate_build_files.ts that hides bazel files

**Comment by KrauseStefan** [comment]
#1632 is related to this
