### ISSUE TITLE
Puppeteer: Image Not Found

### ISSUE THREAD

**Issue by bnewland123** [bazelbuild/rules_nodejs#1617]
I have a service that uses puppeteer, and I'm trying to figure out how to correctly build an image and run it with Bazel. The image builds successfully, but I get 'image not found' when trying to run puppeteer. Is there a way to bundle the Chromium binary or force it to install as a part of the build process before starting the server?

**Comment by alexeagle** [comment]
@gregmagolan was just working in the angular repo to switch them over to puppeteer IIRC

**Comment by gregmagolan** [comment]
For future reference, here is the angular PR that bring in puppeteer: https://github.com/angular/angular/pull/35049.

There is an issue on OSX however as the `@npm//puppeteer` target will not contain the Chrome libs as those files paths have spaces and Bazel can't yet handle spaces in runfiles. There is an outstanding issue for it and it almost got fixed but didn't pass internal Google review.

https://github.com/angular/angular/pull/33927 is a follow up to the angular puppeteer PR and uses puppeteer in integration tests (via new npm_integration_test rule) however the angular repo still uses rules_webtesting to provision browsers for its karma & protractor tests.
