### ISSUE TITLE
pkg_web: Ability to stamp outputs. 

### ISSUE THREAD

**Issue by thesayyn** [bazelbuild/rules_nodejs#1621]
# 🚀 feature request

Stamping pkg_web outputs

### Relevant Rules

pkg_web

### Description

pkg_web  rule cannot stamp outputs.

### Describe the solution you'd like

pkg_web rules should have the ability to stamp outputs as pkg_npm does.

### Describe alternatives you've considered

I've tried to combine pkg_npm and pkg_web to stamp builds although I couldn't succeed because pkg_npm does not pick up the transitive files either in `src` nor `deps` attribute.

**Comment by thesayyn** [comment]
I will work on this if it's okay? @alexeagle

**Comment by alexeagle** [comment]
Fixed by #1664
