### ISSUE TITLE
Bazelisk is slow if executed via yarn

### ISSUE THREAD

**Issue by joeljeske** [bazelbuild/rules_nodejs#1627]
# 🐞 bug report

### Affected Package

 The issue is caused by the package: `@bazel/bazelisk` (I know this package is not managed here, but I think the is issue is only present when run with `yarn` which is a suggested approach from this repo)

### Is this a regression?

 It did not occur when using `@bazel/bazel`

### Description

 A clear and concise description of the problem...

Running the same build repeatedly in bazel should have a near 0s execution time. If I run the same build using `yarn run bazelisk build //...` the execution time is always 4-5 seconds on my machine. Repeatedly executing `./node_modules/.bin/bazelisk build //...` is closer to 0.5-1 second. 

I am not sure what is causing this jump in time and what other affects it could be having. 

### Without Yarn

```sh
# Prime the cache once, 
./node_modules/.bin/bazelisk build //... 2> /dev/null > /dev/null
# Run again to see the cached time
./node_modules/.bin/bazelisk build //...
INFO: Invocation ID: ccd2f808-39c0-495f-a33c-e2c897548579
INFO: Analyzed 2226 targets (0 packages loaded, 0 targets configured).
INFO: Found 2226 targets...
INFO: Elapsed time: 0.665s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

### With Yarn

```sh
# Prime the cache once, 
yarn run bazelisk build //... 2> /dev/null > /dev/null
# Run again to see the cached time
yarn run bazelisk build //... 
yarn run v1.21.1
$ /project/node_modules/.bin/bazelisk build //...
INFO: Invocation ID: 68604a32-15cf-4bab-b16a-e6ad165f63a6
INFO: Analyzed 2226 targets (1 packages loaded, 1730 targets configured).
INFO: Found 2226 targets...
INFO: Elapsed time: 3.934s, Critical Path: 0.09s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
✨  Done in 4.06s.
```

Time Excerpts:
```
# Without yarn
INFO: Elapsed time: 0.665s, Critical Path: 0.00s
# With yarn
INFO: Elapsed time: 3.934s, Critical Path: 0.09s
```

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS 10.14.6
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.3.0
Starting local Bazel server and connecting to it...
Build label: 2.1.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Feb 7 13:04:00 2020 (1581080640)
Build timestamp: 1581080640
Build timestamp as int: 1581080640
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
1.3.0
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
My guess is that this isn't bazelisk fault, and could be reproduced with just Bazel. Can you confirm that?

I was going to suggest that your yarn version is a non-incremental build but it does say zero actions were run. I still suspect yarn is setting something in the environment that causes Bazel to think it needs to re-do some work. https://github.com/bazelbuild/rules_nodejs/blob/25600ea4c307c120d04a14c6d41644a3e8d3ed3a/common.bazelrc#L70-L77 is a flag we suggest because it avoids polluting Bazel's environment, do you have that set?

(would be good for us to recommend running bazel with `--announce_rc` when reporting issues, then I could see what flags you had enabled)

**Comment by joeljeske** [comment]
Yes, the slow down does still occur when invoking bazel through yarn. 
Yes, I have the flag `--incompatible_strict_action_env` set in my rc

After you mentioned the environment variables, I see that my PATH is modified on every run of "yarn". I'm not really sure why it is, and I'm not confident that it is yarn that is doing this: 


package.json
```json
{
   "scripts": { "print-path": "echo PATH=$PATH" }
}
```

```
# First run
PATH=/var/folders/wq/b39w_lqj0jjcj2x7yt_vwy5skxcd7j/T/yarn--1581621663593-0.16213933574838602:..rest of path is the same...

# Second run run
PATH=/var/folders/wq/b39w_lqj0jjcj2x7yt_vwy5skxcd7j/T/yarn--1581621698649-0.9104166682977393:..rest of path is the same...
```

In that directory that changes are 2 shell scripts: "node" and "yarn" which forward all arguments to their respective binaries. 

Any idea what is causing this to be added to my path? Is this yarn? Or macOS??

**Comment by gregmagolan** [comment]
This looks very similar to https://github.com/angular/angular/issues/27514 (https://github.com/angular/angular/issues/27514#issuecomment-445240929).
Do you have both `build` and `run` set for the flag:
```
 build --incompatible_strict_action_env 
 run --incompatible_strict_action_env 
```
Also, make sure you're not forwarding your entire PATH to actions (https://github.com/angular/angular/issues/27514#issuecomment-493049813):
```
 build --action_env=PATH 
 test --action_env=PATH --test_env=PATH 
```

**Comment by alexeagle** [comment]
Note that `--explain` and `--verbose_explanations` are good Bazel flags to tell you why the build wasn't incremental.

Yes Yarn always sets a new directory into the $PATH for every run, it's quite a nuisance. If we could find a way to disable that behavior it might help ppl.

**Comment by joeljeske** [comment]
Thanks for the info! I had no idea about those flags and I’m sure will be helpful. 

I also didn’t realize that behavior in yarn. I could sanitize path before invoking bazel, but seems a little annoying. 

I think I will prefer a global install of bazelisk and direct invocation instead of executing tasks via yarn scripts. It seems like bazels direct usage seems much better than a grouping of scrips in yarn.

**Comment by marcus-sa** [comment]
This is the script I use to symlink the Bazel binary as a local binary, dunno if `@bazel/bazelisk` offers anything similar?
```sh
#!/bin/bash
set -eo pipefail

bazelBin=$(node -p "require('@bazel/bazel').getNativeBinary()")

# Provide the bazel binary globally. We don't want to access the binary
# through Node as it could result in limited memory.
sudo chmod a+x ${bazelBin}
# sudo cp ${bazelBin} /usr/local/bin/bazel
sudo ln -fs ${bazelBin} /usr/local/bin/bazel
```
