### ISSUE TITLE
npm packages containing files named `build` are detected as `build.bazel` files

### ISSUE THREAD

**Issue by KrauseStefan** [bazelbuild/rules_nodejs#1632]
# 🐞 bug report

### Affected Rule 
The issue is caused by the rule: yarn_install

### Is this a regression?
 Yes, the previous version in which this bug was not present was: ....
No, I upgraded and found the error 

### Description
Upgrading to latest bazel and rules_nodejs to latest version, revealed that the check for `BUILD.bazel` files detects files named `build` as `BUILD.bazel` files.

## 🔬 Minimal Reproduction
Install a npm package with a file named `build` inside it, fx `jshint`.

## 🔥 Exception or Error
<pre><code>
INFO: Call stack for the definition of repository 'npm' which is a yarn_install (rule definition at C:/users/skk/_bazel_skk/ciefjnl3/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:431:16):
 - C:/users/skk/_bazel_skk/ciefjnl3/external/build_bazel_rules_nodejs/index.bzl:84:5
 - <WorkaspaceDir>/client/src/WORKSPACE:55:1
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
        File "C:/users/skk/_bazel_skk/ciefjnl3/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 429
                _create_build_files(<4 more arguments>)
        File "C:/users/skk/_bazel_skk/ciefjnl3/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 155, in _create_build_files
                fail(<1 more arguments>)
generate_build_file.js failed:
STDOUT:

STDERR:
npm package 'htmlhint' from @npm yarn_install rule
has a Bazel BUILD file 'node_modules/jshint/bin/build'. We recommend updating to Bazel 2.1 or greater which ignores such files.

If you can't update Bazel from 1.1.0, you can use the @bazel/hide-bazel-files utility to hide these files.
See https://github.com/bazelbuild/rules_nodejs/blob/master/packages/hide-bazel-files/README.md
for installation instructions.

INFO: Elapsed time: 57.061s
INFO: 0 processes.
</code></pre>

## 🌍  Your Environment

**Operating System:**
<pre><code>Windows 10 1909</code></pre>

**Output of `bazel version`:**
<pre><code>
bazel.exe version
Starting local Bazel server and connecting to it...
Build label: 2.1.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Feb 7 13:02:33 2020 (1581080553)
Build timestamp: 1581080553
Build timestamp as int: 1581080553
Done in 5.59s.
</code></pre>

**Rules_nodejs version:**
<pre><code>
"@bazel/karma": "1.3.0",
"@bazel/rollup": "1.3.0",
"@bazel/typescript": "1.3.0",
urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/1.3.0/rules_nodejs-1.3.0.tar.gz"],
</code></pre>

**Anything else relevant?**
Not that I can think of, pretty simple issue 😃

**Comment by KrauseStefan** [comment]
As a workaround I'm currently setting `always_hide_bazel_files = True` for `yarn_install`

**Comment by alexeagle** [comment]
Like that error message says, the right workaround is to upgrade to Bazel 2.1. Can you do that?

**Comment by KrauseStefan** [comment]
I already upgraded to Bazel 2.1.0

**Comment by alexeagle** [comment]
oh, sorry that was in your post.

The error says "If you can't update Bazel from 1.1.0" so I think maybe you upgraded something on your machine to bazel 2.1.0 but that's not actually the version being used for this execution. Maybe your package.json still has 1.1.0? it's coming from somewhere...

**Comment by KrauseStefan** [comment]
I had an old bazel hiding in my system path, that in some cases where used instead of the checked in one. I should have read the code in `generate_build_file.ts` more carefully.

Sorry about the inconvenience.
