### ISSUE TITLE
Cache misses for rules that use `run_npm.sh.template`

### ISSUE THREAD

**Issue by joeljeske** [bazelbuild/rules_nodejs#1637]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: pkg_npm

### Is this a regression?

  Not sure..

### Description

 A clear and concise description of the problem...

I am experiencing remote cache misses for pkg_npm due to its used of "run_npm.sh.template" and the fact that the paths in those generated files are absolute from `/` and thus not portable across machines. 

Relevant code: 

https://github.com/bazelbuild/rules_nodejs/blob/1.3.0/internal/node/node_repositories.bzl#L525-L530

Contents of my `run_npm.sh.template`

```
"/private/var/tmp/_bazel_jjeske/ca38e9361951c2708a9402d836e79bb6/external/nodejs_darwin_amd64/bin/node" "/private/var/tmp/_bazel_jjeske/ca38e9361951c2708a9402d836e79bb6/external/nodejs_darwin_amd64/bin/nodejs/lib/node_modules/npm/bin/npm-cli.js" TMPL_args "$@"

```

Anything using `pkg_npm` rule will not share cache hits on different machines

The contents of the file:  `@nodejs//:run_npm.sh.template` contains absolute paths

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS 10.14.6
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.3.0
Build label: 2.1.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Feb 7 13:04:00 2020 (1581080640)
Build timestamp: 1581080640
Build timestamp as int: 1581080640
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
1.3.0
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
Hmm @gregmagolan we just merged https://github.com/bazelbuild/rules_nodejs/commit/25600ea4c307c120d04a14c6d41644a3e8d3ed3a which I think will make this problem worse.

I think we need to use `./thing` paths for node rather than absolute, by knowing what Bazel will set the PWD

**Comment by gregmagolan** [comment]
https://github.com/bazelbuild/rules_nodejs/commit/25600ea4c307c120d04a14c6d41644a3e8d3ed3a shouldn't have any effect on the cache as they are just env vars setup within an action and not part of any inputs or action_envs. 

However, this is a good find and we should fix `@nodejs//:run_npm.sh.template` to use relatives.
