### ISSUE TITLE
Support named outputs in rollup_bundle when output_dir = True

### ISSUE THREAD

**Issue by joeljeske** [bazelbuild/rules_nodejs#1642]
# 🚀 feature request

### Relevant Rules

rollup_bundle

### Description

I think it is common to use rollup_bundle with output_dir = True when you have a library with either multiple asset types (e.g. images / css / importmap) or if you have dynamic imports that result in multiple JS chunks. Using this makes it cumbersome to access the various files inside the resulting declared_dir usually resulting the writing of custom rules to be able to access specific types of files in downstream rules. 

### Describe the solution you'd like

It would be nice if I could declare either specific files or patterns of files when invoking the rollup_bundle rule and then be able to access those in a more bazel-like fashion, either using OuputGroupInfo or named output labels. 

I'm not sure if it would be possible to support "patterns" as opposed to specific sets of named files as I think the rule must declare these outputs before the build begins. 

### Describe alternatives you've considered

Custom rules to manually copy files from inside the output_dir to another location and declare them as outputs for downstream rules.

**Comment by alexeagle** [comment]
I wanted the same thing and had implemented it originally - but it's not compatible with RBE. The protocol expects that TreeArtifact (directory output) do not overlap with predeclared outputs.
You could imagine a scheme where the action writes some files twice, one under the tree artifact and again in another location, allowing the second copy to have some output files labelled. But then downstream tooling would have to be aware of the custom resolution needed to resolve relative references between the two output locations.

Do you have a specific proposal for how this could work?

**Comment by joeljeske** [comment]
Perhaps for each output, another action is run that copies it out from within the output dir. would that be compatible with RBE?

(Also, how far away is it from being public, I would like to use it... :)
