### ISSUE TITLE
test is failing with package.json in a package outside of WORKSPACE 

### ISSUE THREAD

**Issue by cshunger** [bazelbuild/rules_nodejs#1649]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 

test
### Is this a regression?
No

### Description

Running `bazel test //client/...` caused this issue when package.json and node_modules are in a package separate from the WORKSPACE.

```
.
├── BUILD.bazel
├── client
│   ├── BUILD.bazel
│   ├── config
│   │   ├── babel.config.js
│   │   └── jest.config.js
│   ├── jest.bzl
│   ├── package.json
│   ├── patches
│   │   └── jest-haste-map+24.9.0.patch
│   ├── src
│   │   ├── extra.js
│   │   ├── index2.test.js
│   │   ├── index.js
│   │   └── index.test.js
│   └── yarn.lock
├── README.md
└── WORKSPACE
```

## 🔬 Minimal Reproduction

https://github.com/cshunger/jest_rules

## 🔥 Exception or Error

<pre><code>
INFO: From Testing //client:test:
==================== Test output for //client:test:
FAIL client/src/index2.test.js
  ● Test suite failed to run

    /home/cshunger/.cache/bazel/_bazel_cshunger/e0302b4c29f2b14434fed84ff88e1e35/sandbox/linux-sandbox/1/execroot/examples_jest/bazel-out/k8-fastbuild/bin/client/test.sh.runfiles/examples_jest/client/src/index2.test.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import indexfile from './index.js';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at ScriptTransformer._transformAndBuildScript (../node_modules/jest-runtime/node_modules/@jest/transform/build/ScriptTransformer.js:537:17)

FAIL client/src/index.test.js
  ● Test suite failed to run

    /home/cshunger/.cache/bazel/_bazel_cshunger/e0302b4c29f2b14434fed84ff88e1e35/sandbox/linux-sandbox/1/execroot/examples_jest/bazel-out/k8-fastbuild/bin/client/test.sh.runfiles/examples_jest/client/src/index.test.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import indexfile from './index.js';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at ScriptTransformer._transformAndBuildScript (../node_modules/jest-runtime/node_modules/@jest/transform/build/ScriptTransformer.js:537:17)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        0.723s
Ran all test suites.
================================================================================
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu  x86_64
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 2.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 19 12:30:18 2019 (1576758618)
Build timestamp: 1576758618
Build timestamp as int: 1576758618
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "b6670f9f43faa66e3009488bbd909bc7bc46a5a9661a33f6bc578068d1837f37",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/1.3.0/rules_nodejs-1.3.0.tar.gz"],
)

  </code>
</pre>

**Anything else relevant?**

**Comment by flolu** [comment]
@cshunger Did you get it running?

**Comment by cshunger** [comment]
@flolu no, I never got this working.

**Comment by flolu** [comment]
@cshunger Ok :laughing:
