### ISSUE TITLE
rules_nodejs red on Bazel CI

### ISSUE THREAD

**Issue by lfpino** [bazelbuild/rules_nodejs#165]
Hi there,

I'm seeing some failures in Bazel CI regarding rules_nodejs on Windows: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/178#9232903f-1ba0-4670-8bea-083172a0991e

The relevant part of the error message seems to be the following:
```
D:\temp\tmpo92aq8_a\bazel-bin/src/bazel build --show_progress_rate_limit=5 --curses=yes --color=yes --keep_going --jobs=32 --build_event_json_file=D:\temp\tmpo92aq8_a\build_bep.json --experimental_build_event_json_file_path_conversion=false --announce_rc //... -//:docs
(...)
ERROR: Skipping '//... -//:docs': The package part of '//... -//:docs' should not end in a slash
WARNING: Target pattern parsing failed.
ERROR: command succeeded, but there were errors parsing the target pattern
```

Can you please take a look?

Thanks!

**Comment by lfpino** [comment]
Friendly ping @alexeagle

**Comment by alexeagle** [comment]
Hi @lfpino can you help me understand why the "presubmit" buildkite job passes? I see a green status on this repo, pointing to https://buildkite.com/bazel/nodejs-rules-nodejs-postsubmit

If I don't have enforcement in presubmit, I can't avoid breaking this again in the future.

**Comment by lfpino** [comment]
Hi Alex, I don't really know but I think @buchgr will be able to answer.

**Comment by alexeagle** [comment]
I tried to fix this
https://github.com/bazelbuild/rules_nodejs/commit/a224f2d7bf94a5d83055e37278e663837a16e860

Now I get
```
bazel build --show_progress_rate_limit=5 --curses=yes --color=yes --keep_going --jobs=32 --build_event_json_file=D:\temp\tmpuxviq13h\build_bep.json --experimental_build_event_json_file_path_conversion=false --announce_rc //... -//:docs
--
  | ERROR: Invalid options syntax: -//:docs
```

Can you help me understand how to configure the bazel CI with an exclusion pattern @buchgr ?

**Comment by jin** [comment]
@alexeagle I think all you need is a `--` escape before specifying the targets, like this: https://github.com/bazelbuild/bazel/blob/master/.bazelci/presubmit.yml#L13

**Comment by alexeagle** [comment]
Of course, that should have been obvious - I guess I was distracted by the yaml syntax. Thanks, fixed in https://github.com/bazelbuild/rules_nodejs/commit/cd85cfa1430bdae272d8673afd9502c9212d264a
