### ISSUE TITLE
How to use google-protobuf generated code in ts_devserver

### ISSUE THREAD

**Issue by ogeidix** [bazelbuild/rules_nodejs#1656]
Hi,

I have .js files with CommonJS import style generated via
https://github.com/rules-proto-grpc/rules_proto_grpc/tree/master/nodejs#nodejs_proto_compile
that I am struggling to get working with ts_devserver.

I saw several issues in the tracker regarding umd / amd conversions but I am getting more and more lost.

Is there a recommended way to load CommonJS import-style code in a project?

Thanks

**Comment by alexeagle** [comment]
ts_devserver is probably not what you want for serving an app that wasn't built by the "google3 toolchain" (rules like `ts_library`)
We touch on it a bit on https://github.com/bazelbuild/rules_nodejs/blob/master/packages/typescript/docs/install.md#serving-typescript-for-development
See https://github.com/bazelbuild/rules_nodejs/pull/1695 where @mrmeku is working on this interop, but I think it's still an advanced/complex way to solve it. You're probably better off with a more standard devserver.
We should do more to illustrate this in examples.
