### ISSUE TITLE
Example of using with lerna and yarn workspace.

### ISSUE THREAD

**Issue by jjangga0214** [bazelbuild/rules_nodejs#1663]
Hi!

Many people are using lerna and/or yarn workspace.

I guess either migrating from them to Bazel, or just using them with Bazel together is good to be guided with an example project or tutorial.

For example, currently I have a directory structure like this, where foo is an express server and bar is a library consumed by foo, both based on typescript. 

```
<project root>
├── jest.config.js
├── lerna.json
├── package.json
├── packages
│   ├── bar
│   │   ├── jest.config.js
│   │   ├── package.json
│   │   ├── src
│   │   │   └── index.ts
│   │   ├── test
│   │   │   └── unit
│   │   │       └── index.test.ts
│   │   ├── tsconfig.build.json
│   │   └── tsconfig.json
│   └── foo
│       ├── jest.config.js
│       ├── package.json
│       ├── src
│       │   ├── hello.ts
│       │   └── index.ts
│       ├── test
│       │   ├── integration
│       │   │   └── index.test.ts
│       │   └── unit
│       │       └── index.test.ts
│       ├── tsconfig.build.json
│       └── tsconfig.json
├── tsconfig.build.json
├── tsconfig.json
└── yarn.lock
```

How should I align it with Bazel, like you know, WORKSPACE, BUILD, and their contents?

Any tips or examples?

Thanks!

**Comment by pauldraper** [comment]
Bazel could be considered alternative to yarn/lerna monorepos. Instead of writing dependencies in multiple package.json files, you'd write the dependencies in multiple targets in BUILD files. You'd also have a package.json of all external dependencies (using yarn aliases if you need multiple versions of a package installed).

This works pretty well, though it can be more cumbersome for projects that need to translate the monorepo structure back to externally publish npm packages.

```
<project root>
├── BUILD
├── WORKSPACE # manage node_modules
├── jest.config.js
├── lerna.json
├── package.json
├── packages
│   ├── bar
│   │   ├── BUILD # src target and test target
│   │   ├── jest.config.js
│   │   ├── src
│   │   │   └── index.ts
│   │   ├── test
│   │   │   └── unit
│   │   │       └── index.test.ts
│   │   ├── tsconfig.build.json
│   │   └── tsconfig.json
│   └── foo
│       ├── BUILD # src target and test target
│       ├── jest.config.js
│       ├── src
│       │   ├── hello.ts
│       │   └── index.ts
│       ├── test
│       │   ├── integration
│       │   │   └── index.test.ts
│       │   └── unit
│       │       └── index.test.ts
│       ├── tsconfig.build.json
│       └── tsconfig.json
├── tsconfig.build.json
├── tsconfig.json
└── yarn.lock
```
