### ISSUE TITLE
Add `tsconfig` to providers returned by `compile_ts`

### ISSUE THREAD

**Issue by jroylance** [bazelbuild/rules_nodejs#1670]
# 🚀 feature request

### Relevant Rules

I'd like functionality to be added to `compilation.bzl`, which shouldn't affect any of the rules but may affect rules that depend on, say, `ts_library`. 

### Description

I'm writing a rule in my repo that requires access to the `tsconfig` generated by the `ts_library` rule. If possible, the `tsconfig` file should be added be added to one of the providers returned by `compile_ts` in `compilation.bzl` so the file can be used in a downstream rule. 

### Current workaround

Currently, I'm patching the `@bazel/typescript` package to do what I describe above, but this may be a feature that would be widely beneficial if implemented.

**Comment by alexeagle** [comment]
It's an output of the ts_library rule already
https://github.com/bazelbuild/rules_nodejs/blob/066a52c43052cfb5b32cc2effe52c4d31c133715/packages/typescript/src/internal/build_defs.bzl#L423-L425
so you can for example build
`//packages/typescript/test/some_library:lib_tsconfig.json` in this repo
to get `dist/bin/packages/typescript/test/some_library/lib_tsconfig.json`
and you can depend on that label from another rule that wants to read the tsconfig.

Does that do what you need?

**Comment by jroylance** [comment]
You're absolutely right, sorry about that! That's exactly what I need.
