### ISSUE TITLE
ts_library data not exposed to dependencies

### ISSUE THREAD

**Issue by duarten** [bazelbuild/rules_nodejs#1672]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 

`ts_library`

### Description

 A clear and concise description of the problem...

`ts_library` data attribute not exposed to dependencies.

## 🔬 Minimal Reproduction

Consider the following rules. The `ts_library` `foo` has the output from `web` as data.
```py
pkg_web(
    name = "web",
    srcs = [
        "bundle",
        "public/index.html",
    ],
)

ts_library(
    name = "foo",
    srcs = ["foo.ts"],
    data = [":web"],
    tsconfig = "//:tsconfig.base.json",
    visibility = ["//visibility:public"],
    deps = [
        "@npm//@types/node",
    ],
)
```

If these are consumed by a dependency, say, in package `bar`: 

```py
ts_library(
    name = "lib",
    srcs = glob(["*.ts"]),
    tsconfig = "//:tsconfig.base.json",
    deps = [
        "//web:foo"
   ]
)
```

Then the data files are missing from the runfiles. That is:

```
❯ ls bazel-bin/bar/bar.sh.runfiles/root/web
foo.js
```

## 🔥 Exception or Error

No error, but unexpected behavior.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macos
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 2.1.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Feb 7 13:04:00 2020 (1581080640)
Build timestamp: 1581080640
Build timestamp as int: 1581080640
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
 1.3.0
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
I agree it ought to work like you described, that the data attribute is propagated all the way to runfiles of a binary that transitively depends on the `ts_library`

**Comment by duarten** [comment]
I tried to solve this for the particular case of rollup needing a data file of the `ts_library` (in my case, a css file for processing with PostCSS).

The data files are collected in the runfiles of the `ts_library`, but are not present on disk. I tried modifying `rollup_bundle` to add those files as dependencies, but still they were not on disk:

```py
deps_depsets = []
for dep in ctx.attr.deps:
    # ...

    if hasattr(dep, "data_runfiles"):
        deps_depsets.append(dep.data_runfiles.files)
```

It would be great if you could offer some guidance as to what's missing :)

**Comment by ajbouh** [comment]
@duarten did you ever get this working?

**Comment by jschaf** [comment]
I've hit this bug using esbuild to consume a ts_library that imports CSS. I'm not sure how to propagate the CSS to esbuild:

```bzl
filegroup(
    name = "css",
    srcs = glob(["src/**/*.css"]),
)

ts_library(
    name = "src",
    srcs = glob(
        [
            "src/**/*.ts",
            "types/*.d.ts",
            "src/**/*.tsx",
        ],
    ),
    data = [":css"],
    devmode_target = "esnext",
    prodmode_target = "esnext",
    tsconfig = ":tsconfig",
    deps = ["@erp_app_npm//:node_modules"],
)

esbuild(
    name = "bundle-prod",
    define = ['process.env.NODE_ENV="production"'],
    entry_point = "src/index.tsx",
    format = "iife",
    minify = True,
    platform = "browser",
    target = "esnext",
    deps = [
        ":css",
        ":src",
    ],
)
```
