### ISSUE TITLE
My rollup_bundle doesn't resolve angular dependencies like "@angular/animations"

### ISSUE THREAD

**Issue by jiaqi** [bazelbuild/rules_nodejs#1673]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule:  rollup_bundle

### Is this a regression?

Not sure. This is the first time I try.

### Description

I'm trying to put together a minimal Angular app in https://github.com/jiaqi/angular-on-java/blob/master/webapp/aoj/BUILD. It's almost identical to the example/angular here except it's just one empty page. The js file generated from rollup_bundle in my project starts with

```
import { AnimationBuilder, sequence, AnimationFactory } from '@angular/animations';
...
```
The Angular example in this repository works fine on my computer so clear I'm missing something, but I can't tell. I hope someone here can take a look and tell me what I miss. Thanks.

## 🔬 Minimal Reproduction

If you checkout https://github.com/jiaqi/angular-on-java and run `bazel build webapp/aoj:js_bundle`, then you can see the generated js file with `less bazel-bin/webapp/aoj/js_bundle/index.js`.

## 🔥 Exception or Error

The generated file starts with `import ... from '@angular/animations';`

## 🌍  Your Environment

**Operating System:**

MacOS Catalina, 10.15.3

**Output of `bazel version`:**

2.1.0

**Rules_nodejs version:**

**Anything else relevant?**

**Comment by joeljeske** [comment]
Have you tried setting “@npm//@angular/animations” as a dep for the rollup bundle?

**Comment by alexeagle** [comment]
+1 to that - if you included the output from running rollup I bet there's a warning in there about missing the dependency

**Comment by jiaqi** [comment]
Great! I'm curious how animations dependency was pulled in. The example doesn't have it and my application is simpler than the example.
But the problem is solved, so thank you all for the help.
