### ISSUE TITLE
Runfiles are not used when available on Windows

### ISSUE THREAD

**Issue by filipesilva** [bazelbuild/rules_nodejs#1689]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: Unsure. I think it's caused by the manifest lookup logic for windows.

### Is this a regression?

 No.

### Description

Following https://github.com/bazelbuild/bazel/issues/5807, it is possible to use runfiles on Windows for machines that have symlinks enabled. 
The option that controls this is `--enable-runfiles`, defaulting to false on Windows and to true on other OSs.

When using runfiles, `bazel run` and `bazel test` should use a directory populated with these runfiles.
However, using `rules_nodejs` that doesn't happen.

## 🔬 Minimal Reproduction

```
git clone https://github.com/filipesilva/rules_nodejs_windows_runfiles
cd rules_nodejs_windows_runfiles
npm install
npm run example
```

In Linux, you will see this output:
```
file path is /home/filipesilva/.cache/bazel/_bazel_filipesilva/8aae2c1c8f8783e029b7d6963ffe91c3/execroot/rules_nodejs_windows_runfiles/bazel-out/k8-fastbuild/bin/example.sh.runfiles/rules_nodejs_windows_runfiles/main.js
```

You can tell the runfiles directory is user because the path contains `example.sh.runfiles`.

On Windows, you will see this output:
```
file path is D:\sandbox\rules_nodejs_windows_runfiles\main.js
```

This is the wrong path. 
Instead, it should have been `C:\users\kamik\_bazel_kamik\xv6tfi25\execroot\rules_nodejs_windows_runfiles\bazel-out\x64_windows-fastbuild\bin\example.bat.runfiles\rules_nodejs_windows_runfiles\main.js` (note the `example.bat.runfiles` part).

This is an important distinction given that on Windows data files are present only in their source location when not using runfiles.
Attempting to resolve output files relative to data files on Windows is thus not possible without runfiles.

## 🌍  Your Environment

**Operating System:**

<pre>
Windows 10
</pre>

**Output of `bazel version`:**

<pre>
Bazelisk version: v1.3.0
Build label: 2.1.1
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Feb 21 15:00:01 2020 (1582297201)
Build timestamp: 1582297201
Build timestamp as int: 1582297201
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
1.4.0
</pre>

**Anything else relevant?**

**Comment by danielepolencic** [comment]
I'm having the same issue, I think.

I have a collection of assets as part of a `filegroup` which is used by a `ts_library`. However, none of them are usable once I run the `nodejs_binary` rule — on Windows.

When the program starts, I can see plenty of errors that the assets do not exist.

I checked the path and it does not exist.

The same rule works fine on a Mac.
I enabled the dev mode on windows as well as added the `--enable-runfiles` flag but without any success.

**Comment by petebacondarwin** [comment]
Chiming in that I have also just hit this issue with a proposed change to the Angular compiler tests: https://app.circleci.com/pipelines/github/angular/angular/24266/workflows/3e6fcb2e-5aea-4be8-b1e7-16228a563330/jobs/852079

Did anyone ever find a workaround?

**Comment by petebacondarwin** [comment]
For what it's worth, I was able to use the `copy_to_bin` rule instead of `file_group` to achieve the result that I wanted.

**Comment by filipesilva** [comment]
It's been a while but I think `rules_nodejs` just doesn't try to use runfiles on windows even if available. I think this is set somewhere in the initialization scripts, but don't remember details. Perhaps https://github.com/bazelbuild/rules_nodejs/blob/stable/internal/node/launcher.sh.
