### ISSUE TITLE
Can't run some postinstall scripts with npm_install or yarn_install

### ISSUE THREAD

**Issue by JaredNeil** [bazelbuild/rules_nodejs#169]
If a postinstall script requires additional files (i.e. https://github.com/alexeagle/angular-bazel-example/blob/master/package.json#L30), then it fails with `Error: ENOENT: no such file or directory`.

I'm guessing this is because the path to the file is no longer correct, but that's just a guess.

Is there a way to get that to work?

**Comment by alexeagle** [comment]
Yeah it seems like we should be able to set the working directory in https://github.com/bazelbuild/rules_nodejs/blob/3368e8b6f573226873a7c44a2da3105ef1fe8baf/internal/npm_install/npm_install.bzl#L65 but it's not clear if that belongs in https://docs.bazel.build/versions/master/skylark/lib/repository_ctx.html#execute `environment`
