### ISSUE TITLE
Not able to compile

### ISSUE THREAD

**Issue by sonukapoor** [bazelbuild/rules_nodejs#1697]
# 🐞 bug report

I am cross-posting this from the Angular repo, in the case, it was missed there. 

https://github.com/angular/angular/issues/35891

### Affected Rule

Not sure, I have tried this with the following two versions and get the same result:

node-v12.13.0-win-x64.zip
node-v12.14.1-win-x64.zip

### Is this a regression?

 

I doubt it. 

### Description

 

When running any command using `yarn bazel...`, I get the below errors. I am not able to successfully run the commands.  For the below output, I ran `yarn bazel test //packages/service-worker/test`. 

```
ERROR: C:/projects/archive/angular/packages/service-worker/test/BUILD.bazel:26:1 Compiling TypeScript (devmode) //packages/zone.js/lib:zone_d_ts failed: Worker process quit or closed its stdin stream when we tried to send a WorkRequest:

---8<---8<--- Exception details ---8<---8<---
java.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(356): NativeProcess:WriteStdin(9028): The pipe is being closed.
```

## 🔥 Exception or Error

[log.txt](https://github.com/bazelbuild/rules_nodejs/files/4304499/log.txt)

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Windows 10 
Version 1909
OS Build 18363.57
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 2.1.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Feb 7 13:02:33 2020 (1581080553)
Build timestamp: 1581080553
Build timestamp as int: 1581080553
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
// tried both of these
node-v12.13.0-win-x64.zip
node-v12.14.1-win-x64.zip
  </code>
</pre>

**Comment by alexeagle** [comment]
I'll reply on the original issue.
