### ISSUE TITLE
rollup_bundle srcs are not visible to files reachable from entry_point

### ISSUE THREAD

**Issue by duarten** [bazelbuild/rules_nodejs#1698]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 
`rollup_bundle()`

### Description

Including a file in the `rollup_bundle` `srcs` doesn't make it available to `entry_point` files.

Assuming I add `tailwind.css` to `srcs`, it is available at `.../execroot/root/pkg/tailwind.css`. My index file, on the other hand, is at `.../execroot/root/bazel-out/darwin-dbg/bin/pkg/src/index.mjs`.

## 🔬 Minimal Reproduction

```py
ts_library(
    name = "lib",
    srcs = glob([
        "src/**/*.ts",
    ]),
    tsconfig = "tsconfig",
    deps = [
    ],
)

rollup_bundle(
    name = "bundle",
    srcs = [
        "tailwind.css",
    ],
    config_file = "rollup.config.js",
    entry_point = "src/index.ts",
    format = "iife",
    output_dir = False,
    sourcemap = "inline",
    deps = [":lib"]
```

## 🔥 Exception or Error

<pre><code>
[!] Error: Could not resolve '../tailwind.css' from bazel-out/darwin-dbg/bin/pkg/src/index.mjs
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
  macOS
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 2.1.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Feb 7 13:04:00 2020 (1581080640)
Build timestamp: 1581080640
Build timestamp as int: 1581080640
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
1.3.0
  </code>
</pre>

**Anything else relevant?**

**Comment by duarten** [comment]
The same thing happens to data carried from a dependency to `rollup_bundle`.

Assume this change to the rule:

```diff
diff --git a/packages/rollup/src/rollup_bundle.bzl b/packages/rollup/src/rollup_bundle.bzl
index f5cf732d..3b2abb76 100644
--- a/packages/rollup/src/rollup_bundle.bzl
+++ b/packages/rollup/src/rollup_bundle.bzl
@@ -394,7 +394,13 @@ def _rollup_bundle(ctx):
     )

     return [
-        DefaultInfo(files = depset(outputs)),
+        DefaultInfo(
+            files = depset(outputs),
+            runfiles = ctx.runfiles(
+                collect_default = True,
+                collect_data = True,
+            ),
+        ),
     ]

 rollup_bundle = rule(
```

Then, the rules:

```starlark
ts_library(
    name = "lib",
    srcs = glob([
        "src/**/*.ts",
    ]),
    tsconfig = "tsconfig",
    data = [file.json],
)

rollup_bundle(
    name = "bundle",
    config_file = "rollup.config.js",
    entry_point = "src/index.ts",
    format = "iife",
    output_dir = False,
    sourcemap = "inline",
    deps = [":lib"]
```

Then, in rollup's run_files, the js files of `lib` will be under `bazel-out`, but the data file will not. This will break the import paths and rollup will be unable to find `file.json`. 

Is the correct fix should be to have `ts_library` link the data files in the `bazel-out` dir with the output js files to preserve import paths?

**Comment by alexflk** [comment]
I think I'm running into an issue with this root cause. In the meantime is there any way to make css visible via rollup?

**Comment by alexflk** [comment]
Ended up using copy_to_bin as suggested in #1771. However, it would be great if this use case was better supported.
