### ISSUE TITLE
make @bazel/jasmine jasmine dep a peerDeps

### ISSUE THREAD

**Issue by Toxicable** [bazelbuild/rules_nodejs#1702]
If a repository wants to change their jasmine version they should be able to do it without waiting for @bazel/jasmine to adjust the version.
Using peerDeps fixes this by forcing the user to install jasmine and @bazel/jasmine will use whatever the user has installed.

This is a breaking change so could be good for 2.0

**Comment by Toxicable** [comment]
Putting it on the 2.0 milestone for consideration

**Comment by joeljeske** [comment]
Couldn’t this also be solved by using a minor patch floating version? Then the user could install a specific version if desired or else default to the latest one specified by bazel/jasmine?

**Comment by evahowe** [comment]
@Toxicable is what @joeljeske saying true?  Or no?

**Comment by alexeagle** [comment]
@Toxicable ping!

**Comment by alexeagle** [comment]
Fixed by #1703
