### ISSUE TITLE
Jest Coverage Does Not Fail

### ISSUE THREAD

**Issue by collin-miller** [bazelbuild/rules_nodejs#1729]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 
Jest Example rule

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
When running our jest rule using the Jest coverage configuration the coverage thresholds are not honored and because of this the test does not fail; however, the coverage reports are generated with the expected output.

## 🔬 Minimal Reproduction
add this to the `jest.config.js` file. If you actually do have 100% coverage comment out the implementation of a test and instead fill in with `expect(1).toEqual(1)` so you can have a passing test to decrease your coverage below 100%.
```json

testMatch: ["**/*.test.js", "**/*.test.ts"],
  coverageThreshold: {
    global: {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100
    }
  },
  collectCoverage: true,

```

## 🔥 Exception or Error

<pre><code>

</code>None</pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS Catalina 10.15.3
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
bazel 2.2.0
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
1.4.1
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
I'm not sure how this is a Bazel issue - the bazel test target fails if the jest process returns a non-zero exit code. Can you run the jest process outside of Bazel and debug why it's exiting zero in a case where you expect it not to?

**Comment by collin-miller** [comment]
@alexeagle, I was claiming there was a "bug" in the example. It works fine if you're using JavaScript with Jest; however, Jest with TypeScript was a different animal.

I figured it out. The best way to get Jest working with TypeScript and running code coverage is to use Babel to compile your TypeScript code. For some reason I couldn't get the `ts-jest` module working with Bazel.

There are some examples online that suggest compiling the code using `ts_library` then running jest using the compiled JavaScript; this also does not work with the way Jest runs coverage.

**Comment by smhmayboudi** [comment]
@collin-miller I am facing like your problem and I can not use babel since I have generic test in my code. Would you please share your package and babel config, it may help. thanks.

**Comment by alexeagle** [comment]
Sounds like we need to include this in our examples

**Comment by smhmayboudi** [comment]
@alexeagle I appreciate it. After switching to the rc2, the coverage command is working but there is no coverage data is produced.  After inspecting the Jasmin I see the coverage switch should be pass to the jest command and I am working on it. Please provide the Istanbul coverage in your example as well. Thanks

**Comment by collin-miller** [comment]
I've tried to paste a sample solution a few times but the new GitHub UI messes with the formatting. Let's keep it open and I can try again.

**Comment by collin-miller** [comment]
@smhmayboudi @alexeagle this is the basic coverage rule and config setup I was able to get working. You just need the additional dependencies set in the rule.


`tools/coverage/typescript/coverage.bzl`
```skylark
load("@npm//jest-cli:index.bzl", _jest_test = "jest_test")

def ts_coverage_test(name, srcs, deps = [], **kwargs):
    """A macro around the autogenerated jest_test rule

    Args:
        name (str): Name of the rule
        srcs (list): List of srcs
        deps (list): List of deps
        **kwargs (any): Additional rule keyword arguments
    """

    args = [
        "--no-cache",
        "--no-watchman",
        "--ci",
    ]

    native.genrule(
        name = "jest_config",
        srcs = ["//tools/coverage/typescript:jest.config.js"],
        outs = ["jest.config.js"],
        cmd = "cp $< $@",
        output_to_bindir = True,
    )

    args.extend(["--config", "$(location :jest_config)"])

    for src in srcs:
        args.extend(["--runTestsByPath", "$(locations %s)" % src])

    _jest_test(
        name = name,
        data = srcs + deps + [
            ":jest_config",
            "@npm//@bazel/typescript",
            "@npm//@types/jest",
            "@npm//ts-jest",
        ],
        args = args,
        **kwargs
    )
```

`tools/coverage/typescript/jest.config.js`
```javascript
module.exports = {
  testEnvironment: 'node',
  testMatch: ['**/*.test.js', '**/*.test.ts', '**/*.spec.js', '**/*.spec.ts'],
  preset: 'ts-jest',
  coverageThreshold: {
    global: {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100
    }
  },
  clearMocks: true,
  collectCoverageFrom: ['**/*.{js,ts}', '!**/*.{test,spec}.{js,ts}'],
  resetMocks: true,
  resetModules: true,
  restoreMocks: true,
  verbose: true,
  collectCoverage: true
};```
