### ISSUE TITLE
ts_library compiles tsx files to js not jsx

### ISSUE THREAD

**Issue by calebmer** [bazelbuild/rules_nodejs#1730]
On first glance this appears to be incorrect because `ts_library` compiles `.tsx` files to `.js` and not `.jsx`. Am I missing something or could we change this?

https://github.com/bazelbuild/rules_nodejs/blob/04204df8848faf9024d8200bff32e8f0db82003c/internal/node/node.bzl#L120-L121

**Comment by alexeagle** [comment]
you're right, not just `ts_library` but also `tsc` produces `.js` for `.tsx` inputs, so this is the entry point we should be looking for.

I'm surprised you wrote a node program with a `.tsx` extension though... is that the entry point for server-side rendering or something?

**Comment by calebmer** [comment]
at Airtable we use the convention that _all_ TypeScript files have the `.tsx` extension

we think of it as TypeScript syntax v2 so instead of supporting three dialects (JS, TS, TSX) we choose to only support two
