### ISSUE TITLE
npm_package_bin swallows errors when using glob in addition to root directory

### ISSUE THREAD

**Issue by migueloller** [bazelbuild/rules_nodejs#1744]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: `npm_package_bin`

### Description

When using `npm_package_bin` or any macro that uses it (e.g., `load(@npm//@babel/cli:index.bzl`) using the `glob` function causes downstream errors from the binary (e.g., `babel`) to be swallowed and instead Bazel fails with the following error:

```
ERROR: /path/to/BUILD:18:1: Action path/to/target failed: I/O exception during sandboxed execution: path/to/glob/root (File exists)
Target //path/to:target failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

## 🔬 Minimal Reproduction

When calling `babel` without any arguments, one expects the error output to be:

```
babel:
  stdin compilation requires either -f/--filename [filename] or --no-babelrc
```

In any project with `@babel/cli` as a dependency and the following BUILD file, the expected error from Babel is swallowed, and instead the error described above is seen. If either the glob or the `src` target are removed, then the error from Babel isn't swallowed anymore.

```starlark
load("@build_bazel_rules_nodejs//:index.bzl", "npm_package_bin")

npm_package_bin(
    name = "babel",
    data = ["src"] + glob(["src/**/*.ts"])
    output_dir = True,
    tool = "@npm//@babel/cli/bin:babel",
)
```

## 🌍  Your Environment

**Operating System:**

```
macOS Catalina v10.15.4
```

**Output of `bazel version`:**

```
Bazelisk version: v1.3.0
Build label: 2.2.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Mar 3 09:28:15 2020 (1583227695)
Build timestamp: 1583227695
Build timestamp as int: 1583227695
```

**Rules_nodejs version:**

```
v1.4.1
```

**Comment by migueloller** [comment]
After digging deeper, it seems this is an issue with Bazel itself. Here's how to reproduce:

```starlark
genrule(
    name = "repro",
    srcs = [
        "dir",
        "dir/file",
    ],
    outs = ["file"],
    cmd = "touch $(execpath file) && >&2 echo Boom! && exit 1",
)
```

One would expect Bazel to fail and show `Boom!`, but instead it shows the `(File exists)` error.

I'll open an issue in https://github.com/bazelbuild/bazel.

**Comment by alexeagle** [comment]
Thanks for digging and determining what layer has the problem.

**Comment by migueloller** [comment]
I'm going to close this given that the root cause is upstream.
