### ISSUE TITLE
Cannot resolve dependency by module_name using ts_library import

### ISSUE THREAD

**Issue by rauljordan** [bazelbuild/rules_nodejs#1745]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule:
ts_library

### Is this a regression?
I don't think so

### Description

Created a protobuf in a top-level directory `/proto/api/v1` and defined their js output as a ts_library. Gave the library `module_name = "@proto/api/v1"` and I am now trying to use it in my angular application, but calling `import { API } from '@proto/api/v1;` says the module cannot be found. I included the library as a dep to my ng_module target in the frontend/src/BUILD.bazel file and this still occurs. Created a minimal repository for reproducing the issue fully: https://github.com/rauljordan/angular-bazel-proto

## 🔬 Minimal Reproduction

Can be fully reproduced by running `bazel run //frontend/src:devserver` in https://github.com/rauljordan/angular-bazel-proto. 

In proto/api/v1/BUILD.bazel

```
ts_library(
    name = "v1",
    srcs = glob(["**/*.ts"]),
    module_name = "@proto/api/v1",
    tsconfig = "//frontend:tsconfig.json",
    visibility = ["//visibility:public"],
    deps = [":ts_proto"],
)
```

and in frontend/src/BUILD.bazel

```
ng_module(
    name = "src",
    tsconfig = "//frontend:tsconfig.json",
    srcs = glob(
        include = ["**/*.ts"],
        exclude = [
            "**/*.spec.ts",
            "main.ts",
            "test.ts",
            "initialize_testbed.ts",
        ],
    ),
    assets = glob([
      "**/*.css",
      "**/*.html",
    ]) + ([":styles"] if len(glob(["**/*.scss"])) else []),
    generate_ve_shims = True,
    deps = [
        "@npm//@angular/core",
        "@npm//@angular/platform-browser",
        "@npm//@angular/router",
        "@npm//@types",
        "@npm//rxjs",
        "//proto/api/v1:v1",
    ],
)
```

Finally, in `app.component.ts`
```js
import { API } from '@proto/api/v1';
```

## 🔥 Exception or Error

<pre><code>
frontend/src/app/modules/landing/pages/landing/landing.component.ts:2:21 - error TS2307: Cannot find module '@proto/api/v1'.

-> import { API } from '@proto/api/v1';

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Darwin (MacOS Catalina)
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 2.1.1
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Feb 21 15:00:07 2020 (1582297207)
Build timestamp: 1582297207
Build timestamp as int: 1582297207
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
1.3.0
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
`@proto/api/v1` seems like it's a directory so typescript would have know how to resolve in there. do you have an index.ts file in that lib? is there a package.json with a "main"field? 
Looks to me like you have `frontend/dist/bin/proto/api/v1/ts_proto.d.ts` so you would have to import `@proto/api/v1/ts_proto.d.ts`
also the content of that file suggests it doesn't have exports, but rather declares namespaces, so you're meant to use it as a global variable and a side-effect import.

Sorry but it's not a Bazel question, FWICT we are giving TypeScript a correct path mapping and you have to fix the app.

Maybe relevant that @mrmeku landed some improvements to the ts_proto_library that released today in 1.5.0

**Comment by rauljordan** [comment]
Hi @alexeagle thanks for the response on this - so there are two generated files: ts_proto.d.ts and a ts_proto.js, any thoughts on how would I go about using the js file in the angular app from this generated directory? I just want to be able to (a) generated the ts and go protos from .proto files (which already works), and (b) use the generated js protos in my angular app. Do you know of any sample projects that do something similar?

**Comment by prestonvanloon** [comment]
I'm working with @rauljordan on this. 1.5.0 has resolved our issue. Thanks
