### ISSUE TITLE
Running Karma and Protractor Tests does not work on Google Cloud Build

### ISSUE THREAD

**Issue by flolu** [bazelbuild/rules_nodejs#1746]
# 🐞 bug report

### Affected Rule

The issue is caused by the rules:  Karma and Protractor

### Description

Running [protractor_web_test_suite](https://github.com/bazelbuild/rules_nodejs/blob/1a83a7f139e2e54eb55af3f00b640fc9b505ab7d/examples/angular/e2e/BUILD.bazel#L16) and [karma_web_test_suite](https://github.com/bazelbuild/rules_nodejs/blob/1a83a7f139e2e54eb55af3f00b640fc9b505ab7d/examples/angular/src/app/hello-world/BUILD.bazel#L46) tests on my local machine works totally fine. But running the tests on [Google Cloud Build](https://cloud.google.com/cloud-build) does not work.

## 🔬 Minimal Reproduction

1. Start with the [angular](https://github.com/bazelbuild/rules_nodejs/tree/master/examples/angular) example app
2. Add the following `cloudbuild.yaml` file:
```
steps:
  - id: "e2e tests"
    name: gcr.io/cloud-builders/bazel
    args: ["test",  "//e2e:all"]
  - id: "unit tests"
    name: gcr.io/cloud-builders/bazel
    args: ["test", "//src/..."]
options:
  machineType: "N1_HIGHCPU_8"
```
3. Run it on Google Cloud Build

### e2e Test Errors
Errors are the result of the `protractor_web_test_suite` targets
```
E/launcher - WebDriverError: unknown error: Chrome failed to start: exited abnormally

...

(unknown error: DevToolsActivePort file doesn't exist)
```
You can find the full log [here](https://00e9e64bacd5da54e4401826f69abdeb5f49fc4a017da66847-apidata.googleusercontent.com/download/storage/v1/b/535395706340.cloudbuild-logs.googleusercontent.com/o/log-b75521fc-22d0-4d08-9e5f-66de8933612a.txt?qk=AD5uMEs-0cPqiaK6c4a5wp1_W5YmNrzt54xsgesGczdioSl03nJJYhHzEH4rLmttNUdU9KxIAepF0j0J99_pUsrNwGb9KBx_z5_8DdfpGRpOgMFK0h8ibOr32CPPb2X4lV_kqRDcxD1oc-88CjqBpeX-74DXTZKhe4O0LLdptmdA6P3fCMsq-nY4ucbMTTKAWArRvXX03YejKVLd2bxaeiH_Y2W_8BXb97DgdjNt9BL-nw4b99T3y7cB7cZwlmqnA6covEaC7N7VaowuC4uWM2b_A4tVlsu5N1pEfawBSSuZkJRla2gQLSONYFS0eDbn4ChnVQfVmLnqmI_gtJRtDbeXgqVkhyoelr1VGIaTgicEQbNc0eDqnn2CSQjMPbgpucVRHQs_JeivDM5OmV1QFQWx7Wb2vXjvLVkg2EmSOKTr36Cw3Wsw76skrrhiXVtKYOGo5uj9l0wTSvOhQ1IDH9V7115_ltdRMc1aDZdZrGR7NuyIK-fZz4uytnxBXv4Xr-rUncAbI0TpJKH54mRL5jZo1nkjY4v_eEIqb1TtoVqPrpJftxB71zj5Mmo0XxMKsoV3fTI1zURkQ_YRWAxrayPt9MZjJmIcTfvENukU1Gle7sfK878cWUgvtdpgFYGl3N4i1esA04bdP2kFR6vyDcfLh6TsUeN1aozR7TAl1gQ-IoQQ7ZlMTFDwLtLzv5pAvzoVJ5gkday26bTc4cXB51wa13ZKKOCjMI-AdiGOBjmAUlBGcMEaWxOSMf7q_Y9Aa9zUu01KtYiDVxVYin0XyNyL-D8g55m_XsybdR4pOvtzzfBRQKKMHsEjGHCfPg0eDk6FPWt6dHrt85KdJhm9O5BFMqnkv9lx_vigGUfXBti8PrNFV1aMgfkKUgc-vGNnlypokNmniNkC&isca=1).

### Unit Test Errors
Errors are the result of the `karma_web_test_suite` targets
```
Extracting ../org_mozilla_geckodriver/file/geckodriver-v0.24.0-linux64.tar.gz failed (Exit 2) linux-sandbox failed: error executing command

...
```
The full log can be found [here](https://00e9e64baca4ffb9046c9fa8fdb56756751b269b993167824f-apidata.googleusercontent.com/download/storage/v1/b/535395706340.cloudbuild-logs.googleusercontent.com/o/log-3670445e-dbd8-46a1-a6f1-511565eeed4a.txt?qk=AD5uMEvF5Kd6s5RHlYZsyBaJEeFhxB-thgcs3HY-JrawfCwANRJ2Z3yxHbSlzK0U6HfL4OIyh1kjrLVkhK9eGs0Lo6NWGwr82rVc7_zRJ3Cq3t4f7Ga8KkWSg1jplMnV11UH0kBHLl2S3p4ic6aYTMx62S1Ej6J5_KWL5pSd8nCipHaRoxCS1MO1J93eD-P2Yc88OWpSRpXl24e1Pwbv5_3w8pRhrsTEK5D-Q89oWppxO0ZOc-NdX4gXyxZ6J_aGR00FdZUxcFFA4AjJ_8WbEQ6MSEtDMS4fCruw9t9fGnfR_oM5D25y9IHSjkBW2B_6cJzlrq-nu58e5XD_EGHNiRzIE4zly_blHc_gAcpYhotCanDW2Ke3Yi5YFd5IGwTDty-wKl37jGlmIRY6oyc6KNX3J5HccRAPuDRgT1X1Zt5sObc_lSrL5BckECwTt7pZbG-xqzGMFQeqowOh4hF2kqczRxhGzhp09OpeTHmxP2ez6CAUJUn_0IFzUhfNSApa7PpPVLhXIbpEEvxpnxqSdY7NILzDMUgGdSeZ155_ePvHPDVwmsBfxeTJWoT13wO0y8Ajd1q2N_K2Fz6PYODBp5EkHBHcuyJziPO8FF-68cvcvM9FXyHJaQ4Hj_Pq0Ro1wE0aI4sTzAFLUwYYrQYK_lCSOsv7zsANXHcfcSgMP_5gw-JsmEYHnxt7DN8KORyr4pw_ACOhJIJDnARhoqoTzOd34Y8R6rDjorE5aG4eOC8iV0EOU7bzZ1O9JAf1TMGaXdDD6eR5dBn-5XjMzkByLt4QKYmP0IT7JHA6Bud02TAKnbMNlkk0jp16yMEEHyNdH7UYpoSlBQKj-SzeFmcm3iKbXXGwPJtTjpYWdZMn2h0rBeZayq_IH-whOE2HszE8s9F7z_hvP2-u&isca=1).

## Anything else relevant?
I have already discussed those problems briefly with @rayman1104 and the issues are probably caused because [those](https://github.com/bazelbuild/rules_nodejs/blob/1a83a7f139e2e54eb55af3f00b640fc9b505ab7d/.circleci/config.yml#L31) packages are missing in the `gcr.io/cloud-builders/bazel` image.

**But I honestly don't know how to install them in the Cloud Build Pipeline.**

**Comment by flolu** [comment]
I've tried to install  [those](https://github.com/bazelbuild/rules_nodejs/blob/1a83a7f139e2e54eb55af3f00b640fc9b505ab7d/.circleci/config.yml#L31) mentioned packages before running the tests like this:
```
steps:
  - id: 'unit tests'
    entrypoint: 'bash'
    name: gcr.io/cloud-builders/bazel
    args:
      - '-c'
      - |
        apt-get update \
        && apt-get -y install libgtk-3-0 libasound2 libnss3 libxss1 \
        && apt-get -y install libdbus-glib-1-2 \
        && bazel test //...
timeout: 1000s
options:
  machineType: 'N1_HIGHCPU_8'
```
But the errors are still there.

**Comment by alexeagle** [comment]
Yeah it's tricky to configure a machine such that headless chrome runs on it, since even headless chrome is dynamic-linked against the x11 libs.
I think it's probably out of our scope in rules_nodejs though, other than to say you need a remote worker that can run chromium headless

**Comment by flolu** [comment]
@alexeagle Ok that doesn't sound good :(
Do you know a Docker image that has headless chrome properly configured? Maybe I can use it as a base image and extend it with Bazel?

**Comment by alexeagle** [comment]
Nope, sorry, but I imagine it's easy to test with any docker image by trying to run chromium. Maybe @gregmagolan knows. If you do find a recipe for it we could add to the docs here to make it easier to find.

I had an issue open against chromium for this but I can't access it anymore outside google I think.

By the way do you really need to detect defects in your app that appear only in real browsers? Seems like the testing frameworks are moving towards recommending just a dom-in-node solution like domino, which I've used for all recent webapp testing in this repo.

**Comment by flolu** [comment]
@alexeagle I would really appreciate if I could prevent to use Headless Chrome. I wanted to use it because of the Angular example application: https://github.com/bazelbuild/rules_nodejs/tree/master/examples/angular

Is there anywhere an example on how to test an Angular + Bazel with an "dom-in-node solution"?

**Comment by Toxicable** [comment]
We run our unit tests all in jasmine - no karma.

This is the docker container we use
```
FROM ubuntu:18.04

# Pupeteer/Chrome deps
RUN apt-get update \
&& apt-get install -yq  --no-install-recommends gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 \
libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 \
libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 \
libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 \
libnss3 lsb-release xdg-utils wget

# Bazel deps
RUN apt-get update && apt-get -y install pkg-config zip g++ zlib1g-dev unzip python3 git

#Yarn and Nodejs
RUN apt-get update && apt-get install -y curl apt-transport-https \
&& curl -sL https://deb.nodesource.com/setup_12.x | bash - \
&& apt-get install -y nodejs \
&& curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
&& echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
&& apt-get update && apt-get install -y yarn
```
And this is our settup code for running Angular unit tests in jasmine
```
/* eslint-disable */
// Derived from https://github.com/gregmagolan/angular/blob/9bcebacaf5c695c15c9cb2b2baa51af534f98f8c/tools/testing/init_node_spec.ts

import 'zone.js/dist/zone.js';
import 'zone.js/lib/zone-spec/long-stack-trace';
import 'zone.js/lib/zone-spec/task-tracking';
import 'zone.js/lib/zone-spec/proxy';
import 'zone.js/lib/zone-spec/sync-test';
import 'zone.js/lib/zone-spec/async-test';
import 'zone.js/lib/zone-spec/fake-async-test';
import 'reflect-metadata/Reflect';

// Initialize jasmine with @bazel/jasmine boot() function. This will initialize
// global.jasmine so that it can be patched by zone.js jasmine-patch.js.
require('@bazel/jasmine').boot();

import 'zone.js/lib/jasmine/jasmine';

(global as any).isNode = true;
(global as any).isBrowser = false;

import '@angular/compiler'; // For JIT mode. Must be in front of any other @angular/* imports.
// Init TestBed
import { TestBed } from '@angular/core/testing';
import { ServerTestingModule, platformServerTesting } from '@angular/platform-server/testing';

TestBed.initTestEnvironment(ServerTestingModule, platformServerTesting());
```

**Comment by flolu** [comment]
Sounds great! So I would build the Docker image and use it for the Cloud Build step?
```
steps:
  - id: "unit tests"
    name: gcr.io/path-to-my/jasmine-iamge
    args: ["test",  "//src/..."]
```

@Toxicable But how does the Bazel rule look like (I am referring to [this](https://github.com/bazelbuild/rules_nodejs/blob/master/examples/angular/src/app/hello-world/BUILD.bazel) module)? I mean where do I specify the setup code (the `init_node_spec.ts`)? Because without I get `Error: In this configuration Angular requires Zone.js`
```
ts_library(
    name = "test_lib",
    testonly = 1,
    srcs = glob(["*.spec.ts"]),
    tsconfig = "//src:tsconfig-test",
    deps = [
        ":hello-world",
        "//src/shared/material",
        "@npm//@angular/core",
        "@npm//@angular/platform-browser",
        "@npm//@types/jasmine",
    ],
)

jasmine_node_test(
    name = "test",
    deps = [
        ":test_lib",
    ],
)
```

**Comment by Toxicable** [comment]
You'll need to require it it before the application starts running tests
```
ts_library(
    name = "angular_test_setup",
    testonly = True,
    srcs = [":angular-test-setup.ts"],
    deps = [
        "@npm//@angular/compiler",
        "@npm//@angular/core",
        "@npm//@angular/platform-server",
        "@npm//reflect-metadata",
        "@npm//zone.js",
    ],
)

filegroup(
    name = "angular_test_setup_es5",
    testonly = True,
    srcs = [":angular_test_setup"],
    output_group = "es5_sources",
)

    jasmine_node_test(
        name = "test",
        srcs = [":test_lib"],
        data = [],
        deps = [
            ":angular_test_setup_es5",
            ":angular_test_setup",
        ],
        tags = tags,
        templated_args = ["--node_options=--require=$(rlocation $(location path/to:angular_test_setup_es5))"],
    )
```

**Comment by flolu** [comment]
@Toxicable  I get the following errors when running the test
```
ReferenceError: document is not defined
...
TypeError: Cannot set property 'name' of undefined
...
TypeError: Cannot read property 'detectChanges' of undefined
```
Full error log [here](https://gist.github.com/flolu/e918ca921ace1494e454dc6a03afac35).

## Setup
* [src/BUILD.bazel](https://github.com/bazelbuild/rules_nodejs/blob/master/examples/angular/BUILD.bazel)
  ```
  ts_library(
      name = "angular_test_setup",
      testonly = True,
      srcs = [":angular-test.setup.ts"],
      deps = [
          "@npm//@angular/compiler",
          "@npm//@angular/core",
          "@npm//@angular/platform-server",
          "@npm//@types/node",
          "@npm//reflect-metadata",
          "@npm//zone.js",
      ],
  )

  filegroup(
      name = "angular_test_setup_es5",
      testonly = True,
      srcs = [":angular_test_setup"],
      output_group = "es5_sources",
  )
  ```

* [src/app/hello-world/BUILD.bazel](https://github.com/bazelbuild/rules_nodejs/blob/master/examples/angular/src/app/hello-world/BUILD.bazel)
   ```
  jasmine_node_test(
      name = "jtest",
      srcs = [":test_lib"],
      data = [],
      templated_args = ["--node_options=--require=$(rlocation $(location //src:angular_test_setup_es5))"],
      deps = [
          "//src:angular_test_setup",
          "//src:angular_test_setup_es5",
      ],
  )
  ```
