### ISSUE TITLE
ts_project does not pick up referenced project's parent tsconfig

### ISSUE THREAD

**Issue by kwonoj** [bazelbuild/rules_nodejs#1754]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: `ts_project`

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

let's assume project layout like below

```
- tsconfig.json
\ src
   - tsconfig.esm.json
   \ common
     - BUILD
 	 - tsconfig.json  
     - tsconfig.bzl.json 
   \ preload
     - BUILD
     - tsconfig,json
     - tsconfig.bzl.json
```

`tsconfig.json` under each package extends `\\:tsconfig.json`, `\\src:tsconfig.esm.json`. `tsconfig.bzl.json` is the actual config being used in ts_project, extends each `:tsconfig.json`.

when `\\src\preload:tsconfig.bzl` have reference to `\\src:common`, ts_project `deps` will pick up direct reference, `\\src\common:tsconfig.bzl.json` and does not pick up its extend `\\src\common:tsconfig.json`, in result compilation error occurs by missing some of config flags specified in parent config only.

## 🔬 Minimal Reproduction

- clone https://github.com/kwonoj/ts_project_composite_test, `npm test` on Linux / darwin (sandbox)
- ci output https://github.com/kwonoj/ts_project_composite_test/pull/1/checks?check_run_id=542899759

## 🔥 Exception or Error

<pre><code>

##[error]src/preload/tsconfig.bzl.json(4,5): error TS6306: Referenced project '/home/runner/.cache/bazel/_bazel_runner/effb5996f4ecc130424f20eff3118d8b/sandbox/linux-sandbox/4/execroot/test/src/common/tsconfig.bzl.json' must have setting "composite": true.
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>

  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>

  </code>
</pre>

**Anything else relevant?**

**Comment by kwonoj** [comment]
I think this is more for the question `how to configure ts_project to pick up all configs correctly` rather than bug report.

**Comment by alexeagle** [comment]
1) (not directly related) it's too bad you need a `tsconfig.bzl.json` next to each `tsconfig.json`. I see this is for the outDir workaround to make non-sandboxed execution work. Do you really need `.tmp/out` to be the default (non-bazel) outDir? If you just choose the same outDir all the time then maybe you can eliminate the need for `tsconfig.bzl.json` which will simplify the config and less likely to have it misconfigured

2) To diagnose the problem let's see what are the inputs to `src/preload:tsconfig.bzl` target

`bazel aquery src/preload:tsconfig.bzl`

Okay that has a lot of output, let's just find the *.json inputs

```
$ bazel aquery src/preload:tsconfig.bzl | grep Inputs | tr ',' '\n' | grep .json | grep -v node_modules
 bazel-out/darwin-fastbuild/bin/src/preload/_tsconfig.bzl.module_mappings.json
 src/common/tsconfig.bzl.json
 src/preload/tsconfig.bzl.json
 src/preload/tsconfig.json
 src/tsconfig.esm.json
 tsconfig.json
```

This is missing `src/common/tsconfig.json` which is needed here to fully resolve the configuration of the `src/common` dependency so I think this actually is a bug.

**Comment by alexeagle** [comment]
Yup, trivial fix to include the extended tsconfigs in the set we pass down to dependencies in the _TsConfigInfo provider: https://github.com/kwonoj/ts_project_composite_test/pull/2

Will fix in rules_nodejs for next patch release.

**Comment by kwonoj** [comment]
> Do you really need .tmp/out to be the default (non-bazel) outDir? If you just choose the same outDir all the time then maybe you can eliminate the need for tsconfig.bzl.json which will simplify the config and less likely to have it misconfigured

though in actual repo it have same outdir layout, this repo's tsconfig is simplified omits some of differences between 2 configs. 

> This is missing src/common/tsconfig.json which is needed here to fully resolve the configuration of the src/common dependency so I think this actually is a bug.

yes, that's how I could make this repro, I think I should've include aquery output in issue. 

Thanks for help.
