### ISSUE TITLE
perf_trace memory usage grows unbounded.

### ISSUE THREAD

**Issue by DavidANeil** [bazelbuild/rules_nodejs#1768]
# 🐞 bug report

### Affected Rule
The issue is caused by the rule:
`ts_library`

### Is this a regression?
No

### Description

In rules_typescript: `tsc_wrapped/perf_trace.ts` contains an array `events` that grows unbounded even when performance tracing is disabled.  After ~100 builds on the same worker the caches will begin to evict themselves more and more often, and around ~300 builds the array will be several gigabytes in size and will eventually crash the worker.

### Proposed Solution

Provide a no-op instance of the perf_trace functionality that is substituted when there is no performance output file.

And, for times when performance tracing is desired, also cap the array at ~100000 events.

## 🌍  Your Environment
**Rules_nodejs version:**
```1.1.0```

**Comment by evmar** [comment]
Nice find!  I agree that this should be a no-op when we don't want the logs.  Send a patch?

**Comment by DavidANeil** [comment]
Oops, missed the first ping on this one.  Probably don't want this closed.
