### ISSUE TITLE
Semantic typechecking happens twice in tsc_wrapped

### ISSUE THREAD

**Issue by nickhs** [bazelbuild/rules_nodejs#1769]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: ts_library w/ stateful compiler

### Is this a regression?

Unknown

### Description

`tsc_wrapped.ts` performs semantic type checking of every source file in the package twice:

1. When calling [gatherDiagnostics](https://github.com/bazelbuild/rules_typescript/blob/master/internal/tsc_wrapped/tsc_wrapped.ts#L87)

2. When later calling [emitWithTypescript](https://github.com/bazelbuild/rules_typescript/blob/master/internal/tsc_wrapped/tsc_wrapped.ts#L474)

I was under the impression (2) would hit Typescript's `cachedBindAndCheckDiagnosticsForFile` but apparently Typescript doesn't go down that code path on `emit`? Am I missing another cache somewhere?

## 🔬 Minimal Reproduction

Attach a debugger to a running stateful worker. Create a breakpoint in Typescript's `checkSourceFile` function.

Observe the function being called twice for each individual source file in the package.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
MacOS
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
2.0.0
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
1.4.1
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
I also understood the type-check during emit to be cached. If we're paying for type-check twice, that's really interesting and is probably a de-opt in google internal usage as well.
/cc @alxhub and @evmar (do you want this issue on rules_typescript instead?)

**Comment by evmar** [comment]
I believe the second pass just reuses info gathered from the first.  Search for 'lazily' on https://github.com/microsoft/TypeScript/wiki/Architectural-Overview .

This is at least consistent with the behavior I see in profiles, which is that the gather diagnostics pass is very costly and the emit pass is relatively cheap.

**Comment by nickhs** [comment]
That makes sense. I can see all the calls going through `getDiagnosticsProducingTypeChecker` which refers to a (lazily initialized) shared checker instance.

Going through the checker itself is a bit of a monster, but I'll close this for now and re-open if I can find some empirical proof that there's duplicated type checking. 

As an aside I'm not entirely sure what `cachedBindAndCheckDiagnosticsForFile` from program.ts is buying, but that's a question better suited for the actual Typescript folks.
