### ISSUE TITLE
`jasmine_node_test` should auto restart the JasmineRunner on file change when in debug

### ISSUE THREAD

**Issue by Toxicable** [bazelbuild/rules_nodejs#177]
Currently to debug `jasmine_node_test` you must manually restart the process since running `bazel test :target --config=debug` will only do a single run on the jasmine runner.
It should re-run jasmine and hold the process open when in `config=debug`

for ref: https://github.com/bazelbuild/rules_nodejs/blob/master/internal/jasmine_node_test/jasmine_runner.js#L27

**Comment by alexeagle** [comment]
I'm leaning to close this as WAI - I don't think we necessarily need to support the intersection of watch mode and debug mode at the same time. I could see how it's useful, but it also adds complexity and will be hard for us to add tests that we don't break it.

**Comment by Toxicable** [comment]
If neither this is done nor a Jest target is made, then i don't see how were meant to run Nodejs tests with bazel.
Have you tried using this target yourself? It is very tedious and time consuming.
If you want to attach a debugger then you have to manually kill the process and restart the test after each run.
If you want to use ibazel to restart it then you're reduced to using console.log for debugging.

**Comment by alexeagle** [comment]
@filipesilva is looking into this as part of improving round-trip time for running jasmine tests under ibazel

**Comment by joeljeske** [comment]
This would be very helpful! 

I agree with @Toxicable that maintaining the same NodeJS process is critical for properly debugging node tests.

**Comment by joeljeske** [comment]
I ended up implementing this behavior by overriding the jasmine runner. In iBazel it uses worker threads to run the tests. In normal mode, it launches the jasmine runner the standard way. 

I was concerned with an approach that relies on clearing the require cache and reloading the modules. That assumes that the global scope is left clear during prior runs and no other side effects have been performed. This seemed like a better way to encapsulate the tests runs. And any performance hit would occur only in iBazel mode.
