### ISSUE TITLE
document convenient way to lay out all files in bazel-out

### ISSUE THREAD

**Issue by mrmeku** [bazelbuild/rules_nodejs#1771]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: ts_project

### Is this a regression?
No

### Description
Consider what happens when you try to bundle a `index.js` emited by `ts_project`.

index.js is placed in `execroot/workspace/bazel-out/k8-fastbuild/bin/index.js` and tries to do a relative import of a non-generated file  something like `./styles.css` (other common scenarios would be a local .js, or .json file)

`styles.css` is placed in  `execroot/workspace/styles.css`

So the relative import fails since the bundler doesn't know how to resolve things living `bazel-out` vs not in `bazel-out`

In order to fix this sort of thing we'll either need to layout the directory structure differently or provide some documentation on ways to configure bundlers to resolve these imports.

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
https://github.com/bazelbuild/rules_nodejs/pull/1770

## 🔥 Exception or Error

<pre><code>
ERROR in ./bazel-out/k8-fastbuild/bin/index.js
Module not found: Error: Can't resolve './styles.css' in '.../execroot/react_webpack/bazel-out/k8-fastbuild/bin'
 @ ./bazel-out/k8-fastbuild/bin/index.js 5:13-36
</code></pre>

## 🌍  Your Environment
**Output of `bazel version`:**

<pre>
  <code>
Build label: 2.2.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Mar 3 09:26:12 2020 (1583227572)
Build timestamp: 1583227572
Build timestamp as int: 1583227572
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "d0c4bb8b902c1658f42eb5563809c70a06e46015d64057d25560b0eb4bdc9007",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/1.5.0/rules_nodejs-1.5.0.tar.gz"],
)
  </code>
</pre>

**Comment by alexeagle** [comment]
js_library has a built-in copy_to_bin action on InputArtifacts so you get relative imports together again. That's how @gregmagolan solved this in the linker PR.

**Comment by alexeagle** [comment]
certainly not a `ts_project` bug, it's doing the right thing with its inputs and outputs.
The question is how the user should express that they want other sources of the bundler to be copied to the output tree. You could manually add `copy_to_bin` rules for it, but maybe we should make the `js_library` rule part of the public API, as it now does this https://github.com/bazelbuild/rules_nodejs/blob/1.5.0/internal/js_library/js_library.bzl#L57-L63

**Comment by alexeagle** [comment]
I'm doing some work right now with cra/react-scripts and copy_to_bin works pretty well, just use it as a drop-in replacement for `filegroup` and you get a self-contained output directory

**Comment by alexeagle** [comment]
We should add a bit of docs somewhere for 2.0 to explain the current situation.
IF js_library becomes public API then it changes what we tell you to do...

**Comment by alexeagle** [comment]
js_library not going public in time for 2.0, so I think this should slip too.

**Comment by alexeagle** [comment]
Documenting this now in the js_library rule
