### ISSUE TITLE
Add prerendering with angular to examples

### ISSUE THREAD

**Issue by flolu** [bazelbuild/rules_nodejs#1775]
# 🚀 feature request

### Description

Add an angular module to the [example angular app](https://github.com/bazelbuild/rules_nodejs/tree/master/examples/angular) which supports [prerendering](https://dev.to/michaeljota/how-to-prerender-your-angular-app-using-angular-universal-4g0b).

**Comment by alexeagle** [comment]
That sounds cool, it looks like this is specifically build-time rendering (run angular as a nodejs program in a build step to produce a populated index.html file that goes into the app resources) as opposed to having any server at runtime doing it?

**Comment by flolu** [comment]
@alexeagle Exactly! This is super useful for static pages like "About", "Terms" or even the Home page.

I created the issue because the implementation currently exceeds my own knowledge, otherwise I would have done a pull request. :laughing:

**Comment by mattem** [comment]
I had an [example repo](https://github.com/Evertz/bazel-angular-prerender) for this some months ago. Things have probably changed since then, but should be able to bring it back up to date. I can take this one.

**Comment by flolu** [comment]
@mattem Awesome! I'll check it out later. Thank you :)

**Comment by mattem** [comment]
@flolu Added the prerendering example to examples/angular, let me know how you get on

closed by 8509d9c

**Comment by flolu** [comment]
@mattem Awesome! Thank you so much!
