### ISSUE TITLE
How to use this in a subfolder frontent vue project 

### ISSUE THREAD

**Issue by weixiao-huang** [bazelbuild/rules_nodejs#1776]
# 🚀 feature request

I have a bazel monorepo project which contains both frontend and backend codes. The project structure is shown as below:

```
.
├── BUILD.bazel
├── WORKSPACE
├── backend
└── frontend
    ├── BUILD.bazel
    ├── packages.json
    ├── public
    ├── src
    ├── vue.config.js
    └── yarn.lock
```

And the frontend project has been initialized by [vue-cli](https://cli.vuejs.org/). I want to use codes below to exec `vue-cli-service build --dest=dist`

```
load("@npm//@vue/cli-service:index.bzl", "vue_cli_service")

filegroup(
    name = "frontend-srcs",
    srcs = [
        "vue.config.js",
    ] + glob(
        [
            "src/**",
            "public/**",
        ],
        exclude = [],
    ),
)

filegroup(
    name = "package_json",
    srcs = [
        "package.json",
        "yarn.lock",
    ],
)

vue_cli_service(
    name = "build",
    args = [
       "build",
       "--dest=$(@D)",
    ],
    data = [
       ":portal-srcs",
       ":package_json",
       "@npm//:node_modules",
    ],
    outs = ["dist"],
)
```

However, since bazel will include data as the project structure shown below

```
.
├── external
└── frontend
    ├── packages.json
    ├── public
    ├── src
    ├── vue.config.js
    └── yarn.lock
```

But vue-cli-service want the project structure as below:

```
.

├── packages.json
├── public
├── src
├── vue.config.js
└── yarn.lock
```

However, by using `vue_cli_service` generated by rules_nodejs, I cannot [set environment](https://github.com/vuejs/vue-cli/issues/3152#issuecomment-448892609) or `cd` into the `frontend` dir. So the `vue_cli_service` cannot work.
So how to use rules_nodejs in a subfolder frontent vue project?

**Comment by alexeagle** [comment]
That issue you linked to explains it pretty well. Bazel runs subcommands with a working directory in the root of the repo, but the vue tooling cannot be called with command-line arguments that tell it where to run.

I think you could pass an argument to the `vue_cli_service` like

```
vue_cli_service(
    args = ["--node_options=--require=path/to/some/script.js"]
)
```
where that script simply does the `process.chdir()`.
https://github.com/bazelbuild/rules_nodejs/blob/master/docs/Built-ins.md#templated_args describes it a bit.

That's a pretty sad complex workaround. The right fix is for vue to allow running from a different directory.

**Comment by weixiao-huang** [comment]
It seems not work while adding `chdir.js` into `frontend` dir
```
.
├── BUILD.bazel
├── WORKSPACE
├── backend
└── frontend
    ├── BUILD.bazel
    ├── chdir.js
    ├── packages.json
    ├── public
    ├── src
    ├── vue.config.js
    └── yarn.lock
```
and I add `templated_args = ["--node_options=--require=$(rootpath chdir.js)"]` into `vue_cli_service`

```

vue_cli_service(
    name = "build",
    args = [
       "build",
    ],
    templated_args = ["--node_options=--require=$(rootpath chdir.js)"]
    data = [
       ":portal-srcs",
       ":package_json",
       "@npm//:node_modules",
       "chdir.js",
    ],
)
```
I got error like:

```
ERROR: infinite symlink expansion detected
[start of symlink chain]
/Users/xxx/go/src/go.test/my_project/frontend/node_modules/test_go_my_project/node_modules
/private/var/tmp/_bazel_xxx/039a5720a8b308d23743083ac3c82659/execroot/test_go_my_project/bazel-out/darwin-fastbuild/bin/frontend/vue-build.sh.runfiles/test_go_my_project/node_modules
/private/var/tmp/_bazel_xxx/039a5720a8b308d23743083ac3c82659/external/npm/node_modules
/Users/xxx/go/src/go.test/my_project/frontend/node_modules
[end of symlink chain]
ERROR: Infinite symlink expansion
INFO: Elapsed time: 8.552s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
```

**Comment by weixiao-huang** [comment]
I try to add `templated_args = ["--node_options=--require=$$(realpath $(rootpath chdir.js))"],` into `vue_cli_service` and it actually can work if I remove `outs` and `"--dest=$(@D)",` in vue_cli_service. However, it seems templated_args not support npm_package_bin since `vue_cli_service` will output `dist` and I want to use this folder as srcs into a `pkg_tar` method in bazel.

**Comment by dubov94** [comment]
@weixiao-huang I believe `process.chdir(__dirname)` will just set the current directory to `workspace/frontend`, which is probably suboptimal as Bazel's sandboxing directory is in a different location.

In any case, I thought you might like https://npmjs.com/package/vue-cli-launcher :)

**Comment by alexeagle** [comment]
https://github.com/bazelbuild/rules_nodejs/issues/1840#issuecomment-619277667 is a pretty good answer (if you generate the chdir.js script then __dirname is the right place, conveniently)

**Comment by weixiao-huang** [comment]
I try this method in https://github.com/bazelbuild/rules_nodejs/issues/1840#issuecomment-619277667 but it hangs so much time that I don't know why. Now I use this method to resolve my problem:

```bash
genrule(
    name = "build",
    outs = ["dist"],
    srcs = ["@npm//:node_modules"] + glob(
        ["**"],
        exclude = ["node_modules/**"],
    ),
    # TODO: external/npm/node_modules is a hardcode path for @npm//:node_modules, should get package path of @npm
    cmd = """
        export PATH=$$PWD/$$(dirname $(location @nodejs//:node_bin)):$$PATH
        vue_cli_service=$$PWD/$(location @npm//:node_modules/.bin/vue-cli-service) outs=$$PWD/$@
        cd frontend && ln -s ../external/npm/node_modules ./ && $$vue_cli_service build --dest $$outs
    """,
    tools = [
        "@npm//:node_modules/.bin/vue-cli-service",
        "@nodejs//:node_bin",
    ],
)
```

**Comment by leonwind** [comment]
Hey,
I am currently facing this exact issue as well of having a large monorepository including a vue.js app, which we want to build using Bazel. 
The workaround of @alexeagle to use a `chdir.js` script to change directories is also timing out for me.
Is there a new proper way today on how to solve this issue?
I have also tried the `vue_cli_launcher` rule by @dubov94 but I am getting the same error as if I would use the normal `vue_cli_service` rule by the nodejs rules.

Thanks in advance :)

**Comment by leonwind** [comment]
Since this is still the first thread popping up on Google if one searches for building vue.js from a parent directory in bazel, I want to post the solution here as well:

A proper solution is using the `chdir = package_name()` parameter for the `vue_cli_servie` rule as mentioned in a response to [#3104](https://github.com/bazelbuild/rules_nodejs/issues/3104#issuecomment-984736043).
