### ISSUE TITLE
deprecate @bazel/bazel

### ISSUE THREAD

**Issue by Toxicable** [bazelbuild/rules_nodejs#1784]
Now that @bazel/bazelisk has a `bazel` binary entry point https://github.com/bazelbuild/bazelisk/commit/8c5609acaf93d833b9bb7d79e4163198624c17a5, we should deprecate `@bazel/bazel`

**Comment by alexeagle** [comment]
Yes as soon as there is a release of bazelisk with that update, I agree.

**Comment by alexeagle** [comment]
It's time!

**Comment by alexeagle** [comment]
Also @josephperrott points out that we might want to 
> update the @bazel/bazel binary script that wraps bazel's actual binary to instruct migration to @bazel/bazelisk
in case they don't see the deprecation message

**Comment by josephperrott** [comment]
Happy to mark the package as deprecated on npm

Before I do so, we need to land on the exact wording for the deprecation message, along with if a deprecation message should be added in the wrapper as well.

**Comment by alexeagle** [comment]
I don't think anyone has time to add a deprecation message to the legacy wrapper and release a new 2.x release of `@bazel/bazel` so @josephperrott I suggest just deprecate with "Use @bazel/bazelisk instead"

**Comment by mattem** [comment]
The Angular schematics etc are using `@bazel/bazel`, those would need updating too (see the linked issue) - this was mentioned on the Bazel Slack.

**Comment by alexeagle** [comment]
Ping @josephperrott https://www.npmjs.com/package/@bazel/bazel still doesn't show as deprecated

**Comment by josephperrott** [comment]
Marked as deprecated.

```
$ npm info @bazel/bazel

@bazel/bazel@2.1.0 | Apache-2.0 | deps: 4 | versions: 44
Build and test software of any size, quickly and reliably
https://bazel.build/

DEPRECATED ⚠️  - @bazel/bazel is deprecated, please use @bazel/bazelisk instead

bin: bazel

dist
.tarball: https://registry.npmjs.org/@bazel/bazel/-/bazel-2.1.0.tgz
.shasum: 25a4d3b4171bfb637374133d29878bbcb36b4c92
.integrity: sha512-3Dhs0uJ69ImqC+VIRcifnptPXytxCNWHqyTMFYf0F5AJCVHHW7uRE0tt3Vhm5BseFpdOsjqcghgxGzR/yo10qw==
.unpackedSize: 13.7 kB

dependencies:
@bazel/bazel-darwin_x64: 2.1.0  @bazel/bazel-win32_x64: 2.1.0
@bazel/bazel-linux_x64: 2.1.0   @bazel/hide-bazel-files: latest

maintainers:
- achew22 <npmjs.com@achew22.com>
- angular <devops+npm@angular.io>
- angularcore <angular-core+npm@google.com>
- google-wombot <node-team-npm+wombot@google.com>
- gregmagolan <gmagolan@gmail.com>

dist-tags:
latest: 2.1.0    next: 2.0.0-rc3

published 3 months ago by angular <devops+npm@angular.io>
```

**Comment by alexeagle** [comment]
Thanks Joey!
