### ISSUE TITLE
Regression in 1.5.0 generated rules

### ISSUE THREAD

**Issue by purkhusid** [bazelbuild/rules_nodejs#1787]
# 🐞 bug report

### Affected Rule
The issue is related to the auto generated rules for `node_modules/.bin`

### Is this a regression?
Yes, this works in 1.4.1

### Description
I'm using the auto genrated rules to run GraphQL Code Generator(https://graphql-code-generator.com)

It works fine in version 1.4.1 but in 1.5.0 in fails. 
I've created a minimal reproduction of the issue here: https://github.com/purkhusid/glql-gen-repro

## 🔥 Exception or Error

<pre><code>
Cannot use GraphQLEnumType "__TypeKind" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
[21:03:30] Generate types.ts [failed]
[21:03:30] → Cannot use GraphQLEnumType "__TypeKind" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
MacOS 1.14
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 2.2.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Mar 3 09:28:15 2020 (1583227695)
Build timestamp: 1583227695
Build timestamp as int: 1583227695
  </code>
</pre>

**Rules_nodejs version:**
<pre>
  <code>
    1.5.0
  </code>
</pre>

**Comment by alexeagle** [comment]
Thanks for the small repro.

Regression must be in these commits: https://github.com/bazelbuild/rules_nodejs/compare/1.4.1...1.5.0
I confirmed it's still present at HEAD.
I tried a diff of `bazel aquery :gen` in both the working and broken state, thinking that maybe the action is being passed different inputs, but the diff was only the action key SHA

Still looking for the cause.

**Comment by alexeagle** [comment]
I bisected it manually, it's caused by https://github.com/bazelbuild/rules_nodejs/commit/a6e29c2add19dd487035b0951f5271053a0a11e2
