### ISSUE TITLE
Expose runfile helpers as separate package

### ISSUE THREAD

**Issue by devversion** [bazelbuild/rules_nodejs#1793]
It would be valuable if consumers can import the runfile helpers through a separate package. Currently it's not convenient to use an "unknown" environment variable to load the runfile helpers.

Additionally, there is no TypeScript definition for these helpers. Ideally these should be provided too.

A good package name could be `@bazel/runfiles` which either directly loads the runfile helpers, or handles the environment variable loading internally.

**Comment by Toxicable** [comment]
Looks like this one would fix it https://github.com/bazelbuild/rules_nodejs/pull/1542

**Comment by alexeagle** [comment]
Yeah we should revisit #1542 - it was strange that it wasn't actually a package published to npm, but Greg has been refactoring linker lately so I think it might be different now.
