### ISSUE TITLE
Memory leak of ts_library

### ISSUE THREAD

**Issue by ouchuji** [bazelbuild/rules_nodejs#1803]
# 🐞 bug report

### Affected Rule

 ts_library

### Is this a regression?

 No.

### Description

 Build lot of `ts_library` target via command such as `bazel build src/...` would cause a memory leak problem.
    
The bazel would create a lot of node processes to compile the ts.
![wrong](https://user-images.githubusercontent.com/11475541/78753996-51618180-79a9-11ea-9a13-b8f2e261baf0.png)
Then the computor memory is all ate by these node processes.
![wrong_memory](https://user-images.githubusercontent.com/11475541/78754360-ebc1c500-79a9-11ea-978e-98f999174048.png)
I found that this commit caused this problem.
feat(typescript): use run_node helper to execute tsc 066a52c43052cfb5b32cc2effe52c4d31c133715
And  I change the code like below and the problem is solved, node processes number became normal.
![correct_code](https://user-images.githubusercontent.com/11475541/78755420-b4541800-79ab-11ea-86a6-73422bbd4979.png)
![correct](https://user-images.githubusercontent.com/11475541/78755581-fa10e080-79ab-11ea-9f58-15510fbc7628.png)

And I make deep debuging, found the extra arg `--bazel_node_modules_manifest=%s` to the `tsc_wrapper` caused this probel, and I comment this, the problem is solved too.
![image](https://user-images.githubusercontent.com/11475541/78755969-9a670500-79ac-11ea-9a24-f306efc01472.png)

## 🔬 Minimal Reproduction

It looks great when build a single ts_library target, but not great when build lots of ts targets via `bazel build ...`.

## 🔥 Exception or Error

<pre><code>
No exception, but the computor memory is overflow.
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubutu 18.04 LTS
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
2.1.0
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
1.5.0
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
That's fantastic debugging! Thank you for digging into this and finding the root cause, that should help us find the time to fix it.

**Comment by chrisleck** [comment]
Just guessing here, but it's probably the root cause of recent reports in https://github.com/bazelbuild/rules_nodejs/issues/1027.
