### ISSUE TITLE
Regression in 1.6.0 autogenerated test rules

### ISSUE THREAD

**Issue by purkhusid** [bazelbuild/rules_nodejs#1823]
### Affected Rule

Not so sure if it's only autogenerated rules, but the repro I have is failing in a auto generated test rule.

### Is this a regression?
Yes, this works in 1.5.0.

### Description
Auto generated rules fails to load resolve module from a relative file during a test run.

## 🔬 Minimal Reproduction
https://github.com/purkhusid/ts-jest-repro

## 🔥 Exception or Error

<pre><code>
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //:test
-----------------------------------------------------------------------------
[link_node_modules.js] manifest file /private/var/tmp/_bazel_danielpurkhus/6514ebbf801be819708572b35f1a35af/sandbox/darwin-sandbox/5/execroot/jest_repro/bazel-out/darwin-fastbuild/bin/test.sh.runfiles/jest_repro/_test.module_mappings.json
[link_node_modules.js] manifest contents {
  "workspace": "jest_repro",
  "bin": "bazel-out/darwin-fastbuild/bin",
  "root": "npm/node_modules",
  "modules": {
    "jest_repro": [
      "execroot",
      "bazel-out/darwin-fastbuild/bin"
    ]
  }
}
[link_node_modules.js] startCwd /private/var/tmp/_bazel_danielpurkhus/6514ebbf801be819708572b35f1a35af/sandbox/darwin-sandbox/5/execroot/jest_repro/bazel-out/darwin-fastbuild/bin/test.sh.runfiles/jest_repro
[link_node_modules.js] isExecroot false
[link_node_modules.js] resolved node_modules root npm/node_modules to /private/var/tmp/_bazel_danielpurkhus/6514ebbf801be819708572b35f1a35af/sandbox/darwin-sandbox/5/execroot/jest_repro/bazel-out/darwin-fastbuild/bin/test.sh.runfiles/npm/node_modules
[link_node_modules.js] cwd /private/var/tmp/_bazel_danielpurkhus/6514ebbf801be819708572b35f1a35af/sandbox/darwin-sandbox/5/execroot/jest_repro
[link_node_modules.js] symlink( node_modules -> /private/var/tmp/_bazel_danielpurkhus/6514ebbf801be819708572b35f1a35af/sandbox/darwin-sandbox/5/execroot/jest_repro/bazel-out/darwin-fastbuild/bin/test.sh.runfiles/npm/node_modules )
[link_node_modules.js] mapping hierarchy [{"name":"jest_repro","link":["execroot","bazel-out/darwin-fastbuild/bin"]}]
[link_node_modules.js] symlink( jest_repro -> /private/var/tmp/_bazel_danielpurkhus/6514ebbf801be819708572b35f1a35af/sandbox/darwin-sandbox/5/execroot/jest_repro/bazel-out/darwin-fastbuild/bin/test.sh.runfiles/jest_repro/bazel-out/darwin-fastbuild/bin )
bazel node patches enabled. root: /private/var/tmp/_bazel_danielpurkhus/6514ebbf801be819708572b35f1a35af/sandbox/darwin-sandbox/5/execroot/jest_repro/bazel-out/darwin-fastbuild/bin/test.sh.runfiles symlinks in this directory will not escape
FAIL ./lib.test.js
  ● Test suite failed to run

    Cannot find module 'jest_repro/lib' from 'lib.test.js'

      at Resolver.resolveModule (../../../../../node_modules/jest-resolve/build/index.js:259:17)
      at ../../../lib.test.ts:1:1
      at lib.test.js:3:13
      at Object.<anonymous> (lib.test.js:8:3)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.085s
Ran all test suites within paths "./lib.test.js".
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
MacOS 1.14.6
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 3.0.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Apr 6 12:55:48 2020 (1586177748)
Build timestamp: 1586177748
Build timestamp as int: 1586177748
  </code>
</pre>

**Rules_nodejs version:**
<pre>
  <code>
1.6.0
  </code>
</pre>

**Comment by ouchuji** [comment]
Have a similar problem.
```
Error: Cannot find module 'base/ts/wasm/go/load_test.js'. Please verify that the package.json has a valid "main" entry
    at Function.module.constructor._resolveFilename (base/ts/wasm/go/__load_test_require_patch.js:493:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at node_modules/jasmine/lib/jasmine.js:89:5
    at Array.forEach (<anonymous>)
    at Jasmine.loadSpecs (node_modules/jasmine/lib/jasmine.js:88:18)
    at Jasmine.execute (node_modules/jasmine/lib/jasmine.js:259:8)
    at main (node_modules/@bazel/jasmine/jasmine_runner.js:216:11)
    at Object.<anonymous> (node_modules/@bazel/jasmine/jasmine_runner.js:238:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Object.<anonymous> (base/ts/wasm/go/__load_test_loader.js:32:24)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
================================================================================
Target //base/ts/wasm/go:load_test up-to-date:
  build/bin/base/ts/wasm/go/load_test.sh
INFO: Elapsed time: 1.147s, Critical Path: 0.48s
INFO: 2 processes: 2 linux-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//base/ts/wasm/go:load_test                                              FAILED in 0.2s
  /mnt/data/.cache/bazel/_bazel_chuji/89fa56ba2ed35263d85ebf2f63a85d95/execroot/logi/bazel-out/k8-fastbuild/testlogs/base/ts/wasm/go/load_test/test.log
```
Platform: Unbutu 18.04
rules_nodejs: 1.6
bazel version: 3.0

**Comment by alexeagle** [comment]
Must have been introduced in https://github.com/bazelbuild/rules_nodejs/compare/1.5.0...1.6.0
let's bisect...

for each commit, say `ff0369c`
- git checkout ff0369c
- bazel build :release
then in the repro project change the `urls` for rules_nodejs
`"file:///Users/alx/Projects/rules_nodejs/dist/bin/release.tar.gz"`

note, bazel can't know that the repository rule needs to be re-run so I do a `bazel clean --expunge` between trials

I found the culprit causing the issue was introduced in https://github.com/bazelbuild/rules_nodejs/commit/5c2f6c10860692ca4dcfb99a27afadcb82f6f6b0
/cc @gregmagolan

**Comment by alexeagle** [comment]
Imported your repro so we see the breakage here in our CI
https://github.com/bazelbuild/rules_nodejs/pull/1850

**Comment by purkhusid** [comment]
Thanks for including the bisect steps. I couldn't figure out how to  importted `tar.gz` in my WORKSPACE file . The `file://<url>` is super handy!

**Comment by gregmagolan** [comment]
On my list for this week. Will get a fix into a 1.6.1 release.

**Comment by flolu** [comment]
Thanks for fixing it that quickly!

**Comment by WesleyYue** [comment]
It looks like this regressed again in 2.0.0. I created a new issue. https://github.com/bazelbuild/rules_nodejs/issues/2008
