### ISSUE TITLE
ts_project fails if a label from a different package is passed

### ISSUE THREAD

**Issue by davazp** [bazelbuild/rules_nodejs#1826]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: `ts_project`

### Is this a regression?

 No that I know of.

### Description

When I use `ts_project` with a explicit label passed to the `tsconfig` argument, the loading fails.

## 🔬 Minimal Reproduction

```
ts_project(
    name = "delisp-runtime",
    composite = True,
    source_map = True,
    tsconfig = "//:tsconfig.json",
)
```

## 🔥 Exception or Error

<pre><code>
ERROR: /Users/davazp/Projects/delisp/packages/delisp-runtime/BUILD.bazel:5:1: 
//packages/delisp-runtime:delisp-runtime: label '//:tsconfig.tsbuildinfo' is not in the current package
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS 10.14.6
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
bazel 3.0.0
  </code>
</pre>

**Rules_nodejs version:** 

<pre>
  <code>
1.6.0
  </code>
</pre>

**Anything else relevant?**

I quickly went through the code. The file `internal/ts_project.bzl` contains what it seems to be a good starting point:

```
        buildinfo_out = tsconfig[:-5] + ".tsbuildinfo" if composite or incremental else None,
```

It seems `tsconfig` argument is not treated as a regular label but just a string in some place and it breaks if it starts with `//`.

**Comment by alexeagle** [comment]
Hmm, the design intent here was that the `ts_project` rule always goes in the same directory as the `tsconfig.json` file. TypeScript will determine what files are in the project by reading the tsconfig.json, and paths in that file are relative to its location.
I suppose it could be made to work to have them in different directories, but I also suspect that will cause some sharp edges. Maybe it should just error if they aren't in the same package, enforcing the design intent.
Do you have a reason not to put the `ts_project` in the root next to the `tsconfig.json`?

**Comment by alexeagle** [comment]
I reproduced it in a test case - the real question is where does the `.tsbuildinfo` file go? `tsc` will write it to the root directory, but Bazel requires that outputs be written in the package where the rule lives. It seems like you'd have to manually override where the .tsbuildinfo goes.

Workaround for now is to pass `validate=False` rather than `composite=True` or `incremental=True` to the `ts_project` so it doesn't care about tsc writing a tsbuildinfo file.

**Comment by davazp** [comment]
That makes sense.  I have disabled composite, as it won't provide much value now anyway.

I guess that showing a friendlier error if incremental or composite are true, warning the user that the tsconfig must be in the same package, would be ideal.

But maybe after stripping the package part of the label the error could be less confusing already.

**Comment by davazp** [comment]
> Do you have a reason not to put the `ts_project` in the root next to the `tsconfig.json`?
Not at all, I was translating some `ts_library()` into `ts_project` and I wrongly assumed they would behave similarly.
