### ISSUE TITLE
Support a tarball output for `npm_package_bin` when `output_dir = True`

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/rules_nodejs#1831]
# 🚀 feature request

### Description

I'm working on porting one of our microservices for a backend portal that is written in `vue.js` to Bazel. I need to package the compiled JS into a docker container along with nginx or caddy (or maybe even the standard node http server). 

I am not a JS developer. Vue has a command line tool to build but it has limitations. The generated artifacts are chunked and it includes a hash in the artefact names by default. This means I cannot list the files generated in the outs. My target currently looks like this: 

```
load("@build_bazel_rules_nodejs//:index.bzl", "npm_package_bin")

npm_package_bin(
    name = "app",
    tool = "@npm//@vue/cli-service/bin:vue-cli-service",
    args = [
        "build", "$(location :src/main.js)",
        "--dest", "$(@D)"
    ],
    data = [
        "@npm//:node_modules"
    ] + glob(["src/**"]),
    output_dir = 1
)
```

I need to turn the output into a docker layer and I assume since I cannot declare `outs` that I won't be able to do this. 

We have found a way to be able to disable the chunking which ends up producing one large file for the JS and the CSS and this is not ideal as it gets rid of a runtime optimisation. We have also found a way to disable file hashing but it is not a command line parameter to the `cue-cli-service` but rather a magic file (`vue.config.js`) that needs to be in the root of the project 🤦‍♂️. The rule action is executed at the root of the workspace so it won't pick up this magic file.

### Describe the solution you'd like

What I have tried above and the approach I am taking in general are both workarounds really. I think what we need is for the rule above to support producing a tar for the directory it builds that could be fed to into the docker rule responsible for creating a layer out of a tar. 

### Describe alternatives you've considered

I have tried to write a `genrule` but I get some weird module resolution errors and I suspect this is a dead end.

**Comment by alexeagle** [comment]
Hi @hsyed nice to see you again!

Did you try using a `pkg_tar` on the output dir? I would expect it could peel off that outer directory but if not maybe that's the missing feature (we recently fixed it so nested pkg_npm don't have extra wrapping directories)

**Comment by hsyed** [comment]
@alexeagle thanks, it is good to be back. I took a break due to personal reasons. Glad to see the Kotlin rules are being maintained.

New role, slightly different tech stack. Go mainly but Java/Kotlin might be on the cards for us soon.

It works ! In my mental model I wouldn't have expected the `pkg_tar` rule to accept a rule producing a directory. I don't know if this was possible back when I was working on the Kotlin rules.  Anyhow here is the snippet for creating a vue microservice served by nginx :D 

```
load("@build_bazel_rules_nodejs//:index.bzl", "npm_package_bin")
load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar")
load("@io_bazel_rules_docker//container:container.bzl", "container_image")

npm_package_bin(
    name = "app",
    tool = "@npm//@vue/cli-service/bin:vue-cli-service",
    args = [
        "build", "$(location :src/main.js)",
        "--dest", "$(@D)"
    ],
    data = [
        "@npm//:node_modules"
    ] + glob(["src/**"]),
    output_dir = 1
)

pkg_tar(
    name = "app-tar",
    strip_prefix = "/js/app",
    package_dir = "/usr/share/nginx/html",
    srcs = ["//js:app"],
    mode = "0755",
)

container_image(
   name = "image",
   base = "@nginx//image",
   tars = ["app-tar"]
)
```

It's pretty cool, it just works ! @crlssn can contribute an example if it makes sense ?

**Comment by alexeagle** [comment]
Yes please! We need a Vue example for sure.
