### ISSUE TITLE
No way to import date-fns locales without using internal rules

### ISSUE THREAD

**Issue by Serginho** [bazelbuild/rules_nodejs#1841]
# 🚀 feature request

### Relevant Rules
`karma_web_test_suite`

### Description

I can't find the way to import date-fns locales. I've imported date-fns for tests with `@npm//date-fns:date-fns.umd.js` in sources, but when browserify internally generates the umd bundle, locales are not imported.

It would be nice if you add an example of how to import this case. Even if you explain me how to do it, I can make a PR to improve examples for everyone.

I've tried to import the locale file in karma web test suite sources, event using require.config.js unsuccessfully.

Versions:
Bazel: 2.1.0
Rules node js: 1.2.2

**Comment by marcus-sa** [comment]
You need to use `npm_umd_bundle` like:
```
npm_umd_bundle(
    name = "date_fns_locale_umd",
    package_name = "date-fns/locale",
    entry_point = "@npm//:node_modules/date-fns/locale/index.js",
    package = "@npm//date-fns",
)
``` 
this used to work in `1.0.0`, but unfortunately it no longer does.

**Comment by Serginho** [comment]
@marcus-sa Can you access to the rule? I haven't tried to use it cause it's an internal rule.
>https://github.com/bazelbuild/rules_nodejs/blob/0eda43f524e296b67271faa1d947db798854f8a0/internal/npm_install/npm_umd_bundle.bzl#L17
