### ISSUE TITLE
Feature request: build native nodejs modules 

### ISSUE THREAD

**Issue by th0br0** [bazelbuild/rules_nodejs#185]
I'd like to build native nodejs modules (e.g. with https://github.com/nodejs/nan ) via bazel and also link in other `cc_library` targets that I've defined.

Is this currently on the roadmap?
If not, what's a good approach to do this that does not boil down to copying around compiled libraries?

**Comment by alexeagle** [comment]
I don't know much about this. Our team maintains the clang-format npm module, which is compiled for three platforms and all the binaries are distributed in the package - but this is unusual IIUC. The other option is like node-sass which use GYP and are compiled on the users machine, right? In that case nodejs is the build tool so I don't think there is much we could do to help.

It's certainly not on the roadmap. Maybe include some more details about the use cases and a proposed design for this, in case someone has time to pick it up and contribute.

**Comment by Toxicable** [comment]
Possibly a rule wrapper on https://www.npmjs.com/package/node-pre-gyp would do the job
I'm not certain how linking to other `cc_library` would work, would just depend on how `node-pre-gyp` works

**Comment by alexeagle** [comment]
#506 has a longer thread on this
