### ISSUE TITLE
npm_install not equivalent to `npm ci` for dependent versions or lerna hoisting

### ISSUE THREAD

**Issue by vpanta** [bazelbuild/rules_nodejs#1857]
Please bear with me, I'm still getting used to npm as a whole as well, so I might not use the right terminology/definitions when describing this. This also might not be a bazel bug per-se, but I'm at a loss for how to continue debugging it.

# 🐞 bug report

### Affected Rule

The issue is caused by the rule:
`npm_install`

### Is this a regression?

I don't know, this is my first attempt using bazel

### Description

We have a fairly large monorepo for TS and Go code which we've begun subpackaging with `lerna`. I've recently joined and have begun investigating Bazel as a single replacement for our mix of gulp, make, etc build system. In doing so, I'm attempting to get it to run in our world for a single subpackage (with a project global workspace file).

When I run `rm -rf node_modules/ && npm ci` for the repository, everything works as expected.

However, once I set up a `WORKSPACE` and run `rm -rf node_modules/ && bazel clean --expunge && bazel build :all` (BUILD file is empty right now), it fails during npm postinstall steps due to a version inconsistency. The error message I receive implies it's using a newer version of a dependency then the specific package requires:

```
> web-embed-lab@0.2.11 postinstall /Users/vasilios/src/bazel-npm-dependency-issue/node_modules/web-embed-lab
> go-npm install && mv ./node_modules/.bin/* ./tmp/* ../.bin/

 (/Users/vasilios/src/bazel-npm-dependency-issue/node_modules/.bin/go-npm:163
    var untar = tar.Extract({ path: opts.binPath });
                    ^

TypeError: tar.Extract is not a function
```

Specifically, `tar`'s newer versions have renamed `Extract` to simply `x`, and while `go-npm` requires `tar@2.2.1` (and is correct in my `package-lock.json`), `tar@4.4.*` is required elsewhere in the project and seems to get used here specifically when run via `npm_install`

Additional note:
Performing `npm ci` before `bazel build :all` allows it to get past that error, however then I run into an error during that build due to the `lerna` hoisting done as postinstall. I've included both issues in the below repo.

## 🔬 Minimal Reproduction

I have managed to create a minimal reproduction case trying to emulate what our main repo does.
https://github.com/vpanta/bazel-npm-dependency-issue

Clone that and run
> `bazel build :all`

## 🔥 Exception or Error

<pre><code>
master:~/src/bazel-npm-dependency-issue$ rm -rf node_modules/ && bazel clean --expunge && bazel build :all --define=VERBOSE_LOGS=1
INFO: Starting clean.
Starting local Bazel server and connecting to it...
INFO: Call stack for the definition of repository 'npm' which is a npm_install (rule definition at /private/var/tmp/_bazel_vasilios/7c22617b777286224fc3aac8aa91e2bd/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:309:15):
 - /private/var/tmp/_bazel_vasilios/7c22617b777286224fc3aac8aa91e2bd/external/build_bazel_rules_nodejs/index.bzl:80:5
 - /private/var/tmp/_bazel_vasilios/7c22617b777286224fc3aac8aa91e2bd/external/build_bazel_rules_nodejs/index.bzl:80:5
 - /Users/vasilios/src/bazel-npm-dependency-issue/WORKSPACE:34:1
ERROR: An error occurred during the fetch of repository 'npm':
   npm_install failed: 

... successful steps redacted ...

> web-embed-lab@0.2.11 postinstall /Users/vasilios/src/bazel-npm-dependency-issue/node_modules/web-embed-lab
> go-npm install && mv ./node_modules/.bin/* ./tmp/* ../.bin/

 (/Users/vasilios/src/bazel-npm-dependency-issue/node_modules/.bin/go-npm:163
    var untar = tar.Extract({ path: opts.binPath });
                    ^

TypeError: tar.Extract is not a function
    at Object.install (/Users/vasilios/src/bazel-npm-dependency-issue/node_modules/.bin/go-npm:163:21)
    at Object.<anonymous> (/Users/vasilios/src/bazel-npm-dependency-issue/node_modules/.bin/go-npm:212:17)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:67:12)
    at internal/main/run_main_module.js:17:47
npm WARN bazel-npm-dependency-issue@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @bazel/bazel-linux_x64@2.1.0 (node_modules/@bazel/bazel/node_modules/@bazel/bazel-linux_x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @bazel/bazel-linux_x64@2.1.0: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @bazel/bazel-win32_x64@2.1.0 (node_modules/@bazel/bazel/node_modules/@bazel/bazel-win32_x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @bazel/bazel-win32_x64@2.1.0: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web-embed-lab@0.2.11 postinstall: `go-npm install && mv ./node_modules/.bin/* ./tmp/* ../.bin/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web-embed-lab@0.2.11 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vasilios/.npm/_logs/2020-04-30T18_19_14_168Z-debug.log
)

... 2x repeated attempts redacted ...

INFO: Elapsed time: 15.850s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
MacOS v10.15.4 Catalina
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
master:~/src/bazel-npm-dependency-issue$ bazel version
Build label: 2.1.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Feb 7 13:04:00 2020 (1581080640)
Build timestamp: 1581080640
Build timestamp as int: 1581080640
  </code>
</pre>

**Rules_nodejs version:**

<pre>
  <code>
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "f9e7b9f42ae202cc2d2ce6d698ccb49a9f7f7ea572a78fd451696d03ef2ee116",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/1.6.0/rules_nodejs-1.6.0.tar.gz"],
)
  </code>
</pre>

**Anything else relevant?**
Again, *insert I don't know what I'm doing dog* so maybe this isn't an issue with bazel but I'm just doing something wrong.

**Comment by alexeagle** [comment]
We haven't tested with Lerna, and the way it expects to control the node_modules layout probably conflicts with what we expect. But it's great to have this minimal repro, maybe we can play with it to understand better what we'd need to fix to make Lerna work in this way.

**Comment by vpanta** [comment]
Sans lerna though, the initial question is around it using the (seemingly) wrong version of the `tar` package. Presumably if we got that far, we'd replace lerna packaging with bazel builds.

**Comment by vpanta** [comment]
Would like to reopen as I have some more info:

`bazel run @nodejs//:npm -- ci` fails with the version mismatch, but adding `--scripts-prepend-node-path=true` makes it work.

In fact, the later `lerna` issue also works fine.

**Comment by vpanta** [comment]
And it seems like using that in `npm_install` is working for me now.

```
npm_install(
    name = "npm",
    args = ["--scripts-prepend-node-path=true"],
    package_json = "//:package.json",
    package_lock_json = "//:package-lock.json",
)
```

I don't know why this specifically would cause the version mismatch and the `lerna` post-install failure :/

**Comment by alexeagle** [comment]
@vpanta could you clarify, is there still a bug in rules_nodejs or a change we should make? I think your last comment indicates it's working, or you have a workaround

**Comment by vpanta** [comment]
We can close this. As of `rules_nodejs@3.2.1` we aren't having this issue anymore. Technically our stack works on MacOS using `npm_install` (and we haven't changed anything about using `lerna` at the moment, nor anything about the competing `tar` versions).

We are still prevented from using `npm_install` on our CI (Linux) docker container by https://github.com/bazelbuild/rules_nodejs/issues/506 however

But we'll talk about this there, closing this issue.
