### ISSUE TITLE
Verify early that test files actually define the corresponding named modules

### ISSUE THREAD

**Issue by mernst-github** [bazelbuild/rules_nodejs#1867]
#1308 # Relevant Rules

karma_web_test

### Description

The scripts generated by karma_web_test loadFile()s all the files and then require()s them as modules:

```
...
 loadFile(
      "workspace/src/test/ts/..._test.js",
      "var __awaiter = ...");
  loadFile(
      "../../../../../../../../_tmp/38e45c1d5edcea94c71b05fa49e4545d/tmp-18895cP3fwIlj2RG3.js",
      "\n      // A simplified version of Karma's requirejs.config.tpl.js f...)

```

The unstated assumption is that ..._test.js actually defines a named module '..._test' . If that assumption doesn't hold the errors are really hard to grasp for a newbie, namely
'no timestamp' warnings, 404s in the web server (since the module name doesn't even map to the right url) and a 30s timeout (since we never reach __karma__.start).

I did not find this documented anywhere and the mechanism in the examples/ is also fairly obscure: 
```
// at least one import or export is needed for this file to
// be compiled into an named-UMD module by typescript
export {}; 
```

To reproduce, try to use an empty .js file as "src" of a karma_web_test rule.

### Describe the solution you'd like

The requirements for the contents of test files  should be documented more clearly.
Also, after/as part of each loadFile, karma_web_test should check that the file indeed defined the right named module and abort early with a useful error message.

### Describe alternatives you've considered

Maybe even a build-time check on the test files whether they're named modules?

**Comment by mernst-github** [comment]
#1872 is a "wonderful" example of the confusion that arises when people try to debug these issues. A better error would really be appreciated!

**Comment by applmak** [comment]
+1 This caused me much wasted time.

**Comment by mernst-github** [comment]
Alternatively, instead of _assuming_ that test files create certain modules, one could use this (semi-public) requirejs api to _learn_ which modules are defined and issue the respective 'require' calls.
https://github.com/requirejs/requirejs/wiki/Internal-API:-onResourceLoad 
(I just read up on this, I have no experience whether the api works as expected.)

**Comment by papshed** [comment]
+1 This caused us much wasted time.

**Comment by alexeagle** [comment]
Sorry everyone - since karma_web_test is no longer in this repo, I'm closing the issue.
