### ISSUE TITLE
npm_package.publish script assumes there is a symlink_prefix

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#187]
reported by @IgorMinar

The .pack and .publish scripts produced by npm_package run `npm publish bazel-out/path/to/thing`

If you don't have a `bazel-out` folder in your project this fails.

**Comment by nimerritt** [comment]
I guess that explains why I need to run the bazel run command from the workspace root which confused me a bit. https://github.com/Springworks/rules_nodejs_min_pub/blob/02c43b5690e1daccad15417455ecc322a65f2c8d/super_app/build.sh#L5

**Comment by alexeagle** [comment]
Actually that's a different issue:
https://github.com/bazelbuild/rules_nodejs/issues/187
You ought to be able to run those commands from any working directory

**Comment by alexeagle** [comment]
The Bazel team is making progress on the XCode/VSCode interaction problem, they have narrowed it down to an issue with Santa and VSCode - I think the priority here is low because when they fix that, we'll just recommend that everyone has a bazel-out symlink (this is in a stable location even if you use `--symlink_prefix=dist/` to relocate the other symlinks)
