### ISSUE TITLE
Documentation on using self-hosted node_modules for TS incorrect

### ISSUE THREAD

**Issue by Fleker** [bazelbuild/rules_nodejs#1870]
# 🐞 bug report

### Affected Rule
The issue comes from the documentation at https://github.com/bazelbuild/rules_nodejs/blob/master/docs/TypeScript.md#self-managed-npm-dependencies, which appears to be wrong and vague.

### Description

I've followed the steps to compile a TS library successfully and now and incorporating an external library for which I need to include as part of the `ts_library` rule. I have installed it locally via npm and want to make it part of my library rule.

However, following the guidance in the documentation throws multiple errors and I do not know how to adjust the rule so that it works. It seems that at the very least the `node_modules` attribute is wrong, suggesting issues with the rest of the section.

## 🔬 Minimal Reproduction

_BUILD_
```
filegroup(
  name = "node_modules",
  srcs = glob(
    include = [
      "node_modules/**/*.js",
      "node_modules/**/*.d.ts",
      "node_modules/**/*.json",
      "node_modules/.bin/*",
    ],
    exclude = [
      # Files under test & docs may contain file names that
      # are not legal Bazel labels (e.g.,
      # node_modules/ecstatic/test/public/中文/檔案.html)
      "node_modules/**/test/**",
      "node_modules/**/docs/**",
      # Files with spaces in the name are not legal Bazel labels
      "node_modules/**/* */**",
      "node_modules/**/* *",
    ],
  ),
)

# Create a tsc_wrapped compiler rule to use in the ts_library
# compiler attribute when using self-managed dependencies
nodejs_binary(
    name = "@bazel/typescript/tsc_wrapped",
    entry_point = "@bazel/typescript/internal/tsc_wrapped/tsc_wrapped.js",
    # Point bazel to your node_modules to find the entry point
    node_modules = ["//:node_modules"],
)
```

## 🔥 Exception or Error

<pre><code>
$ bazelisk build //...
ERROR: /.../typescript/BUILD:78:1: //typescript:@bazel/typescript/tsc_wrapped: invalid label '@bazel/types
cript/internal/tsc_wrapped/tsc_wrapped.js' in attribute 'entry_point' in 'nodejs_binary' rule: invalid repository name '@bazel/typescript/internal/tsc_wrapped/tsc_wrapped.js': workspace names may contain only A-Z, a-z, 0-9, '-', '_' and '.'
ERROR: /.../typescript/BUILD:78:1: //typescript:@bazel/typescript/tsc_wrapped: expected value of type 'str
ing' for attribute 'node_modules' in 'nodejs_binary' rule, but got ["//:node_modules"] (list)
ERROR: /.../typescript/BUILD:78:1: //typescript:@bazel/typescript/tsc_wrapped: missing value for mandatory
 attribute 'entry_point' in 'nodejs_binary' rule
ERROR: package contains errors: typescript
ERROR: error loading package 'typescript': Package 'typescript' contains errors
INFO: Elapsed time: 0.109s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
error Command failed with exit code 1.
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Debian 5.2.17-1rodete3-amd64
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.4.0
Build label: 3.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Apr 22 10:32:27 2020 (1587551547)
Build timestamp: 1587551547
Build timestamp as int: 1587551547
  </code>
</pre>

**Rules_nodejs version:**

<pre>
  <code>
v1.6.0
  </code>
</pre>

**Anything else relevant?**

The correct rule should look more like:

```
nodejs_binary(
    name = "ext-lib",
    entry_point = "@npm//:node_modules/@bazel/typescript/internal/tsc_wrapped/tsc_wrapped.js",
    # Point bazel to your node_modules to find the entry point
    node_modules = ":node_modules",
)
```

**Comment by mattem** [comment]
Thanks for reporting this issue, the docs are misleading here. 
The `nodejs_binary` used here is for tsc_wrapped, and should be:
```
nodejs_binary(
    name = "@bazel/typescript/tsc_wrapped",
    entry_point = "@npm//:node_modules/@bazel/typescript/internal/tsc_wrapped/tsc_wrapped.js",
    # Point bazel to your node_modules to find the entry point
    node_modules = ":node_modules",
)
```
