### ISSUE TITLE
Unclear how to integrate self-hosted node_modules in ts_library rule

### ISSUE THREAD

**Issue by Fleker** [bazelbuild/rules_nodejs#1871]
# 🐞 bug report

### Affected Rule

`ts_library`

### Is this a regression?
No

### Description

After modifying my setup like #1870 I would like the external libraries to be integrated into my `ts_library` as a dependency. However, [the documentation](https://github.com/bazelbuild/rules_nodejs/blob/master/docs/TypeScript.md) is not clear on how to get a `DelcarationInfo` from my `nodejs_binary`.

The `ext-lib` rule finishes, generating a few files, but it doesn't seem like it generates the sufficient files to work in a `ts_library`.

## 🔬 Minimal Reproduction

```
filegroup(
  name = "node_modules",
  srcs = glob(
    include = [
      "node_modules/**/*.js",
      "node_modules/**/*.d.ts",
      "node_modules/**/*.json",
      "node_modules/.bin/*",
    ],
    exclude = [
      # Files under test & docs may contain file names that
      # are not legal Bazel labels (e.g.,
      # node_modules/ecstatic/test/public/中文/檔案.html)
      "node_modules/**/test/**",
      "node_modules/**/docs/**",
      # Files with spaces in the name are not legal Bazel labels
      "node_modules/**/* */**",
      "node_modules/**/* *",
    ],
  ),
)

nodejs_binary(
  name = "ext-lib",
  entry_point = "@npm//:node_modules/@bazel/typescript/internal/tsc_wrapped/tsc_wrapped.js",
  # Point bazel to your node_modules to find the entry point
  node_modules = ":node_modules",
)

ts_library(
  name = "lib",
  srcs = [":quicktype", ":codegen"],
  deps = [":core-lib", ":ext-lib"]
)
```

## 🔥 Exception or Error

<pre><code>
$ bazelisk build //typescript:lib
ERROR: /.../typescript/BUILD:85:1: in ts_library rule //typescript:lib: 
Traceback (most recent call last):
        File "/.../typescript/BUILD", line 85
                ts_library(name = 'lib')
        File "/.../.cache/bazel/_bazel_fleker/62e2e7c5c3b8d6bdc05ec6603bd6c4c8/external/npm_bazel_typescript/internal/build_defs.bzl", line 280, in _ts_library_impl
                compile_ts(ctx, <4 more arguments>)
        File "/.../.cache/bazel/_bazel_fleker/62e2e7c5c3b8d6bdc05ec6603bd6c4c8/external/npm_bazel_typescript/internal/common/compilation.bzl", line 220, in compile_ts
                d[DeclarationInfo]
<merged target //typescript:ext-lib> doesn't contain declared provider 'DeclarationInfo'
ERROR: Analysis of target '//typescript:lib' failed; build aborted: Analysis of target '//typescript:lib' failed
INFO: Elapsed time: 0.118s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 13 targets configured)
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Debian 5.2.17-1rodete3-amd64
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.4.0
Build label: 3.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Apr 22 10:32:27 2020 (1587551547)
Build timestamp: 1587551547
Build timestamp as int: 1587551547
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
v1.6.0
  </code>
</pre>

**Anything else relevant?**

**Comment by mattem** [comment]
Generally, it's recommended to use fine-grained deps, as this scales better with the size of the `node_modules` repo. For fine grained deps, they can be added to the `deps` attr of `ts_library` as needed (assuming the dep is yargs in this example):

```
ts_library(
    name = "src",
    srcs = glob(["*.ts"]), # or references to ts files directly, or a rule that generates ts
    deps = [
       "@npm//yargs",
       ":core-lib",
    ],
)
```

For coarse-grained, adding a `node_modules` attr would be needed, referencing that filegroup (`//:node_modules`). The `compiler` attr would also need to be set, which is what the `nodejs_binary` here is for (not for specifying deps). `*_binary` rules are generally considered runnable, eg tsc for Typescript compile.

```
ts_library(
    name = "src",
    srcs = glob(["*.ts"]), # or references to ts files directly, or a rule that generates ts
    deps = [":core-lib"],
    node_modules = "//:node_modules",
    compiler = "//:@bazel/typescript/tsc_wrapped",
)
```

**Comment by Fleker** [comment]
Thanks. Unfortunately, while `@npm//yargs` seems to work as a direct dependency, I'm trying and unable to use `@npm//googleapis` correctly that way. But your recommendation of formatting it that way does work.

**Comment by mattem** [comment]
Do you get an error? I'm not familiar with the googleapis module, but if you can send me an error and version of googleapis you are using, then I can try and repro.

**Comment by Fleker** [comment]
Using a rule that includes [googleapis](https://github.com/googleapis/google-api-nodejs-client#readme):

```
ts_library(
  name = "lib",
  srcs = [":quicktype", ":codegen"],
  deps = [":core-lib", "@npm//googleapis"]
)
```

The build error is

```
Starting local Bazel server and connecting to it...
ERROR: /.../typescript/BUILD:85:1: no such package '@npm//googleapis': BUILD file not found in directory '
googleapis' of external repository @npm. Add a BUILD file to a directory to mark it as a package. and referenced by '//typescript:lib'
ERROR: Analysis of target '//typescript:lib' failed; build aborted: no such package '@npm//googleapis': BUILD file not found in directory 'googleapis' of exte
rnal repository @npm. Add a BUILD file to a directory to mark it as a package.
```

This doesn't happen with `@npm//yargs`, and it doesn't happen using the `node_modules` rule.

**Comment by mattem** [comment]
Do you have `googleapis` in your `package.json` file? 
I made a [small repo](https://github.com/mattem/rules_nodejs_issue_1871) with googleapis as a dep, it builds and runs as expected.

**Comment by Fleker** [comment]
My build process has more than one step which includes copying the package contents to its output directory. I have the rule:

```
copy_file(
  name = "package",
  src = ":_package.json",
  out = "package.json"
)
```

With the underscore prefix in the working directory as there's an error if they share the same name. I also seem to be unable to alias the file. My `_package.json` does have `googleapis` in the dependency list.

**Comment by mattem** [comment]
Are you able to put together a small reproduction repo showing the issue?

**Comment by Fleker** [comment]
Here's a minimal repro case demonstrating the error similar to the larger project design 
https://github.com/Fleker/bazelbuild_rules_nodejs_1871
