### ISSUE TITLE
Remove node_modules attribute from all rules

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/rules_nodejs#1886]
Users should use node_modules_library if they want to self manage node_modules and pass the target to deps.

TODO(@gregmagolan): need a little investigation to come up with the right recommendations.

**Comment by alexeagle** [comment]
I spent an hour or two trying to tear these out and didn't succeed. Maintainers are stretched thin on time right now so punting this to next breaking release.

**Comment by alexeagle** [comment]
fixed by https://github.com/bazelbuild/rules_nodejs/commit/c2927afa9a5d77652783f94eada80baf1c9be68f
