### ISSUE TITLE
Add a disclaimer to README about Google support level for these rules

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/rules_nodejs#1887]
rules_python has some copy that is a good reference in their README: https://github.com/bazelbuild/rules_python#overview

**Comment by gregmagolan** [comment]
Can also add specific copy about ts_devsever, karma_web_test & ts_library as they come from the g3 toolchain and have g3 idiosyncrasies

**Comment by alexeagle** [comment]
Note, for convenience I merged to the default branch (1.x) so we should cherry-pick to `next`. Dependabot is doing this too.
