### ISSUE TITLE
Expose require resolver as a public API

### ISSUE THREAD

**Issue by greenboxal** [bazelbuild/rules_nodejs#1891]
# 🚀 feature request

### Relevant Rules

* nodejs_binary
* nodejs_test

### Description

Test runners like jest and linters like eslint loads javascript to be tested using custom resolvers instead of exposing nodejs' `require()`. As they reimplement nodejs logic, the patch applied to require() so it uses runfiles has no effect, and it will fail to resolve most imports.

### Describe the solution you'd like

Expose an API, maybe in `BAZEL_NODE_RUNFILES_HELPER` that returns the resolved path for a file. This is already accessible through `module.constructor._resolveFilename`, but this seems like a private API that could break. I believe we only have to standardize the API.

**Comment by joeljeske** [comment]
Have you tried using require.resolve(path)?

**Comment by greenboxal** [comment]
I believe that should work in most cases (didn't think fo that). In any case, I worry about situations where `require` was replaced, like what Jest does.

I guess that if `require.resolve()` solves most use cases this has way lower priority, but still interesting to provide a stable API.

**Comment by alexeagle** [comment]
We are moving away from patching require() to handle runfiles, so I'd suggest not relying on that. Either use `runfiles.resolve` if you're a bazel-aware binary that wants to see a "union" view of the input tree and output tree, or else make sure everything gets copied into the output tree and just use `require.resolve` like @joeljeske says. I think any additional public API would actually be a design smell, one of these two should work.
If you have a specific scenario that isn't supported, please open a new issue - thanks!
