### ISSUE TITLE
Build fails "Unable to load file '@npm//@bazel/protractor:package.bzl'"

### ISSUE THREAD

**Issue by cschuet** [bazelbuild/rules_nodejs#1894]
# 🐞 bug report

### Affected Rule

bazel run src:nodejs_image -- --norun

### Is this a regression?

Yes, build for 2e93d963401f86b394c02b767ab1d045531b7e3e works fine.

### Description

Bazel build of target `bazel run src:nodejs_image -- --norun` fails with

> $ bazel run src:nodejs_image -- --norun
> INFO: Invocation ID: c15f9132-9ae9-4e11-9893-b61b20e475d0
> ERROR: error loading package '': Unable to load file '@npm//@bazel/protractor:package.bzl': file doesn't exist
> INFO: Elapsed time: 144.451s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (0 packages loaded)
> FAILED: Build did NOT complete successfully (0 packages loaded)

Bazel version:

> Bazelisk version: v1.4.0
> Starting local Bazel server and connecting to it...
> Build label: 3.1.0
> Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
> Build time: Wed Apr 22 10:32:27 2020 (1587551547)
> Build timestamp: 1587551547
> Build timestamp as int: 1587551547

**Comment by lukasholzer** [comment]
Can reproduce the same behaviour with the current master. `e8ffdbc9ff5f0d66276138d27fb8019e72c51ec6`

**Comment by alexeagle** [comment]
Hmm, it's probably related to https://github.com/bazelbuild/rules_nodejs/commit/7dd9ec31ae34a8f46bbd0b655c42f6b37c0bf1df
you can see in that commit we do have `load("@npm//@bazel/protractor:package.bzl", "npm_bazel_protractor_dependencies")` in `e2e/ts_devserver/WORKSPACE` 
Can you do a bit more digging into where the load statement lives that causes this?

Do you intend to use protractor for your app?
- if not, maybe we accidentally introduced a dependency on it
- if so, maybe you're missing the `@bazel/protractor` package in your dependencies?

**Comment by Smokrow** [comment]
The same thing happens when you want to load bazel labs:
`load("@npm_bazel_labs//:package.bzl", "npm_bazel_labs_dependencies") `

**Comment by dparrish** [comment]
This is happening for me running the included examples:
```
$ git clone git@github.com:bazelbuild/rules_nodejs.git

$ cd rules_nodejs/examples/angular

$ bazel build :dummy_test
INFO: Invocation ID: 29558be6-8618-4228-8037-335189466010
ERROR: error loading package '': Unable to load file '@npm//@bazel/protractor:package.bzl': file doesn't exist
INFO: Elapsed time: 0.078s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

$ bazel version
Build label: 3.2.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed May 27 17:54:00 2020 (1590602040)
Build timestamp: 1590602040
Build timestamp as int: 1590602040

```

**Comment by alexeagle** [comment]
@dparrish that's a different issue - right now we have some breaking changes on master leading up to the 2.0 release so the examples only work if their dependencies are built from head.
We'll come up with a proper solution for that today, right now you should just checkout the 1.x branch to get examples that work against current release.
