### ISSUE TITLE
The output of the `ng_ts_library` does not play well with the `ng_package` rule.

### ISSUE THREAD

**Issue by lukasholzer** [bazelbuild/rules_nodejs#1903]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: `ng_ts_library`

### Is this a regression?

 No

### Description

When the `ng_package` rule is utilized from the `@npm_angular_bazel//:index.bzl` repository, to create an [angular package format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview) of the compiled modules with the `ng_ts_library` it is failing with the error message provided below.

I created a reproducible example in this pull request #1902 

## 🔬 Minimal Reproduction

1. checkout my pull request #1902 
2. Go to Directory `cd examples/angular`
3. Run `bazel build //src/lib/angular-lib`

## 🔥 Exception or Error

<pre><code>
INFO: Invocation ID: 51254892-f612-462b-8fa2-e9a7d73af168
ERROR: /Users/lukas.holzer/Sites/rules_nodejs/examples/angular/src/lib/angular-lib/BUILD.bazel:5:1: in ng_package rule //src/lib/angular-lib:angular-lib:

The following files have no generating action:
src/lib/angular-lib/angular-lib.umd.js
src/lib/angular-lib/angular-lib.umd.min.js
src/lib/angular-lib/fesm2015/angular-lib.js
src/lib/angular-lib/fesm5/angular-lib.js
ERROR: Analysis of target '//src/lib/angular-lib:angular-lib' failed; build aborted: Analysis of target '//src/lib/angular-lib:angular-lib' failed
INFO: Elapsed time: 0.094s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
OS X 10.15.4
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.4.0
Build label: 3.1.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Apr 22 10:35:52 2020 (1587551752)
Build timestamp: 1587551752
Build timestamp as int: 1587551752
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
  </code>
</pre>

**Anything else relevant?**

**Comment by mattem** [comment]
Notes from investigation, the issue manifests when the compiler is overridden on `ts_library` and extra deps added. 

During a build of `ng_package`, the typescript compile is replayed to produce ES5 syntax with ES modules, via the `esm5_outputs_aspect`. When that aspect replays the compile, it does so with the standard tsc_wrapped binary [1], and therefore has the missing extra deps added for `@angular/compiler-cli` require.

[1] https://github.com/angular/angular/blob/master/packages/bazel/src/esm5.bzl#L146

**Comment by alexeagle** [comment]
This bumps into some older clunky parts of the rules.
In particular, the replay aspect is a hack for Angular to produce es5. I've heard this requirement is going away. Maybe Angular team has already made some announcement about their package format no longer including an es5 variant? Seems like the closest fix is to make the es5 output optional now as a prefactoring to whatever Angular is doing, and try to remove all uses of that esm5.bzl feature.

**Comment by jbedard** [comment]
The es5 variants have been removed for v10, and were deprecated in v9?

https://github.com/angular/angular/commit/9dbb30f884dfedc758df1efeaf79c826c51fd1c7
