### ISSUE TITLE
Support declare_directory inputs to ts_library

### ISSUE THREAD

**Issue by cschuet** [bazelbuild/rules_nodejs#1907]
# 🚀 feature request

## Background

I am working on a project in which I rely on protobuf / gRPC + JSON/gRPC transcoding to connect my backends to an Angular frontend. I am using protobuf descriptor + swagger to generate angular clients for my APIs. Currently I check-in the generated client code, but would much rather have the Angular client code generation become part of the build process.

I did some research and found it easy to move the swagger.json generation to Bazel, but I am struggling with writing a rule to auto-generate Angular client generation. The problem is mainly that it is difficult deal with situations in Bazel where the file outputs of a rule are only known at execution phase, but not yet at analysis phase. [This](https://stackoverflow.com/questions/48417712/how-to-build-static-library-from-the-generated-source-files-using-bazel-build/48524539#48524539) indicates that using [declare_directory](https://docs.bazel.build/versions/master/skylark/lib/actions.html#declare_directory) is way to deal with such situations.

## declare_directory inputs to ts_library

I set up a simple toy example to explore this approach

`ben.bzl`
```
def _impl(ctx):
  # Adding .ts is a hack to trick ts_library rule to accept the input formerly.
  tree = ctx.actions.declare_directory(ctx.attr.name + ".ts")
  ctx.actions.run(
    inputs = [],
    outputs = [ tree ],
    arguments = [ tree.path ],
    progress_message = "Generating ts files into '%s'" % tree.path,
    executable = ctx.executable._tool,
  )

  return [ DefaultInfo(files = depset([ tree ])) ]

gen = rule(
  implementation = _impl,
  attrs = {
    "_tool": attr.label(
      executable = True,
      cfg = "host",
      allow_files = True,
      default = Label("//src:tool"),
    )
  }
)
```

`tool.cc` simply generates a trivial typescript file:
```
#include <iostream>
#include <filesystem>
#include <fstream>
#include <sys/stat.h>
using namespace std;

int main(int argc, char* argv[]) {
  mkdir(argv[1], S_IRWXU);
  std::ofstream out(std::string(argv[1]) + "/test.ts");
  out << "class Greeter{}" << std::endl;
  out.close();
}
```

In the `BUILD` file I would like to use the declared directory output as a srcs input to `ts_library)`

```
load("@npm_bazel_typescript//:index.bzl", "ts_library")
load(":gen.bzl", "gen")

exports_files(["tsconfig.json"], visibility = ["//visibility:public"])

gen(
    name = "gen_tree",
)

ts_library(
  name = "gen_lib",
  srcs = [ ":gen_tree" ],
)

cc_binary(
  name = "tool",
  srcs = ["tool.cc"],
)

```

However this does not work as the typescript compiler invocation fails with `Compilation failed Error: EISDIR: illegal operation on a directory, read` as `ts_library` does not support directory inputs.

Can we make this work? Is there another way to achieve swagger generated Angular client code to become part of the build process?

### Relevant Rules

`ts_library`

### Description

Extend `ts_library` to accept `declare_directory` inputs for generated code.

### Describe the solution you'd like

I have proposed a solution in this feature request, but I am generally interested in solutions for the problem to include swagger-generated client code in the build process.

### Describe alternatives you've considered

* check-in the code

**Comment by alexeagle** [comment]
I think this should be pretty easy to add to the ts_project rule, which is a thin wrapper around `tsc`.
ts_library is harder because it has a source-of-truth in Google's internal repo so making pull requests to it is a longer process.

**Comment by alexeagle** [comment]
I think I need this today for bringing https://github.com/apollographql/apollo-tooling#apollo-clientcodegen-output into a ts_project, looking now...
