### ISSUE TITLE
Publish examples to stand-alone repositories

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/rules_nodejs#1912]
Using our examples is problematic when there are breaking changes on head before the next release. The work-around is to clone at a release tag and the examples should always work. The better solution is to publish the examples to their own stand-alone repos with the source of truth the monorepo.

**Comment by alexeagle** [comment]
Related: the issue for the canonical angular example
https://github.com/bazelbuild/rules_nodejs/issues/1130

**Comment by gonzojive** [comment]
This would be much appreciated.

One thing I discovered after copying examples/angular into a directory outside of rules_js is that example/angular/.bazelrc depends on the root .bazelrc. After copying the relevant .bazelrc entries into the external project directory, the example seems to build and test ok @ 1.7.0. I'm not sure what the expectations are for rules_nodejs regarding .bazelrc. Do the rules depend on a certain .bazelrc configuration to work properly? Which .bazelrc files do users need to keep in sync when updating rules_nodejs versions.  This is just something to keep in mind when publishing the example repos.

**Comment by alexeagle** [comment]
Scoping down the 2.0 milestone since Greg and I haven't had much time.

**Comment by evahowe** [comment]
@alexeagle and @gregmagolan - can I close this then or do we do something else with it?

**Comment by alexeagle** [comment]
Now that we decided default branch will be stable, I think this is less important
