### ISSUE TITLE
Multiple ts_project/ts_library rules in the same library

### ISSUE THREAD

**Issue by longlho** [bazelbuild/rules_nodejs#1914]
# 🚀 feature request

### Relevant Rules

`ts_project`/`ts_library`

### Description

It's pretty common to produce CommonJS & ES Module dist for different env/bundler consumption. Within `package.json` I can specify `main` for CommonJS & `module` for ES Module.

Currently I don't think I can compile the same set of source files using 2 `ts_project`/`ts_library` to produce cjs + esm artifacts right?

### Describe the solution you'd like

Allow output directory/pattern so I can dist out cjs & esm separately

### Describe alternatives you've considered

Copy src files to a 2 separate folders & compile?

**Comment by joeljeske** [comment]
ts_library does produce esm and umd artifacts that can be used independently. You can reference them using the output groups “es5_sources” and “es6_sources”. 

Another option is to use a tool like rollup to bundle to different formats. You can specify output directories with rollup and the reference the directory as a whole.

**Comment by longlho** [comment]
Yup the way we bundle all libraries in formatjs suite is that we output both UMD (ES5) & ESM (ES6) with 2 tsconfig (`tsconfig.json` to `dist/` & `tsconfig.esm.json` to `lib/` basically). An example: https://github.com/formatjs/formatjs/tree/master/packages/react-intl
We use the ES6 version to run [test262](https://github.com/tc39/test262) suite as well
While the solution mentioned might work, it complicates things like sourcemap, especially when custom TS compiler is involved.

**Comment by alexeagle** [comment]
Actually this turns out to be very easy:
https://github.com/bazelbuild/rules_nodejs/pull/1947

Like I said, ts_project knows a mapping from input .ts to output .js - but that mapping can take an argument with an extra path segment we use as an outdir. Note that it still has to go in the output tree under the package where the rule is declared.

Does that solve your problem?

**Comment by longlho** [comment]
Yup definitely! Thanks I'll follow that PR

**Comment by alexeagle** [comment]
It's merged so I'll close this. The change in ts_project.bzl is really small so it's easy for you to patch until next release.
I dunno if we'll cut another 1.x release or do a 2.0 beta next.

**Comment by longlho** [comment]
Thanks! I'm waiting for https://github.com/bazelbuild/rules_nodejs/pull/1898 anw so i'll wait for the next beta release or so.
