### ISSUE TITLE
Error when compile AngularExample in Windows

### ISSUE THREAD

**Issue by salim-boudriiya** [bazelbuild/rules_nodejs#1920]
Hi,

We are trying to run the example of the angular project that is in the repository:

https://github.com/bazelbuild/rules_nodejs/tree/master/examples/angular

but we find the following error:

ERROR: C:/users/degr/downloads/angular-bazel-example-master/src/app/billing/module0/BUILD.bazel:14:1: SassCompiler src/app/billing/module0/cmp1/cmp1.component.css failed (Exit 1)
 ‘“”’ is not recognized as an internal or external command,
 operable program or batch file.
 Target //src:devserver failed to build
 Use --verbose_failures to see the command lines of failed build steps.
 ERROR: C:/users/degr/downloads/angular-bazel-example-master/src/BUILD.bazel:89:1 SassCompiler src/app/billing/module0/cmp1/cmp1.component.css failed (Exit 1)
 INFO: Elapsed time: 2.705s, Critical Path: 0.89s
 INFO: 0 processes.
 FAILED: Build did NOT complete successfully
 ERROR: Build failed. Not running target
 FAILED: Build did NOT complete successfully
 Error starting process: fork/exec C:\Users\DEGR\AppData\Local\Temp\bazel_script_path658914935.bat: %1 is not a valid Win32 application.
 Run start failed fork/exec C:\Users\DEGR\AppData\Local\Temp\bazel_script_path658914935.bat: %1 is not a valid Win32 application.

can someone help us.

Best regards.

@gonzaloruizdevilla

**Comment by alexeagle** [comment]
Hrm, yeah it's disabled on our Windows CI
https://github.com/bazelbuild/rules_nodejs/blob/master/examples/BUILD.bazel#L37

But something seems confused in your report, there is no `billing` folder in https://github.com/bazelbuild/rules_nodejs/tree/master/examples/angular/src/app
So I think you're looking at the very outdated archived repo https://github.com/angular/angular-bazel-example/tree/master/src/app/billing

Maybe you should start with a fresh clone of this repo?

**Comment by salim-boudriiya** [comment]
Thanks Alex,

we will try right now, and we will tell you about the result.

Best regards.
