### ISSUE TITLE
Support named ts_projects for bazel output progress messages

### ISSUE THREAD

**Issue by joeljeske** [bazelbuild/rules_nodejs#1927]
# 🚀 feature request

### Relevant Rules

ts_project

### Description

I am using a single tsconfig.json for most of my packages. I only include the relevant srcs/deps for each package but leverage the same tsconfig.json file. The bazel output log shows progress like this: 

```
Compiling TypeScript project path/to/tsconfig.json
Compiling TypeScript project path/to/tsconfig.json
Compiling TypeScript project path/to/tsconfig.json
Compiling TypeScript project path/to/tsconfig.json
Compiling TypeScript project path/to/tsconfig.json
```

(Those are all separate target messages)

### Describe the solution you'd like

I would like the progress message to be customizable, or at least use the target in the name instead of the tsconfig name. 

### Describe alternatives you've considered

Patching @bazel/typescript for this behavior. 

Perhaps I am using ts_project incorrectly by re-using the same config, but it otherwise seems to work find.

**Comment by alexeagle** [comment]
Yeah you're holding it right. Having a single config file is a good practice.

You can see other `progress_message` around the repo, they are not super consistent. I did do a pass once to make them more consistent though, so I'd propose

`"Compiling TypeScript project %s [tsc -p %s]" % (ctx.label, ctx.file.tsconfig.short_path)`
WDYT?

**Comment by joeljeske** [comment]
Looks fine to me, just making sure you can see a label
