### ISSUE TITLE
Where can I find the worker source code?

### ISSUE THREAD

**Issue by calebmer** [bazelbuild/rules_nodejs#1929]
I’ve been looking at the source code for `@bazel/rollup` and `@bazel/worker` in this repository but I can’t find the source code for files with names like `worker.js`. Why is that? Are these files considered to be private? I can see the compiled versions in the npm packages, e.g. https://unpkg.com/browse/@bazel/worker@1.7.0/

**Comment by alexeagle** [comment]
If you trace through the build file in that package, you'll see they are copied from rules_typescript. It's a weird artifact of these coming from Google-internal source-of-truth as part of ts_library implementation.
We have an issue to move the sources here and add concurrent worker support.

**Comment by mattem** [comment]
The source TS file is here, for reference
https://github.com/bazelbuild/rules_typescript/blob/master/internal/tsc_wrapped/worker.ts

**Comment by calebmer** [comment]
Thank you!
