### ISSUE TITLE
facing issue whilst building project through bazel

### ISSUE THREAD

**Issue by Taranbirbajwa** [bazelbuild/rules_nodejs#1939]
An error occurred during the fetch of repository 'build_bazel_rules_nodejs':
   java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_nodejs/releases/download/1.6.0/rules_nodejs-1.6.0.tar.gz] to C:/users//_bazel_10/xiuovwtk/external/build_bazel_rules_nodejs/rules_nodejs-1.6.0.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: no such package '@build_bazel_rules_nodejs//': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_nodejs/releases/download/1.6.0/rules_nodejs-1.6.0.tar.gz] to C:/users/1030/_bazel_1030/xiuovwtk/external/build_bazel_rules_nodejs/rules_nodejs-1.6.0.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: no such package '@build_bazel_rules_nodejs//': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_nodejs/releases/download/1.6.0/rules_nodejs-1.6.0.tar.gz] to C:/users/1030/_bazel_103/xiuovwtk/external/build_bazel_rules_nodejs/rules_nodejs-1.6.0.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by alexeagle** [comment]
Hi, this isn't enough information to help you. It looks like you have some local network issue preventing Bazel from downloading. Are you on a corporate network that requires a proxy maybe? See https://docs.bazel.build/versions/master/external.html#using-proxies

**Comment by Taranbirbajwa** [comment]
Hi Alex,

Thanks for responding promptly.

I on a personal network not on any Corporate.I executed bazel sync command but still getting the same error.


INFO: Call stack for the definition of repository 'build_bazel_rules_nodejs' which is a http_archive (rule definition at C:/users/1037/_bazel_1030/xiuovwtk/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - E:/ccefrontend/WORKSPACE:21:1
 - E:/ccefrontend/WORKSPACE:21:1
WARNING: Download from https://github.com/bazelbuild/rules_nodejs/releases/download/1.6.0/rules_nodejs-1.6.0.tar.gz failed: class javax.net.ssl.SSLHandshakeException PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: An error occurred during the fetch of repository 'build_bazel_rules_nodejs':
   java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_nodejs/releases/download/1.6.0/rules_nodejs-1.6.0.tar.gz] to C:/users/1037/_bazel_103/xiuovwtk/external/build_bazel_rules_nodejs/rules_nodejs-1.6.0.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: no such package '@build_bazel_rules_nodejs//': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_nodejs/releases/download/1.6.0/rules_nodejs-1.6.0.tar.gz] to C:/users/103/_bazel_1037/xiuovwtk/external/build_bazel_rules_nodejs/rules_nodejs-1.6.0.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Loading: loading...

**Comment by alexeagle** [comment]
sorry, I don't think this is anything wrong with rules_nodejs. Looks like Bazel on your machine just can't download from https URLs at all. You can probably confirm by downloading something else and get the same error
