### ISSUE TITLE
Add an example for the "yarn_local" rule

### ISSUE THREAD

**Issue by lexor90** [bazelbuild/rules_nodejs#194]
Hi,
first off thanks for these bazel rules.

It seems to me that the current `yarn_local` rule is broken, or maybe it's just me using it the wrong way, so let me explain what I tried so far.

This is what the `WORKSPACE` looks like

    local_repository(
      name = "build_bazel_rules_nodejs",
      path = "third_party/nodejs/github.com/bazelbuild/rules_nodejs"
    )

    load("@build_bazel_rules_nodejs//:defs.bzl", "node_repositories", "yarn_local")

    yarn_local(
      name = "yarn", # if you change this name rules_nodejs won't use this dep
      path = __workspace_dir__ + "/third_party/nodejs/", # "/yarn" is appended in the rule
      package_json = ["//:tools/nodejs/package.json"]
    )

    node_repositories(package_json = ["//:tools/nodejs/package.json"], node_version = "8.11.1",)

Now, the checked-in version is the .tar.gz version of yarn, downloaded straight from GitHub releases (yarn v1.6.0).

Of course it's gonna fail, because running `bazel run @yarn//:yarn` searches for a file named "bin/yarn.js" and the ".tar.gz" release has the "yarn.js" file nested under "bin/" (defined inside of the repository_ctx.file("yarn.js", ...) rule in [node_repositories.bzl#L277](https://github.com/bazelbuild/rules_nodejs/blob/master/internal/node/node_repositories.bzl#L277) ). 

So, to overcome this directory structure, I downloaded the release "yarn-1.6.0.js" file, which bundles the whole thing in a single .js file (and properly renamed it), but then it continued to fail since [node_repositories.bzl#L375](https://github.com/bazelbuild/rules_nodejs/blob/master/internal/node/node_repositories.bzl#L375) defines the symlink as "bin/yarn", so the file would end up to be "bin/yarn/yarn.js", while it should be "bin/yarn.js".

My solution was then to patch the above [L375](https://github.com/bazelbuild/rules_nodejs/blob/master/internal/node/node_repositories.bzl#L375) this way:

    -   repository_ctx.symlink(repository_ctx.attr.path + "/yarn", "bin/yarn")
    +   repository_ctx.symlink(repository_ctx.attr.path + "/yarn", "bin/")

So now it works since my local yarn.js ends up in the proper location.

Is it expected that the vendored yarn is a single ".js" file or the rule should also support the .tar.gz? 
Is it me giving the wrong "path" to "yarn_local" or is this issue also happening to someone else?

Also, I find it a bit weird that the rule appends something to the path I'm defining as the location to yarn (I'm talking about the `repository_ctx.attr.path + "/yarn" `) since it forces a particular directory structure.

I'm thinking it's me doing something wrong, so I ask for an example, but should it be a bug feel free to rename this issue.

Thank you.

bazel version:
Build label: 0.9.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Dec 19 09:32:45 2017 (1513675965)
Build timestamp: 1513675965
Build timestamp as int: 1513675965

platform:
Mac OS X 10.12.6

**Comment by alexeagle** [comment]
/cc @gregmagolan who just changed this substantially yesterday.

the `yarn_local` rule was refactored and I bet this issue isn't reproducible. Could you try 
```
http_archive(
    name = "build_bazel_rules_nodejs",
    url = "https://github.com/bazelbuild/rules_nodejs/archive/153c10d0d131589bbcab6821fd325cb1f125a242.zip",
    strip_prefix = "rules_nodejs-153c10d0d131589bbcab6821fd325cb1f125a242",
)
```
and see if it solves the problem?

(Sorry for the churn that we introduced this rule and then removed it again...)

**Comment by gregmagolan** [comment]
@lexor90 `yarn_local()` has been removed at the latest commit (153c10d0d131589bbcab6821fd325cb1f125a242). The path to a local yarn is now configured in the `node_repositories()` function.

```
node_repositories(
   package_json = ["//:tools/nodejs/package.json"],
   node_version = "8.11.1",
   yarn_path = "path/to/yarn/base")
```

where `path/to/yarn/base` is the base of the extracted yarn package (for example https://github.com/yarnpkg/yarn/releases/download/v1.8.1/yarn-v1.8.1.tar.gz).

**Comment by alexeagle** [comment]
This is documented at https://github.com/bazelbuild/rules_nodejs/#installation-with-local-vendored-versions-of-nodejs-and-yarn so I think there is nothing we need to do here.
Please comment if that's wrong.
