### ISSUE TITLE
Is there a way to specify in nodejs_binary.data a scoped package?

### ISSUE THREAD

**Issue by kovkev** [bazelbuild/rules_nodejs#1943]
Is there a way to specify in nodejs_binary.data a scoped package?

I installed @google-cloud/translate but when I try to specify it in nodejs_binary.data (as "@npm//@google-cloud/translate"), I cannot build the target. I can't find any documentation on how to include scoped package dependencies.

**Comment by alexeagle** [comment]
"cannot build the target" could mean a bunch of things. We have that template for issues to help you remember what bits to include - an error message would be useful here because I can't tell if Bazel thought there was no such label, or if node is failing to resolve an import from it.

**Comment by kovkev** [comment]
Hi, I was wondering if there were examples anywhere online to validate that I was doing the right thing. 

The issue was that I installed the package in the wrong directory. Sorry about that!
