### ISSUE TITLE
JS outputs from ts_library does not include transitive dependencies

### ISSUE THREAD

**Issue by WesleyYue** [bazelbuild/rules_nodejs#1952]
I want to import a typescript module from one part of my repo at another part without having a bunch of "../.." in my imports to get back to the root folder of my bazel workspace. How can I setup absolute imports (relative to my workspace) for webpack? Do I need to set something in webpack.config.js? If so, what?

Minimal setup to illustrate the issue below:

_Folder structure_
```
folder1/
    moduleA.ts
    BUILD
folder2/
    moduleB.ts
    BUILD
WORKSPACE
```

_WORKSPACE_
```
workspace(
    name = "myworkspace",
)

...
```

*** **_moduleA.ts_** ***
```
// TS COMPILER CAN FIND THIS BUT WEBPACK CAN'T FIND THIS
import { thing } from "myworkspace/folder2/moduleB";  

...
```

_folder1/BUILD_
```
load("@npm_bazel_typescript//:index.bzl", "ts_library")
load("@npm//webpack-cli:index.bzl", webpack = "webpack_cli")

ts_library(
    name = "moduleA",
    srcs = ["moduleA.ts"],
    deps = [
        "//folder2:moduleB",
    ],
)

filegroup(
    name = "moduleA.js",
    srcs = [
        "moduleA",
    ],
    output_group = "es6_sources",
    visibility = ["//visibility:public"],
)

webpack(
    name = "bundle",
    outs = ["app.bundle.js"],
    args = [
        "$(locations :moduleA.js)",
        "--config",
        "$(execpath //:webpack.config.js)",
        "-o",
        "$@",
    ],
    data = [
        ":moduleA.js",
        "//:webpack.config.js",
        "@npm//:node_modules",
    ],
    visibility = ["//visibility:public"],
)
```

**Comment by marcus-sa** [comment]
https://github.com/bazelbuild/rules_nodejs/issues/1380
See the last comment.
This is rollup tho, but shouldn't differentiate with webpack when replacing import names.

**Comment by WesleyYue** [comment]
I don't think that solves my problem. I _want_ to refer to my files through absolute paths and not modules, and I especially would prefer to not have to setup a rule for every single file I want to import.

**Comment by WesleyYue** [comment]
It turns out the issue is that filegroup does not infer from moduleA that `//folder2:moduleB` needs to be included transitively. Adding `//folder2:moduleB` to the filegroup srcs fixed my issue. Is this a bug? Or is this intended behaviour?

**Comment by alexeagle** [comment]
I think maybe https://github.com/bazelbuild/rules_nodejs/pull/1040 solves this

**Comment by evahowe** [comment]
@WesleyYue - does #1040 solve this?

**Comment by WesleyYue** [comment]
I'm not familiar with Bazel internals so I don't understand exactly what was changed in https://github.com/bazelbuild/rules_nodejs/pull/1843, however, I tried migrating to 2.0.0-rc.0 which should include the PR but that didn't solve the issue. In fact, it made it so that my fix of adding all the deps to the filegroup() didn't even work anymore.

**Comment by WesleyYue** [comment]
Any update on this? As I mentioned above, the behaviour is now even more broken and my workaround no longer works.

**Comment by ajbouh** [comment]
I am also struggling with this for rollup

**Comment by WesleyYue** [comment]
@evahowe Could you replace the `Can Close?` tag to get dev attention on this issue again?

**Comment by WesleyYue** [comment]
@alexeagle Would you be able to revisit this issue?

**Comment by alexeagle** [comment]
Sorry, I don't have time today to repro the issue or dig into it. Also I haven't worked with `ts_library` lately so it would take some time to pull up the context, and I don't have many volunteer hours lately :(

**Comment by WesleyYue** [comment]
I revisited this issue and made a minimal repo to test this issue [here](https://github.com/WesleyYue/bazel-vue-webpack-typescript/tree/1952). (Note it is under the 1952 instead of main branch)

I was also able to get my workaround to work with the latest rules_nodejs fwiw. Not sure if I just made a mistake when I was testing previously or something updated in rules_nodejs to let my workaround work again. However, the original issue of dependencies not flowing through transitively still exists.

Run `bazel build //:bundle` to reproduce the error in the repo above.

**Comment by alexeagle** [comment]
Thanks for the repro, that helps a lot.

https://bazelbuild.github.io/rules_nodejs/Built-ins.html#JSEcmaScriptModuleInfo-sources is the intended mechanism to get transitive ESmodule-format JS files from the deps of a rule. The way we use `filegroup` to extract the `es6_sources` output group isn't meant to pass transitive files.

The `webpack-cli` rule you're using doesn't have a starlark implementation so it doesn't understand providers, it just gets the default outputs from the things in the `data` attribute.

So we can make this work with a little minimal adapter from `JSEcmaScriptModuleInfo` to `DefaultInfo` like this

`esmodule_sources.bzl`
```
"Adapt JSEcmaScriptModuleInfo provider from deps into DefaultInfo output"
load("@build_bazel_rules_nodejs//:providers.bzl", "JSEcmaScriptModuleInfo")

def _impl(ctx):
    return [DefaultInfo(files = depset(transitive = [x[JSEcmaScriptModuleInfo].sources for x in ctx.attr.deps]))]

esmodule_sources = rule(_impl, attrs = {"deps": attr.label_list()})
```

Now the webpack bundle succeeds by using this rule in place of the `filegroup` you have now:

```
esmodule_sources(
    name = "js",
    deps = ["moduleA_ts"],
)

webpack_cli(
    name = "bundle",
    outs = [
        "app.bundle.js",
    ],
    args = [
        "$(locations :js)",  # Entry point
    ...
    ],
    data = [
        ":js",
       ...
    ],
)
```

Of course this isn't very ergonomic and you might not want that bit of adapter code. This is one good reason that we should have a custom rule for `webpack_cli` so it can understand Bazel providers.
