### ISSUE TITLE
Workspace-local module-name resolution failing for nodejs_binary w/ ts_library outputs

### ISSUE THREAD

**Issue by nkeynes** [bazelbuild/rules_nodejs#1960]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: nodejs_binary with ts_library

### Is this a regression?

 I don't know.

### Description

Workspace-local module-name resolution fails when nodejs_binary is run with the output of ts_library, even though the ts_library() target compiles successfully. That is, when the entry-point JS imports another module by name, where that module is another ts_library dependency rather than an external NPM module.

## 🔬 Minimal Reproduction

https://github.com/nkeynes/bazel-js-testcase
$ bazel run :testws

## 🔥 Exception or Error

<pre><code>
Target //:testws up-to-date:
  bazel-bin/testws.sh
  bazel-bin/testws_loader.js
  bazel-bin/testws_require_patch.js
INFO: Elapsed time: 0.155s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Error: Cannot find module '@testws/a/src/Bar'. Please verify that the package.json has a valid "main" entry
    at Function.module.constructor._resolveFilename (/private/var/tmp/_bazel_nkeynes/76014e8f73985d10065a1d7619faccc2/execroot/dylan/bazel-out/darwin-fastbuild/bin/testws_require_patch.js:483:17)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at b/src/index.ts:1:1
    at /private/var/tmp/_bazel_nkeynes/76014e8f73985d10065a1d7619faccc2/execroot/dylan/bazel-out/darwin-fastbuild/bin/testws.sh.runfiles/dylan/b/src/index.js:3:17
    at Object.<anonymous> (/private/var/tmp/_bazel_nkeynes/76014e8f73985d10065a1d7619faccc2/execroot/dylan/bazel-out/darwin-fastbuild/bin/testws.sh.runfiles/dylan/b/src/index.js:9:3)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
    macOS 10.15.5
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.4.0
Build label: 3.2.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed May 27 17:58:08 2020 (1590602288)
Build timestamp: 1590602288
Build timestamp as int: 1590602288
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
    1.6.0
  </code>
</pre>

**Anything else relevant?**
N/A

**Comment by nkeynes** [comment]
Digging into this a little further, it looks like the problem may be related to the handling of module_root. The compiled b/src/index.js ends up requiring "@testws/a/src/Bar":
```
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    const Bar_1 = require("@testws/a/src/Bar");
    console.log(Bar_1.getBar());
```
 If this is manually corrected to "@testws/a/Bar", then the imports resolve correctly at runtime.

**Comment by evahowe** [comment]
@nkeynes does manually changing to "@testws/a/Bar" solve the problem then or does something else need doing?

**Comment by nkeynes** [comment]
Hi @evahowe, that's manually as in 'hacking up the JS files that are generated as the output of ts_library()' (which bazel will immediately overwrite next time I run it) - I don't have a way to make this work as part of the build without restructuring the tree to avoid using 'module_root' at all.

**Comment by evahowe** [comment]
@nkeynes - aha - that makes sense.  Thanks for getting back to me so I can make sure this gets in the right category.

**Comment by nkeynes** [comment]
I've updated the test case for 2.2.0, and confirmed that this issue is still present.
