### ISSUE TITLE
Missing types do not cause strict deps errors with worker enabled on ts_library

### ISSUE THREAD

**Issue by mattem** [bazelbuild/rules_nodejs#1961]
# 🐞 bug report

### Affected Rule
ts_library

### Is this a regression?

No

### Description

Running a build with ts_library in worker mode does not perform strict dep checking on `@types`.

## 🔬 Minimal Reproduction

https://github.com/JesseTatasciore/bazel-typescipt-types-issue-repro

`bazel build --strategy=TypeScriptCompile=worker //...` will build successfully
`bazel build --strategy=TypeScriptCompile=local //...` will fail on a strict deps issue, missing `@types/semver`

## 🔥 Exception or Error

<pre><code>
semver.ts:1:25 - error TS2307: [strictDeps] transitive dependency on external/npm/node_modules/@types/semver/index.d.ts not allowed. Please add the BUILD target to your rule's deps.

1 import * as semver from 'semver';
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
MacOS / Ubuntu
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: 56a03d98104be7cfa57d4bbdc03b4c7cea29a6c9
Build label: 3.2.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed May 27 17:58:08 2020 (1590602288)
Build timestamp: 1590602288
Build timestamp as int: 1590602288
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
1.6.1
  </code>
</pre>

**Anything else relevant?**
This is caused by `tc.getSymbolAtLocation` running undefined when running in worker mode.
https://github.com/bazelbuild/rules_typescript/blob/master/internal/tsc_wrapped/strict_deps.ts#L84

**Comment by vpanta** [comment]
Just to note on here, we have a similar case with a scoped pkg where we the dep is actually included (`@npm//@types/babel__core`) and yet in `local` strategy we still get a `[strict deps]` error saying we're missing it. It works without an issue in `worker` strategy.
