### ISSUE TITLE
Do Not Add 'List' Suffix to Repeated Fields in Generated Typescript Protos

### ISSUE THREAD

**Issue by rauljordan** [bazelbuild/rules_nodejs#1965]
# 🚀 feature request

### Relevant Rules

ts_proto_library

### Description

Hi all, currently I have this protobuf:

```
message FooResponse {
  repeated int foo = 1;
}
```
Which gets compiled into the following typescript definition using ts_proto_library
```js
export class FooResponse extends jspb.Message {
  getFooList(): Array<int>;
  setFooList(value: Array<int>): void;
  clearFooList(): void;
  addFoo(value?: int, index?: number): APIKey;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): FooResponse.AsObject;
  static toObject(includeInstance: boolean, msg: FooResponse): FooResponse.AsObject;
  static serializeBinaryToWriter(message: FooResponse, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): FooResponse;
  static deserializeBinaryFromReader(message: FooResponse, reader: jspb.BinaryReader): FooResponse;
}

export namespace FooResponse {
  export type AsObject = {
    fooList: Array<int>,
  }
}
```
I want to be able to use this type in my front-end, but the JSON data returned by my grpc-gateway looks like this:

```js
{ foo: [1, 2, 3] }
```
Instead of the expected
```js
{ fooList: [1, 2, 3] }
```
Any way around this? 

### Describe the solution you'd like

I want to be able to compile typescript protos that handle repeated types the same way the grpc-gateway handles repeated types:

ts_proto_library of 

```
message FooResponse {
  repeated int foo = 1;
}
```
outputs: 

```js
export namespace FooResponse {
  export type AsObject = {
    fooList: Array<int>,
  }
}
```
but I want
```js
export namespace FooResponse {
  export type AsObject = {
    foo: Array<int>,
  }
}
```

### Describe alternatives you've considered

Have tried opening up an issue in the grpc-gateway repo but they believe it is something that should be addressed by ts_proto_library: https://github.com/grpc-ecosystem/grpc-gateway/issues/1465

**Comment by bweston92** [comment]
Hi @rauljordan there is a request to make this optional. https://github.com/protocolbuffers/protobuf/issues/6773

There is a workaround by @majelbstoat in there linking to a Gist https://gist.github.com/majelbstoat/5f73f58a057123c8d46db66ebbaae987

**Comment by evahowe** [comment]
Thanks so much @bweston92!  

@rauljordan did that answer your question?

**Comment by thesayyn** [comment]
Alternatively, you can use this https://github.com/thesayyn/protoc-gen-ts plugin instead.

**Comment by mrmeku** [comment]
@rauljordan We are using the protoc plugin from https://github.com/grpc/grpc-web in order to generate our JS/TS code. I think that repo is a more appropriate place for this bug to be filed since we don't own the code generation portion of this feature

**Comment by Leo7654** [comment]
https://github.com/nestjs/nest/issues/4025
