### ISSUE TITLE
Unable to access .bin folder in node_modules after npm_install

### ISSUE THREAD

**Issue by bhanupradeep7** [bazelbuild/rules_nodejs#1970]
# 🐞 bug report

### Affected Rule

/node_modules/.bin/BUILD file no longer generated

### Is this a regression?
NA, this was a new feature. 

### Description

As mentioned in the link provided, https://github.com/bazelbuild/rules_nodejs/wiki#node_modulesbinbuild-file-no-longer-generated.
I've added manual_build_file_contents in WORKSPACE during npm_install
`   manual_build_file_contents = """
filegroup(
  name = "bin_files",
  srcs = glob(["node_modules/.bin/*"]),
)"""`. 
When I try to access `@npm//:bin_files/gulp`, it is throwing error as 
`ERROR: /Users/bn/xyz/BUILD.bazel:54:1: no such target '@npm//:bin_files/gulp': target 'bin_files/gulp' not declared in package '' defined by /Users/bn/build/002d84248db10ba9723789a90392069e/external/npm/BUILD.bazel and referenced by '//:build-xyz'`

## 🌍  Your Environment

**Operating System:**
MAC OS

**Output of `bazel version`:**
v3.1.0

**Rules_nodejs version:**
v1.6

**Comment by mattem** [comment]
A filegroup doesn't expose individual files in that way. 
The *_install rules generate `nodejs_binary` targets that can be used in a `genrule` `tools` attr, or use the generated macro. Without knowing the use case here it's tricky to suggest the right path:

```
load("@npm//gulp:index.bzl", "gulp")

gulp(
    name = "gulp",
    output_dir = 1,
    data = ["@npm//gulp"],
    args = ["--help"]
)
```

Will output the gulp help menu when built, so you could get it to run a task or similar.

**Comment by bhanupradeep7** [comment]
This worked for me.
Thank you
