### ISSUE TITLE
Error: Internal error!  Helm + Tilt

### ISSUE THREAD

**Issue by smhmayboudi** [bazelbuild/rules_nodejs#1976]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 
nodejs_image

### Is this a regression?
Yes

### Description
I change only to rc (rules_nodejs-2.0.0-rc.0) and update my package (@bazel/typescript 2.0.0-rc.0).

## 🔬 Minimal Reproduction

https://github.com/tilt-dev/bazel_example
Instead of using bazel_k8s, I used helm in tiltfile.

## 🔥 Exception or Error

<pre><code>
local: bazelisk query 'filter("^//", buildfiles(deps(set(//apps/YYY/src:YYY_nodejs_image))))' --order_output=no
 → Loading: 0 packages loaded
 → Loading: 0 packages loaded
 → Loading: 0 packages loaded
 → Loading: 0 packages loaded
 → Loading: 0 packages loaded
 → Loading: 0 packages loaded
 → Loading: 0 packages loaded
 → Loading: 0 packages loaded
 → Loading: 0 packages loaded
 → Loading: 0 packages loaded
 → Loading: 0 packages loaded
 → ERROR: Failed to load Starlark extension '@npm_bazel_typescript//:index.bzl'.
 → Cycle in the workspace file detected. This indicates that a repository is used prior to being defined.
 → The following chain of repository dependencies lead to the missing definition.
 →  - @npm_bazel_typescript
 → This could either mean you have to add the '@npm_bazel_typescript' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.
 → ERROR: cycles detected during target parsing
 → Loading: 0 packages loaded
 → Loading: 0 packages loaded
Successfully loaded Tiltfile (17.878255833s)
Traceback (most recent call last):
  /Users/smhmayboudi/Developer/XXX-api/Tiltfile:78:12: in <toplevel>
  /Users/smhmayboudi/Developer/XXX-api/Tiltfile:65:25: in bazel_build
  <builtin>: in local
Error: command ["sh" "-c" "bazelisk query 'filter(\"^//\", buildfiles(deps(set(//apps/YYY/src:YYY_nodejs_image))))' --order_output=no"] failed.
error: exit status 7
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Software:
    System Software Overview:
      System Version: macOS 10.15.5 (19F101)
      Kernel Version: Darwin 19.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 16 days 10:22
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.5.0
Starting local Bazel server and connecting to it...
Build label: 3.3.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jun 17 12:59:56 2020 (1592398796)
Build timestamp: 1592398796
Build timestamp as int: 1592398796
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
rules_nodejs-2.0.0-rc.0
@bazel/typescript 2.0.0-rc.0
  </code>
</pre>

**Anything else relevant?**

**Comment by mattem** [comment]
There are a number of breaking changes that came with 2.0.0, from the output posted it looks like perhaps all the changes haven't been made, loads from `@npm_bazel_typescript` should be `@npm//@bazel/typescript`.

See the [release notes](https://github.com/bazelbuild/rules_nodejs/releases/tag/2.0.0-rc.0) for the full instructions, there are [some extra notes](https://github.com/bazelbuild/rules_nodejs/wiki#migrating-to-20) on the wiki too.

If there's something we've missed, let us know

**Comment by smhmayboudi** [comment]
Thanks for your great help.
