### ISSUE TITLE
Provide an output group for `ts_project` that contains `DeclarationInfo`

### ISSUE THREAD

**Issue by longlho** [bazelbuild/rules_nodejs#1978]
# 🚀 feature request

### Relevant Rules

ts_project

### Description

Right now there are tooling like `@microsoft/api-extractor` that bundles type definitions into a single `d.ts` (kinda like rollup for `d.ts`). However, `ts_project` doesn't not export its type definitions so it'd be great if it does that either by default or an output group.

I'm probably looking for type definitions to be included in `DefaultInfo` otherwise I don't think `npm_package_bin` can read it as `data`?

### Describe the solution you'd like

It'd be great if it does that either by default or an output group

### Describe alternatives you've considered

Custom rules to extract `DeclarationInfo` out of `ts_project`

**Comment by alexeagle** [comment]
Great point, you shouldn't have to write a rule just to consume the DeclarationInfo. filegroup with output groups is the simple API for a consumer to select the outputs they want. This should be easy so maybe a good training issue for anyone who wants to contribute - I can give some pointers where to look.

**Comment by longlho** [comment]
I can put in a PR :)
