### ISSUE TITLE
No 'bazel-out' folder found in path '/app/apps/XXX/src/YYY_nodejs_binary.runfiles/XXX'!

### ISSUE THREAD

**Issue by smhmayboudi** [bazelbuild/rules_nodejs#1979]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: rules_nodejs

### Is this a regression?

 NO

### Description

 A clear and concise description of the problem...
I tried to run one of the microservices over nestjs framework with help of tilt and bezel. I think I have a problem with layers.

## 🔬 Minimal Reproduction

<pre><code>
load("@build_bazel_rules_nodejs//:index.bzl", "nodejs_binary")
load("@io_bazel_rules_docker//container:container.bzl", "container_push")
load("@io_bazel_rules_docker//nodejs:image.bzl", "nodejs_image")
load("@XXX//:apps/common/bazel/jest_test/index.bzl", "jest_test")
load("@npm//@bazel/typescript:index.bzl", "ts_config", "ts_library")

package(default_visibility = ["//visibility:public"])

ts_config(
    name = "YYY_ts_config",
    src = "//apps/YYY:tsconfig.app.json",
    deps = [
        "//:tsconfig.json",
    ],
)

ts_library(
    name = "YYY_ts_library",
    srcs = glob(
        ["*.ts"],
        exclude = ["*spec.ts"],
    ),
    module_name = "@XXX/YYY",
    runtime = "nodejs",
    tsconfig = ":YYY_ts_config",
    deps = [
        ...
        "@npm//source-map-support",
    ],
)

ts_library(
    name = "YYY_test_ts_library",
    srcs = glob(["*spec.ts"]),
    module_name = "@XXX/YYY",
    runtime = "nodejs",
    tsconfig = ":YYY_ts_config",
    deps = [
        ":YYY_ts_library",
        "@npm//@nestjs/testing",
    ],
)

nodejs_binary(
    name = "YYY_nodejs_binary",
    data = [
        ":YYY_ts_library",
    ],
    entry_point = ":main",
    templated_args = [
        "--nobazel_patch_module_resolver",
        "--node_options=--require=source-map-support/register",
    ],
)

jest_test(
    name = "YYY_jest_test",
    srcs = glob(["*spec.ts"]),
    jest_config = "//:jest.config.json",
    deps = [
        ":YYY_test_ts_library",
        "@npm//@types/jest",
    ],
)

nodejs_image(
    name = "YYY_nodejs_image",
    binary = ":YYY_nodejs_binary",
)

container_push(
    name = "YYY_container_push",
    format = "Docker",
    image = ":YYY_nodejs_image",
    registry = "localhost:5000",
    repository = "XXX_YYY",
    tag = "{EXPECTED_REF}",
)
</code></pre>

## 🔥 Exception or Error

<pre><code>
Error:
No 'bazel-out' folder found in path '/app/apps/YYY/src/YYY_nodejs_binary.runfiles/XXX'!

  at panic (/app/apps/YYY/src/YYY_nodejs_binary.runfiles/build_bazel_rules_nodejs/internal/linker/index.js:23:11)
  at /app/apps/YYY/src/YYY_nodejs_binary.runfiles/build_bazel_rules_nodejs/internal/linker/index.js:79:13
  at Generator.next (<anonymous>)
  at /app/apps/YYY/src/YYY_nodejs_binary.runfiles/build_bazel_rules_nodejs/internal/linker/index.js:8:71
  at new Promise (<anonymous>)
  at __awaiter (/app/apps/YYY/src/YYY_nodejs_binary.runfiles/build_bazel_rules_nodejs/internal/linker/index.js:4:12)
  at resolveRoot (/app/apps/YYY/src/YYY_nodejs_binary.runfiles/build_bazel_rules_nodejs/internal/linker/index.js:73:12)
  at /app/apps/YYY/src/YYY_nodejs_binary.runfiles/build_bazel_rules_nodejs/internal/linker/index.js:340:31
  at Generator.next (<anonymous>)
  at /app/apps/YYY/src/YYY_nodejs_binary.runfiles/build_bazel_rules_nodejs/internal/linker/index.js:8:71
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Software:
    System Software Overview:
      System Version: macOS 10.15.5 (19F101)
      Kernel Version: Darwin 19.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.5.0
Starting local Bazel server and connecting to it...
Build label: 3.3.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jun 17 12:59:56 2020 (1592398796)
Build timestamp: 1592398796
Build timestamp as int: 1592398796
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
rules_nodejs-2.0.0-rc.0
@bazel/typescript 2.0.0-rc.0
  </code>
</pre>

**Anything else relevant?**

**Comment by smhmayboudi** [comment]
I list all of the files inside the docker container.
https://gist.github.com/smhmayboudi/e2a548294384ff55f5b8e4a670cc432d#file-nodejs_image_file_list

**Comment by smhmayboudi** [comment]
when you get a shell from docker and run pwd command:
`# pwd
/app/apps/YYY/src/YYY_nodejs_binary.runfiles/XXX`

Then I try to run bash
`# ./apps/YYY/src/YYY_nodejs_binary.sh
\ERROR: cannot find build_bazel_rules_nodejs/third_party/github.com/bazelbuild/bazel/tools/bash/runfiles/runfiles.bash`

I tried o find the runfiles.bash:
`# find / | grep runfiles.bash
/app/apps/YYY/src/YYY_nodejs_binary.runfiles/build_bazel_rules_nodejs/third_party/github.com/bazelbuild/bazel/tools/bash/runfiles/runfiles.bash`

**Comment by smhmayboudi** [comment]
Even I am reciving this message for build :
<pre><code>
ERROR: /Users/___________/Developer/XXX-api/apps/YYY/src/BUILD.bazel:49:11: Compiling TypeScript (devmode) //apps/YYY/src:YYY_test_ts_library failed (Exit 1)
error TS5055: Cannot write file '/private/var/tmp/_bazel____________/ae7401e5b0bf3160fe284ae16f776623/execroot/XXX/bazel-out/darwin-fastbuild/bin/apps/YYY/src/YYY.config.d.ts' because it would overwrite input file.
  Adding a tsconfig.json file will help organize projects that contain both TypeScript and JavaScript files. Learn more at https://aka.ms/tsconfig.
error TS5055: Cannot write file '/private/var/tmp/_bazel____________/ae7401e5b0bf3160fe284ae16f776623/execroot/XXX/bazel-out/darwin-fastbuild/bin/apps/YYY/src/YYY.config.service.d.ts' because it would overwrite input file.
  Adding a tsconfig.json file will help organize projects that contain both TypeScript and JavaScript files. Learn more at https://aka.ms/tsconfig.
error TS5055: Cannot write file '/private/var/tmp/_bazel____________/ae7401e5b0bf3160fe284ae16f776623/execroot/XXX/bazel-out/darwin-fastbuild/bin/apps/YYY/src/YYY.controller.d.ts' because it would overwrite input file.
  Adding a tsconfig.json file will help organize projects that contain both TypeScript and JavaScript files. Learn more at https://aka.ms/tsconfig.
error TS5055: Cannot write file '/private/var/tmp/_bazel____________/ae7401e5b0bf3160fe284ae16f776623/execroot/XXX/bazel-out/darwin-fastbuild/bin/apps/YYY/src/YYY.events.gateway.d.ts' because it would overwrite input file.
  Adding a tsconfig.json file will help organize projects that contain both TypeScript and JavaScript files. Learn more at https://aka.ms/tsconfig.
error TS5055: Cannot write file '/private/var/tmp/_bazel____________/ae7401e5b0bf3160fe284ae16f776623/execroot/XXX/bazel-out/darwin-fastbuild/bin/apps/YYY/src/YYY.module.d.ts' because it would overwrite input file.
  Adding a tsconfig.json file will help organize projects that contain both TypeScript and JavaScript files. Learn more at https://aka.ms/tsconfig.
error TS5055: Cannot write file '/private/var/tmp/_bazel____________/ae7401e5b0bf3160fe284ae16f776623/execroot/XXX/bazel-out/darwin-fastbuild/bin/apps/YYY/src/YYY.service.d.ts' because it would overwrite input file.
  Adding a tsconfig.json file will help organize projects that contain both TypeScript and JavaScript files. Learn more at https://aka.ms/tsconfig.
error TS5055: Cannot write file '/private/var/tmp/_bazel____________/ae7401e5b0bf3160fe284ae16f776623/execroot/XXX/bazel-out/darwin-fastbuild/bin/apps/YYY/src/main.d.ts' because it would overwrite input file.
  Adding a tsconfig.json file will help organize projects that contain both TypeScript and JavaScript files. Learn more at https://aka.ms/tsconfig.
apps/YYY/src/YYY.config.service.spec.ts:1:37 - error TS2307: [strictDeps] transitive dependency on apps/YYY/src/YYY.config.service.ts not allowed. Please add the BUILD target to your rule's deps.

1 import { YYYConfigService } from "./YYY.config.service";
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~
apps/YYY/src/YYY.config.spec.ts:1:20 - error TS2307: [strictDeps] transitive dependency on apps/YYY/src/YYY.config.ts not allowed. Please add the BUILD target to your rule's deps.

1 import config from "./YYY.config";
                     ~~~~~~~~~~~~~~~~~
apps/YYY/src/YYY.controller.spec.ts:3:34 - error TS2307: [strictDeps] transitive dependency on apps/YYY/src/YYY.controller.ts not allowed. Please add the BUILD target to your rule's deps.

3 import { YYYController } from "./YYY.controller";
                                   ~~~~~~~~~~~~~~~~~~~~~
apps/YYY/src/YYY.controller.spec.ts:4:31 - error TS2307: [strictDeps] transitive dependency on apps/YYY/src/YYY.service.ts not allowed. Please add the BUILD target to your rule's deps.

4 import { YYYService } from "./YYY.service";
                                ~~~~~~~~~~~~~~~~~~
apps/YYY/src/YYY.events.gateway.spec.ts:3:37 - error TS2307: [strictDeps] transitive dependency on apps/YYY/src/YYY.events.gateway.ts not allowed. Please add the BUILD target to your rule's deps.

3 import { YYYEventsGateway } from "./YYY.events.gateway";
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~
apps/YYY/src/YYY.service.spec.ts:3:31 - error TS2307: [strictDeps] transitive dependency on apps/YYY/src/YYY.service.ts not allowed. Please add the BUILD target to your rule's deps.

3 import { YYYService } from "./YYY.service";
                                ~~~~~~~~~~~~~~~~~~

ERROR: /Users/___________/Developer/XXX-api/apps/YYY/src/BUILD.bazel:77:10 Compiling TypeScript (devmode) //apps/YYY/src:YYY_test_ts_library failed (Exit 1)
<code></pre>

**Comment by smhmayboudi** [comment]
I solved this problem:

<pre><code>
load("@build_bazel_rules_nodejs//:index.bzl", "nodejs_binary")
load("@io_bazel_rules_docker//container:container.bzl", "container_push")
load("@io_bazel_rules_docker//nodejs:image.bzl", "nodejs_image")
load("@XXX//:apps/common/bazel/jest_test/index.bzl", "jest_test")
load("@npm//@bazel/typescript:index.bzl", "ts_config", "ts_library")

package(default_visibility = ["//visibility:public"])

ts_config(
    name = "YYY_ts_config",
    src = "//apps/YYY:tsconfig.app.json",
    deps = [
        "//:tsconfig.json",
    ],
)

ts_library(
    name = "YYY_ts_library",
    srcs = glob(
        ["*.ts"],
        exclude = ["*spec.ts"],
    ),
    module_name = "@XXX/YYY",
    runtime = "nodejs",
    tsconfig = ":YYY_ts_config",
    deps = [
        "//libs/apm/src:apm_ts_library",
        "//libs/common/src:common_ts_library",
        "//libs/prom/src:prom_ts_library",
        "//libs/sentry/src:sentry_ts_library",
        "@npm//@nestjs/common",
        "@npm//@nestjs/config",
        "@npm//@nestjs/core",
        "@npm//@nestjs/microservices",
        "@npm//@nestjs/platform-express",
        "@npm//@nestjs/platform-socket.io",
        "@npm//@nestjs/websockets",
        "@npm//@types/ms",
        "@npm//@types/node",
        "@npm//@types/socket.io",
        "@npm//@types/source-map-support",
        "@npm//ms",
        "@npm//redis",
        "@npm//reflect-metadata",
        "@npm//source-map-support",
        "@npm//tslib",
    ],
)

nodejs_binary(
    name = "YYY_nodejs_binary",
    data = [
        ":YYY_ts_library",
    ],
    entry_point = ":main",
    templated_args = [
        "--nobazel_patch_module_resolver",
        "--node_options=--require=source-map-support/register",
    ],
)

jest_test(
    name = "YYY_jest_test",
    srcs = glob(["*spec.ts"]),
    jest_config = "//:jest.config.json",
    deps = [
        ":YYY_ts_library",
        "@npm//@nestjs/testing",
        "@npm//@types/jest",
        "@npm//ts-jest",
    ],
)

nodejs_image(
    name = "YYY_nodejs_image",
    binary = ":YYY_nodejs_binary",
)

container_push(
    name = "YYY_container_push",
    format = "Docker",
    image = ":YYY_nodejs_image",
    registry = "localhost:5000",
    repository = "XXX_YYY",
    tag = "{EXPECTED_REF}",
)
<code></pre>

**Comment by alexeagle** [comment]
I think this is the same problem as number 1977 so we at least need to add some better error messaging there since multiple people are seeing it
