### ISSUE TITLE
json files are not declared as output in `ts_project`

### ISSUE THREAD

**Issue by longlho** [bazelbuild/rules_nodejs#1988]
# 🚀 feature request

### Relevant Rules

ts_project
### Description

 A clear and concise description of the problem or missing capability...
Followup from https://github.com/bazelbuild/rules_nodejs/pull/1981

If outdir is specified, the JSON files get copied to it so ideally it should be part of js_outs (or its own json_outs).

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by alexeagle** [comment]
I'm a little confused, in the title you say they are not copied, but in the description you say they are copied.

**Comment by longlho** [comment]
Sorry I mean when run with tsc they are copied but it’s not part of the
DefaultInfo output
