### ISSUE TITLE
`pkg_npm` doesn't seem to support `declare_directory` input

### ISSUE THREAD

**Issue by longlho** [bazelbuild/rules_nodejs#1989]
I have a script that uses `npm_package_bin` to generate an output directory but specifying that as `deps` in `pkg_npm` doesn't seem to get it packaged.

**Comment by longlho** [comment]
Turns out empty folder got ignored by `npm pack`. I've added a test for it

**Comment by alexeagle** [comment]
So just to clarify, there wasn't a bug nor missing feature in rules_nodejs, you've added a test to demonstrate that it was already Working as Intended.
