### ISSUE TITLE
Resolving module path failed in postinstall

### ISSUE THREAD

**Issue by liuheng-pony** [bazelbuild/rules_nodejs#1996]
# 🐞 bug report

### Affected Rule

build_bazel_rules_nodejs: 1.7.0

### Description

We are using npm package `@danmarshall/deckgl-typings` in project. The package is calling a symlink in `.bin` directory
./node_modules/.bin/indefinitely-typed -> node_modules/indefinitely-typed/bin/cli2.js
```
#!/usr/bin/env node
require("../dist/index");
```

But the path could not be resolved by `npm_install`.
Is anything I'm not doing right? or whether could I solve it by some workaround? 

## 🔬 Minimal Reproduction
1. `npm i @danmarshall/deckgl-typings -D` in any `npm_install` project
2. clear the `node_modules`
3. try to bazel build or run anything to trigger the `npm_install`

## 🔥 Exception or Error

<pre><code>
ERROR: An error occurred during the fetch of repository 'npm':
   npm_install failed: 
> @danmarshall/deckgl-typings@4.1.11 postinstall /home/liuheng/deckgl-typing-repro/node_modules/@danmarshall/deckgl-typings
> indefinitely-typed --folder deck.gl__aggregation-layers --folder deck.gl__core --folder deck.gl__layers --folder deck.gl__google-maps --folder deck.gl__json --folder deck.gl__mapbox --folder deck.gl__mesh-layers --folder deck.gl__geo-layers --folder deck.gl__extensions --folder deck.gl__react --folder deck.gl --folder luma.gl__webgl-state-tracker --folder luma.gl__webgl --folder luma.gl__shadertools --folder luma.gl__core --folder math.gl

 (internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module '../dist/index'
Require stack:
- /home/liuheng/deckgl-typing-repro/node_modules/.bin/indefinitely-typed
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/liuheng/deckgl-typing-repro/node_modules/.bin/indefinitely-typed:2:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/liuheng/deckgl-typing-repro/node_modules/.bin/indefinitely-typed'
  ]
}
npm WARN deckgl-typing-repro@1.0.0 No description
npm WARN deckgl-typing-repro@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @danmarshall/deckgl-typings@4.1.11 postinstall: `indefinitely-typed --folder deck.gl__aggregation-layers --folder deck.gl__core --folder deck.gl__layers --folder deck.gl__google-maps --folder deck.gl__json --folder deck.gl__mapbox --folder deck.gl__mesh-layers --folder deck.gl__geo-layers --folder deck.gl__extensions --folder deck.gl__react --folder deck.gl --folder luma.gl__webgl-state-tracker --folder luma.gl__webgl --folder luma.gl__shadertools --folder luma.gl__core --folder math.gl`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @danmarshall/deckgl-typings@4.1.11 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/liuheng/.npm/_logs/2020-07-02T04_29_25_132Z-debug.log
)
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 16.04
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 2.2.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Mar 3 09:26:12 2020 (1583227572)
Build timestamp: 1583227572
Build timestamp as int: 1583227572
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
build_bazel_rules_nodejs: 1.7.0
  </code>
</pre>

Thanks.

**Comment by lukasholzer** [comment]
my workaround is that i have a postinstall script where I execute

```javascript
// postinstall.js

const { execSync } = require('child_process');
execSync(`node ${require.resolve('patch-package')}`);

//..other stuff like running ngcc

```

**Comment by liuheng-pony** [comment]
> my workaround is that I have a postinstall script where I execute
> 
> ```js
> // postinstall.js
> 
> const { execSync } = require('child_process');
> execSync(`node ${require.resolve('patch-package')}`);
> 
> //..other stuff like running ngcc
> ```
> 
> or run it directly inside the postinstall with `"postinstall": "node ./node_modules/patch-package/dist/index.js"` but this won't work on windows. that's the reason for the `require.resolve`

Thanks for your advice, Lukas. But my problem is , the `postinstall` is from my dependency package. How could I deal with them? If I ignore them, how could I run that script?

**Comment by lukasholzer** [comment]
> > my workaround is that I have a postinstall script where I execute
> > ```js
> > // postinstall.js
> > 
> > const { execSync } = require('child_process');
> > execSync(`node ${require.resolve('patch-package')}`);
> > 
> > //..other stuff like running ngcc
> > ```
> > 
> > 
> > or run it directly inside the postinstall with `"postinstall": "node ./node_modules/patch-package/dist/index.js"` but this won't work on windows. that's the reason for the `require.resolve`
> 
> Thanks for your advice, Lukas. But my problem is , the `postinstall` is from my dependency package. How could I deal with them? If I ignore them, how could I run that script?

Can you be a little bit more specific maybe or share a link? Is it a peerDependency? you can run `npm ci --ignore-scripts` to ignore postinstall scripts and then run it manually for example.

**Comment by liuheng-pony** [comment]
> > > my workaround is that I have a postinstall script where I execute
> > > ```js
> > > // postinstall.js
> > > 
> > > const { execSync } = require('child_process');
> > > execSync(`node ${require.resolve('patch-package')}`);
> > > 
> > > //..other stuff like running ngcc
> > > ```
> > > 
> > > 
> > > or run it directly inside the postinstall with `"postinstall": "node ./node_modules/patch-package/dist/index.js"` but this won't work on windows. that's the reason for the `require.resolve`
> > 
> > 
> > Thanks for your advice, Lukas. But my problem is , the `postinstall` is from my dependency package. How could I deal with them? If I ignore them, how could I run that script?
> 
> Can you be a little bit more specific maybe or share a link? Is it a peerDependency? you can run `npm ci --ignore-scripts` to ignore postinstall scripts and then run it manually for example.

`npm i @danmarshall/deckgl-typings -D`  this package made the error. install it to any bazel-managed npm project, you will encounter it. 
I understand what you mean, but how could I ask the Bazel-managed dependence to do that?

**Comment by whimzyLive** [comment]
also getting this with pretty much with all packages

**Comment by a-ignatov-parc** [comment]
@liuheng-pony have you tried using bazel managed `npm`? You can use it by running `@npm//:npm`. 

For example:
```bzl
bazel run @npm//:npm -- i @danmarshall/deckgl-typings -D
```

Also, it worth trying to switch to `yarn` since `npm` has an [additional step](https://github.com/bazelbuild/rules_nodejs/blob/stable/internal/npm_install/npm_install.bzl#L272) in the pipeline that might cause problems.

**Comment by parisholley** [comment]
i just got hit with this due to a transitive dependency (npm-run-all) doing the same thing:

https://github.com/mysticatea/npm-run-all/issues/118

**Comment by parisholley** [comment]
I was able to work around this by setting `preserve_symlinks = False` on my `node_repositories`. Not sure yet what else it will break as I haven't tested the rest of my workspace, but it is start.
