### ISSUE TITLE
Make `stripInternal` compilerOption in `ts_library` configurable.

### ISSUE THREAD

**Issue by lukasholzer** [bazelbuild/rules_nodejs#2000]
# 🚀 feature request

### Relevant Rules

The `ts_library` rule from `@bazel/typescript`

### Description

Currently, the `@bazel/typescript` has a hardcoded default for the `stripInternal` property that is set to `True`. 

https://github.com/bazelbuild/rules_typescript/blob/master/internal/common/tsconfig.bzl#L276

### Describe the solution you'd like

Not Overriding the property if it is set to a different value in a `tsconfig.json` or making it configurable through the `ts_library` rule.

### Describe alternatives you've considered

The workaround is to apply a patch in the repository (via `patch-package`) that inverts it but I consider this method as ugly.

```patch
diff --git a/node_modules/@bazel/typescript/internal/common/tsconfig.bzl b/node_modules/@bazel/typescript/internal/common/tsconfig.bzl
index fc1d6f7..9af2e92 100755
--- a/node_modules/@bazel/typescript/internal/common/tsconfig.bzl
+++ b/node_modules/@bazel/typescript/internal/common/tsconfig.bzl
@@ -264,7 +264,7 @@ def create_tsconfig(
         # We don't support this compiler option (See github #32), so
         # always emit declaration files in the same location as outDir.
         "declarationDir": "/".join([workspace_path, outdir_path]),
-        "stripInternal": True,
+        "stripInternal": False,
 
         # Embed source maps and sources in .js outputs
         "inlineSourceMap": True,

```

**Comment by alexeagle** [comment]
To help understand the severity, what bad thing happens in your app when `stripInternal` is enabled?

**Comment by literalpie** [comment]
For us, it's causing issues in our project where we use `@internal` to denote things that should not be documented. While trying bazel in this project, I got "Cannot resolve type entity i2.MyComponentName to symbol" errors.

**Comment by lukasholzer** [comment]
Yea in our library we annotate all not public facing methods, properties with `@internal` https://github.com/dynatrace-oss/barista/blob/master/libs/barista-components/chart/src/chart.ts#L345

This indicates for our consumers that the method, property function is not part of the public API even though it might have to be exported for Angular to work. 

When we are consuming the DeclarationInfo with Bazel from an already compiled library in another library we maybe need those internal but they aren't represented there as they got stripped by the typescript compiler.

(We are using our own libraries) For example, the chart is using the core library.

**Comment by alexeagle** [comment]
rules_typescript is now part of this repo in the 3.x branch so changes to `ts_library` are now feasible and don't have to be synced with google internal

**Comment by lukasholzer** [comment]
I guess we can tackle this issue now :)

**Comment by mattem** [comment]
Yeah, there was a similar change that @jbedard mentioned about passing down the `angularCompilerOptions` correctly, or at least the ones that `ts_library` could support.

**Comment by jbedard** [comment]
Yeah I'd like to do that, for both `angularCompilerOptions` as well as any other tsconfig options that `ts_library` doesn't strictly need to be in control of.

**Comment by alexeagle** [comment]
accepting PRs :) 
I suspect none of the core maintainers have time for this, as we're trying to get `ts_project` to a state where `ts_library` could be officially deprecated (and are doing heavy changes in the plumbing of package fetch/install/link)
