### ISSUE TITLE
Ability to run a nodejs_binary as a data dep under a test

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#2002]
The linker sets a variable `startCwd` with this comment
```
// pwd=execroot/my_wksp when under execroot or pwd=runfiles/my_wksp
  // when under runfiles.
```
However if the user runs a nodejs_binary themselves under some other working directory, we error with a noisy panic like

```
  Error:
  No 'bazel-out' folder found in path '/private/var/tmp/_bazel_alex.eagle/ea778b5c9af68d802a0dccaac8e08d8a/execroot/gerrit/_tmp/c82e2073ab2f5e1c5fbd8ffbfcb7b74d'!

    at panic (/private/var/tmp/_bazel_alex.eagle/ea778b5c9af68d802a0dccaac8e08d8a/external/build_bazel_rules_nodejs/internal/linker/index.js:23:11)

 Error: Internal error! Please run again with
   --define=VERBOSE_LOG=1
and file an issue: https://github.com/bazelbuild/rules_nodejs/issues/new?template=bug_report.md
Include as much of the build output as you can without disclosing anything confidential.
```

Since the linker is enabled in more places by our 2.0 release, this appears as a new bug for them.
Observed in 
https://github.com/bazelbuild/rules_nodejs/issues/1977

At least the error message could be better - we can probably calculate from the environment what working directory Bazel would have used and report that you can disable the linker. Maybe all linker panics should include the workaround is to disable the linker with `--nobazel_run_linker`

**Comment by alexeagle** [comment]
Note, we have a similar problem where Cypress wants to exec some random bazel-built binary as a data dep

**Comment by samschlegel** [comment]
Also ran into this when using `bazel run` with `--run_under` to change the directory.
```bash
bazel run --run_under="cd $PWD && " <bin_target>
```
In this case `--nobazel_run_linker` fixed the issue, however the way we actually want to use this is in a subtool, so we also run into the issues in #1910

**Comment by gregmagolan** [comment]
Picking this up today. There is a test in angular/angular that hits this as well.
