### ISSUE TITLE
Migrating to 2.0 wiki typo

### ISSUE THREAD

**Issue by WesleyYue** [bazelbuild/rules_nodejs#2007]
In the 2.0 migration wiki (https://github.com/bazelbuild/rules_nodejs/wiki#migrating-to-20), the heading for migrating @npm_bazel_ statements is incorrect and does not reflect the buildozer rule.

It should say `... @npm_bazel_* to @npm//@bazel/*`. Note the double slash after@npm.

**Comment by mattem** [comment]
Thanks! Fix on the wiki now
