### ISSUE TITLE
How to use Protocol Buffers from JavaScript

### ISSUE THREAD

**Issue by prestonvanloon** [bazelbuild/rules_nodejs#201]
Any plans for this? I haven't been able to find a build rule from bazel that provides static code generation for nodejs with protobufs.

https://github.com/grpc/grpc/tree/v1.11.x/examples/node/static_codegen

I have seen the example from https://github.com/pubref/rules_protobuf, but that depends on a different set of rules for node.

**Comment by alexeagle** [comment]
See the comment on your linked issue - there is `ts_proto_library` now, does this do what you need?

If not can you help me understand what you'd expect a `node_proto_library` to do? Just to yield generated JS files containing client-side library for working with protos?

I think it would be useful for the grpc team to own more of the TypeScript story...

Also, I think we are juggling a few different related issues between here and rules_typescript - it would be easier for me to follow the thread if you could close some as duplicates...

**Comment by prestonvanloon** [comment]
Sorry about that. I did open a few since I was trying to build a nodejs service that used grpc and was written in typescript. 

`ts_proto_library` might allow me to use the proto for typescript libraries, but I expect there is still a use case for javascript libraries to want to depend on the generated JS for protobufs.

This issue is opened to support the latter case of js libraries.

**Comment by alexeagle** [comment]
One possibility is just to use `ts_proto_library` and throw away the `.d.ts` outputs.
Another option is to hook up the same dcodeio/protobuf.js library in this repo, but only wire up the .js outputs.
Or maybe we should just wrap the grpc library as a bazel rule.

I think @mrmeku is the lead on this.
