### ISSUE TITLE
node_modules directory junction in execroot on Windows causes race condition. Other OSs unaffected.

### ISSUE THREAD

**Issue by rickwebiii** [bazelbuild/rules_nodejs#2014]
# 🐞 bug report
On Windows, the node_modules directory junction in execroot is a race condition and causes random build failures if 2 targets using different yarn_install targets run concurrently.

### Affected Rule
It's a subtly interplay between nodejs_binary and multiple yarn_install rules in the same WORKSPACE.

I'm using the automatically generated webpack_cli rules generated from 2 different yarn_installs that are actually just simple wrappers around nodejs_binary rules.

### Is this a regression?
Probably not.

### Description
My build has 2 yarn_installs pointing to 2 different package.json and yarn.lock files. There are a set of rules that consume node_modules from one yarn_install and a different set for the other. If targets from each set run concurrently, I get build failures due to missing node modules. The reason is that the node_modules directory junction in exec root is pointing to the other yarn_install's node_modules.

## 🔬 Minimal Reproduction
I don't know that you can make a minimal repro for this, since you need fairly long-running nodejs_binary rules using node_modules from different yarn_installs running concurrently. In our case, this is 2 webpack jobs that each take over a minute.

## 🔥 Exception or Error
Various, but always related to missing npm packages when running webpack. The errors are packages needed by the code, not for webpack itself.

## 🌍  Your Environment
**Operating System:**
This issue only repos on Windows, which doesn't feature sandboxing without a bunch of extra steps. The issue doesn't repro on Mac or Linux.

**Output of `bazel version`:**
3.3.0

**Rules_nodejs version:**
1.7.0

**Anything else relevant?**
You might be able to eliminate this issue by coalescing all your dependencies into a single package.json and having only a single yarn_install target. This would mean the directory junction is always being updated to point to the same external/node_modules directory and something something NTFS atomicity might mean regardless of the target that set the junction, concurrently running targets can still access the same set of node_modules.

**Comment by alexeagle** [comment]
oh boy, this is tricky. @devversion is the last person to understand the race conditions of linker on Windows - any guidance Paul?

**Comment by rickwebiii** [comment]
I thought a little more about it and a quick fix to ensure correctness (with major drawbacks) would be if the target is running as local without sandboxing, acquire a named mutex. This will serialize all nodejs targets, but prevent failures.

You can probably be a little more clever and use a named read/write lock. If the directory junction in execroot is already pointing at the node_modules directory you want, increment the read/write lock. If not, you have to wait for the lock to hit zero, at which point you acquire the lock, update the directory junction, and then execute. This way, targets that use the same node_modules can all run in parallel, but those that want to use a different one have to wait.

Another possible approach would be to make a junction named to something unique to the yarn_install's target name and set the NODE_PATH environment variable to point to the unique name in the nodejs_binary rule. This way, you can have multiple directory junctions in the exec root at the same time without interfering with one another. I suspect there will be weird edge cases where this will break people.

**Comment by alexeagle** [comment]
Oh yarn itself has a mutex to serialize installs, which we expose here
https://github.com/bazelbuild/rules_nodejs/blob/1.x/docs/Built-ins.md#use_global_yarn_cache
Does that help?

**Comment by rickwebiii** [comment]
No, the yarn_installs aren't the tasks that experience the race conditions. The issue happens during the execution phase when you have 2 different nodejs_binary rules that each consume a different node_modules directory.

For example:
```
WORKSPACE:

npm_install(
  name = "a",
)

npm_install(
  name = "b",
)
```

```
BUILD

load("@a//some_node_module:index.bzl", "foo")
load("@b//some_other_module:index.bzl", "bar")

foo(
  name = "my_foo"
)

bar(
  name = "my_bar"
)
```

I've omitted inputs and such from this example, but assume my_foo and my_bar have no dependencies between one another and thus can run in parallel.

On Windows, the tasks will run in a non-sandboxed exec-root. when my_foo runs, it will try to create a dir junction from `exec/__main__/node_modules -> exec/__main__/external/a/node_modules`  while my_bar tries to create a directory junction from `exec/__main__/node_modules -> exec/__main__/external/b/node_modules`. If my_foo isn't done running while my_bar overwrites the node_modules directory junction, my_foo will fail to find npm packages that aren't in `@b`. Even worse, if a and b have the same packages, but different versions then my_foo can actually successfully compile with the wrong package versions.

In an ideal world, I'd just use sandboxing on Windows as it's highly desirable, but it doesn't seem the state of the world is such yet that it's really usable beyond experimentation.
