### ISSUE TITLE
karma_web_test_suite manual tag also needs test_suite_tag "manual" declared

### ISSUE THREAD

**Issue by yoonjesung** [bazelbuild/rules_nodejs#2020]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 
`karma_web_test_suite`

### Description

 A clear and concise description of the problem...

In order to run `karma_web_test_suite` with the "manual" tag properly, the attribute `tags` and `test_suite_tags` both need to be set as `["manual"]`.

Offending line:
https://github.com/bazelbuild/rules_nodejs/blob/2.0.0-rc.1/packages/karma/karma_web_test.bzl#L439

Seems that by defaulting `test_suite_tags` to `None` somehow overrides web_tests's `DEFAULT_TEST_SUITE_TAGS`.

## 🔬 Minimal Reproduction

In https://github.com/bazelbuild/rules_nodejs/tree/1.x/examples/web_testing, add `"manual"` to the tags of either `config_test` of `no_ config_test`. The expectation is that the test will not run using `bazel test //...`, but it still does. Only way to resolve is to also add `test_suiite_tags = "manual"`

**Comment by alexeagle** [comment]
sounds right, want to send a PR for it?
