### ISSUE TITLE
karma_web_test crashes when config_file is not colocated

### ISSUE THREAD

**Issue by longlho** [bazelbuild/rules_nodejs#2029]
# 🐞 bug report

### Affected Rule

karma_web_test

### Is this a regression?

I have no idea

### Description

My project structure
```
formatjs
 |- karma.conf.js
 |- packages
 |--- intl-getcanonicallocales
 |--- BUILD
 |--- karma.conf.js
```
In `formatjs/packages/intl-getcanonicallocales/BUILD` I have `karma_web_test`. If I set `config_file` to `karma.conf.js` (colocated in that package), everything works. If I set `config_file` to `//:karma.conf.js` (the root one), it crashes. They have the exact same content.

## 🔥 Exception or Error

<pre><code>
FAIL: //packages/intl-getcanonicallocales:karma (see /home/longlho/.cache/bazel/_bazel_longlho/576c18efaac10246ec115c72af79fca6/execroot/formatjs/bazel-out/k8-fastbuild/testlogs/packages/intl-getcanonicallocales/karma/test.log)
INFO: From Testing //packages/intl-getcanonicallocales:karma:
==================== Test output for //packages/intl-getcanonicallocales:karma:
[link_node_modules.js] manifest file /home/longlho/.cache/bazel/_bazel_longlho/576c18efaac10246ec115c72af79fca6/sandbox/linux-sandbox/271/execroot/formatjs/bazel-out/k8-fastbuild/bin/packages/intl-getcanonicallocales/karma.runfiles/npm/karma/bin/_karma.module_mappings.json
[link_node_modules.js] manifest contents {
  "workspace": "formatjs",
  "bin": "bazel-out/k8-fastbuild/bin",
  "root": "npm/node_modules",
  "modules": {}
}
[link_node_modules.js] startCwd /home/longlho/.cache/bazel/_bazel_longlho/576c18efaac10246ec115c72af79fca6/sandbox/linux-sandbox/271/execroot/formatjs/bazel-out/k8-fastbuild/bin/packages/intl-getcanonicallocales/karma.runfiles/formatjs
[link_node_modules.js] isExecroot false
[link_node_modules.js] resolved node_modules root npm/node_modules to /home/longlho/.cache/bazel/_bazel_longlho/576c18efaac10246ec115c72af79fca6/sandbox/linux-sandbox/271/execroot/formatjs/bazel-out/k8-fastbuild/bin/packages/intl-getcanonicallocales/karma.runfiles/npm/node_modules
[link_node_modules.js] cwd /home/longlho/.cache/bazel/_bazel_longlho/576c18efaac10246ec115c72af79fca6/sandbox/linux-sandbox/271/execroot/formatjs
[link_node_modules.js] symlink( node_modules -> /home/longlho/.cache/bazel/_bazel_longlho/576c18efaac10246ec115c72af79fca6/sandbox/linux-sandbox/271/execroot/formatjs/bazel-out/k8-fastbuild/bin/packages/intl-getcanonicallocales/karma.runfiles/npm/node_modules )
[link_node_modules.js] mapping hierarchy []
bazel node patches enabled. root: /home/longlho/.cache/bazel/_bazel_longlho/576c18efaac10246ec115c72af79fca6/sandbox/linux-sandbox/271/execroot/formatjs/bazel-out/k8-fastbuild/bin/packages/intl-getcanonicallocales/karma.runfiles symlinks in this directory will not escape

Running karma tests
-----------------------------------------------------------------------------
version     : 5.1.0
pwd         : /home/longlho/.cache/bazel/_bazel_longlho/576c18efaac10246ec115c72af79fca6/sandbox/linux-sandbox/271/execroot/formatjs/bazel-out/k8-fastbuild/bin/packages/intl-getcanonicallocales/karma.runfiles/formatjs
conf        : /home/longlho/.cache/bazel/_bazel_longlho/576c18efaac10246ec115c72af79fca6/sandbox/linux-sandbox/271/execroot/formatjs/bazel-out/k8-fastbuild/bin/packages/intl-getcanonicallocales/karma.runfiles/formatjs/packages/intl-getcanonicallocales/karma.conf.js
node_options:

[link_node_modules.js] manifest file /home/longlho/.cache/bazel/_bazel_longlho/576c18efaac10246ec115c72af79fca6/sandbox/linux-sandbox/271/execroot/formatjs/bazel-out/k8-fastbuild/bin/packages/intl-getcanonicallocales/karma.runfiles/npm/karma/bin/_karma.module_mappings.json
[link_node_modules.js] manifest contents {
  "workspace": "formatjs",
  "bin": "bazel-out/k8-fastbuild/bin",
  "root": "npm/node_modules",
  "modules": {}
}
[link_node_modules.js] startCwd /home/longlho/.cache/bazel/_bazel_longlho/576c18efaac10246ec115c72af79fca6/sandbox/linux-sandbox/271/execroot/formatjs/bazel-out/k8-fastbuild/bin/packages/intl-getcanonicallocales/karma.runfiles/formatjs
[link_node_modules.js] isExecroot false
[link_node_modules.js] resolved node_modules root npm/node_modules to /home/longlho/.cache/bazel/_bazel_longlho/576c18efaac10246ec115c72af79fca6/sandbox/linux-sandbox/271/execroot/formatjs/bazel-out/k8-fastbuild/bin/packages/intl-getcanonicallocales/karma.runfiles/npm/node_modules
[link_node_modules.js] cwd /home/longlho/.cache/bazel/_bazel_longlho/576c18efaac10246ec115c72af79fca6/sandbox/linux-sandbox/271/execroot/formatjs
[link_node_modules.js] symlink( node_modules -> /home/longlho/.cache/bazel/_bazel_longlho/576c18efaac10246ec115c72af79fca6/sandbox/linux-sandbox/271/execroot/formatjs/bazel-out/k8-fastbuild/bin/packages/intl-getcanonicallocales/karma.runfiles/npm/node_modules )
[link_node_modules.js] mapping hierarchy []
bazel node patches enabled. root: /home/longlho/.cache/bazel/_bazel_longlho/576c18efaac10246ec115c72af79fca6/sandbox/linux-sandbox/271/execroot/formatjs/bazel-out/k8-fastbuild/bin/packages/intl-getcanonicallocales/karma.runfiles symlinks in this directory will not escape
[karma.conf.js] running with
    cwd: /home/longlho/.cache/bazel/_bazel_longlho/576c18efaac10246ec115c72af79fca6/sandbox/linux-sandbox/271/execroot/formatjs/bazel-out/k8-fastbuild/bin/packages/intl-getcanonicallocales/karma.runfiles/formatjs
    configPath: formatjs/karma.conf.js
[karma.conf.js] base karma configuration: {
  "frameworks": [
    "jasmine",
    "jasmine-matchers"
  ],
  "files": [
    "**/*.bundled.js"
  ],
  "reporters": [
    "progress"
  ],
  "port": 9876,
  "colors": true,
  "logLevel": "INFO",
  "plugins": [
    "karma-chrome-launcher",
    "karma-jasmine",
    "karma-jasmine-matchers"
  ],
  "browsers": [
    "ChromeHeadless"
  ],
  "autoWatch": false,
  "singleRun": true,
  "concurrency": null
}
wslpath: /home/longlho/.cache/bazel/_bazel_longlho/576c18efaac10246ec115c72af79fca6/sandbox/linux-sandbox/271/execroot/formatjs/bazel-out/k8-fastbuild/bin/packages/intl-getcanonicallocales/karma.runfiles/build_bazel_rules_nodejs/internal/node/_node_bin: No such file or directory
11 07 2020 04:05:59.788:ERROR [config]: Error in config file!
 Error: Command failed: wslpath -w "/home/longlho/.cache/bazel/_bazel_longlho/576c18efaac10246ec115c72af79fca6/sandbox/linux-sandbox/271/execroot/formatjs/bazel-out/k8-fastbuild/bin/packages/intl-getcanonicallocales/karma.runfiles/build_bazel_rules_nodejs/internal/node/_node_bin"
wslpath: /home/longlho/.cache/bazel/_bazel_longlho/576c18efaac10246ec115c72af79fca6/sandbox/linux-sandbox/271/execroot/formatjs/bazel-out/k8-fastbuild/bin/packages/intl-getcanonicallocales/karma.runfiles/build_bazel_rules_nodejs/internal/node/_node_bin: No such file or directory

    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at getAllPrefixesWsl (/home/longlho/.cache/bazel/_bazel_longlho/576c18efaac10246ec115c72af79fca6/sandbox/linux-sandbox/271/execroot/formatjs/node_modules/karma-firefox-launcher/index.js:83:25)
    at getFirefoxExeWsl (/home/longlho/.cache/bazel/_bazel_longlho/576c18efaac10246ec115c72af79fca6/sandbox/linux-sandbox/271/execroot/formatjs/node_modules/karma-firefox-launcher/index.js:115:22)
    at Object.<anonymous> (/home/longlho/.cache/bazel/_bazel_longlho/576c18efaac10246ec115c72af79fca6/sandbox/linux-sandbox/271/execroot/formatjs/node_modules/karma-firefox-launcher/index.js:256:20)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 77 73 6c 70 61 74 68 3a 20 2f 68 6f 6d 65 2f 6c 6f 6e 67 6c 68 6f 2f 2e 63 61 63 68 65 2f 62 61 7a 65 6c 2f 5f 62 61 7a 65 6c 5f 6c 6f 6e 67 6c 68 6f ... 230 more bytes>
  ],
  pid: 112,
  stdout: <Buffer >,
  stderr: <Buffer 77 73 6c 70 61 74 68 3a 20 2f 68 6f 6d 65 2f 6c 6f 6e 67 6c 68 6f 2f 2e 63 61 63 68 65 2f 62 61 7a 65 6c 2f 5f 62 61 7a 65 6c 5f 6c 6f 6e 67 6c 68 6f ... 230 more bytes>
}
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
WSL on Windows
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
3.3.1
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
2.0.0-rc.2
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
actually `internal/node/_node_bin: No such file or directory` seems like https://github.com/bazelbuild/rules_nodejs/commit/0bd9b7e7201ce4635880a0c278f88ebe875d2cfd but you say you're on rc.2 so you should have that fix...
does feel like a pathing bug
