### ISSUE TITLE
Feat: Protractor custom frameworks support

### ISSUE THREAD

**Issue by yoonjesung** [bazelbuild/rules_nodejs#2043]
# 🚀 feature request

### Relevant Rules

`protractor_web_test`/`protractor_web_test_suite`

### Description

The current protractor web test rule only allows for the jasmine2 framework. Mocha and Cucumber seem to be popular protractor frameworks, and it would be nice to see these (or more generally, custom frameworks) supported. Mocha may be simpler since it is built-in to protractor, but there are issues with getting cucumber to run properly with protractor in bazel.

### Describe the solution you'd like

Allow for an optional framework + frameworkPath arguments to be passed, which would update protractor.conf.js appropriately.

### Describe alternatives you've considered

I've attempted to rewrite the current rule to allow for the cucumber framework. However, the `protractor-cucumber-framework` depends on cucumber as a dependency. But due to module-resolution issues, have had trouble getting this to run properly since there's a discrepancy between where the protractor entry point is run and where the runtime output directory.

**Comment by alexeagle** [comment]
We can help you get the `require('protractor-cucumber-framework')` resolution to work - you probably need to clone the nodejs_binary that runs protractor and add the `data` dep there.

**Comment by yoonjesung** [comment]
Thanks! Actually, the issue isn't with resolving the 'protractor-cucumber-framework', but with when that module attempts to `require('cucumber')`; it expects cucumber to be resolved at `private/.../devserver_test_chromium-local.sh.runfiles/<workspace>/`, but all of the data deps live in `private/.../devserver_test_chromium-local.sh.runfiles/npm/node_modules/` as far as I can tell.

I tried to be clever and symlink the cucumber dependency there, but then that resulted in the error:
```
      You appear to be executing an install of cucumber (most likely a global install)
      that is different from your local install (the one required in your support files).
      For cucumber to work, you need to execute the same install that is required in your support files.
      Please execute the locally installed version to run your tests.
      
      Executed Path: /private/.../devserver_test_chromium-local.sh.runfiles/npm/node_modules/cucumber/lib/index.js
      Local Path:        /<workspace-root>/npm/node_modules/cucumber/lib/index.js
```
So I couldn't figure out how to get cucumber to be co-located with the protractor binary. I'm sure I'm missing something here, but not sure what that is.
