### ISSUE TITLE
Read through package.json bin entry when resolving entry_point

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#205]
This was suggested by some visitor last week (sorry I forgot who)

https://github.com/bazelbuild/rules_nodejs/blob/3a35786d8e78627f9e0783fbf45e1c960eaccdf8/examples/rollup/BUILD.bazel#L16 has an example of our typical pattern: you read the `bin` entry from the `package.json` and put that in the BUILD file.
It would be better to point to the package, or the package.json, and let the rule read the package.json to find the bin.
This would make it more robust (in case the `bin` changes in a new version of the package) and less boilerplate to ask Bazel to run an arbitrary program we fetched from NPM.

**Comment by nimerritt** [comment]
Please don't make this the only option. package.json files are a NPM concept and not a Nodejs requirement.

**Comment by alexeagle** [comment]
@gregmagolan I think we can close this now that we generate nodejs_binary for packages that have a `bin` in package.json?

**Comment by gregmagolan** [comment]
> @gregmagolan I think we can close this now that we generate nodejs_binary for packages that have a `bin` in package.json?

I agree. `entry_point` is now also a label so you can easily create your own `nodejs_binary` and point the entry point to your node_modules such as `entry_point = "@npm//:node_modules/rollup/bin/rollup"`
