### ISSUE TITLE
angular example is not working

### ISSUE THREAD

**Issue by hiepxanh** [bazelbuild/rules_nodejs#2064]
### Description

Angular newest example is not working

```
- git clone https://github.com/bazelbuild/rules_nodejs
- cd rules_nodejs/examples/angular
- npm i
- ng serve
```

got error 

![image](https://user-images.githubusercontent.com/16970990/88128214-a1362280-cbff-11ea-9adf-3fc9ccde45f6.png)

`npm i @angular/bazel -S`

![image](https://user-images.githubusercontent.com/16970990/88128314-e22e3700-cbff-11ea-97ad-a01afd55a29c.png)

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**Output of `bazel version`:**
```
"dependencies": {
        "@angular/animations": "10.0.2",
        "@angular/bazel": "^10.0.4",
        "@angular/cdk": "10.0.1",
        "@angular/common": "10.0.2",
        "@angular/core": "10.0.2",
        "@angular/forms": "10.0.2",
        "@angular/material": "10.0.1",
        "@angular/platform-browser": "10.0.2",
        "@angular/platform-browser-dynamic": "10.0.2",
        "@angular/platform-server": "10.0.2",
        "@angular/router": "10.0.2",
        "@ngrx/store": "9.2.0",
        "@nguniversal/express-engine": "^9.0.0",
        "date-fns": "1.30.1",
        "rxjs": "6.5.3",
        "systemjs": "6.1.2",
        "tslib": "2.0.0",
        "zone.js": "0.10.3"
    },
    "devDependencies": {
        "@angular/cli": "10.0.0",
        "@angular/compiler": "10.0.2",
        "@angular/compiler-cli": "10.0.2",
        "@babel/cli": "^7.6.0",
        "@babel/core": "^7.6.0",
        "@babel/preset-env": "^7.6.0",
        "@bazel/bazelisk": "^1.4.0",
        "@bazel/benchmark-runner": "^0.1.0",
        "@bazel/buildifier": "^3.0.0",
        "@bazel/ibazel": "^0.13.1",
        "@bazel/karma": "^1.7.0",
        "@bazel/protractor": "^1.7.0",
        "@bazel/rollup": "^1.7.0",
        "@bazel/terser": "^1.7.0",
        "@bazel/typescript": "^1.7.0",
        "@types/jasmine": "3.4.0",
        "@types/node": "6.14.6",
        "core-js": "2.6.9",
        "firebase-tools": "7.1.0",
        "history-server": "^1.3.1",
        "html-insert-assets": "^0.6.0",
        "karma": "~4.1.0",
        "karma-chrome-launcher": "2.2.0",
        "karma-firefox-launcher": "1.1.0",
        "karma-jasmine": "2.0.1",
        "karma-requirejs": "1.1.0",
        "karma-sourcemap-loader": "0.3.7",
        "protractor": "^5.4.2",
        "requirejs": "2.3.6",
        "rollup": "^1.21.4",
        "rollup-plugin-commonjs": "^10.1.0",
        "rollup-plugin-node-resolve": "^5.2.0",
        "terser": "4.3.1",
        "typescript": "^3.9.0"
    }

```

**Comment by alexeagle** [comment]
First, you're probably cloning 1.x (the default branch) since I'm waiting for @philwo to change it to stable

Second I'm guessing we don't test by running `ng build` and only do Bazel build, will check

**Comment by alexeagle** [comment]
the default branch is fixed to `stable` (there should be no `@angular/bazel` package involved in this example)

I tried it locally and `npx ng serve` works for me in `examples/angular` (I do `npx` because I don't trust the global-installed `ng` command does the right thing, YMMV)

**Comment by hiepxanh** [comment]
I follow the instruction in the .README file
![image](https://user-images.githubusercontent.com/16970990/88245281-deaeb480-ccc0-11ea-92a8-6e27475457f4.png)

> the default branch is fixed to stable (there should be no `@angular/bazel` package involved in this example) 

 So I'm getting error, that should not be like this, or we should update README, or we should update the package.json to make it run after npm install. do you want an application that not run after `npm install` but doesn't mention in the README file? So what exactly should I do with bazel? `npx ng serve` all the time? I do not allow to use global-installed `ng` with bazel? ok it's fine. Just write it the README. We have a nice bug that was found. 

I could be correct or wrong but I think my issue is helpful for this project. I am just trying to help you to testing it. I'm so exicting and test bazel every time it release new version since it just an beta. I dont expect you close my issue so rude like this. 
All I'm trying to test and do a helpful issue sir, and you just close my issue so quickly. 

Thanks for your comment and solution, I would like to try your solution and get some feedback, me be we can do some investment, maybe we can help to findout other bug. But opsss.... you just CLOSED my issues.

Have good days

**Comment by hiepxanh** [comment]
you just made for me a bad day sir. 

So Sad... 😭  😥  😞

**Comment by alexeagle** [comment]
Wow, I don't mean to make you sad, I am just taking time for my family to maintain this in my spare time and try to keep the issue backlog clean. I'll reopen if something is still broken. Global ng should be fine too.

**Comment by hiepxanh** [comment]
yeah, I love to spending the time with family too. I have two cats while coding at home. So I understand you are doing very elevated things. Hope I can share my time to help you something.
 I will take a look into that and keep report this to you. I appreciate your work, the repository should be clean, and I will close it as soon as possible, after I find out nice solution to run it. I have a super big with hundred components and I'm so exciting to use Bazel with latest feature to my project. Forgive for my sensitive.
I will try `npx` tomorrows and find out why global `ng` not working.

**Comment by alexeagle** [comment]
I suspect your global `ng` already works, did you still see an error with that after getting the rules_nodejs update?

**Comment by hiepxanh** [comment]
thank you, I find out that the default branch when I clone is not the `stable` branch, it is `1.x` after I clone, and because I run it direct from my CMD, I cannot see it. Just got the error `EPERM: operation not permitted + bazelisk-windows_amd64.exe` only but I think I can search that error. 
thank you for take your time. That my bad. Close issues as my misstake. BTW, why github doesn't set the stable as default branch when I run `git clone https://github.com/bazelbuild/rules_nodejs`, that so tricky, I'm too exiciting to check it, forgot the default branch is not `stable`.  Today, I just double check and the default branch back to stable now. That is good. 
have a good day

**Comment by hiepxanh** [comment]
I think I found it, and I dont have solution :D 
https://github.com/bazelbuild/rules_nodejs/issues/894
