### ISSUE TITLE
Example of next.js build-time prerendering

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#2066]
Next.js docs for prerendering:
https://nextjs.org/learn/basics/data-fetching/two-forms

**Comment by alexeagle** [comment]
cc @elliottsj I see you've been down this road before https://github.com/vercel/next.js/issues/9588

**Comment by elliottsj** [comment]
Unfortunately I didn't get too far since I ended up blocked by that issue, and ended up not using Bazel due to other circumstances as well.

This is what I tried without success:

```bazel
# This doesn't work; results in this error:
#   > Build error occurred
#   Error: > Build directory is not writeable. https://err.sh/zeit/next.js/build-dir-not-writeable
# This is because the next.config.js file isn't picked up by the Next.js CLI, because it's not found
# in the working directory.
next(
    name = "next",
    args = [
        "build",
        "$(location src)",
        # Normally we'd pass in the output dir as a "$@" argument like below.
        # But the Next.js CLI doesn't accept args for the output dir, so this isn't possible.
        # Instead, we're hard-coding the output dir in next.config.js for now.
        # "$@",
    ],
    data = [
        "next.config.js",
        "src/.",
        "@npm//:node_modules",
    ],
    output_dir = True,
)
```

**Comment by RamaneekGill** [comment]
@alexeagle FWIW we (+ @elliottsj) [Nx](https://github.com/nrwl/nx) to manage our monorepo. They do have some sort of Bazel support planned. 

I know that the folks over at Nrwl have been involved with you in the past. They might have some ideas or working examples of NextJS and Bazel.

**Comment by psylovibe** [comment]
my setup is a little different. My project is housing a polyglot lang. mono-repos. I was able to get the build to complete without `write_chdir_script`. But, the generated .next/* files are missing in my run file. This is probably because of `write_chdir_script` not executing?

```
next(
    name = ".next",
    args = [
        "build",
        "./src/js/hello-world",
    ],
    data = glob([
        "components/*",
        "pages/**",
        "public/**",
        "styles/*",
    ]) + [
        "//:package.json",
    ],
    output_dir = True,
)

next(
    name = ".next.start",
    args = [
        "start",
        "./src/js/hello-world",
    ],
    data = [":.next"],
)
```

```
% yarn build                                   
yarn run v1.22.4
$ bazelisk build //src/js/hello-world:.next
INFO: Build option --legacy_external_runfiles has changed, discarding analysis cache.
INFO: Analyzed target //src/js/hello-world:.next (1 packages loaded, 16178 targets configured).
INFO: Found 1 target...
INFO: From Action src/js/hello-world/.next:
Creating an optimized production build...

Compiled successfully.

Automatically optimizing pages...

Page                                                           Size     First Load JS
┌ ○ /                                                          3.42 kB        61.3 kB
├   └ css/80ef9a32b2f9e4d03d0b.css                             660 B
├ ○ /404                                                       3.46 kB        61.3 kB
└ λ /api/hello                                                 0 B            57.9 kB
+ First Load JS shared by all                                  57.9 kB
  ├ chunks/f6078781a05fe1bcb0902d23dbbb2662c8d200b3.3bec96.js  10.2 kB
  ├ chunks/framework.9cd2c6.js                                 40 kB
  ├ chunks/main.126e78.js                                      6.71 kB
  ├ chunks/pages/_app.ce79c4.js                                258 B
  └ chunks/webpack.488dc2.js                                   751 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)

Redirects

┌ source: /:path+/
├ destination: /:path+
└ permanent: true
 

Target //src/js/hello-world:.next up-to-date:
  dist/bin/src/js/hello-world/.next
INFO: Elapsed time: 11.159s, Critical Path: 10.54s
INFO: 1 process: 1 darwin-sandbox.
INFO: Build completed successfully, 2 total actions
✨  Done in 11.52s.
```

I also tried my own nodejs_binaries where I was able to build .next files but when trying to run in dev or prod I am just not able to get up and running. In dev, I get `Invalid Hook Call` for Component even with applying webpack resolves.

**Comment by kogai** [comment]
I'll record my setup which little different from both here which can be got expected output.

```bazel
load(":next_config_js.bzl", "next_config_js")

next_config_js(
    name = "next.config",
    template = "//:next.config.js.tpl",
)

load("@build_bazel_rules_nodejs//:index.bzl", "npm_package_bin")

npm_package_bin(
    name = "dist",
    args = [
        "build",
    ],
    tool = "@npm//next/bin:next",
    output_dir = True,
    data = [
        # If npm_package_bin provides a interface transitive_deps, this target can access next.config.js which //:next.config build.
        # //:next.config
        "//:next.config.js",
        "//:pages/index.jsx",
        "//:package.json",
        "@npm//:node_modules",
    ],
)
```

As @alexeagle and @elliottsj have pointed out, it seems to be common in Bazel to pass the output directory from the CLI, but the Next.js CLI doesn't have such interfaces.
So, I tried to generate next.config.js dynamically, which can configure distDir despite the CLI interface.

The following is the sample repository.
https://github.com/kogai/exapmle-bazel-nextjs

It specifies an output directory by executing a custom-Bazel-rule that replaces the distDir in `next.config.js.tpl` by building `//:next.config` target.
However, `//:dist` target can't access the generated next.config.js even though `//:next.config` has been set to data parameter of npm_package_bin.
This is why I need a workaround to copy from `bazel-bin/next.config.js` to repository root which outside of the bazel's sandbox, as I wrote in README.md.

According to the documentation,

> similar to genrule.srcs may also include targets that produce or reference npm packages which are needed by the tool

https://github.com/bazelbuild/rules_nodejs/blob/stable/docs/Built-ins.md#data-4

Does this explain the different nature of deps?
Or, perhaps if #1504 is merged and the `//:next.config` can be set as transitive_deps, this problem might be solved.

**Comment by ofagbemi** [comment]
For anyone having trouble here, I was able to get this working with the auto-generated next-cli Bazel rules by using [`copy_to_bin`](https://bazelbuild.github.io/rules_nodejs/Built-ins.html#copy_to_bin) to get around Next's output directory constraints.

```bazel
load("@build_bazel_rules_nodejs//:index.bzl", "copy_to_bin")
load("@npm//next:index.bzl", "next")

YARN_DEPS = [
    "@npm//@types/node",
    "@npm//react",
    "@npm//react-dom",
    "@npm//typescript",
]

# Next.js doesn't allow its build output to be written anywhere outside of the
# source directory, so we copy all of the source files over into the exec folder
# and run next on the source there. That way, the output will be written there
# and we can return it as our rule output.

copy_to_bin(
    name = "bin_src",
    srcs = [
        "package.json",
        "pages/index.js",
    ],
)

next(
    name = "next_build",
    outs = [".next"],
    args = ["build $(RULEDIR)"],
    data = [":bin_src"] + YARN_DEPS,
)

next(
    name = "build",
    outs = ["dist"],
    args = ["export $(RULEDIR) -o $(@D)/dist"],
    data = [":next_build"],
)
```

**Comment by flolu** [comment]
Working example with  `copy_to_bin` and `@npm//next:index.bzl`: [flolu/nextjs-bazel](https://github.com/flolu/nextjs-bazel)

**But** importing global CSS styles into `pages/_app.js` causes this error:
```
Global CSS cannot be imported from files other than your Custom <App>. Please move all global CSS imports to pages/_app.js. Or convert the import to Component-Level CSS (CSS Modules).
```

Any ideas for this?

**Comment by flolu** [comment]
After some debugging it turns out that [this if](https://github.com/vercel/next.js/blob/ab158c0aee53882457d2bac3e36b8ccf197166f0/packages/next/build/webpack/config/blocks/css/index.ts#L211) is not triggered, meaning `ctx.customAppFile` is `null`. 

Here is the log output of `ctx`:
```
{
  ctx: {
    rootDirectory: '/home/flo/.cache/bazel/_bazel_flo/e959037946bf226f3b911fa40ec62d93/sandbox/linux-sandbox/85/execroot/nextjs-bazel/bazel-out/k8-fastbuild/bin',
    customAppFile: null,
    isDevelopment: false,
    isProduction: true,
    isServer: true,
    isClient: false,
    assetPrefix: '',
    sassOptions: {},
    productionBrowserSourceMaps: false,
    future: {
      strictPostcssConfiguration: false,
      excludeDefaultMomentLocales: false,
      webpack5: false
    }
  }
}
```

But I have no idea why this is happening

**Comment by flolu** [comment]
After some more debugging, I found the problem: This [if statement](https://github.com/vercel/next.js/blob/cd9bb986eba25006d4872e30eedf24ef5680bc6b/packages/next/server/lib/find-page-file.ts#L34) throws an error
```
Error: EACCES: permission denied, access '/home/flo/.cache/bazel/_bazel_flo/e959037946bf226f3b911fa40ec62d93/sandbox/linux-sandbox/186/execroot/nextjs-bazel/bazel-out/k8-fastbuild/bin/pages/_app.tsx'
```

If I patch Next.js to ignore this error, everything works fine!
**Is there any way to prevent this error when building with Bazel?**

**Comment by alexeagle** [comment]
Nice digging @flolu !
The workaround would be to run without the Bazel sandbox so the files have the original write permissions.

But I think we should make a PR to next.js to fix that assertion. They should be able to operate on a read-only file tree (there are other uses for this like when sources get mounted from a network filesystem in some CI systems).
I think they would accept it since there are some ppl over there working on Bazel adoption.

**Comment by flolu** [comment]
I've tried to add `tags = ["no-sandbox"]` but it does not seem to disable the sandbox.
How can I disable it?

**Comment by xnerhu** [comment]
I have this error.

```bash
yarn run v1.22.10
$ bazel build //...
INFO: Invocation ID: 52a3e0b2-0042-46a6-9eec-5fdf8d181ed3
INFO: Analyzed 9 targets (2 packages loaded, 13 targets configured).
INFO: Found 9 targets...
ERROR: C:/users/xnerh/projects/wexond-old/bazel-test/frontend/website/BUILD:13:5: Action frontend/website/.next failed: (Exit 1): next.bat failed: error executing command bazel-out/host/bin/external/npm/next/bin/next.bat build bazel-out/x64_windows-fastbuild/bin/frontend/website ... (remaining 1 argument(s) skipped)> Build error occurred
[Error: EPERM: operation not permitted, open 'C:\users\xnerh\_bazel_xnerh\d2buhs2e\execroot\init\bazel-out\x64_windows-fastbuild\bin\frontend\website\next-env.d.ts'] {  errno: -4048,
  code: 'EPERM',  syscall: 'open',
  path: 'C:\\users\\xnerh\\_bazel_xnerh\\d2buhs2e\\execroot\\init\\bazel-out\\x64_windows-fastbuild\\bin\\frontend\\website\\next-env.d.ts'
}
```

**Comment by alexeagle** [comment]
@gregmagolan happens to be working on this for a client, I believe

**Comment by gregmagolan** [comment]
No longer in scope for rules_nodejs which only supplies the Node.js toolchain as of [v6.0.0](https://github.com/bazelbuild/rules_nodejs/releases/tag/v6.0.0-beta0).

Downstream canonical JavaScript + Node.js ruleset is now https://github.com/aspect-build/rules_js.
