### ISSUE TITLE
NPM ts_library deps regression

### ISSUE THREAD

**Issue by WesleyYue** [bazelbuild/rules_nodejs#2070]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 
ts_library

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 2.0.0-rc.3

### Description

 A clear and concise description of the problem...
ts_library complains that the "package.json" file in an external npm package is not of the extension '.ts', '.tsx', '.d.ts'.

## 🔬 Minimal Reproduction

https://github.com/WesleyYue/ts-jest-repro

## 🔥 Exception or Error

<pre><code>

t@t:/tmp/ts-jest-repro# bazel build //:test
WARNING: /root/.cache/bazel/_bazel_root/bfde6f60a4a1ca6bc7b0ec93a29e8cef/external/remote_java_tools_linux/BUILD:671:1: in hdrs attribute of cc_library rule @remote_java_tools_linux//:combiners: Artifact 'external/remote_java_tools_linux/java_tools/src/tools/singlejar/zip_headers.h' is duplicated (through '@remote_java_tools_linux//:transient_bytes' and '@remote_java_tools_linux//:zip_headers'). Since this rule was created by the macro 'cc_library', the error might have been caused by the macro implementation
INFO: Analyzed target //:test (437 packages loaded, 9415 targets configured).
INFO: Found 1 target...
ERROR: /tmp/ts-jest-repro/BUILD.bazel:5:1: Compiling TypeScript (devmode) //:lib failed (Exit 1)
error TS6054: File '/root/.cache/bazel/_bazel_root/bfde6f60a4a1ca6bc7b0ec93a29e8cef/execroot/jest_repro/external/npm/node_modules/@types/flatbuffers/package.json' has an unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.

Target //:test failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /tmp/ts-jest-repro/BUILD.bazel:23:1 Compiling TypeScript (devmode) //:lib failed (Exit 1)
INFO: Elapsed time: 15.849s, Critical Path: 4.05s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 18.04.4 LTS

  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 3.1.0- (@non-git)
Build target: bazel-out/aarch64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sat Jul 11 22:58:09 2020 (1594508289)
Build timestamp: 1594508289
Build timestamp as int: 1594508289
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
2.0.0
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
Yes thanks - this was already fixed in https://github.com/bazelbuild/rules_nodejs/commit/065922b6963f1f9401c8a7638ef11c0709635886
we'll have 2.0.1 out this morning :)

**Comment by chasain** [comment]
Any updates on 2.0.1, been keeping an eye out for it since this comment

**Comment by alexeagle** [comment]
https://github.com/bazelbuild/rules_nodejs/releases/tag/2.0.1
