### ISSUE TITLE
Cannot use nodejs_binary inside a local genrule

### ISSUE THREAD

**Issue by hristozov** [bazelbuild/rules_nodejs#2076]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: nodejs_binary

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 1.7.1

### Description

 A clear and concise description of the problem...

As part of building an Angular project we use a `nodejs_binary` for the compiler inside a `genrule`. We have a condition to toggle the `local` flag on the `genrule` (used for local development).

After upgrading from 1.7.1 to 2.0.0 we noticed that the build fails when `local` is on. Things seem to break in the patcher:
https://github.com/bazelbuild/rules_nodejs/blob/ecafc24ecbfbddc37e1e28b32491cae5234072d6/internal/node/node_patches.js#L554-L564
`requireScriptName` points to `/path/to/output/base/external/build_bazel_rules_nodejs/internal/node/node_patches.js`. As a result, on line 559 we attempt to create `_node_bin` next to `node_patches.js`. However, since we're in the output base, we don't have permission to write there.

The `nodejs_binary` uses `"@npm//:node_modules/@angular/cli/bin/ng"` as an entry point.

## 🔬 Minimal Reproduction

Unfortunately, my project is non-trivial and I still can't create a proper repro, but will spend some more time in the next few days. Will also try the rules before and after 48bb9cc612de7f70d07bc04c23876a6eda375859.

## 🔥 Exception or Error

<pre><code>
ERROR: /path/to/project/sub-project/projects/components/BUILD.bazel:6:8: Building sub-project //sub-project/projects/components:components failed (Exit 1)
[link_node_modules.js] using runfiles manifest ../bazel-out/host/bin/sub-project/projects/components/build-components-binary.sh.runfiles_manifest
[link_node_modules.js] manifest file /path/to/output/base/execroot/project_workspace/bazel-out/host/bin/sub-project/projects/components/_build-components-binary.module_mappings.json
[link_node_modules.js] manifest contents {
  "workspace": "project_workspace",
  "bin": "bazel-out/host/bin",
  "root": "npm-sub-project/node_modules",
  "modules": {}
}
[link_node_modules.js] startCwd /path/to/project/sub-project
[link_node_modules.js] isExecroot false
[link_node_modules.js] resolved node_modules root npm-sub-project/node_modules to /path/to/project/npm-sub-project/node_modules
[link_node_modules.js] cwd /path/to/project/sub-project
[link_node_modules.js] symlink( node_modules -> /path/to/project/npm-sub-project/node_modules )
[link_node_modules.js] mapping hierarchy []
bazel node patches enabled. root: /path/to/output/base/execroot/project_workspace symlinks in this directory will not escape
/path/to/output/base/external/build_bazel_rules_nodejs/internal/node/node_patches.js:564
            throw e;
            ^

Error: ENOENT: no such file or directory, mkdir '/path/to/output/base/external/build_bazel_rules_nodejs/internal/node/_node_bin'
    at Object.mkdirSync (fs.js:757:3)
    at Object.exports.patcher [as subprocess] (/path/to/output/base/external/build_bazel_rules_nodejs/internal/node/node_patches.js:559:14)
    at Object.<anonymous> (/path/to/output/base/external/build_bazel_rules_nodejs/internal/node/node_patches.js:675:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:901:12)
INFO: Elapsed time: 34.094s, Critical Path: 21.48s
INFO: 3 processes: 3 darwin-sandbox.
FAILED: Build did NOT complete successfully
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS 10.14.6
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
3.3.0
  </code>
</pre>

**Rules_nodejs version:**

<pre>
  <code>
2.0.1
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
As mentioned in the release notes you can use `templated_args = ["--nobazel_node_patches"]` to go back to the 1.7 behavior, where we don't run this node_patches.js

**Comment by hristozov** [comment]
Thanks, that workaround resolved the issue for me!
