### ISSUE TITLE
Allow for a file to generate environment variables

### ISSUE THREAD

**Issue by rockwotj** [bazelbuild/rules_nodejs#2077]
# 🚀 feature request

### Relevant Rules

`nodejs_binary`

### Description

We currently are moving our create-react-app to use rules_nodejs to use bazel for our frontend as well as our backend.

Right now we have a bunch of environment variables ie `REACT_APP_FOO` that we set before calling `npm run X` and we'd like to move that into bazel. However, these are specific per environment (we have a set of variables for dev, staging and prod). We have a solution for this in our backend code already.

### Describe the solution you'd like

Essentially I'd like to be able to pass in a label to a target that is a file and creates the environment variables.

### Describe alternatives you've considered

Use something like `env-cmd` (which is what we use now via `npm run X`) but I'm not sure how to hook that up so it works to call the `react-scripts` generated bzl package (and keeps the environment).

The other option is to write a script that encapsulates all this and just takes the environment file and then the react-scripts target to run, but that seems complicated and I'm not sure how to do that either.

**Comment by alexeagle** [comment]
Interesting! Seems pretty simple for npm_package_bin to add an env_file label attribute which points to some (possibly generated) input of key/value pairs and sets them into the environment that node runs under.

**Comment by rockwotj** [comment]
I was able to instead just use bazel to generate the config in a json file and preprocess the index.html instead of relying on `REACT_APP_` variables.
