### ISSUE TITLE
missing pieces in installation document

### ISSUE THREAD

**Issue by adb** [bazelbuild/rules_nodejs#2087]
# 🐞 bug report

### Affected Rule

This is about some gaps and inconsistencies in the setup document for the typescript rules (e.g., ts_library):

https://github.com/bazelbuild/rules_nodejs/blob/stable/packages/typescript/install.md

### Is this a regression?

Maybe? The docs are out of sync with the code.

### Description

I'm walking through an install from scratch trying to debug an issue with another install I have, making notes of what's not quite right in the docs. So far:

- Installing the typescript package should be mentioned at the same time as @bazel/typescript. Or (I'm still relatively new to the node universe) should @bazel/typescript perhaps have an explicit dependency on typescript?

- The packages used in the example load() commands are inconsistent with each other and with the WORKSPACE "yarn create @bazel" generated for me: e.g.,

load("@npm//typescript:index.bzl", "tsc")
load("//packages/typescript:index.bzl", "ts_library")

vs what works on a freshly created project, which is

load("@npm//@bazel/typescript:index.bzl", "ts_devserver", "ts_library")

## 🔬 Minimal Reproduction

n/a

## 🔥 Exception or Error

n/a

## 🌍  Your Environment

cross-platform (I've been working on macOS Mojave and GCP's Debian buster)

**Output of `bazel version`:**

bazel 3.4.1 (Linux)
bazel 3.3.0 (Mac)

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

2.0.1, still present in trunk code

**Anything else relevant?**

**Comment by alexeagle** [comment]
Your yarn probably had an existing 1.x @bazel/create package and reused it.
Could you check 
yarn create @bazel@latest

**Comment by evahowe** [comment]
@adb - did @alexeagle solve your problem?
