### ISSUE TITLE
Documentation has load statements that produce errors

### ISSUE THREAD

**Issue by gonzojive** [bazelbuild/rules_nodejs#2092]
# 🐞 bug report

### Affected Rule

ts_library, rollup_bundle, and probably many more

### Is this a regression?

Yes, previous cut and paste from the documentation worked.

### Description

`bazel query //...` fails with the following setup, generated by copy/paste from https://bazelbuild.github.io/rules_nodejs/Rollup.html and other documentation pages:

```skylark
# build.bazel
load("//packages/rollup:index.bzl", "rollup_bundle")
load("//packages/typescript:index.bzl", "ts_library")
```

```skylark
# WORKSPACE.bazel
# Bazel workspace created by @bazel/create 2.0.1

# Declares that this directory is the root of a Bazel workspace.
# See https://docs.bazel.build/versions/master/build-ref.html#workspace
workspace(
    # How this workspace would be referenced with absolute labels from another workspace
    name = "gtile",
    # Map the @npm bazel workspace to the node_modules directory.
    # This lets Bazel use the same node_modules as other local tooling.
    managed_directories = {"@npm": ["node_modules"]},
)

# Install the nodejs "bootstrap" package
# This provides the basic tools for running and packaging nodejs programs in Bazel
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "0f2de53628e848c1691e5729b515022f5a77369c76a09fbe55611e12731c90e3",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/2.0.1/rules_nodejs-2.0.1.tar.gz"],
)

# The yarn_install rule runs yarn anytime the package.json or yarn.lock file changes.
# It also extracts and installs any Bazel rules distributed in an npm package.
load("@build_bazel_rules_nodejs//:index.bzl", "yarn_install")
yarn_install(
    # Name this npm so that Bazel Label references look like @npm//package
    name = "npm",
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
)

```

```js
// package.json
{
    "name": "gtile",
    "version": "0.1.0",
    "private": true,
    "devDependencies": {
        "@bazel/bazelisk": "latest",
        "@bazel/buildifier": "latest",
        "@bazel/ibazel": "latest",
        "@bazel/rollup": "^2.0.1"
    },
    "scripts": {
        "build": "bazel build //...",
        "test": "bazel test //..."
    }
}
```

it produces this error:

```
Label '//packages/rollup:index.bzl' is invalid because 'packages/rollup' is not a package; perhaps you meant to put ....
```

## 🔬 Minimal Reproduction

See above

## 🔥 Exception or Error

See above

## 🌍  Your Environment

**Operating System:**

linux, amd64

<pre>
  <code>

  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
bazel version                                                                                                                            
Build label: 3.4.1                                                                                                                                                            
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar                                                                   
Build time: Tue Jul 14 06:27:53 2020 (1594708073)                                                                                                                             
Build timestamp: 1594708073                                                                                                                                                   
Build timestamp as int: 1594708073     
  </code>
</pre>

**Rules_nodejs version:**

See above

**Anything else relevant?**

**Comment by alexeagle** [comment]
Oh interesting that the replacement we do when publishing wasn't applied when producing the docsite. I guess that makes sense.

**Comment by gonzojive** [comment]
The docs are still invalid. I'm guessing they need to be rebuilt and pushed
before this is fully fixed.
