### ISSUE TITLE
Improve error message when ngcc is forgotten

### ISSUE THREAD

**Issue by literalpie** [bazelbuild/rules_nodejs#2097]
# 🚀 feature request

### Relevant Rules

`ts_library` with `use_angular_plugin=True`

### Description

If you add Bazel to an Angular project and forget to add ngcc to your postinstall, the error message is rather unhelpful:
```
projects/my-lib/src/lib/icon/inner.module.ts:22:14 - error TS-996003: [ngtsc] Appears in the NgModule.exports of MyLibModule, but itself has errors
```

### Describe the solution you'd like

It would be great if the error message mentioned the possibility that the culprit is the lack of `ngcc`. Alternatively, the builder could run ngcc if needed on build (like the normal CLI builder), but I assume if that was easy to do, it would already be done.

### Describe alternatives you've considered

Better documentation also might help. Searching Google for "angular Bazel appears in NgModule.exports but itself has errors" did not lead me to a solution.

I hope that even if nothing comes out of this issue code-wise, it will serve as documentation of sorts for future people searching for the same thing.

**Comment by literalpie** [comment]
I would still like to see this be fixes

**Comment by alexeagle** [comment]
Feels like something Angular should print. Bazel isn't the only reason you might be running without having done ngcc

**Comment by literalpie** [comment]
That's fair. In that case, you can close this
