### ISSUE TITLE
iBazel doesn't keep node_modules after reload 

### ISSUE THREAD

**Issue by andy-zhou** [bazelbuild/rules_nodejs#2107]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: `webpack_dev_server` (and likely any generated macros)

### Description

iBazel seems to remove the `node_modules` symlink after a reload when using the `ibazel_notify_changes` tag with a generated macro.

## 🔬 Minimal Reproduction

https://github.com/andy-zhou/ibazel-webpack-example

## 🔥 Exception or Error

<pre><code>
ERROR in [...]/execroot/ibazel_webpack_example/node_modules/[...]
Module build failed: Error: ENOENT: no such file or directory, open '[...]/execroot/ibazel_webpack_example/node_modules/[...]'
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux / Ubuntu 20.04
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.6.0
Build label: 3.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Apr 6 12:52:37 2020 (1586177557)
Build timestamp: 1586177557
Build timestamp as int: 1586177557
Done in 0.09s.
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "6a67a8a1bf6fddc9113f73471029b819eef4575c3a936a4a01d57e411894d692",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/2.0.2/rules_nodejs-2.0.2.tar.gz"],
)
  </code>
</pre>

**Anything else relevant?**
This potentially blocks #2098 from working.

**Comment by andy-zhou** [comment]
Would love to dig into this - any advice on where to start looking?

**Comment by veRYANgry** [comment]
@andy-zhou This appears to not be related to bazel to me. It appears that an ibazel -> webpack connector is needed to let webpack know when to run again. From what I have read the node API can allow the creation of such a connection, but maybe this connector would be better done as a pull request into the command line interface for webpack and the dev server.

If anyone has more insight or ideas I would like to hear them. I am currently slowly working on a simple server using the node api for webpack to get this working

**Comment by andy-zhou** [comment]
In the minimal reproduction, I configured webpack to poll for exactly that reason. For some reason, the `node_modules` folder disappears on a reload though, which causes issues when `webpack_dev_server` reloads after polling.

**Comment by andy-zhou** [comment]
Hey, wanted to check in on this. This is unfortunately a pretty major blocker for our adoption of bazel. Would love to get to the bottom of this and, if helpful, toss in a PR. Any advice on where to start?

**Comment by veRYANgry** [comment]
I was successful by using a rough plugin that checks for files removed and changed. Only tested on Mac OS. Take a look:
``` js
const readline = require('readline');
const chokidar = require('chokidar');

const rl = readline.createInterface({
  input: process.stdin,
});

/**
 * Watch using chokidar, pretending anything removed is not actually gone, wait until ibazel is done then 
 * tell the compiler it is time to compile
 */
class WatchIbazelPluginFileSystem {
  constructor(options, wfs) {
    this.inputFileSystem = wfs.inputFileSystem;
    this.callbackwebpack = undefined;
    this.filesChanged = false;
    this.bazelComplete = false;
    this.options = options;
    this.changedFiles = new Map();
    this.allFiles = new Map();
    this.watcher = undefined;

    rl.on('line', input => {
      if (input.trim() === 'IBAZEL_BUILD_COMPLETED SUCCESS') {
        if (this.filesChanged === true) {
          // Warning this changes in future versions of webpack
          // take a look here https://github.com/webpack/webpack/blob/v4.43.0/lib/node/NodeWatchFileSystem.js for more info
          this.inputFileSystem.purge(Array.from(this.changedFiles.keys()));
          this.callbackwebpack(
            null,
            Array.from(this.changedFiles.keys()),
            [],
            [],
            this.allFiles,
            this.allFiles,
          new Set());
            this.filesChanged = false;
            this.bazelComplete = false;
        } else {
          this.bazelComplete = true;
        }
      }
    });
	}

  watch(files, dirs, missing, startTime, optionsz, callback, callbackUndelayed) {

    this.callbackwebpack = callback;
    // reset the watcher on new calls
    if(this.watcher !== undefined) {
      this.watcher.close();
    }
    this.changedFiles = new Map();
    this.allFiles = new Map();
    files.forEach((value) => {
      this.allFiles.set(value, startTime);
    });
    dirs.forEach((value) => {
      this.allFiles.set(value, startTime);
    });

    const options = this.options;
    const watcher = chokidar.watch(files.concat(dirs), {
      persistent: options.persistance || true,
      ignored: options.ignored || false,
      ignoreInitial: options.ignoreInitial || false,
      followSymlinks: options.followSymlinks || true,
      cwd: options.cwd || '',
      disableGlobbing: options.disableGlobbing || false,
      usePolling: options.usePolling || true,
      interval: options.interval || 200,
      binaryInterval: options.binaryInterval || 300,
      alwaysStat: options.alwaysStat || false,
      depth: options.depth || 99,
      awaitWriteFinish: {
        stabilityThreshold: options.stabilityThreshold || 2000,
        pollInterval: options.pollInterval || 100
      },

      ignorePermissionErrors: options.ignorePermissionErrors || false,
      atomic: options.atomic || true
    });
    this.watcher = watcher;
    watcher
    .on('change', (path) => {
        this.changedFiles.set(path, new Date());
        this.allFiles.set(path, new Date());
        this.filesChanged = true;      })
    .on(
      'unlink',
        (path) => {
          this.changedFiles.set(path, new Date());
          this.allFiles.set(path, new Date());
          this.filesChanged = true;
          watcher.add(path);
        }
    );

		return {
      close: () => {
        watcher.close();
      },
			pause: () => watcher.pause(),
			getContextTimeInfoEntries: () => {
				return new Map();
			},
			getFileTimeInfoEntries: () => {
				return new Map();
			}
		};
	}
}

class WatchIbazelPlugin {
	/**
	 */
  constructor(options) {
    this.options = options;
	}

	/**
	 * Apply the plugin
	 */
	apply(compiler) {
		compiler.hooks.afterEnvironment.tap("WatchIbazelPlugin", () => {
      compiler.watchFileSystem = new WatchIbazelPluginFileSystem(this.options, compiler.watchFileSystem);
		});
	}
}

module.exports = WatchIbazelPlugin;
```

**Comment by andy-zhou** [comment]
Thanks @veRYANgry. Haven't taken a look at your plugin yet, but I did some digging of my own.

It turns out that `webpack-dev-server` automatically injects [two entries](https://github.com/webpack/webpack-dev-server/blob/89ffb86cd26425c59e3937ca06a2c804a01b8f1d/lib/utils/addEntries.js#L18) for hot module replacement in the webpack config, which `webpack` then bundles and watches. Unfortunately the injection uses `require.resolve()` and therefore standard module resolution to get the filename. To my understanding, this ends up resolving to the **build** directory at `execroot/<worspace>/node_modules` instead of `<target>.sh.runfiles/npm/node_modules`.

Would love a Bazel expert's confirmation here, but I think that `node_modules` disappears because it's not used during the `ibazel` reload.

Overall, it seems like this should be something addressed on `rules_nodejs`'s side, since having `node_modules` live under `npm/` seems like it has the potential to break any tool that uses `require.resolve()`. Would love someone more familiar chime in. 

@alexeagle, I noticed your work around `--nobazel_patch_module_resolver`, which seems potentially relevant. Is there any work I could do to help?

-----

In the meantime, two potential workarounds on the webpack side:
1. Turn off [inline mode](https://webpack.js.org/configuration/dev-server/#devserverinline) to avoid the injection, then manually edit the webpack config to point the the correct entries.
2. Have a custom [webpack-dev-server](https://webpack.js.org/guides/hot-module-replacement/#via-the-nodejs-api) but use custom injection code.

**Comment by andy-zhou** [comment]
Just tried the plugin - it doesn't work because it's still trying to read from `execroot/<workspace>/node_modules`

```
ℹ ｢wdm｣: Compiling...
✖ ｢wdm｣: Hash: 0e7021cff94f1754d740
Version: webpack 4.44.1
Time: 30ms
Built at: 09/11/2020 12:20:59 PM
                                  Asset      Size  Chunks                               Chunk Names
   6d3a2bb4ef8850bfbde5.hot-update.json  46 bytes          [emitted] [immutable] [hmr]  
                          app.bundle.js  1010 KiB    main  [emitted]                    main
main.6d3a2bb4ef8850bfbde5.hot-update.js   4.3 KiB    main  [emitted] [immutable] [hmr]  main
Entrypoint main = app.bundle.js main.6d3a2bb4ef8850bfbde5.hot-update.js
[../../../../../../node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 238 bytes {main} [built] [failed] [1 error]
[../../../../../../node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 229 bytes {main} [built] [failed] [1 error]
[./example_app/index.js] 231 bytes {main} [built]
    + 12 hidden modules

ERROR in (webpack)-dev-server/client?http://localhost:8080
Module build failed: Error: ENOENT: no such file or directory, open '/home/andy/.cache/bazel/_bazel_andy/d55e6f3c2f102d8878bdf1a7f8a42d53/execroot/ibazel_webpack_example/node_modules/webpack-dev-server/client/index.js'
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./example_app/index.js main[0]

ERROR in (webpack)/hot/dev-server.js
Module build failed: Error: ENOENT: no such file or directory, open '/home/andy/.cache/bazel/_bazel_andy/d55e6f3c2f102d8878bdf1a7f8a42d53/execroot/ibazel_webpack_example/node_modules/webpack/hot/dev-server.js'
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./example_app/index.js main[1]
```

**Comment by veRYANgry** [comment]
Oh, I think you will want to pass in the entry point to the dev server using bazel:
```
webpack_dev_server(
    name = "devserver_webpack",
    args = [
        "$(rootpath main_src)", // <-- main_src is the single main js file output of the ts, this is index.mjs for me
        "--config",
        "$(execpath webpackdev.config.js)",
        "--mode",
        "development",
    ],
...
```
You can use this to grab only the mjs that end with index:
```
# A filter aspect for only using a main file from a filegroup
def _filter_srcs_impl(ctx):
    return DefaultInfo(files=depset([f for f in ctx.files.srcs if f.basename.endswith("index.mjs")]))

filter_srcs = rule(
    implementation = _filter_srcs_impl,
    attrs = {
        "srcs": attr.label_list(allow_files=True, mandatory=True),
    },
)
```

**Comment by andy-zhou** [comment]
I don't think the issue is with the source files that are being bundled, but rather the injected HMR files. It's not clear to me how adding the js output solves that. Do you have a minimal working example?

**Comment by veRYANgry** [comment]
@andy-zhou I will modify your branch when I get a chance and post it

**Comment by veRYANgry** [comment]
Looks like I get the same node modules issue, haha. I have working code with https://github.com/bazelbuild/rules_nodejs/releases/download/1.4.1/rules_nodejs-1.4.1.tar.gz and `load("@npm_bazel_typescript//:index.bzl", "ts_setup_workspace")`. I will try to put up an example when I have time

**Comment by zachgrayio** [comment]
We are also working through some issues here. What I am trying to work out is why some projects run into this issue and some do not; I'm not convinced its related to rules_nodejs version

**Comment by andy-zhou** [comment]
@zachgrayio Is it similar to what I'm describing [here](https://github.com/bazelbuild/rules_nodejs/issues/2107#issuecomment-691200365)?

It seems like part of the reason is that node's resolution algorithm doesn't work well with folder structure generated by `rules_nodejs`. The other part seems related to the fact that iBazel sometime drops `node_modules`.

**Comment by zachgrayio** [comment]
@andy-zhou not entirely sure; it's definitely the vanishing symlink that's the root problem for us, but I still don't understand why node_modules is showing up there to begin with. 

our current workaround is to restore the symlink after ibazel runs, but this is not a proper long term solution

**Comment by xnerhu** [comment]
Any update on this?

**Comment by xc2** [comment]
Related reproduction: https://github.com/xc2/GithubIssues/tree/main/bazel-rule_nodejs-craMIssingNodeModules
