### ISSUE TITLE
Generate @npm build files with restrictive visibility for transitive dependencies

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/rules_nodejs#2110]
🚀 feature request

### Relevant Rules

- `yarn_install`
- `npm_install`

### Description

By default, the generated build files for npm packages are all publicly visible: 

https://github.com/bazelbuild/rules_nodejs/blob/065922b6963f1f9401c8a7638ef11c0709635886/internal/npm_install/index.js#L14

All packages are treated the same. However, transitive dependencies that are not declared in package.json should have more restrictive visibility, say `@npm//:__subpackages__`.

### Describe the solution you'd like

Only generate `//visibility:public` for packages are declared in package.json, and use `@ws//:__subpackages__` for the rest.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by alexeagle** [comment]
Yeah that's a really good point, I think it could be considered a breaking change so maybe we should wait...
