### ISSUE TITLE
ts_project(emit_declaration_only=True) should give .d.ts in default outputs

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#2116]
This feels like it matches the developer intent.

In particular, if you build a ts_project rule, it will trivially succeed with no outputs because no .js files are produced. That's pretty confusing if you meant to use it to type-check your project.

**Comment by DavidANeil** [comment]
This could also be configured by checking a starlark tsconfig, if we go that route.

**Comment by alexeagle** [comment]
I would hope that starlark ts_config can only do the same things a tsconfig file can, otherwise the layering gets weird?
