### ISSUE TITLE
Including .d.ts folder

### ISSUE THREAD

**Issue by danielepolencic** [bazelbuild/rules_nodejs#2123]
_This is not a bug report, but a request for clarification._

I'm trying to use Bazel in a Typescript repository.
The repo has a `types` folder that contains a collection of local Typescript declarations for npm modules.

The type declarations are necessary to compile the Typescript, but I can't make them work with Bazel.

What I have tried:

- Created a `BUILD` file for the `types` folder and used the `ts_library` to "compile" the `.d.ts`s. I added the `:types` dependency to the other modules, but I still get an error that Typescript can't find the declarations.
- Managed the dependencies manually and included the `types` folder in the `node_modules` filegroup. I followed the instructions here: https://bazelbuild.github.io/rules_nodejs/install.html#using-self-managed-dependencies however, I stumbled on the same error.

I created a simple repo that should hopefully clarify what I'm trying to achieve: https://github.com/danielepolencic/bazeltest
The repository fails with `npm start` or `bazel run universal_server`.

How should I include local type declarations in Bazel?

**Comment by alexeagle** [comment]
Yeah internally at google there's a `ts_declaration` rule but it was redundant with ts_library.

You can make a `filegroup` equivalent that produces DeclarationInfo with the `ts_project` rule - put this in your `types/BUILD`
```
load("@npm//@bazel/typescript:index.bzl", "ts_project")

ts_project(
    name = "types",
    srcs = glob(["*.d.ts"]),
    source_map = True,
    tsconfig = "//:tsconfig.json",
    visibility = ["//visibility:public"],
)
```
and then I'm able to build your `//packages/a` target by adding `deps = ["//types"]`

**Comment by alexeagle** [comment]
It also seems to work if `types/BUILD` contains
```
load("@npm//@bazel/typescript:index.bzl", "ts_library")

ts_library(
    name = "types",
    srcs = glob(["*.d.ts"]),
    tsconfig = "//:tsconfig.json",
    visibility = ["//visibility:public"],
)
```
so I can't repro the problem with typescript not finding declarations brought in this way.

**Comment by danielepolencic** [comment]
Thanks, that answers my question and you can close this ticket.

I was wondering if it is better to include the types in the `node_module` filegroup because now I have to include the declarations in every ts package I use.

I'm new to Bazel and I just want to understand the trade-offs.

**Comment by alexeagle** [comment]
the `node_module` filegroup comes from installing third-party packages from npm, so that's not what you want for depending on your own code.
