### ISSUE TITLE
Can't use the output of rollup_bundle as an input to ts_library

### ISSUE THREAD

**Issue by ajbouh** [bazelbuild/rules_nodejs#2124]
#1320 🐞 bug report

### Affected Rule

`rollup_bundle` and `ts_library`

### Is this a regression?

It's unclear if this was ever possible

### Description

It seems that `rollup_bundle` emits a single tree artifact as its output (with `emit_dirs = True` and rollup plugins that emit assets).

Unfortunately `ts_library` expects all dependencies to have a `DeclarationInfo` provider. I don't know how to create a `DeclarationInfo` provider that actually works. Both `filegroup`, `pkg_npm` lack this provider.

I've tried to use a custom `node_module_library` rule with:
- an empty `DeclarationInfo` provider and
- a `LinkablePackageInfo` with a chosen `package_name`,

but it never seems to populate the directory in a way that can be imported by typescript code. I think this is because I can't provide a value for `files` that is within the given `path`, since `files` is an array of just the directory output by `rollup_bundle`.

All attempts so far have failed.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS 10.15.2
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
$ yarn bazel version
yarn run v1.22.4
$ .../node_modules/.bin/bazel version
Bazelisk version: v1.5.0
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
Build label: 3.0.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Apr 6 12:55:48 2020 (1586177748)
Build timestamp: 1586177748
Build timestamp as int: 1586177748
✨  Done in 0.34s.
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
2.0.1
  </code>
</pre>

**Comment by alexeagle** [comment]
`ts_library` deps are intended to bring in new things for the type-checker. I don't see how the output of your rollup_bundle is useful for typecheck or emit of typescript code. Could you explain the use case please?

**Comment by ajbouh** [comment]
I'm using a tool that does some basic code generation. I've been porting this tool to operate in a bazel-native fashion

The tool takes javascript (and other files) as input and generates javascript (and other files) as output. Under the hood this tool is using rollup to merge together input files with some generated intermediate code.

In my port-to-bazel effort I'm having the tool emit a rollup config that I'm passing to rollup_bundle. I have a macro that is trying to wrap all this in something that can be imported by other downstream ts_library targets in my project.

**Comment by alexeagle** [comment]
I'm still a little confused which output file from rollup is required as an input file to typescript, and why that file would provide declarations. Is rollup used to bundle `.d.ts` files or something?

So I'll just answer generally:
- If you want to turn arbitrary filegroup into DeclarationInfo, you can just list them as srcs of a trivial `ts_project` rule.
- if TypeScript needs to read the file, but it's not a declaration file, then maybe you can list in the `data` rather than `deps`

**Comment by ajbouh** [comment]
I'm essentially using rollup to dynamically generate a first party npm package. The directory structure that's generated looks something like:

```
my-thing/
my-thing/middlware.js
my-thing/middlware.d.ts
my-thing/manifest.json
my-thing/client/
my-thing/client/foo.js
my-thing/client/css.js
```

Inside of `middlware.js` are functions that reference the files in `client/`.

I expect some other (possibly Typescript) code to do something like:

```javascript
import middleware from 'path/to/my-thing`

// ...
server.use('/', middleware)
```

**Comment by alexeagle** [comment]
In that case I think you want to change the shape of your dependency graph. Probably you should typecheck your other code using the original TS sources, not the rolled-up ones.

middleware_file1.ts -> tsc -> middleware_file1.d.ts + other_code.ts -> tsc -> other_code.js
middleware_file1.d.ts + middleware_file2.d.ts -> rollup -> middleware.d.ts

is that helpful?

**Comment by ajbouh** [comment]
A bit helpful, yes. Although I'm afraid I don't understand how you're suggesting I implement this.

I'd like to be able to use this as a normal dependency in downstream artifacts without needing to do anything special or fancy in those targets to make it work.

My interpretation of your suggestion is:
- middleware-input_lib (ts_library)
- middleware-partial-bundle (rollup_bundle, depends on middleware-input_lib)
- my_express_server (ts_library)

It sounds like you're suggesting to use the .d.ts files from middleware-input_lib with the .js files from middleware-partial-bundle.

If that's the case, how do I solve the package_name problem?

The .d.ts and .js files will not be in the same directory, but must somehow be accessible under the same package_name or module_name.

**Comment by ajbouh** [comment]
Seems like would be easier and more composable to give rollup_bundle providers for all the types of things it might plausibly output
