### ISSUE TITLE
Rollup worker with rollup-plugin-terser fails

### ISSUE THREAD

**Issue by joeljeske** [bazelbuild/rules_nodejs#2127]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 

rollup_bundle with worker mode with rollup-plugin-terser

### Is this a regression?

 No

### Description

 A clear and concise description of the problem...

When using rollup_bundle with supports_worker = True and using rollup-plugin-terser, eventually you encounter: 

```
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
--
17-Aug-2020 14:27:00 | at ChildProcess.target.send (internal/child_process.js:678:16)
17-Aug-2020 14:27:00 | at ChildProcessWorker.send (/private/var/tmp/_bazel_bamboo/afb0e097bce57d29028f27f77a76a531/execroot/ns/node_modules/jest-worker/build/workers/ChildProcessWorker.js:286:17)
17-Aug-2020 14:27:00 | at WorkerPool.end (/private/var/tmp/_bazel_bamboo/afb0e097bce57d29028f27f77a76a531/execroot/ns/node_modules/jest-worker/build/base/BaseWorkerPool.js:125:24)
17-Aug-2020 14:27:00 | at JestWorker.end (/private/var/tmp/_bazel_bamboo/afb0e097bce57d29028f27f77a76a531/execroot/ns/node_modules/jest-worker/build/index.js:178:22)
17-Aug-2020 14:27:00 | at handler (/private/var/tmp/_bazel_bamboo/afb0e097bce57d29028f27f77a76a531/execroot/ns/node_modules/rollup-plugin-terser/index.js:58:23)
17-Aug-2020 14:27:00 | at processTicksAndRejections (internal/process/task_queues.js:93:5)
17-Aug-2020 14:27:00 | Emitted 'error' event on ChildProcess instance at:
17-Aug-2020 14:27:00 | at internal/child_process.js:682:35
17-Aug-2020 14:27:00 | at processTicksAndRejections (internal/process/task_queues.js:75:11) {
17-Aug-2020 14:27:00 | code: 'ERR_IPC_CHANNEL_CLOSED'
17-Aug-2020 14:27:00 | }
```

Rollup Plugin Terser uses worker threads, which cannot be disabled as far as i can tell. Eventually in this stateful worker, the workers seem disposed perhaps, and then we encounter this issue. When disabling worker mode (using --strategy OR by supports_worker=False), terser does not fail. When disabling terser and keeping worker mode, it does not fail. 

## 🔥 Exception or Error

<pre>
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
<code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS 10.14.6
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
2.1.0
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
1.6.0
  </code>
</pre>

**Anything else relevant?**

* I do not think anything relevant has changed for rollup in 2.x rules_nodejs
* I realize there is a terser specific binding for rules_nodejs, however, the rollup plugin fits fine into my system and the caching benefits are negated by almost always having propagating changes from inputs-outputs.

**Comment by alexeagle** [comment]
Yeah rollup worker mode is still experimental as we note in the docs, I'm not surprised if there are bad interactions with plugins. We don't have a full plan for promoting this feature out of experimental.

As a workaround, how about you don't use terser in your development loop, and just apply the standalone terser rule when building a production artifact?

**Comment by joeljeske** [comment]
Yea makes sense  I actually do only build with terser in "opt" mode but there are still workers being used there. Or are you suggesting that I should not be using workers for prod artifacts?

**Comment by alexeagle** [comment]
Right the workaround would be to disable workers for that optimized build.

(I wonder if we should hook --compilation_mode=opt like we do for dbg)
