### ISSUE TITLE
bazel build only works once

### ISSUE THREAD

**Issue by codesuki** [bazelbuild/rules_nodejs#2129]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
Hi there :)
I copied the `examples/react_webpack` content (except .bazelrc) and ran `bazel build //...`.
Worked without problem.
On subsequent `bazel build //...` invocations the build fails with 
```
BUILD.bazel:16:11: output 'bazel-out/host/bin/external/npm/webpack-cli/bin/webpack-cli.sh.runfiles/npm/node_modules/uri-js/src/index.js' was not created
BUILD.bazel:16:11: output 'dist/ideas/bazel-out/host/bin/external/npm/webpack-cli/bin/webpack-cli.sh.runfiles/npm/node_modules/uri-js/src/index.js' was not created
BUILD.bazel:16:11: output 'dist/out/host/bin/external/npm/webpack-cli/bin/webpack-cli.sh.runfiles/npm/node_modules/uri-js/src/index.js' was not created
BUILD.bazel:16:11: output 'node_modules/uri-js/src/index.js' was not created
```

I can fix it by deleting `node_modules` and `bazel clean`. So bazel seems to get confused if those exist.
What am I missing?

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
❯ bazel version    
Build label: 3.4.1-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jul 14 20:29:43 2020 (1594758583)
Build timestamp: 1594758583
Build timestamp as int: 1594758583
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
2.0.3
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
Looks like you're missing a `.bazelignore` ? somehow I think bazel is seeing outputs of the prior build as inputs to the subsequent build

**Comment by evahowe** [comment]
@codesuki - does this solve your problem?

**Comment by codesuki** [comment]
Thanks for the fast answer! That was it. Totally overlooked bazelignore 😅
