### ISSUE TITLE
Exclude files with spaces in bazel-managed node_modules

### ISSUE THREAD

**Issue by jwahlin** [bazelbuild/rules_nodejs#213]
Several npm packages have spaces in file names. This breaks the bazel-managed node_modules. Adding a line like this to the exclude attribute should solve the problem:
<pre>"node_modules/**/* *.*",</pre>

**Comment by jwahlin** [comment]
I don't know how much flexibility you want to provide here, but if you want to expand the flexibility, you could add an exclude attribute to yarn_install and npm_install. Or, for even greater flexibility, you could add a build_file attribute.

**Comment by alexeagle** [comment]
Actually we want to move the other way and allow any files to be valid labels. I think this is already the case in the latest Bazel, what version are you on?
```
C:\Users\alexeagle\Projects\repro213
λ bazel query "deps(//:spaces)"
//:spaces
//:some file
//:WORKSPACE
//:BUILD

C:\Users\alexeagle\Projects\repro213
λ bazel info release
release 0.12.0

C:\Users\alexeagle\Projects\repro213
λ cat BUILD
filegroup(
    name = "spaces",
    srcs = glob(["*"]),
)

C:\Users\alexeagle\Projects\repro213
λ ls
 BUILD   WORKSPACE   bazel-bin@   bazel-genfiles@   bazel-out@   bazel-repro213@   bazel-testlogs@  'some file'
```

**Comment by jwahlin** [comment]
I'm on 0.13.0. I'll try the latest and see how it goes.

I've noticed you use self-managed node_modules in angular. Is that the approach you personally would recommen?d

**Comment by alexeagle** [comment]
I think I am wrong, the repro above isn't sufficient to show that spaces aren't allowed in labels - @hansl had the same issue late last week.

Angular would like to switch to bazel-managed node_modules, I expect many projects would follow the same path of starting out more similar to web ecosystem, and as they adopt Bazel more, they'd be comfortable switching. The self-managed node_modules is really there to make the on-ramp simpler.

**Comment by gregmagolan** [comment]
Files with spaces are excluded in bazel-managed npm deps (those created with `yarn_install` or `npm_install`). The labels themselves are now legal in Bazel 0.17.1 but Bazel is not able to create a runfiles tree with these files as the MANIFEST file is space delimited (see https://github.com/bazelbuild/bazel/issues/4327).
