### ISSUE TITLE
Create a symlink for a package's BUILD.bazel file on "link:" node modules

### ISSUE THREAD

**Issue by mistic** [bazelbuild/rules_nodejs#2131]
# 🐞 bug report

### Affected Rule

`yarn_install` or `npm_install`

### Is this a regression?

 No

### Description

Currently when using managed dependencies if we declare a `link:` in our `package.json` to a local package the resulting generated `BUILD.bazel` file would be a concatenation between a common `BUILD.bazel` content for a node_module plus the content of the `BUILD.bazel` file in the linked package source code, if any. That behaviour creates a couple of problems and make the rules_nodejs not compliant with the common node development environemnt.

That would be solvable if we create a symlink for the package source `BUILD.bazel` on the npm workspace instead of generating a file. If the package source doesn't contain a `BUILD.bazel` we can still create the symlink and log a warning to let the user know he must create a `BUILD.bazel` file in order to use `link:` packages as node_modules. A possible implementation for this feature would be to look for symlinked modules at https://github.com/bazelbuild/rules_nodejs/blob/stable/internal/npm_install/generate_build_file.ts#L475 and filter those out to be processed in another function responsible for creating the symlinks for `${realpath}/BUILD.bazel`. In order to make that operation more user friendly the `BUILD.bazel` created by the user should only be needed to expose a target with the same name of the package so the implementation of that feature needs to rework a little what is being generated by https://github.com/bazelbuild/rules_nodejs/blob/stable/internal/npm_install/generate_build_file.ts#L964

## 🔬 Minimal Reproduction

There is none provided. A simple bazel setup with managed dependencies and a `link:` on the package.json for some local package to be symlinked as a node_module would be enough.

## 🔥 Exception or Error

None

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS 10.15.6
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.5.0
Build label: 3.3.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jun 17 12:59:56 2020 (1592398796)
Build timestamp: 1592398796
Build timestamp as int: 1592398796
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
rules_nodejs@2.0.3
@bazel/typescript@2.0.3
  </code>
</pre>

**Anything else relevant?**

No

**Comment by mistic** [comment]
@migueloller firstly pointed a solution like that and I've discussed the details offline with him!

**Comment by mistic** [comment]
@gregmagolan do you have any input about this one?

**Comment by staeke** [comment]
I'm also very interested in this one. Also happy to pick up work if needed. @mistic @migueloller

**Comment by mistic** [comment]
@staeke that is something definitely under my radar as it is a feature I will need to successfully complete the migration into bazel that I'm currently working on. However I still have other things to complete before looking into this one. If you have time and want to start looking into this one that will be much appreciated 😃

**Comment by mistic** [comment]
I've spent sometime looking at this and I've came up with https://github.com/mistic/rules_nodejs/commit/0d234adab1b8960fad07a9a9d4d39176e493a79e

We need to understand now how we can test this and apply some final polish into the work mentioned above

**Comment by mistic** [comment]
Closed by https://github.com/bazelbuild/rules_nodejs/pull/2330
