### ISSUE TITLE
FR: Examples of hot-reloading projects

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_nodejs#2133]
# 🚀 feature request

### Description

 A clear and concise description of the problem or missing capability...
I asked a question in the [slack channel](https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1597424643467500) but would love more input. I was playing around with the [vue example](https://github.com/bazelbuild/rules_nodejs/tree/stable/examples/vue) and a friend asked how to setup hot reloading. I tried and could not figure it out. As far as I know, `vue_cli_service` supports hot reloading but I don't know how to update the source files being served after the target is built by Bazel.

### Describe the solution you'd like

 If you have a solution in mind, please describe it.
As part of the examples already included in this project, would it be possible to add an example of hot reloading?

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?
This admittedly feels kinda "anti-bazel" so I would understand if there was no implementation that the team feels is worth recommending to people by adding an example of it here, but perhaps some examples could be added to this ticket for future readers 😄

**Comment by a-ignatov-parc** [comment]
Have you tried [`ibazel`](https://github.com/bazelbuild/bazel-watcher) with `ibazel_notify_changes` tag? 

The tag will prevent the cli from reloading and `ibazel` will update source tree when it detects any change.

**Comment by parisholley** [comment]
something about how bazel mounts files on macos doesn't get detected out of the box by webpack-dev-server, (i assume this is similar to problems in the past on trying to do file watchers on network file systems, virtualbox, etc)... i was able to fix it by just adding the ` --watch-poll` to webpack-dev-server... no need for ibazel

**Comment by UebelAndre** [comment]
Thanks guys for the suggestions 😃 I'm gonna cycle back to the project I'm working on that lead me to this question soon and try out both iBazel and `--watch-poll`. 

I also want to say I'm looking forward to #2149 going in. I think it's going to be super valuable documentation in the repo. Thanks @parisholley for starting on it 😀

**Comment by duarten** [comment]
Does the solution without `ibazel` work for when files are added?

**Comment by Aghassi** [comment]
#2431 I've taken a swing at this without using `ibazel` and using `webpack-dev-server` with `bazel run`.  It's fairly basic, and probably could use some more scrutiny. Depending on your use case, it may or may not work.

**Comment by Aghassi** [comment]
I guess we can bring it up in the weekly meeting CC @gregmagolan and @alexeagle. Just note it's very much in a "we tried" state. it's definitely a work in progress

**Comment by UebelAndre** [comment]
Any updates? I think there should definitely be 1 concrete example of how you'd do active development with the rules using hot reloading. At the very least, it'd be nice to know if user should be trying to get `react-script start`/`vue-cli-service serve`/etc... to work or if there's another recommended bazel way to do it ([ibazel](https://github.com/bazelbuild/bazel-watcher)). 

I don't think a shoulder shrug is sufficient (not suggesting that's what's going on). I think this is an important part of developing software and there should be some concrete examples of how the same workflow can be done with Bazel.

**Comment by UebelAndre** [comment]
There is still much to be desired but it seems no one cares about this other than me and I have no bandwidth to engage on this issue. I think the developer experience of many things in Bazel leaves *much* to be desired but web-dev feels like a particularly large pain-point since I think there are some extremely common practices (like hot-reloading) that's (in my opinion) still questionable or a mystery. 

Dear future readers, 
I've had some success kinda breaking away from Bazel rebuilds (`ibazel`) and using Bazel to start dev-servers but there are still numbers of edge cases there. I hope the experience improves or you're willing to share how you maintain a reasonable developer experience after switching to Bazel. I'm very interested! 😄
