### ISSUE TITLE
Add an example using Jest with TypeScript

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#2135]
Probably show `tsc` running as a separate action - although there are speed benefits to having a Babel plugin in Jest do the transpilation instead. 
Related #1761 and #1454

**Comment by vdeantoni** [comment]
I took at stab at having Jest execute the output of ts_library. You can see/clone  my [repo](https://github.com/vdeantoni/bazel_jest_typescript).
It seems the *.test.js file is not accessible at runtime, see the README.me for more details.

**Comment by fredrikredflag** [comment]
I managed to get this to fly @vdeantoni .

Some prerequisites:
- jest@24.9.0 
- This patch: https://github.com/bazelbuild/rules_nodejs/blob/stable/examples/jest/patches/jest-haste-map%2B24.9.0.patch
- jest.config.js in root and export it via `exports_files`

The jest config needed to contain `moduleNameMapper` in order to resolve mappings correctly (jest_typescript is my workspace name):
```
module.exports = {
    testEnvironment: 'node',
    reporters: ['default'],
    testMatch: ['**/*.spec.js'],
    moduleNameMapper: {
        'jest_typescript/(.*)': '<rootDir>/$1',
    },
};
```

After this is pretty straight forward, doesn't even need a custom macro.

```
load("@npm//@bazel/typescript:index.bzl", "ts_library")
load("@npm//jest-cli:index.bzl", "jest_test")

ts_library(
    name = "test_lib",
    srcs = glob([
        "**/*.ts",
    ]),
    deps = [
        "//src:src",
        "@npm//@types",
        "@npm//chai"
    ],
)

jest_test(
    name = "unit_test",
    data = [
        "//:jest.config.js",
        ":test_lib",
        "@npm//chai"
    ],
)
```

**Comment by alexeagle** [comment]
@fredrikredflag that's cool, do you have a suggestion where we could add this to our examples so other ppl can find the solution?

**Comment by fredrikredflag** [comment]
@alexeagle In order to make easy to find, maybe just add another example called `jest_typescript`?

The `moduleNameMapper` isn't the idea solution. But it works.

 I could do a PR for it.

**Comment by alexeagle** [comment]
Ideally we'd keep a smallish number of examples so maybe add to the existing Jest one? A PR would be awesome, I don't have time ...

**Comment by vdeantoni** [comment]
@fredrikredflag awesome, it worked great! thanks a lot

**Comment by mrmeku** [comment]
I'll try to land an example in the near future now that https://github.com/facebook/jest/pull/9351 is finalized
