### ISSUE TITLE
Test failures on Bazel CI

### ISSUE THREAD

**Issue by katre** [bazelbuild/rules_nodejs#214]
See the logs at: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/246#509b0233-304d-4061-a290-2a80e2809922 and https://storage.googleapis.com/bazel-buildkite-artifacts/509b0233-304d-4061-a290-2a80e2809922/internal/e2e/rollup/test/attempt_1.log

The error is:
```
Failed: Actual output in bundle.min.js doesn't match golden file bundle-min_golden.js_.
```

**Comment by alexeagle** [comment]
That test failure seems to be due to not having the `--stamp` applied - either its missing
https://github.com/bazelbuild/rules_nodejs/blob/master/tools/bazel.rc#L7
or the build is happening with `--nostamp` - how is that build configured?

**Comment by katre** [comment]
We recently changed the way that bazel.rc was handled with CI, and now it is being used. It looks like the current failures for rules_nodejs are not related to this, so I can close the issue. Thanks!
