### ISSUE TITLE
example project 'create-react-app' hangs at Starting the development server....

### ISSUE THREAD

**Issue by SamuelTJackson** [bazelbuild/rules_nodejs#2143]
I cloned this repo and tried the example [create-react-app](https://github.com/bazelbuild/rules_nodejs/tree/stable/examples/create-react-app) 
it hangs at starting the development server...
## 🔬 Minimal Reproduction
```bash
git clone https://github.com/bazelbuild/rules_nodejs.git
cd examples/create-react-app
yarn install
yarn start
```
## 🔥 Exception or Error
```bash
yarn run v1.22.4
$ ibazel run //:start
iBazel [6:08PM]: Querying for files to watch...
Loading: 0 packages loaded
Loading: 0 packages loaded

Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded

Loading: 0 packages loaded
iBazel [6:08PM]: Running //:start
Loading: 
Loading: 0 packages loaded
Analyzing: target //:start (0 packages loaded, 0 targets configured)
INFO: Analyzed target //:start (1 packages loaded, 3 targets configured).
INFO: Found 1 target...

INFO: Elapsed time: 0.367s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
INFO: Build completed successfully, 0 total actions
Loading: 
Loading: 0 packages loaded
Analyzing: target //:start (0 packages loaded, 0 targets configured)
INFO: Analyzed target //:start (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[0 / 4] [Prepa] BazelWorkspaceStatusAction stable-status.txt
Target //:start up-to-date:
  bazel-bin/start.sh
  bazel-bin/start_loader.js
  bazel-bin/start_require_patch.js
INFO: Elapsed time: 0.840s, Critical Path: 0.38s
INFO: 16 processes: 16 linux-sandbox.
INFO: Build completed successfully, 18 total actions
INFO: Build completed successfully, 18 total actions
iBazel [6:08PM]: Starting...

################################################################################
# Did you know iBazel can invoke programs like Gazelle, buildozer, and         #
# other BUILD file generators for you automatically based on bazel output?     #
# Documentation at: https://github.com/bazelbuild/bazel-watcher#output-runner  #
################################################################################

```
than it hangs on
`Starting the development server...`
## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Operating System: Arch Linux
Kernel: Linux 5.8.1-arch1-1
Architecture: x86-64

  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.6.1
Starting local Bazel server and connecting to it...
Build label: 3.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Apr 6 12:52:37 2020 (1586177557)
Build timestamp: 1586177557
Build timestamp as int: 1586177557
  </code>
</pre>

**Comment by alexeagle** [comment]
Yeah I see this too. It works with `bazel run :start` but not with `ibazel` so I think there's something different in the environment that prevents the popped-up browser window from communicating back to the server, or the server isn't listening on the expected port

**Comment by cuyl** [comment]
```sh
CI=true ibazel run //:start > stdout.log
```
This command works. I don't know why ibazel triggers the end event of the stdin.
https://github.com/facebook/create-react-app/blob/d2f813f8897ffcd2f0b0d2da75d0c44924c92f4d/packages/react-scripts/scripts/start.js#L168-L175
