### ISSUE TITLE
npm_install postinstall cannot execute any NPM packages on Windows

### ISSUE THREAD

**Issue by SkaillZ** [bazelbuild/rules_nodejs#2144]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: npm_install

### Description

The NPM postinstall script fails on Windows if any NPM executables are executed. This only happens with the `npm_install` rule, `yarn_install` seems to work fine.

## 🔬 Minimal Reproduction
* Clone the fork `https://github.com/SkaillZ/rules_nodejs`
* `cd examples/angular_npm` (contains the `angular` example adapted to use NPM instead of Yarn)
* Run any bazel command in the workspace (e.g. `bazel run dummy_test`)

## 🔥 Exception or Error

<pre><code>
> angular-bazel-example@ postinstall C:\Users\rene.buchmayer\repos\rules_nodejs\examples\angular_npm
> ngcc

The system cannot find the path specified.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-bazel-example@ postinstall: `ngcc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-bazel-example@ postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Windows 10
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.6.1
Build label: 3.4.1
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jul 14 06:32:11 2020 (1594708331)
Build timestamp: 1594708331
Build timestamp as int: 1594708331
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
2.0.3
  </code>
</pre>

**Comment by lukasholzer** [comment]
@evahowe what is the duplicate issue?

**Comment by SkaillZ** [comment]
@evahowe Could you please clarify why this issue is considered a duplicate? I'd like to keep an eye on the other issue about this problem, so it would be great if you could provide a link.

**Comment by lukasholzer** [comment]
I found somehow the Issue, nevertheless, I have no clue how to fix it.

The issue seems to be the `npm.cmd` that is executed on windows: https://github.com/bazelbuild/rules_nodejs/blob/stable/internal/npm_install/npm_install.bzl#L216 When I change this line to use the globally available npm binary instead of the one that is provided through the `npm.cmd` in `external/nodejs_windows_amd64/bin/npm.cmd` it is working.

```diff
        # Prefix filenames with _ so they don't conflict with the npm package `npm`
        repository_ctx.file(
            "_npm.sh",
            content = """#!/usr/bin/env bash
# Immediately exit if any command fails.
set -e
- (cd "{root}"; "{npm}" {npm_args})
+ (cd "{root}"; npm {npm_args})
""".format(
                root = root,
                npm = repository_ctx.path(npm),
                npm_args = " ".join(npm_args),
            ),
            executable = True,
        )
```

### Reproduction

The easiest way to reproduce this issue is:
1. blank Bazel Workspace with rules_nodejs.
2. `npm init` and `npm i -D uuid`.
3. Create a `postinstall.js` script and add following lines.
```javascript
const { resolve } = require('path');
const { execSync } = require("child_process");
const uuidBin = path.resolve('node_modules', '.bin', 'uuid');
const result = execSync(uuidBin).toString();
console.log(`Result: `, result);
```
4. Add `"postinstall": "node postinstall.js",` task to npm run scripts.

When invoked via `yarn_install` it is passing and printing a uuid. – When invoked via `npm_install` it is failing with.

```
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
        File "C:/tmp/me2bmvgk/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 276, column 13, in _npm_install_impl
                fail("npm_install failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: npm_install failed:
> test@1.0.0 postinstall C:\Users\Administrator\Desktop\test
> node postinstall.js

 (npm WARN lifecycle The node binary used for scripts is C:\Program Files\nodejs\node.exe but npm is using C:\tmp\me2bmvgk\external\nodejs_windows_amd64\bin\nodejs\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
The system cannot find the path specified.
child_process.js:660
    throw err;
    ^

Error: Command failed: C:\Users\Administrator\Desktop\test\node_modules\.bin\uuid
The system cannot find the path specified.

    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\test\postinstall.js:16:16)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 54 68 65 20 73 79 73 74 65 6d 20 63 61 6e 6e 6f 74 20 66 69 6e 64 20 74 68 65 20 70 61 74 68 20 73 70 65 63 69 66 69 65 64 2e 0d 0a>
  ],
  pid: 3348,
  stdout: <Buffer >,
  stderr: <Buffer 54 68 65 20 73 79 73 74 65 6d 20 63 61 6e 6e 6f 74 20 66 69 6e 64 20 74 68 65 20 70 61 74 68 20 73 70 65 63 69 66 69 65 64 2e 0d 0a>
}
```
