### ISSUE TITLE
How to include node builtins in rollup bundle

### ISSUE THREAD

**Issue by kalbasit** [bazelbuild/rules_nodejs#216]
I'm trying to move our application from a mix of Gulp, Webpack to Bazel, and I'm getting an error that `events` is not defined, and I'm not sure how to fix it.

Below a simplified version, and [here](https://github.com/kalbasit/bazel-reproducible/tree/master/events-not-defined) a fully reproducible workspace.

lib.ts

```TypeScript
import { EventEmitter } from "events";

const focusBlurEventEmitter = new EventEmitter();
focusBlurEventEmitter.emit('focus');
```

BUILD.bazel
```python
load("@build_bazel_rules_typescript//:defs.bzl", "ts_library")
load("@build_bazel_rules_nodejs//:defs.bzl", "rollup_bundle")

ts_library(
    name = "lib",
    srcs = ["lib.ts"],
    node_modules = "@root_node_modules//:node_modules",
    tsconfig = "//:tsconfig.json",
    visibility = ["//visibility:private"],
)

rollup_bundle(
    name = "bundle",
    entry_point = "lib",
    node_modules = "@root_node_modules//:node_modules",
    deps = [":lib"],
)
```

bundle.js (the output)

```Javascript
(function (events) {
    'use strict';
    var focusBlurEventEmitter = new events.EventEmitter();
    focusBlurEventEmitter.emit('focus');
}(events));
//# sourceMappingURL=bundle.es6.js.map
```

The above obviously does not work in a browser due to events missing. I tried setting the globals in the `rollup_bundle` to `{"events":"events"}` and `{"events":"events.EventEmitter"}` with no luck.

Isn't Rollup supposed to `browserify` the build?

**Comment by kalbasit** [comment]
@alexeagle any ideas on how to fix or workaround this?

**Comment by alexeagle** [comment]
Adding

```
    globals = {
        'events': 'events.EventEmitter'
    },
```

makes a working-looking bundle to me

`!function(t){"use strict";(new t.EventEmitter).emit("focus")}(events.EventEmitter);`

in the sense that whatever global symbol you told it to use is passed to this IIFE

**Comment by kalbasit** [comment]
@alexeagle the problem is `events` is not defined in the browser, it's only available in nodejs. I tried adding `events` to the dependencies in package.json but I got a warning about double events and still did not make it to the bundle.

**Comment by alexeagle** [comment]
Could you please give a more complete repro of what commands you run that
give an error?
If you target nodejs runtime you should generally not bundle sources.

**Comment by kalbasit** [comment]
@alexeagle I only took that javascript and run it in a browser, here's a jsfiddle for it: https://jsfiddle.net/kalbasit/s3mc0odu/

So my main question is, how to get the roll-up bundle to run in a browser?

**Comment by kalbasit** [comment]
@alexeagle I tried the `umd` module, and I did include events in the `package.json` and it still does not include the events module in it. How to pass `'preferBuiltins: false'` ?

```sh-session
$ yarn add events
$ bazel build //:bundle.umd.js
INFO: Analysed target //:bundle.umd.js (16 packages loaded).
INFO: Found 1 target...
INFO: From SkylarkAction bundle.umd.js:
WARNING: source-map-support module not installed.
   Stack traces from languages like TypeScript will point to generated .js files.

preferring built-in module 'events' over local alternative at '/home/kalbasit/.cache/bazel/_bazel_kalbasit/e8115732e5e29842fd2749f3bbc15097/external/root_node_modules/node_modules/events/events.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning                                                                                                                                                                                           
Target //:bundle.umd.js up-to-date:
  bazel-bin/bundle.umd.js
INFO: Elapsed time: 4.082s, Critical Path: 3.26s
INFO: 6 processes: 3 local, 3 processwrapper-sandbox.
INFO: Build completed successfully, 28 total actions
$ cat bazel-bin/bundle.umd.js
(function (global, factory) {
        typeof exports === 'object' && typeof module !== 'undefined' ? factory(require('events')) :
        typeof define === 'function' && define.amd ? define(['events'], factory) :
        (factory(global.events));
}(this, (function (events) { 'use strict';

const focusBlurEventEmitter = new events.EventEmitter();
focusBlurEventEmitter.emit('focus');

})));
//# sourceMappingURL=bundle.umd.js.map
```

**Comment by alexeagle** [comment]
Sorry, I still don't understand what behavior you expect. Do you want the EventEmitter API to be emulated in a browser? What do you expect the output bundle to look like?

I see there's a rollup plugin to add node builtins - https://github.com/calvinmetcalf/rollup-plugin-node-builtins - do you know whether this is what you need? I'd suggest you create a minimal example that uses vanilla rollup.config.js (with no Bazel involved) so you understand what configuration you require.

In Angular we pass plugins to this helper:
https://bazelbuild.github.io/rules_nodejs/rollup/rollup_bundle.html#write_rollup_config
in the ng_rollup_bundle rule:
https://github.com/angular/angular/blob/1eafd04eb33698b48fc3e9f2bfbfefe7d8005f92/packages/bazel/src/ng_rollup_bundle.bzl#L104
so if your usage is really unique, you can make your own rule similar to that. Or if I can understand your use case better, maybe `rollup_bundle` should do it out-of-the-box.

**Comment by kalbasit** [comment]
> Sorry, I still don't understand what behavior you expect. Do you want the EventEmitter API to be emulated in a browser? What do you expect the output bundle to look like?

The `events` module is not available in the browser, but it is provided by the [events](https://www.npmjs.com/package/events) library. The expected output is whatever I have in my code, plus the code coming from https://github.com/Gozala/events/blob/master/events.js

> I see there's a rollup plugin to add node builtins - calvinmetcalf/rollup-plugin-node-builtins - do you know whether this is what you need? I'd suggest you create a minimal example that uses vanilla rollup.config.js (with no Bazel involved) so you understand what configuration you require.

That's probably what I need, I'll try out tonight and let you know if it works.

> In Angular we pass plugins to this helper:
> bazelbuild.github.io/rules_nodejs/rollup/rollup_bundle.html#write_rollup_config
> in the ng_rollup_bundle rule:
> angular/angular:packages/bazel/src/ng_rollup_bundle.bzl@1eafd04#L104
> so if your usage is really unique, you can make your own rule similar to that. Or if I can understand your use case better, maybe rollup_bundle should do it out-of-the-box.

I'm hoping to get you a full example of what I'm trying to achieve, maybe we can add a `rollup_browserify_bundle` that would do what I need.

**Comment by eordano** [comment]
For future internauts: this has been recently made available, please see https://github.com/bazelbuild/rules_nodejs/tree/master/packages/rollup/test/plugins for an example.

**Comment by eordano** [comment]
I believe this issue can now be closed (cc: @alexeagle)

**Comment by gajus** [comment]
> For future internauts: this has been recently made possible and easy, please see https://github.com/bazelbuild/rules_nodejs/tree/master/packages/rollup/test/plugins for an example.

Not clear what this is linking to.

**Comment by gregmagolan** [comment]
@gajus rules_nodejs is no longer maintained. Please check out [rules_js](https://docs.aspect.build/rules/aspect_rules_js) instead. [rules_rollup](https://github.com/aspect-build/rules_rollup) ports over the `@bazel/rollup` rule to work with rules_js.
