### ISSUE TITLE
Add an example running integration tests on Docker-Compose services

### ISSUE THREAD

**Issue by flolu** [bazelbuild/rules_nodejs#2163]
There are good examples on how to run unit tests.
But I can't seem to figure out how properly run **integration tests across multiple services**.
I would like to start a docker-compose file and then test the API of those services.

---

It would be nice if someone could point me in the right direction here.

I've tried to use [testcontainers](https://github.com/testcontainers/testcontainers-node), but there seems to be an [issue](https://github.com/testcontainers/testcontainers-node/issues/113) when running Docker-Compose during Bazel test execution.

**Comment by mattem** [comment]
This is a pretty common ask I think with bazel, being able to 'run' a target to bring up services before starting a test. I know Dropbox have some rule sets that do this, and internally at my org we have generated scripts that will `bazel run` services before starting tests.

**Comment by flolu** [comment]
@mattem That sounds good! Is there any chance for me to see some implementations?
