### ISSUE TITLE
Following docs on Bazel does not work

### ISSUE THREAD

**Issue by cjds** [bazelbuild/rules_nodejs#2165]
# 🐞 bug report

### Affected Rule

`ts_library`

### Is this a regression?

Unknown 

### Description

Trying to use the basic example on the Bazel website does not work

https://bazelbuild.github.io/rules_nodejs/TypeScript.html#usage

## 🔬 Minimal Reproduction
WORKSPACE
```
workspace(name = 'rpicar')
http_archive(
    name = "build_bazel_rules_nodejs",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/2.0.3/rules_nodejs-2.0.3.tar.gz"],
)

load("@build_bazel_rules_nodejs//:index.bzl", "node_repositories", "yarn_install")

node_repositories(
    package_json = ["//:package.json"],
)

yarn_install(
    name = "npm",
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
)

```
BUILD
```
load("@npm//:@bazel/typescript/index.bzl", "ts_library")

ts_library(name = "greeter", srcs = [":greeter.ts"], tsconfig = ":tsconfig.json")
```

## 🔥 Exception or Error

<pre><code>
root@cjds:/rpicar/ui# bazel build greeter
ERROR: Skipping 'greeter': error loading package 'ui': cannot load '@npm//:@bazel/typescript/index.bzl': no such file
WARNING: Target pattern parsing failed.
ERROR: cannot load '@npm//:@bazel/typescript/index.bzl': no such file
INFO: Elapsed time: 0.083s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
</code></pre>

## 🌍  Your Environment

**Output of `bazel version`:**

  <code>
Build label: 3.4.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jul 14 06:27:53 2020 (1594708073)
Build timestamp: 1594708073
  </code>

**Comment by mattem** [comment]
The issue is the misplaced colon in the load statement here:
```
load("@npm//:@bazel/typescript/index.bzl", "ts_library")
``` 
should be

```
load("@npm//@bazel/typescript:index.bzl", "ts_library")
```

I searched in the docs for the load statement as it appears in this issue, but wasn't able to find it, so the docs look correct in that sense to me?

**Comment by cjds** [comment]
@mattem I did try that originally but I ran into this

```
ERROR: Label '@npm//@bazel/typescript:index.bzl' is invalid because '@bazel/typescript' is not a package; perhaps you meant to put the colon here: '@npm//:@bazel/typescript/index.bzl'?
INFO: Elapsed time: 0.035s
INFO: 0 processes.
```

That's why I switched it

**Comment by mattem** [comment]
Do you have `@bazel/typescript` in your `package.json`?
https://bazelbuild.github.io/rules_nodejs/TypeScript.html#installation

**Comment by cjds** [comment]
That fixed it.. But then the docs confuse me

>We recommend you use Bazel managed dependencies but if you would like Bazel to also install a node_modules in your workspace you can also point the node_repositories repository rule in your WORKSPACE file to your package.json

If I am `npm install @bazel/typescript`ing then how am I letting Bazel manage my dependencies?

**Comment by mattem** [comment]
Perhaps the wording in the docs can be improved here, but the `npm install` part here is to get the `@bazel/typescript` dep into your `package.json` file. It would also work if it was added manually and then `bazel build greeter` ran, as bazel would detect the change to `package.json` and run yarn / npm (in this way, the user never runs yarn / npm).
