### ISSUE TITLE
Support ts_proto_library for grpc-node?

### ISSUE THREAD

**Issue by flolu** [bazelbuild/rules_nodejs#2173]
@bazel/labs' [ts_proto_library](https://github.com/bazelbuild/rules_nodejs/tree/e87ce09c8027e8bf3c16e4a3534a7dd2b906ddb3/packages/labs/grpc_web) works perfectly for `https://github.com/grpc/grpc-web`. Is there a way to generate [grpc-node](https://github.com/grpc/grpc-node) files?

**Comment by alexeagle** [comment]
@mrmeku any thoughts?

**Comment by thesayyn** [comment]
@flolu You could use https://github.com/thesayyn/protoc-gen-ts if that works for you.

**Comment by flolu** [comment]
@thesayyn Oh, that looks good. I will try it out! :+1:

**Comment by flolu** [comment]
The [protoc-gen-ts](https://github.com/thesayyn/protoc-gen-ts) plugin by @thesayyn works really good. Thus I will close this issue.
A grpc example implementation can be found here: https://github.com/thesayyn/protoc-gen-ts/tree/master/examples/grpc
