### ISSUE TITLE
rollup_bundle not able to resolve modules from another ng_module

### ISSUE THREAD

**Issue by Toxicable** [bazelbuild/rules_nodejs#218]
Since only occurs since version `0.9.0`
ng_package throws
>ERROR: /home/fabian/Documents/monorepo-example/libs/lib2/BUILD.bazel:18:1: ng_package: Rollup //libs/lib2:npm_package failed (Exit 1)
[!] Error: Could not resolve import '@repo/lib1' from '/home/fabian/.cache/bazel/_bazel_fabian/225520c1efda9e4f79b739a415510a8f/execroot/monorepo_example/bazel-out/k8-fast
build/bin/libs/lib2/npm_package.es6/libs/lib2/index.js'

When trying to bundle a module with a dependency on another.
It worked fine on v0.8.0

I have a an mostly minimal reproduction here: 
https://github.com/Toxicable/bazel-monorepo-example
https://github.com/Toxicable/bazel-monorepo-example/commit/9e3eb44d4dfef42f2f5bc3ea59399535d75409c0
https://github.com/Toxicable/bazel-monorepo-example/blob/master/WORKSPACE#L31
To reproduce:
1. clone repo above
2. adjust the WORKSPACE to use 0.9.1
3. `bazel build libs/...`
4. adjsut WORKSPACE down to 0.8
5. `bazel build libs/...`
6. notice no error

**Comment by gregmagolan** [comment]
Prior to 0.9.1, rollup would silently fail on imports that were not resolved. I added a check to rollup_bundle so that it would error out when it couldn't resolve an import.

**Comment by gregmagolan** [comment]
@Toxicable I'll dig into this today

**Comment by Toxicable** [comment]
fixed via https://github.com/angular/angular/commit/a6e797b8f53132c3b249ff16f1d3c2bed759b08c

**Comment by gregmagolan** [comment]
Resolved by https://github.com/angular/angular/pull/24298 (https://github.com/angular/angular/commit/a6e797b8f53132c3b249ff16f1d3c2bed759b08c)
