### ISSUE TITLE
--incompatible_disallow_empty_glob and vendored_node/vendored_yarn

### ISSUE THREAD

**Issue by uri-canva** [bazelbuild/rules_nodejs#2185]
# 🐞 bug report

### Affected Rule

`node_repositories`

### Is this a regression?

Not that I know of.

### Description

`node_repositories` cannot be used with `--incompatible_disallow_empty_glob` and `vendored_node`/`vendored_yarn` at the same time as it unconditionally globs the files extracted from the node and yarn tarballs even though they won't exist if `vendored_node` and `vendored_yarn` are specified:

This is where yarn is extracted:
https://github.com/bazelbuild/rules_nodejs/blob/df18c616122fe34a0c3de02051ea6be242993778/internal/node/node_repositories.bzl#L321

This is why the extraction is skipped when specifying `vendored_yarn:
https://github.com/bazelbuild/rules_nodejs/blob/df18c616122fe34a0c3de02051ea6be242993778/internal/node/node_repositories.bzl#L303

This is where the files are globbed unconditionally:
https://github.com/bazelbuild/rules_nodejs/blob/df18c616122fe34a0c3de02051ea6be242993778/internal/node/node_repositories.bzl#L633

Same for node files.

## 🔬 Minimal Reproduction

A new project with `vendored_node` and `vendored_yarn` and `--incompatible_disallow_empty_glob` in bazelrc.

## 🔥 Exception or Error

<pre><code>
> bazel build //api/sdk/javascript:api --define=VERBOSE_LOGS=1
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 6e5e4a4a-362c-42f7-8ff4-8e18f001d83f
ERROR: /private/var/tmp/_bazel_uri/b22d7aa4485b379a1f149a8c01c57b3f/external/nodejs_darwin_amd64/BUILD.bazel:27:14: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_uri/b22d7aa4485b379a1f149a8c01c57b3f/external/nodejs_darwin_amd64/BUILD.bazel", line 25
		filegroup(name = "yarn_files", <1 more arguments>)
	File "/private/var/tmp/_bazel_uri/b22d7aa4485b379a1f149a8c01c57b3f/external/nodejs_darwin_amd64/BUILD.bazel", line 27, in filegroup
		glob(["bin/yarnpkg/**"])
glob pattern 'bin/yarnpkg/**' didn't match anything, but allow_empty is set to False.
ERROR: /private/var/tmp/_bazel_uri/b22d7aa4485b379a1f149a8c01c57b3f/external/nodejs/BUILD.bazel:5:6: Target '@nodejs_darwin_amd64//:bin/node_repo_args.sh' contains an error and its package is in error and referenced by '@nodejs//:bin/node_repo_args.sh'
ERROR: Analysis of aspect '@mypy_integration//:mypy.bzl%mypy_aspect of //api/sdk/javascript:api' failed; build aborted: Analysis failed
INFO: Elapsed time: 6.446s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (75 packages loaded, 1094 targets configured)

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G2021
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
> bazel version
Build label: 3.3.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jun 17 12:59:56 2020 (1592398796)
Build timestamp: 1592398796
Build timestamp as int: 1592398796
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
`1.4.1`
  </code>
</pre>

**Anything else relevant?**

I have not attempted to repro the bug on the latest version, but I saw what I think is the relevant code is still the same.

**Comment by alexeagle** [comment]
Fixed by #2194
