### ISSUE TITLE
Error: command failed: npm --silent install semver@^7.1.2

### ISSUE THREAD

**Issue by bduffany** [bazelbuild/rules_nodejs#2191]
# 🐞 bug report

### Description

I'm trying to migrate our repo to no longer depend on `@bazel/bazel` since it's deprecated in favor of `@bazel/bazelisk` + `.bazelversion`. So I removed `@bazel/bazel: "2.0.0"` from `package.json`, which was the incorrect version anyway (our repo has `3.1.0` listed in `.bazelversion`. But when I do this, I get the following error: https://app.buildbuddy.io/invocation/291a73e2-74eb-4abb-84ed-746c39ac194f#log

## 🔬 Minimal Reproduction

See the following branch: https://github.com/bduffany/buildbuddy/tree/bazelisk

Specifically this commit: https://github.com/bduffany/buildbuddy/commit/4af756fb29dc6f1c3157ef2a4a1c7f6241e13850

You can run `bazel build //proto:command_line_ts_proto` to get the error.

## 🔥 Exception or Error

https://app.buildbuddy.io/invocation/291a73e2-74eb-4abb-84ed-746c39ac194f#log

(--define=VERBOSE_LOGS=1 results in an upload timeout, you can run locally for verbose logs)

## 🌍  Your Environment

**Operating System:**

Ubuntu 20.04

**Output of `bazel version`:**

Bazelisk version: v1.6.1
Build label: 3.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Apr 22 10:32:27 2020 (1587551547)
Build timestamp: 1587551547
Build timestamp as int: 1587551547

**Rules_nodejs version:**

1.6.1

**Comment by alexeagle** [comment]
Buildbuddy has thrown away your log it seems, I get a 404 there. That's too bad that their retention doesn't allow for this use case of an issue that is investigated later.
Could you paste the error?

**Comment by bduffany** [comment]
Ah, sorry about that. Here is the full error:

```
Starting local Bazel server and connecting to it...
WARNING: ignoring LD_PRELOAD in environment.
INFO: Streaming build results to: https://app.buildbuddy.io/invocation/2f098900-5016-4d0e-bb66-5f35858c8d03
INFO: Analyzed target //server:server (542 packages loaded, 21260 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /home/b/.cache/bazel/_bazel_b/b1efedad95ff8a846adc47f250b077fb/sandbox
ERROR: /home/b/code/bb/buildbuddy/proto/BUILD:372:1: Action proto/command_line_ts_proto.mjs.tmpl failed (Exit 1) pbjs.sh failed: error executing command bazel-out/host/bin/rules/pbjs.sh --target static-module --wrap es6 --strict-long --out bazel-out/k8-fastbuild/bin/proto/command_line_ts_proto.mjs.tmpl proto/command_line.proto ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
installing semver@^7.1.2
Error: Command failed: npm --silent install semver@^7.1.2
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at modInstall (/home/b/.cache/bazel/_bazel_b/b1efedad95ff8a846adc47f250b077fb/sandbox/linux-sandbox/31/execroot/buildbuddy/bazel-out/host/bin/rules/pbjs.sh.runfiles/npm/node_modules/protobufjs/cli/util.js:129:19)
    at Object.exports.setup (/home/b/.cache/bazel/_bazel_b/b1efedad95ff8a846adc47f250b077fb/sandbox/linux-sandbox/31/execroot/buildbuddy/bazel-out/host/bin/rules/pbjs.sh.runfiles/npm/node_modules/protobufjs/cli/util.js:140:9)
    at Object.<anonymous> (/home/b/.cache/bazel/_bazel_b/b1efedad95ff8a846adc47f250b077fb/sandbox/linux-sandbox/31/execroot/buildbuddy/bazel-out/host/bin/rules/pbjs.sh.runfiles/npm/node_modules/protobufjs/cli/pbjs.js:7:6)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
Target //server/cmd:buildbuddy failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/b/code/bb/buildbuddy/server/cmd/BUILD:7:1 Action proto/buildbuddy_service_ts_proto.mjs.tmpl failed (Exit 1) pbjs.sh failed: error executing command bazel-out/host/bin/rules/pbjs.sh --target static-module --wrap es6 --strict-long --out bazel-out/k8-fastbuild/bin/proto/buildbuddy_service_ts_proto.mjs.tmpl proto/buildbuddy_service.proto ... (remaining 11 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 14.266s, Critical Path: 1.98s
INFO: 28 processes: 24 linux-sandbox, 4 worker.
INFO: Streaming build results to: https://app.buildbuddy.io/invocation/2f098900-5016-4d0e-bb66-5f35858c8d03
FAILED: Build did NOT complete successfully
```

**Comment by bduffany** [comment]
I can run `npm install --silent semver@^7.1.2` myself and the error goes away, but then I get more errors:

```
Error: Command failed: npm --silent install chalk@^4.0.0 tmp@^0.2.0 espree@^7.0.0 estraverse@^5.1.0
```

If I install those, the build succeeds.

Obviously I shouldn't need to manually run `npm install` if I am using Bazel though. Also I'm not sure why it's trying to do an `npm install` given that the repo is using Yarn.

**Comment by bduffany** [comment]
Also it's probably worth mentioning that the failing target is a `ts_proto_library`.

**Comment by fabcotech** [comment]
same issue here

**Comment by camoonke** [comment]
same issue here
