### ISSUE TITLE
Switch bazel workspace from build_bazel_rules_nodejs to rules_nodejs

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#2196]
This is in the Bazel rules style guide, and many rules now ship this way (go and docker are still notable exceptions)

**Comment by alexeagle** [comment]
We'll maybe do this at the end, if we have buildozer commands that mostly patch up users

**Comment by mattem** [comment]
Maybe `bind` can help migrate?

**Comment by alexeagle** [comment]
build_bazel_rules_nodejs has been effectively dead since it wasn't included in 6.0, closing.
