### ISSUE TITLE
downloading hermetic node from the bazel.build mirror fails

### ISSUE THREAD

**Issue by zachgrayio** [bazelbuild/rules_nodejs#2198]
```
 WARNING: Download from https://mirror.bazel.build/nodejs.org/dist/v12.18.3/node-v12.18.3-darwin-x64.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
```

defined here: 
https://github.com/bazelbuild/rules_nodejs/blob/42a81622ff9ada6b703777ef1291686bc7fdd665/internal/node/node_versions.bzl#L688

URL 404s: https://mirror.bazel.build/nodejs.org/dist/v12.18.3/node-v12.18.3-darwin-x64.tar.gz

not immediately clear to me what the issue is, but thought I'd file it 

edit: v2.2.0

**Comment by alexeagle** [comment]
Yeah the Bazel team hasn't provided a way for non-googlers to mirror files, or to request that they be mirrored (other than by emailing an individual)
We should probably just remove all our mirror.bazel.build links for nodejs since there's no process for it.

**Comment by mattem** [comment]
Won't fix, see https://github.com/bazelbuild/rules_nodejs/issues/2406
