### ISSUE TITLE
angular component style sourcemaps fail to load in devmode / ts_devserver

### ISSUE THREAD

**Issue by matthewjh** [bazelbuild/rules_nodejs#2206]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 

### Is this a regression?

no

### Description

`sass_binary` by default produces two files, .css and .css.map, which are siblings. In the generated css file it will append a source map URL directive referring to the .css.map file:

```css
.done{text-decoration:line-through}.edit-icon{margin-right:12px}
/*# sourceMappingURL=todos.component.css.map */
````

When the component is loaded and instantiated at runtime, Angular inserts a style tag in the `head` element containing the textual content of the css file.

```html
<head>
  <!-- ... ->
  <style>
     .done{text-decoration:line-through}.edit-icon{margin-right:12px}
    /*# sourceMappingURL=todos.component.css.map */
   </style>
</html>
```

The problem is that, on seeing this, the browser will make a request to `${BASE_URL}/todos.component.css.map`. This will fail unless the source map happens to be served at the root. 

I'm not sure how this may be fixed. `rules_sass` appears to be doing the right thing, because all it can reasonably do is specify the relative path to the css.map file, rather than speculate on the absolute path it will end up being served from.

One could argue that the Angular compiler should, on transforming the stylesheet, augment the sourceMappingURL to include path information that is later lost on head insertion, e.g. `  /*# sourceMappingURL=todos.component.css.map */` => `  /*# sourceMappingURL=path/to/css/todos.component.css.map */`

A possible solution for users of this package is to force rules_sass to inline the source maps in the CSS files. However, I don't see that option in the rules_sass docs.

The problem is nettlesome as large apps have their devtools consoles spammed up by failed css sourcemap fetches, which is very unhelpful for the signal:noise ratio and developer experience.

## 🔬 Minimal Reproduction

1. check out rules_nodejs stable
2. cd examples/angular
3. `yarn bazel run //src:devserver`
4. open the browser at the devserver url
5. wait until the browser tries to fetch css sourcemaps. you may be able to force it by opening the element inspector and expanding the `<style>` tags angular has inserted inside `<head>` 

## 🔥 Exception or Error

<pre><code>

DevTools failed to load SourceMap: Could not load content for http://pc:5432/example/hello-world.component.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

DevTools failed to load SourceMap: Could not load content for http://pc:5432/example/secondary-styles.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
3.5.0
  </code>
</pre>

**Rules_nodejs version:**

2.2

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>

  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
This feels like a problem in Angular. You could reproduce this with Angular CLI and a pair of `.css`/`.css.map` files like you get from rules_sass right?
