### ISSUE TITLE
Create TypescriptInfo Provider

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_nodejs#2208]
# 🚀 feature request

### Description

 A clear and concise description of the problem or missing capability...

I noticed https://github.com/bazelbuild/rules_rust/blob/master/wasm_bindgen/wasm_bindgen.bzl#L48 in `rules_rust` and figured it was this way because of 
I've come accross https://github.com/bazelbuild/rules_nodejs/blob/88c19f14aa2a346b539aff142259b30ee04f8930/packages/labs/protobufjs/ts_proto_library.bzl#L140
in this repo. This feels like something that should be a new provider. Is there any reason this can't be one?

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

I'd like to be able to load a provider to return in `rules_rust` from `rules_nodejs` to avoid using the legacy provider syntax.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

I can't really think of an alternative to the feature request outside of doing nothing... which would make me sad 😞

**Comment by alexeagle** [comment]
DeclarationInfo is the provider you're looking for (other compile-to-js Langs like Dart and ClosureJS can use this typings format as well)

**Comment by UebelAndre** [comment]
Do I need to worry about `es5_sources`, `es6_sources`, `transitive_es5_sources`, or  `transitive_es6_sources` which aren't in that provider?

**Comment by alexeagle** [comment]
no, DeclarationInfo is for typescript typings, but there are other providers for other purposes. See docs on them at the bottom of https://bazelbuild.github.io/rules_nodejs/Built-ins.html#declarationinfo (everything ending in "Info" is a provider)

The ones you mentioned es5_sources, es6_sources, transitive_es5_sources, or transitive_es6_sources are all deprecated and will be removed along with the "typescript" string-typed provider in ts_library.

**Comment by alexeagle** [comment]
(I closed because I think there's nothing more to do but LMK if you think rules_nodejs needs to change)
