### ISSUE TITLE
Please move from native to Skylark rules for external git/http repositories

### ISSUE THREAD

**Issue by aehlig** [bazelbuild/rules_nodejs#221]
Bazel is planning to move away from native rules for external repositories to Skylark rules, mainly because bundling every version control system in bazel does not scale. As part of this effort, we plan to submit https://bazel-review.googlesource.com/c/bazel/+/55932 soon, which will cause bazel by default to insist that the skylark versions the git and http rules for external repositories be used. This can be disabled by a flag for at least the next 6 months, but we still would appreciate if you could adopt your repository to use the Skylark versions of those rules soon.

A test run of downstream projects with that flag flip in bazel enabled can be found at https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/286

For more background, see
- the original announcement https://groups.google.com/d/topic/bazel-discuss/dO2MHQLwJF0/discussion
- and the documentation of the incompatible changes https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#remove-native-git-repository

Thanks.

**Comment by alexeagle** [comment]
I see from that "global presubmit" that my first error comes from transitive use of those native rules via the Go dependency. I can make the changes in this repo but it seems like I can't verify it's fixed until all my dependencies are fixed first.

**Comment by aehlig** [comment]
As far as I can see, the first error is the [call to the native `http_archive`](https://github.com/bazelbuild/rules_nodejs/blob/153c10d0d131589bbcab6821fd325cb1f125a242/WORKSPACE#L54). But it is true that the dependency most likely pulls in other errors, so you would have to switch to a newer version or patch those errors on import.

**Comment by mhlopko** [comment]
I don't think this is fixed: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/531#f7c6e00a-2493-442c-8cc6-918767809bf0. Please reopen and fix ideally soon, I'm disabling rules_nodejs from our downstream pipeline so we're not detecting unintentional breakages at bazel@HEAD.

**Comment by meteorcloudy** [comment]
Any progress on this?
