### ISSUE TITLE
Bazel is not working, even using the quickstart guide

### ISSUE THREAD

**Issue by v1d3rm3** [bazelbuild/rules_nodejs#2210]
# 🐞 bug report

### Is this a regression?
I don't know.

### Description
So far I haven't been able to make it work, not using the Quickstart, not even using examples in repository. All tries failed. In other project, it gives me the error: 
Compiling TypeScript (devmode) //:app failed: Worker process did not return a WorkResponse:

## 🔬 Minimal Reproduction

I followed exactly the steps in Quickstart of https://bazelbuild.github.io/rules_nodejs/, when i execute `npm run build`, it gives an error.

## 🔥 Exception or Error

<pre><code>
[.......]
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//@babel/plugin-transform-exponentiation-operator:plugin-transform-exponentiation-operator__contents
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//browserslist:browserslist__files
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//browserslist:browserslist__nested_node_modules
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//browserslist:browserslist__contents
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//@babel/plugin-transform-for-of:plugin-transform-for-of__nested_node_modules
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//@babel/plugin-transform-for-of:plugin-transform-for-of__files
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//@babel/plugin-transform-for-of:plugin-transform-for-of__contents
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//@babel/plugin-syntax-class-properties:plugin-syntax-class-properties__nested_node_modules
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//@babel/plugin-syntax-class-properties:plugin-syntax-class-properties__files
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//@babel/plugin-syntax-class-properties:plugin-syntax-class-properties__contents
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//@babel/plugin-transform-template-literals:plugin-transform-template-literals__files
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//@babel/plugin-transform-template-literals:plugin-transform-template-literals__nested_node_modules
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//@babel/plugin-transform-template-literals:plugin-transform-template-literals__contents
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//@babel/plugin-transform-sticky-regex:plugin-transform-sticky-regex__nested_node_modules
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//@babel/plugin-transform-sticky-regex:plugin-transform-sticky-regex__files
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//@babel/plugin-transform-sticky-regex:plugin-transform-sticky-regex__contents
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//@babel/plugin-transform-modules-commonjs:plugin-transform-modules-commonjs__nested_node_modules
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//@babel/plugin-transform-modules-commonjs:plugin-transform-modules-commonjs__files
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//@babel/plugin-transform-modules-commonjs:plugin-transform-modules-commonjs__contents
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//is-regex:is-regex__nested_node_modules
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//is-regex:is-regex__files    
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//is-regex:is-regex__contents 
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//@babel/preset-env:preset-env__nested_node_modules
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//@babel/preset-env:preset-env__contents
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//@babel/plugin-transform-typeof-symbol:plugin-transform-typeof-symbol__nested_node_modules
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//@babel/plugin-transform-typeof-symbol:plugin-transform-typeof-symbol__files
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//@babel/plugin-transform-typeof-symbol:plugin-transform-typeof-symbol__contents
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//object-keys:object-keys__files
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//object-keys:object-keys__nested_node_modules
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//object-keys:object-keys__contents
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//@babel/helper-create-class-features-plugin:helper-create-class-features-plugin__files
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//@babel/helper-create-class-features-plugin:helper-create-class-features-plugin__nested_node_modules
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//@babel/helper-create-class-features-plugin:helper-create-class-features-plugin__contents
DEBUG: C:/users/victo/_bazel_victo/ljl2le6h/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl:19:14: [link_node_modules.bzl] No LinkablePackageInfo for @npm//@babel/preset-env:preset-envINFO: Analyzed target //:compile (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: C:/users/victo/workspace/my_workspace/BUILD.bazel:5:6: Action app.es5.js failed (Exit 127)
/bin/bash: C:/users/victo/_bazel_victo/ljl2le6h/execroot/my_workspace/bazel-out/host/bin/external/npm/@babel/cli/bin/babel.sh: No such file or directory
Target //:compile failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.808s, Critical Path: 0.24s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
WindowsBuildLabEx                                       : 19041.1.amd64fre.vb_release.191206-1406
WindowsCurrentVersion                                   : 6.3
WindowsEditionId                                        : Professional
WindowsInstallationType                                 : Client
WindowsInstallDateFromRegistry                          : 07/06/2020 21:38:11
WindowsProductId                                        : 00330-80000-00000-AA975
WindowsProductName                                      : Windows 10 Pro
WindowsRegisteredOrganization                           :
WindowsRegisteredOwner                                  : - 
WindowsSystemRoot                                       : C:\WINDOWS
WindowsVersion                                          : 2004
WindowsUBR                                              : 508
HyperVisorPresent                                       : True
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 3.5.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Sep 2 20:16:28 2020 (1599077788)
Build timestamp: 1599077788
Build timestamp as int: 1599077788
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
"@bazel/bazelisk": {
            "version": "1.6.1",
            "resolved": "https://registry.npmjs.org/@bazel/bazelisk/-/bazelisk-1.6.1.tgz",
            "integrity": "sha512-2JpfZb6eYCGrdLdUJamncIpI4pgEAhPURYGg+rCgqoZDJxzADuOnpf/00dEBXPM2XByXNXTqsKEFN2gTaZz2mA==",
            "dev": true
        },
        "@bazel/buildifier": {
            "version": "3.5.0",
            "resolved": "https://registry.npmjs.org/@bazel/buildifier/-/buildifier-3.5.0.tgz",
            "integrity": "sha512-cbUS0/GMg57g6NIg6JekgmqVtuobYzW4aGHk7KzMS/bFZvxg6WY19JJ5UZSzGyAGDu2152oUTFbh4WN74Fz1+Q==",
            "dev": true
        },
        "@bazel/ibazel": {
            "version": "0.13.2",
            "resolved": "https://registry.npmjs.org/@bazel/ibazel/-/ibazel-0.13.2.tgz",
            "integrity": "sha512-q5fGwjTY76MLNcYpF2zEu/y1Clu4DjdjhvJM9+yDKc3+3mBlbX+uiMJYiCz5b0oSYdJTlw1QSRptTYA7CID8EQ==",
            "dev": true
        },
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
`external/npm/@babel/cli/bin/babel.sh: No such file or directory` suggests that maybe `@babel/cli` is not installed?

you say the error is `Compiling TypeScript (devmode) //:app failed: Worker process did not return a WorkResponse:` but that's truncated, the next lines are probably the interesting ones

**Comment by v1d3rm3** [comment]
I'll close this issue, i give up of using bazel for typescript.
