### ISSUE TITLE
Update zone.js to Latest Version in examples/angular

### ISSUE THREAD

**Issue by flolu** [bazelbuild/rules_nodejs#2212]
# 🚀 feature request

### Description

Currently the Angular example uses [zone.js](https://www.npmjs.com/package/zone.js) version 0.10.3
https://github.com/bazelbuild/rules_nodejs/blob/5478dabbb428a60cb353ef5f4d9ee8d6d44caba3/examples/angular/package.json#L27

### Describe alternatives you've considered

I've tried to upgrade the version, but this line
https://github.com/bazelbuild/rules_nodejs/blob/5478dabbb428a60cb353ef5f4d9ee8d6d44caba3/examples/angular/src/BUILD.bazel#L85

throws an error after upgrading to 0.11.1

```
ERROR: no such target '@npm//:node_modules/zone.js/dist/zone.min.js': target 'node_modules/zone.js/dist/zone.min.js' not declared in package ''
```

Is there any reason why it is not yet updated to a later version? (e.g. 0.11.1)
What would I need to change to upgrade?

**Comment by mattem** [comment]
Looking in the node_modules folder, it seems like that zone.js has changed the structure of the published artifacts (the `dist` folder now contains folders with `packages.json` references)

The label would be `@npm//:node_modules/zone.js/fesm2015/zone.min.js` for the fesm2015 bundle, or `@npm//:node_modules/zone.js/umd/zone.min.js` for UMD.

As for updating, those labels would need to change, plus a few other references in the repo.
One thing I did note that was generating an Angular app with the Angular CLI (`10.1.4`) still generates a `package.json` file with zone.js@~0.10.2, are we sure that ~0.11.0 is fully compatible?

**Comment by JiaLiPassion** [comment]
Yeah, zone.js update to the `Angular Package format` from `0.11.x`, I will update this part.

**Comment by 1057189519** [comment]
So can someone tell me how to upgrade zone.js? Thanks!

**Comment by 1057189519** [comment]
@JiaLiPassion How to use the npm command to upgrade zone.js, if not, how to upgrade it? Thanks!
