### ISSUE TITLE
Provide Example for Angular Elements

### ISSUE THREAD

**Issue by flolu** [bazelbuild/rules_nodejs#2216]
# 🚀 feature request

I was wondering if it is possible to use the [angular example](https://github.com/bazelbuild/rules_nodejs/tree/stable/examples/angular) to build [Angular elements](https://angular.io/guide/elements)?

Can I just use the [angular example](https://github.com/bazelbuild/rules_nodejs/tree/stable/examples/angular) and add [@angular/elements](https://www.npmjs.com/package/@angular/elements) to it?
Are there other considerations which would make this harder?

**Comment by alexeagle** [comment]
No idea, you should give it a try and ask in `#angular` on bazel slack if you run into issues.

/cc @robwormald :)

**Comment by Serginho** [comment]
@flolu Did you achieve that?

**Comment by flolu** [comment]
@Serginho Unfortunately not.
But I didn't really try hard, because the projects goal shifted and Elements is no longer required.
