### ISSUE TITLE
What Is The Recommended Way of Building Angular Applications?

### ISSUE THREAD

**Issue by flolu** [bazelbuild/rules_nodejs#2218]
I want to build my Angular applications with Bazel in production.

But currently I am unsure if I should use [examples/angular](https://github.com/bazelbuild/rules_nodejs/tree/stable/examples/angular) or rather [examples/angular_bazel_architect](https://github.com/bazelbuild/rules_nodejs/tree/stable/examples/angular_bazel_architect).

Are there any considerations before using any of them in production?
- examples/angular_bazel_architect definitely seems easier to setup and maintain
- but examples/angular seems to be used more by production applications

**Comment by alexeagle** [comment]
https://bazelbuild.github.io/rules_nodejs/examples.html#angular
Is meant to explain the tradeoffs and is linked from the readme of each example.

Can you help me understand what to clarify there?

**Comment by flolu** [comment]
@alexeagle That link pretty much answers my question, thank you!
