### ISSUE TITLE
yarn_install time out with large dependency amount

### ISSUE THREAD

**Issue by kyubisation** [bazelbuild/rules_nodejs#2231]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 
yarn_install (would probably also happen with npm_install)

### Is this a regression?

 No

### Description

With a large amount of dependencies in a project, yarn_install results in a "Timed out".
More precisely it is the [_create_build_files](https://github.com/bazelbuild/rules_nodejs/blob/2.2.0/internal/npm_install/npm_install.bzl#L113) execute, which calls [generate_build_file.ts](https://github.com/bazelbuild/rules_nodejs/blob/2.2.0/internal/npm_install/generate_build_file.ts) (in my test it timed out during [findPackages()](https://github.com/bazelbuild/rules_nodejs/blob/2.2.0/internal/npm_install/generate_build_file.ts#L95)). 

It works, if I extend the timeout for the `repository_ctx.execute` in `_create_build_files`.

## 🔬 Minimal Reproduction

Tested with https://github.com/angular/components
`bazel build src/cdk/bidi`

## 🔥 Exception or Error

<pre><code>

INFO: Repository npm instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule yarn_install defined at:
  /home/lukas/.cache/bazel/_bazel_lukas/14787a90d7607eee821eb51658cd0614/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:450:16: in <toplevel>
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
        File "/home/lukas/.cache/bazel/_bazel_lukas/14787a90d7607eee821eb51658cd0614/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 448
                _create_build_files(<4 more arguments>)
        File "/home/lukas/.cache/bazel/_bazel_lukas/14787a90d7607eee821eb51658cd0614/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 162, in _create_build_files
                fail(<1 more arguments>)
generate_build_file.ts failed:
STDOUT:

STDERR:
Timed out
ERROR: no such package '@npm//': Traceback (most recent call last):
        File "/home/lukas/.cache/bazel/_bazel_lukas/14787a90d7607eee821eb51658cd0614/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 448
                _create_build_files(<4 more arguments>)
        File "/home/lukas/.cache/bazel/_bazel_lukas/14787a90d7607eee821eb51658cd0614/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 162, in _create_build_files
                fail(<1 more arguments>)
generate_build_file.ts failed:
STDOUT:

STDERR:
Timed out
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
WSL 2 Ubuntu 20.04 (Windows 10)
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.6.0
Build label: 3.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Apr 22 10:32:27 2020 (1587551547)
Build timestamp: 1587551547
Build timestamp as int: 1587551547
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
2.2.0
  </code>
</pre>

**Anything else relevant?**

**Comment by kyubisation** [comment]
@alexeagle Thank you very much for the fix. This might simply be caused by performance limitations in WSL.

**Comment by arnaudgibert** [comment]
I still got the problem even with this fix. So for future references, doing a simple `bazel clean` can save you a lot of trouble. 😉

**Comment by kyubisation** [comment]
Also a lesson learned; I previously used the mounted Windows drives from WSL, which is extremely slow and generally not recommended (for this use case). I have since switched to directly using the WSL file system.

**Comment by arnaudgibert** [comment]
And for those who still use wsl1 try wsl2 which is way faster for I/O on drive.
