### ISSUE TITLE
npm_package_bin unable to see file exposed in `data` field

### ISSUE THREAD

**Issue by WesleyYue** [bazelbuild/rules_nodejs#2241]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 
npm_package_bin

### Is this a regression?

No

### Description

 A clear and concise description of the problem...

What I would like to do is to use ts_library with Vue's Single File Components (SFC). Currently, bazel supports Vue SFC by [handing over all control to the vue cli tool](https://github.com/bazelbuild/rules_nodejs/blob/8bbc27bbdf3999fc5fb9d751279e102dbf3a9149/examples/vue/BUILD.bazel#L27) installed through npm. This means that the Vue cli needs to ingest all the related source which means you can't re-use existing bazel targets (for example, if I have existing ts_library targets). imo this defeats the point of bazel, and I might as well just be calling vue cli natively. 

Because I have existing code already built through ts_library targets, I would like to use bazel to handle the ts transpilation, then use webpack to bundle the .vue SFCs and js targets from the ts transpilation. However, including the .vue SFC files in the data field of the autogenerated webpack-cli bazel rule does not expose the .vue files to webpack, and the build fails.

## 🔬 Minimal Reproduction

[See this git repo to reproduce the error.](https://github.com/WesleyYue/bazel-vue-webpack-typescript)

## 🔥 Exception or Error

I run into the following error:
```root@f9c6dd5796bf:/data/bazel-vue-webpack-typescript# bazel build //:bundle
INFO: Analyzed target //:bundle (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /data/bazel-vue-webpack-typescript/BUILD.bazel:24:1: Action app.bundle.js failed (Exit 2) webpack-cli.sh failed: error executing command bazel-out/host/bin/external/npm/webpack-cli/bin/webpack-cli.sh bazel-out/k8-fastbuild/bin/moduleA.mjs bazel-out/k8-fastbuild/bin/moduleA_ts.externs.js --config ./webpack.config.js -o ... (remaining 6 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Hash: 11f7893bb625a1ba88d9
Version: webpack 4.44.2
Time: 70ms
Built at: 10/18/2020 8:19:17 PM
        Asset      Size  Chunks             Chunk Names
app.bundle.js  6.07 KiB    main  [emitted]  main
Entrypoint main = app.bundle.js
chunk {main} app.bundle.js (main) 477 bytes [entry] [rendered]
    > main
 [0] multi ./bazel-out/k8-fastbuild/bin/moduleA.mjs ./bazel-out/k8-fastbuild/bin/moduleA_ts.externs.js 40 bytes {main} [depth 0] [built]
     multi entry
 [./bazel-out/k8-fastbuild/bin/moduleA.mjs] 437 bytes {main} [depth 1] [built]
     [no exports]
     single entry /root/.cache/bazel/_bazel_root/06a14c3cc09f26b19c2ba4d6cef531f2/sandbox/linux-sandbox/9/execroot/vue/bazel-out/k8-fastbuild/bin/moduleA.mjs [0] multi ./bazel-out/k8-fastbuild/bin/moduleA.mjs ./bazel-out/k8-fastbuild/bin/moduleA_ts.externs.js main[0]
 [./bazel-out/k8-fastbuild/bin/moduleA_ts.externs.js] 0 bytes {main} [depth 1] [built]
     single entry /root/.cache/bazel/_bazel_root/06a14c3cc09f26b19c2ba4d6cef531f2/sandbox/linux-sandbox/9/execroot/vue/bazel-out/k8-fastbuild/bin/moduleA_ts.externs.js [0] multi ./bazel-out/k8-fastbuild/bin/moduleA.mjs ./bazel-out/k8-fastbuild/bin/moduleA_ts.externs.js main[1]

LOG from webpack.buildChunkGraph.visitModules
<t> prepare: 0.489757ms
<t> visiting: 0.136489ms

ERROR in ./bazel-out/k8-fastbuild/bin/moduleA.mjs
Module not found: Error: Can't resolve './App.vue' in '/root/.cache/bazel/_bazel_root/06a14c3cc09f26b19c2ba4d6cef531f2/sandbox/linux-sandbox/9/execroot/vue/bazel-out/k8-fastbuild/bin'
resolve './App.vue' in '/root/.cache/bazel/_bazel_root/06a14c3cc09f26b19c2ba4d6cef531f2/sandbox/linux-sandbox/9/execroot/vue/bazel-out/k8-fastbuild/bin'
  No description file found
  No description file found
  no extension
    /root/.cache/bazel/_bazel_root/06a14c3cc09f26b19c2ba4d6cef531f2/sandbox/linux-sandbox/9/execroot/vue/bazel-out/k8-fastbuild/bin/App.vue doesn't exist
  .wasm
    /root/.cache/bazel/_bazel_root/06a14c3cc09f26b19c2ba4d6cef531f2/sandbox/linux-sandbox/9/execroot/vue/bazel-out/k8-fastbuild/bin/App.vue.wasm doesn't exist
  .mjs
    /root/.cache/bazel/_bazel_root/06a14c3cc09f26b19c2ba4d6cef531f2/sandbox/linux-sandbox/9/execroot/vue/bazel-out/k8-fastbuild/bin/App.vue.mjs doesn't exist
  .js
    /root/.cache/bazel/_bazel_root/06a14c3cc09f26b19c2ba4d6cef531f2/sandbox/linux-sandbox/9/execroot/vue/bazel-out/k8-fastbuild/bin/App.vue.js doesn't exist
  .json
    /root/.cache/bazel/_bazel_root/06a14c3cc09f26b19c2ba4d6cef531f2/sandbox/linux-sandbox/9/execroot/vue/bazel-out/k8-fastbuild/bin/App.vue.json doesn't exist
  as directory
    /root/.cache/bazel/_bazel_root/06a14c3cc09f26b19c2ba4d6cef531f2/sandbox/linux-sandbox/9/execroot/vue/bazel-out/k8-fastbuild/bin/App.vue doesn't exist
[/root/.cache/bazel/_bazel_root/06a14c3cc09f26b19c2ba4d6cef531f2/sandbox/linux-sandbox/9/execroot/vue/bazel-out/k8-fastbuild/bin/package.json]
[/root/.cache/bazel/_bazel_root/06a14c3cc09f26b19c2ba4d6cef531f2/sandbox/linux-sandbox/9/execroot/vue/bazel-out/k8-fastbuild/bin/App.vue/package.json]
[/root/.cache/bazel/_bazel_root/06a14c3cc09f26b19c2ba4d6cef531f2/sandbox/linux-sandbox/9/execroot/vue/bazel-out/k8-fastbuild/bin/App.vue]
[/root/.cache/bazel/_bazel_root/06a14c3cc09f26b19c2ba4d6cef531f2/sandbox/linux-sandbox/9/execroot/vue/bazel-out/k8-fastbuild/bin/App.vue.wasm]
[/root/.cache/bazel/_bazel_root/06a14c3cc09f26b19c2ba4d6cef531f2/sandbox/linux-sandbox/9/execroot/vue/bazel-out/k8-fastbuild/bin/App.vue.mjs]
[/root/.cache/bazel/_bazel_root/06a14c3cc09f26b19c2ba4d6cef531f2/sandbox/linux-sandbox/9/execroot/vue/bazel-out/k8-fastbuild/bin/App.vue.js]
[/root/.cache/bazel/_bazel_root/06a14c3cc09f26b19c2ba4d6cef531f2/sandbox/linux-sandbox/9/execroot/vue/bazel-out/k8-fastbuild/bin/App.vue.json]
 @ ./bazel-out/k8-fastbuild/bin/moduleA.mjs 1:0-28 2:12-15
 @ multi ./bazel-out/k8-fastbuild/bin/moduleA.mjs ./bazel-out/k8-fastbuild/bin/moduleA_ts.externs.js
Target //:bundle failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.797s, Critical Path: 1.54s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

Running with --sandbox_debug and looking in the sandbox directory, I can confirm that App.vue does not show up in the directory. I expected it to show up since it was included in a data field. I dug through the [bazel code](https://github.com/bazelbuild/rules_nodejs/blob/ddd527a66f5489890aec924f99b0bc2e56abcf06/internal/node/npm_package_bin.bzl#L42) and it seems that everything in data should be expected as an input to the rule (and I can confirm this because when I add :App.vue to the "outs" of the rule, it complains about it being both an input and output). I also tried wrapping it in a filegroup rule as show [here](https://github.com/bazelbuild/rules_nodejs/blob/8bbc27bbdf3999fc5fb9d751279e102dbf3a9149/examples/vue/src/BUILD.bazel), since the vue_cli_service where this is referenced should also be based on npm_package_bin. However, that didn't work either.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Debian Buster
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 3.1.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sun Oct 18 00:07:26 2020 (1602979646)
Build timestamp: 1602979646
Build timestamp as int: 1602979646
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
1.7.0
  </code>
</pre>

**Anything else relevant?**

**Comment by MaxAlex** [comment]
I've just hit the same issue in my very first use of rules_nodejs. My understanding is that bazel doesn't put the argument files to a genrule in the execution path; as per https://docs.bazel.build/versions/master/be/make-variables.html, they're in a subdirectory of the execution path that depends on the bazel project structure.  So if you're trying to run something that expects its inputs to the in the current directory, that causes this error.

In the case of webpack, I think you _should_ be able to make it use an alternate base path (the directory of your input file) through the "--context" flag, something like
```
    args = [
        "--context",
        "$$(dirname $(location input.js))"
        "--entry",
        "$(location input.js)",
       ...
    ],
```
...except that, as it turns out, npm_package_bin parses the substitution command into "$(dirname" and "$(location input.js)", causing it to fail.  This is due to the call to .split(" ") at https://github.com/bazelbuild/rules_nodejs/blob/stable/internal/node/npm_package_bin.bzl#L31

I haven't been able to find a workaround, unless I'm missing something this seems like a fairly serious issue?

**Comment by WesleyYue** [comment]
@MaxAlex I don't think that is the issue. The `context` flag in webpack is only used to resolve `entry` and `loaders`. If the entry point can be correctly resolved, webpack should be able to resolve the imports that the entry point references, relative to the entry point's file location. In our case, $(execpath entry.js) gives the relative path of `./bazel-myproject/foo/bar/entry.js` where bazel is executing the command in the directory that contains `bazel-myproject`, so the entry point resolves fine. As a further example, see this [example](https://github.com/bazelbuild/rules_nodejs/blob/065922b6963f1f9401c8a7638ef11c0709635886/examples/react_webpack/BUILD.bazel). While it only specifies the entry point of `index.js`, webpack-cli can resolve `styles.css` by inferring that it should be in the same directory as `index.js` based on how it is being imported in `index.js`.

As I mentioned,

>Running with --sandbox_debug and looking in the sandbox directory, I can confirm that App.vue does not show up in the directory.

What I'm seeing is that the App.vue file actually does not show up in the execpath at all, and my guess is that maybe there is some filtering in the npm_package_bin wrapper of genrule that only allows files named a certain way to get through (ex. js or css files only).
