### ISSUE TITLE
Add attribute on ts_proto_library that defines protoc `Wire Format Mode`

### ISSUE THREAD

**Issue by andre-cunha** [bazelbuild/rules_nodejs#2244]
# 🐞 bug report

### Affected Rule
labs/ts_proto_library

### Description

ts_proto_library always set `protoc` wire format mode as `grpcweb`. [code implementation](https://github.com/bazelbuild/rules_nodejs/blob/stable/packages/labs/grpc_web/ts_proto_library.bzl#L71)

This format can only support grpc unary services. [description](https://github.com/grpc/grpc-web#wire-format-mode) - [bug](https://github.com/grpc/grpc-web/issues/281).

It would be nice to have a ts_proto_library attribute to set `mode=[grpcwebtext|grpcweb]` so streaming services can be used.

**Comment by alexeagle** [comment]
https://github.com/bazelbuild/rules_nodejs/pull/1720 already out for this
