### ISSUE TITLE
Possibility to have authentication when downloading nodejs and yarn

### ISSUE THREAD

**Issue by KrauseStefan** [bazelbuild/rules_nodejs#2262]
# 🚀 feature request

### Relevant Rules

`node_repositories`

### Description
It is currently not possible to add authentication when downloading nodejs and yarn.
On our project we are building code in an environment disconnected from the internet, we use a package repository to store artefacts, this artifact server has authentication enabled.

I therefor request support for downloading using basic authentication when downloading artefacts using the `node_repositories` rule.

### Describe the solution you'd like

I have created a patch that we currently use for adding support for authentication.
See https://github.com/KrauseStefan/rules_nodejs/commit/6ce4d6fcc068a408c665955a43d4f36616b76630

is this something you would be interested in adopting?

**Comment by alexeagle** [comment]
Sure, looks good to wire that auth attribute for users to set it.

**Comment by KrauseStefan** [comment]
I've now opened a pull request
