### ISSUE TITLE
Version the docsite

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#2267]
When we ship 3.0 it would be really nice to still host the 2.x docs in a nice way for users to reference.

Maybe need to copy everything to a subdirectory before running Jekyll. Relative paths need to stay relative and need to verify they stay within the subdir.

**Comment by alexeagle** [comment]
Going to do something hacky to keep a 2.0 docsite running. Punting a proper solution down the road.

**Comment by mattem** [comment]
No, bad bot.

**Comment by mattem** [comment]
rnj docs will use the Aspect site for 4.0.0

Closed via #2727
