### ISSUE TITLE
Self-contained nodejs binary

### ISSUE THREAD

**Issue by fparga** [bazelbuild/rules_nodejs#2270]
Is there a way to build a self-contained nodejs binary with bazel? Something equivalent to `subpar` or `--build_python_zip` with python.

**Comment by DavidANeil** [comment]
I think I asked this once on Slack and was led toward `pkg_npm` which can be consumed by some docker rules, maybe?

I ended up just skipping `nodejs_binary` entirely and using `pkg_tar` on our bundler's single js file + node_modules.

**Comment by evahowe** [comment]
@fparga does this solve your problem?

**Comment by fparga** [comment]
Well, I haven't found exactly what I was looking for, but I think the suggestions I got are appropriate alternatives.
I think you can close.
