### ISSUE TITLE
ts_project worker support in Windows

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#2277]
We are landing a partially-finished Persistent Worker support for `ts_project` without Windows, because we haven't figured out the API to use. 

We should try PsSuspend for this as suggested by @mistic  in https://github.com/bazelbuild/rules_nodejs/pull/2136#issuecomment-698286168

**Comment by KrauseStefan** [comment]
For anyone else subscribe to this issue, this was fixed in #2416
