### ISSUE TITLE
Better Bazel Angular example using ngrx

### ISSUE THREAD

**Issue by stephanwlee** [bazelbuild/rules_nodejs#2280]
# 🚀 feature request

### Relevant Rules

- karma_web_test_suite
- ts_library

### Description

Please expand the Angular example with usage of `@ngrx/store`.

### Describe the solution you'd like

Trying to upgrade from Angular 9 to 10 and it seems like the upgrade requires a lot of underlying infrastructure upgrade as well. While upgrading, I hit a hard roadblock where karma test incorrectly bundles in non-UMD sources of `@ngrx/*`. 

In the past, I've found the examples to be quite self explanatory and inspiring and I definitely appreciate that (thanks Alex Eagle). However, The example currently does not exercise the code enough and it may not have uncovered a bug that I am facing.

#### Symptoms

- When executing a karma test with `@ngrx/store` dependency, it bundles in `esm2015/src/store_module.ngfactory.js` which is incompatible with concatjs

#### Things I've debugged

Disclaimer: lack complete understanding of bazel and the rules.

- Noted the esm2015 files in the karma_test_wrapped_test.conf.js
- Put a print statement in https://github.com/bazelbuild/rules_nodejs/blob/bc36519086536e1576c7b0657437dccced397782/packages/karma/karma_web_test.bzl#L221 and noted that the esm2015 files are included as part of the `files`
- run `bazel build @npm//@ngrx/store` and in the generated `BUILD.bazel` file, I noticed the `"//:node_modules/@ngrx/store/esm2015/src/store_module.ngfactory.js",` included as part of `store__contents`. This looked suspicious and manually removed to see if it solves anything. Without understanding how this interplays with the rules, I suspect that karma rule is supposed to only collect specific type of files (UMD) from the dependency chain but it is grabbing everything attached to `ctx.files`?

### Describe alternatives you've considered

Abandon bazel-angular integration and just use angular CLI which is very inconvenient since we are completely bought into bazel.

**Comment by flolu** [comment]
I can confirm. I am encountering similar issues (#2320) when upgrading from NgRx 9 to 10.

**Comment by flolu** [comment]
@stephanwlee Were you able to fix this issue? I am still encountering similar problems
