### ISSUE TITLE
ts_project allow_js option breaks when there is a .d.ts file

### ISSUE THREAD

**Issue by lencioni** [bazelbuild/rules_nodejs#2281]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: ts_project

### Is this a regression?

 No, allow_js is a new feature in 2.3.0 which was just published.

### Description

 

When using ts_project with allow_js set to True, Bazel will fail when it in encounters a .js file that also has a .d.ts file, because the .d.ts file is used as both an input and output.

> Error in rule: rule 'foo_types' has file 'foo/bar.d.ts' as both an input and an output

## 🔬 Minimal Reproduction

Set up ts_project with allow_js = True, and then make a foo.js and foo.d.ts file in the project.

## 🔥 Exception or Error

<pre><code>
Error in rule: rule 'foo_types' has file 'foo/bar.d.ts' as both an input and an output
</code></pre>

## 🌍  Your Environment

**Operating System:**

N/A

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: 1.5.0
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Build label: 3.7.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Oct 20 13:31:07 2020 (1603200667)
Build timestamp: 1603200667
Build timestamp as int: 1603200667
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
2.3.0
  </code>
</pre>

**Anything else relevant?**

I believe we want `_is_ts_src` to exclude .js and .jsx files that also have .d.ts files

https://github.com/bazelbuild/rules_nodejs/blob/423ef7335c8821096cc20d79c8b0d4d758a7be86/packages/typescript/internal/ts_project.bzl#L309-L312

**Comment by alexeagle** [comment]
What does typescript do in this case? Does it write a .d.ts file to the outdir and ignore the source .d.ts? Or does it assume the input is already typed and skip the declaration emit?

**Comment by alexeagle** [comment]
trying this myself, `tsc` doesn't even try to emit
```error TS5055: Cannot write file '/Users/alex.eagle/Projects/rules_nodejs/packages/typescript/test/ts_project/allow_js/a.d.ts' because it would overwrite input file.```
so I think you can't do this under vanilla TypeScript either. That suggests to me that maybe we are doing the right thing.

**Comment by mattinsler** [comment]
OK, so I the main difference here (when running `tsc` directly) is whether the output directory is different from the source directory. If you add an outDir to the command line then you shouldn't see that error.

```shell
~/rules_nodejs $ tsc --outDir /tmp/foo -p packages/typescript/test/ts_project/allow_js/tsconfig.json
```

In bazel's context, this would always be the case because the out directory is always different. The one caveat here could be if we make the declaration_dir different from the out_dir, but we can leave that for another exercise.

I think the real issue here is that we're declaring the `.d.ts` files in `typings_outs` up front, so bazel will have an issue. If we don't declare the outputs and just derive them in the rule implementation, this should work as expected.

Is there a good reason for pre-defining the output files here? I'm still too new to bazel to understand that trade-off.

**Comment by lencioni** [comment]
@alexeagle what do you think the best next steps are here?

**Comment by evahowe** [comment]
@alexeagle - ping!  Can you follow up on this?

**Comment by lencioni** [comment]
FWIW, we only had a handful of places where we were running into this and I've since just removed the problematic code so this issue is currently not affecting us (though I believe it is still an issue that should be addressed). My current focus is on landing https://github.com/bazelbuild/rules_nodejs/pull/2384

**Comment by maapteh** [comment]
For the one which lands here from search engine, we encountered this issue too with Bazel. Solved by removing our own main index.d.ts file and include the references in the index.ts file

```
/// <reference path="./generated-schema-spa.d.ts" />
...snip
```

This way the typings are included in the main package, while still keeping your own types. And Bazel will build.
