### ISSUE TITLE
Inconsistent node module resolution for npm packages

### ISSUE THREAD

**Issue by duarten** [bazelbuild/rules_nodejs#2286]
# 🐞 bug report

### Affected Rule

Rules generated for npm packages in node_modules.

### Is this a regression?

Unsure.

### Description

When a `nodejs_binary` wraps a NPM package, the binary is run out of `external/npm/node_modules`. If that binary happens to require runfiles, then modules required by those runfiles can be satisfied from `execroot/{wksp}/node_modules`. This leads to duplicate modules being loaded/bundled.

For example, running Nextjs through Bazel results in Webpack bundling two React's, which causes failures with hooks.

## 🔬 Minimal Reproduction

Consider the following files:

`WORKSPACE`:
```starlark
workspace(
    name = "repro",
    managed_directories = {"@npm": ["node_modules"]},
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

rules_node_version = "2.3.0"

http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "452bef42c4b2fbe0f509a2699ffeb3ae2c914087736b16314dbd356f3641d7e5",
    urls = [
        "https://github.com/bazelbuild/rules_nodejs/releases/download/{}/rules_nodejs-{}.tar.gz"
            .format(rules_node_version, rules_node_version),
    ],
)

load("@build_bazel_rules_nodejs//:index.bzl", "yarn_install")

yarn_install(
    name = "npm",
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
)
```

`BUILD.bazel`:
```starlark
load("@npm//next:index.bzl", "next")

next(
    name = "app",
    data = ["pages/index.jsx"],
    templated_args = ["build", "--node_options=--preserve-symlinks-main"],
)
```

`package.json`:
```json
{
    "name": "repro",
    "version": "0.1.0",
    "private": true,
    "devDependencies": {
        "@bazel/bazelisk": "1.7.3",
        "next": "10.0.1",
        "react": "17.0.1",
        "react-dom": "17.0.1"
    }
}
```

`pages/index.jsx`:
```js
import React from "react"

const Home = () => <div>Hello, World!</div>

export default Home
```

Running the rule causes Nextjs to be executed under `external/npm/node_modules`. All modules loaded by Nextjs are resolved inside that folder. Then, through Webpack, the `pages/index.jsx` file is loaded, in `execroot/repro/bazel-out/darwin-fastbuild/bin/dev.sh.runfiles/repro`. Modules loaded from this directory are resolved in `execroot/repro/node_modules`.

If feels like `nodejs_binary` could detect whether the entry point belongs to a source file or to a npm binary, and if the latter, adjust it so it points inside the execroot. Not sure what this could break though?

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
  macos
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.7.3
Build label: 3.7.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Oct 20 13:31:07 2020 (1603200667)
Build timestamp: 1603200667
Build timestamp as int: 1603200667
  </code>
</pre>

**Rules_nodejs version:**

<pre>
  <code>
2.3.0
  </code>
</pre>

**Comment by duarten** [comment]
Indeed, a comment in `link_node_modules.ts` says:

> Under runfiles, the linker should symlink node_modules at `execroot/my_wksp` so that when there are no runfiles (default on Windows) and scripts run out of `execroot/my_wksp` they can resolve node_modules with standard node_module resolution

**Comment by duarten** [comment]
I guess the linker is doing its job correctly by linking `node_modules` at `execroot/my_wksp/node_modules`. The issue is probably more related to the fact that `generate_build_file.ts` is linking all dependencies of the npm executable in `npm/node_modules` under the runfiles. That's likely incorrect for peer dependencies, which, not being provided by the library, should be resolved in `execroot/my_wksp/node_modules`.

**Comment by duarten** [comment]
Note that `--preserve-symlinks` and `--preserve-symlinks-main` don't affect `__filename`.

**Comment by evahowe** [comment]
@duarten, @alexeagle - does the above solve the issue?
