### ISSUE TITLE
Example https://bazel.angular.io/example/ is broken

### ISSUE THREAD

**Issue by phelanma** [bazelbuild/rules_nodejs#2288]
# 🐞 bug report

### Affected Rule

Its either a deployment configuration or build issue

### Is this a regression?

unknown

### Description
Trying to understand what is going on in this example rules_nodejs/examples/angular/
So used the link... blank page.

## 🔬 Minimal Reproduction

GOTO:  https://bazel.angular.io/example/

![Screenshot 2020-11-15 at 10 05 15](https://user-images.githubusercontent.com/3662700/99160375-26eb5a00-272a-11eb-9553-9119b7243083.png)

## 🔥  Error

Broken build

## 🌍  Your Environment

Interwebs

**Rules_nodejs version:**
Whichever the build used

**Comment by alexeagle** [comment]
we "fixed" it by taking down the bazel.angular.io example site, now that this project isn't owned by the Angular team and they aren't doing "marketing" for Bazel.

Ideally we'd publish all of our examples to some live hosting thing, Angular shouldn't be special in this regard. But that's a lot of infra to setup and maintain and we are just volunteers
