### ISSUE TITLE
Update example and doc with ts_project 

### ISSUE THREAD

**Issue by Socolin** [bazelbuild/rules_nodejs#2295]
Hello

As documented, it's recommanded to use `ts_project` for new project.

> ts_project is recommended for all new uses, and we hope to migrate all users to it in the future. It simply runs tsc --project.

But I found it difficult to understand how to use it without any example https://github.com/bazelbuild/rules_nodejs/tree/master/examples

Other documentation piece is also pointing toward `ts_library`

https://docs.bazel.build/versions/master/build-javascript.html

Any chances those can be updated ?

**Comment by tomasdev** [comment]
I ended up not using `ts_project` for this exact reason (lack of docs)

**Comment by mgenov** [comment]
I'm also experiencing some issues with it, but I'm trying to make it working. You can take a look into the test folder of typescript. It contains a lot of examples related to ts_project. 

https://github.com/bazelbuild/rules_nodejs/tree/master/packages/typescript/test/ts_project
