### ISSUE TITLE
Add a Windows CI environment

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#23]
@damienmg is this something I can get from http://ci.bazel.build ? I see some windows references in https://github.com/bazelbuild/continuous-integration/search?utf8=%E2%9C%93&q=windows&type= so I think you have some support there?

**Comment by damienmg** [comment]
Yes we have windows slave :)

**Comment by alexeagle** [comment]
@filipesilva volunteered to try resolving the remaining issue.

**Comment by alexeagle** [comment]
Fixed by #36
