### ISSUE TITLE
ts_project fails to find type declarations when compilerOptions target is es2019 or module is esnext

### ISSUE THREAD

**Issue by d4rkr00t** [bazelbuild/rules_nodejs#2302]
# 🐞 bug report

### Affected Rule

`ts_project`

### Is this a regression?

NO

### Description

 A clear and concise description of the problem...

Setting target and module in compilerOptions of ts_project breaks type definitions resolution:
```
ts_project(
    name = "ts",
    srcs = glob([
        "**/*.ts",
    ]),
    tsconfig = {
        "compilerOptions": {
            "strict": True,
            "declaration": True,
            "outDir": "esm",
            "types": [],
            "target": "es2019",
            "module": "esnext",
            "allowSyntheticDefaultImports": True,
            "lib": [
                "dom",
                "es5",
                "scripthost",
                "es2015.core",
                "es2015.collection",
                "es2015.symbol",
                "es2015.iterable",
                "es2015.promise",
                "es2016.array.include",
            ],
        },
    },
    deps = [
        "//packages/pkg-a",
        "@npm//react",
        "@npm//@types/react",
    ],
)
```

## 🔬 Minimal Reproduction

https://github.com/d4rkr00t/bazel_experiments

Comment out this lines https://github.com/d4rkr00t/bazel_experiments/blob/master/packages/pkg-b/BUILD.bazel#L25-L26 to make compilation work again.

## 🔥 Exception or Error

<pre><code>
node_modules/@types/react/index.d.ts(28,22): error TS2307: Cannot find module 'csstype' or its corresponding type declarations.
packages/pkg-b/index.ts(1,22): error TS2307: Cannot find module 'pkg-a' or its corresponding type declarations.
Target //packages/pkg-b:pkg-b failed to build
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
     macOs Catalina: 10.15.7
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
   3.0.0 and 3.7.0
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
    2.3.0
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
This isn't a Bazel issue - you can reproduce this with just plain TypeScript `tsc`.

The answer is that when you change `module` it also implicitly changes `moduleResolution`. Set the latter to `node` to keep your types resolving the same.
See https://www.typescriptlang.org/docs/handbook/module-resolution.html#module-resolution-strategies

**Comment by d4rkr00t** [comment]
🤦‍♂️ thank you
