### ISSUE TITLE
devserver fails to load esModuleInterop dependency

### ISSUE THREAD

**Issue by gonzojive** [bazelbuild/rules_nodejs#2317]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: I can't tell. Probably Typescript rules.

### Is this a regression?

No, I don't think so.

### Description

See the diff at https://github.com/gonzojive/rules_nodejs/commit/2fd421f8b2f4c3ed452ffbfe9817b149d19df33d

I am trying to depend on the 'color-interpolate' npm, which has a default export that is a function. When I load the app using the devserver, I get an error:

```
GET http://localhost:5555/color-interpolate.js net::ERR_ABORTED 404 (Not Found)
Uncaught Error: Script error for "color-interpolate", needed by: examples_angular/src/app/home/home
```

## 🔬 Minimal Reproduction

See the diff to the example angular app here: https://github.com/gonzojive/rules_nodejs/commit/2fd421f8b2f4c3ed452ffbfe9817b149d19df33d

run it with

```shell
git clone https://github.com/gonzojive/rules_nodejs.git repro
cd repro
git checkout failed-default-export
cd examples/angular
bazel run //src:devserver -- -port 5555
```

Load http://localhost:5555 in the web browser, see the error.

## 🔥 Exception or Error

<pre><code>
```
GET http://localhost:5555/color-interpolate.js net::ERR_ABORTED 404 (Not Found)
Uncaught Error: Script error for "color-interpolate", needed by: examples_angular/src/app/home/home
```
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
     Linux
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 3.7.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Oct 20 13:29:16 2020 (1603200556)
Build timestamp: 1603200556
Build timestamp as int: 1603200556
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "121f17d8b421ce72f3376431c3461cd66bfe14de49059edc7bb008d5aebd16be",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/2.3.1/rules_nodejs-2.3.1.tar.gz"],
)
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
This example uses the `concatjs` bundler. It's labelled "Google" in the examples index https://bazelbuild.github.io/rules_nodejs/examples.html#angular
The reason is that it's less compatible with the npm ecosystem. By using the concatjs bundler, you have to make all your dependencies loadable by require.js, see https://requirejs.org/docs/commonjs.html for some background.

Practically speaking, this means you need to do some kind of shimming so that `require([color-interpolate])` works in the browser. We automatically generate a UMD bundle for all third-party packages so `@npm//color-interpolate:color-interpolate__umd` might already provide what you need. I tried adding it to the `scripts` attribute of your repro (thanks for the convenient repro by the way - without that I wouldn't have had time to investigate)

```
diff --git a/examples/angular/src/BUILD.bazel b/examples/angular/src/BUILD.bazel
index 9952508e..d2e82045 100644
--- a/examples/angular/src/BUILD.bazel
+++ b/examples/angular/src/BUILD.bazel
@@ -118,6 +118,7 @@ ts_devserver(
     scripts = [
         "@npm//:node_modules/tslib/tslib.js",
         ":rxjs_umd_modules",
+        "@npm//color-interpolate:color-interpolate__umd",
         # We are manaully adding the bazel generated named-UMD date-fns bundle here as
         # named-UMD bundles for non-APF npm packages are not yet automatically added.
         # This file is generated by the npm_umd_bundle @npm//date-fns:date-fns__umd
```

and now your app loads without errors.

**Comment by alexeagle** [comment]
(note that esModuleInterop was a red herring, probably needed at compile-time for TS to find the type info but not related to the runtime error, which was simply that there was no AMD module registered for that name)

Our docs for this are at https://bazelbuild.github.io/rules_nodejs/repositories.html#npm
> Sometimes you need a UMD bundle, but a package doesn’t ship one. For example, the ts_devserver rule depends on third-party libraries having a named UMD entry point. The @npm//foo:foo__umd target will automatically run Browserify to convert the package’s main entry into UMD.

but that's hard to find so I think for our 3.0 release, where concatjs is a new package, I'll repeat this doc over there.

**Comment by alexeagle** [comment]
added to the doc for 3.0

**Comment by gonzojive** [comment]
Nice. Is there some way to make the devserver automatically pull in the missing umds? I'm not sure why this step is needed sometimes and not others. Apologies if the info is in the docs and I'm not understanding it.
