### ISSUE TITLE
Documentation issue: Built-ins - nodejs_binary

### ISSUE THREAD

**Issue by enigmatix** [bazelbuild/rules_nodejs#2357]
Hi, I was reading these docs and thought the description for nodejs_binary seemed off:

https://bazelbuild.github.io/rules_nodejs/Built-ins.html#nodejs_binary

It says `Runs some JavaScript code in NodeJS.`, but I would have thought based on the naming convention (and seemingly what it actually does) that it creates a NodeJs binary.  Can you confirm if one or the other is correct?

**Comment by mattem** [comment]
What do you mean by Nodejs binary here? (to me, a nodejs binary is a self-contained Node runtime and program).

Perhaps we can update the wording here. `nodejs_binary` will run a javascript file (defined in `entry_point`) under Node, similar to calling `node ./my-file.js` on the command line. The `build` verb on a `nodejs_binary` sets up the files and launcher script. It's perhaps a bazel idiom to call something a `*_binary` rule that performs this task, even it doesn't always result in a self contained executable.

**Comment by enigmatix** [comment]
Sorry, my mistake.  Now that i understand the ecosystem better and how it's executing I can see it does what the label says, defines a binary you can execute / include in other rules.  Happy to close this off.
