### ISSUE TITLE
Documentation issue: TypeScript

### ISSUE THREAD

**Issue by enigmatix** [bazelbuild/rules_nodejs#2375]
This link at the bottom of the section User-Managed Dependencies doesn't seem to go anywhere.  The repo link is valid, but the anchor no longer exists on the page.  Not sure where it went (from a quick scan).

 https://github.com/bazelbuild/rules_nodejs#dependencies

**Comment by mattem** [comment]
Can you link to the doc page that this link appears on?

**Comment by enigmatix** [comment]
Sorry, thought the site 'create issue' link added the url for some reason.  My bad.

https://bazelbuild.github.io/rules_nodejs/TypeScript.html#user-managed-npm-dependencies
