### ISSUE TITLE
example/protocol_buffers should use ts_project

### ISSUE THREAD

**Issue by simmonmt** [bazelbuild/rules_nodejs#2381]
# 🚀 feature request

### Description

example/react_webpack shows how to build a react app using ts_project and webpack. It should also show how to build a react app using ts_library and webpack, as it is my understanding that ts_library is the best way to go if I'm to use dynamically-generated TS files (like protobuf definitions).

I've made an attempt at converting example/app to use ts_library. You can find it here: https://github.com/simmonmt/rules_nodejs/commit/c2f1fdb279b7832c4577b8142e4d621445198451

It compiles and bundles properly, but when I load it in the browser (i.e. `bazel run :server`), I get this error:

```
app.bundle.js:6 Uncaught Error: Cannot find module 'react'
    at n (app.bundle.js:6)
    at app.bundle.js:6
    at app.bundle.js:6
    at Object.<anonymous> (app.bundle.js:6)
    at n (app.bundle.js:1)
    at app.bundle.js:1
    at app.bundle.js:1
```

If you can help me to figure out what went wrong here, I'd be happy to submit a PR that adds ts_library to example/react_webpack, thus resolving this issue.

**Comment by simmonmt** [comment]
I think I found the problem. ts_library by default creates UMD modules in devmode, which isn't compatible with Webpack (or at least not without fancy footwork that's beyond my understanding). Telling it to make es2015 modules makes Webpack happy. PR incoming.

**Comment by alexeagle** [comment]
could we back up a step? you say
> my understanding that ts_library is the best way to go if I'm to use dynamically-generated TS files
I don't think this is true - we'd like to deprecate `ts_library`. Seems like I should update `examples/protocol_buffers` to use `ts_project` instead. Do you remember what you read that gave you that understanding?

**Comment by simmonmt** [comment]
https://github.com/bazelbuild/rules_nodejs/issues/2301, for one, in which it says I'd need to run tsc directly to compile an "opaque" directory of ts files (which confused be, since I thought the proto libraries would be declaring their outputs). Using ts_library seemed a lot easier than that.

**Comment by simmonmt** [comment]
And yes, an update to example/protocol_buffers that shows how to use ts_project would be helpful if ts_library isn't the way to go.

**Comment by mattem** [comment]
This was done in https://github.com/bazelbuild/rules_nodejs/commit/5f26d0ff0a5a9e5fd548e82bba60e110d02579ca, but has since been removed. Closing as won't fix.
