### ISSUE TITLE
Coverage docs

### ISSUE THREAD

**Issue by Toxicable** [bazelbuild/rules_nodejs#2382]
So we need some docs for coverage.
For now I'll update this issue as the docs, once I've finalized it I'll add a MR to into the docs site.

# Config

**.bazelrc**
```
# When running `bazel coverage` --instrument_test_targets needs to be set in order to
# collect coverage information from test targets
coverage --instrument_test_targets
```

**WORKSPACE**
If you use `included_files` then ensure that .wasm is added
If you don't use `included_files` then this isn't needed 
```
yarn_install(
  ...
  included_files = [ ".wasm" ] 
```

**Targets**
Any target that you'd like to enable coverage for needs to add `"@npm//c8"` as a dep.
```
jasmine_node_test(
  ...
  deps = [ "@npm//c8" ]
```
**Tracking issues**
- Incorrect paths of coverage files #2376 
- Enabling "all: true" option in c8 #2377 

# Development

**Basic run**
Run `yarn bazel coverage --combined_report=lcov --experimental_convenience_symlinks=normal :target`
The combined lcov report will be in `bazel-out/_coverage/_coverage_report.dat`

**Tracking issues**
- ibazel coverage support https://github.com/bazelbuild/bazel-watcher/issues/448
- Coverage Gutters watch 
- Symlink only coverage file

# CI

**Comment by herman-rogers** [comment]
Does this rule work with karma_web_test_suite? As in can I run `bazelisk coverage` for karma rules and have it output correct coverage?

**Comment by farcaller** [comment]
It doesn't seem to work with e.g. jest (based on the jest example) – there's no coverage data generated after the run.
