### ISSUE TITLE
pkg_npm has outputs attribute which has been deprecated

### ISSUE THREAD

**Issue by EliSchleifer** [bazelbuild/rules_nodejs#2387]
# 🐞 bug report

### Affected Rule

internal/pkg_npm/pkg_npm.bzl

pkg_npm = rule(
    implementation = _pkg_npm,
    attrs = PKG_NPM_ATTRS,
    doc = _DOC,
    outputs = PKG_NPM_OUTPUTS,
)

### Is this a regression?

No. New bazel deprecation

### Description

outputs were deprecated by bazel and should be removed from this rule

## 🔬 Minimal Reproduction

Build rules_nodejs with latest bazel

## 🔥 Exception or Error

<pre><code>

ERROR: Traceback (most recent call last):
        File ".../build_bazel_rules_nodejs/internal/node/node.bzl", line 553, column 21, in <toplevel>
                nodejs_binary = rule(
Error in rule: in call to rule(), parameter 'outputs' is deprecated and will be removed soon. It may be temporarily re-enabled by setting --incompatible_no_rule_outputs_param=false
ERROR: error loading package '': in ...index.bzl: Extension file 'internal/node/node.bzl' has errors
INFO: Elapsed time: 2.639s

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
OSX Catalina
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 3.7.2
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 17 17:02:20 2020 (1608224540)
Build timestamp: 1608224540
Build timestamp as int: 1608224540
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>

  </code>
</pre>

**Anything else relevant?**

**Comment by mattem** [comment]
Thanks for the report.
This was flagged in #1303, there are some docs issues to resolve as outlined in the upstream bazel issue https://github.com/bazelbuild/bazel/issues/7977 and in Stardoc https://github.com/bazelbuild/stardoc/issues/27

I'm guessing your running with `--incompatible_no_rule_outputs_param`, unfortunately it will have to be disabled currently `--noincompatible_no_rule_outputs_param`

I'll close this as duplicate
