### ISSUE TITLE
Using select for tsconfig & supports_workers = True for ts_project doesn't work.

### ISSUE THREAD

**Issue by wardellbagby** [bazelbuild/rules_nodejs#2394]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 

`ts_project`

### Is this a regression?

No, because `supports_workers` didn't exist in previous releases.

### Description

 A clear and concise description of the problem...
When using a `select`-able `tsconfig` attribute for the `ts_project` rule along with `supports_workers = True`, Bazel throws an error it expected a type `string` and instead received the `select` statement.

## 🔬 Minimal Reproduction

`BUILD.bazel`

```
load("@npm//@bazel/typescript:index.bzl", "ts_project")

ts_project(
  name = "compile_ts",
  tsconfig = select({
    "//conditions:default": "//:tsconfig.json" # Purposefully a single case for a minimal repro, but fails with multiple cases.
  }),
  supports_workers = True
)
```
Changing `supports_workers` to false or omitting it entirely works.

## 🔥 Exception or Error
This error comes from my working changes for my repo at https://github.com/wardellbagby/lyricistant
<pre><code>
➜  lyricistant git:(main) ✗ bazel run //apps/web:start --define=VERBOSE_LOGS=1 
INFO: Build option --define has changed, discarding analysis cache.
ERROR: /Users/wardell/Development/lyricistant/renderer/main/BUILD.bazel:34:11: //renderer/main:compile_ts_worker: expected value of type 'string' for element 3 of attribute 'data' in 'nodejs_binary' rule, but got select({"//:test_build": "//:test-tsconfig", "//conditions:default": "//:tsconfig.json"}) (select)
ERROR: /Users/wardell/Development/lyricistant/apps/web/BUILD.bazel:26:10: Target '//renderer/main:main' contains an error and its package is in error and referenced by '//apps/web:bundle_web'
ERROR: /Users/wardell/Development/lyricistant/apps/web/BUILD.bazel:26:10: Target '//renderer/main:index.ejs' contains an error and its package is in error and referenced by '//apps/web:bundle_web'
ERROR: /Users/wardell/Development/lyricistant/apps/web/BUILD.bazel:26:10: Target '//renderer/main:static_resources' contains an error and its package is in error and referenced by '//apps/web:bundle_web'
ERROR: /Users/wardell/Development/lyricistant/apps/web/BUILD.bazel:26:10: Target '//renderer/main:webpack_config' contains an error and its package is in error and referenced by '//apps/web:bundle_web'
ERROR: Analysis of target '//apps/web:start' failed; build aborted: Analysis failed
INFO: Elapsed time: 1.939s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 122 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 122 targets configured)

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS Catalina - 10.15.7
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: development
Build label: 3.7.2
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 17 17:02:20 2020 (1608224540)
Build timestamp: 1608224540
Build timestamp as int: 1608224540
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
3.0.0
  </code>
</pre>

**Anything else relevant?**
I know `supports_workers` is very much experimental right now, just wanted to bring this to the attention of you all, and maybe see if there was a workaround that let me have my cake and eat it too?

**Comment by wardellbagby** [comment]
I can confirm this is still an issue with the upgraded TS worker support in 3.1.0.

**Comment by alexeagle** [comment]
Yeah an attribute has to do something special to be "configurable" I think. It would help to prioritize this if you can say what's the use case for it

**Comment by wardellbagby** [comment]
Yeah, of course!

So my [project](https://github.com/wardellbagby/lyricistant/tree/4aceda05a7745f7fe193428b6bf05bdf9afcd9ec) uses multiple TS configs to compile the same code with either CommonJS imports or ES6 imports.

[I have a macro around `ts_project`](https://github.com/wardellbagby/lyricistant/blob/4aceda05a7745f7fe193428b6bf05bdf9afcd9ec/tooling/ts_project.bzl) that everything that wants to compile Typescript uses, and that is what doing the `select` for the config.

If it's compiling TS to eventually be bundled with Webpack (and so run in a browser), then I use the TS config that uses ES6 imports. If it's compiling TS to eventually be run in Node (which I do for my unit tests), then it uses CommonJS imports, since I'm still using Node 14.

However, with 3.1.0, y'all added support for Node 15 directly, which supports ES6 modules without the experimental flag, so maybe I don't need to do that anymore. Although the option would still be nice so I can disable source maps generation when compiling unit tests.
