### ISSUE TITLE
Serving application with bazel run doesn't build dependent library

### ISSUE THREAD

**Issue by templth** [bazelbuild/rules_nodejs#2399]
# 🐞 Bug report

### Description

I have a monorepo containing an Angular application (called `app`) and an Angular library (called `lib`). Bazel is configured and we can build the application using the following command:

```
$ bazel build //angular/app:build
(...)
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

However, serving the application with the following command fails because the library can't be resolved:

```
$ bazel run //angular/app:serve
(...)
INFO: Analyzed target //angular/app:serve (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //angular/app:serve up-to-date:
  bazel-bin/angular/app/serve.sh
  bazel-bin/angular/app/serve_loader.js
  bazel-bin/angular/app/serve_require_patch.js
INFO: Elapsed time: 0.564s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
```

The errors correspond to imports of elements contained in the library `lib` the application relies on.

```
app:serve: 
ERROR in angular/app/src/app/core/components/app/app.component.ts:2:45 - error TS2307: Cannot find module 'lib' or its corresponding type declarations.

2 import { InternationalizationService } from 'lib';
                                              ~~~~~
angular/app/src/app/core/components/auth/confirm-email/confirm-email.component.ts:3:29 - error TS2307: Cannot find module 'lib' or its corresponding type declarations.

(...)
```

Our Bazel configuration is based on the one in this project: https://github.com/bazelbuild/rules_nodejs/blob/master/examples/angular_bazel_architect/BUILD.bazel#L13

## 🌍 Your Environment

<pre><code>
$ ng version

Angular CLI: 10.2.1
Node: 12.19.1
OS: linux x64

Angular: 10.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: <error>

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1002.1
@angular-devkit/architect-cli      0.1002.1
@angular-devkit/build-angular      0.1002.1
@angular-devkit/core               10.2.1
@angular-devkit/schematics         10.2.1
@angular/cdk                       10.2.7
@angular/cli                       10.2.1
@angular/material                  10.2.7
@angular/material-moment-adapter   10.2.7
@bazel/bazelisk                    1.7.3
@bazel/ibazel                      v0.14.0
@bazel/rollup                      3.0.0
@bazel/typescript                  3.0.0
@bazel/worker                      3.0.0
@schematics/angular                10.2.1
@schematics/update                 0.1002.1
ng-packagr                         10.1.2
rxjs                               6.6.3
typescript                         4.0.5
</code></pre>

**Comment by mattem** [comment]
Are you able to make a small reproduction repo of the issue?

**Comment by smnrd** [comment]
I'm working with @templth on this and I managed to reproduce the issue within the angular_bazel_architect example.
From `bazelbuild/rules_nodejs` root :
```
cd examples/angular_bazel_architect
yarn
bazel run //:serve
```
The local `node_modules` (useful for IDE support) causes the issue. If I had to guess I'd say that bazel creates a symlink in execRoot to this local `node_modules` which prevents `yarn_install` to create its own link pointing to `outputBase/external/npm`. 

This does not happen if we set `symlink_node_modules` to True, but doing so breaks our CI in a weird, non-reproducible way.

We thought adding `node_modules` to `.bazelignore` would cause bazel not to add symlink to our local `node_modules` in execRoot, but this is already set in the angular_bazel_architect example, and it fails anyway.

**Comment by mattem** [comment]
Thanks. When setting `symlink_node_modules = True`, are the managed directories also being added to the `workspace` call? eg:

```
workspace(
    name = "angular_bazel_architect",
    managed_directories = {
        "@npm": ["node_modules"],
    }
)
```

This should allow for IDE support and bazel to share the same node_modules folder. When running with that set, the above list of commands work serve the app correctly for me.

**Comment by smnrd** [comment]
Thanks for helping. We did set `managed directories` for `node_modules` ( in our case `"@npm": ["third_party/npm/node_modules"]` with a local symlink at workspace root to get IDE working).
With `symlink_node_modules = True` everything is working fine for us too, but this break our CI (packages in node_modules seem to 'disappear' randomly).
I'd be happy with a clean way to set  `symlink_node_modules = True`  for local dev and  `symlink_node_modules = False` for CI, but as far as I understand I cannot use bazel's `select` (to select a different value for `symlink_node_modules` depending on the environment) in workspace rules.
