### ISSUE TITLE
NodeJS 404 on Bazel mirror (node-v14.15.3-linux-x64.tar.xz)

### ISSUE THREAD

**Issue by achew22** [bazelbuild/rules_nodejs#2406]
# 🐞 bug report

### Affected Rule

```
load("@build_bazel_rules_nodejs//:index.bzl", "node_repositories", "yarn_install")

node_repositories(
    node_version = "14.15.3",
    yarn_version = "1.22.4",
)
```

### Is this a regression?

Not sure. Since this is a non-fatal error, I don't know if it's new since we upgraded about 20 days ago. It has been in all the CI runs that I'm checked in our run history.

### Description

 A clear and concise description of the problem...

It's possible that I just noticed this (it's a warning after all) now and that it's successfully falling back to an alternative download. I hypothesize that the `rules_nodejs` releaser doesn't upload all the node versions to gcs for mirroring. If that's the case then it might be worth noting that the selected version of nodejs by the caller is not one that is mirrored on GCS and removing it from the alternative download list.

## 🔬 Minimal Reproduction

`WORKSPACE`:

```
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "6142e9586162b179fdd570a55e50d1332e7d9c030efd853453438d607569721d",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/3.0.0/rules_nodejs-3.0.0.tar.gz"],
)

# Check the bazel version and download npm dependencies
load("@build_bazel_rules_nodejs//:index.bzl", "node_repositories", "yarn_install")

node_repositories(
    node_version = "14.15.3",
    yarn_version = "1.22.4",
)
```

## 🔥 Exception or Error

<pre><code>
WARNING: Download from https://mirror.bazel.build/nodejs.org/dist/v14.15.3/node-v14.15.3-linux-x64.tar.xz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
$ uname -a
Linux devbox 5.4.0-1032-gcp #34-Ubuntu SMP Wed Dec 9 17:23:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
$ bazel version
Starting local Bazel server and connecting to it...
Build label: 3.7.2
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 17 16:57:23 2020 (1608224243)
Build timestamp: 1608224243
Build timestamp as int: 1608224243
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "6142e9586162b179fdd570a55e50d1332e7d9c030efd853453438d607569721d",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/3.0.0/rules_nodejs-3.0.0.tar.gz"],
)
  </code>
</pre>

**Anything else relevant?**

Nope. Thanks so much!

**Comment by mattem** [comment]
Thanks for the report, we'll have to find someone from Google that has access to updating the mirror, as I assume it's controlled by them still. 

@alexeagle do you know who would be a contact point here?

**Comment by mattem** [comment]
We discussed this today in the sync meeting and we don't think it should be on Bazel or the Bazel team to mirror NodeJS releases. 
We decided to change our default URLs to stop using `mirror.bazel.build`
