### ISSUE TITLE
absent c8 package makes tests fail under `bazel coverage`

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#2407]
coverage depending on c8, should it be non-fatal? Doesn't work with generated_file_test for example.

It could warn somewhere. Maybe only with VERBOSE_COVERAGE. 

decision: the error message should tell you how to both turn to a warning globally and also turn off for one target.

**Comment by mattem** [comment]
Related https://github.com/bazelbuild/rules_nodejs/issues/2407

**Comment by gregmagolan** [comment]
No longer in scope for rules_nodejs which only supplies the Node.js toolchain as of [v6.0.0](https://github.com/bazelbuild/rules_nodejs/releases/tag/v6.0.0-beta0).

Downstream canonical JavaScript + Node.js ruleset is now https://github.com/aspect-build/rules_js.
