### ISSUE TITLE
file '@npm//@bazel/typescript:index.bzl' does not contain symbol 'concatjs_devserver'

### ISSUE THREAD

**Issue by farcaller** [bazelbuild/rules_nodejs#2414]
# 🐞 bug report

### Affected Rule

`concatjs_devserver`

### Is this a regression?

Yes

### Description

The [docs](https://bazelbuild.github.io/rules_nodejs/Concatjs.html#serving-js-in-development-mode-under-bazel) state one should use devserver via:

```
load("@npm//@bazel/typescript:index.bzl", "concatjs_devserver", "ts_library")

ts_library(
    name = "app",
    srcs = ["app.ts"],
)

concatjs_devserver(
    name = "devserver",
    # We'll collect all the devmode JS sources from these TypeScript libraries
    deps = [":app"],
    # This is the path we'll request from the browser, see index.html
    serving_path = "/bundle.js",
    # The devserver can serve our static files too
    static_files = ["index.html"],
)
```

But doing this fails with:

`Error: file '@npm//@bazel/typescript:index.bzl' does not contain symbol 'concatjs_devserver'`

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
ubuntu
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.7.3
Build label: 4.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 21 07:33:24 2021 (1611214404)
Build timestamp: 1611214404
Build timestamp as int: 1611214404
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
    3.0.0 with the following deps in packages.json:

    "@bazel/bazelisk": "latest",
    "@bazel/buildifier": "latest",
    "@bazel/concatjs": "^3.0.0",
    "@bazel/ibazel": "latest",
    "@bazel/rollup": "^3.0.0",
    "@bazel/typescript": "^3.0.0",
  </code>
</pre>

**Anything else relevant?**

**Comment by mattem** [comment]
Thanks for the issue.
This is an issue in the documentation, loads for `concatjs_devserver` should be from the `@bazel/concatjs` package.

```
load("@npm//@bazel/concatjs:index.bzl", "concatjs_devserver")
load("@npm//@bazel/typescript:index.bzl", "ts_library")

ts_library(
    name = "app",
    srcs = ["app.ts"],
)

concatjs_devserver(
    name = "devserver",
    # We'll collect all the devmode JS sources from these TypeScript libraries
    deps = [":app"],
    # This is the path we'll request from the browser, see index.html
    serving_path = "/bundle.js",
    # The devserver can serve our static files too
    static_files = ["index.html"],
)
```

The 3.0.0 migration docs have further information too: https://github.com/bazelbuild/rules_nodejs/wiki#rename-ts_devserver---concatjs_devserver-2239
