### ISSUE TITLE
Enable multi-linker by default

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/rules_nodejs#2451]
This is a breaking change and needs to be sequenced with the 4.0 release.

To turn it on by default, the `package_path` should default to the directory of the `package.json` file if it is unset (`""`).
It can be overridden if necessary. To override to root the value of `"/"` could be used.

**Comment by charlesoconor** [comment]
This would be awesome! Just spent a tone of time finding this flag.

**Comment by gregmagolan** [comment]
Flipping the default for 5.0 in https://github.com/bazelbuild/rules_nodejs/pull/3233

**Comment by gregmagolan** [comment]
Closed by #3233
