### ISSUE TITLE
could not find dependency 'bindings' of 'watchpack-chokidar2/node_modules/fsevents'

### ISSUE THREAD

**Issue by herry-c** [bazelbuild/rules_nodejs#2452]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 
npm_install

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

I tried to use bazel for npm install, but bazel downloaded the dependency on the optional fsevents option, which I did not generate when I ran npm install on the command line.

## 🔥 Exception or Error

<pre><code>

Error in fail: generate_build_file.ts failed: 
STDOUT:
STDERR:
could not find dependency 'bindings' of 'watchpack-chokidar2/node_modules/fsevents'
ERROR: generate_build_file.ts failed: 
STDOUT:
STDERR:
could not find dependency 'bindings' of 'watchpack-chokidar2/node_modules/fsevents'

If I run the npm install command on the CLI, the following warning message is displayed:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

However, bazel does not skip this warning and still downloads fsevents.
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
linux
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>

  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
3.1.0
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
I think this makes sense, that npm has the concept of "optional" dependencies which really means "non-fatal install failures" but when we mirror the npm dependency graph into build files (generate_build_files.ts) we don't have that concept.

**Comment by keanedawg** [comment]
We honestly got around this by just switching to using yarn install (or getting rid of the package that has the optional dependencies).
