### ISSUE TITLE
`yarn_install` isn't run when invoking a target depending on the `yarn_install` repo

### ISSUE THREAD

**Issue by mmatheson** [bazelbuild/rules_nodejs#2456]
# 🐞 bug report

### Affected Rule

yarn_install

### Is this a regression?

Not that I know of

### Description

`yarn_install` is not run when I invoke a bazel command on a target that depends on it.

## 🔬 Minimal Reproduction

clone https://github.com/mmatheson/rules_nodejs_yarn
from the root run `bazel run src:app`

Expected: builds successfully and runs (printing Hello World to console)

## 🔥 Exception or Error

<pre><code>
$ bazel run src:app
Starting local Bazel server and connecting to it...
INFO: Analyzed target //src:app (25 packages loaded, 1131 targets configured).
INFO: Found 1 target...
ERROR: /home/matt/scratch/rules_nodejs_yarn/src/BUILD:5:14: //src:app: missing input file 'external/npm/node_modules/lodash/LICENSE', owner: '@npm//:node_modules/lodash/LICENSE'
Target //src:app failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/matt/scratch/rules_nodejs_yarn/src/BUILD:5:14 1049 input file(s) do not exist
INFO: Elapsed time: 3.045s, Critical Path: 0.03s
INFO: 1 process: 1 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
$ bazel version
Build label: 3.7.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Nov 24 17:38:30 2020 (1606239510)
Build timestamp: 1606239510
Build timestamp as int: 1606239510
  </code>
</pre>

**Rules_nodejs version:**

<pre>
  <code>
3.1.0
  </code>
</pre>

**Anything else relevant?**

Things that work:
`yarn install`
OR
`bazel sync`

before running `bazel run`

**Comment by pcj** [comment]
Can you check if this is a regression?  Please try with `3.0.0`

**Comment by mmatheson** [comment]
@pcj I don't think so. I added branches `3.0` and `2.3.3` to the example repo in the ticket, each one pointing to a different rules_nodejs version. When I `git clone`, `git checkout 2.3.3` and `bazel run src:app` I get the same error as in the ticket.

**Comment by mattem** [comment]
I tried this on both MacOS and Linux (bionic and focal) and couldn't repro :( 
I did note that there is no `.bazelversion` in the repro, but running on both the listed version `3.7.1` and `4.0.0` yielded the same results. So I'm not really sure what's going on here.

```
bazel run src:app

Starting local Bazel server and connecting to it...
INFO: Analyzed target //src:app (25 packages loaded, 1131 targets configured).
INFO: Found 1 target...
Target //src:app up-to-date:
  bazel-bin/src/app.sh
  bazel-bin/src/app_loader.js
  bazel-bin/src/app_require_patch.js
INFO: Elapsed time: 7.683s, Critical Path: 0.12s
INFO: 7 processes: 7 internal.
INFO: Build completed successfully, 7 total actions
INFO: Build completed successfully, 7 total actions
Hello World
```

**Comment by mmatheson** [comment]
I wonder if something is getting cached by bazel that doesn't prompt it to re-run `yarn_install`. I don't get this 100%, for example I just tried it again and it worked the first time but when I deleted the repo & and re-cloned it failed the second time:

```
 $ git clone git@github.com:mmatheson/rules_nodejs_yarn.git
Cloning into 'rules_nodejs_yarn'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 29 (delta 13), reused 23 (delta 7), pack-reused 0
Receiving objects: 100% (29/29), done.
Resolving deltas: 100% (13/13), done.
 $ cd rules_nodejs_yarn
 $ bazel run src:app
Starting local Bazel server and connecting to it...
INFO: Analyzed target //src:app (25 packages loaded, 1131 targets configured).
INFO: Found 1 target...
Target //src:app up-to-date:
  bazel-bin/src/app.sh
  bazel-bin/src/app_loader.js
  bazel-bin/src/app_require_patch.js
INFO: Elapsed time: 5.290s, Critical Path: 0.03s
INFO: 2 processes: 2 internal.
INFO: Build completed successfully, 2 total actions
INFO: Build completed successfully, 2 total actions
Hello World
 $ cd ..
 $ rm -rf rules_nodejs_yarn
 $ git clone git@github.com:mmatheson/rules_nodejs_yarn.git
Cloning into 'rules_nodejs_yarn'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 29 (delta 13), reused 23 (delta 7), pack-reused 0
Receiving objects: 100% (29/29), done.
Resolving deltas: 100% (13/13), done.
 $ cd rules_nodejs_yarn
 $ bazel run src:app
Starting local Bazel server and connecting to it...
INFO: Analyzed target //src:app (25 packages loaded, 1131 targets configured).
INFO: Found 1 target...
ERROR: /home/matt/scratch/rules_nodejs_yarn/src/BUILD:5:14: //src:app: missing input file 'external/npm/node_modules/lodash/LICENSE', owner: '@npm//:node_modules/lodash/LICENSE'
Target //src:app failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/matt/scratch/rules_nodejs_yarn/src/BUILD:5:14 1049 input file(s) do not exist
INFO: Elapsed time: 2.848s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by alexeagle** [comment]
I think this is related to https://bazelbuild.github.io/rules_nodejs/Built-ins.html#yarn_install-symlink_node_modules

Since you don't have `managed_directories` enabled, you can get into a race condition where we try to symlink the external/npm/node_modules to your project directory but the node_modules may not exist there.

@gregmagolan could we do something better here? seems like a common issue lately
