### ISSUE TITLE
Bazel error when attempting to run rules_nodejs repository tests

### ISSUE THREAD

**Issue by pshields** [bazelbuild/rules_nodejs#2458]
# 🐞 bug report

### Affected Rule

Seems to be something defined in `npm_install.bzl`. Maybe `yarn_install`.

### Is this a regression?

This error seems to be new, but if I try the same thing at version `3.0.0`, I get a different error: `'""' is not recognized as an internal or external command, operable program or batch file.`

(That error was also mentioned in https://github.com/bazelbuild/rules_nodejs/issues/1559, which indicates there may be a Windows dependency that the `rules_nodejs` documentation doesn't appear to currently mention, related to shell scripting / bash...)

### Description

I can't successfully run the repository's tests on Windows.

## 🔬 Minimal Reproduction

When I run `bazelisk test //...` from a local checkout of the `rules_nodejs` repository on Windows, I get an error. `bazelisk test //internal/npm_install/test:test` is an example of a particular target that also triggers a similar error.

## 🔥 Exception or Error

<pre><code>
INFO: Invocation ID: f8ab59a5-5d19-43f3-a597-54016f2f6f9d
INFO: Build option --define has changed, discarding analysis cache.
INFO: Repository fine_grained_goldens instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule yarn_install defined at:
  C:/users/pshie/_bazel_pshie/sa3gfjp6/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:503:31: in <toplevel>
INFO: Repository npm instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule yarn_install defined at:
  C:/users/pshie/_bazel_pshie/sa3gfjp6/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:503:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'fine_grained_goldens':
   Traceback (most recent call last):
        File "C:/users/pshie/_bazel_pshie/sa3gfjp6/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 471, column 15, in _yarn_install_impl
                _copy_file(repository_ctx, repository_ctx.attr.package_json)
        File "C:/users/pshie/_bazel_pshie/sa3gfjp6/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 188, column 17, in _copy_file
                fail("mkdir -p %s failed: \nSTDOUT:\n%s\nSTDERR:\n%s" % (dirname, result.stdout, result.stderr))
Error in fail: mkdir -p _/tools/fine_grained_goldens failed:
STDOUT:

STDERR:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("mkdir" -p _/tools/fine_grained_goldens): The system cannot find the file specified.
 (error: 2)
ERROR: C:/[...path to rules_nodejs...]/rules_nodejs/internal/npm_install/test/BUILD.bazel:10:18: //internal/npm_install/test:test depends on @fine_grained_goldens//:golden_files in repository @fine_grained_goldens which failed to fetch. no such package '@fine_grained_goldens//': mkdir -p _/tools/fine_grained_goldens failed:
STDOUT:

STDERR:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("mkdir" -p _/tools/fine_grained_goldens): The system cannot find the file specified.
 (error: 2)
ERROR: Analysis of target '//internal/npm_install/test:test' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.351s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 152 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 152 targets configured)
</code></pre>

## 🌍  Your Environment

**Operating System:**

Windows 10

**Output of `bazel version`:**

<pre><code>Bazelisk version: development
Build label: 3.6.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Oct 6 13:16:08 2020 (1601990168)
Build timestamp: 1601990168
Build timestamp as int: 1601990168
</code></pre>

**Rules_nodejs version:**

`stable` branch `HEAD`.

(If I try the same thing at version `3.0.0`, I get a different error: `'""' is not recognized as an internal or external command, operable program or batch file.`)

**Comment by pshields** [comment]
It looks like I might need MSYS2 installed? The Bazel docs for Windows say:

```
You will need MSYS2 to build, test, or run targets that depend on Bash. Typically these are genrule, sh_binary, sh_test, but there may be more (e.g. Starlark rules). Bazel shows an error if a build target needs Bash but Bazel could not locate it.
```

I'll plan to try installing MSYS2 and see if that helps. If that was the problem, I wonder if there's a way to make the error message more clear.

**Comment by alexeagle** [comment]
yes, you're right, rules_nodejs depends on bash and a few other unix tools. We've worked to make .cmd versions of some things, but I'm not surprised that MSYS2 is required to build/test rules_nodejs itself.

please ping me if that's not the fix :)
