### ISSUE TITLE
Breakage with Bazel HEAD due to 00805727b867d33fd922e63ca82b0d9825ad79fe

### ISSUE THREAD

**Issue by lberki** [bazelbuild/rules_nodejs#2464]
This breakage was reported by our continuous integration.

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1906#44b4eb78-3a05-4ecf-abdb-dfa16b20ff86

It is probably caused by https://github.com/bazelbuild/bazel/commit/00805727b867d33fd922e63ca82b0d9825ad79fe that calls test binaries in external repositories not using their legacy `external/$REPO/$REPO_RELATIVE_PATH` path but the canonical `../$REPO/$REPO_RELATIVE_PATH` one.

I haven't looked into what the mechanism of the breakage is; my guess is that test binaries try to find data files relative to $0 and that logic needs to be updated.

This bug is also available in our continuous integration repository as https://github.com/bazelbuild/continuous-integration/issues/1093 .

**Comment by alexeagle** [comment]
Is it possibly related to our use of --nolegacy_external_runfiles? https://github.com/bazelbuild/rules_nodejs/blob/stable/common.bazelrc#L60-L62

**Comment by gyias** [comment]
Probably not. [The triggering change](https://github.com/bazelbuild/bazel/commit/00805727b867d33fd922e63ca82b0d9825ad79fe) is part of the effort to deprecate the legacy external runfiles path.

**Comment by gyias** [comment]
Hmm, I now think the commit isn't actually the culprit. I ran a CI with a revert, and [it's still broken](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1919#c241c4a5-0a18-4836-bdbf-a212d27b698e).

**Comment by alexeagle** [comment]
Okay let us know if you need something from rules_nodejs maintainers...

**Comment by meteorcloudy** [comment]
I believe the true culprit is https://github.com/bazelbuild/bazel/commit/7149f578006a4ad0d51df69830a6986749b34df5
https://buildkite.com/bazel/bazel-auto-sheriff-face-with-cowboy-hat/builds/433

FYI @lberki

**Comment by meteorcloudy** [comment]
And this can only be reproduced with remote caching (or just --disk_cache=/tmp/bazel_disk_cache). I'm suspecting this is a bug in Bazel.

**Comment by comius** [comment]
Confirming it is fixed: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1924
