### ISSUE TITLE
"Invalid build flag" error when running esbuild with `define` argument

### ISSUE THREAD

**Issue by shosti** [bazelbuild/rules_nodejs#2473]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: 

`esbuild`

### Is this a regression?

No

### Description

When using the `define` option in the `esbuild` rule, builds fail with errors similar to:

```
 > error: Invalid build flag: "--define=process.env.NODE_ENV=\"production\""
```

From [the esbuild docs](https://esbuild.github.io/getting-started/#bundling-for-the-browser), it looks like generated CLI argument should be `--define:process.env.NODE_ENV=\"production\"` instead of `--define=process.env.NODE_ENV=\"production\"`.

## 🔬 Minimal Reproduction

This occurs with an `esbuild` rule that looks like this:

```
esbuild(
    name = "dashboard",
    entry_point = "src/index.tsx",
    deps = [
        ":lib",
    ],
    tool = select({
        "@bazel_tools//src/conditions:darwin": "@esbuild_darwin//:bin/esbuild",
        "@bazel_tools//src/conditions:windows": "@esbuild_windows//:esbuild.exe",
        "@bazel_tools//src/conditions:linux_x86_64": "@esbuild_linux//:bin/esbuild",
    }),
    define = [
        "process.env.NODE_ENV=\"production\"",
    ],
)
```

I tried with esbuild 0.8.34 and 0.8.46.

## 🔥 Exception or Error

```
 > error: Invalid build flag: "--define=process.env.NODE_ENV=\"production\""
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 3.5.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Sep 2 20:11:46 2020 (1599077506)
Build timestamp: 1599077506
Build timestamp as int: 1599077506
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
3.2.0
  </code>
</pre>

**Anything else relevant?**

**Comment by shosti** [comment]
I have a fix locally, I can make a PR really quick.

**Comment by mattem** [comment]
Thanks for the report, this was fixed at HEAD earlier today by https://github.com/bazelbuild/rules_nodejs/pull/2469

**Comment by shosti** [comment]
Oh awesome, thanks!
