### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by Kritz1994** [bazelbuild/rules_nodejs#2479]
Hi,
I'm using this rule - ts_web_test_suite to run angular unit test cases with bazel.

ts_web_test_suite(
    name = "unit_test",
    tags = ["native", "no-bazelci"],
    srcs = [
        # We are manaully adding a browserify generated named UMD date-fns bundle here that
        # was generated in our package.json postinstall step. This is a temporary work-around
        # to get commonjs modules & npm packages working with ts_web_test_suite. A more ergonomic
        # solution is planned for Angular v8. See https://github.com/bazelbuild/rules_nodejs/issues/646.
         "@npm//date-fns:date-fns.umd.js",
    ],
    # do not sort
       bootstrap = [
        "@npm//:node_modules/zone.js/dist/zone-testing-bundle.js",
        "@npm//:node_modules/reflect-metadata/Reflect.js",
    ],
    browsers = [
        "@io_bazel_rules_webtesting//browsers:chromium-local",
        # TODO(gregmagolan): re-enable firefox testing once fixed
        # See https://github.com/bazelbuild/rules_typescript/issues/296
        #"@io_bazel_rules_webtesting//browsers:firefox-local",
    ],
    runtime_deps = [
        "//ui/src:initialize_testbed",
    ],
    deps = [
        ":test",
        "//ui/src:rxjs_umd_modules",
    ],
)

And I'm running this command to find the coverage report using lcov.
bazel coverage --combined_report=lcov //ui/...

But the _coverage_report.dat file generated here is empty.

Can anyone help with this?

_Originally posted by @Kritz1994 in https://github.com/bazelbuild/rules_nodejs/issues/931#issuecomment-782070444_

**Comment by alexeagle** [comment]
I bet we don't have any coverage support for karma. @Toxicable is our coverage expert - any idea whether this ought to work or how much effort?
