### ISSUE TITLE
tsconfig.bzl from rules_typescript is stomping on sourceMap value. 

### ISSUE THREAD

**Issue by EliSchleifer** [bazelbuild/rules_nodejs#2481]
# 🐞 bug report

### Affected Rule

bazelbuild/rules_typescript/internal/common/tsconfig.bzl

### Is this a regression?
I don't think so

### Description
The tsconfig.bzl file makes an assumption that all users want to set sourceMap:False and inlineSource,inlineSourceMap to true. VS Code does not fully support inlineSources. I would like to be able to generate sourceMaps. I realize the nonsense that sourceMaps generate for files dumped into bazel-bin, but I'd rather deal with that and be able to debug my code in VS Code.

## 🔬 Minimal Reproduction
Set tsconfig.json to sourceMap:true, it will always be set to false in the generated tsconfig.

## 🌍  Your Environment

Ubuntu 18
bazel 4.0

**Rules_nodejs version:**
3.0.0

**Comment by alexeagle** [comment]
the `ts_library` rule is super-opinionated since it comes from Google-internal where there are few choices. I suggest using `ts_project` instead since that's just a thin layering on top of the TypeScript compiler and supports everything.
