### ISSUE TITLE
Support prefix stripping in js_library

### ISSUE THREAD

**Issue by aaliddell** [bazelbuild/rules_nodejs#2482]
# 🚀 feature request

### Relevant Rules

`js_library`

### Description

It would be useful to have the ability to strip a prefix from the require path when using a `js_library`.

For example, with the following project layout:

```
- WORKSPACE
- BUILD
- module/
-- file.js
```

In BUILD, we have a `js_library` declared like so:

```starlark
js_library(
    name = "some_library",
    srcs = ["module/file.js"],
    package_name = "module",
)
```

When using the `js_library`, you would presently have to do:

```js
require('module/module/file.js')
```

### Describe the solution you'd like

A mechanism to tell `js_library` a path that should be stripped/hidden, such that libraries can be within subdirectories without that appearing in the require path. Such as:

```starlark
js_library(
    name = "some_library",
    srcs = ["module/file.js"],
    package_name = "module",
    strip_prefix = "module",  # Example name
)
```

With this, the require becomes:

```js
require('module/file.js')
```

I think this could be achieved through changing the `path` on the `LinkablePackageInfo` to point to the directory, rather than the local package root:

https://github.com/bazelbuild/rules_nodejs/blob/2c2cc6eec42b0f4f805fb3063920107b78f821fd/internal/js_library/js_library.bzl#L225-L231

e.g. line 226 becomes:

```starlark
path = "/".join([p for p in [ctx.bin_dir.path, ctx.label.workspace_root, ctx.label.package, ctx.attr.strip_prefix] if p])
```

This would be a backwards compatible change, since in the absence of the `strip_prefix` attr being set, the behaviour would be unchanged. This is similar to `includes` on `cc_library` or `strip_import_prefix` on `proto_library`.

### Describe alternatives you've considered

- Tried patching the generated `LinkablePackageInfo` in a subsequent rule and forwarding other providers, but this doesn't work since the old provider is picked up by an aspect and results in 'conflicting mapping'. This would also break as soon as a new provider is added to rules_nodejs.
- Putting the BUILD file in the `module` folder is not feasible, as that folder is an output from prior rules rather than a static folder as in the above example.

**Comment by mattem** [comment]
Closed via #2519
