### ISSUE TITLE
The remote build fails and a timeout message is displayed.

### ISSUE THREAD

**Issue by herry-c** [bazelbuild/rules_nodejs#2490]
# 🚀 feature request

### Relevant Rules
node_repositories

### Description

The remote build fails and a timeout message is displayed.
I tried to build a JavaScript project remotely from bazel build //... --remote_executor=xxx and failed with the following failure message:
DEADLINE_EXCEEDED: deadline exceeded after xxxs,
 I don't time out when building a java project, but I encountered a time out problem when building a React project.

### Describe the solution you'd like

I want the build to be remotely executed.

### Describe alternatives you've considered
I used the node_repositories() configuration, but it still didn't work.My configuration is as follows：
node_repositories(
    package_json = ["//:package.json"],
    node_version = "12.8.1",
    yarn_version = "1.22.4",
)

**Comment by mattem** [comment]
Hi, thanks for the report. This could be cause by a number of things, and the information provided isn't really enough to go on.
The first thing that comes to mind is providing fine-grained npm dependencies as mentioned in the docs here:
https://bazelbuild.github.io/rules_nodejs/dependencies.html#coarse-node_modules-dependencies

**Comment by herry-c** [comment]
Thank you very much for your advice, I do use coarse-grained dependencies at the moment.
Some of my code and configurations are as follow:
How do I modify the configuration to make my remote build work?
package.json
{
  "devDependencies": {
    "webpack": "^4.15.1",
    "webpack-cli": "^4.1.0",
    "@bazel/buildifier": "^3.5.0",
    "@bazel/ibazel": "^0.14.0",
    "@bazel/typescript": "^3.1.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "webpack-dev-server --mode development",
    "build": "bazel build //..."
  },
  "dependencies": {
    "lodash": "^4.17.10"
  }
}

BUILD.bazel 

load("@npm//webpack-cli:index.bzl", webpack = "webpack_cli")

webpack(
    name = "bundle",
    outs = ["app.bundle"],
    args = [
        "--config",
        "$(execpath webpack.config.js)",
        "-o",
        "$@",
    ],
    data = [
        "webpack.config.js",
        "@npm//:node_modules",
    ] + glob(["src/*"]),
)

WORKSPACE

workspace(
    name = "react_webpack",
    managed_directories = {"@npm": ["node_modules"]},
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "dd4dc46066e2ce034cba0c81aa3e862b27e8e8d95871f567359f7a534cccb666",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/3.1.0/rules_nodejs-3.1.0.tar.gz"],
)

load("@build_bazel_rules_nodejs//:index.bzl", "yarn_install")
load("@build_bazel_rules_nodejs//:index.bzl", "node_repositories")

node_repositories(
    package_json = ["//:package.json"],
    node_version = "12.8.1",
    yarn_version = "1.22.4",
)

yarn_install(
    # Name this npm so that Bazel Label references look like @npm//package
    name = "npm",
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
)
