### ISSUE TITLE
webapp example fails on Windows 10 with `mkdir -p _ failed`

### ISSUE THREAD

**Issue by biro-mark** [bazelbuild/rules_nodejs#2491]
# 🐞 bug report

### Affected Rule

 _yarn_install_impl

### Description

Could not run `bazel run :server` as described https://github.com/bazelbuild/rules_nodejs/tree/stable/examples/webapp

## 🔬 Minimal Reproduction

1. git clone https://github.com/bazelbuild/rules_nodejs.git
2. cd rules_nodejs\examples\webapp
3. bazel run :server

## 🔥 Exception or Error

<pre><code>
C:\Users\mark\rules_nodejs\examples\webapp>bazel run :server --define=VERBOSE_LOGS=1
INFO: Invocation ID: d99623dd-9579-4c9e-9060-78691db4ea4c
INFO: Repository npm_deps instantiated at:
  C:/users/mark/rules_nodejs/examples/webapp/WORKSPACE:30:13: in <toplevel>
  C:/users/mark/_bazel_mark/msumpq5c/external/build_bazel_rules_nodejs/index.bzl:78:18: in yarn_install
Repository rule yarn_install defined at:
  C:/users/mark/_bazel_mark/msumpq5c/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:509:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'npm_deps':
   Traceback (most recent call last):
        File "C:/users/mark/_bazel_mark/msumpq5c/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 477, column 15, in _yarn_install_impl
                _copy_file(repository_ctx, repository_ctx.attr.package_json)
        File "C:/users/mark/_bazel_mark/msumpq5c/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 212, column 17, in _copy_file
                fail("mkdir -p %s failed: \nSTDOUT:\n%s\nSTDERR:\n%s" % (dirname, result.stdout, result.stderr))
Error in fail: mkdir -p _ failed:
STDOUT:

STDERR:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("mkdir" -p _): The system cannot find the file specified.
 (error: 2)
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/users/mark/_bazel_mark/msumpq5c/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 477, column 15, in _yarn_install_impl
                _copy_file(repository_ctx, repository_ctx.attr.package_json)
        File "C:/users/mark/_bazel_mark/msumpq5c/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 212, column 17, in _copy_file
                fail("mkdir -p %s failed: \nSTDOUT:\n%s\nSTDERR:\n%s" % (dirname, result.stdout, result.stderr))
Error in fail: mkdir -p _ failed:
STDOUT:

STDERR:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("mkdir" -p _): The system cannot find the file specified.
 (error: 2)
ERROR: no such package '@npm_deps//@bazel/protractor': mkdir -p _ failed:
STDOUT:

STDERR:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("mkdir" -p _): The system cannot find the file specified.
 (error: 2)
INFO: Elapsed time: 0.342s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Windows 10 64 bit
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 4.0.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 21 07:39:16 2021 (1611214756)
Build timestamp: 1611214756
Build timestamp as int: 1611214756
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
commit 38db19db73c1cfe0e2426d11cebd08e862b5f7c6 (HEAD -> stable, origin/stable, origin/HEAD)
Author: Urian Chang <urian.chang@dominodatalab.com>
Date:   Tue Feb 23 16:18:42 2021 -0800

    Add Domino Data Lab as rules_nodejs adopter (#2485)
  </code>
</pre>

**Comment by bombsimon** [comment]
The version of `mkdir` bundled with Windows does not support the `-p` flag and thus the command will fail. A workaround while waiting for a fix could be to install `mkdir` with f.ex. [`scoop`](https://scoop.sh/) by install the `coreutils` package. `coreutils` is [bundled with a version of `mkdir`](https://github.com/rivy/scoop.bucket.scoop-main/blob/master/coreutils.json#L43) which supports the flag.

**Comment by tomdegoede** [comment]
Same issue here. Is the -p flag require don unix or can it just be removed?

**Comment by mattem** [comment]
Ooof, I wonder if the Buildkite CI is running Windows 7, or has some extra bins installed that makes this work. 
@philwo do you know if we can run against Windows 10 on Bazel CI? 🙏

**Comment by pshields** [comment]
FYI, a potentially similar `mkdir` Windows issue I ran into in #2458 were resolved by installing MSYS2 on my Windows machine, as mentioned by the Bazel documentation in https://docs.bazel.build/versions/4.0.0/install-windows.html (`You will need MSYS2 to build, test, or run targets that depend on Bash. Typically these are genrule, sh_binary, sh_test, but there may be more (e.g. Starlark rules).`). Perhaps installing MSYS2 would resolve your issue?

(I think it's probably worth mentioning this somewhere in the rules_nodejs documentation, and ideally printing a more helpful error message when MSYS2 is not installed.)

**Comment by pshields** [comment]
FYI, a potentially similar `mkdir` Windows issue I ran into in #2458 was resolved by installing MSYS2 on my Windows machine, as mentioned by the Bazel documentation in https://docs.bazel.build/versions/4.0.0/install-windows.html (`You will need MSYS2 to build, test, or run targets that depend on Bash. Typically these are genrule, sh_binary, sh_test, but there may be more (e.g. Starlark rules).`). Perhaps installing MSYS2 would resolve your issue?

(I think it's probably worth mentioning this somewhere in the rules_nodejs documentation, and ideally printing a more helpful error message when MSYS2 is not installed.)

**Comment by khogeland** [comment]
I had to add MSYS2's `usr/bin` to my Windows path var to get around this issue.

All the shell rules (AFAIK) will use MSYS2 from its default location if it exists, but `repository_ctx.execute` uses the system shell. This is the only place I've found that requires changing the Windows path; couldn't this instance just be changed to `mkdir _`, `mkdir _/whatever`?

**Comment by pshields** [comment]
> I had to add MSYS2's usr/bin to my Windows path var to get around this issue.

Thanks for mentioning that; I had to do that step this time when I was trying out some rules_nodejs stuff on a new Windows machine.

**Comment by tomdegoede** [comment]
Supposedly Fixed by #2697 ?
