### ISSUE TITLE
esbuild README could benefit from docs on required rules_nodejs version

### ISSUE THREAD

**Issue by bduffany** [bazelbuild/rules_nodejs#2493]
I ran into this issue when trying to use esbuild:

```
        File "/home/b/.cache/bazel/_bazel_b/b1efedad95ff8a846adc47f250b077fb/external/npm/@bazel/esbuild/esbuild.bzl", line 6, column 75, in <toplevel>
                load("@build_bazel_rules_nodejs//internal/linker:link_node_modules.bzl", "MODULE_MAPPINGS_ASPECT_RESULTS_NAME", "module_mappings_aspect")
Error: file '@build_bazel_rules_nodejs//internal/linker:link_node_modules.bzl' does not contain symbol 'MODULE_MAPPINGS_ASPECT_RESULTS_NAME'
```

Guessing it's because I'm on an outdated version of `rules_nodejs` (`^2.3.0`) -- but the README in `@bazel/esbuild` doesn't mention which version is required -- might be useful to add docs on the required version so that other folks don't run into this issue :)

**Comment by mattem** [comment]
It's expected that the version of rules_nodejs in the bazel `WORKSPACE` match the `@bazel` packages in the `package.json` file.
However, we should explicitly call this out somewhere if we don't already, I think it's only hinted at in the release notes.
Note that this isn't specific to the esbuild package.

**Comment by bduffany** [comment]
Would make things a bit more user friendly if the tooling itself could print a warning when the versions don't match -- is that something that seems possible to do? I wouldn't mind contributing a PR but not exactly sure where to start

**Comment by mattem** [comment]
Ah yeah, we do already have that, seems it wasn't included in the package.json postinstall for the esbuild package
