### ISSUE TITLE
Cypress Custom Commands Not Available

### ISSUE THREAD

**Issue by tobiasschweizer** [bazelbuild/rules_nodejs#2502]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 

`cypress_web_test`

### Is this a regression?

I've only started to use `@bazel/cypress` recently. I did not work with any previous version.

I use the following versions:
- `@bazel/cypress@3.1.0` 
- `cypress@6.4.0`

### Description

Following the examples given in this [repo](https://github.com/bazelbuild/rules_nodejs/tree/stable/examples/cypress), we were able to set up working e2e tests with `cypress` and Bazel. 

However, we have defined some [custom commands](https://docs.cypress.io/api/cypress-api/custom-commands.html) like "login" in `commands.ts` but these are not available from the [spec file](https://github.com/dasch-swiss/dsp-tangoh-app/blob/64e01d7fe4a7dc3930e4dcc5910e63c876d15776/cypress/integration/login.spec.ts#L6), resulting in an error.

This is the [setup](https://github.com/dasch-swiss/dsp-tangoh-app/blob/64e01d7fe4a7dc3930e4dcc5910e63c876d15776/cypress/integration/BUILD.bazel#L103-L126).
             
## 🔬 Minimal Reproduction

https://github.com/dasch-swiss/dsp-tangoh-app/runs/2032029031#step:9:332

https://github.com/dasch-swiss/dsp-tangoh-app/pull/11

## 🔥 Exception or Error

<pre><code>cypress/integration/login.spec.ts:6:12 - error TS2339: Property 'login' does not exist on type 'cy & EventEmitter'.
cy.login('anything.user01@example.org', 'test');</code></pre>

## 🌍  Your Environment

**Operating System:**

Ubuntu-latest on GitHubCI , see https://github.com/dasch-swiss/dsp-tangoh-app/blob/wip/e2e-setup/.github/workflows/main.yml

**Output of `bazel version`:**

See https://github.com/dasch-swiss/dsp-tangoh-app/blob/wip/e2e-setup/package.json

**Rules_nodejs version:**

Node version 14 on GitHubCI , see https://github.com/dasch-swiss/dsp-tangoh-app/blob/wip/e2e-setup/.github/workflows/main.yml

**Comment by tobiasschweizer** [comment]
Any hint would be highly appreciated. It seems that "command.ts" is not loaded / executed before running the specs. However, when I run `npx cypress open --config-file cypress/cypress.json`, it works.

**Comment by alexeagle** [comment]
looks like just a typecheck error in a `ts_library` rule and not happening when cypress is running. What happens if you just disable that one typecheck (like casting through `any`)?
Feels like it's probably not a bazel-specific issue but I don't have time to read through all those resources you posted

**Comment by tobiasschweizer** [comment]
> looks like just a typecheck error in a `ts_library` rule and not happening when cypress is running. What happens if you just disable that one typecheck (like casting through `any`)?
> Feels like it's probably not a bazel-specific issue but I don't have time to read through all those resources you posted

Thanks for your response. Which `ts_library` rule are you referring to? Would I have to apply the cast in the rule itself?

**Comment by mattem** [comment]
The typecheck would likely be solved by following this guide from Cypress? 
https://docs.cypress.io/guides/tooling/typescript-support.html#Types-for-custom-commands

Something like:
```
declare namespace Cypress {
  interface Chainable {
    login(username: string, password: string): Chainable<Element>
  }
}
```

**Comment by tobiasschweizer** [comment]
I'll try that, thanks a lot for the hint (and reminder to RTFM :-))
