### ISSUE TITLE
"Cannot find module" error when importing library in jasmine test, despite proper deps

### ISSUE THREAD

**Issue by bduffany** [bazelbuild/rules_nodejs#2511]
# 🐞 bug report

### Description

When running a `jasmine_node_test` that imports a testing library, I get the error `Cannot find module 'nodejs_example/testing/server'` -- even though the name of the workspace is `nodejs_example` and I have the `ts_library` which builds `testing/server.js` as a `dep` of the test library.

## 🔬 Minimal Reproduction

See https://github.com/bduffany/buildbuddy-nodejs-example/pull/2/files

```bash
git clone https://github.com/bduffany/buildbuddy-nodejs-example
cd buildbuddy-nodejs-example
git fetch origin initial-html-test
git checkout initial-html-test
bazel test //test/integration/initial_html:initial_html_test
```

## 🔥 Exception or Error

<pre><code>
(node:53) UnhandledPromiseRejectionWarning: Error: Cannot find module 'nodejs_example/testing/server'
Require stack:
- /home/b/.cache/bazel/_bazel_b/394f0006a5dfe1600b5f4381c1753f49/sandbox/linux-sandbox/179/execroot/nodejs_example/bazel-out/k8-fastbuild/bin/test/integration/initial_html/initial_html_test.sh.runfiles/nodejs_example/test/integration/initial_html/initial_html_test.js
- /home/b/.cache/bazel/_bazel_b/394f0006a5dfe1600b5f4381c1753f49/sandbox/linux-sandbox/179/execroot/nodejs_example/bazel-out/k8-fastbuild/bin/test/integration/initial_html/initial_html_test.sh.runfiles/npm/node_modules/jasmine/lib/loader.js
- /home/b/.cache/bazel/_bazel_b/394f0006a5dfe1600b5f4381c1753f49/sandbox/linux-sandbox/179/execroot/nodejs_example/bazel-out/k8-fastbuild/bin/test/integration/initial_html/initial_html_test.sh.runfiles/npm/node_modules/jasmine/lib/jasmine.js
- /home/b/.cache/bazel/_bazel_b/394f0006a5dfe1600b5f4381c1753f49/sandbox/linux-sandbox/179/execroot/nodejs_example/bazel-out/k8-fastbuild/bin/test/integration/initial_html/initial_html_test.sh.runfiles/npm/node_modules/@bazel/jasmine/index.js
- /home/b/.cache/bazel/_bazel_b/394f0006a5dfe1600b5f4381c1753f49/sandbox/linux-sandbox/179/execroot/nodejs_example/bazel-out/k8-fastbuild/bin/test/integration/initial_html/initial_html_test.sh.runfiles/npm/node_modules/@bazel/jasmine/jasmine_runner.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /home/b/.cache/bazel/_bazel_b/394f0006a5dfe1600b5f4381c1753f49/sandbox/linux-sandbox/179/execroot/nodejs_example/bazel-out/k8-fastbuild/bin/test/integration/initial_html/initial_html_test.sh.runfiles/nodejs_example/test/integration/initial_html/initial_html_test.js:13:22
    at /home/b/.cache/bazel/_bazel_b/394f0006a5dfe1600b5f4381c1753f49/sandbox/linux-sandbox/179/execroot/nodejs_example/bazel-out/k8-fastbuild/bin/test/integration/initial_html/initial_html_test.sh.runfiles/nodejs_example/test/integration/initial_html/initial_html_test.js:3:17
    at Object.<anonymous> (/home/b/.cache/bazel/_bazel_b/394f0006a5dfe1600b5f4381c1753f49/sandbox/linux-sandbox/179/execroot/nodejs_example/bazel-out/k8-fastbuild/bin/test/integration/initial_html/initial_html_test.sh.runfiles/nodejs_example/test/integration/initial_html/initial_html_test.js:9:3)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Loader.requireShim [as require_] (/home/b/.cache/bazel/_bazel_b/394f0006a5dfe1600b5f4381c1753f49/sandbox/linux-sandbox/179/execroot/nodejs_example/bazel-out/k8-fastbuild/bin/test/integration/initial_html/initial_html_test.sh.runfiles/npm/node_modules/jasmine/lib/loader.js:35:3)
    at /home/b/.cache/bazel/_bazel_b/394f0006a5dfe1600b5f4381c1753f49/sandbox/linux-sandbox/179/execroot/nodejs_example/bazel-out/k8-fastbuild/bin/test/integration/initial_html/initial_html_test.sh.runfiles/npm/node_modules/jasmine/lib/loader.js:28:12
    at new Promise (<anonymous>)
    at Loader.load (/home/b/.cache/bazel/_bazel_b/394f0006a5dfe1600b5f4381c1753f49/sandbox/linux-sandbox/179/execroot/nodejs_example/bazel-out/k8-fastbuild/bin/test/integration/initial_html/initial_html_test.sh.runfiles/npm/node_modules/jasmine/lib/loader.js:27:12)
    at Jasmine.loadSpecs (/home/b/.cache/bazel/_bazel_b/394f0006a5dfe1600b5f4381c1753f49/sandbox/linux-sandbox/179/execroot/nodejs_example/bazel-out/k8-fastbuild/bin/test/integration/initial_html/initial_html_test.sh.runfiles/npm/node_modules/jasmine/lib/jasmine.js:91:23)
    at Jasmine.execute (/home/b/.cache/bazel/_bazel_b/394f0006a5dfe1600b5f4381c1753f49/sandbox/linux-sandbox/179/execroot/nodejs_example/bazel-out/k8-fastbuild/bin/test/integration/initial_html/initial_html_test.sh.runfiles/npm/node_modules/jasmine/lib/jasmine.js:267:14)
(node:53) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:53) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
</code></pre>

## 🌍  Your Environment

**Operating System:** Ubuntu 20.04

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.7.3
Build label: 4.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 21 07:33:24 2021 (1611214404)
Build timestamp: 1611214404
Build timestamp as int: 1611214404
  </code>
</pre>

**Rules_nodejs version:** 3.2.1

**Comment by alexeagle** [comment]
As of 2.0 (this change https://github.com/bazelbuild/rules_nodejs/commit/044495c ), you need to explicitly tell us that your bazel workspace name is also an npm package you want to require from. See

https://bazelbuild.github.io/rules_nodejs/Built-ins.html#nodejs_binary-link_workspace_root

Though we mostly recommend using relative paths, or naming your subdirectory as an npm package and using the linker, so that your code is portable with non-Bazel builds (treating the workspace root as an npm package isn't a typical JS idiom)

**Comment by bduffany** [comment]
@alexeagle I'm importing that file using its relative path but still getting this error. Maybe something somewhere in the stack is trying to rewrite relative paths? https://github.com/bduffany/buildbuddy-nodejs-example/blob/430fdd29ceda395cb55ad06e27da195751f6299b/test/integration/initial_html/initial_html_test.ts

Maybe it's being rewritten because of `rootDirs` in our tsconfig.json? https://github.com/bduffany/buildbuddy-nodejs-example/pull/2/files#diff-b55cdbef4907b7045f32cc5360d48d262cca5f94062e353089f189f4460039e0

**Comment by alexeagle** [comment]
Ah yes, you're using `ts_library` which is documented as less compatible
https://bazelbuild.github.io/rules_nodejs/TypeScript.html#alternatives

It was designed for Google Closure JS which uses a `goog.module` syntax that always produces these absolute imports.

Can you use `ts_project` instead? I'd like to deprecate `ts_library`.

**Comment by bduffany** [comment]
Unrelated to this thread, but are there any tradeoffs we're making by switching to `ts_project`? The docs [here](https://sourcegraph.com/github.com/bazelbuild/rules_nodejs/-/blob/docs/TypeScript.md) mention that `ts_library` is fast and optimized -- is `ts_project` just as fast?

**Comment by alexeagle** [comment]
ts_project is fast with the experimental worker support (keeping `tsc` running between builds)

**Comment by mattboardman** [comment]
@alexeagle unrelated to the issue. Are you suggesting we use `ts_project` for new projects going forward?

**Comment by alexeagle** [comment]
https://bazelbuild.github.io/rules_nodejs/TypeScript.html#alternatives is the current guidance, but yeah I think we are ready to update that with "only use ts_library if you really want this peculiar Google-flavor JS"
