### ISSUE TITLE
Mark @bazel/karma deprecated on NPM

### ISSUE THREAD

**Issue by bduffany** [bazelbuild/rules_nodejs#2514]
Is there a way to mark https://www.npmjs.com/package/@bazel/karma as deprecated and point folks to the preferred alternatives? (The @bazel/karma package was deleted as of rules_nodejs v3). I tried importing this package into my rules_nodejs v3 project and was bitten by the version mismatch error.

**Comment by alexeagle** [comment]
Good suggestion! I ran
`npm deprecate @bazel/karma "As of https://github.com/bazelbuild/rules_nodejs/releases/tag/3.0.0 use @bazel/concatj
s instead"`
and it shows up on npm now.
