### ISSUE TITLE
rules should warn when typescript version is not compatible with the current rules_nodejs release

### ISSUE THREAD

**Issue by bduffany** [bazelbuild/rules_nodejs#2517]
If TS rules are using newer features that are only implemented in a certain version of TypeScript, then there should probably be an early error saying "TypeScript X.Y.Z is not compatible with rules_nodejs A.B.C; run `yarn upgrade typescript` to update."

See https://github.com/bazelbuild/rules_nodejs/issues/2515 for context

**Comment by alexeagle** [comment]
We already indicate the minimum range for the typescript package using the npm-idiomatic mechanism, peer dependencies

https://github.com/bazelbuild/rules_nodejs/blob/stable/packages/typescript/package.json#L26

I think the treatment of peer dependency warnings from npm install / yarn install is not very good, but I think that's out of our scope, so nothing more we can do here?
