### ISSUE TITLE
Hot reload - create-react-app

### ISSUE THREAD

**Issue by johnnypow** [bazelbuild/rules_nodejs#2521]
# 🐞 bug report

### Affected Rule

Example of create-react-app

### Is this a regression?

I don't know.

### Description

Hot reload from create react app not hot reloading.

## 🔬 Minimal Reproduction

1. Run `ibazel run //:start` in /examples/create-react-app
2. Modify App.tsx

-- ibazel runs, however the app is not restarted/refreshed.

```
iBazel [5:26PM]: Changed: "/rules_nodejs/examples/create-react-app/src/App.tsx". Rebuilding...
iBazel [5:26PM]: Running //:start
iBazel [5:26PM]: Notifying of changes
Loading:
Loading: 0 packages loaded
Analyzing: target //:start (0 packages loaded, 0 targets configured)
INFO: Analyzed target //:start (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[0 / 2] [Prepa] BazelWorkspaceStatusAction stable-status.txt
Target //:start up-to-date:
  bazel-bin/start.sh
  bazel-bin/start_loader.js
  bazel-bin/start_require_patch.js
INFO: Elapsed time: 0.395s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
iBazel [5:26PM]: IBAZEL BUILD SUCCESS
```

## 🔥 Exception or Error

A whole bunch of `No LinkablePackageInfo` and `Mappings at @npm//normalize-package-data:normalize-package-data__contents: {}` going on.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
    ProductName:	Mac OS X
    ProductVersion:	10.15.7
    BuildVersion:	19H524
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 3.6.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Mar 9 15:45:38 2021 (1615304738)
Build timestamp: 1615304738
Build timestamp as int: 1615304738
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
    3.2.2
  </code>
</pre>

**Anything else relevant?**

Nope

**Comment by alexeagle** [comment]
Yeah we haven't thought enough about how to make HMR work.

**Comment by martaver** [comment]
I just forked `rules_nodejs` and tried it myself, it's not just HMR - the app in browser won't update with changes after ibazel notifies. Not even with a refresh - the changes aren't being rebuilt by webpack.

**Comment by valgussev** [comment]
I have tried to find the commit which has introduced this issue but it seems only the initial commit with vanilla create-react-app worked https://github.com/bazelbuild/rules_nodejs/commit/b7bdab7d. I just want to highlight that it's not only the HMR which does not work, but also page reload does not take the changes into account.

**Comment by valgussev** [comment]
I have tried to find the commit which has introduced this issue but it seems only the initial one with vanilla create-react-app worked https://github.com/bazelbuild/rules_nodejs/commit/b7bdab7d. 

Just to highlight that is not only the HMR issue, page reload also does not work.

Any thoughts on what could be the issue or workarounds?

**Comment by alexeagle** [comment]
Sorry, right now we don't have time or resources to dig into this problem. Hoping to set up an OpenCollective to collect some funding from users, which might let us pay someone to contribute this sort of thing.

**Comment by cuyl** [comment]
@valgussev That was a hack to prevent `ibazel` sent EOF to stdin of the `react-scripts start` process, without `ibazel_notify_changes ` the process will stop immediately.  Is there another way to prevent EOF?

**Comment by jfroffice** [comment]
Is there still an error with the HMR ?

**Comment by alexeagle** [comment]
I think HMR can work with `js_run_devserver`

**Comment by AhammedAliBP** [comment]
I am able to run a React app (CRA 5) using js_run_devserver, but hot reload is not happening if I make any changes to the file. Can someone please help?

```
 js_run_devserver(
        name = "{}_dev".format(name),
        args = ["start"],
        chdir = native.package_name(),
        command = "/".join([".."] * len(native.package_name().split("/"))) + "/node_modules/.bin/react-scripts",
        data = srcs,
    )
```
