### ISSUE TITLE
Cannot use default outputs of a rule for srcs in ts_project

### ISSUE THREAD

**Issue by parabolala** [bazelbuild/rules_nodejs#2527]
# 🐞 bug report

### Affected Rule

ts_project, ts_config

### Is this a regression?

No

### Description

This issue looks similar to #2504, but this one doesn't involve filegroups. 

I have a rule (custom protobuf compiler) that outputs `*.ts` files in its `DefaultInfo.files`. I would like to use its produced `*.ts` files as input to `ts_project`, but this doesn't work currently. Specifying the name of the generating rule string that's not a `*.ts` source in srcs yields `Error in fail: ts_project target "//:tsconfig" is configured to produce no outputs.`

The `ts_project()` is a macro that tries to expand the provided `<>.ts` strings from `srcs` into `<>.d.ts` and `<>.js`. As it’s executed at the **loading** phase, it can’t expand the provided non-source rule name (e.g. `:example_ts_proto`) into the names of rule’s output `.ts`  files as they’re not known until the **analysis** phase. The macro then requests the `<src>.d.ts` outputs from the rule explicitly.

## 🔬 Minimal Reproduction

I have a repo where I use ts_project() to turn generated `.ts` file into `.d.ts` and `.js` for packaging: https://github.com/parabolala/bazel-ts-proto

The rule `//:example_ts_proto` has `.ts` files as outputs.

What I wanted to get in the end is to have the output of `bazel build :npm-pkg && find bazel-bin/npm-pkg` to include `.d.ts` and `.js` files, but not the `.ts` sources.

The repo has a patch that workarounds the issue. The issue is reproduced by removing `"postinstall": "patch-package"` from `package.json`.

## 🔥 Exception or Error

```Error in fail: ts_project target "//:tsconfig" is configured to produce no outputs.

Note that ts_project must know the srcs in advance in order to predeclare the outputs.
Check the srcs attribute to see that some .ts files are present (or .js files with allow_js=True).
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS Big Sur
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: development
Build label: 4.0.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 21 07:38:50 2021 (1611214730)
Build timestamp: 1611214730
Build timestamp as int: 1611214730
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
3.2.1
  </code>
</pre>

**Anything else relevant?**

A workaround/hack that got me the expected result (not a thoughtful fix) is at https://github.com/parabolala/bazel-ts-proto/blob/main/patches/%40bazel%2Btypescript%2B3.2.2.patch. Essentially it changes `ts_config` to correctly expandnon-source-file inputs in its `srcs`. It also changes ts_project to not barf when no `*.ts` strings are specified as `ts_project` `srcs`.

**Comment by alexeagle** [comment]
We tried to cover this in https://bazelbuild.github.io/rules_nodejs/TypeScript.html#alternatives
> The only reason to use raw tsc is if you want to compile an opaque directory of .ts files and cannot enumerate them to Bazel. (For example if the .ts files are generated by some tool). This will produce an opaque directory of .js file outputs, which you won’t be able to individually reference.

Basically if you can't predict the .ts inputs at loading time, then just use `tsc` directly. 

However another observation here is that the proto rule you're using would be a lot more convenient if it produced .d.ts/.js pairs rather than .ts source files. The case of not knowing what are the .ts sources at loading time should be pretty rare, IMO
