### ISSUE TITLE
Feature: Allow using the `node` binary as present in PATH

### ISSUE THREAD

**Issue by kalbasit** [bazelbuild/rules_nodejs#254]
Hello,

I'm using [NixOS](https://nixos.org) as my daily driver. NixOS does not provide an FHS so the downloaded binaries such as nodejs do not work.

The nodejs binary that end up getting installed in NixOS is located at `/nix/store/q05xbja14rsgqzknmmlkajnzacjnp4hl-nodejs-8.11.3/bin/node` for my system (x86_64) at this [nixpkgs version](https://github.com/NixOS/nixpkgs/commit/fddd90e9eaf7063156721ac7a296b2f219edb92e). However this path is different on Mac and is going to change if the nixpkgs version changes or any of the libarires that nodejs depends on.

With this in mind, using [`node_path`](https://github.com/bazelbuild/rules_nodejs/blob/20ff5892612f8359aec8aaf26dd3902a24976ada/internal/node/node_repositories.bzl#L148-L150) to set the path to the nodejs binary is combersome and is definitely going to lead to errors as the system runnning Bazel changes.

Can we add support for using the host version of node, as detected by PATH? [`rules_go`](https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst#using-the-installed-go-sdk) is already doing that.

**Comment by alexeagle** [comment]
What is "FHS"?

We decided yesterday to break the ability to point `node_path` to a path on disk anyway, as you say that's not portable. It should be a label instead.

Thanks for the pointer to Go, that's interesting that they allow this. I'm not sure it's a good idea since you may have the wrong node version, and it makes your build non-remotable.

I don't understand what's actually broken for you. Does some bazel code fail to build/run?

**Comment by kalbasit** [comment]
I will try out #249 and report back if it helps. @alexeagle another blocker for me is #247.

**Comment by kalbasit** [comment]
@alexeagle the integration of rules_go and nix was solved by https://github.com/bazelbuild/rules_go/pull/1618 (see https://github.com/bazelbuild/rules_go/issues/1611#issuecomment-409363344 for more details on it works). 

>  It should be a label instead.

Is it possible to point to a node binary coming from another ruleset? Something like this:

```bzl
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_tweag_rules_nixpkgs",
    strip_prefix = "rules_nixpkgs-4575647f3795fee2a8b732f97076a363907f7248",
    url = "https://github.com/tweag/rules_nixpkgs/archive/4575647f3795fee2a8b732f97076a363907f7248.tar.gz",
    sha256 = "b4c1bd8ddab305c4c1e2ee3d52e82508867adcb5798156f22714ed91649301dc",
)

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "ee90a5e7e7f95b038e482641c112e225e6fd914c77d1d608e1248cd66b36533b",
    strip_prefix = "rules_go-a660c0a666b3d827131ad30f2aac323d32ee9db5",
    url = "https://github.com/jayconrod/rules_go/archive/a660c0a666b3d827131ad30f2aac323d32ee9db5.zip",
)

load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_git_repository", "nixpkgs_package")

nixpkgs_git_repository(
    name = "nixpkgs",
    revision = "95aa869f04c131d2b488ee36be721bf8af28c1a9",
    sha256 = "c34b8734c6110ae2cb2edcf5b3201232827e8c92a79b6fceb7f6c5566a36eee6",
)

nixpkgs_package(
    name = "nodejs-8_x",
    repository = "@nixpkgs"
)

// TODO: tell rules_nodejs that node is availble under @nodejs-8_x//:bin/node
```

The `node` binary is now available under @nodejs-8_x//:bin/node

```sh-session
$ bazel run @nodejs-8_x//:bin/node -- --version
(14:45:07) WARNING: Option 'experimental_remote_spawn_cache' is deprecated
(14:45:07) WARNING: Option 'experimental_remote_spawn_cache' is deprecated
(14:45:07) INFO: Current date is 2018-07-31
(14:45:07) INFO: Analysed target @nodejs-8_x//:bin/node (0 packages loaded).
(14:45:07) INFO: Found 1 target...
(14:45:07) INFO: Elapsed time: 0.148s, Critical Path: 0.03s
(14:45:07) INFO: 0 processes.
(14:45:07) INFO: Build completed successfully, 1 total action
(14:45:07) INFO: Build completed successfully, 1 total action
v8.11.3
```

**Comment by alexeagle** [comment]
@kalbasit sure, it shouldn't matter to us what workspace the label comes from.

I can imagine even if you have that formulation under nix, users might still ask us to allow their system node to be used under Bazel, seems like we should resolve that question on this issue.

**Comment by alexeagle** [comment]
We now let you point to a locally installed node when we added toolchain support, so I think this should work. Please comment/open a new issue if it doesn't work
