### ISSUE TITLE
Documentation issue: Built-ins

### ISSUE THREAD

**Issue by farcaller** [bazelbuild/rules_nodejs#2540]
The documentation [here](https://bazelbuild.github.io/rules_nodejs/Built-ins.html#npm_package_bin) states:

> These rules are available without any npm installation, via the WORKSPACE install of the build_bazel_rules_nodejs workspace. This is necessary to bootstrap Bazel to run the package manager to download other rules from NPM.

however it doesn't hold for `npm_package_bin` which needs to be loaded via `load("@build_bazel_rules_nodejs//:index.bzl", "npm_package_bin")`

**Comment by alexeagle** [comment]
That load statement comes from the built-in and doesn't require any npm packages be installed.

**Comment by farcaller** [comment]
My bad, I wasn’t thinking straight when I read the docs. Of course it makes sense now!
