### ISSUE TITLE
tsconfig.bzl overwrites preserveConstEnums Typescript setting

### ISSUE THREAD

**Issue by chrismatix** [bazelbuild/rules_nodejs#2543]
# 🚀 feature request

### Relevant Rules

bazelbuild/rules_typescript/internal/common/tsconfig.bzl

### Description

The `tsconfig.bzl` [hardcodes](https://github.com/bazelbuild/rules_nodejs/blob/c2927afa9a5d77652783f94eada80baf1c9be68f/third_party/github.com/bazelbuild/rules_typescript/internal/common/tsconfig.bzl#L250) the `preserveConstEnums` setting to `false`

Since we are using `isolatedModules` for downstream compilation with Babel we want to be able to set it to true. 

### Describe the solution you'd like

When setting `preserveConstEnums` to `true` it is not overwritten in `tsconfig.bzl`. While I can see from [this issue](bazelbuild/rules_typescript/internal/common/tsconfig.bzl) that this is part of Google's opinionated build tooling, allowing for an override while keeping the default seems like a good compromise.

### Describe alternatives you've considered

For now setting `isolatedModules` to `false` is a workaround but it makes working with downstream processors less safe.

**Comment by alexeagle** [comment]
This is one of many things that is brittle about `ts_library` and why we no longer recommend it. Could you consider using `ts_project` instead, where 100% of the TypeScript configuration space is available to you?

**Comment by chrismatix** [comment]
Thanks for the clarification @alexeagle! Yes, that seems like the best forward.
