### ISSUE TITLE
Incremental Next.js Example

### ISSUE THREAD

**Issue by flolu** [bazelbuild/rules_nodejs#2554]
[Next.js](https://github.com/vercel/next.js) is becoming increasingly popular. But the [examples for React](https://bazelbuild.github.io/rules_nodejs/examples#react) are not really developed.

So I'd like to emphasize on this TODO:
https://github.com/bazelbuild/rules_nodejs/blob/e92bc7ae6476d8d4c079a9947b59c197a2d84ff4/docs/examples.html#L228

It would be gorgeous to have a standardized example, like with [Angular](https://github.com/bazelbuild/rules_nodejs/tree/stable/examples/angular), for incrementally building and testing Next.js applications with Bazel.

I've noticed @alexeagle did start a draft for building Next.js apps [here](https://github.com/bazelbuild/rules_nodejs/pull/2068). But it seems to be abandoned.

Also, @lukasholzer [seems to have experience](https://github.com/vercel/next.js/issues/14778#issuecomment-717207992) in building Next.js apps with Bazel. Maybe you can help us out here?

**Comment by duarten** [comment]
I opened #2577 with a simple example.
