### ISSUE TITLE
Universal support for examples/angular_bazel_architect

### ISSUE THREAD

**Issue by flolu** [bazelbuild/rules_nodejs#2572]
I was trying to add universal support to [examples/angular_bazel_architect](https://github.com/bazelbuild/rules_nodejs/tree/stable/examples/angular_bazel_architect).

Here is what I've tried:

1. `ng add @nguniversal/express-engine`
2. Add a target for building the server:
    ```
    architect(
        name = "build_server_prod",
        args = [
            "frontend:server:production",
            "--outputPath=$(@D)",
        ],
        configuration_env_vars = ["NG_BUILD_CACHE"],
        data = glob(
            [
                "src/**/*",
            ],
            exclude = [
                "src/**/*.spec.ts",
                "src/test.ts",
            ],
        ) + APPLICATION_DEPS + [
            "tsconfig.app.json",
            "@npm//@nguniversal/builders",
            "@npm//@nguniversal/express-engine",
            "@npm//@types/express",
            "@npm//@angular/platform-server",
            "@npm//express",
            "build_prod",
        ],
        output_dir = True,
    )
    ```

But building `build_server_prod` terminates with an empty error:
```
ERROR

Logs:
Target //:build_server_prod failed to build
INFO: Elapsed time: 9.344s, Critical Path: 5.63s
INFO: 3 processes: 3 internal.
FAILED: Build did NOT complete successfully
```

I think the server build relies on the output of `build_prod`, but it probably expects it in an `dist/frontend/` directory. Maybe that's causing the error.

Would be great if we can make this work!

**Comment by alexeagle** [comment]
Can you add more logging somewhere to find out where the architect universal package is looking for inputs? From that error yeah it's hard to know which layer the problem is in.
