### ISSUE TITLE
How to add TailwindCSS to examples/angular?

### ISSUE THREAD

**Issue by flolu** [bazelbuild/rules_nodejs#2573]
Angular CLI v11.2 now supports [TailwindCSS](https://tailwindcss.com/) (https://github.com/angular/angular-cli/commit/73b409881f71a8235769a345356dcde3c568d0c3)

That's done by detecting a `tailwind.config.js` and then configuring `postcss` with it.
It works out of the box with [examples/angular_bazel_architect](https://github.com/bazelbuild/rules_nodejs/tree/stable/examples/angular_bazel_architect) (see this commit: https://github.com/flolu/angular-bazel-architect/commit/1bdf950f66a5cde634495481d4fd065e3a68e64f)

My question is what steps it would take to make TailwindCSS work for [examples/angular](https://github.com/bazelbuild/rules_nodejs/tree/stable/examples/angular)?

**Comment by mattem** [comment]
We've essentially have to do the same, configure `postcss` with a given `tailwind.config.js`, there wouldn't be any 'auto' configuration, just more rules in a BUILD file.
