### ISSUE TITLE
Importing typescript libraries with ts_project does not work

### ISSUE THREAD

**Issue by flolu** [bazelbuild/rules_nodejs#2575]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: ts_project

### Description

I am trying to migrate a personal project from `ts_library` to `ts_project`.
Suppose I have a `app` that imports from `libraries/a` and `libraries/b`.

With `ts_library` I can simply do
- `module_name = "@libraries/a"`
- and `module_name = "@libraries/b"`

`ts_project` does not have a `module_name` attribute. Thus I've tried to replicate this test: [import_package_by_name](https://github.com/bazelbuild/rules_nodejs/tree/stable/packages/typescript/test/ts_project/import_package_by_name). Via `js_library` and `package_name`

But I cannot make it work:

## 🔬 Minimal Reproduction

https://github.com/flolu/bazel-ts-project

- `yarn install`
- `yarn start`

## 🔥 Exception or Error

<pre><code>
  app/index.ts(1,15): error TS2307: Cannot find module '@libraries/a' or its corresponding type declarations.
  app/index.ts(2,15): error TS2307: Cannot find module '@libraries/b' or its corresponding type declarations.
</code></pre>

**Comment by mattem** [comment]
Two issues:

* Missing `declaration = True` from both `tsconfig.json` and the `ts_project` for the libraries.
* The `package_name` attr on the libraries `js_library` is set to `@libs/a` / `@libs/b`, but the import statements are `@libraries/a` / `@libraries/b`

```
diff --git a/libraries/a/BUILD b/libraries/a/BUILD
index 3f37245..e50db72 100644
--- a/libraries/a/BUILD
+++ b/libraries/a/BUILD
@@ -13,11 +13,12 @@ ts_project(
     name = "a",
     srcs = glob(["*.ts"]),
     tsconfig = "tsconfig",
+    declaration = True,
 )
 
 js_library(
     name = "a_js",
-    package_name = "@libs/a",
+    package_name = "@libraries/a",
     deps = [
         "a",
         "tsconfig",
diff --git a/libraries/a/tsconfig.json b/libraries/a/tsconfig.json
index db6dd58..7291582 100644
--- a/libraries/a/tsconfig.json
+++ b/libraries/a/tsconfig.json
@@ -1,6 +1,7 @@
 {
   "extends": "../../tsconfig.json",
   "compilerOptions": {
-    "moduleResolution": "node"
+    "moduleResolution": "node",
+    "declaration": true
   }
 }
diff --git a/libraries/b/BUILD b/libraries/b/BUILD
index 80826cf..eb9be37 100644
--- a/libraries/b/BUILD
+++ b/libraries/b/BUILD
@@ -13,11 +13,12 @@ ts_project(
     name = "b",
     srcs = glob(["*.ts"]),
     tsconfig = "tsconfig",
+    declaration = True,
 )
 
 js_library(
     name = "b_js",
-    package_name = "@libs/b",
+    package_name = "@libraries/b",
     deps = [
         "b",
         "tsconfig",
diff --git a/libraries/b/tsconfig.json b/libraries/b/tsconfig.json
index db6dd58..7291582 100644
--- a/libraries/b/tsconfig.json
+++ b/libraries/b/tsconfig.json
@@ -1,6 +1,7 @@
 {
   "extends": "../../tsconfig.json",
   "compilerOptions": {
-    "moduleResolution": "node"
+    "moduleResolution": "node",
+    "declaration": true
   }
 }
```

Applying the diff above results in the following output from the `nodejs_binary`

```
bazel run //app:bin
INFO: Analyzed target //app:bin (0 packages loaded, 1 target configured).
INFO: Found 1 target...
Target //app:bin up-to-date:
  bazel-bin/app/bin.sh
  bazel-bin/app/bin_loader.js
  bazel-bin/app/bin_require_patch.js
INFO: Elapsed time: 0.190s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
a b
```

**Comment by flolu** [comment]
Thank you very much, Matt!

**Comment by flolu** [comment]
I want to test `libraries/a`. I've added
- `index.test.ts`
- `tsconfig.test.json`
- a `ts_project` target for the test file
  ```
  ts_project(
      name = "a_test",
      srcs = ["index.test.ts"],
      declaration = True,
      tsconfig = "tsconfig_test",
      deps = [
          "a",
          "@npm//@types/jasmine",
          "@npm//@types/node",
      ],
  )
  ```
- and a `jasmine_node_test` target 
  ```
  jasmine_node_test(
      name = "test",
      config_file = "jasmine.json",
      templated_args = ["--bazel_patch_module_resolver"],
      deps = ["a_test"],
  )
  ```

But running `yarn test` throws this error:
```
libraries/a/index.test.ts(1,15): error TS2307: Cannot find module './index' or its corresponding type declarations.
```

You can try it yourself: https://github.com/flolu/bazel-ts-project

What am I doing wrong?

**Comment by mattem** [comment]
If your importing from bazel-out (which you are here), then you need to set `rootDirs` appropriately. Something like:

```
"rootDirs": [
        ".",
        "../../bazel-out/host/libraries/a",
        "../../bazel-out/darwin-fastbuild/bin/libraries/a",
        "../../bazel-out/k8-fastbuild/bin/libraries/a",
        "../../bazel-out/x64_windows-fastbuild/bin/libraries/a",
        "../../bazel-out/darwin-dbg/bin/libraries/a",
        "../../bazel-out/k8-dbg/bin/libraries/a",
        "../../bazel-out/x64_windows-dbg/bin/libraries/a",
    ]
```

This is outlined on the [ts_project docs page](https://bazelbuild.github.io/rules_nodejs/TypeScript.html#ts_project-1)

I think the project you linked is also missing the peer dependencies from `@bazel/jasmine` of `jasmine` and `jasmine-core`.

**Comment by flolu** [comment]
Ouch, that is ugly. This only seems to work when I add it to `libraries/a/tsconfig.json`
Is it possible to declare those `rootDirs` once in the root `/tsconfig.json`?

**Comment by matthewjh** [comment]
I am in a similar position @flolu. I have a large codebase that is working with `ts_library`, relatively happily, that I want to move to `ts_project`. My hope was that `ts_project` would, in the mid term, be a simplification over `ts_library`.

The need to enumerate a mass of paths in `rootDirs` makes it practically infeasible for larger projects. 

At this point, `ts_library` is far simpler to use. I'm surprised that `ts_project` is the recommended go-to TS rule in its current state.

Is there an example of a codebase using `ts_project` with more than a few targets, all inter-dependent? I would be interested to see how they cope with the config as I do wonder whether I'm missing something.

**Comment by alexeagle** [comment]
@matthewjh we have some examples in `/packages/typescript/test/ts_project` as well as the examples/ in the repo.

`ts_library` is simpler to configure for sure. However it's much harder to make sense of its outputs and it's less compatible with the ecosystem. The tradeoff in `ts_project` is that it's a thin wrapper around calling `tsc` so now users are exposed to the semantics of TypeScript's compiler.

The easy way to deal with rootdirs is put those seven lines in your root `tsconfig.json` (the one the editor uses, likely) and then just use `extends` in the others so they also know where bazel's output folder lives.

There is some discussion of smoothing this migration path, I do appreciate that it's difficult right now and you're right that the regression in user experience is something we should fix. Probably we'll do that by validating the inputs you're giving to TypeScript and improving error messaging, rather than introducing a bunch of complexity within the rule like a custom compiler or generating a tsconfig.

**Comment by alexeagle** [comment]
the `rootDirs` setting should be to the package containing the `tsconfig.json` file IIUC
