### ISSUE TITLE
ts_project -> concatjs_devserver "exports is not defined" 

### ISSUE THREAD

**Issue by pyle** [bazelbuild/rules_nodejs#2585]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 

```
load("@npm//@bazel/typescript:index.bzl", "ts_project")
load("@npm//@bazel/concatjs:index.bzl", "concatjs_devserver")

ts_project(
    name = "app",
    srcs = glob(["**/*.ts"]), # Where we have a sub directory with a TypeScript file imported in to the a 'main' entry point.
)

concatjs_devserver(
    name = "devserver",
    serving_path = "/bundle.js",
    static_files = [
        "index.html",
    ],
    deps = [":app"],
)
```

### Is this a regression?

Not sure; This is my first time using `ts_project()` over multiple `ts_library()` targets; Also the first time using the `concatjs_devserver()` rule as opposed to the older `ts_devserver()`.

### Description

If using the `concatjs_devserver` and importing sub modules when using `ts_project()` compilation will succeed but in browser we'll recieve the `Uncaught ReferenceError: exports is not defined` error. 
I did try specifying my own tsconfig file and some different compilation option but could not quite get the right set in order to remove these kinds of import/module errors.

## 🔬 Minimal Reproduction

Repo: https://github.com/pyle/concatjs_bazel_repro/tree/0df72f03d0d440c9a2dc92725056b06e9d3ac5ba

1. Run `ibazel run //app:devserver`
2. Observe in Browser `Uncaught ReferenceError: exports is not defined` error.

## 🔥 Exception or Error

<pre><code>

Uncaught ReferenceError: exports is not defined
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Windows 10
Chrome 89
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 3.6.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Oct 6 13:11:20 2020 (1601989880)
Build timestamp: 1601989880
Build timestamp as int: 1601989880
  </code>
</pre>

**Rules_nodejs version:** https://github.com/pyle/concatjs_bazel_repro/tree/0df72f03d0d440c9a2dc92725056b06e9d3ac5ba

**Anything else relevant?**

I know docs don't mention that you can use this devserver with `ts_project` but my assumption is that it would work or we'd have a devserver (documented) that is compatible with `ts_project()` (given that's the rule of choice going forward).

**Comment by alexeagle** [comment]
As described on the readme for `@bazel/concatjs` package, inputs have to use named AMD/UMD format. So your TS files need to declare module names. I'll send a PR adding an example to the README...

**Comment by alexeagle** [comment]
I should add, ConcatJS is an advanced bundler that requires you are careful about the module syntax of both your code and your third-party dependencies. It sounds like you had that working previously with `ts_library` so you can make this work the same way. But it's certainly harder than using a more common JS bundler that understands lots of module syntax.
