### ISSUE TITLE
esbuild: sub-dependencies resolved incorrectly

### ISSUE THREAD

**Issue by ofagbemi** [bazelbuild/rules_nodejs#2586]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: esbuild

### Is this a regression?

No

### Description

Let's say that I'm bundling some code that depends on `module-a@1` and `module-b`. `module-b` depends on a different version of `module-a` — let's say `module-a@2`. In the bundle, `module-a` gets resolved to `module-a@1`, even if we never import `module-a` directly and it only actually gets imported via `module-b`.

I think this might be happening because the [esbuild rule uses the tsconfig `paths` field](https://github.com/bazelbuild/rules_nodejs/blob/d10e17cc4dc0e5f3753595c74134e2cc8dc4a8b9/packages/esbuild/esbuild.bzl#L44). The module is getting resolved to `@npm/node_modules/module-a` instead of to `@npm/node_modules/module-b/node_modules/module-a`.

My real-world example is trying to use `next` — which depends on `styled-jsx -> stylis@3` — and `@emotion/css` — which depends on `@emotion/cache -> stylis@4` — together.

## 🔬 Minimal Reproduction

Here's a repo that repros: https://github.com/ofagbemi/esbuild-test

In the example, module-1 includes `stylis@3` and `@emotion/css`, which includes `stylis@4`. To see the issue,
1. run `bazel build :bundle`
2. open `bazel-bin/module-1/bundle.js`
3. notice that only one copy of `stylis.js` actually gets bundled — the one at `external/npm/node_modules/stylis/stylis.js` (can ctrl/cmd-f for "stylis.js")

Note that esbuild handles this fine on its own. You can compare the above to the output of `npx esbuild module-1/index.ts --bundle --platform=node > test-bundle.js` — esbuild properly includes both `node_modules/stylis/stylis.js` and `node_modules/@emotion/cache/node_modules/stylis/dist/umd/stylis.js`.

I think the problem is with the way the Bazel esbuild rule sets the [tsconfig `paths` field](https://github.com/bazelbuild/rules_nodejs/blob/d10e17cc4dc0e5f3753595c74134e2cc8dc4a8b9/packages/esbuild/esbuild.bzl#L44) — you can observe a similar issue if you set paths to something like `{ "*": "./node_modules/*" }`.

## 🔥 Exception or Error

n/a

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
MacOS Catalina v10.15.7
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: development
Build label: 4.0.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 21 07:38:50 2021 (1611214730)
Build timestamp: 1611214730
Build timestamp as int: 1611214730
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
3.2.3
  </code>
</pre>

**Anything else relevant?**

**Comment by mattem** [comment]
Hm, this mapping is so esbuild can find the `node_modules` tree inside the `external` folder, rather than at the sources root. Is there a way to tell esbuild that the `node_modules` tree is somewhere else without providing this mapping?

A solution would be run esbuild via the `run_node` helper, rather than just calling it directly on the command line, as that would run the linker first, but that is a larger refactor and would force us into using the JS API, which I don't think we've made a decision on yet.

Given that it can be repro'd without bazel, perhaps we can file an issue upstream to give the ability to change where `node_modules` resides without adding to the `path` mappings in a `jsconfig` file.

**Comment by mattem** [comment]
I wonder if instead we could split out calling the linker from the node_launcher so it could be called via other scripts, and have some common starlark to setup args etc.
