### ISSUE TITLE
ESBuild issue: Relative paths when working in a monorepo

### ISSUE THREAD

**Issue by Aghassi** [bazelbuild/rules_nodejs#2588]
If you invoke esbuild from the root of a monorepo, all import paths in a given compilation will be relative to the root of the monorepo. For example, if I import `./a.js` from `//path/to/project`, esbuild will fail to find the module because `./a.js` will be looking at the monorepo root. ESBuild supports https://esbuild.github.io/api/#working-directory through their build api, so if we can use the build api to invoke we will be able to just pass along whatever value the user specifies.

CC @mattem

**Comment by Aghassi** [comment]
Nevermind, this is me not adding sources correctly

**Comment by kyubisation** [comment]
@Aghassi I am currently struggling with this. Do you perhaps have an example of how to configure this correctly?

**Comment by Aghassi** [comment]
I'll have to look on Monday as I pivoted from this at work. @mattem and I are working on it in the limited time we have amongst other things, but happy to show what I have.

**Comment by kyubisation** [comment]
Hello @Aghassi 
Thank you very much, but I think I had a basic misunderstanding on how to configure it.
@mattem managed to answer this: https://github.com/bazelbuild/rules_nodejs/issues/2691#issuecomment-846429871
