### ISSUE TITLE
Build output missing when building a nuxt npm_package_bin and the code is not in the WORKSPACE directory

### ISSUE THREAD

**Issue by Bogdan-Catalin** [bazelbuild/rules_nodejs#2605]
# 🐞 bug report

### Affected Rule

nodejs_binary running nuxt.

### Description

When building a nuxt project from a different directory than the WORKSPACE directory (for example `app/` in the repo under Minimal Reproduction) there are no output directories despite getting logs from nuxt that it built everything. 

## 🔬 Minimal Reproduction

Sketched an example repo [here](https://github.com/Bogdan-Catalin/bazel-nuxt-containerized). I also tried setting `chdir` when building from repo root, but it doesn't help much.

## 🔥 Exception or Error

Build results are not present in bazel-out, just an empty `.nuxt` folder when running `bazel build //app:.nuxt`.

## 🌍  Your Environment

**Operating System:**
MacOS BigSur
Debian Buster

**Output of `bazel version`:**
3.7.2

**Rules_nodejs version:**
3.3.0

**Comment by Bogdan-Catalin** [comment]
@alex374 So far no. In more complicated projects there's no output even when building from the nuxt project root with a WORKSPACE file defined there.

**Comment by mhallmark** [comment]
Also facing this issue.
