### ISSUE TITLE
Module resolution problems for dev servers under mono repo setup

### ISSUE THREAD

**Issue by DumbledoreD** [bazelbuild/rules_nodejs#2618]
I'm having problems getting dev servers running under a mono repo setup. 

The initial compilation is good. But susequent compilations caused by file changes always throw "Can not find module" errors.

Debugging shows that during the initial compilation, modules are resolved to `.../dev.sh.runfiles/<workspace-name>/<package-name>`. But on the subsequent compilations, modules are resolved to `.../dev.sh.runfiles/<workspace-name>/node_modules/<package-name>`. Note the extra `node_modules` in the path.

For non-react projects, I've successfully solved the problem by symlinking `node_modules`.

But for react projects, like Next.js, symlink will casue "invalid hook" error.

The above can be reproduced with https://github.com/DumbledoreD/nextjs-bazel-repro. Start the dev server with `yarn install && cd next-app && yarn dev`. Make some change to one of the tsx files, and the error will appear in the console.

Any help is appreciated. Thanks.

**Comment by DumbledoreD** [comment]
Possibly related to https://github.com/bazelbuild/rules_nodejs/issues/2205.

**Comment by DumbledoreD** [comment]
A few things that I've tried without success

1. Ran with and without `--bazel_run_from_execroot` flag.
2. Ran with and without `--bazel_patch_module_resolver` flag.
3. Ran with and without `chdir = package_name()`.
4. Combinations of 1,2,3,
5. Force Webpack to resolve modules with `config.resolve.modules = [path.resolve("/path/to/root", "node_modules")]`.

**Comment by pwalker** [comment]
@DumbledoreD What version of rules_nodejs are you using?  When using rules_nodejs 4.6.3, I've got no error and I get the next.js dev server working with ibazel.  Then, if I don't change any options but upgrade to rules_nodejs 5.2.0 I get an "invalid hook"-type error when I load the page in a browser.

I don't yet know enough about the differences between these versions to make heads or tails of whats going on, but I thought I'd drop a comment in case it's useful to any future googling.
