### ISSUE TITLE
TypeScript compilation of files reachable from an entry point

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#2642]
TypeScript has the behavior that if you run `tsc a.ts` and `a.ts` contains an import from `./b.ts`, then that module is automatically included in the program and emitted.

This means that legacy builds might be configured to compile an "entry point" file, and then emit .js outputs for all reachable files. Non-reachable files might not correctly type-check and *must not* be included in the program.

Since `ts_project` currently requires an exhaustive list of `srcs` and expects outputs for each of these `srcs`, this is currently difficult to use. You'd be forced to run vanilla `tsc` instead, producing an `output_dir` which makes downstream usage of those outputs harder.

Instead we could imagine some tooling as part of a BUILD file generator that uses the TypeScript API to query the compiler for which srcs belong in a given program, then write these to the `srcs` list of the ts_project rule. 

Note I have some WIP for this over here: https://github.com/stackb/bzl-configure/blob/master/src/plugin_ts_project.ts

**Comment by gregmagolan** [comment]
No longer in scope for rules_nodejs which only supplies the Node.js toolchain as of [v6.0.0](https://github.com/bazelbuild/rules_nodejs/releases/tag/v6.0.0-beta0).

Downstream canonical JavaScript + Node.js ruleset is now https://github.com/aspect-build/rules_js.
