### ISSUE TITLE
Break our python dependency; makes install more cumbersome

### ISSUE THREAD

**Issue by filipesilva** [bazelbuild/rules_nodejs#265]
Right now, setting up the `rules_nodejs` repository on Windows requires:
- Bazel itself
- Visual C++ Build Tools 2015 (used in `//:docs`, but docs seems broken on windows anyway)
- Python (used in `//internal/common:check_bazel_version_test` because that is a python file)

If the targets mentioned above are not built, it is possible to build and test `rules_nodejs` on Windows with just Bazel:

- build all via `bazel build -- ... -//:docs`, 
- test all via `bazel test -- ... -//:docs -//internal/common:check_bazel_version_test`.

/cc @alexeagle

**Comment by alexeagle** [comment]
Updating to new doc generator is happening in the background, so I'll re-purpose this to say we should test our skylark code using a skylark interpreter rather than python.

@dslomov do you have some pointer to the latest on how to write skylark unit tests in open-source?

**Comment by alexeagle** [comment]
We no longer require users to install our repo, so they should not be exposed to any python dependency.

I'm less concerned about the requirements for developing in this repo.
