### ISSUE TITLE
Allow for lazy loading of npm dependencies when using cypress

### ISSUE THREAD

**Issue by JesseTatasciore** [bazelbuild/rules_nodejs#2666]
# 🚀 feature request

### Relevant Rules
`cypress_repository`
`cypress_web_test`

### Description

When importing the cypress rules (following the outlined example) we need to add multiple references to our npm / yarn install within the WORKSPACE file. This breaks the lazy loading of our `yarn_install`.

As far as I can tell, there are 3 problem points.

The first, is the dependency on `@bazel/cypress` in the WORKSPACE file. This can be solved by pulling the given tgz directly from npm via a `http_archive`, instead of through a yarn / npm install. Seems fairly straightforward.

The second, is the npm dependency on cypress in the WORKSPACE file. This dependency is used to get a cypress binary. Hopefully we can do something similar to esbuild where we download some native binaries for the different platforms and have the rule use those accordingly.

The third, is that the repo rule itself will need some changes to allow for the above 2 points. I made the 2 above changes locally but it breaks the repo rules in its current state. As far as I can tell the repo rule is relying on / needs the deps (at least the `@bazel/cypress` one) coming from an NPM install (but I will need to do some more investigation).

If this seems like a valid request, then I am more than willing to make an attempt at implementing. (If its already possible then the example should be updated to show how)

**Comment by zacharyliu** [comment]
The workaround we're using is to add an `http_archive` to `WORKSPACE`. As you mentioned, with this setup alone `@bazel/cypress` still needs to be installed via `package.json`, but it does seem to at least avoid the costly `yarn_install` step for unrelated targets.

```py
http_archive(
    name = "npm_bazel_cypress",
    patch_cmds = [
        "mkdir @bazel && mv package @bazel/cypress",
    ],
    # Replace sha256 and url with the same version from package.json.
    sha256 = "33849438d52070b23a39042bf8bdc23b5ca3a7c4033ace5b942cd82eb2506c94",
    url = "https://registry.yarnpkg.com/@bazel/cypress/-/cypress-3.2.2.tgz",
)

load("@npm_bazel_cypress//@bazel/cypress:index.bzl", "cypress_repository")

cypress_repository(
    name = "cypress",
)
```

**Comment by alexeagle** [comment]
was fixed by https://github.com/bazelbuild/rules_nodejs/pull/2876
