### ISSUE TITLE
Consolidate logic for collecting js inputs from providers

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#2667]
in https://github.com/bazelbuild/rules_nodejs/commit/5ad15960e69906a2c3e2484be9b17d1a77f83221 we observed that this logic is inconsistent. We should have a starlark helper function to iterate through the providers on the `deps` and collect the exposed JS files that can be input for tools

**Comment by alexeagle** [comment]
Looks like it's too late for this to make 5.0, slipping...

**Comment by gregmagolan** [comment]
No longer in scope for rules_nodejs which only supplies the Node.js toolchain as of [v6.0.0](https://github.com/bazelbuild/rules_nodejs/releases/tag/v6.0.0-beta0).

Downstream canonical JavaScript + Node.js ruleset is now https://github.com/aspect-build/rules_js.
