### ISSUE TITLE
Sharable github pages theme

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_nodejs#2675]
# 🚀 feature request

### Description

It seems `rules_nodejs` has a github theme that's quite consistent with the official Bazel docs. Is this something that can be easily made sharable so other rules can benefit?

**Comment by alexeagle** [comment]
I have an even better idea. Let's just make one docsite that shows all the rules, adding features solves everyone's problem at once.
https://docs.aspect.dev

**Comment by UebelAndre** [comment]
I love it! How do we setup repos to work with it?

**Comment by alexeagle** [comment]
I've got a script that populates the site, what repo would you want to add? Probably need a separate issue tracker for it

**Comment by UebelAndre** [comment]
Really so long as [rules_rust](https://github.com/bazelbuild/rules_rust) is there I'm happy. We're currently discussing how to avoid having generated docs committed in PRs (https://github.com/bazelbuild/rules_rust/pull/695) so I was doing some investigation on how we could do this and setup versioned docs. I only know of this repo which has versioned docs which is what brought me to open this issue. I think it'd be awesome if there was something we could open an issue or PR on to add or update docs.

**Comment by mattem** [comment]
I'm going to call this resolved but the Aspect doc site effort, rnj now uses the Aspect site as its own docsite SoT.

**Comment by UebelAndre** [comment]
The only thing that's not clear from this is what the process is for reporting issues in the new site.

**Comment by UebelAndre** [comment]
I think it'd be awesome if the site was open source and we could contribute things to it. But totally up to Alex. I just don't want to create unnecessary noise or distraction chasing down things related to the site.

**Comment by alexeagle** [comment]
yeah I'll figure out what should be open-source soonish. you can just ping me on slack in the meantime with any requests. That will be my real motivation to fix the process :)
