### ISSUE TITLE
Documentation intro page is out of date with respect to Bazel-managed dependencies

### ISSUE THREAD

**Issue by jfirebaugh** [bazelbuild/rules_nodejs#2686]
https://bazelbuild.github.io/rules_nodejs/ states:

> It is up to the user to install packages into their node_modules directory, though the build tool can verify the contents.
> ...
> In the nodejs rules, Bazel is not the package manager

My understanding is that this was true prior to the introduction of [Bazel-managed dependencies](https://bazelbuild.github.io/rules_nodejs/dependencies.html#bazel-managed-vs-self-managed-dependencies), but with Bazel-managed dependencies, Bazel _does_ manage node packages. To more accurately reflect the current status quo, this section should be updated to mention the (recommended) approach of using Bazel-managed dependencies with the workspace `managed_directories` attribute. Or perhaps the "Design" and "Hermeticity and reproducibility" sections should simply be deleted, since the same material is more accurately covered on the [Dependencies](https://bazelbuild.github.io/rules_nodejs/dependencies.html) page.

**Comment by alexeagle** [comment]
Thanks for filing, that's good timing since we just launched a new docsite. I agree this content was the first thing I wrote four years ago and should just be deleted.

**Comment by alexeagle** [comment]
the reference to https://github.com/bazelbuild/rules_nodejs/issues/1 will be missed 💀
