### ISSUE TITLE
esbuild with relative es6_sources output dependency

### ISSUE THREAD

**Issue by kyubisation** [bazelbuild/rules_nodejs#2691]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: esbuild

### Is this a regression?

 No

### Description

I want to create an esbuild bundle with the esm output (`output_group = "es6_sources"`) from a (ng_)ts_library target and its relative dependency.

## 🔬 Minimal Reproduction

https://github.com/kyubisation/bazel-esbuild-reproduction/blob/main/src/BUILD.bazel

<details>
 <summary>src/main.ts</summary>

```ts
import { enableProdMode } from '@angular/core';
import { platformBrowser } from '@angular/platform-browser';

import { AppModule } from './app/app.module';

enableProdMode();
platformBrowser().bootstrapModule(AppModule);
```
</details>

<details>
 <summary>src/BUILD.bazel</summary>

```
load("@npm//@bazel/esbuild:index.bzl", "esbuild")
load("//tools:angular_ts_library.bzl", "ng_ts_library")

package(default_visibility = ["//:__subpackages__"])

ng_ts_library(
    name = "src",
    srcs = [
        "main.ts",
    ],
    tsconfig = ":tsconfig.json",
    deps = [
        "//src/app",
        "@npm//@angular/core",
        "@npm//@angular/platform-browser",
    ],
)

filegroup(
    name = "esm",
    srcs = ["src"],
    output_group = "es6_sources",
)

# create a single bundle of the JS sources
esbuild(
    name = "bundle",
    entry_point = "main.ts",
    # minify = True,
    # setting node as the platform will default us to CJS
    platform = "node",
    tool = select({
        "@bazel_tools//src/conditions:darwin": "@esbuild_darwin//:bin/esbuild",
        "@bazel_tools//src/conditions:linux_x86_64": "@esbuild_linux//:bin/esbuild",
        "@bazel_tools//src/conditions:windows": "@esbuild_windows//:esbuild.exe",
    }),
    deps = [
        ":esm",
        "//src/app:esm",
        "@npm//@angular/core",
        "@npm//@angular/platform-browser",
    ],
)
```
</details>

<details>
 <summary>src/app/app.module.ts</summary>

```ts
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
  ],
  exports: [AppComponent],
  bootstrap: [AppComponent],
})
export class AppModule {}
```
</details>

<details>
 <summary>src/app/BUILD.bazel</summary>

```
load("//tools:angular_ts_library.bzl", "ng_ts_library")

package(default_visibility = ["//:__subpackages__"])

ng_ts_library(
    name = "app",
    srcs = glob(["*.ts"]),
    angular_assets = ["app.component.html"],
    deps = [
        "@npm//@angular/core",
        "@npm//@angular/platform-browser",
    ],
)

filegroup(
    name = "esm",
    srcs = ["app"],
    output_group = "es6_sources",
)

```
</details>

## 🔥 Exception or Error

<pre><code>
INFO: From Bundling Javascript src/main.ts [esbuild]:
[link_node_modules.js] manifest file: bazel-out/k8-fastbuild/bin/src/_bundle_esbuild.module_mappings.json
[link_node_modules.js] manifest contents: {
  "workspace": "bazel_esbuild",
  "bin": "bazel-out/k8-fastbuild/bin",
  "roots": {
    "": "npm"
  },
  "module_sets": {}
}
[link_node_modules.js] startCwd: /home/lukas/.cache/bazel/_bazel_lukas/8ffd0b2ff872364e8d8e294bb1e858af/sandbox/linux-sandbox/28/execroot/bazel_esbuild
[link_node_modules.js] execroot: /home/lukas/.cache/bazel/_bazel_lukas/8ffd0b2ff872364e8d8e294bb1e858af/sandbox/linux-sandbox/28/execroot/bazel_esbuild
[link_node_modules.js] isExecroot: true
[link_node_modules.js] resolved npm workspace node modules path to /home/lukas/.cache/bazel/_bazel_lukas/8ffd0b2ff872364e8d8e294bb1e858af/sandbox/linux-sandbox/28/execroot/bazel_esbuild/external/npm/node_modules
[link_node_modules.js] creating symlink node_modules -> /home/lukas/.cache/bazel/_bazel_lukas/8ffd0b2ff872364e8d8e294bb1e858af/sandbox/linux-sandbox/28/execroot/bazel_esbuild/external/npm/node_modules
BAZEL_NODE_MODULES_ROOTS=:npm
BAZEL_PATCH_ROOTS=/home/lukas/.cache/bazel/_bazel_lukas/8ffd0b2ff872364e8d8e294bb1e858af/sandbox/linux-sandbox/28/execroot/bazel_esbuild,/home/lukas/.cache/bazel/_bazel_lukas/8ffd0b2ff872364e8d8e294bb1e858af/sandbox/linux-sandbox/28/execroot/bazel_esbuild/node_modules,/home/lukas/.cache/bazel/_bazel_lukas/8ffd0b2ff872364e8d8e294bb1e858af/sandbox/linux-sandbox/28/execroot/bazel_esbuild/external/npm/node_modules
bazel node patches enabled. roots: /home/lukas/.cache/bazel/_bazel_lukas/8ffd0b2ff872364e8d8e294bb1e858af/sandbox/linux-sandbox/28/execroot/bazel_esbuild,/home/lukas/.cache/bazel/_bazel_lukas/8ffd0b2ff872364e8d8e294bb1e858af/sandbox/linux-sandbox/28/execroot/bazel_esbuild/node_modules,/home/lukas/.cache/bazel/_bazel_lukas/8ffd0b2ff872364e8d8e294bb1e858af/sandbox/linux-sandbox/28/execroot/bazel_esbuild/external/npm/node_modules symlinks in these directories will not escape
 > bazel-out/k8-fastbuild/bin/src/main.mjs:3:26: error: Could not resolve "./app/app.module"
    3 │ import { AppModule } from './app/app.module';
      ╵                           ~~~~~~~~~~~~~~~~~~

ERROR: /home/lukas/projects/bazel-esbuild/src/BUILD.bazel:26:8: output 'src/bundle_metadata.json' was not created
ERROR: /home/lukas/projects/bazel-esbuild/src/BUILD.bazel:26:8: output 'src/bundle.js' was not created
ERROR: /home/lukas/projects/bazel-esbuild/src/BUILD.bazel:26:8: output 'src/bundle.js.map' was not created
ERROR: /home/lukas/projects/bazel-esbuild/src/BUILD.bazel:26:8: Bundling Javascript src/main.ts [esbuild] failed: not all outputs were created or valid
Target //src:bundle failed to build

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu-20-04
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.6.0
Build label: 4.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 21 07:33:24 2021 (1611214404)
Build timestamp: 1611214404
Build timestamp as int: 1611214404
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "10f534e1c80f795cffe1f2822becd4897754d18564612510c59b3c73544ae7c6",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/3.5.0/rules_nodejs-3.5.0.tar.gz"],
)

    "@bazel/esbuild": "^3.5.0",
    "@bazel/ibazel": "^0.15.10",
    "@bazel/typescript": "^3.5.0",
  </code>
</pre>

**Anything else relevant?**

It is possible that I'm simply doing something wrong. If so, additional documentation might help on how to use esbuild with separate modules.

**Comment by mattem** [comment]
Most of the rules will pick out the sources needed automatically via the passed providers, including esbuild, so pulling out the es6_sources `filegroup` means it misses providers and all the transitive dependencies provided by them. 

In addition we need to tell esbuild to prefer the `.mjs` files via [`--resolve-extensions`](https://esbuild.github.io/api/#resolve-extensions)

Something like:

```
ng_ts_library(
    name = "src",
    srcs = [
        "main.ts",
    ],
    tsconfig = ":tsconfig.json",
    deps = [
        "//src/app",
        "@npm//@angular/core",
        "@npm//@angular/platform-browser",
    ],
)

# create a single bundle of the JS sources
esbuild(
    name = "bundle",
    entry_point = "main.ts",
    platform = "browser",
    args = [
        "--resolve-extensions=.mjs,.js"
    ],
    tool = select({
        "@bazel_tools//src/conditions:darwin": "@esbuild_darwin//:bin/esbuild",
        "@bazel_tools//src/conditions:linux_x86_64": "@esbuild_linux//:bin/esbuild",
        "@bazel_tools//src/conditions:windows": "@esbuild_windows//:esbuild.exe",
    }),
    deps = [
        ":src",
    ],
)
```

**Comment by kyubisation** [comment]
Thank you very much for the explanation. 👍
