### ISSUE TITLE
Add support for darwin arm64

### ISSUE THREAD

**Issue by utkuturunc** [bazelbuild/rules_nodejs#2699]
# 🚀 feature request

### Relevant Rules

Add support for darwin arm64 for Apple Silicon Macs

### Description

Currently builds are failing because the toolchain does not exist

### Describe the solution you'd like

Native support for arm based macbooks 

### Describe alternatives you've considered

Running bazel builds in rosetta and docker

**Comment by alexeagle** [comment]
What do you get when you run `uname -m` ?
