### ISSUE TITLE
ts_project does not work with ngc if generated tsconfig is used

### ISSUE THREAD

**Issue by matthewjh** [bazelbuild/rules_nodejs#2701]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

When I take the example in

https://github.com/bazelbuild/rules_nodejs/tree/stable/packages/typescript/test/ts_project/ngc

and modify it to use a generated/inline tsconfig, `ngc` errors with

```
Error: Internal Error: absoluteFrom(ngc): path is not absolute
    at Object.absoluteFrom (C:\packages\compiler-cli\src\ngtsc\file_system\src\helpers.ts:27:11)
    at C:\packages\compiler-cli\src\ngtsc\util\src\typescript.ts:111:34
    at Array.map (<anonymous>)
    at Object.getRootDirs (C:\packages\compiler-cli\src\ngtsc\util\src\typescript.ts:111:19)
    at Function.NgCompilerHost.wrap (C:\packages\compiler-cli\src\ngtsc\core\src\host.ts:172:22)
    at new NgtscProgram (C:\packages\compiler-cli\src\ngtsc\program.ts:74:32)
    at Object.createProgram (C:\packages\compiler-cli\src\transformers\program.ts:824:12)
    at Object.performCompilation (C:\packages\compiler-cli\src\perform_compile.ts:320:18)
    at main (C:\packages\compiler-cli\src\main.ts:45:48)
    at C:\packages\compiler-cli\src\main.ts:240:22
```

I'm not sure what is at fault here, `ts_project` or `ngc`. I note the rule works fine with vanilla `tsc` rather than `ngc`. However, using a checked-in versus a generated tsconfig sholud not make a difference as long as the config is the same.

## 🔬 Minimal Reproduction

```
ts_project(
    name = "ngc",
    srcs = [
        "comp.ng.html",
        "component.ts",
    ],
    tsc = "@npm//@angular/compiler-cli/bin:ngc",
    tsconfig = {
        "compilerOptions": {
            "module": "es2015",
            "moduleResolution": "node",
            "composite": False,
            "experimentalDecorators": True
        }
    },
    deps = [
        "@npm//@angular/core",
    ],
)
```

## 🌍  Your Environment

**Operating System:**
Windows 10
**Output of `bazel version`:**

4.0.0

**Rules_nodejs version:**
3.5.0

**Anything else relevant?**
   "@bazel/typescript": "^3.4.0",
    "@angular/compiler": "^11.2.11",
    "@angular/compiler-cli": "^11.2.11",

**Comment by alexeagle** [comment]
Looks like you're on an old version of ngc and didn't apply the patch - see docs https://docs.aspect.dev/bazelbuild/rules_nodejs/3.5.1/packages/typescript/readme#ts_project-tsc

**Comment by matthewjh** [comment]
Thanks @alexeagle -- the patch fixes it.

However, I am using 11.2. The doc says you only need the patch for Angular versions <11 ("To use the ngc program from Angular versions prior to 11...").

**Comment by alexeagle** [comment]
Seems like the fix is in here https://unpkg.com/@angular/compiler-cli@11.0.0/src/ngtsc/util/src/typescript.js

**Comment by matthewjh** [comment]
In

https://unpkg.com/@angular/compiler-cli@11.0.0/src/ngtsc/util/src/typescript.js

The return of `getRootDirs` is 

```ts
return rootDirs.map(function (rootDir) { return file_system_1.absoluteFrom(host.getCanonicalFileName(rootDir)); });
```

The patch (as well as Toxicable's fix) makes it

```ts
return rootDirs.map(function (rootDir) { return file_system_1.getFileSystem().resolve(host.getCurrentDirectory(), rootDir); })
````

The latter works, but the former does not.

Looks like 12 has the fix:

https://unpkg.com/@angular/compiler-cli@12.0.2/src/ngtsc/util/src/typescript.js

**Comment by alexeagle** [comment]
I see, what about each minor release of 11? I'd just like to be precise about what is the min version in the docs fix

**Comment by matthewjh** [comment]
11.2.13 doesn't have it, either. 12.0.0 is the first non-next version with the fix.
