### ISSUE TITLE
nodejs_binary with non-root user fails to start with EACCES: permission denied

### ISSUE THREAD

**Issue by avigadm** [bazelbuild/rules_nodejs#2719]
# 🐞 bug report

### Affected Rule

nodejs_binary

### Is this a regression?
don't think so

### Description

I have the following bazel build file and I'm able to run **nodejs_binary** successfully but when I run **nodejs_image** and then run the image with **non-root** user on my k8s cluster it fails with EACCES: permission denied error

```
js_library(
    name = "lib",
    srcs = [":srcs"],
    deps = [
        "@npm//express",
        "//another-monorepo-package:lib",
    ]
)
nodejs_binary(
    name = "bin",
    data = [":lib"],
    entry_point = ":index.ts"
)
nodejs_image(
    name = "image",
    binary = "bin",
    base = "@mybase"
)
```

## 🔥 Exception or Error

<pre><code>
[link_node_modules.js] An error has been reported: [Error: EACCES: permission denied, symlink '/app/myapp/bin-prod.runfiles/npm/node_modules' -> 'node_modules'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'symlink',
  path: '/app/myapp/bin-prod.runfiles/npm/node_modules',
  dest: 'node_modules'
} Error: EACCES: permission denied, symlink '/app/myapp/bin-prod.runfiles/npm/node_modules' -> 'node_modules'

</code></pre>

## 🌍  Your Environment

**Operating System:**

mac,linux

**Output of `bazel version`:**
<pre>
  <code>
Bazelisk version: development
Build label: 4.1.0
Build time: Fri May 21 11:16:55 2021 (1621595815)
Build timestamp: 1621595815
Build timestamp as int: 1621595815
  </code>
</pre>

**Rules_nodejs version:**
<pre>
  <code>
3.5.1
  </code>
</pre>

**Anything else relevant?**

It works fine if I run it as root user i.e. 
```
securityContext:
  runAsNonRoot: false
  runAsUser: 0
```

**Comment by jaronsummers** [comment]
https://github.com/bazelbuild/rules_docker/issues/1591

Try this.

```
        args = [
            "--nobazel_run_linker",
            "--nobazel_node_patches",
        ],
```

**Comment by Avigad2** [comment]
@jaronsummers it doesn't work. also pretty sure that I need the linker to resolve `//another-monorepo-package:lib`

**Comment by kaikash** [comment]
up :(

**Comment by taozhou-glean** [comment]
got the same error today, any update ?

**Comment by alexeagle** [comment]
Sorry, nodejs_binary has been unmaintained for a year now and we're currently removing it from this repo in the 6.x branch.
