### ISSUE TITLE
Unable to build Skydoc based on TypeScript rules

### ISSUE THREAD

**Issue by sgammon** [bazelbuild/rules_nodejs#2720]
# 🐞 bug report

### Affected Rule

`ts_library`

### Is this a regression?

No, I don't think so

### Description

I have a macro defined in a codebase downstream which loads and uses `ts_library`. Thankfully, there are awesome `:bzl` targets all over `rules_nodejs` which let me depend on the Bazel libs when building my own docs. However, it doesn't seem like there is a matching `:bzl` target for TypeScript tooling, and my consequently fails.

## 🔬 Minimal Reproduction

1) Depend on `rules_nodejs`
2) Write a macro which executes `load()`, say, in `test.bzl`
3) Wrap `test.bzl` in a `stardoc` target and build it

## 🔥 Exception or Error

<pre><code>
com.google.devtools.build.skydoc.SkydocMain$StarlarkEvaluationException: File tools/defs/ts.bzl imported '@npm//@bazel/typescript:index.bzl', yet external/npm/@bazel/typescript/index.bzl was not found, even at roots [., external/elements].
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:475)
	at com.google.devtools.build.skydoc.SkydocMain.eval(SkydocMain.java:325)
	at com.google.devtools.build.skydoc.SkydocMain.main(SkydocMain.java:228)
Caused by: java.nio.file.NoSuchFileException: external/npm/@bazel/typescript/index.bzl
	at com.google.devtools.build.skydoc.SkydocMain.getInputSource(SkydocMain.java:517)
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:448)
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:465)
	... 2 more
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS Big Sur (11.3)
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 4.1.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri May 21 11:16:55 2021 (1621595815)
Build timestamp: 1621595815
Build timestamp as int: 1621595815
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
3.5.1
  </code>
</pre>

**Anything else relevant?**

**Comment by sgammon** [comment]
notably, i _do_ see a matching target for `grpc_web` at `@npm//@bazel/labs/grpc_web:bzl`, so maybe this is easy and it just hasn't been exposed yet?

**`bazel query @npm//@bazel/... | grep bzl`:**
```
Loading: 0 packages loaded
@npm//@bazel/labs/grpc_web:bzl
Loading: 0 packages loaded
Loading: 0 packages loaded
```

**Comment by mattem** [comment]
This is likely missing from all `@bazel/*` packages, as the `BUILD` files are generated by the `pkg_npm` targets. Should copy the same `filegroup` pattern in the main rnj distro.

**Comment by alexeagle** [comment]
Maybe an easy answer here is just for us to expose a dependency on skylib so that all our bzl_library targets are exposed, making rules_nodejs more "normal" like other rulesets.

I do think that comes at an expense of making the novice user experience worse. We could reevaluate that tradeoff.

The other fix would be to have stardoc rules in some or all examples to make sure all our packages are covered.
