### ISSUE TITLE
Cypress is hard coded to `@npm`

### ISSUE THREAD

**Issue by mhevery** [bazelbuild/rules_nodejs#2728]
# 🐞 bug report

### Affected Rule

```
load("@npm//@bazel/cypress:index.bzl", "cypress_repository")
```

See: https://github.com/bazelbuild/rules_nodejs/blob/stable/packages/cypress/index.bzl#L66-L78

Notice that `@npm` is hard coded in the paths. This creates a problem when trying to load cypress from as a sub-project in bazel.

### Is this a regression?

no 

### Description

It seems that `cypress_repository` insists on being in `@npm`. This means that it is not possible to include it as a sub-project.

```
local_repository(
    name = "qwik",
    path = "./repos/qwik",
    repo_mapping = {"@npm" : "@npm_qwik"}
)

yarn_install(
    name = "npm_qwik",
    package_json = "@qwik//:package.json",
    yarn_lock = "@qwik//:yarn.lock",
)

load("@npm_qwik//@bazel/cypress:index.bzl", "cypress_repository")
```

## 🔥 Exception or Error

The above fails with:

```
ERROR: /private/var/tmp/_bazel_misko/276eafca1bf964828f777fc0a89af91f/external/qwik/cypress/BUILD.bazel:32:17: in nodejs_test rule @qwik//cypress:cypress: 
Traceback (most recent call last):
        File "/private/var/tmp/_bazel_misko/276eafca1bf964828f777fc0a89af91f/external/build_bazel_rules_nodejs/internal/node/node.bzl", line 143, column 56, in _nodejs_binary_impl
                node_modules_manifest = write_node_modules_manifest(ctx, link_workspace_root = ctx.attr.link_workspace_root)
        File "/private/var/tmp/_bazel_misko/276eafca1bf964828f777fc0a89af91f/external/build_bazel_rules_nodejs/internal/linker/link_node_modules.bzl", line 89, column 25, in write_node_modules_manifest
                fail("All npm dependencies at the path '%s' must come from a single workspace. Found '%s' and '%s'." % (path, other_workspace, workspace))
Error in fail: All npm dependencies at the path '' must come from a single workspace. Found 'npm_qwik' and 'npm'.
ERROR: Analysis of target '@qwik//cypress:cypress' failed; build aborted: Analysis of target '@qwik//cypress:cypress' failed
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>

  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>

  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
That can't be true because the cypress example doesn't use a workspace named "@npm"
https://github.com/bazelbuild/rules_nodejs/blob/stable/examples/cypress/WORKSPACE
I think you've got both an `@npm` workspace and a `@quik` workspace, and are passing both to cypress.

**Comment by mhevery** [comment]
Let me investigate more.
