### ISSUE TITLE
Coverage not generated with ts_project

### ISSUE THREAD

**Issue by subnova** [bazelbuild/rules_nodejs#2762]
# 🐞 bug report

### Affected Rule

ts_project

### Is this a regression?

Regression between ts_library and ts_project.

### Description

Coverage reports are not generated when (test) code is built using ts_project.

## 🔬 Minimal Reproduction

The issue is demonstrated by the repository https://github.com/subnova/coverage_test (minus the patch that resolves the issue).

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
    System Version:	macOS 10.15.7 (19H1217)
    Kernel Version:	Darwin 19.6.0
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 4.0.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 21 07:38:50 2021 (1611214730)
Build timestamp: 1611214730
Build timestamp as int: 1611214730
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
3.5.1
  </code>
</pre>

**Comment by Toxicable** [comment]
If anyone comes accross this, you may also need to enable:
tsconfig: `inlineSourceMap`, `inlineSources`
.bazelrc: `coverage --instrument_test_targets --experimental_forward_instrumented_files_info_by_default`
