### ISSUE TITLE
Can't build against `lit` with `ts_library`

### ISSUE THREAD

**Issue by sgammon** [bazelbuild/rules_nodejs#2767]
# 🐞 bug report

### Affected Rule

`ts_library`

### Is this a regression?

I don't know if this is new

### Description

When compiling TypeScript code against the latest release of `lit`, an error arises that otherwise does not occur (when using `ts_library` or building via `tsc` directly).

## 🔬 Minimal Reproduction

See minimal repo [here](https://github.com/sgammon/lit-rules-nodejs-repro)
See failing BuildBuddy log [here](https://app.buildbuddy.io/invocation/9303c845-4dfb-43c4-b109-6df1eb996990)

## 🔥 Exception or Error

<pre><code>
ERROR: /Volumes/VANTAGE/rules_nodejs_repro_tslit/BUILD.bazel:33:11: Compiling TypeScript (devmode) //:library failed: (Exit 1): tsc_wrapped.sh failed: error executing command bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.sh @@bazel-out/darwin-fastbuild/bin/library_es5_tsconfig.json
src/index_library.ts:7:8 - error TS7016: Could not find a declaration file for module 'lit/decorators.js'. '/private/var/tmp/_bazel_sam.g/84d0becc136d2ca413fcbae52b83a1ee/execroot/rules_nodejs_repro_tslit/external/npm/node_modules/lit/decorators.js' implicitly has an 'any' type.

7 } from 'lit/decorators.js';
</code></pre>

Offending code:
```javascript
import {
  customElement
} from 'lit/decorators.js';
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS Big Sur 11.3
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 4.1.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri May 21 11:16:55 2021 (1621595815)
Build timestamp: 1621595815
Build timestamp as int: 1621595815
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
3.6.0 (0fa2d443571c9e02fcb7363a74ae591bdcce2dd76af8677a95965edf329d778a)
  </code>
</pre>

**Anything else relevant?**

We recently upgraded to `3.6.0`, but this bug surfaced before that upgrade.

**Comment by sgammon** [comment]
@justinfagnani / @alexeagle / @gregmagolan any idea what might be causing this? since `lit` is callable from Soy internally at Google, I figure this has to work somewhere along the way with `ts_library`?

**Comment by justinfagnani** [comment]
I'm not sure. We do publish decorators.d.ts to npm: https://unpkg.com/browse/lit@2.0.0-rc.2/

**Comment by sgammon** [comment]
i saw that - IIRC, `ts_library` won't process JS sources, which was my first guess, but you're right there are `.d.ts` files under the hood.

**Comment by alexeagle** [comment]
seems surprising to me that you import from `lit/decorators.js` rather than `lit/decorators` but no idea if that's related to the problem.

Maybe building with `--define=VERBOSE_LOGS=1` will produce typescript resolution tracing? (With `ts_project` the `tsc` command is exposed so you just add `--traceResolution` to the `args`...)

We should figure out how to run the lit compilation without `ts_library` since we're working to deprecate that rule. I'll have to brush up on how lit works with TypeScript outside of Bazel so we can do the same.

**Comment by justinfagnani** [comment]
> import from `lit/decorators.js`

This is intended and how we use npm package exports. Using the extension means that import maps are small because we can map the entire package with a prefix mapping rather than each individual file. Hopefully this is not related at all.

**Comment by sgammon** [comment]
@alexeagle at the moment, we're planning to stick with `ts_library` because of the improved build graph resolution. we have a `ts_library` target per element, essentially. afaik we wouldn't be able to do that with `ts_project` as effectively, right?

in any case, i'll try with `--define=VERBOSE_LOGS=1`. worth noting that it works fine with `ts_project` -- the repro has both examples if you'd like to give it a shot. building via `ts_project` works fine, but no such luck via `ts_library`.

**Comment by sgammon** [comment]
@alexeagle any ideas?
