### ISSUE TITLE
Some targets fail to build on RBE

### ISSUE THREAD

**Issue by xingao267** [bazelbuild/rules_nodejs#277]
//examples/rollup:bundle, //examples/rollup:test, //examples/rollup:test_devmode_srcs fail to build on RBE, which I had to skipped in https://github.com/bazelbuild/rules_nodejs/pull/274. We should look into re-enable them.

**Comment by alexeagle** [comment]
all the excluded targets were removed when we switched the example from rollup to parcel in https://github.com/bazelbuild/rules_nodejs/commit/2d3c682aac68c18fc0a3b2451c33bb1f6123b9fa#diff-b87fc4746c05e7b451e025d6d2914276

We don't seem to be running any tests on RBE - we only have build_targets here. But I don't know of anything that doesn't work on RBE so closing this
