### ISSUE TITLE
translate_package_lock rule fails if sha1 is used for integrity in lock file

### ISSUE THREAD

**Issue by devversion** [bazelbuild/rules_nodejs#2771]
There seem to be cases within NPM v7 where the lock file inconsistently mixes SHA1 and SHA256 integrity checksums. This breaks with the `translate_package_lock` rule as Bazel's `ctx.download` does not support SHA1 yet. e.g. consider the following error:

```
ERROR: /home/circleci/.cache/bazel/_bazel_circleci/02fc451c9ce3986cffaddce25971cb5b/external/npm_yargs-14.2.3/BUILD.bazel:5:12: @npm_yargs-14.2.3//:npm_yargs-14.2.3 depends on @npm_path-exists-3.0.0//:npm_path-exists-3.0.0 in repository @npm_path-exists-3.0.0 which failed to fetch. no such package '@npm_path-exists-3.0.0//': Definition of repository npm_path-exists-3.0.0: Unsupported checksum algorithm: 'sha1-zg6+ql94yxiSXqfYENe1mwEP1RU=' (expected SHA-256, SHA-384, or SHA-512) at /home/circleci/rules_nodejs/WORKSPACE:68:26
ERROR: Analysis of target '//internal/npm_tarballs/test:get_all_devdeps' failed; build aborted: Analysis failed
```

and the package lock content for `path-exists@3.0.0`:

```json
    "node_modules/c8/node_modules/yargs/node_modules/path-exists": {
      "version": "3.0.0",
      "resolved": "https://registry.npmjs.org/path-exists/-/path-exists-3.0.0.tgz",
      "integrity": "sha1-zg6+ql94yxiSXqfYENe1mwEP1RU=",
      "dev": true,
      "license": "MIT",
      "engines": {
        "node": ">=4"
      }
    },
```

This error could be reproduced by deleting the lock file for `packages/node-patches` and re-creating it with Node v7.

This might be related to https://github.com/npm/cli/issues/2401, but the lock specification of NPM states that it can be either SHA1, or SHA256... so it seems "valid" that there is some mix of checksum algorithms.

**Comment by alexeagle** [comment]
Bazel 4.1 has my fix for downloading with SHA-1 integrity, try upgrading?

**Comment by devversion** [comment]
@alexeagle ah good point! I was looking at https://github.com/bazelbuild/bazel/issues/7323 and didn't realize SHA1 support landed. Nice work!

**Comment by devversion** [comment]
It might make sense to print a warning if an integrity string starts with `sha1` in the lockfile, and the Bazel version is outdated.
