### ISSUE TITLE
`post_install_patches` can't resolve file path without `symlink_node_modules = False`

### ISSUE THREAD

**Issue by longlho** [bazelbuild/rules_nodejs#2774]
# 🐞 bug report

### Affected Rule

`npm_install`

### Is this a regression?

No

### Description

My patch files has path relative to workspace root according to doc (e.g `node_modules/foo/bar.js`) but without `symlink_node_modules = False` paths don't seem to be able to resolve

## 🔬 Minimal Reproduction

1. Clone https://github.com/formatjs/formatjs
2. Follow https://github.com/formatjs/formatjs#development
3. Remove `symlink_node_modules` in WORKSPACE
4. Run `npm run build`

## 🔥 Exception or Error

<pre><code>
Error in fail: Error applying patch //:npm_package_patches/tslib+2.3.0.patch:
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- a/node_modules/tslib/package.json
|+++ b/node_modules/tslib/package.json
--------------------------
File to patch:
Skip this patch? [y]
Skipping patch.
1 out of 1 hunk ignored
ERROR: no such package '@npm//karma': Error applying patch //:npm_package_patches/tslib+2.3.0.patch:
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- a/node_modules/tslib/package.json
|+++ b/node_modules/tslib/package.json
--------------------------
File to patch:
Skip this patch? [y]
Skipping patch.
1 out of 1 hunk ignored</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Mac OSX
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
3.7.2
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
3.6.0
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
Thanks for the repro, I played with it for a couple minutes but don't have a quick fix.

Based on https://github.com/bazelbuild/rules_nodejs/blob/a611b600b5d2f1242ee615ac4b1c8cd03d0c3b03/internal/npm_install/npm_install.bzl#L321-L323 I bet @gregmagolan can tell us more quickly whether this is a bug or not.

**Comment by gregmagolan** [comment]
Thanks for the report. This is indeed a bug. It is a case I missed when I added the feature. Should be an easy fix so I'll put up a PR soon.

**Comment by gregmagolan** [comment]
I put up a PR to support `post_install_patches` with `symlink_node_modules` enabled https://github.com/bazelbuild/rules_nodejs/pull/2793.

There is the caveat of this mode re-using `node_modules` between runs of the repository rule so patches can and will run on node_modules files that have already been patched and fail. The PR recommends that users use something like https://www.npmjs.com/package/patch-package when running with `symlink_node_modules` enabled as it handles the re-apply patch logic more robustly.

**Comment by gregmagolan** [comment]
I have considered making `symlink_node_modules` work in the opposite direction where the actual files live in the external repository so patches could always run in there which would solve this problem. The symlink would then be in the user's workspace and point to the node_modules in the external workspace instead. This may, however, have the negative side-effect of breaking tooling and editor support outside of bazel which expect the actual path of node_modules to be in the user's clone and not in some external directory.
