### ISSUE TITLE
external docsite is not ideal

### ISSUE THREAD

**Issue by zachgrayio** [bazelbuild/rules_nodejs#2780]
First of all -- big thanks to all authors/maintainers/contributors for all the excellent work here and for picking this up and providing support for it.

That said, I find it odd that a project hosted under `bazelbuild` links to an external/third-party commercial site for docs, especially when it adds no value over the previous setup hosted under github.io. I'm not sure the recent moves in this area across various repositories send a great signal to the community. 

I'm all for adding a `sponsors` section or getting more parties added to the existing [experts](https://bazel.build/experts.html) page etc, but there should probably be a brighter line between community and commercial interests. There's clearly a conflict of interest here; what's to say users aren't going to be forced to pay to access the docs next month? Is there _any_ guidance for what's allowable for projects hosted under the `bazelbuild` github org? 🤔

**Comment by alexeagle** [comment]
That's a good question, why not keep the GH pages setup? It was a monumental effort to get that site setup, especally considering we have no funding for OSS work here. There were two big problems:

1. the rendering is hard. Stardoc output is pretty bad, even the new "html tables in markdown" output is not portable markdown. It also doesn't allow for easy anchors on attributes, making it harder to permalink directly to relevant docs. So we have our own custom velocity templates in https://github.com/bazelbuild/rules_nodejs/tree/stable/tools/stardoc/templates that we have to maintain. Then on top of that GH pages uses ruby gems and Jekyll, which under our Bazel setup was non-hermetic and also lots of code to maintain.

2. it's not versioned. With the 4.0 of rules_nodejs coming soon, we want to continue serving a docsite for the 
3.0 version of the rules, but AFAICT there is no way to have GH pages provide the tag/branch in the URL so you can view a different branch. We did something hacky to keep a 2.x docsite when we launched 3.0 but don't want to keep hacking.

We thought about using something like readthedocs like the python community does, but it was a similar amount of work to port our setup. Ultimately I agree the ideal would be for the Bazel team to host documentation for "recommended" rulesets, but having talked to the tech writing lead my sense is that's not feasible for them to increase scope.
