### ISSUE TITLE
node_modules resolution for requests inside bazel-out should stop at root

### ISSUE THREAD

**Issue by filipesilva** [bazelbuild/rules_nodejs#280]
When resolving modules, `module.constructor._resolveLookupPaths` will look up possible paths for `node_modules` folder.

For the file below
```
C:\\users\\kamik\\_bazel_kamik\\npefw2s4\\execroot\\build_bazel_rules_nodejs\\bazel-out\\x64_windows-fastbuild\\genfiles\\internal\\e2e\\node\\lib_module_resolution_copy.spec.js
```
this is the result of `module.constructor._resolveLookupPaths`
```
[ 'C:\\users\\kamik\\_bazel_kamik\\npefw2s4\\execroot\\build_bazel_rules_nodejs\\bazel-out\\x64_windows-fastbuild\\genfiles\\internal\\e2e\\node\\node_modules',
  'C:\\users\\kamik\\_bazel_kamik\\npefw2s4\\execroot\\build_bazel_rules_nodejs\\bazel-out\\x64_windows-fastbuild\\genfiles\\internal\\e2e\\node_modules',
  'C:\\users\\kamik\\_bazel_kamik\\npefw2s4\\execroot\\build_bazel_rules_nodejs\\bazel-out\\x64_windows-fastbuild\\genfiles\\internal\\node_modules',
  'C:\\users\\kamik\\_bazel_kamik\\npefw2s4\\execroot\\build_bazel_rules_nodejs\\bazel-out\\x64_windows-fastbuild\\genfiles\\node_modules',
  'C:\\users\\kamik\\_bazel_kamik\\npefw2s4\\execroot\\build_bazel_rules_nodejs\\bazel-out\\x64_windows-fastbuild\\node_modules',
  'C:\\users\\kamik\\_bazel_kamik\\npefw2s4\\execroot\\build_bazel_rules_nodejs\\bazel-out\\node_modules',
  'C:\\users\\kamik\\_bazel_kamik\\npefw2s4\\execroot\\build_bazel_rules_nodejs\\node_modules',
  'C:\\users\\kamik\\_bazel_kamik\\npefw2s4\\execroot\\node_modules',
  'C:\\users\\kamik\\_bazel_kamik\\npefw2s4\\node_modules',
  'C:\\users\\kamik\\_bazel_kamik\\node_modules',
  'C:\\users\\kamik\\node_modules',
  'C:\\users\\node_modules',
  'C:\\node_modules',
  'C:\\Users\\kamik\\_bazel_kamik\\npefw2s4\\external\\nodejs\\bin\\nodejs\\lib\\node' ]
```

If the file being resolved is inside bazel-out however, we shouldn't allow resolving `node_modules` above bazel-out` because those folders shouldn't be accessible. 

It's common enough that users have `node_modules` folders on their user folder or in their disk root, usually by accident. Local resolutions can then present results that are not available in other environments.

When resolving lookup paths for files inside bazel-out we should filter the result list to only include paths up to a certain directory:
```
[ 'C:\\users\\kamik\\_bazel_kamik\\npefw2s4\\execroot\\build_bazel_rules_nodejs\\bazel-out\\x64_windows-fastbuild\\genfiles\\internal\\e2e\\node\\node_modules',
  'C:\\users\\kamik\\_bazel_kamik\\npefw2s4\\execroot\\build_bazel_rules_nodejs\\bazel-out\\x64_windows-fastbuild\\genfiles\\internal\\e2e\\node_modules',
  'C:\\users\\kamik\\_bazel_kamik\\npefw2s4\\execroot\\build_bazel_rules_nodejs\\bazel-out\\x64_windows-fastbuild\\genfiles\\internal\\node_modules',
  'C:\\users\\kamik\\_bazel_kamik\\npefw2s4\\execroot\\build_bazel_rules_nodejs\\bazel-out\\x64_windows-fastbuild\\genfiles\\node_modules',
  'C:\\users\\kamik\\_bazel_kamik\\npefw2s4\\execroot\\build_bazel_rules_nodejs\\bazel-out\\x64_windows-fastbuild\\node_modules',
  'C:\\users\\kamik\\_bazel_kamik\\npefw2s4\\execroot\\build_bazel_rules_nodejs\\bazel-out\\node_modules',
  'C:\\Users\\kamik\\_bazel_kamik\\npefw2s4\\external\\nodejs\\bin\\nodejs\\lib\\node' ]
```

(NB: the last entry is for the node executable root and must always be there)

**Comment by rogerhub** [comment]
This sounds like it's WAI (this behavior is [described in docs](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders)) and also not something that can be changed in rules_nodejs.

**Comment by filipesilva** [comment]
It is working as intended for Node resolution, but as far as rules_nodejs goes I feel it should honor the bazel sandbox. Even using sandboxes, this behaviour enables different output based on the bazel folder location.

It can be changed by overriding the [_resolveLookupPaths ](https://github.com/nodejs/node/blob/88105c998ef9d3f54aa8f22b82ec8cc31cbfac95/lib/internal/modules/cjs/loader.js#L547 )function and filtering out the paths outside bazel folders.

We already override `module.constructor._resolveFilename` so it is not a stretch to override this one too.

**Comment by rogerhub** [comment]
Ah, I missed the sandbox bit, and I wasn't aware we were already overriding _resolveFilename. Carry on then.
