### ISSUE TITLE
@bazel/worker 3.0 breaks when upgarde to rules_nodejs 4.x

### ISSUE THREAD

**Issue by mrmeku** [bazelbuild/rules_nodejs#2807]
The worker package should probably not be so constrained. We should remove the check for the major version of rules_nodejs from the package

**Comment by devversion** [comment]
Just to capture this here. A potential workaround is to add `--ignore-scripts` to the yarn install (if Yarn is used). Here is an example for `rules_sass`:

```bzl
# TODO: remove workaround once `rules_sass` supports v4 of the Bazel NodeJS rules,
# or when https://github.com/bazelbuild/rules_nodejs/issues/2807 is solved. For now, we just
# replicate the original `sass_repositories` call and manually add the `--ignore-scripts`
# Yarn argument to not run the postinstall version check of `@bazel/worker`
yarn_install(
    name = "build_bazel_rules_sass_deps",
    package_json = "@io_bazel_rules_sass//sass:package.json",
    yarn_lock = "@io_bazel_rules_sass//sass:yarn.lock",
    symlink_node_modules = False,
    args = ["--ignore-scripts"],
)
```

**Comment by mattem** [comment]
This breaks our own CI 🙃 
https://app.circleci.com/pipelines/github/bazelbuild/rules_nodejs/3549/workflows/fe06ec3d-d508-4ef9-b114-45cd66f97a50/jobs/56462
