### ISSUE TITLE
rules_nodejs CI broken for Bazel@HEAD

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/rules_nodejs#2815]
Example breakage: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2091#571c2dcf-e17f-4647-a6f1-212b93aad11c

Even good commits seem broken.

Looks like mirrors for downloading `kotlinx-html-js-0.6.12-sources.jar` no longer provide this jar?

ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/535e526ea7b76a642b08e7766789b8fe/external/maven/BUILD:26:8: @maven//:org_jetbrains_kotlinx_kotlinx_html_js_jar_sources_0_6_12_extension depends on @org_jetbrains_kotlinx_kotlinx_html_js_jar_sources_0_6_12//file:file in repository @org_jetbrains_kotlinx_kotlinx_html_js_jar_sources_0_6_12 which failed to fetch. no such package '@org_jetbrains_kotlinx_kotlinx_html_js_jar_sources_0_6_12//file': java.io.IOException: Error downloading [http://dl.bintray.com/kotlin/kotlinx.html/org/jetbrains/kotlinx/kotlinx-html-js/0.6.12/kotlinx-html-js-0.6.12-sources.jar, https://maven.google.comorg/jetbrains/kotlinx/kotlinx-html-js/0.6.12/kotlinx-html-js-0.6.12-sources.jar, https://repo1.maven.org/maven2org/jetbrains/kotlinx/kotlinx-html-js/0.6.12/kotlinx-html-js-0.6.12-sources.jar] to /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/535e526ea7b76a642b08e7766789b8fe/external/org_jetbrains_kotlinx_kotlinx_html_js_jar_sources_0_6_12/file/downloaded: GET returned 404 Not Found

**Comment by c-parsons** [comment]
@philwo

**Comment by alexeagle** [comment]
Yeah the bintray CDN is going away and that jar isn't mirrored anywhere else. I think we'll have to delete that example. I asked in the kotlin channel in Bazel slack...

**Comment by alexeagle** [comment]
Fixed by disabling in #2748
