### ISSUE TITLE
Question: how to use a generated .d.ts file in a project

### ISSUE THREAD

**Issue by sayrer** [bazelbuild/rules_nodejs#2818]
Suppose I have:

`import type { Image } from "@myproject/my-types";`

I'm creating a single `.d.ts` file with a genrule, but how do I specify that file as a dependency, and give it that package name? If I try to make it a `ts_project` with this `.d.ts` file in `srcs`, I get an error: `Error in fail: ts_project target "//myproject/types" is configured to produce no outputs.`

**Comment by sayrer** [comment]
The answer is to use a `js_library`.

**Comment by a-ignatov-parc** [comment]
@sayrer I'm curious to ask if you have tried configuring `ts_project` to emit declarations? Without this, only `.js` artifacts will be generated and `.d.ts` files have no js representation.

**Comment by sayrer** [comment]
The input to the `js_library` rule is a `.d.ts` file generated by something other than `ts_project.`

**Comment by jfirebaugh** [comment]
Is there a full example of this somewhere? "Use a `js_library`" was a good hint but I still haven't figured out the whole setup.
