### ISSUE TITLE
pkg_npm mangles binary protobuf file

### ISSUE THREAD

**Issue by freythgs** [bazelbuild/rules_nodejs#2821]
# 🐞 bug report

### Affected Rule

I am using `pkg_npm` with `package_name` to include generated JavaScript proto code and a binary protobuf. I am not applying any substitutions. Unfortunately //internal/pkg_npm:packager.js does not consider my binary proto as proto and while I do not have any substitutions seems to re-encode the file.

 The issue is caused by the rule: 

### Is this a regression?

Before we were using rules_nodejs 1.7 and the implicit WORKSPACE root handling. This problem started to occur after we upgraded.

 Yes, the previous version in which this bug was not present was: 1.7.0

### Description

 A clear and concise description of the problem...

packager.js attempts to determine whether or not to apply substitutions to the given dependency. Unfortunately the isbinaryfile checking seems too be incomplete/wrong for my input file and some UTF-8 (re-)encoding seems to appear.

https://github.com/bazelbuild/rules_nodejs/blob/4ffa628ee5b4b2ff6c452e500a81f4f4b2c94a54/internal/pkg_npm/packager.js#L47

## 🔬 Minimal Reproduction

```
pkg_npm(
  name = "foo",
  package_name = "foo",
  srcs = ["package.json"],
  deps = ["//:binary_proto"]],
)
```

`bazel build //:foo` and then md5sum //:binary_proto and bazel-bind/foo/binary_proto. They unfortunately do not match.

## 🔥 Exception or Error

md5sum of the binary proto is not the same as the source.

<pre><code>

</code></pre>

## 🌍  Your Environment

**Rules_nodejs version:**

<pre>
  <code>
3.7.0
  </code>
</pre>

**Anything else relevant?**

**Comment by freythgs** [comment]
The best I can think of is to introduce binary_deps attribute that are not subject to substitutions and are copied.

**Comment by freythgs** [comment]
@alexeagle any preference on how to solve this?

**Comment by alexeagle** [comment]
Hey, sorry I'm behind on triaging issues.

Can you dig a bit on why the isBinaryFile library fails to detect your file encoding?
https://github.com/bazelbuild/rules_nodejs/tree/4ffa628ee5b4b2ff6c452e500a81f4f4b2c94a54/third_party/github.com/gjtorikian/isBinaryFile is where we have our vendored copy of that library
(perhaps it has been fixed upstream and we just need to rebase our vendored copy to pick up changes)?

**Comment by freythgs** [comment]
I started to add protobuf parsing to isbinaryfile by parsing the first varInt (fieldnumber + type) but surely some of the text files (KO) were valid varint's too. I will expand by trying to parse full messages... Taking a step back I think what pkg_npm attempts is really difficult.

1. I never want pkg_npm to mangle my binary files
2. Some never want to leak internal code ("copybara")

I think by tasting just 500 bytes of a file this is impossible. What about making copybara and other replacements explicit?

**Comment by zecke** [comment]
https://github.com/gjtorikian/isBinaryFile/pull/49 for some protobuf tasting.

**Comment by alexeagle** [comment]
Yes, it's heuristic and so we can never know for sure if a file is binary or not.

I'm not sure how copybara is a requirement here. I think the only way we could make it foolproof is to have a mode for pkg_npm where we assume every file is binary and never touch it?

**Comment by zecke** [comment]
copybara: In the sense that iff isbinaryfiles gets the classification wrong, one will "leak" code between BEGIN-INTERNAL/END-INTERNAL markers (I assumed that is handled by something like copybara).

I probably don't know all the constraints but I think we should make substitutions a high-level rule. Then I can write something like this:

```
pkg_npm(
  srcs = [":filtered_src", ":binaries"],
 ...
)

pkg_filter(
  name = "filtered_src",
   srcs = glob(...),
   subsitutions = [...],
)

filegroup(
  name = "binaries",
  ...
)
```

The shorter alternative is to have different inputs for sources and data. WDUT?

**Comment by zecke** [comment]
The issue persists. I carry a patch that treats files by filename differently.
