### ISSUE TITLE
Running generated NPM binaries from the runfiles node_modules

### ISSUE THREAD

**Issue by jsannemo** [bazelbuild/rules_nodejs#2827]
# 🚀 feature request

### Description

Running generated NPM binaries from the runfiles node_modules rather than execroot.

The auto-generated rules for running NPM package binaries are awesome: it was really easy to get webpack builds working together with some bazel-generated source files, which was my goal.

However, I also fought quite a lot in getting the dev server to work with autorefresh, generated files, etc. In the end I managed to make it work using `nodejs_binary` using a separate wrapper script to start the webpack devserver, but failed to get it working properly with the generated `webpack_cli`.

The root of this was that the `webpack_cli` rule seemed to use the `node_modules` in the execroot rather than the runfiles version. This is basically fine, except that if you run another bazel command -- for example, because you are using `ibazel` to refresh your generated sources -- that `node_modules` symlink disappears. Unfortunately, webpack loads the dev server hot reload client to inject into the packed bundle upon refresh, and since webpack was started from the execroot node_modules, that's where it looks for those files upon refresh.

### Describe the solution you'd like

It would be great if the wrapper would allow, for those cases where you do a `bazel run` rather than just use them as tools in a build rule, the module to be taken from the runfiles (this is what I would expect anyway if I'm trying to deploy an executable build with `bazel run`.

**Comment by andy-zhou** [comment]
Can you share your workaround? This seems exactly the same as #2107.

**Comment by alexeagle** [comment]
This is basically the approach we're taking in a new experimental repo, https://github.com/aspect-build/rules_js
