### ISSUE TITLE
Esbuild should support plugins

### ISSUE THREAD

**Issue by joeljeske** [bazelbuild/rules_nodejs#2832]
# 🚀 ESBuild should support plugins 

### Relevant Rules

esbuild 

### Description

 

Esbuild has concept of plugins for varied experiences. The Bazel rules should support them, both custom plugins and ones from from NPM. 

### Describe the solution you'd like

Perhaps there could be a hook to customize the config passed to Esbuild, or maybe the specifying of a custom config file. 

 

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

none available

**Comment by mattem** [comment]
closed via #2840
Will be in a 4.x release
