### ISSUE TITLE
pkg_npm should accept dependencies in other packages

### ISSUE THREAD

**Issue by duarten** [bazelbuild/rules_nodejs#2833]
# 🚀 feature request

### Relevant Rules

`pkg_npm`

### Description

`pkg_npm` can include files local to the package where its defined as well as files from other workspaces, if allowed by the `vendor_external` attribute. However, dependencies from other packages are filtered out.

### Describe the solution you'd like

Files in other packages should also be copied to the out directory. Possibly, there could be another attribute to whitelist the other packages.

### Describe alternatives you've considered

The current workaround is to copy (e.g., with a genrule) the files from the external packages into this one.

**Comment by alexeagle** [comment]
Hey @duarten 
The https://docs.aspect.dev/bazelbuild/rules_nodejs/3.7.0/docs/builtins.html#pkg_npm-nested_packages feature is meant for this purpose. Each package can declare a `pkg_npm` and then these are nested into the root.

The reason I don't know how to do what you describe is that the files need to be mapped from their workspace location into the resulting archive. It's not clear what that mapping should be if the files come from outside the package. (pkg_tar has similar issue and a different and confusing solution with strip_prefix and directory attributes)

**Comment by duarten** [comment]
Thanks for the explanation, @alexeagle! 

Nested packages aren't ideal for what I'm trying to do, which is get a `data`, binary file that comes from another package into the archive. Maybe `vendor_external` could accept "external" packages as well and apply the same path logic? That said, the workaround I used was to copy the file into the package declaring the `pkg_npm` via a `genrule`. I think that is good enough for such corner cases and doesn't justify adding unclear semantics to the rule.

**Comment by alexeagle** [comment]
https://github.com/aspect-build/bazel-lib/blob/main/docs/copy_to_directory.md is a general solution for reorganizing the output tree into a new folder, which you could then use as an input to publish a package. I think that provides a proper solution for this.
