### ISSUE TITLE
ts_project cannot compile a ts file that imports a generated json file

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#2843]
The TypeScript compiler treats .json files as sources that must be within the rootDir. Unlike resolution of `.d.ts` files for typings, we can't simply pre-process the generated .json files as a separate project.

Repro:

a.ts:
```
import {name} from './gen.json'
```

BUILD:
```
load("@build_bazel_rules_nodejs//third_party/github.com/bazelbuild/bazel-skylib:rules/write_file.bzl", "write_file")
load("//packages/typescript:index.bzl", "ts_project")

write_file(
    name = "gen_json",
    out = "subdir/gen.json",
    content = ["""{ "name": "gen-json" }"""],
)

ts_project(
    name = "compile",
    srcs = ["a.ts", "gen.json"],
    tsconfig = "tsconfig.json",
)
```

tsconfig.json:
```
{
    "compilerOptions": {
        "resolveJsonModule": true,
        "rootDirs": [
            ".",
            "../../../../../bazel-out/darwin-fastbuild/bin/packages/typescript/test/ts_project/json",
            "../../../../../bazel-out/k8-fastbuild/bin/packages/typescript/test/ts_project/json",
        ]
    }
}
```

Error:
```
packages/typescript/test/ts_project/json/a.ts(1,20): error TS6059: 
File '[execroot]/build_bazel_rules_nodejs/bazel-out/darwin-fastbuild/bin/packages/typescript/test/ts_project/json/gen.json'
 is not under 'rootDir' '[execroot]/build_bazel_rules_nodejs/packages/typescript/test/ts_project/json'.
 'rootDir' is expected to contain all source files.
```

However if the json file were represented as typings, then it would work. That is, when performing type-checking we would want a generated `.d.ts` file to show the type-shape of the json file. This would presumably be the output of some other rule that turns json schema into TypeScript typings, like the compiler does internally, but exposed as a separate "project".

With the same a.ts and tsconfig.json as above, this now works:
```
write_file(
    name = "gen_json",
    out = "gen.json",
    content = ["""{ "name": "gen-json" }"""],
)
write_file(
    name = "gen_json_typing",
    out = "gen.json.d.ts",
    content = ["export declare const name = 'gen-json'"],
)
ts_project(
    name = "compile",
    srcs = ["a.ts", "gen.json", "gen.json.d.ts"],
    tsconfig = "tsconfig.json",
)
```

However it's not really feasible for users to have to generate typings for their json manually, they want to do the simple thing that TypeScript normally supports if the .json file were actually located with the sources.

It feels like the JSON import feature added to TypeScript is just missing the pathmapping resolution logic that exists for .d.ts files, and so we ought to be able to file a bug upstream on the TypeScript project.

**Comment by alexeagle** [comment]
https://github.com/microsoft/TypeScript/issues/24744 kinda suggests "json always treated as a module" which is similar. In fact the JSON sources are always written to the output tree, which is why TS needs them to conform to the rootDir/outDir scheme that .ts inputs would. What we really want here is to say "you can use this json file to typecheck against, but there's no need to copy it to the output folder since it's already there".

**Comment by alexeagle** [comment]
https://github.com/microsoft/TypeScript/pull/36066 seems to explicitly break what we wanted here, which is a way to get the typeshape for the json file without having to treat it as an emittable source.

**Comment by loudmouth** [comment]
hey @gregmagolan just thought i'd bump up my last message and see if you had anything shareable for this topic. I've attempted invoking `json-to-dts` via `npm_package_bin` but struggling...

**Comment by loudmouth** [comment]
According to my understanding of the comment left above, I have used used `json-dts-generator` as an `npm_package_bin`. While I was able to successfully "build" a `js_library` that uses the generated type declarations as well as my static data (i.e. JSON file), trying to resolve imports inside a `ts_project` in a separate path in the workspace results in the compiler being unable to find the file. This is despite having `rootDirs` configured properly in `tsconfig.json` and having `link_workspace_root = True` in the `ts_project` rule.

One thing you can see in my `json_dts_generator` rule is that the src has been copied to bin; I was wondering if that may cause files to not be available for the `ts_project` rule

```
load("@npm//json-dts-generator:index.bzl", "json_dts_generator")
load("@build_bazel_rules_nodejs//:index.bzl", "js_library", "copy_to_bin")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "data",
    srcs = [
        "data.json",
    ],
)

copy_to_bin(
    name = "srcs",
    srcs = ["data.json"]
)

json_dts_generator(
    name = "data_declarations",
    outs = [
        "_common.d.ts",
        "data.d.ts",
    ],
    data = [":srcs"],
    args = ["$(RULEDIR) $(RULEDIR)"],
)

js_library(
    name = "currencies_js",
    # Code that depends on this target can import from "@myco/mypkg"
    package_name = "data-lib",
    package_path = "path/to/lib",
    # Consumers might need fields like "main" or "typings"
    srcs = [
        ":data.json", 
        "_common.d.ts",
        "data.d.ts",
    ],
    # The .js and .d.ts outputs from above will be part of the package
    deps = [
        ":data_declarations",
    ],
)
```

**Comment by gregmagolan** [comment]
I put up a minimal example of using the json-to-dts package I forked from json-dts-generator. https://github.com/gregmagolan/json-to-dts-example/blob/main/src/BUILD.bazel. Hope that helps.

**Comment by alexeagle** [comment]
Note, this is fixed in https://github.com/aspect-build/rules_ts
