### ISSUE TITLE
Local PATH not used by npm_package_bin with "local" tag

### ISSUE THREAD

**Issue by jahdiel** [bazelbuild/rules_nodejs#2856]
# 🐞 Local PATH not used by npm_package_bin with "local" tag

### Affected Rule

The issue is caused by the rule: **npm_package_bin**

### Description

When running the `npm_package_bin` rule the script fails because it cannot find the commands from the PATH env variable. I ran the rule with the `--experimental_allow_tags_propagation` flag and added `tags = ["local"]` to avoid the creation of a sandbox. When I do this, it does not create the sandbox env, but the `process.env` still doesn't contain the local PATH env variables (`PATH: /private/var/tmp/_bazel_xxxx/ee64c9fe5b58ac0fc7d/external/build_bazel_rules_nodejs/internal/node/_node_bin`). The package bin I am trying to run uses commands in **/usr/bin**, which are not present in the bazel filesystem.

Interestingly enough, I created a similar script and used the `nodejs_binary` rule and it does have the local PATH in the `process.env` and works fine.

## 🔬 Minimal Reproduction

I am trying to run a react-native script, but was able to narrow the issue to **/usr/bin** not being in the PATH.

<pre>
  <code>
npm_package_bin(
    name = "metro",
    outs = ["main.jsbundle"],
    args = [
        "bundle",
        "--entry-file",
        "./rn_app/index.js",
        "--platform",
        "ios",
        "--dev",
        "true",
        "--bundle-output",
        "$@",
        "--config",
        "./metro.config.js",
        "--verbose",
    ],
    data = glob([
        "*/**",
        "*.json",
        "*.js",
        "*.tsx",
    ]) + [
        "//:package.json", 
        "//:metro.config.js",
        "//:tsconfig.json",
    ] + [
        "@npm//metro-react-native-babel-preset",
        "@npm//:node_modules",
    ],
    package = "react-native",
    package_bin = "react-native",
    tags = ["local"],
)
  </code>
</pre>

## 🔥 Exception or Error

<pre><code>
error: Error: spawnSync find ENOENT
      at Object.spawnSync (internal/child_process.js:1041:20)
      at Object.spawnSync (child_process.js:607:24)

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
ProductName:    Mac OS X
ProductVersion: 10.15.6
BuildVersion:   19G2021
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.10.1
Build label: 4.1.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri May 21 11:16:55 2021 (1621595815)
  </code>
</pre>

**Rules_nodejs version:**

<pre>
  <code>
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "8f5f192ba02319254aaf2cdcca00ec12eaafeb979a80a1e946773c520ae0a2c9",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/3.7.0/rules_nodejs-3.7.0.tar.gz"],
)
  </code>
</pre>

**Comment by alexeagle** [comment]
I think `--action_env` is the flag you need (assuming `--experimental_strict_action_env` is enabled in your `.bazelrc`)

Otherwise Bazel always tries to scrub the environment seen by actions to ensure hermeticity and get more cache hits. It's not related to the spawn strategy (local vs sandbox)
