### ISSUE TITLE
Getting "cannot find build_bazel_rules_nodejs/.../runfiles.bash" in sh_test that doesn't depend on rules_nodejs

### ISSUE THREAD

**Issue by bduffany** [bazelbuild/rules_nodejs#2866]
# 🐞 bug report

### Description

When I add a `jest_test` next to my `sh_test`, it causes the `sh_test` to start failing with

```
ERROR: cannot find build_bazel_rules_nodejs/third_party/github.com/bazelbuild/bazel/tools/bash/runfiles/runfiles.bash
```

## 🔬 Minimal Reproduction

1. Clone https://github.com/bduffany/rules_cssbuild
2. Try running `bazel test //test:test_css_contents` -- it passes
3. Uncomment the `jest_test` rule in that file (and the `load` statement at the top)
4. Run the test again, it fails.
5. Try removing the `data` dep of that `sh_test` to be 100% sure there are no `rules_nodejs` dependencies. The test still fails with the same error

## 🌍  Your Environment

**Operating System:** Ubuntu 20.04

**Output of `bazel version`:**

```
Bazelisk version: v1.7.5
Build label: 4.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri May 21 11:11:34 2021 (1621595494)
Build timestamp: 1621595494
Build timestamp as int: 1621595494
```

**Rules_nodejs version:** 4.0.0-rc.0

**Comment by bduffany** [comment]
Hmm, I think the problem is that `jest_test` is generating a `test.sh` file whose name conflicts with the `test.sh` file in that directory. But I don't know why Bazel doesn't give some sort of error that `test.sh` is defined by 2 rules?

**Comment by alexeagle** [comment]
Yeah collisions of filenames between the bazel-out tree and source tree are a common failure mode in Bazel. I asked in Bazel slack if there's a common way to resolve this (I can't remember how we avoided this problem at Google or if googlers were just trained from hitting it often enough)

It might be a Bazel feature request to warn that an output is shadowing a source file of the same name. I don't think there's much we can do about it in rules_nodejs though. If you have any ideas about a general fix that would be great!
