### ISSUE TITLE
Lazy loading of npm dependencies

### ISSUE THREAD

**Issue by ewianda** [bazelbuild/rules_nodejs#2879]
# 🚀 feature request

### Relevant Rules
* yarn_install
* npm_install

### Description

 
In a relative large monorepo with multiple programming languages, multiple applications and > 200 committers, it is useful to be able to only download dependencies for the target you want to build. This is a similar issue with [rules_python](https://github.com/bazelbuild/rules_python/issues/395) that has been addressed in[ rules_pip](https://github.com/ali5h/rules_pip).

### Describe the solution you'd like
The ability to build a non-javascript target without downloading all dependencies in `package.json`

### Describe alternatives you've considered

 The current solution we have is to have multiple WORKSPACEs for different application within the same repository which defeats the idea of a monorepo

**Comment by alexeagle** [comment]
Fetching js dependencies for a non-js build is a different problem (eager fetch in Workspace) usually because of a load statement from an npm external repo. Where are you seeing that happen?

I assume this issue is more about the case of needing a small number of npm packages, but we fetch and install all of them. We do have a partially thought-through plan for that

**Comment by ewianda** [comment]
> Fetching js dependencies for a non-js build is a different problem (eager fetch in Workspace) usually because of a load statement from an npm external repo. Where are you seeing that happen?

I feel stupid for not reaching out earlier. Turns out I was defining all my helper macros for python and nodejs in one external repository called `devtools`  which clearly reflects your comment.

**Comment by ewianda** [comment]
> I assume this issue is more about the case of needing a small number of npm packages, but we fetch and install all of them. We do have a partially thought-through plan for that

Your assumption is spot on. I will be looking out for when this gets implemented, but for now it is a non-issue when building non-js related targets.
