### ISSUE TITLE
[ts_project] using Angular compiler with composite = True errors because ngc doesn't generate .tsbuildinfo

### ISSUE THREAD

**Issue by matthewjh** [bazelbuild/rules_nodejs#2885]
# 🐞 bug report

### Affected Rule

ts_project

### Is this a regression?

n/a

### Description

In `ts_project`, the `.tsbuildinfo` file is declared as an output so that bazel will delete the file when re-building the rule. However, `ngc` does not generate `.tsbuildinfo` files because it does not support tsc incremental mode:

https://github.com/angular/angular/issues/42011

Passing `ts_build_info_file = None` as an attribute on the `ts_project` rule doesn't work, as the implementation defaults the downstream attribute:

```python
tsbuildinfo_path = ts_build_info_file if ts_build_info_file else name + ".tsbuildinfo"
```

My current workaround is to patch `ts_project.bzl` to comment out:

`buildinfo_out = tsbuildinfo_path if composite or incremental else None,`

and replace with

`buildinfo_out = None`

but this is too blunt an instrument and will cause bazel not to delete `.tsbuildinfo` files when it would be present e.g,. through non `tsc = ngc` rules.

I'm not sure what the best way to fix this would be. Seems we more or less want 

`buildinfo_out = if tsc is ngc then None else regular_buildinfo_out`

But this means encoding the ngc `node_binary` target into `ts_project`, which seems nasty. 

A cleaner alternative is to add a new attribute `force_no_tsbuildinfo_path`. 

If someone who knows more about this codebase and best practices can lend some advice, I am happy to take a stab at implementing a fix.

## 🔬 Minimal Reproduction

https://github.com/matthewjh/rules_nodejs/tree/ngc_tsbuildinfo_error_repo

`bazel build //packages/typescript/test/ts_project/a:tsconfig`

## 🔥 Exception or Error

<pre><code>

INFO: Analyzed target //packages/typescript/test/ts_project/a:tsconfig (1 packages loaded, 5 targets configured).
INFO: Found 1 target...
ERROR: C:/users/matt/documents/github/rules_nodejs_fork/rules_nodejs/packages/typescript/test/ts_project/a/BUILD.bazel:12:11: output 'packages/typescript/test/ts_project/a/tsconfig.tsbuildinfo' was not created
ERROR: C:/users/matt/documents/github/rules_nodejs_fork/rules_nodejs/packages/typescript/test/ts_project/a/BUILD.bazel:12:11: Compiling TypeScript project //packages/typescript/test/ts_project/a:tsconfig [tsc -p packages/typescript/test/ts_project/a/tsconfig.json] failed: not all outputs were created or valid
Target //packages/typescript/test/ts_project/a:tsconfig failed to build
Use --verbose_failures to see the command lines of failed build steps.

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
  Windows 10
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
 Bazelisk version: v1.5.0
Build label: 4.1.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri May 21 11:17:01 2021 (1621595821)
Build timestamp: 1621595821
Build timestamp as int: 1621595821

  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
 stable
  </code>
</pre>

**Comment by matthewjh** [comment]
@alexeagle any preference or thought on how I can handle this cleanly? so I can raise a PR and hopefully get this fix in the next release.

I think ideally the `tsc` value itself would convey whether it generates a tsbuildinfo file or not (`tsc = {binary, generates_tsbuildinfo}`), but I'm not sure whether such as thing is even possible with bazel.

**Comment by alexeagle** [comment]
What's the benefit of setting `composite = True` on an ngc compilation with ts_project? Does removing that fix it?

I'm also curious if you can set tsBuildInfoFile in the `tsconfig` to some sentinel value like empty string, would that suppress typescript creating it? Then ts_project could also ignore empty values.
