### ISSUE TITLE
Cypress can't be bundled into a docker container

### ISSUE THREAD

**Issue by purkhusid** [bazelbuild/rules_nodejs#2893]
# 🐞 bug report

### Affected Rule
`cypress_web_test`

### Is this a regression?
Yes, this is an regression caused by this change: https://github.com/bazelbuild/rules_nodejs/pull/2766

### Description

Before this patch this worked:

```
load("@npm//@bazel/cypress:index.bzl", "cypress_web_test")
load("@io_bazel_rules_docker//nodejs:image.bzl", "nodejs_image")

cypress_web_test(
    name = "e2e_tests",
    srcs = [
        ":support",
        ":tests",
    ],
    config_file = "cypress.json",
    data = [
        "@npm//@babel/core",
        "@npm//@babel/preset-env",
        "@npm//@cypress/webpack-preprocessor",
        "@npm//babel-loader",
        "@npm//cypress-mochawesome-reporter",
        "@npm//mochawesome",
        "@npm//regenerator-runtime",
        "@npm//webpack",
    ],
    plugin_file = "cypress/plugins/index.js",
    tags = [
        "manual",
        "no-cache",
        "requires-network",
    ],
)

nodejs_image(
    name = "image",
    testonly = True,
    base = "@cypress_base//image",
    binary = ":e2e_tests",
    visibility = ["//visibility:public"],
)
```

But after the change you get the following error:

```
(13:30:37) ERROR: /home/danielp/dannidev/monorepo/src/nodejs/e2e_tests/BUILD.bazel:55:8: Writing: bazel-out/k8-fastbuild/bin/src/nodejs/e2e_tests/fle.tar failed: I/O exception during sandboxed execution: /home/danielp/.cache/bazel/_bazel_danielp/b287f68e9314696794df3601f93ec5d5/sandbox/linux-sandbox/78/execroot/monorepo/external/cypress_linux/Cypress (File exists)
```

This also happens if you try to put the Cypress binary into a pkg_tar and seems to be related to this issue:
bazelbuild/rules_pkg#135

Unless someone has another way of putting the Cypress binary into a docker container(We run cypress e2e tests in our deployment pipelines) then the only fix is reverting this or keeping a private patch that reverts this.

## 🔬 Minimal Reproduction

See BUILD file snippet in the description

## 🔥 Exception or Error

<pre><code>
(13:30:37) ERROR: /home/danielp/dannidev/monorepo/src/nodejs/e2e_tests/BUILD.bazel:55:8: Writing: bazel-out/k8-fastbuild/bin/src/nodejs/e2e_tests/fle.tar failed: I/O exception during sandboxed execution: /home/danielp/.cache/bazel/_bazel_danielp/b287f68e9314696794df3601f93ec5d5/sandbox/linux-sandbox/78/execroot/monorepo/external/cypress_linux/Cypress (File exists)

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux (Fedora 33)
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
4.2.0
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
4.0.0
  </code>
</pre>

**Comment by alexeagle** [comment]
Interesting that pkg_tar has the same issue. Any idea at what layer this should be solved? is it some tool we're invoking that should take different arguments?

**Comment by purkhusid** [comment]
I do believe that this just an issue with how finicky directory handling is in Bazel when using sandboxed execution.
I've been trying to find a solution that does not include globs but nothing works so far.

This comment outlines the workaround for pkt_tar: https://github.com/bazelbuild/rules_pkg/issues/135#issuecomment-858734286

I'm not too familiar with the internals of Bazel and how it handles directories so I haven't been able to do a deep dive.

@mrmeku might be able to shine a light on how much the performance improvements are worth compared to the `glob` approach that was used before the patch.
