### ISSUE TITLE
Setting `--define` flags makes nodejs_binary not reproducible

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/rules_nodejs#290]
We are using `--define` flags for some parts in the repository unrelated to node, but when these values change on `bazel build ...` commands then it rebuilds every node binary and everything that depends on it making this behaviour less then ideal for our use case because it reduces the cache hit rate and means we get different  resulting docker containers even when nothing has changed in the js stack

The culprit is this line: https://github.com/bazelbuild/rules_nodejs/blob/master/internal/node/node.bzl#L82 as `define` flags are part of the configuartion variables. So if I have `bazel build --define test=test` the resulting `nodejs_binary` file includes `export test="test"`.

What is the reason this has been put in? Could it just be removed, or at least made configurable, as removing it for us seems to have no effect. Happy to make a PR for whatever is best.

**Comment by alexeagle** [comment]
The reason we added that line was for tests that have golden files, so you can do `bazel run :my_test --define=golden=accept` and it just updates the golden files in your repo.
But I think it's really fishy that we expose all the variables.

That said, my understanding is that all the `--define` variables are inputs to every action anyway, so it's expected that you'll have zero incrementality when you change it. We use `--define` right now within angular to experimentally enable our new compiler and have the same issues.

Did you actually confirm locally that it works?

**Comment by Globegitter** [comment]
Yes, so with different `--define` flags I do see bazel logging `Build options have changed, discarding analysis cache.` but I do not see any rebuilds anymore for our `nodejs_image`. I think the main reason for that is because the sha of the output files are still the same so bazel still reuses the action cache. 

Here the output of our production image before the fix and after, when just adding random `--define` variables:

Before:
```
(10:16:44) INFO: Elapsed time: 40.355s, Critical Path: 32.88s
(10:16:44) INFO: 5 processes: 5 linux-sandbox.
(10:16:44) INFO: Build completed successfully, 10 total actions
```

After:
```
(10:16:56) INFO: Elapsed time: 3.250s, Critical Path: 0.20s
(10:16:56) INFO: 0 processes.
(10:16:56) INFO: Build completed successfully, 1 total action
```

And if then I build it again with exactly the same define variables:
```
(10:20:54) INFO: Elapsed time: 0.390s, Critical Path: 0.01s
(10:20:54) INFO: 0 processes.
(10:20:54) INFO: Build completed successfully, 1 total action
```
This is with the analysis cache from the previous run.

But also the problem is not just the speed but the fact that for us the resulting docker image have different shas even though they should have the same.
