### ISSUE TITLE
examples/create-react-app does not work

### ISSUE THREAD

**Issue by xnerhu** [bazelbuild/rules_nodejs#2908]
# 🐞 bug report

### Affected Rule
react_scripts

### Description

Create-react-app example creates `chdir.js` file in `bazel-out` folder but it can't be found.

## 🔬 Minimal Reproduction
```bash
CD into examples/create-react-app
yarn
yarn start
```

## 🔥 Exception or Error

<pre><code>
iBazel [1:06PM]: Running //:start
Loading: 
Loading: 0 packages loaded
Analyzing: target //:start (0 packages loaded, 0 targets configured)
INFO: Analyzed target //:start (1 packages loaded, 3 targets configured).
INFO: Found 1 target...

INFO: Elapsed time: 0.272s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
INFO: Build completed successfully, 0 total actions
iBazel [1:06PM]: Launching with notifications
Loading: 
Loading: 0 packages loaded
Analyzing: target //:start (0 packages loaded, 0 targets configured)
INFO: Analyzed target //:start (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[0 / 5] [Prepa] BazelWorkspaceStatusAction stable-status.txt
Target //:start up-to-date:
  bazel-bin/start.sh
  bazel-bin/start_loader.js
  bazel-bin/start_require_patch.js
  bazel-bin/start.bat
INFO: Elapsed time: 0.277s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
iBazel [1:06PM]: Starting...

################################################################################
# Did you know iBazel can invoke programs like Gazelle, buildozer, and         #
# other BUILD file generators for you automatically based on bazel output?     #
# Documentation at: https://github.com/bazelbuild/bazel-watcher#output-runner  #
################################################################################

Error: Cannot find module './chdir.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1231:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:468:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:71:3)
    at internal/main/run_main_module.js:7:1

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Windows 11
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.10.1
Build label: 4.2.1
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Aug 30 15:19:20 2021 (1630336760)
Build timestamp: 1630336760
Build timestamp as int: 1630336760
  </code>
</pre>

**Rules_nodejs version:**

<pre>
  <code>
up-to-date stable branch of rules_nodejs
  </code>
</pre>

**Anything else relevant?**
I'm using powershell.

**Comment by alexeagle** [comment]
Interesting, we do have a windows CI for that example which is passing

https://buildkite.com/bazel/rules-nodejs-nodejs/builds/10476#1b443e9a-34a4-4572-b751-76c9109a6054
> //examples:examples_create-react-app PASSED

any idea what's different between you and that CI run indicating this should work?

**Comment by xnerhu** [comment]
I've really no idea. When I change chdir path in `react_scripts - start` to `--node_options=--require=../chdir.js` it compiles but, it throws 
```bash
Failed to compile.

multi C:/users/xnerh/projects/open-source/rules_nodejs/examples/create-react-app/node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js C:/users/xnerh/projects/open-source/rules_nodejs/examples/create-react-app/node_modules/react-dev-utils/webpackHotDevClient.js ./src/index.tsx
Cannot find file: 'ReactRefreshEntry.js' does not match the corresponding name on disk: 'C:\users\xnerh\projects\open-source\rules_nodejs\examples\create-react-app\node_modules\@pmmmwh\react-refresh-webpack-plugin\client\Projects'.
```

I also tried to use just webpack as an alternative, but #2107 is a blocker to me.

**Comment by xnerhu** [comment]
I believe chdir is not found, because `$(rootpath chdir.js)` isn't resolved correctly.  Running `bazel run //:start --enable_runfiles` does work (not counting react refresh issue). Running ibazel with --enable_runfiles doesn't work and I belive it's because it's not supported.

**Comment by alexeagle** [comment]
I think ibazel allowlists flags that are passed through to bazel, so adding `--enable_runfiles` there is the trivial fix
