### ISSUE TITLE
Bazel startup freezes for several minutes on rules_nodejs template project

### ISSUE THREAD

**Issue by dhirving** [bazelbuild/rules_nodejs#2909]
### Affected Rule

Seems like something is wrong during skyframe analysis with node_modules or yarn in rules_nodejs 4.0.0 with Bazel 4.1.0.

### Is this a regression?

 
This is my first attempt at using Bazel, but I am still able to reproduce the issue after downgrading to rules_nodejs 3.8.0

### Description

While running a build where any BUILD.bazel file has a dependency of the form "@npm//some-package-name", bazel sometimes freezes for 2-3 minutes during startup, before invoking any builds.  While this is occurring, the entire MacOS is locked up with the "spinning beach ball" and the computer becomes unusable.

The freeze occurs after printing the invocation ID:
```
INFO: Invocation ID: 92148a4a-9737-4778-849a-f7fa48ce0654
```

java.log shows that it is scanning the skyframe graph during this time:
```
210902 16:18:11.457:I 20 [com.google.devtools.build.lib.skyframe.DiffAwarenessManager.getDiff] About to compute diff between SequentialView[owner=null, position=-2, modifiedAbsolutePaths=[]] and SequentialView[owner=null, position=-2, modifiedAbsolutePaths=[]] for /Users/dave/repos/clean_bazel2
210902 16:18:11.458:I 20 [com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.handleDiffsWithMissingDiffInformation] About to scan skyframe graph checking for filesystem nodes of types [EXTERNAL, OUTPUT, EXTERNAL_REPO, EXTERNAL_IN_MANAGED_DIRECTORY]
210902 16:19:20.324:I 20 [com.google.devtools.build.lib.skyframe.FilesystemValueChecker.lambda$getDirtyValues$2] Spent 68863477203 nanoseconds checking 5340 filesystem nodes (14779 scanned)
210902 16:19:20.325:I 20 [com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.logDiffInfo] DiffAwareness found 0 modified source files and directory listings for /Users/dave/repos/clean_bazel2
```
(this one minute time is from the minimal reproduction below, but increases with more dependencies in package.json.)

## 🔬 Minimal Reproduction
I was able to reproduce the issue with an unmodified version of the repository created by `yarn create @bazel`.

With bazelisk-darwin-amd64 v1.10.1 installed as /usr/local/bin/bazel on MacOS Big Sur 11.4:
```
yarn create @bazel clean_bazel --typescript
cd clean_bazel
# this works OK the first time, starting up quickly and creating yarn.lock
bazel run @nodejs//:yarn
# on the second or third invocation, this freezes up for 1 to 2 minutes in the same way as it does
# when running bazel build //... on my more complicated project
bazel run @nodejs//:yarn
bazel run @nodejs//:yarn
# some subsequent runs complete in a few hundred milliseconds,
# others take 1-2 minutes
bazel run @nodejs//:yarn
```

## Logs
[java.log](https://github.com/bazelbuild/rules_nodejs/files/7100498/java.log)
[java-with-verbose-logs-1-enabled.log](https://github.com/bazelbuild/rules_nodejs/files/7100546/java-with-verbose-logs-1-enabled.log)

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
MacOS Big Sur 11.4 (Intel, Macbook Pro 2019)
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.10.1
Build label: 4.1.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri May 21 11:16:55 2021 (1621595815)
Build timestamp: 1621595815
Build timestamp as int: 1621595815
  </code>
</pre>

**Rules_nodejs version:**

<pre>
  <code>
     http_archive(
        name = "build_bazel_rules_nodejs",
        sha256 = "8a7c981217239085f78acc9898a1f7ba99af887c1996ceb3b4504655383a2c3c",
        urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/4.0.0/rules_nodejs-4.0.0.tar.gz"],
    )

"@bazel/bazelisk@latest":
  version "1.10.1"
  resolved "https://registry.yarnpkg.com/@bazel/bazelisk/-/bazelisk-1.10.1.tgz#46236a43ad58e310c55247f866da0dc6083c3d8b"
  integrity sha512-IHszNzBO2UrUy6YtsSAsZtnU6I6qpzXGkWdEvGoMxLgJnDsEnsIYniDCUjvjU1KAP+A03eepmCHlyFcRHMSxRA==

"@bazel/buildifier@latest":
  version "4.0.1"
  resolved "https://registry.yarnpkg.com/@bazel/buildifier/-/buildifier-4.0.1.tgz#52cfbad5cbb86e9183a29dde2370cd465730ea0d"
  integrity sha512-BTmtvJbeeEVrqRApI1gr5hvPgYcHLpdGJ5EXNXEWO692ztMPSj5fB/dH0xUlaW45jn6LimYx8ymqTMhj3538og==

"@bazel/ibazel@latest":
  version "0.15.10"
  resolved "https://registry.yarnpkg.com/@bazel/ibazel/-/ibazel-0.15.10.tgz#cf0cff1aec6d8e7bb23e1fc618d09fbd39b7a13f"
  integrity sha512-0v+OwCQ6fsGFa50r6MXWbUkSGuWOoZ22K4pMSdtWiL5LKFIE4kfmMmtQS+M7/ICNwk2EIYob+NRreyi/DGUz5A==

"@bazel/typescript@latest":
  version "4.0.0"
  resolved "https://registry.yarnpkg.com/@bazel/typescript/-/typescript-4.0.0.tgz#71a6f0f5e340c6b8516b21fbc0f0853e74055d0c"
  integrity sha512-+Le9q+5IR9gEnSH8sXyxDB5dD6NJx2kbm6AL+cijYVat2MczpGV4sI1mu0mdLzYsEX5Tjt5iHkaNb7sFESjnYA==
  dependencies:
    protobufjs "6.8.8"
    semver "5.6.0"
    source-map-support "0.5.9"
    tsutils "2.27.2"
  </code>
</pre>

**Comment by dhirving** [comment]
Looks like this was a MacOS issue, not a Bazel issue.  Updating from MacOS 11.4 to to 11.5.2 appears to have resolved it.  Sorry for the spam.

**Comment by dhirving** [comment]
I spoke too soon -- the probability of this occurring went down significantly after the MacOS update, but it's still happening.  Any hints on how I could get a better idea what Bazel is actually doing when this problem occurs?

**Comment by alexeagle** [comment]
could you check if it still happens without the `managed_directories` feature (and symlink_node_modules=False)? the presence of `EXTERNAL_IN_MANAGED_DIRECTORY` in the error message makes me wonder if that feature in Bazel is interacting poorly with the filesystem

**Comment by dhirving** [comment]
I gave that a try, but the lockup still occurs the second or third time I run `bazel run @nodejs//:yarn`.

I commented out the managed_directories line in the workspace declaration and added symlink_node_modules = False to yarn_install, so my WORKSPACE file now looks like this:
```
# Bazel workspace created by @bazel/create 4.0.0

# Declares that this directory is the root of a Bazel workspace.
# See https://docs.bazel.build/versions/main/build-ref.html#workspace
workspace(
    # How this workspace would be referenced with absolute labels from another workspace
    name = "clean_bazel2",
    # Map the @npm bazel workspace to the node_modules directory.
    # This lets Bazel use the same node_modules as other local tooling.
    #managed_directories = {"@npm": ["node_modules"]},
)

load("//tools:bazel_deps.bzl", "fetch_dependencies")

fetch_dependencies()

# The yarn_install rule runs yarn anytime the package.json or yarn.lock file changes.
# It also extracts and installs any Bazel rules distributed in an npm package.
load("@build_bazel_rules_nodejs//:index.bzl", "yarn_install")
yarn_install(
    # Name this npm so that Bazel Label references look like @npm//package
    name = "npm",
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
    symlink_node_modules = False
```

Separately from this, I discovered that adding `startup --batch` to my .bazelrc reduces the chance of the lockup occurring from approximately 50% of bazel invocations to <10%.

**Comment by dhirving** [comment]
Figured out what was going on here.

VSCode's file indexing was interacting with Bazel in a weird way.  Added bazel-out/ and dist/ to VSCode's exclude settings and everything is right with the world.

.vscode/settings.json:
```
{
  "files.watcherExclude": {
    "bazel-out/**": true,
    "dist/**": true
  },
  "search.exclude": {
    "bazel-out/**": true,
    "dist/**": true
  }
}
```

Thanks for your response, and sorry for wasting your time on something that isn't a Bazel issue.
