### ISSUE TITLE
nodejs_binary fails to resolve workspace absolute imports / require like my_wksp/path/to/file

### ISSUE THREAD

**Issue by smnrd** [bazelbuild/rules_nodejs#2910]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: `nodejs_binary`

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 3.8.0

### Description

nodejs_binary fails to resolve workspace absolute imports / require like my_wksp/path/to/file (as described in [nodejs_binary docs](https://github.com/bazelbuild/rules_nodejs/blob/4.0.0/docs/Built-ins.md#link_workspace_root) )

## 🔬 Minimal Reproduction

`https://github.com/smnrd/repro-nodejs-binary-absolute-import-failure.git`

## 🔥 Exception or Error

<pre><code>
Error: Cannot find module 'mywksp/mod'
Require stack:
- /home/simon/.cache/bazel/_bazel_simon/389881ea9aac3e360f57a8c0a45336a7/execroot/mywksp/bazel-out/k8-fastbuild/bin/main/main.sh.runfiles/mywksp/main/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (home/simon/.cache/bazel/_bazel_simon/389881ea9aac3e360f57a8c0a45336a7/execroot/mywksp/bazel-out/k8-fastbuild/bin/main/index.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Debian Linux on WSL2
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.9.0
Build label: 4.2.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Aug 30 15:17:47 2021 (1630336667)
Build timestamp: 1630336667
Build timestamp as int: 1630336667
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
4.0.0
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
Interesting I just noticed the same error updating rules_nodejs to bazel 4.2.0 on windows
https://buildkite.com/bazel/rules-nodejs-nodejs/builds/10480#960b3490-5840-4961-b9a4-3de9a8fa633c
but no error on ubuntu. Not sure if it's related.

**Comment by Zemnmez** [comment]
I think this is the same issue as https://github.com/bazelbuild/rules_nodejs/issues/2970

**Comment by smnrd** [comment]
I found a fix that works for us. I just submitted it a PR.
In case someone need it before the PR is merged, [here is the patch](https://github.com/bazelbuild/rules_nodejs/files/7548043/fix-linker-workspace-absolute-imports.patch.txt) (for release 4.4.5, to be used in the `WORKSPACE` file with `build_bazel_rules_nodejs` `http_archive` as [explained here](https://github.com/bazelbuild/rules_nodejs/blob/stable/docs/changing-rules.md#patching-the-built-in-release)).

**Comment by smnrd** [comment]
Fixed by #3093 .
