### ISSUE TITLE
Feature request: make .bin entires worker capable

### ISSUE THREAD

**Issue by thesayyn** [bazelbuild/rules_nodejs#2925]
# 🚀 feature request

### Relevant Rules

npm_package_bin

### Description

Currently, `.bin` entries of the npm packages can not be worker capable. Hence one can not have a bin that is worker capable, without writing a wrapper package to talk worker protocol which might not be feasible in all cases.

the solution, though it is a draft and I might be missing some edge cases, is adding a `supports_worker` attribute to npm_package_bin. this will only be possible when `bazelBin` in the package.json file has an indicator that the bin is worker capable. in the future, we could extend this for `multiplex` and `cancellation` features.

when this is done, we will change npm_install build generation script to add execution requirements to npm_package_bin through generated macros for bin entries.

https://github.com/bazelbuild/rules_nodejs/blob/055d6ae9d7d2761e68944744e5375f5589ee1c1c/internal/npm_install/generate_build_file.ts#L1294-L1297

I see that this could be useful for package authors who want to support workers.

### Describe alternatives you've considered

None

**Comment by alexeagle** [comment]
npm_package_bin was intended for npm programs that aren't bazel-aware, to conveniently run "any" program.

The program you're running has to know about the worker protocol. Once you're down the path of a custom JS entry point, I don't think you gain much from having an auto-generated rule for that package.

Can discuss more though.

**Comment by alexeagle** [comment]
Seems like YAGNI but if we ever do come across an npm package that can act as a worker, but has no other reason to require a custom rule, then this is certainly possible.
