### ISSUE TITLE
ts_projects depending on each other fail on windows

### ISSUE THREAD

**Issue by xnerhu** [bazelbuild/rules_nodejs#2939]
# 🐞 bug report

### Affected Rule

`load("@npm//@bazel/typescript:index.bzl", "ts_project")`

### Description

A rule for compiling only test files generates all source files, even tho I selected with wildcard files with `.test.ts` extension and then it fails, because it cannot override previously built files that were actual source code. 

It fails with `bazel build //:compile_tests` but also when executing these two separately (after removing `:compile` dep from `compile_tests`.

I think the reason is that ts_project doesn't respect 

## 🔬 Minimal Reproduction

```bazel
load("@npm//@bazel/typescript:index.bzl", "ts_config", "ts_project")

ts_config(
    name = "tsconfig",
    src = "tsconfig.json",
)

ts_project(
    name = "compile",
    srcs = glob(
        ["src/**/*.ts"],
        exclude = ["src/**/*.test.ts"],
    )],
    source_map = True,
    tsconfig = ":tsconfig",
)

ts_project(
    name = "compile_tests",
    srcs = glob(["src/**/*.test.ts"]),
    source_map = True,
    tsconfig = ":tsconfig",
    deps = [
        ":compile",
    ],
)

```

tsconfig.json
```json
{
  "compilerOptions": {
    "rootDir": ".",
    "outDir": "../../bazel-out/x64_windows-fastbuild/bin/backend/common"
  }
}
```

## Logs
```bash
INFO: Invocation ID: df23c672-0089-4cc5-8a13-3a374fc464d9
INFO: Analyzed target //backend/common:compile_tests (128 packages loaded, 3169 targets configured).  
INFO: Found 1 target...
ERROR: C:/users/xnerh/projects/blazity/gladiator-ci-cd-test/backend/common/BUILD.bazel:64:11: Compiling TypeScript project //backend/common:compile_tests [tsc -p backend/common/tsconfig.json] failed: (Exit 2): tsc.bat failed: error executing command 
  cd C:/users/xnerh/_bazel_xnerh/r43nvpru/execroot/init
  SET BAZEL_NODE_MODULES_ROOTS=
    SET COMPILATION_MODE=fastbuild
  bazel-out/host/bin/external/npm/typescript/bin/tsc.bat --project backend/common/tsconfig.json --outDir bazel-out/x64_windows-fastbuild/bin/backend/common --rootDir backend/common --bazel_node_modules_manifest=bazel-out/x64_windows-fastbuild/bin/backend/common/_compile_tests_TsProject.module_mappings.json
Execution platform: @local_config_platform//:hos
error TS5033: Could not write file 'C:/users/xnerh/_bazel_xnerh/r43nvpru/execroot/init/bazel-out/x64_windows-fastbuild/bin/backend/common/src/index.js.map': EPERM: operation not permitted, open 'C:/users/xnerh/_bazel_xnerh/r43nvpru/execroot/init/bazel-out/x64_windows-fastbuild/bin/backend/common/src/index.js.map'.

...
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Windows 11
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.10.1
Build label: 4.1.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri May 21 11:17:01 2021 (1621595821)
Build timestamp: 1621595821
Build timestamp as int: 1621595821
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
4.1.0
  </code>
</pre>

**Anything else relevant?**
I'm using Powershell. I have OS dev mode with symlinks enabled as well as --enable_runfiles.

**Comment by alexeagle** [comment]
This is a known limitation when running outside the sandbox
https://docs.aspect.dev/bazelbuild/rules_nodejs/4.0.0/packages/typescript/docs.html#issues-when-running-non-sandboxed
even though Bazel is running the typescript compiler with the constrained set of sources, `tsc` then walks around the disk and adds more files to the program which should not be there.

I think we should add more instructions in that doc for what you can do to workaround it. In this case you need to pass some `includes` or `excludes` to the typescript compiler to prevent it putting files into one of those programs that doesn't belong. Try adding `args=["--listFiles"]` to debug.

**Comment by xnerhu** [comment]
`includes: *.test.ts` in tsconfig, also transpiles imported ts files.

**Comment by xnerhu** [comment]
I think I may be able to make a workaround but I wonder how can I extend tsconfig in a different directory that has `includes src/**/*.test.ts` property. The problem is that it selects files that are in the `tools/ts` dir and not `packages/a`
```
packages
     a
       src
          tests
            index.test.ts
       ts_config
       extends ../../tools/ts/ts_config.json"
 tools
     ts
        ts_config
        { includes: "src/**/*.test.ts" }

**Comment by matthewjh** [comment]
@xnerhu you could try with a generated tsconfig file (put `tsconfig = {}` in your rule attributes). The generated tsconfig file enumerates all the `srcs` in the `files` property

**Comment by xnerhu** [comment]
@matthewjh Thank you! It will definitely help my with experimenting with Bazel. Unfortunately I get `Projects must list all files or use an 'include' pattern. `

**Comment by matthewjh** [comment]
@xnerhu I think you may be getting 

"Projects must list all files or use an 'include' pattern."

because you have imports from your test code (compile_tests) into your main code (compile). Try adding a project reference in compile_test's tsconfig to compile's tsconfig:

https://github.com/bazelbuild/rules_nodejs/blob/stable/packages/typescript/test/ts_project/c/tsconfig.json#L3-L5

You'll also need `composite = True` on both for this to work.

**Comment by xnerhu** [comment]
`tsconfig = {}` outputs .js files directly in src folder in common package. I have composite true on it and reference on the consumer.
