### ISSUE TITLE
Yarn target that does not run against all the package.json directories?

### ISSUE THREAD

**Issue by jfaust** [bazelbuild/rules_nodejs#294]
Maybe this is something we can already do, but I haven't found it in looking through the docs or code. Right now, `@nodejs//:yarn` is a script that runs yarn across all the `package.json` directories. There are times when it'd be nice to be able to run the right version of `yarn` in a given CWD -- the main use-case I have right now being `yarn add` or `yarn remove`. Currently it's not really possible to only use the version of `yarn` managed by `bazel` for this reason.

**Comment by Globegitter** [comment]
@jfaust We ran into this also and I already have an idea on how to fix this / make this at least possible, but have not had the time yet to work on it - hopefully soon though.

**Comment by alexeagle** [comment]
I think you can just run the (undocumented) label
`bazel run @nodejs//:bin/yarn`
to skip the wrapper script that runs against all the directories

**Comment by jfaust** [comment]
@alexeagle ahh, that's perfect.

**Comment by Globegitter** [comment]
Yep so that use-case does indeed work, I was thinking about the case where you want to run yarn only against one of the directories listed, which is currently not possible as far as I am aware. So that is the case we have run into sometimes, where we just want to `yarn add` packages to one of our `package.json` files.

**Comment by jfaust** [comment]
@Globegitter yarn has a `--cwd` option which allows this to work, unless I'm misunderstanding.

```
bazel run @nodejs//:bin/yarn -- --cwd $PWD add <package>
```

There's another solution to this that we use for other scripts that's a bit gnarlier, but which works... a modified `bazel-run.sh` script that uses `--run-under` and runs things as:
```
bazel run --script_path="$runcmd" --run_under="cd $PWD && " "$@"
```

**Comment by gregmagolan** [comment]
Added this to the rules_nodejs README.md. The `--cwd $PWD` is not strictly necessary since yarn will run in the current working directory.

**Comment by jfaust** [comment]
Is that true when running through `bazel run`? I thought it always set the cwd into the runfiles dir.

**Comment by gregmagolan** [comment]
@jfaust That's a good question. It think it works in this case since `@nodejs//:bin/yarn` is just an executable bash script and not a rule with runfiles. On windows the target is actually the `@nodejs//:bin/yarn.cmd` file (come to think of it I need to update the README with that).

**Comment by Globegitter** [comment]
yep so what @gregmagolan documented does indeed work but it still creates a `node_modules` directory in the cwd it is being run (so directly in the workspace). What I would like ideally is that yarn would run in the external repository and then when I run the binary that is depending on those node_modules it would not have to install/download all modules from scratch again. But I suppose that would ideally have `repository_cache` support so we can execute the `yarn install` command in a directory with an existing `cache/node_modules` directory. Maybe a workaround in the meantime could be to make it possible to put the `yarn cache` into a persisted place, but I guess that has its own challenges as we would want a unique persisted place.
