### ISSUE TITLE
Turn on --nolegacy_external_runfiles

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#295]
Under this option, builds fail because we rely on the legacy paths under the runfiles.
Reported in https://github.com/alexeagle/angular-bazel-example/issues/183

**Comment by gregmagolan** [comment]
Flag is turned on in this repo and in rules_typescript. One exceptional case related to an ngc test in angular/angular still in progress here: https://github.com/bazelbuild/rules_typescript/pull/315

**Comment by gregmagolan** [comment]
May want to land the TODOs from here still as a reminder to update the code-base once `--nolegacy_external_runfiles` is the default in Bazel: https://github.com/bazelbuild/rules_nodejs/pull/354
