### ISSUE TITLE
Which docs are canonical?

### ISSUE THREAD

**Issue by jfirebaugh** [bazelbuild/rules_nodejs#2964]
As a new user of rules_nodejs, I have found the current documentation situation confusing.

* Search engine results tend to land me on https://bazelbuild.github.io/rules_nodejs/, which lacks navigation to other sections of the documentation.
* The [repository page](https://github.com/bazelbuild/rules_nodejs) does not list a home page for rules_nodejs.
* The README links to https://docs.aspect.dev/rules_nodejs/, but this redirects to documentation for version 4.1.0, which is not the latest version.
* The README also links to https://bazelbuild.github.io/rules_nodejs/install.html, which seems to duplicate https://docs.aspect.dev/bazelbuild/rules_nodejs/4.1.0/docs/install.html.

Some suggestions that would have made this less confusing for me:

* Decide on either https://bazelbuild.github.io/ or https://docs.aspect.dev/ as the canonical home of documentation. Redirect the other to the canonical location.
* Ensure that the canonical location reflects the latest released version.
* Ensure that the canonical location has UI for navigating between sections of the documentation.
* Set the the canonical location as the repository homepage in GitHub.

**Comment by alexeagle** [comment]
Thanks for pointing this out and also providing helpful suggestions! I have spent a bunch of time in this area so I appreciate the prompting.

I did some cleanup work:
- This repo is under Google's governance and ought to be self-contained. The Bazel team at Google asked that we stop linking to a third-party site for docs. https://github.com/bazelbuild/rules_nodejs/commit/bb2068ad67e71b57c3536a54b41b98708b6f501c was merged to our 3.x branch but didn't get cherry-picked to the 4.0 release. I just fixed that. Also added the docs link as the GitHub homepage and added the missing nav links to https://bazelbuild.github.io/rules_nodejs/ so it now actually functions as a standalone site.
- The docsite at docs.aspect.dev has so many more features than what we could do here (or other bazel ruleset maintainers could do aside from maybe rules_haskell) so I **100% recommend using it in place of the docs for all rulesets** - we just aren't allowed to call that the "canonical" documentation per above as much as I think that's better for our users.
- We don't have the ability to version the docs here, so you just see the HEAD of the `stable` branch documented. Versioning is one of the features of the docs.aspect.dev site.
- https://docs.aspect.dev/rules_nodejs has caught up to mirror the 4.2.0 version now

please keep the suggestions coming 😎

**Comment by jfirebaugh** [comment]
Awesome, thank you!

**Comment by matthewjh** [comment]
@alexeagle is it worth linking to the aspect.dev docs somewhere, making clear they are "unofficial"? I agree they are better, so it'd be a shame for people not to get the benefit.
