### ISSUE TITLE
Error using ts_project with cross-target srcs: label '//a:a.js' is not in the current package

### ISSUE THREAD

**Issue by jfirebaugh** [bazelbuild/rules_nodejs#2967]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: `ts_project`

### Is this a regression?

 Unknown

### Description

I am working in a monorepo with multiple TypeScript projects in subdirectories. One such TypeScript project (call it "b") depends on a file from another project (call it "a"), which is imported with a relative path, i.e. `import "../a/a"`. I cannot figure out how to build such a project using rules_nodejs. See the reproduction below for what I've tried.

## 🔬 Minimal Reproduction

Minimal reproduction: https://github.com/jfirebaugh/bazel_test. Run the command `bazel build //b:b`.

## 🔥 Exception or Error

```
ERROR: /Users/john/figma/bazel_repro/bazel_test/b/BUILD.bazel:3:11: //b:b: label '//a:a.js' is not in the current package
ERROR: error loading package 'b': Package 'b' contains errors
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS 11.4
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 4.2.1-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jan 1 00:00:00 1980 (315532800)
Build timestamp: 315532800
Build timestamp as int: 315532800
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
4.2.0
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
separate `ts_project` rules are compiled separately, so you should use `deps` on the b target to reference the outputs of `a`.

Take a look at the a, b, and c directories in https://github.com/bazelbuild/rules_nodejs/tree/stable/packages/typescript/test/ts_project

**Comment by jfirebaugh** [comment]
Thank you, that was helpful!
