### ISSUE TITLE
How do you use jest_test with link_workspace_root?

### ISSUE THREAD

**Issue by Zemnmez** [bazelbuild/rules_nodejs#2970]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule:  jest_test

### Is this a regression?

Not that I know of. https://github.com/bazelbuild/rules_nodejs/issues/2188 seems to be related.

### Description

 A clear and concise description of the problem...

I am trying to use `link_workspace_root` with my jest tests, but the effect so far has been my code builds just fine but jest cant resolve any dependencies during tests.

I feel intuitively that this is a runfiles issue, but I can't work out how to get bazel to drop me into an environment where I can check the layout.

## 🔬 Minimal Reproduction

Here is an example from https://github.com/Zemnmez/quickcult/tree/no-ttsc:

```bash
# all typescript code building just fine outside of jest:
ubuntu@ip-172-31-41-96:~/devel/quickcult$ yarn bazel build //typescript/iter:*
yarn run v1.22.11
$ /home/ubuntu/devel/quickcult/node_modules/.bin/bazel build '//typescript/iter:*'
INFO: Invocation ID: ac148d55-9314-419a-95f9-4afc5cc556d3
INFO: Build option --action_env has changed, discarding analysis cache.
INFO: Analyzed 34 targets (1 packages loaded, 13135 targets configured).
INFO: Found 34 targets...
INFO: Elapsed time: 4.303s, Critical Path: 0.13s
INFO: 3 processes: 3 internal.
INFO: Build completed successfully, 3 total actions
Done in 4.57s.
```

And running the tests:

```bash
ubuntu@ip-172-31-41-96:~/devel/quickcult$ yarn bazel test //typescript/iter:*
yarn run v1.22.11
$ /home/ubuntu/devel/quickcult/node_modules/.bin/bazel test '//typescript/iter:*'
INFO: Invocation ID: aef2aca3-3b12-4af4-9801-681637973ab4
INFO: Build option --action_env has changed, discarding analysis cache.
INFO: Analyzed 34 targets (1 packages loaded, 13135 targets configured).
INFO: Found 31 targets and 3 test targets...
FAIL: //typescript/iter:test (see /home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/execroot/quickcult/bazel-out/k8-fastbuild/testlogs/typescript/iter/test/test.log)
INFO: From Testing //typescript/iter:test:
==================== Test output for //typescript/iter:test:
 FAIL  typescript/iter/iter_test.js
  ● Test suite failed to run

    Cannot find module 'typescript/iter' from 'typescript/iter/iter_test.js'

      at Resolver.resolveModule (../npm/node_modules/jest-resolve/build/resolver.js:311:11)
      at Object.<anonymous> (../../../typescript/iter/iter_test.ts:1:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.519 s
Ran all test suites within paths "typescript/iter/iter_test.js".
================================================================================
INFO: Elapsed time: 4.626s, Critical Path: 1.68s
INFO: 2 processes: 2 linux-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//typescript/iter:iter_ts_lint                                  (cached) PASSED in 3.3s
//typescript/iter:tests_lib_ts_lint                             (cached) PASSED in 3.5s
//typescript/iter:test                                                   FAILED in 1.2s
  /home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/execroot/quickcult/bazel-out/k8-fastbuild/testlogs/typescript/iter/test/test.log

Executed 1 out of 3 tests: 2 tests pass and 1 fails locally.
INFO: Build completed, 1 test FAILED, 2 total actions
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## 🔥 Exception or Error

<pre><code>

yarn run v1.22.11
$ /home/ubuntu/devel/quickcult/node_modules/.bin/bazel test '//typescript/iter:*' --define=VERBOSE_LOGS=1
==================== Test output for //typescript/iter:test:
[link_node_modules.js] manifest file: /home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/421/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/test.sh.runfiles/quickcult/typescript/iter/_test.module_mappings.json
[link_node_modules.js] manifest contents: {
  "workspace": "quickcult",
  "bin": "bazel-out/k8-fastbuild/bin",
  "roots": {
    "": "npm"
  },
  "module_sets": {
    "": {
      "quickcult": "bazel-out/k8-fastbuild/bin"
    }
  }
}
[link_node_modules.js] startCwd: /home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/421/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/test.sh.runfiles/quickcult
[link_node_modules.js] execroot: /home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/421/execroot/quickcult
[link_node_modules.js] isExecroot: false
[link_node_modules.js] changed directory to execroot /home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/421/execroot/quickcult
[link_node_modules.js] resolved npm workspace node modules path to /home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/421/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/test.sh.runfiles/npm/node_modules
[link_node_modules.js] creating symlink node_modules -> /home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/421/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/test.sh.runfiles/npm/node_modules
[link_node_modules.js] modules for package path '':
{
  "quickcult": "bazel-out/k8-fastbuild/bin"
}
[link_node_modules.js] mapping hierarchy for package path '':
[{"name":"quickcult","link":"bazel-out/k8-fastbuild/bin"}]
[link_node_modules.js] creating symlink node_modules/quickcult -> /home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/421/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/test.sh.runfiles/quickcult/
BAZEL_NODE_MODULES_ROOTS=:npm
BAZEL_PATCH_ROOTS=/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/421/execroot/quickcult,/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/421/execroot/quickcult/node_modules,/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/421/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/test.sh.runfiles,/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/421/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/test.sh.runfiles/quickcult/node_modules,/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/421/execroot/quickcult/external/npm/node_modules,/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/421/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/test.sh.runfiles/npm/node_modules,/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/421/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/test.sh.runfiles/quickcult/external/npm/node_modules
bazel node patches enabled. roots: /home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/421/execroot/quickcult,/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/421/execroot/quickcult/node_modules,/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/421/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/test.sh.runfiles,/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/421/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/test.sh.runfiles/quickcult/node_modules,/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/421/execroot/quickcult/external/npm/node_modules,/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/421/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/test.sh.runfiles/npm/node_modules,/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/421/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/test.sh.runfiles/quickcult/external/npm/node_modules symlinks in these directories will not escape
 FAIL  typescript/iter/iter_test.js
  ● Test suite failed to run

    Cannot find module 'typescript/iter' from 'typescript/iter/iter_test.js'

      at Resolver.resolveModule (../npm/node_modules/jest-resolve/build/resolver.js:311:11)
      at Object.<anonymous> (../../../typescript/iter/iter_test.ts:1:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.586 s
Ran all test suites within paths "typescript/iter/iter_test.js".
================================================================================
==================== Test output for //typescript/iter:tests_lib_ts_lint:
[link_node_modules.js] manifest file: /home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/420/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/tests_lib_ts_lint.sh.runfiles/quickcult/typescript/iter/_tests_lib_ts_lint.module_mappings.json
[link_node_modules.js] manifest contents: {
  "workspace": "quickcult",
  "bin": "bazel-out/k8-fastbuild/bin",
  "roots": {
    "": "npm"
  },
  "module_sets": {}
}
[link_node_modules.js] startCwd: /home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/420/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/tests_lib_ts_lint.sh.runfiles/quickcult
[link_node_modules.js] execroot: /home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/420/execroot/quickcult
[link_node_modules.js] isExecroot: false
[link_node_modules.js] changed directory to execroot /home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/420/execroot/quickcult
[link_node_modules.js] resolved npm workspace node modules path to /home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/420/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/tests_lib_ts_lint.sh.runfiles/npm/node_modules
[link_node_modules.js] creating symlink node_modules -> /home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/420/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/tests_lib_ts_lint.sh.runfiles/npm/node_modules
BAZEL_NODE_MODULES_ROOTS=:npm
BAZEL_PATCH_ROOTS=/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/420/execroot/quickcult,/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/420/execroot/quickcult/node_modules,/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/420/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/tests_lib_ts_lint.sh.runfiles,/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/420/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/tests_lib_ts_lint.sh.runfiles/quickcult/node_modules,/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/420/execroot/quickcult/external/npm/node_modules,/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/420/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/tests_lib_ts_lint.sh.runfiles/npm/node_modules,/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/420/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/tests_lib_ts_lint.sh.runfiles/quickcult/external/npm/node_modules
bazel node patches enabled. roots: /home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/420/execroot/quickcult,/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/420/execroot/quickcult/node_modules,/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/420/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/tests_lib_ts_lint.sh.runfiles,/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/420/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/tests_lib_ts_lint.sh.runfiles/quickcult/node_modules,/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/420/execroot/quickcult/external/npm/node_modules,/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/420/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/tests_lib_ts_lint.sh.runfiles/npm/node_modules,/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/420/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/tests_lib_ts_lint.sh.runfiles/quickcult/external/npm/node_modules symlinks in these directories will not escape
jsxBracketSameLine is deprecated.

/home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/sandbox/linux-sandbox/420/execroot/quickcult/bazel-out/k8-fastbuild/bin/typescript/iter/tests_lib_ts_lint.sh.runfiles/quickcult/typescript/iter/iter_test.ts
  1:40  error  Insert `;`  prettier/prettier

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

================================================================================
//typescript/iter:iter_ts_lint                                  (cached) PASSED in 4.3s
//typescript/iter:test                                                   FAILED in 1.4s
  /home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/execroot/quickcult/bazel-out/k8-fastbuild/testlogs/typescript/iter/test/test.log
//typescript/iter:tests_lib_ts_lint                                      FAILED in 2.5s
  /home/ubuntu/.cache/bazel/_bazel_ubuntu/eef25c75b9bdd1803062da64b98415bb/execroot/quickcult/bazel-out/k8-fastbuild/testlogs/typescript/iter/tests_lib_ts_lint/test.log

Executed 2 out of 3 tests: 1 test passes and 2 fail locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
WSL 2
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
$ /home/ubuntu/devel/quickcult/node_modules/.bin/bazel version
Bazelisk version: v1.10.1
Build label: 5.0.0-pre.20210913.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Sep 17 16:54:24 2021 (1631897664)
Build timestamp: 1631897664
Build timestamp as int: 1631897664
Done in 0.13s.
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
4.2.0
  </code>
</pre>

**Anything else relevant?**

thank you :)

**Comment by alexeagle** [comment]
confirmed the files are passed to the jest_test action

```
bazel aquery //typescript/iter:test | grep Inputs | tr ',' '\n' | grep iter
  Inputs: [bazel-out/k8-fastbuild/bin/typescript/iter/test.sh.runfiles_manifest]
 bazel-out/k8-fastbuild/bin/typescript/iter/_test.module_mappings.json
 bazel-out/k8-fastbuild/bin/typescript/iter/dict.js
 bazel-out/k8-fastbuild/bin/typescript/iter/index.js
 bazel-out/k8-fastbuild/bin/typescript/iter/iter_test.js
 bazel-out/k8-fastbuild/bin/typescript/iter/test.sh
 bazel-out/k8-fastbuild/bin/typescript/iter/test.sh.runfiles/MANIFEST
 bazel-out/k8-fastbuild/bin/typescript/iter/test_loader.js
 bazel-out/k8-fastbuild/bin/typescript/iter/test_require_patch.js
```

I dunno about your trick to tell jest about the js files
```

jest_test(
    name = "test",
    srcs = [f[:-len(".ts")] + ".js" for f in tstestfiles],
    deps = [
        ":iter_js",
    ],
)
```

I think maybe you need something like this `--runTestsByPath` flag to point at the files in `bazel-out`
https://github.com/bazelbuild/rules_nodejs/blob/stable/examples/jest/jest.bzl

@mrmeku knows the most about Jest resolver.

**Comment by Zemnmez** [comment]
link workspace root happens here: https://github.com/Zemnmez/quickcult/blob/no-ttsc/rules.bzl#L13
```starlark
def jest_test(link_workspace_root = True, project_deps = [], deps = [], **kwargs):
    _jest_test(
        deps = deps + [ x + "_js" for x in project_deps ],
        link_workspace_root = link_workspace_root,
        **kwargs
    )
```

and then calls this macro https://github.com/Zemnmez/quickcult/blob/no-ttsc/tools/jest/jest.bzl
```starlark
def jest_test(name, srcs, deps = [], jest_config="//:jest.ts.config.js", **kwargs):
    "A macro around the autogenerated jest_test rule"
    templated_args = [
        "--no-cache",
        "--no-watchman",
        "--ci",
        "--colors",
    ]
    templated_args.extend(["--config", "$(rootpath %s)" % jest_config])
    for src in srcs:
        templated_args.extend(["--runTestsByPath", "$(rootpath %s)" % src])

    data = [jest_config] + srcs + deps + ["//tools/jest:jest_reporter_js"]
    _jest_test(
        name = name,
        data = data,
        templated_args = templated_args,
        **kwargs
    )

    # This rule is used specifically to update snapshots via `bazel run`
    jest(
        name = "%s.update" % name,
        data = data,
        templated_args = templated_args + ["-u"],
        **kwargs
    )
```

So it does actually use `--runtestsbypath`
