### ISSUE TITLE
Linker does not work properly with worker_sandboxing flag

### ISSUE THREAD

**Issue by matthewjh** [bazelbuild/rules_nodejs#2975]
### Description

When the `--worker_sandboxing` flag is on, programs relying on the linker do not work properly after the first run.

When the worker first starts up, the linker runs and creates the top-level node_modules -> npm external repo link, as well as the links to first-party modules in the npm repo; this is good.

When the worker rule's inputs change subsequently, Bazel cleans out the worker exec root in:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/worker/WorkerExecRoot.java#L36

This wipes out the links initially created by the linker.

I suspect the linker needs to be invoked anew every time the worker is told to re-build. I have a hacked-together version that does this and it seems to work well.

Another benefit of doing this is that the worker can then adapt to changes in the transitive module mappings over time. Deletion aside, by linking only once, I'm not sure things will work properly as first party packages are added and removed from the rule deps over the lifespan of the worker.

## 🔬 Minimal Reproduction

You can see this in the rules_nodejs_repo @ stable by adding `supports_workers = True` to the `ts_project` rule at

`packages/typescript/test/ts_project/worker/BUILD.bazel`

Then run `bazel build //packages/typescript/test/ts_project/worker:tsconfig --worker_sandboxing`

Let the first build run (it should work)

Note that the node_modules link is present at the worker root

Then make a code change

Re-run build command

Let the second build run (it should fail)

Note that the node_modules link is absent at the worker root

```
error TS2318: Cannot find global type 'Array'.

error TS2318: Cannot find global type 'Boolean'.

error TS2318: Cannot find global type 'Function'.

error TS2318: Cannot find global type 'IArguments'.

error TS2318: Cannot find global type 'Number'.

error TS2318: Cannot find global type 'Object'.

error TS2318: Cannot find global type 'RegExp'.

error TS2318: Cannot find global type 'String'.

error TS2688: Cannot find type definition file for 'google-protobuf'.
  The file is in the program because:
    Entry point for implicit type library 'google-protobuf'

error TS2688: Cannot find type definition file for 'long'.
  The file is in the program because:
    Entry point for implicit type library 'long'

error TS2688: Cannot find type definition file for 'node'.
  The file is in the program because:
    Entry point for implicit type library 'node'

error TS6053: File '/home/matt/.cache/bazel/_bazel_matt/05291f0e7e9413b48a99ef3149d206fb/bazel-workers/worker-1-TsProject/build_bazel_rules_nodejs/node_modules/typescript/lib/lib.d.ts' not found.
  The file is in the program because:
    Default library

````

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
4.2.1
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
stable
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
@gregmagolan is considering a new linker implementation that's more linker-friendly, that could be run more than once during a node process.
