### ISSUE TITLE
How to configure private npm registry with esbuild_repositories?

### ISSUE THREAD

**Issue by oxmo456** [bazelbuild/rules_nodejs#3005]
Hello,

I would like to use `esbuild_repositories `but unfortunately it seems that there is no way to configure a private npm registry. Would it make sense to have the capability to provide the environment argument from `npm_install `when calling `esbuild_repositories`?

Example:

`esbuild_repositories(npm_repository = "npm",     environment = { "npm_config_registry": "http://private_npm_registry/",},)`

I also looked at a way to globaly configure the npm registry but couldn't find one :/

Thank you for your help :)

**Comment by oxmo456** [comment]
Cool! I'll test this and let you know @alexeagle thank you!

**Comment by matthewjh** [comment]
> this uses the bazel downloader, so you can already configure it differently.
> 
> https://github.com/bazelbuild/bazel/blob/09c621e4cf5b968f4c6cdf905ab142d5961f9ddc/src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/UrlRewriterConfig.java#L66 is the best documentation I know of.
> 
> you make a file containing a rewrite rule like
> 
> `rewrite (registry.nodejs.org)/(.*) artifactory.build.internal.net/artifactory/$1/$2`
> 
> then point bazel to it with a line in `.bazelrc`
> 
> `common --experimental_downloader_config=.bazel_downloader_config`

That is nice! So far I had replicated all `http_archive` rules to point to our internal server, which is a PITA.  I'll give this a go

**Comment by alexeagle** [comment]
reopening this since I think we should get the answer into the docs
