### ISSUE TITLE
React example fails to run tests if used in a sub-directory

### ISSUE THREAD

**Issue by c16a** [bazelbuild/rules_nodejs#3007]
# 🐞 bug report

### Affected Rule

 The issue is caused by rules_nodejs

### Is this a regression?

 Not sure

### Description

 A clear and concise description of the problem...
When the [create-react-app example](https://github.com/bazelbuild/rules_nodejs/tree/stable/examples/create-react-app) is used in a standalone workspace, everything works as expected. But when it's used in a sub-directory, the `test` targets fail to find any test scripts and it fails. The `build` and `start` targets however work as expected even in this case.

## 🔬 Minimal Reproduction

This has been reproduced here https://github.com/c16a/react-bazel-template
Run `bazel test //...` to reproduce the error.

## 🔥 Exception or Error
The error is dumped into testlogs.
<pre><code>
Executing tests from //apps/web:test
-----------------------------------------------------------------------------
/home/c16a/.cache/bazel/_bazel_c16a/af73ff1e54a044e3e8e9034ef7074773/sandbox/linux-sandbox/130/execroot/chat/bazel-out/k8-fastbuild/bin/apps/web/test.sh.runfiles/chat/apps/web
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
No files found in /home/c16a/.cache/bazel/_bazel_c16a/af73ff1e54a044e3e8e9034ef7074773/sandbox/linux-sandbox/130/execroot/chat/bazel-out/k8-fastbuild/bin/apps/web/test.sh.runfiles/chat/apps/web.
Make sure Jest's configuration does not exclude this directory.
To set up Jest, make sure a package.json file exists.
Jest Documentation: facebook.github.io/jest/docs/configuration.html
Pattern:  - 0 matches

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
NAME="openSUSE Tumbleweed"
# VERSION="20211005"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20211005"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20211005"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo-Tumbleweed"
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.10.1
Build label: 4.2.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Aug 30 15:17:47 2021 (1630336667)
Build timestamp: 1630336667
Build timestamp as int: 1630336667
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "3635797a96c7bfcd0d265dacd722a07335e64d6ded9834af8d3f1b7ba5a25bba",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/4.3.0/rules_nodejs-4.3.0.tar.gz"],
)
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
thanks for the repro, I stared at it for a while but couldn't find the missing path segment. the jest process seems to me that it's executed in the right working directory.
