### ISSUE TITLE
timeout attribute in npm_install

### ISSUE THREAD

**Issue by UlysseM** [bazelbuild/rules_nodejs#301]
Hi,

I do have very large repository to pull, and I would often get the following error message:

> npm_install failed:  (Timed out; also encountered an error while attempting to retrieve output)

It looks like the npm_install is using the repository_ctx execute (https://docs.bazel.build/versions/master/skylark/lib/repository_ctx.html#execute - which has a default timeout of 600 seconds), to run npm install (https://github.com/bazelbuild/rules_nodejs/blob/f188192fa36ab285322f90866708bf18bcd3b736/internal/npm_install/npm_install.bzl#L107), but there is no way to provide a timeout argument to npm_install directly.

Would it be possible to expose the repository_ctx's timeout to the npm_install / yarn_install api?

If people are ok with this, I can try to make a patch.

**Comment by alexeagle** [comment]
Sure, exposing a `timeout` attribute on `npm_install` sounds okay to me.

Note that you should enable `--experimental_repository_cache` to avoid fetching the same repository repeatedly - but on CI it's harder to keep this incremental.
