### ISSUE TITLE
bazel build ... tries to build broken node_modules target

### ISSUE THREAD

**Issue by taymonbeal** [bazelbuild/rules_nodejs#3014]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: `yarn_install`

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 2.0.3

### Description

 `bazel build ...` fails because it attempts to build a target that's not actually part of my project, but instead introduced via `node_modules`, and that doesn't build correctly.

## 🔬 Minimal Reproduction

`bazel build --define=VERBOSE_LOGS=1 ...` from the `javascript` directory of https://github.com/taymonbeal/tink/tree/update-ts-deps

## 🔥 Exception or Error

<pre><code>
taymon@taymon9056690:~/tink/javascript$ bazel build --define=VERBOSE_LOGS=1 ...
DEBUG: /home/taymon/.cache/bazel/_bazel_taymon/037894a88ca005b5f57563ad86a74fca/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /home/taymon/.cache/bazel/_bazel_taymon/037894a88ca005b5f57563ad86a74fca/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:14: rbe_default not using checked in configs; Bazel version 4.2.1 was picked/selected but no checked in config was found in map {"0.20.0": ["8.0.0"], "0.21.0": ["8.0.0"], "0.22.0": ["8.0.0", "9.0.0"], "0.23.0": ["8.0.0", "9.0.0"], "0.23.1": ["8.0.0", "9.0.0"], "0.23.2": ["9.0.0"], "0.24.0": ["9.0.0"], "0.24.1": ["9.0.0"], "0.25.0": ["9.0.0"], "0.25.1": ["9.0.0"], "0.25.2": ["9.0.0"], "0.26.0": ["9.0.0"], "0.26.1": ["9.0.0"], "0.27.0": ["9.0.0"], "0.27.1": ["9.0.0"], "0.28.0": ["9.0.0"], "0.28.1": ["9.0.0"], "0.29.0": ["9.0.0"], "0.29.1": ["9.0.0", "10.0.0"], "1.0.0": ["9.0.0", "10.0.0"], "1.0.1": ["10.0.0"], "1.1.0": ["10.0.0"], "1.2.0": ["10.0.0"], "1.2.1": ["10.0.0"], "2.0.0": ["10.0.0"], "2.1.0": ["10.0.0"], "2.1.1": ["10.0.0", "11.0.0"], "2.2.0": ["11.0.0"], "3.0.0": ["11.0.0"], "3.1.0": ["11.0.0"], "3.2.0": ["11.0.0"], "3.3.0": ["11.0.0"], "3.3.1": ["11.0.0"], "3.4.1": ["11.0.0"], "3.5.0": ["11.0.0"], "3.5.1": ["11.0.0"], "3.6.0": ["11.0.0"], "3.7.0": ["11.0.0"], "3.7.1": ["11.0.0"], "3.7.2": ["11.0.0"]}
ERROR: While resolving toolchains for target //node_modules/@bazel/concatjs/third_party/github.com/bazelbuild/bazel/src/main/protobuf:blaze_worker_go_proto: no matching toolchains found for types @io_bazel_rules_go//go:toolchain
ERROR: Analysis of target '//node_modules/@bazel/concatjs/third_party/github.com/bazelbuild/bazel/src/main/protobuf:blaze_worker_go_proto' failed; build aborted: no matching toolchains found for types @io_bazel_rules_go//go:toolchain
INFO: Elapsed time: 0.098s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 88 targets configured)
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Debian Testing
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 4.2.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Aug 30 15:17:47 2021 (1630336667)
Build timestamp: 1630336667
Build timestamp as int: 1630336667
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
4.4.0
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
you should have `node_modules` in your `.bazelignore` file to prevent bazel from descending into that directory when expanding the recursive wildcard.
