### ISSUE TITLE
`@build_bazel_rules_nodejs//:bzl` has no integration test

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_nodejs#3030]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 

### Is this a regression?

Yes, loads and stardoc used to work just fine in at least `4.0.0`

### Description

 A clear and concise description of the problem...

Currently, rendering docs via `stardoc` is broken for `rules_rust` on newer versions of `rules_nodejs` because of an update to some of the `.bzl` files.

```
(21:15:47) ERROR: error loading package 'wasm_bindgen': in /workdir/wasm_bindgen/wasm_bindgen.bzl: in /workdir/wasm_bindgen/providers.bzl: cannot load '@build_bazel_rules_nodejs//internal/providers:declaration_info.bzl': no such file
```

https://github.com/bazelbuild/rules_rust/pull/984
https://github.com/bazelbuild/rules_rust/pull/953

There should be an integration test to ensure the `//:bzl` target actually includes all files such that external workspaces can continue to render stardoc docs.

```
ERROR: /private/var/tmp/_bazel_user/ed46dd183bde476d0b6a237289845378/external/build_bazel_rules_nodejs/BUILD.bazel:42:12: no such target '@build_bazel_rules_nodejs//internal/generated_file_test:bzl': target 'bzl' not declared in package 'internal/generated_file_test' defined by /private/var/tmp/_bazel_user/ed46dd183bde476d0b6a237289845378/external/build_bazel_rules_nodejs/internal/generated_file_test/BUILD and referenced by '@build_bazel_rules_nodejs//:bzl'
ERROR: /private/var/tmp/_bazel_user/ed46dd183bde476d0b6a237289845378/external/build_bazel_rules_nodejs/BUILD.bazel:42:12: no such target '@build_bazel_rules_nodejs//internal/linker:bzl': target 'bzl' not declared in package 'internal/linker' defined by /private/var/tmp/_bazel_user/ed46dd183bde476d0b6a237289845378/external/build_bazel_rules_nodejs/internal/linker/BUILD.bazel and referenced by '@build_bazel_rules_nodejs//:bzl'
```

## 🔬 Minimal Reproduction

Likely https://github.com/bazelbuild/rules_rust/pull/953

**Comment by UebelAndre** [comment]
I opened https://github.com/bazelbuild/rules_nodejs/pull/3068 to fix the ability to generate docs.

**Comment by gregmagolan** [comment]
No longer in scope for rules_nodejs which only supplies the Node.js toolchain as of [v6.0.0](https://github.com/bazelbuild/rules_nodejs/releases/tag/v6.0.0-beta0).

Downstream canonical JavaScript + Node.js ruleset is now https://github.com/aspect-build/rules_js.
