### ISSUE TITLE
yarn_versions helper only includes v1

### ISSUE THREAD

**Issue by Karibash** [bazelbuild/rules_nodejs#3071]
# 🚀 Yarn Berry Support

### Relevant Rules

[yarn_install](https://github.com/bazelbuild/rules_nodejs/blob/aa9882b9d5afaeb9815a3630017fa2911eeedb0a/internal/npm_install/npm_install.bzl#L808-L968)

### Description

When trying to use Yarn berry with the yarn_install rule, an error occurs because it implicitly sets the `--mutex network`, which is not supported by Yarn Berry.
The following implementation shows that the mutex option can be disabled by setting the `use_global_yarn_cache` to false, but the `--cache-folder` is implicitly set next.
https://github.com/bazelbuild/rules_nodejs/blob/aa9882b9d5afaeb9815a3630017fa2911eeedb0a/internal/npm_install/npm_install.bzl#L825-L834

In Yarn Berry, setting the `--cache-folder` in the CLI is deprecated, so an error will occur in this case as well.
https://github.com/yarnpkg/berry/blob/83311e1d4dec7fb6c0ead21f37efa9b687be58b9/packages/plugin-essentials/sources/commands/install.ts#L211-L219

The following is an example of WORKSPACE.bazel for using Yarn Berry.

```bazel
http_archive(
    name = "vendored_yarn_3_1_0",
    build_file_content = """exports_files(["vendored_yarn_3_1_0/berry--yarnpkg-cli-3.1.0/packages/yarnpkg-cli/bin/yarn.js"])""",
    urls = ["https://github.com/yarnpkg/berry/archive/refs/tags/@yarnpkg/cli/3.1.0.tar.gz"],
)

load("@build_bazel_rules_nodejs//:index.bzl", "node_repositories")
node_repositories(
    vendored_yarn = "@vendored_yarn_3_1_0//:berry--yarnpkg-cli-3.1.0/packages/yarnpkg-cli",
)

load("@build_bazel_rules_nodejs//:index.bzl", "yarn_install")
yarn_install(
    name = "npm",
    args = ["--immutable"],
    frozen_lockfile = False,
    use_global_yarn_cache = False,
    data = [
      "@//:.yarnrc.yml",
      "@vendored_yarn_3_1_0//:berry--yarnpkg-cli-3.1.0/packages/yarnpkg-cli/bin/yarn.js",
    ],
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
)
```

### Describe the solution you'd like

The ideas suggested in the issue comments below are helpful.
> 1. add a flag to remove the automatic addition of --mutex network
> 2. add a bool attribute yarn2_compatible that does not use --mutex network and replaces --frozen-lockfile with --immutable
> 3. detect that yarn2 is used and behave accordingly

https://github.com/bazelbuild/rules_nodejs/issues/1599#issuecomment-816480044

Personally, I think the 1st idea is better, as it seems to be easy to implement without destructive changes.
An example is shown below.

```diff
yarn_install(
    name = "npm",
    args = ["--immutable"],
    frozen_lockfile = False,
-   use_global_yarn_cache = False,
+   use_mutex = False,
    data = [
      "@//:.yarnrc.yml",
      "@vendored_yarn_3_1_0//:berry--yarnpkg-cli-3.1.0/packages/yarnpkg-cli/bin/yarn.js",
    ],
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
)
```

**Comment by lummax** [comment]
https://github.com/bazelbuild/rules_nodejs/blob/d2f9c4137543c3ed8477ca3aa73b2aa0fcbd7fe9/nodejs/private/yarn_versions.bzl while that comment still refers to an open issue, the list of supported yarn versions could be extended now.

**Comment by alexeagle** [comment]
I noticed from the example above that https://github.com/yarnpkg/berry/archive/refs/tags/@yarnpkg/cli/3.1.0.tar.gz is over 150MB file so I don't think that's quite the right workaround either.

**Comment by alexeagle** [comment]
Re-opening this issue to get the yarn_versions builtin to support more versions.

**Comment by vincent-lecrubier-skydio** [comment]
@alexeagle I see you made a PR for this and closed it. Would you mind explaining the current status on this please?

**Comment by sgammon** [comment]
friendly ping?

**Comment by alexeagle** [comment]
I checked out that pr again, and commented there. It doesn't actually work, and I don't have a client who needs it. Contributions welcome of course 😁

**Comment by alexeagle** [comment]
Just to wrap this up, rules_nodejs is no longer maintained and rules_js standardized on pnpm because it's lockfile allows us to port the node_modules layout to starlark, which allows lazy install of only needed packages for the requested build and test targets

**Comment by sgammon** [comment]
dumb question but that means pnpm is the way to go and yarn berry won't be supported, right? @alexeagle

**Comment by sgammon** [comment]
that does sound like a major gain
