### ISSUE TITLE
Apple M1 Mac (Darwin arm64) support for local development

### ISSUE THREAD

**Issue by CooperBills** [bazelbuild/rules_nodejs#3085]
# Apple M1 Mac (Darwin arm64) support for local development

### Description

Currently, `rules_nodejs` fails to build with Apple M1 Macs (Darwin arm64). This issue is to track updates to rules_nodejs to support local development on Macs using M1 processors (Darwin arm64). 

### Changes to enable support:
- [ ] Bump Bazel to 4.2.0 (4.2.0 includes a bugfix to properly report the CPU architecture on macs, which rules_go needs. See: https://github.com/bazelbuild/bazel/issues/12671 for more details)
- [x] Update tsconfigs to search `darwin_arm64-fastbuild` 
    * Done: https://github.com/bazelbuild/rules_nodejs/pull/3087
- [x] Bump `@io_bazel_rules_webtesting//web/versioned:browsers-0.3.2.bzl` to `0.3.3`, which includes drivers and browsers for macos arm64 targets (see: https://github.com/bazelbuild/rules_webtesting/pull/427)
    * Done: https://github.com/bazelbuild/rules_nodejs/pull/3086
- [ ] Modify Cypress toolchain to allow running on mac arm64. Currently, Cypress does not have an arm64 build and officially only supports running Cypress under rosetta. The rules_nodejs toolchains lock Cypress to only x86, and would need to be opened up to allow running Cypress on M1 Macs (via rosetta).
- [x] Update `//packages/concatjs:docs_scrub_platform` to also scrub arm64 platform builds.
    * Done: https://github.com/bazelbuild/rules_nodejs/pull/3089

The above changes enable successful full builds (`bazel build //...`) and testing (`bazel test //...`), with ~97% tests passing (the last 3% is because headless firefox is failing with timeouts).

I have these changes locally, and will be opening PRs for them in the next day or so.

**Comment by alexeagle** [comment]
Yes, users need Bazel 4.2.0, but I'm not sure how rules_nodejs has responsibility for that.

The other fixes sound right to me, thanks!

**Comment by CooperBills** [comment]
Ah, to clarify: it's to bump the `.bazelversion` (and corresponding locations) in the repository so contributors will use 4.2.0 (It's currently 4.1.0).

**Comment by CooperBills** [comment]
@alexeagle Looks like you already began bumping to 4.2.0 a month or so ago: https://github.com/bazelbuild/rules_nodejs/pull/2926

**Comment by alexeagle** [comment]
Yup, we have some more work to update our own version of Bazel, but that has no effect on what version users have. It's not transitive.

**Comment by alexeagle** [comment]
@CooperBills I think all the things here are landed, can we close this?

**Comment by CooperBills** [comment]
@alexeagle Although not everything has landed, I'm ok with closing this with the following note:

Any contributor working on an M1 Mac will need Bazel 4.2.0+, so this temporary one-line change locally is needed to get things working (until the repo's version is bumped):
```patch
Index: .bazelversion
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/.bazelversion b/.bazelversion
--- a/.bazelversion	(revision d30c366127c208d14d08adb74f4a847f87558c92)
+++ b/.bazelversion	(date 1638896444779)
@@ -1,1 +1,1 @@
-4.1.0
+4.2.0
```

Also, as of this writing, #3088 Has yet to be merged, so any contributor working on an M1 Mac will need to either pick the changes from that branch or temporarily add this one-line hack locally to get Cypress working:
```patch
Index: toolchains/cypress/BUILD.bazel
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/toolchains/cypress/BUILD.bazel b/toolchains/cypress/BUILD.bazel
--- a/toolchains/cypress/BUILD.bazel	(revision d30c366127c208d14d08adb74f4a847f87558c92)
+++ b/toolchains/cypress/BUILD.bazel	(date 1638896391246)
@@ -71,7 +71,7 @@
     name = "cypress_darwin_toolchain",
     target_compatible_with = [
         "@platforms//os:osx",
-        "@platforms//cpu:x86_64",
+#        "@platforms//cpu:x86_64",
     ],
     toolchain = ":cypress_darwin_toolchain_config",
     toolchain_type = ":toolchain_type",
```

With those work arounds the repo works quite well with M1's, so I think this ticket can be closed.

**Comment by alexeagle** [comment]
our local .bazelversion file in this repo doesn't affect what happens for users. The other PR is merged now. Thanks!
