### ISSUE TITLE
Executing npm binary in another binary through Bazel fails

### ISSUE THREAD

**Issue by jbeder** [bazelbuild/rules_nodejs#3098]
# 🐞 bug report

### Affected Rule

Somewhere in the interaction between `yarn_install` and Bazel's execution environment.

### Is this a regression?

I don't believe so.

### Description

I'm trying to execute a npm binary (in this case, the [Firebase emulator](https://www.npmjs.com/package/firebase-tools)) from a Go binary that's built and run through Bazel.

When I execute it within a test, it succeeds. When I execute the same code within a normal Go binary, it fails with:

```
ERROR: cannot find build_bazel_rules_nodejs/third_party/github.com/bazelbuild/bazel/tools/bash/runfiles/runfiles.bash
``` 

## 🔬 Minimal Reproduction

https://github.com/jbeder/bazel-bash-bug is a minimal reproduction. Please see there for complete details, but some highlights: the Firebase emulator is executed as follows (error handling elided for readability):

```
var firebase = "external/npm/firebase-tools/bin/firebase.sh"

rfpath, _ := bazel.RunfilesPath()
binary, _ := bazel.Runfile(firebase)
args := []string{"emulators:start", "--config", configFile, "--project", "demo-foo"}
cmd := exec.Command(binary, args...)
cmd.Dir = rfpath
cmd.Start()
```

Firebase is added to the library in Bazel as follows:

```
go_library(
    name = "bazel-bash-bug",
    srcs = ["fb.go"],
    data = ["@npm//firebase-tools/bin:firebase"],
    importpath = "github.com/jbeder/bazel-bash-bug",
    visibility = ["//visibility:public"],
    deps = ["@io_bazel_rules_go//go/tools/bazel:go_default_library"],
)
```

The library is executed in a Go test and a Go binary. When running the tests, either from `bazel test` or `bazel run`, it succeeds in starting the emulator:

```
bazel test --test_output=streamed  :bazel-bash-bug_test
```

and

```
bazel run  :bazel-bash-bug_test
```

but when running the binary, it fails:

```
$ bazel run main:main 
INFO: Analyzed target //main:main (1 packages loaded, 3 targets configured).
INFO: Found 1 target...
Target //main:main up-to-date:
  bazel-bin/main/main_/main
INFO: Elapsed time: 0.564s, Critical Path: 0.12s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
ERROR: cannot find build_bazel_rules_nodejs/third_party/github.com/bazelbuild/bazel/tools/bash/runfiles/runfiles.bash
2021/11/25 12:04:28 exit status 1
```

## 🔥 Exception or Error

```
ERROR: cannot find build_bazel_rules_nodejs/third_party/github.com/bazelbuild/bazel/tools/bash/runfiles/runfiles.bash
```

## 🌍  Your Environment

**Operating System:**

Mac OS 11.6.1

**Output of `bazel version`:**

```
Build label: 4.2.1-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jan 1 00:00:00 1980 (315532800)
Build timestamp: 315532800
Build timestamp as int: 315532800
```

**Rules_nodejs version:**

```
https://github.com/bazelbuild/rules_nodejs/releases/download/4.4.5/rules_nodejs-4.4.5.tar.gz
```

**Comment by alexeagle** [comment]
Looks to me like we just missed propagating a file through the runfiles provider somewhere.
