### ISSUE TITLE
Unable to run `@nodejs//:npm` directly when using `use_nvmrc`

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_nodejs#3109]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule:
`node_repositories`

### Is this a regression?

Not a regression that I know of.

### Description

If I run `@nodejs//:npm` and pass commands to it `bazel run @nodejs//:npm -- init` I run into the failure listed below. This is only an issue if the version of node is set via `use_nvmrc`. It works fine when explicitly setting `node_version`.

### nvmrc
```text
16.13.1
```

### BUILD.bazel
```python
# Empty
```

### WORKSPACE.bazel
```python
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "cfc289523cf1594598215901154a6c2515e8bf3671fd708264a6f6aefe02bf39",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/4.4.6/rules_nodejs-4.4.6.tar.gz"],
)

load("@build_bazel_rules_nodejs//:index.bzl", "node_repositories")

node_repositories(
    use_nvmrc = "//:.nvmrc",
)
```

## 🔥 Exception or Error

```
bazel run @nodejs//:npm -- init
```
<pre><code>
INFO: Invocation ID: 86c4c377-20ac-4652-b6ab-40b5115740bd
INFO: Analyzed target @nodejs//:npm (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target @nodejs_darwin_amd64//:bin/npm up-to-date (nothing to build)
INFO: Elapsed time: 0.147s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
/private/var/tmp/_bazel_user/186e9c9382f69ad6204d4160ff593da6/external/nodejs_darwin_amd64/bin/node: line 19: /private/var/tmp/_bazel_user/186e9c9382f69ad6204d4160ff593da6/external/nodejs_darwin_amd64/bin/nodejs/bin/node: No such file or directory
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
MacOS 11.6
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 4.2.1
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Aug 30 15:24:28 2021 (1630337068)
Build timestamp: 1630337068
Build timestamp as int: 1630337068
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>

  </code>
</pre>

**Anything else relevant?**

**Comment by thesayyn** [comment]
Hey, @UebelAndre 

Could you share minimal version of your workspace file especially the part where you declare the use_nvmrc attribute and contents of your nvmrc file?

**Comment by UebelAndre** [comment]
I thought I did in the issue description 🤔

**Comment by thesayyn** [comment]
Oh yes. sorry, my bad.

**Comment by thesayyn** [comment]
Looks like everything is in place. https://github.com/bazelbuild/rules_nodejs/blob/5798eeeda78c8acc2ebc2f24a41aca33164a972f/nodejs/private/node_versions.bzl#L1771 and version `16.13.1` is listed here.

**Comment by UebelAndre** [comment]
Yeah, this wouldn't be an issue of whether or not the node version was available. I feel like that error would be pretty obvious. I think users should be able to use the `use_nvmrc` attribute and see no behavior differences had they specified `node_version`. I haven't looked at the implementation since but expect something like this to be an easy fix or have an obvious solution.

**Comment by thesayyn** [comment]
A bit of update;

Upon closer look, I found out that `use_nvmrc` is not the root cause of the issue. I get the same error with `node_version` as well as with no attribute. 

As far as I can tell, the problem is that the `nodejs_register_toolchains` is not invoked by bazel at all. Probably this is something we broke along the way when we were splitting up the core. 

when I put the following code into my workspace file, I see the problem go away;

```python
http_archive(
    name = "rules_nodejs",
    sha256 = "8f4a19de1eb16b57ac03a8e9b78344b44473e0e06b0510cec14a81f6adfdfc25",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/4.4.6/rules_nodejs-core-4.4.6.tar.gz"],
)

load("@rules_nodejs//nodejs:repositories.bzl", "nodejs_register_toolchains", "rules_nodejs_dependencies")

nodejs_register_toolchains(
    name = "nodejs",
    node_version = "16.9.0",
)
```

though this is not a solution but a workaround.

**Comment by maksimr** [comment]
Hi, I have the same problem when try to use `use_nvmrc`. And looks like this attribute just ignored, so am I right that `use_nvmrc` doesn't work now?

**Comment by ve6yeq** [comment]
There is a "use before assignment" issue at:

https://github.com/bazelbuild/rules_nodejs/blob/621c75f1c2daac39ee7a0896938faf6ca4fcbbb9/nodejs/repositories.bzl#L354-L357

Where the call to `assert_node_exists_for_host(...)` uses the value of `node_version` before the value is read from the `.nvmrc` file in `_download_node(...)`. This results in `assert_node_exists_for_host(...)` using the default value for `node_version` which does not always exist for every platform. (e.g. for release 4.7.1, the default value of `node_version` is `14.17.5` which does not exist for `darwin-arm64` as `16.0.0` is the first supported version)

A simple workaround appears to be just to add a `node_version = "16.0.0"` as well as the `use_nvmrc = "//:.nvmrc"` such that the call to `assert_node_exists_for_host(...)` passes and execution continues to `_download_node(...)` where the value in `.nvmrc` overrides the value in `node_version` and the node runtime is downloaded according to the version in `.nvmrc`.
