### ISSUE TITLE
Using Starlark build setting values as `esbuild` `define`s

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/rules_nodejs#3113]
# feature request
### Relevant Rules
I would like to add an attribute to the existing `esbuild` rule.
### Description
The existing `esbuild` rule offers a `define` attribute that can be used to replace global identifiers in the output bundle with strings from a dict that are subject to Make variable and location expansion.
Given that the more modern way to pass configurable settings into Bazel is the use of Starlark build settings (e.g. those defined in bazel_skylib), it would be very useful if `esbuild` would allow to globally replace identifiers with their values.
### Describe the solution you'd like
A label-keyed string dict attribute could be added to `esbuild`, where labels are expected to be Starlark build settings (providing bazel_skylib's `BuildSettingInfo`) and mapped to the identifier their value should replace in the resulting bundle.
A problem with this approach is that `esbuild` would need an honest, non-vendored dependency on `bazel_skylib` to access the `BuildSettingInfo` provider. If this is acceptable, I could provide a PR that implements this feature.
### Describe alternatives you've considered
Create a separate rule that consumes build settings and writes out an esbuild config that contains the relevant defines. This would however require lots of boilerplate and nested configs.

**Comment by mattem** [comment]
Closed via #3122
