### ISSUE TITLE
select in toolchains causes eager fetch for all platforms

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#3124]
This should be removed:

https://github.com/bazelbuild/rules_nodejs/blob/stable/toolchains/node/BUILD.bazel#L94-L125

we have a `resolved_toolchain` mechanism in 5.x instead.

**Comment by mattem** [comment]
@alexeagle believes this is fixed now

**Comment by mattem** [comment]
Closed via #3172
