### ISSUE TITLE
 Bazel Jest Test Rule in a React TS Project Having Issues Resolving Module Imports

### ISSUE THREAD

**Issue by eyi1** [bazelbuild/rules_nodejs#3136]
# 🐞 Bazel Jest Test Rule in a react typescript project having issues resolving module imports

### Affected Rule

Integration of the following rules:
ts_project + jest_test

### Description

We’re adding a test suite using Jest (test runner) inside our Bazel ts project. But we're encountering a problem where Jest is unable to resolve the module import statements that use relative paths during the test runtime.

We have an **App.tsx** which depends on an import **sum.tsx**.
When we run out test, our test file: **App.test.tsx** can't find the **./sum** import from source. 

🔥   **The error we're seeing is ` Cannot find module './sum' from 'App.test.tsx'`**

**Hypothesis**: Jest (the test runner) is unable to resolve the module import statements that use relative paths during the test runtime because it appears that BAZEL does not put all the source together in the same directory (during that test execution runtime

## 🔬 Minimal Reproduction

// App.tsx
<pre><code>
import React from 'react';
import Sum from './sum';

function App() {
  return (
    <div className="App">
     <Sum />
    </div>
  );
}

export default App;
</code></pre>

// sum.tsx
<pre><code>
import React from 'react';

class Sum extends React.Component {
  render() {
    return Hello;
  }
}

export default Sum; 
</code></pre>

// App.test.tsx
<pre><code>
import React , { Component } from 'react';
import { render, screen } from '@testing-library/react';
import Sum from './components/sum';';

test('renders learn react link', () => {
  render(<Sum />);
  expect(true).toBe(true);
});
</code></pre>

// BUILD.bazel
<pre><code>
load("@npm//@bazel/typescript:index.bzl", "ts_project")
load("jest.bzl", "jest_test")
package(default_visibility = ["//visibility:public"])

ts_project(
    name = "src",
    srcs = ["index.tsx", "App.tsx", "sum.tsx"],
    extends = "//:tsconfig.json",
    tsconfig = {},
    deps = [
        "@npm//@types",
        "@npm//react",
        "@npm//@testing-library/jest-dom",
        "@npm//@types/jest",
        "@npm//@types/react",
        "@npm//@testing-library/react",
        "@npm//@babel/preset-react",
        "@npm//@babel/preset-typescript",
        "@npm//@babel/preset-env",
    ],
    out_dir = "out"
)

jest_test(
    name = "test",
    srcs = [".babelrc.js", "App.test.tsx"],
    jest_config = "jest.config.js",
    deps = [
        ":src",
        "@npm//react",
        "@npm//@types/jest",
        "@npm//@jest/transform",
        "@npm//@types/react",
        "@npm//@testing-library/react",
        "@npm//@testing-library/jest-dom",
        "@npm//babel-jest",
        "@npm//@babel/preset-react",
        "@npm//@babel/preset-typescript",
        "@npm//@babel/preset-env",
    ],
)
</code></pre>

### 🔥 🔥**Error**

// Test log outputs following error after this running in the command line: bazel test //src/...:all 

<pre>
<code>

exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //src:test
-----------------------------------------------------------------------------
{
  "configs": [
    {
      "automock": false,
      "cache": false,
      "cacheDirectory": "/private/var/folders/sz/jkrqch5x6p31t54rn_d2wryc0000gn/T/jest_dx",
      "clearMocks": false,
      "coveragePathIgnorePatterns": [
        "/node_modules/"
      ],
      "cwd": "/private/var/tmp/_bazel_eunyi/31648d8ea3039e4eb64767f87ff7e0ff/sandbox/darwin-sandbox/6/execroot/testjest/bazel-out/darwin-fastbuild/bin/src/test.sh.runfiles/testjest",
      "detectLeaks": false,
      "detectOpenHandles": false,
      "errorOnDeprecated": false,
      "extensionsToTreatAsEsm": [],
      "extraGlobals": [],
      "forceCoverageMatch": [],
      "globals": {},
      "haste": {
        "computeSha1": false,
        "enableSymlinks": false,
        "forceNodeFilesystemAPI": false,
        "throwOnModuleCollision": false
      },
      "injectGlobals": true,
      "moduleDirectories": [
        "node_modules"
      ],
      "moduleFileExtensions": [
        "js",
        "jsx",
        "ts",
        "tsx",
        "json",
        "node"
      ],
      "moduleNameMapper": [
        [
          "^~/(.*)$",
          "/private/var/tmp/_bazel_eunyi/31648d8ea3039e4eb64767f87ff7e0ff/sandbox/darwin-sandbox/6/execroot/testjest/bazel-out/darwin-fastbuild/bin/src/test.sh.runfiles/testjest/src/lib/ts/rms/src/$1"
        ]
      ],
      "modulePathIgnorePatterns": [],
      "name": "c1656db0e477666e6bd40f16fee7f78a",
      "prettierPath": "prettier",
      "resetMocks": false,
      "resetModules": false,
      "restoreMocks": false,
      "rootDir": "/private/var/tmp/_bazel_eunyi/31648d8ea3039e4eb64767f87ff7e0ff/sandbox/darwin-sandbox/6/execroot/testjest/bazel-out/darwin-fastbuild/bin/src/test.sh.runfiles/testjest/src",
      "roots": [
        "/private/var/tmp/_bazel_eunyi/31648d8ea3039e4eb64767f87ff7e0ff/sandbox/darwin-sandbox/6/execroot/testjest/bazel-out/darwin-fastbuild/bin/src/test.sh.runfiles/testjest/src"
      ],
      "runner": "/private/var/tmp/_bazel_eunyi/31648d8ea3039e4eb64767f87ff7e0ff/sandbox/darwin-sandbox/6/execroot/testjest/bazel-out/darwin-fastbuild/bin/src/test.sh.runfiles/testjest/node_modules/jest-cli/node_modules/jest-runner/build/index.js",
      "setupFiles": [],
      "setupFilesAfterEnv": [],
      "skipFilter": false,
      "slowTestThreshold": 5,
      "snapshotSerializers": [],
      "testEnvironment": "/private/var/tmp/_bazel_eunyi/31648d8ea3039e4eb64767f87ff7e0ff/sandbox/darwin-sandbox/6/execroot/testjest/bazel-out/darwin-fastbuild/bin/src/test.sh.runfiles/testjest/node_modules/jest-environment-jsdom/build/index.js",
      "testEnvironmentOptions": {},
      "testLocationInResults": false,
      "testMatch": [
        "**/__tests__/**/*.[jt]s?(x)",
        "**/?(*.)+(spec|test).[tj]s?(x)"
      ],
      "testPathIgnorePatterns": [
        "/node_modules/"
      ],
      "testRegex": [],
      "testRunner": "/private/var/tmp/_bazel_eunyi/31648d8ea3039e4eb64767f87ff7e0ff/sandbox/darwin-sandbox/6/execroot/testjest/bazel-out/darwin-fastbuild/bin/src/test.sh.runfiles/testjest/node_modules/jest-circus/runner.js",
      "testURL": "http://localhost",
      "timers": "real",
      "transform": [
        [
          "\\.[jt]sx?$",
          "/private/var/tmp/_bazel_eunyi/31648d8ea3039e4eb64767f87ff7e0ff/sandbox/darwin-sandbox/6/execroot/testjest/bazel-out/darwin-fastbuild/bin/src/test.sh.runfiles/testjest/node_modules/babel-jest/build/index.js",
          {}
        ]
      ],
      "transformIgnorePatterns": [
        "node_modules/"
      ],
      "watchPathIgnorePatterns": []
    }
  ],
  "globalConfig": {
    "bail": 0,
    "changedFilesWithAncestor": false,
    "collectCoverage": false,
    "collectCoverageFrom": [],
    "coverageDirectory": "/private/var/tmp/_bazel_eunyi/31648d8ea3039e4eb64767f87ff7e0ff/sandbox/darwin-sandbox/6/execroot/testjest/bazel-out/darwin-fastbuild/bin/src/test.sh.runfiles/testjest/src/coverage",
    "coverageProvider": "babel",
    "coverageReporters": [
      "json",
      "text",
      "lcov",
      "clover"
    ],
    "detectLeaks": false,
    "detectOpenHandles": false,
    "errorOnDeprecated": false,
    "expand": false,
    "findRelatedTests": false,
    "forceExit": false,
    "json": false,
    "lastCommit": false,
    "listTests": false,
    "logHeapUsage": false,
    "maxConcurrency": 5,
    "maxWorkers": 11,
    "noStackTrace": false,
    "nonFlagArgs": [
      "src/.babelrc.js",
      "src/App.test.tsx"
    ],
    "notify": false,
    "notifyMode": "failure-change",
    "onlyChanged": false,
    "onlyFailures": false,
    "passWithNoTests": false,
    "projects": [],
    "rootDir": "/private/var/tmp/_bazel_eunyi/31648d8ea3039e4eb64767f87ff7e0ff/sandbox/darwin-sandbox/6/execroot/testjest/bazel-out/darwin-fastbuild/bin/src/test.sh.runfiles/testjest/src",
    "runTestsByPath": true,
    "skipFilter": false,
    "testFailureExitCode": 1,
    "testPathPattern": "src/.babelrc.js|src/App.test.tsx",
    "testSequencer": "/private/var/tmp/_bazel_eunyi/31648d8ea3039e4eb64767f87ff7e0ff/sandbox/darwin-sandbox/6/execroot/testjest/bazel-out/darwin-fastbuild/bin/src/test.sh.runfiles/testjest/node_modules/jest-cli/node_modules/@jest/test-sequencer/build/index.js",
    "updateSnapshot": "none",
    "useStderr": false,
    "watch": false,
    "watchAll": false,
    "watchman": false
  },
  "version": "27.3.1"
}
FAIL src/App.test.tsx
  ● Test suite failed to run

    Cannot find module './sum' from 'App.test.tsx'

       6 | import { render, screen } from '@testing-library/react';
       7 | // import App from './App';
    >  8 | import Sum from './sum';
         | ^
       9 |
      10 | // jest.mock("./components/sum");
      11 |

      at Resolver.resolveModule (../node_modules/jest-runtime/node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (App.test.tsx:8:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.874 s
Ran all test suites within paths "src/.babelrc.js", "src/App.test.tsx".

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
MacOS Big Sur Version 11.6
  </code>
</pre>

**Rules_nodejs version:**

Using Version 4.4.6

<pre>
  <code>
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "cfc289523cf1594598215901154a6c2515e8bf3671fd708264a6f6aefe02bf39",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/4.4.6/rules_nodejs-4.4.6.tar.gz"],
)
  </code>
</pre>

**Anything else relevant?**

Can anybody shed some light on this issue?

**Comment by bzitzow** [comment]
The fix: 
```
js_library(
    name = "src-js",
    deps = [
        "//workspace/location/src",
    ],
)
```

Then reference the `js_library.name` in the `jest_test` config as a dependency.

```
jest_test(
...
    deps = [
        # JS source files post typescript transpilation:
        "//workspace/location/src:src-js",
```
