### ISSUE TITLE
.d.ts files not included when packaging with pkg_web

### ISSUE THREAD

**Issue by chortis** [bazelbuild/rules_nodejs#3137]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: pkg_web (also pkg_tar from rules_pkg)

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Unsure

### Description

 I am trying to move some directories around to get a structure before packing an npm package for distribution. The structure I want doesn't match the src's so I am trying to pack them up into a tar and organize them which I can do, but when packing, Bazel seems to be not including any declaration files from compiled typescript, or anything with `.d.`

Runniny my `ts_project` rule does properly generate everything I want.

Is this some sort of configuration problem or bug?

## 🔬 Minimal Reproduction

<pre><code>

pkg_web(
    name = "package_lib",
    srcs = [
        "//package/src",
        "//package/types",
        "//assets"
    ],
    additional_root_paths = [
        "package/src"
    ]
)

</code></pre>

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
MacOS
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
4.1.0
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
4.0.0
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
pkg_web isn't meant for just moving files around, it's specifically for targetting a browser runtime which is why typings aren't included.

You can write something simpler to just copy files around, or use something like https://docs.aspect.dev/aspect-build/bazel-lib/v0.3.0/docs/docs/copy_to_directory-docgen.html

**Comment by chortis** [comment]
> pkg_web isn't meant for just moving files around, it's specifically for targetting a browser runtime which is why typings aren't included.
> 
> You can write something simpler to just copy files around, or use something like https://docs.aspect.dev/aspect-build/bazel-lib/v0.3.0/docs/docs/copy_to_directory-docgen.html

Great thanks! I used the `copy_to_directory` macro and got the structure I want (also much faster :D) but copying the dir still doesn't include the declarations. Anything with a `.d.` in the file is ignored when copying.

I am wondering if there is something Bazel is doing to ignore these files. This isn't a bug in this repo though.

**Comment by chortis** [comment]
Actually as I further investigated, it seems I might be mistaken, but it looks like `.d` files aren't included in the actual output of `ts_project`. When looking at verbose logging it is only `js` and `map` files. 

The declarations are in the `bin` directory of the compiled source, and they have been set in my `ts_project` and tsconfig However if I'm using this in another rule they aren't included. I'm not exactly sure what I'm missing here.

**Comment by alexeagle** [comment]
ah, Bazel actually has multiple sets of output files. When you build a target, or dep on it, you get the files in DefaultInfo.

ts_project also provides OutputGroupInfo
https://github.com/bazelbuild/rules_nodejs/blob/4.4.6/packages/typescript/internal/ts_project.bzl#L247

which means you can `bazel build //my:ts_project --output_groups=types` or 
```
filegroup(
   name = "select_typings",
  srcs = "my_tsproject",
  output_groups = "types")
```
to grab the .d.ts outputs

**Comment by chortis** [comment]
That's it. Awesome thanks so much for your help.
