### ISSUE TITLE
Support bzlmod users

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#3138]
When Bazel 5.0 ships, users are going to want to use rules_nodejs from their MODULE.bazel file. We should get our module registered in the bazel-central-registry and have it manage the toolchains.

**Comment by uhthomas** [comment]
I see, thanks for the pointers. Is it recommended to use aspect's rules over rules_nodejs? Is there  any official suggestion, plans to merge or deprecate?

**Comment by alexeagle** [comment]
All the maintainers are now working on aspect rules_js so yes, over the course of the next months as it matures past 1.0 I'd recommend users migrate. It's a rewrite and so much too breaking to make it a 6.0 of rules_nodejs.

**Comment by alexeagle** [comment]
build_bazel_rules_nodejs will probably never go on the BCR and is no longer in this repo at HEAD.
