### ISSUE TITLE
Should be possible for users to write their own TS rule

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#3139]
In rules_nodejs core, we should provide the primitives for building a variety of nodejs/browser toolchains. We can't pick all the winners.

One example is `ts_project` where we made some decisions. In particular, it's shipped as an npm package rather than a bazel module, so that it can use the version of typescript that the project uses, as a peerdependency.

This is not an obvious choice, as it can require downloading lots of npm packages just to type-check a file. We should expose the `tsc` helper logic as a starlark library so that others can write rules that do it differently according to their needs.

Large companies in particular usually have special constraints from their legacy system and are better off adapting bazel to their repo rather than the other way.

**Comment by gregmagolan** [comment]
No longer in scope for rules_nodejs which only supplies the Node.js toolchain as of [v6.0.0](https://github.com/bazelbuild/rules_nodejs/releases/tag/v6.0.0-beta0).

Downstream canonical JavaScript + Node.js ruleset is now https://github.com/aspect-build/rules_js.
