### ISSUE TITLE
@nodejs//:node crashing in custom rules with 0.11.0+

### ISSUE THREAD

**Issue by fwouts** [bazelbuild/rules_nodejs#314]
I've been using the `@nodejs//:node` target to define other Bazel rules, like the following:
```py
def _my_rule_impl(ctx):
  ctx.actions.run(
    executable = ctx.file._internal_nodejs,
    inputs = [
      ctx.file._script,
    ],
    outputs = [ctx.outputs.output],
    arguments = [
      # Run `node my-rule.js`.
      ctx.file._script.path,
      # Output path.
      ctx.outputs.output.path,
    ]
  )

my_rule = rule(
  implementation = _my_rule_impl,
  attrs = {
    "_internal_nodejs": attr.label(
      allow_files = True,
      single_file = True,
      default = Label("@nodejs//:node"),
    ),
    "_script": attr.label(
      allow_files = True,
      single_file = True,
      default = Label("//my_rule:my-rule-impl.js"),
    ),
  },
  outputs = {
    "output": "%{name}_output"
  }
)
```

This rule's implementation would effectively delegate to a NodeJS script like the following:
```js
const fs = require("fs");
const [, , outputPath] = process.argv;
fs.writeFileSync(outputPath, "Hello, World!", "utf8");
```

This worked extremely well, until rules_nodejs@0.11.0 which broke this behaviour. My rule now fails with the following error:
```
ERROR: /Users/work/dev/bazel-bug/example/BUILD.bazel:5:1: SkylarkAction example/example_output failed (Exit 127)
external/nodejs/bin/node: line 5: external/nodejs/bin/nodejs/bin/node: No such file or directory
Target //example:example failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 9.423s, Critical Path: 0.05s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

Did something change with the `@nodejs//:node` target? It looks like the path `external/nodejs/bin/nodejs/bin/node` is incorrect, as it should probably be `external/nodejs/bin/node`?

To make it easier for you to debug, I've created the smallest possible example in the following repo: https://github.com/zenclabs/bazel-rules-nodejs-bug-repro

**Comment by fwouts** [comment]
I wonder if https://github.com/bazelbuild/rules_nodejs/commit/1cda064b92e7ee295a8e02aae42c3316166076cd could be the culprit.

**Comment by gregmagolan** [comment]
The files of the external @nodejs repository have been moved around a few times to fix various bugs and to support RBE (remote bazel execution). Not sure which change would have broke this for you. The `@nodejs//:node` target is now an alias for `@nodejs//:bin/node` which is a shell script that sets up some paths and then calls into the nodejs binary `@nodejs//:bin/nodejs/bin/node`.

If you change your custom rule to
```
    "_internal_nodejs": attr.label(
      allow_files = True,
      single_file = True,
      default = Label("@nodejs//:bin/nodejs/bin/node"),
    ),
```
which points to the nodejs binary itself then it should work with the latest versions of rules_nodejs. Note: on Windows the nodejs binary is `@nodejs//:bin/nodejs/node.exe`.

**Comment by fwouts** [comment]
Thank you! I can confirm `Label("@nodejs//:bin/nodejs/bin/node")` works on Mac.

I'm not sure how to work with the constraint that it's a different target for Windows. How are you meant to select a different target dynamically?

I was thinking of doing the following:
```
my_rule = rule(
  implementation = _my_rule_impl,
  attrs = {
    "_internal_nodejs_unix": attr.label(
      allow_files = True,
      single_file = True,
      default = Label("@nodejs//:bin/nodejs/bin/node"),
    ),
    "_internal_nodejs_windows": attr.label(
      allow_files = True,
      single_file = True,
      default = Label("@nodejs//:bin/nodejs/node.exe"),
    ),
    "_script": attr.label(
      allow_files = True,
      single_file = True,
      default = Label("//my_rule:my-rule-impl.js"),
    ),
  },
  outputs = {
    "output": "%{name}_output"
  }
)
```

and then picking one or the other [depending on the current platform](https://github.com/bazelbuild/bazel/issues/2045) (since we don't have access to `ctx` when the rule is declared, only in its implementation).

Unfortunately this doesn't work:
```
$ bazel build //...
ERROR: /Users/work/dev/bazel-bug/example/BUILD.bazel:5:1: every rule of type my_rule implicitly depends upon the target '@nodejs//:bin/nodejs/node.exe', but this target could not be found because of: no such target '@nodejs//:bin/nodejs/node.exe': target 'bin/nodejs/node.exe' not declared in package '' defined by /private/var/tmp/_bazel_work/59b8e7c5adb214339c3c1d8c99d11183/external/nodejs/BUILD.bazel
ERROR: Analysis of target '//example:example' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.115s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
```

If there's some Bazel documentation that addresses this, please feel free to send me that way and close the ticket. I've looked for a while and haven't found a way.

It seems like it would all be easier if there was a single Node binary target that wasn't platform-specific. I'm guessing that's impossible for technical reasons?

**Comment by fwouts** [comment]
The culprit is ce8148b7de3a3d7621e47d26dc30e21fd0849a14. Reverting only this commit makes the alias `@nodejs//:node` work again.

What happens is that `CUR_DIR=$(dirname ${BASH_SOURCE[0]})` doesn't lead to the correct location when using `@nodejs//:node` from another workspace (it's a relative path).

To illustrate what I mean, I added debug statements in the [`bin/node` bash script](https://github.com/bazelbuild/rules_nodejs/blob/master/internal/node/node_repositories.bzl#L233):
```
repository_ctx.file("bin/node", content="""#!/bin/bash
#Generated by node_repositories.bzl
CUR_DIR=$(dirname ${{BASH_SOURCE[0]}})
echo "CUR_DIR=$CUR_DIR"
tree $CUR_DIR
...
```

This is the output when you run `@nodejs//:node` directly (no issues):
```
$ bazel run @nodejs//:node
CUR_DIR=/private/var/tmp/_bazel_work/59b8e7c5adb214339c3c1d8c99d11183/external/nodejs/bin
/private/var/tmp/_bazel_work/59b8e7c5adb214339c3c1d8c99d11183/external/nodejs/bin
├── node
├── node.js
├── node_args.sh
├── nodejs
│   ├── CHANGELOG.md
│   ├── LICENSE
│   ├── README.md
│   ├── bin
│   │   ├── node
│   │   ├── npm -> ../lib/node_modules/npm/bin/npm-cli.js
│   │   └── npx -> ../lib/node_modules/npm/bin/npx-cli.js
...
```

Whereas from another workspace (like [this one](https://github.com/zenclabs/bazel-rules-nodejs-bug-repro)), `CUR_DIR` seems very much incorrect:
```
$ bazel build //...
INFO: Analysed target //example:example (4 packages loaded).
INFO: Found 1 target...
ERROR: /Users/work/dev/bazel-bug/example/BUILD.bazel:5:1: SkylarkAction example/example_output failed (Exit 127)
external/nodejs/bin/node: line 7: external/nodejs/bin/nodejs/bin/node: No such file or directory
CUR_DIR=external/nodejs/bin
external/nodejs/bin
`-- node -> /private/var/tmp/_bazel_work/59b8e7c5adb214339c3c1d8c99d11183/execroot/bazel_javascript/external/nodejs/bin/node

0 directories, 1 file
Target //example:example failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.216s, Critical Path: 0.06s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

This looks to me like a real bug. @huangw5 since you authored the breaking commit, would you have suggestions on how to fix this?

**Comment by huangw5** [comment]
Thanks @fwouts for reporting the bug. I confirm that I can reproduce it. I will try to have a fix asap.
