### ISSUE TITLE
[pkg_npm] Tarball runfile does not respect workspace environment replacements

### ISSUE THREAD

**Issue by sumwatshade** [bazelbuild/rules_nodejs#3143]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: `pkg_npm`

### Is this a regression?

Not to my knowledge, we had previously not attempted to use the `tgz` flag

### Description

Our team has a use case where we want to grab the generated tarball from the `pkg_npm` command so that we can augment it for distribution. After adding the `tgz` per rules_nodejs docs, we observe failures around our substitutions for `{VERSION}` (and/or workspace status command vars) not being replaced.

## 🔬 Minimal Reproduction

A minimal reproduction has been provided in [this sample repo](https://github.com/sumwatshade/bazel-simple) and found by running the following after cloning the repo:

```
yarn
yarn bazelisk build //packages/core:release.tar --verbose_failures --stamp
```

## 🔥 Exception or Error

<pre><code>
bazel-simple/packages/core/BUILD.bazel:83:8: Executing genrule //packages/core:release.tar failed: (Exit 1): bash failed: error executing command
  (cd /private/var/tmp/_bazel_lshadler/4105e2cfbecd5b0747c78df78ebf4cd8/execroot/bazel_simple && \
  exec env - \
    PATH=***** \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/packages/core/release.pack.sh 2>/dev/null | tail -1 | xargs -I {} cp {} bazel-out/darwin-fastbuild/bin/packages/core/core.tgz')
Execution platform: @local_config_platform//:host
Target //packages/core:release.tar failed to build
</code></pre>

Digging into this error and re-running the `release.pack.sh` command within the sandbox displays this:

<pre><code>
/private/var/tmp/_bazel_lshadler/4105e2cfbecd5b0747c78df78ebf4cd8/execroot/bazel_simple
❯ /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/packages/core/release.pack.sh'
npm ERR! Invalid version: "${MY_VERSION}"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lshadler/.npm/_logs/2021-12-14T01_05_17_728Z-debug.log
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS Big Sur 11.6.1
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.10.1
Starting local Bazel server and connecting to it...
Build label: 4.2.2
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 2 18:28:52 2021 (1638469732)
Build timestamp: 1638469732
Build timestamp as int: 1638469732
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
4.4.2
  </code>
</pre>

**Comment by sumwatshade** [comment]
Notable diff between `release-0.params`:

```diff
+++ bazel-out/darwin-fastbuild/bin/packages/core/release-0.params
--- bazel-out/host/bin/packages/core/release-0.params
bazel-out/darwin-fastbuild/bin/packages/core/release
packages/core
'[]'
'[{"path":"bazel-out/darwin-fastbuild/bin/packages/core/package.json","shortPath":"packages/core/package.json"},{"path":"bazel-out/darwin-fastbuild/bin/packages/core/lib/main.js","shortPath":"packages/core/lib/main.js"},{"path":"bazel-out/darwin-fastbuild/bin/packages/core/lib/name.js","shortPath":"packages/core/lib/name.js"},{"path":"bazel-out/darwin-fastbuild/bin/packages/core/lib/main.d.ts","shortPath":"packages/core/lib/main.d.ts"},{"path":"bazel-out/darwin-fastbuild/bin/packages/core/lib/name.d.ts","shortPath":"packages/core/lib/name.d.ts"}]'
'[]'
'{"1.0.0-PLACEHOLDER": "${MY_VERSION}"}'
- ''
- ''
+ bazel-out/volatile-status.txt
+ bazel-out/stable-status.txt
''
//packages/core:release
true
@sumwatshade/core
```

In the latter section, I also see that `bazel-out/host/bin/packages/core/release/package.json` does not have the appropriate replacement for `${MY_VERSION}`. Naively, this appears as if the workspace status commands are not being propagated as context for the `release.pack.sh` script executed [here](https://github.com/bazelbuild/rules_nodejs/blob/stable/internal/pkg_npm/pkg_npm.bzl#L405)

**Comment by mattem** [comment]
Thanks for the repro!
