### ISSUE TITLE
npm_package_bin doesn't pass through `tags`

### ISSUE THREAD

**Issue by arohner** [bazelbuild/rules_nodejs#3156]
# 🚀 feature request

npm_package_bin doesn't seem to pass through `tags=["no-sandbox"]` to the underlying actions. It would be great if it did.

### Relevant Rules

npm_package_bin

### Description

I have an `npm_package_bin` action that works with `--spawn_strategy=local`, but fails under the sandbox. As a quick hack, it would be nice if I could disable the sandbox on this particular step without disabling it for the rest of the build.

**Comment by alexeagle** [comment]
you should just turn on `experimental_allow_tags_propagation ` in your bazelrc 
https://github.com/bazelbuild/bazel/issues/8830

which fixes it for npm_package_bin and also every other custom Bazel rule.
