### ISSUE TITLE
support binary files in generated_file_test

### ISSUE THREAD

**Issue by longlho** [bazelbuild/rules_nodejs#3184]
# 🚀 feature request

### Relevant Rules

`generated_file_test`

### Description

We have the use case of checking in assets like fonts/png/tar files and it'd be great if `generated_file_test` supports binary files as well. Right now it reads file as `utf-8` encoding and during write as well which messes stuff up.

Happy to put in a PR if you want.

### Describe the solution you'd like

`generated_file_test` supports binary files as well.

### Describe alternatives you've considered

Write my own implementation?

**Comment by alexeagle** [comment]
We have `is_binary` in the repo already, but it has false positives.

The simplest answer is to use bazel-skylib directly. I added a `failure_message` attribute to `diff_test` https://docs.aspect.dev/bazelbuild/bazel-skylib/1.1.1/docs/diff_test.html
so you can just use the pattern directly, paired with an sh_binary to copy the file.
See https://blog.aspect.dev/bazel-can-write-to-the-source-folder

**Comment by longlho** [comment]
thanks for the pointer. That works!
