### ISSUE TITLE
Local package linking does not propagate to tests

### ISSUE THREAD

**Issue by riyavsinha** [bazelbuild/rules_nodejs#3186]
# 🐞 bug report

### Affected Rule

Not sure, I think it may have to do more with how tests handle local package linking by `npm_install` than `npm_install` itself?

### Is this a regression?

Not as far as I know

### Description

When using `npm_install`, there is a `[links](https://bazelbuild.github.io/rules_nodejs/Built-ins.html#npm_install-links)` argument available that is supposed to enable linking a bazel target to another's `node_modules`. This works when building, but then fails when running tests, throwing errors about how it "cannot find" the locally linked package.

My understanding is that when running the test, the `runfiles` section creates a sandboxed environment to run the test in, but the local package declarations in the WORKSPACE are not propagating to this test environment, and it therefore does not know where to look to resolve package dependencies properly.

## 🔬 Minimal Reproduction

https://github.com/riyavsinha/bazel_npm_install_links

Run `$ npx bazel test //packages/pkg_a/server/tests`

## 🔥 Exception or Error

<pre><code>
  Error: Cannot find module '../src/run-generator'
  Require stack:
  - /private/var/tmp/_bazel_riyavsinha/fdaf9e77a057c94623bff564de10ce59/sandbox/darwin-sandbox/57/execroot/example/bazel-out/darwin-fastbuild/bin/packages/pkg_a/server/tests/tests.sh.runfiles/example/packages/pkg_a/server/tests/run-generator-test.js
  - /Users/riyavsinha/Projects/bazel_npm_install_links/packages/pkg_a/node_modules/ava/lib/worker/base.js

  › - /Users/riyavsinha/Projects/bazel_npm_install_links/packages/pkg_a/node_modules/ava/lib/worker/base.js
  › Object.<anonymous> (packages/pkg_a/server/tests/run-generator-test.js:2:21)

  ✖ packages/pkg_a/server/tests/run-generator-test.js exited with a non-zero exit code: 1

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
      macOS Monterey v12.1
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.10.1
Build label: 4.2.2
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 2 18:28:52 2021 (1638469732)
Build timestamp: 1638469732
Build timestamp as int: 1638469732
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
4.5.1
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
I think this is fixed in rules_js
