### ISSUE TITLE
cypress_web_test cannot expand locations in env as documented

### ISSUE THREAD

**Issue by djmarcin** [bazelbuild/rules_nodejs#3239]
# 🐞 bug report

### Affected Rule

cypress_web_test

### Is this a regression?

Not sure, but it does not match the documented behavior.

### Description

Attempting to use any location expansion in cypress_web_test results in an error. This is because of [this code](https://github.com/bazelbuild/rules_nodejs/blob/6acec9d336f96d4036298168d5bf0ff0fa0de3ca/packages/cypress/internal/cypress_web_test.bzl#L106-L111), which creates a list with an embedded list that is eventually passed to ctx.expand_location which rejects this format.

## 🔬 Minimal Reproduction

Any cypress_web_test rule with an env expansion like: `env = { "FOO": "//:foo" }`

## 🔥 Exception or Error

<pre><code>
Traceback (most recent call last):
        File "/home/david/.cache/bazel/_bazel_david/7d1037d21a52700832f2c490bcd1c89d/external/npm/@bazel/cypress/internal/cypress_web_test.bzl", line 113, column 48, in _cypress_web_test_impl
                return nodejs_test_kwargs["implementation"](
        File "/home/david/.cache/bazel/_bazel_david/7d1037d21a52700832f2c490bcd1c89d/external/build_bazel_rules_nodejs/internal/node/node.bzl", line 206, column 75, in _nodejs_binary_impl
                env_vars += "export %s=%s\n" % (key, expand_location_into_runfiles(ctx, value, data))
        File "/home/david/.cache/bazel/_bazel_david/7d1037d21a52700832f2c490bcd1c89d/external/build_bazel_rules_nodejs/internal/common/expand_into_runfiles.bzl", line 111, column 40, in expand_location_into_runfiles
                path += ctx.expand_location(input[i:j], targets)
Error in expand_location: at index 0 of targets, got element of type list, want Target</code>
</pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu Linux 20.04
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.11.0
Build label: 6.0.0-pre.20211215.3
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Dec 21 19:45:47 2021 (1640115947)
Build timestamp: 1640115947
Build timestamp as int: 1640115947
  </code>

Also reproduces on 
  <code>
Bazelisk version: v1.11.0
Build label: 4.2.2
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 2 18:15:58 2021 (1638468958)
Build timestamp: 1638468958
Build timestamp as int: 1638468958
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
4.6.0
  </code>
</pre>

**Anything else relevant?**

**Comment by anagrius** [comment]
doing `env: {"X": "$(execpath :my-file)"}` crashes Bazel completely

**Comment by gregmagolan** [comment]
No longer in scope for rules_nodejs which only supplies the Node.js toolchain as of [v6.0.0](https://github.com/bazelbuild/rules_nodejs/releases/tag/v6.0.0-beta0).

Downstream canonical Cypress + Node.js ruleset is now https://github.com/aspect-build/rules_cypress.
