### ISSUE TITLE
jasmine_node_test not creating links in Windows

### ISSUE THREAD

**Issue by alan-agius4** [bazelbuild/rules_nodejs#325]
When using `jasmine_node_test`. The symlinks under `workspace.test.runfiles` are not being created when running on `Windows` however these are when running on `Mac`

If you take a look at the below screenshots, on Windows there is no files and folders on top of `MANIFEST`, while on `Mac` there are.

**Windows**
![image](https://user-images.githubusercontent.com/17563226/45624875-daddf580-ba8b-11e8-8aee-920aa86ae7f5.png)

**Mac**
<img width="419" alt="screen shot 2018-09-17 at 14 39 48" src="https://user-images.githubusercontent.com/17563226/45624904-ea5d3e80-ba8b-11e8-88e2-54281e557313.png">

Reproduction;
1 ) clone https://github.com/alan-agius4/jasmine_node_test_different_output
2) run `bazel test :tests`

I would expect that running this on both platforms will have the same result.

**Comment by meteorcloudy** [comment]
@alan-agius4 Are you passing `--experimental_enable_runfiles` flag?  Creating symlink tree is not enabled by default on Windows. And you also need to use Bazel built from HEAD or a 0.18.0 release candidate.

**Comment by alan-agius4** [comment]
Thanks for your answer.

 No, and I am using bazel `0.17.1`

**Comment by alexeagle** [comment]
It's expected that runfiles tree isn't present on Windows. rules should read through the manifest file instead.
