### ISSUE TITLE
Generated webpack rule doesn't build when used as a dependency

### ISSUE THREAD

**Issue by geoffliu** [bazelbuild/rules_nodejs#3257]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 
@npm//webpack

### Is this a regression?

 Not sure, this is my first attempt with Bazel + JS

### Description

 A clear and concise description of the problem...
Please take a look at the minimal repro below. I have two rules. The first uses `@npm//webpack` to bundle JS files, and the second is a `sh_binary` rule that uses the output of the first as data attribute. Running `bazel query 'deps(//:upload)'` correctly shows that `//:src/index.js` is a dependency (along with a lot of node modules files).

When I `bazel build //:upload`, the build completes without error, but webpack is not invoked. Checking bazel-out and bazel-bin confirms that there is no webpack output.

## 🔬 Minimal Reproduction
https://github.com/geoffliu/bazel-issue

## 🔥 Exception or Error
None

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
OSX 11.6
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 4.2.2-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jan 1 00:00:00 1980 (315532800)
Build timestamp: 315532800
Build timestamp as int: 315532800
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
4.6.0
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
building the :bundle target works correctly

```
% bazel build -s :bundle
INFO: Analyzed target //:bundle (142 packages loaded, 3514 targets configured).
INFO: Found 1 target...
SUBCOMMAND: # //:bundle [action 'Action bundle', configuration: 1054a2250c4245b865962919778764c4f205786ff7dd6c61ef877b456d4f1e39, execution platform: @local_config_platform//:host]
(cd /private/var/tmp/_bazel_alexeagle/70a7ea949ae5b7dada65f322bcc74c5f/execroot/__main__ && \
  exec env - \
    BAZEL_NODE_MODULES_ROOTS=:npm \
    COMPILATION_MODE=fastbuild \
    NODE_ENV=production \
  bazel-out/host/bin/external/npm/webpack/bin/webpack.sh build -o bazel-out/darwin_arm64-fastbuild/bin/bundle '--bazel_node_modules_manifest=bazel-out/darwin_arm64-fastbuild/bin/_bundle.module_mappings.json')
INFO: From Action bundle:
asset main.js 27 bytes [emitted] [minimized] (name: main)
./src/index.js 27 bytes [built] [code generated]
webpack 5.66.0 compiled successfully in 92 ms
Target //:bundle up-to-date:
  bazel-bin/bundle
% cat bazel-out/darwin_arm64-fastbuild/bin/bundle/main.js
console.log("hello world");
```

However the `webpack` rule is an instance of `npm_package_bin` which doesn't produce a runfiles object, I think that's why your `sh_binary` doesn't end up with the bundle directory at runtime. As a workaround I could change your BUILD file to end like this

```
filegroup(
  name = "outs",
  srcs = [":bundle"],
)

sh_binary(
  name = "upload",
  srcs = ["script.sh"],
  data = [":bundle", ":outs"],
  args = [
    "$(location :bundle)"
  ]
)
```

and that fixes it.

Surprisingly I think this is a long-standing bug.

**Comment by geoffliu** [comment]
Thanks @alexeagle for the workaround and quick fix! I'm unfamiliar with the project's release cycle, which version should I be looking forward to?

**Comment by alexeagle** [comment]
I'll cut a patch release 4.6.2 this week. We're also about to make 5.0.0 and I'll cherry-pick the fixes from the `stable` branch to that. Either will work.
