### ISSUE TITLE
tags are not propagated from ts_project to validation target

### ISSUE THREAD

**Issue by djmarcin** [bazelbuild/rules_nodejs#3259]
# 🐞 bug report

### Affected Rule

ts_project macro

### Is this a regression?

No

### Description

`tags` such as `manual` are not propagated to the generated `validate_options` rule. This makes it impossible to disable this target from running under wildcard expansion, or to disable things like caching on this target.

They need to be added to [this invocation](https://github.com/bazelbuild/rules_nodejs/blob/9bc681d14ba197752e4770d95bfc524825d6082f/packages/typescript/internal/ts_project.bzl#L742-L757)

## 🔬 Minimal Reproduction

Set `tags = ['manual']` on a ts_project invocation, `bazel build //path/to/target/...`, observe that the validate target is built despite the ts_project being marked manual.

## 🔥 Exception or Error

n/a

## 🌍  Your Environment

any

**Rules_nodejs version:**

<pre>
  <code>
4.6.1
  </code>
</pre>

**Anything else relevant?**

**Comment by mattem** [comment]
Closed via #3260
