### ISSUE TITLE
Output directory missing write permission when using output_dir = True

### ISSUE THREAD

**Issue by geoffliu** [bazelbuild/rules_nodejs#3267]
# 🐞 bug report

### Affected Rule

@npm//webpack, possibly npm_package_bin in general

### Is this a regression?

Not sure

### Description

 A clear and concise description of the problem...

I have a rule that roughly looks like this: 

```
webpack(
  name = "bundle",
  output_dir = True,
  args = [
    "-o",
    "$(@D)",
  ]
...
)
```

In the `bazel-cache/execroot/__main__/bazel-out/k8-fastbuild/bin/` the corresponding output directory has r-xr-xr-x permissions. If I change the rule declaration to

```
webpack(
  name = "bundle",
  outs = ["bundle_out"],
  args = [
    "-o",
    "$@",
  ]
...
)
```

then the output directory has rwxr-xr-x. What's the difference between these two formulations? Is the missing w in the first version intended, or a bug? This is tripping up our build runners when they try to clean cache.

## 🔬 Minimal Reproduction

This is happening on all our webpack rules, so I suspect it's easily repro-able. Happy to provide a minimal repo if needed.

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Arch Linux
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 4.2.2
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 2 18:15:58 2021 (1638468958)
Build timestamp: 1638468958
Build timestamp as int: 1638468958
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
4.6.0
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
That behavior is up to Bazel. The outputs are expected to be read only - I think the bug there is the cleanup script should not rely on write access.

**Comment by geoffliu** [comment]
I see. I suppose it's just surprising that the two formulations have different behaviors. Are the `$(@D)` construct and `output_dir` flag specific to nodejs rules? I didn't see documentation for it in, say, `genrule`.

**Comment by alexeagle** [comment]
https://docs.bazel.build/versions/main/be/make-variables.html#predefined_genrule_variables

The @D is the output directory for all Bazel rules. output_dir Boolean attribute is a rules nodejs convention.

**Comment by geoffliu** [comment]
Thank you!
