### ISSUE TITLE
No such package '@nodejs//': The repository '@nodejs' could not be resolved

### ISSUE THREAD

**Issue by flolu** [bazelbuild/rules_nodejs#3282]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: nodejs_image

### Is this a regression?

Yes, the previous version in which this bug was not present was: 4.6.1

## 🔬 Minimal Reproduction

https://github.com/flolu/nodejs-not-defined

This target causes the error.
```
nodejs_image(
    name = "base_image",
    binary = "server",
    node_repository_name = "nodejs",
)
```

`node_repository_name = "my_node_linux_amd64"` from the [5.0 migration guide](https://github.com/bazelbuild/rules_nodejs/wiki/Migrating-to-5.0#nodejs_image-from-rules_docker) doesn't work either.

## 🔥 Exception or Error

<pre><code>
ERROR: /home/flo/Documents/nodejs-not-defined/app/BUILD.bazel:27:13: no such package '@nodejs//': The repository '@nodejs' could not be resolved: Repository '@nodejs' is not defined and referenced by '//app:base_image.2'
ERROR: Analysis of target '//app:base_image.2' failed; build aborted: Analysis failed
</code></pre>

**Comment by alexeagle** [comment]
I think you missed the first section - build_bazel_rules_nodejs now has starlark module dependencies:

```
load("@build_bazel_rules_nodejs//:repositories.bzl", "build_bazel_rules_nodejs_dependencies")

build_bazel_rules_nodejs_dependencies()
```

**Comment by flolu** [comment]
These dependencies are defined [here](https://github.com/flolu/nodejs-not-defined/blob/4d4dd97a6fe06f5aa2f65881a5a937d7e900e3e7/WORKSPACE#L15).

**Comment by alexeagle** [comment]
Ah, sorry, this was my first attempt to work this morning before coffee kicked in.

https://github.com/bazelbuild/rules_nodejs/blob/5.0.1/e2e/nodejs_image/BUILD.bazel#L20 shows that the `node_repository_name` needs an architecture (the nodejs toolchain is now conditioned on the exec platform rather than the target platform)

**Comment by alexeagle** [comment]
Also as the migration guide says, you need a newer rules_docker. I've asked a googler maintainer to cut a release as there still isn't one that includes our fix commit.

**Comment by alexeagle** [comment]
This patch makes your build work: https://gist.github.com/alexeagle/2001e9e58e261c07461fb05e47a95454

**Comment by flolu** [comment]
Thank you!

**Comment by alexeagle** [comment]
Just to close the loop, we now have a rules_docker release including the change needed for rnj5.
