### ISSUE TITLE
Adding extra acceptable file formats for rollup_bundle

### ISSUE THREAD

**Issue by branks** [bazelbuild/rules_nodejs#3306]
# 🚀 feature request

### Description
Currently the rollup_bundle rule is limiting the acceptable file formats to only "js" and "mjs". This is out of sync with the way the Rollup CLI works as I can pass files of any format there, such as "jsx" and then rely on a Babel plugin to transpile the files for example

### Describe the solution you'd like
I would like to make a minor change to the file here - https://github.com/bazelbuild/rules_nodejs/blob/stable/packages/rollup/rollup_bundle.bzl
changing line 211, 217 and 247 to allow other common formats such as "jsx", "css", "scss", "sass", "ts" and "tsx". 

### Describe alternatives you've considered
As I am new to Bazel, I am proposing this simpler change of just adding those as extra acceptable formats, but a future bigger change could be to allow it to either use a list of formats from a rule attributes, or to look at something like the @rollup/plugin-node-resolve plugin within the rollup config file

**Comment by alexeagle** [comment]
That sounds right, the Bazel rule should permit all legal uses of the rollup cli
