### ISSUE TITLE
Add example using JavaScript

### ISSUE THREAD

**Issue by sberney** [bazelbuild/rules_nodejs#3315]
# 🚀 feature request

### Relevant Rules

All/any

### Description

All of the `examples/` are typescript as far as I can tell

### Describe the solution you'd like

I would appreciate an example using JavaScript only, as I will not be using typescript at all.

### Describe alternatives you've considered

I have searched for many examples, but none of them actually work when I try to use them.
For example, even the create-react-app example here does not work for me unless I `yarn add --dev @bazel/ibazel` to it.

I have a very simple app that uses yarn to install one library. It then runs `index.js`. It doesn't have any transpilation. Using these examples, I can't see how to come up with a simple, understandable setup. I am new to bazel, but I have python working already.

**Comment by mattem** [comment]
What would you like this example to do? JS example for web, node?
Not sure why cra requires the install of `ibazel` again, it's listed as a `devDependency` https://github.com/bazelbuild/rules_nodejs/blob/stable/examples/create-react-app/package.json#L21
