### ISSUE TITLE
ts_project fails to import js_library global type merge declarations when tsconfig is not in workspace root

### ISSUE THREAD

**Issue by patrick-steadman** [bazelbuild/rules_nodejs#3321]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: ts_project, js_library

### Is this a regression?

Unsure.

### Description

When `tsconfig.json`, `node_modules` and `package.json` are located in the workspace root, I can successfully import `d.ts` global namespace type declaration mergin targets using `js_library` as deps of `ts_project`. When these `tsconfig.json` etc. and the targets are moved to a subdirectory, I get errors that indicate the merged declarations are not being included in the typescript program:

```
bazel build //dir:test_server
dir/testServer.ts(8,29): error TS2339: Property 'foo' does not exist on type 'Request<ParamsDictionary>'.
```

## 🔬 Minimal Reproduction
Failing in subdirectory: https://github.com/ptsteadman/deps-typecheck/tree/fail-import-type-declarations

Succeeding when files are in workspace root:
https://github.com/ptsteadman/deps-typecheck/tree/success-type-decs-as-deps

## 🔥 Exception or Error

https://pastebin.com/kgU9G69n

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
  ARM M1 OSX,
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
bazel 5.0.0

  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
4.6.1
  </code>
</pre>

**Anything else relevant?**

Perhaps just a problematic tsconfig? The build succeeds if I include the type declaration targets in srcs but that feels like a hack.

**Comment by alexeagle** [comment]
These

https://github.com/ptsteadman/deps-typecheck/blob/success-type-decs-as-deps/tsconfig.json#L20-L26

start with `./`

which means these

https://github.com/ptsteadman/deps-typecheck/blob/fail-import-type-declarations/dir/tsconfig.json#L20-L26

need to start with `../`

(there has to be a symmetry between the number of segments walked up the tree and the number walked back down, so /dir on the end means you need ../ on the front)

**Comment by alexeagle** [comment]
https://github.com/bazelbuild/rules_nodejs/pull/3126/files is where I've worked on giving better error messaging when rootDirs is malformed. I'll go rebase that and try to get it further if I get some time...

**Comment by patrick-steadman** [comment]
The tsconfig `rootDirs` section is indeed the wrong path in my repro, this was an oversight in creating the repro, I've fixed the paths, pushed to the failing branch.

But after correctly setting paths to `bazel-out` in `rootDirs` I'm still seeing a build failure, but only for the declaration merging / global types, which is the issue we've been having in our project.

```
bazel build //dir:test_server
dir/testServer.ts(8,29): error TS2339: Property 'foo' does not exist on type 'Request<ParamsDictionary>'.
```

So I think this is still an open issue - l'll update the description.

**Comment by patrick-steadman** [comment]
Thanks for looking at the repro, I will continue to try to narrow down the issue.

**Comment by alexeagle** [comment]
Hey @patrick-steadman sorry we never got back to you on this one. We've simplified stuff a lot over in rules_js and are making a strong effort right now to resolve anything filed there to avoid bug bankruptcy!
