### ISSUE TITLE
non-ts input files cause failure for ts_project with non-default root_dir

### ISSUE THREAD

**Issue by cartmanez** [bazelbuild/rules_nodejs#3330]
# 🐞 bug report

### Affected Rule

ts_project

### Is this a regression?

Not sure.

### Description

My ts code requires some json files on runtime. So I supply both ts and json files in srcs for ts_project.
If I use default root_dir(i.e. '.'), that works fine, json files appear in the output.
However, if I set a non-default root_dir, I get an error

## 🔬 Minimal Reproduction
https://github.com/cartmanez/bazel-ts-repo

<pre><code>
# this fails
bazel build //ts-and-json-mix:dist

# this does not, because root_dir is set to '.'
bazel build //ts-and-json-mix:dist-no-root-dir
</code></pre>

## 🔥 Exception or Error

<pre><code>
ERROR: ... output 'ts-and-json-mix/dist/src/file.json' was not created
ERROR: ... Compiling TypeScript project //ts-and-json-mix:dist [tsc -p ts-and-json-mix/tsconfig.json] failed: not all outputs were created or valid
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux archlinux 5.16.9-arch1-1 #1 SMP PREEMPT Fri, 11 Feb 2022 22:42:06 +0000 x86_64 GNU/Linux
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.11.0
Build label: 5.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jan 19 14:08:54 2022 (1642601334)
Build timestamp: 1642601334
Build timestamp as int: 1642601334
  </code>
</pre>

**Rules_nodejs version:**

<pre>
  <code>
5.1.0
  </code>
</pre>

**Anything else relevant?**
Seems like no. Thank you in advance!

**Comment by alexeagle** [comment]
thanks for the repro!

adding `args = ["--listEmittedFiles"]` to your `dist` target shows this output, including the place TS wrote the json file and the place Bazel expected to find it:

```
INFO: From Compiling TypeScript project //ts-and-json-mix:dist [tsc -p ts-and-json-mix/tsconfig.json]:
TSFILE: /home/alexeagle/.cache/bazel/_bazel_alexeagle/df8ac8c6303c857c7c7030efffd3687b/sandbox/linux-sandbox/40/execroot/bazel-ts-repo/bazel-out/k8-fastbuild/bin/ts-and-json-mix/dist/file.json
TSFILE: /home/alexeagle/.cache/bazel/_bazel_alexeagle/df8ac8c6303c857c7c7030efffd3687b/sandbox/linux-sandbox/40/execroot/bazel-ts-repo/bazel-out/k8-fastbuild/bin/ts-and-json-mix/dist/index.js
TSFILE: /home/alexeagle/.cache/bazel/_bazel_alexeagle/df8ac8c6303c857c7c7030efffd3687b/sandbox/linux-sandbox/40/execroot/bazel-ts-repo/bazel-out/k8-fastbuild/bin/ts-and-json-mix/dist/index.js.map
TSFILE: /home/alexeagle/.cache/bazel/_bazel_alexeagle/df8ac8c6303c857c7c7030efffd3687b/sandbox/linux-sandbox/40/execroot/bazel-ts-repo/bazel-out/k8-fastbuild/bin/ts-and-json-mix/dist/index.d.ts
TSFILE: /home/alexeagle/.cache/bazel/_bazel_alexeagle/df8ac8c6303c857c7c7030efffd3687b/sandbox/linux-sandbox/40/execroot/bazel-ts-repo/bazel-out/k8-fastbuild/bin/ts-and-json-mix/dist/index.d.ts.map
ERROR: /home/alexeagle/repros/bazel-ts-repo/ts-and-json-mix/BUILD.bazel:11:11: output 'ts-and-json-mix/dist/src/file.json' was not created
```

The place TypeScript wrote looks right to me (next to the other files) so I think our logic that predicts the output locations must be wrong.

**Comment by alexeagle** [comment]
yeah this is clearly wrong logic
https://github.com/bazelbuild/rules_nodejs/blob/stable/packages/typescript/internal/ts_project.bzl#L173-L184
it needs to use the _out_paths helper like we do for predicting the .js output location
https://github.com/bazelbuild/rules_nodejs/blob/stable/packages/typescript/internal/tslib.bzl#L38
