### ISSUE TITLE
Angular Bazel Monorepo

### ISSUE THREAD

**Issue by herman-rogers** [bazelbuild/rules_nodejs#3333]
# 🚀 feature request

### Description

We didn't see in the examples how to use multi-linker with an angular monorepo so wanted to share our example with the community: https://github.com/herman-rogers/angular-bazel-monorepo

It currently uses (we'll be upgrading it soon):

* Rules Nodejs 4.6.2
* Angular 10

And it shows how to have multiple apps with independent package.json/tsconfigs, how to utilize external first party libraries, and how to utilize shared components across apps. It also shows how to bootstrap legacy AngularJS apps and we're still working on getting legacy component upgrading to work (which is a use case for several enterprises.)

Just wanted to document it here so anyone that was wanting to do something similar could find it.

**Comment by alexeagle** [comment]
Neat, could you send a PR listing your example under https://github.com/bazelbuild/rules_nodejs/blob/stable/docs/examples.md#angular ?
That's easier for users to find than an issue.
