### ISSUE TITLE
Svelte Support

### ISSUE THREAD

**Issue by avarun42** [bazelbuild/rules_nodejs#3355]
# 🚀 Svelte / SvelteKit Support

### Description

I noticed [this line in the docs](https://bazelbuild.github.io/rules_nodejs/examples.html#svelte) while I was searching to find information on Svelte support:
>None yet, please file an issue if you need this.

It would be great to have Svelte/SvelteKit support as I am currently looking to integrate a SvelteKit project with a Bazel monorepo. Thus I am filing an issue as requested.

### Describe the solution you'd like

Implement support for `.svelte` files, running Vite through SvelteKit, and ESM modules.

### Describe alternatives you've considered

There exists an [outdated library](https://github.com/thelgevold/rules_svelte) that seems to have gotten Svelte support partially working, but this repo is a better location for this feature.

**Comment by avarun42** [comment]
SvelteKit 1.0 is released now along with Vite 4, so would be great to get Svelte + Vite + SvelteKit support working as part of bazel.

https://svelte.dev/blog/announcing-sveltekit-1.0

**Comment by gregmagolan** [comment]
rules_nodejs is not actively maintained anymore so this would be a difficult one to get added unless someone steps up to do the work. We (the past maintainers) are making bug fixes and patch releases only at this point.

However, if there was a need for Svelte / SvelteKit support, this is something that would be easier to built on top of [rules_js](https://github.com/aspect-build/rules_js), which is where we are putting all of our efforts going forward.

**Comment by alexeagle** [comment]
@avarun42 do you think your company would be willing to fund this with a feature bounty?
