### ISSUE TITLE
Gatsby build regression in 5.3.0 from 4.4.6

### ISSUE THREAD

**Issue by jarreds** [bazelbuild/rules_nodejs#3378]
# 🐞 Gatsby build regression

### Affected Rule

```python
load("@npm//gatsby-cli:index.bzl", "gatsby")

gatsby(
    name = "public",
    args = [
        "--node_options=--require=./build.js",
        "build",
        "--verbose",
    ],
    chdir = "$(RULEDIR)",
    data = [
        ":package.json",
        ":source",
        "@npm//:node_modules",
    ],
    output_dir = True,
)
```

### Is this a regression?

Yes, this has been working great in 4.4.6, but no longer works in 5.3.0

### Description

As part of the Gatsby build process, it writes a number of files to the bazel-out in a `.cache` dir. It was totally fine writing these files in 4.4.6 but now throws a permission error in 5.3.0.

I'm trying to figure out if this is actually a regression, or something that needs to be worked around now. If so, I'm curious if you all can help figure out how. I'm having a difficult time in the change logs trying to determine what might have changed to cause this.

## 🔥 Exception or Error

<pre><code>
$ bazel build services/console:public

...

  Error: EACCES: permission denied, open '/private/var/tmp/_bazel_users/63162deb
  35ba6b2f678241a64a1d59bb/sandbox/darwin-sandbox/2782/execroot/acme/bazel-ou
  t/darwin_arm64-fastbuild/bin/services/console/.cache/api-runner-browser-plugin
  s.js'
  
  - node:fs:585 Object.openSync
    node:fs:585:3
  
  - node:fs:2153 Object.writeFileSync
    node:fs:2153:35
  
  - initialize.ts:544 initialize
    [acme]/[gatsby]/src/services/initialize.ts:544:6
  
  - index.ts:47 bootstrap
    [acme]/[gatsby]/src/bootstrap/index.ts:47:9
  
  - build.ts:94 build
    [acme]/[gatsby]/src/commands/build.ts:94:53
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS Monterey 12.2.1 M1
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: development
Build label: 5.0.0
Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jan 19 14:16:16 2022 (1642601776)
Build timestamp: 1642601776
Build timestamp as int: 1642601776
  </code>
</pre>

**Rules_nodejs version:**

<pre>
  <code>
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "3ceb1e5b5dcad5fa2ad8870a20201cfbb9c9c63cac4055c9ab370034c765297f",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/5.3.0/rules_nodejs-5.3.0.tar.gz"],
)
  </code>
</pre>

**Comment by alexeagle** [comment]
Hmm, did you already look through the upgrade wiki https://github.com/bazelbuild/rules_nodejs/wiki/Migrating-to-5.0 and the breaking change notes on the 5.0.0 release?

**Comment by alexeagle** [comment]
You'd have to debug what that gatsby tool is trying to do. Maybe it wants to modify files in node_modules?

**Comment by garymm** [comment]
@jarreds where did you add `exports_directories_only = False`?
