### ISSUE TITLE
exports_directories_only && electron npm package

### ISSUE THREAD

**Issue by pgherveou** [bazelbuild/rules_nodejs#3381]
# 🐞 bug report

When exports_directories_only option is True, a ts_project depending on electron  fails with the following output

```python
ts_project(
    name = "lib",
    srcs = ["foo.ts"],
    declaration = True,
    extends = "//:tsconfig.json",
    deps = [
        "@npm//electron",
    ],
)
```
```bash
bazel build :lib
INFO: Invocation ID: 788ae363-a246-434e-9fc5-ad847eded5c6
INFO: Analyzed target //:lib (7 packages loaded, 319 targets configured).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_pgherveou/e8abb188809fb2a68548cb4762974f47/external/npm/BUILD.bazel:557:10: Copying directory external/npm/_/node_modules/electron failed: Exec failed due to IOException: The file type of 'external/npm/_/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework' is not supported.
Target //:lib failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 9.235s, Critical Path: 0.64s
INFO: 12 processes: 12 internal.
FAILED: Build did NOT complete successfully
```
### Affected Rule

noticed while building ts_project rule

### Is this a regression?

Things build fine when exports_directories_dependencies is set to False

## 🔬 Minimal Reproduction

```bash
git clone git@github.com:pgherveou/rules_nodejs_playground.git
bazel build :lib
```
## 🌍  Your Environment

Mac OS Monterey
Apple M1

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: development
Build label: 5.0.0
Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jan 19 14:16:16 2022 (1642601776)
Build timestamp: 1642601776
Build timestamp as int: 1642601776
  </code>
</pre>

**Rules_nodejs version:**

<pre>
  <code>
5.3.0
  </code>
</pre>

**Comment by alexeagle** [comment]
Looks like the electron package contains files with spaces in the name, and exports_directories_only must first copy all the files into an output folder. @gregmagolan known issue?

**Comment by gregmagolan** [comment]
Not an issue I was aware of. Under the hood this is a `copy_file(is_dir = True)` target that is running `cp -rf $from $to`:

https://github.com/bazelbuild/rules_nodejs/blob/stable/third_party/github.com/bazelbuild/bazel-skylib/rules/private/copy_file_private.bzl#L88

**Comment by gregmagolan** [comment]
Ahh. It seems to be dying on `node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework` as it is a symlink pointing to a non-existant file:

```
$ ls -l _/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron\ Framework.framework/Electron\ Framework 
lrwxr-xr-x  1 greg  wheel  35  1 Apr 00:10 _/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework -> Versions/Current/Electron Framework
$ ls -l _/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron\ Framework.framework/Versions/
total 0
drwxr-xr-x  6 greg  wheel  192  1 Apr 00:10 A
```

`cp -rfH` will resolve that `copy_file` failure.

As to why the `Versions/Current` isn't created when npm install runs under bazel I'm not sure. Outside of bazel that file is a symlink

```
 ls -l node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron\ Framework.framework/Electron\ Framework 
lrwxr-xr-x  1 greg  staff  35  1 Apr 00:06 node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework -> Versions/Current/Electron Framework
$ ls -l node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron\ Framework.framework/Versions/
total 0
lrwxr-xr-x  1 greg  staff    1  1 Apr 00:06 Current -> A
```

**Comment by gregmagolan** [comment]
In any case, I'll put up the PR to fix `copy_file(is_dir = True` to use `cp -fRH`

**Comment by gregmagolan** [comment]
For reference, the cp `-r` option is historic and discouraged on macos. It differs from cp `-r` on linux.
https://man7.org/linux/man-pages/man1/cp.1.html
https://ss64.com/osx/cp.html

**Comment by pgherveou** [comment]
Thanks so much for looking into this 🙏

**Comment by fmeum** [comment]
I got hit by this with `taiko` and investigated the root cause a bit further: The symlink points to a directory and thus unlinked in https://github.com/bazelbuild/rules_nodejs/blob/696e134b592fe8543f3a6fa0f8ac683599cbb953/internal/npm_install/generate_build_file.ts#L626. Deleting any directory symlinks seems a bit much and will likely cause issue down the line that are extremely hard to debug as they can't be reproduced outside the Bazel repository rule.

@gregmagolan Given that the Yarn version this is intended as a workaround can be considered ancient by now, could this special handling be removed and the minimum Yarn version increased to inform users about this issue should they still be using it?

**Comment by pgherveou** [comment]
@gregmagolan the fix did not seem to resolve the issue
after updating the deps to the latest version in the repro repo [here](https://github.com/pgherveou/rules_nodejs_playground)
I have the following issue
```
❯ bazel build //:lib --verbose_failures
INFO: Invocation ID: cd7d95fe-fe98-4b0c-ab4f-c64955467958
INFO: Analyzed target //:lib (22 packages loaded, 86 targets configured).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_pgherveou/e8abb188809fb2a68548cb4762974f47/external/npm/BUILD.bazel:541:10: Copying directory external/npm/_/node_modules/electron failed: Exec failed due to IOException: The file type of 'external/npm/_/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework' is not supported.
Target //:lib failed to build
INFO: Elapsed time: 0.185s, Critical Path: 0.02s
INFO: 9 processes: 9 internal.
```

**Comment by fmeum** [comment]
I can also confirm this isn't fixed as per https://github.com/bazelbuild/rules_nodejs/issues/3392.

Removing the `fs.unlink` on directory symlinks in the BUILD file generating script fixed this for me.

**Comment by Kila2** [comment]
maybe use cp -a for macos will reslove this issue

**Comment by Kila2** [comment]
when xcode copy framework it will use buildin-copy.
it imp can found at [Driver.cpp](https://github.com/facebookarchive/xcbuild/blob/dbaee552d2f13640773eb1ad3c79c0d2aca7229c/Libraries/builtin/Sources/copy/Driver.cpp)
so maybe we need use this method instead of `cp -fR`
