### ISSUE TITLE
jasmine_node_test does not currently recognize .cjs spec/test files.

### ISSUE THREAD

**Issue by jstuder-gh** [bazelbuild/rules_nodejs#3400]
# 🐞 bug report

### Affected Rule

jasmine_node_test

### Is this a regression?

No

### Description

jasmine_node_test does not currently recognize cjs spec/test files.

The jasmine test runner script will accept the .cjs file extension but the `_js_sources` rule to gather sources currently does not recognize .cjs files.

## 🔬 Minimal Reproduction

Given the following test file:
<pre><code>
// foo.test.cjs:
describe('spec in file ending with .test.cjs', () => {
  it('should run', () => {
    expect(true).toBe(true);
  });
});
</code></pre>

And this target:

<pre><code>
jasmine_node_test(
    name = "dot_test_cjs_test",
    srcs = ["foo.test.cjs"],
)
</code></pre>

Will fail with no specs found.

## 🔥 Exception or Error

<pre><code>

==================== Test output for //packages/jasmine/test:dot_test_cjs_test:
DEPRECATED: Support for Jasmine versions prior to '4.0.x' is deprecated in '@bazel/jasmine'.
Randomized with seed 13701
Started

No specs found
Finished in 0.002 seconds
Incomplete: No specs found
Randomized with seed 13701 (jasmine --random=true --seed=13701)
================================================================================

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
  Linux x86_64
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
  5.0.0
  </code>
</pre>

**Rules_nodejs version:**

<pre>
  <code>
5.4.0
  </code>
</pre>

**Comment by alexeagle** [comment]
I think it was fixed by #3401 ?
