### ISSUE TITLE
Typescript documentation is confusing

### ISSUE THREAD

**Issue by gonzojive** [bazelbuild/rules_nodejs#3402]
I find it difficult to understand how to use the TypeScript rules to achieve simple things.

Examples:

1) I'd like to write an executable program using TypeScript. Is there a rule for that? Seems like no

2) I have a few files (`base.ts` and `user.ts`). `user.ts` depends on `base.ts`. Should I use one `ts_project` rule for each? `ts_project` and depend on `:base` from the `user` target? It seems very strange to call something a "project" when it is just a single file - is that really the right rule?

3) If I am writing a rule that produces `.ts` files, such as a protobuf code generator, what is the preferred approach?

Also, `ts_library` says it should not be used for new code and has a for a while, which is a bit confusing coming from other languages where the <language>_library rule is the standard way to declare a library. 

I hope this is helpful.

**Comment by matthewjh** [comment]
1. You would chain different rules together to do that. Each rule has a different responsibility.

- ts_project: translates TS -> JS files using the TypeScript compiler
- nodejs_binary: produces an executable that calls into a JS entry point

2. 
"project" is TypeScript terminology. A TypeScript project is a compilation unit of tsc (TypeScript Compiler). Take a look at:

https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

The ts_project rule is just calling tsc with `--project`.

So you would have one ts_project per compilation unit. How you draw this boundary is up to you, but generally you'd want to bundle multiple related files into a single compilation unit. E.g. an app, a library, a microservice, could all be distinct compilation units.

3. I think your rule could expose the TS files as `DefaultInfo` files, which could then be fed into other rules expecting TS files. I've not done this myself though.

---

I agree with your point about `ts_library` vs `ts_project` naming. I suppose the underlying cause, besides the fact that `ts_project` came after `ts_library` and needed a distinct name, is that tsc itself doesn't have the concept of a "library"

**Comment by gonzojive** [comment]
I can answer this myself through experimentation, but I cant't tell from the documentation. Can a ts_project depend on another ts_project? Is this a reasonable way to set up smaller compilation units?

**Comment by matthewjh** [comment]
Yes, that's right.
