### ISSUE TITLE
optionsvalid.d.ts changes across machines

### ISSUE THREAD

**Issue by aptenodytes-forsteri** [bazelbuild/rules_nodejs#3416]
Here, ts_project_options_validator.js writes `process.argv[1]` to the file:

https://github.com/bazelbuild/rules_nodejs/blob/43e478dd48cea53dbcc580da92ccb517534b832d/nodejs/private/ts_project_options_validator.js#L130

For us, this resolves to something like:

```
/home/jenkins_user/local-bazel-output-base/sandbox/linux-sandbox/9011/execroot/<workspace>/bazel-out/host/bin/external/path/to/ts_project_options_validator.js
```

So different build machines might populate the remote cache with different values, or local builds might unnecessarily differ from the remote cache. Does it make sense to remove this absolute path from the `optionsvalid.d.ts` file?

**Comment by fparga** [comment]
Duplicate of https://github.com/bazelbuild/rules_nodejs/issues/3461

**Comment by fparga** [comment]
Fixed by https://github.com/bazelbuild/rules_nodejs/pull/3462

**Comment by aptenodytes-forsteri** [comment]
Glad it's fixed!
