### ISSUE TITLE
`rootDirs` workaround does not work as documented

### ISSUE THREAD

**Issue by jfirebaugh** [bazelbuild/rules_nodejs#3423]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: `ts_project`

### Is this a regression?

No

### Description

The [documentation for `ts_project`](https://bazelbuild.github.io/rules_nodejs/TypeScript.html#ts_project) describes how to set the `rootDirs` compiler option so that TypeScript can resolve relative references to the bazel-out folder. However, this doesn't work as documented in seemingly simple cases. For example, a project with subdirectories `a` and `b` containing respective `ts_project`s, where `a` depends on `b`. Based on the documentation, `a`'s `tsconfig.json` should contain:

```
    "rootDirs": [
      ".",
      "../bazel-out/host/bin/a",
      "../bazel-out/darwin-fastbuild/bin/a",
    ]
```

(Paths for additional host architectures omitted because I'm testing solely on macOS.)

## 🔬 Minimal Reproduction

https://github.com/jfirebaugh/rules_nodejs_test

## 🔥 Exception or Error

```
a/a.ts(1,19): error TS2307: Cannot find module '../b/b' or its corresponding type declarations.
```

## 🌍  Your Environment

**Operating System:** macOS
**Output of `bazel version`:**

<pre>
  <code>
Build label: 5.0.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jan 1 00:00:00 1980 (315532800)
Build timestamp: 315532800
Build timestamp as int: 315532800
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
5.4.0
  </code>
</pre>

**Anything else relevant?**

The following patch allows the project to build successfully, but is contrary to what the documentation suggests:

```
diff --git a/a/tsconfig.json b/a/tsconfig.json
index 99f2666..ccc45c9 100644
--- a/a/tsconfig.json
+++ b/a/tsconfig.json
@@ -3,9 +3,9 @@
     // https://bazelbuild.github.io/rules_nodejs/TypeScript.html#ts_project
     // https://github.com/microsoft/TypeScript/issues/37378
     "rootDirs": [
-      ".",
-      "../bazel-out/host/bin/a",
-      "../bazel-out/darwin-fastbuild/bin/a",
+      "..",
+      "../bazel-out/host/bin",
+      "../bazel-out/darwin-fastbuild/bin",
     ]
   }
 }
```

**Comment by Zemnmez** [comment]
If anyone who has worked on this issue has suggestions on how to debug this when it happens, I'd really appreciate it. Every now and then something breaks with this feature and I lose a lot of time trying to guess what combination of `rootDirs` and paths makes it work.

I've been trying to upgrade to a newer version of the nodejs rules, and have been unable to because I can't make "rootDirs" work. I've been using "paths" which has worked just fine until the more recent versions:

https://github.com/Zemnmez/monorepo/pull/544/commits/2dbbcadc1add25216c385f2b50b64d4c0b0185dc

**Comment by jfirebaugh** [comment]
This isn't an issue with rules_js.
