### ISSUE TITLE
TsConfigInfo memory leak

### ISSUE THREAD

**Issue by Andrius-B** [bazelbuild/rules_nodejs#3430]
# 🐞 bug report

### Affected Rule: ts_config / TsConfigInfo provider
We are having an issue with ts_config consuming absurd amounts of memory, here's the relevant output of `bazel [..] dump --rules`:
```
RULE                                 COUNT     ACTIONS          BYTES         EACH
filegroup                           12,078           0     17,726,232        1,467
java_library                         4,332      13,025     35,065,464        8,09
ts_project                             136         268     14,161,720      104,130
ts_config                              131           0  1,839,281,704   14,040,318
```

### Is this a regression?
no, we are seeing this issue occur on `4.6.3` but reading the sources reveals that it would occur in `stable` as well.

### Description
The problem lies in the implementation of `TsConfigInfo` provider, where `deps` is a `list` instead of a `depset`. This causes artifact duplication which consumes *a lot* of memory, just to be squished down into a `depset` later by the `ts_project` implementation. I've seen the `TsConfigInfo.deps` list get as long as 50M elements, with only ~20 unique elements.

## 🔬 Minimal Reproduction

I have no small sample to reproduce this, but in theory constructing a highly linked tree of `ts_config` rules should show it quite well.

## 🔥 Exception or Error

```
net.starlark.java.eval.Starlark$UncheckedEvalError: OutOfMemoryError thrown during Starlark evaluation (<target>)
        at <starlark>.depset(<builtin>:0)
        at <starlark>.run_node([..]/build_bazel_rules_nodejs/internal/providers/node_runtime_deps_info.bzl:147)
        at <starlark>._ts_project_impl([..]/@bazel/typescript/internal/ts_project.bzl:248)
Caused by: java.lang.OutOfMemoryError: Java heap space
```

## 🌍  Your Environment

**Output of `bazel version`:**

<pre>
  <code>
Build label: 5.1.1
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Apr 8 15:57:36 2022 (1649433456)
Build timestamp: 1649433456
Build timestamp as int: 1649433456
  </code>
</pre>

**Rules_nodejs version:**
`4.6.3`

**Comment by alexeagle** [comment]
Is it fixed now that your PR landed?

**Comment by Andrius-B** [comment]
Yes it is, thanks!
