### ISSUE TITLE
jasmine_node_test fine grained dependencies

### ISSUE THREAD

**Issue by devversion** [bazelbuild/rules_nodejs#344]
When using the `jasmine_node_test` rule, developers currently need to manually specify `@npm//:jasmine` as dependency when using fine-grained dependencies. 

Should this be done automatically with the assumption of `jasmine` being installed? or should there be at least a note for the rule?

**Comment by alexeagle** [comment]
I think the only way it makes sense to do it automatically is if jasmine_node_test uses its own internal version of jasmine that it installs (like the ts_proto_library does with the protobuf.js dependency)

**Comment by gregmagolan** [comment]
This will get resolved with #543. `jasmine_node_test` will be shipped in a `@bazel/jasmine` npm package and will fetch `jasmine` as a transitive dep so a user won't have to explicitly have it in their package.json. By default `jasmine_node_test` will assume `@npm//jasmine` is where it will find jasmine so a user won't have to explicitly add it as a dep to jasmine_node_test.

**Comment by gregmagolan** [comment]
Resolved in 0.26.0 release when using @bazel/jasmine npm package and npm_bazel_jasmine bazel workspace to load jasmine_node_test
