### ISSUE TITLE
Feature request: support entryNames property in esbuild

### ISSUE THREAD

**Issue by paullewis** [bazelbuild/rules_nodejs#3469]
# 🚀 feature request

### Relevant Rules

`esbuild`

### Description

If you build with an esbuild config, you can set the [`entryNames`](https://esbuild.github.io/api/#entry-names) option, per the docs. This option is particularly useful for including the hash in the filename of the generated bundle, and thereby enabling a far-future expiration date on the JS bundle. Without it, the cache headers need to be set to invalidate the file immediately, lest the bundle is updated but the previously cached version served by the HTTP cache.

However, all that said the esbuild rule does not know that the `entryNames` option has been set, and Bazel goes looking for the declared output JS (and sourcemap file), i.e., it goes looking for `foo.js` rather than – say – `foo-abcde123.js`, and the build fails. 

### Describe the solution you'd like

Ideally the esbuild rule would support hashing in the entry point filenames akin to the way it accepts the chunk outputs from esbuild today. I presume, therefore, the esbuild rule would need an extra arg that maps to a predefined `entryNames` arg in `esbuild`.

### Describe alternatives you've considered

An alternative would be a separate build step to hash the JS after esbuild has output it, but it seems a shame when esbuild supports it directly.

**Comment by alexeagle** [comment]
Hey sorry @paullewis I assume you've switched to aspect_rules_esbuild by now?

**Comment by paullewis** [comment]
I have indeed, yes 😄
