### ISSUE TITLE
Error running nodejs_binary from sh_binary

### ISSUE THREAD

**Issue by emspishak** [bazelbuild/rules_nodejs#3505]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: nodejs_binary

### Is this a regression?

 Not that I know of

### Description

 Adding a nodejs_binary as a data dependency of a sh_binary target and then trying to run that nodejs_binary from the shell script results in an error:

```
ERROR: cannot find build_bazel_rules_nodejs/third_party/github.com/bazelbuild/bazel/tools/bash/runfiles/runfiles.bash
```

## 🔬 Minimal Reproduction

See https://github.com/emspishak/nodejs_sh_binary_bug . Clone that repository and run

```
bazel run //my_project:RunNode
```

to see the error.

## 🔥 Exception or Error

<pre><code>ERROR: cannot find build_bazel_rules_nodejs/third_party/github.com/bazelbuild/bazel/tools/bash/runfiles/runfiles.bash
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre><code>macOS 12.4</code></pre>

**Output of `bazel version`:**

<pre><code>Bazelisk version: development
Build label: 5.2.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 7 16:11:03 2022 (1654618263)
Build timestamp: 1654618263
Build timestamp as int: 1654618263</code></pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre><code>5.5.2</code></pre>

**Anything else relevant?**

The missing file (`build_bazel_rules_nodejs/third_party/github.com/bazelbuild/bazel/tools/bash/runfiles/runfiles.bash`) looks like it exists, but is just in a directory called `external`, so it exists at the same path, but you need to add `external/` to the beginning: `external/build_bazel_rules_nodejs/third_party/github.com/bazelbuild/bazel/tools/bash/runfiles/runfiles.bash`

**Comment by aptenodytes-forsteri** [comment]
I have a workaround rule here: https://github.com/emspishak/nodejs_sh_binary_bug/pull/1

**Comment by sacsar** [comment]
I'm afraid I don't have a solution, but I am currently facing a similar issue--trying to run the `protoc-gen-ts_proto` wrapper script gives the same error. What's slightly odd is that I have successfully run the `protoc-gen-ts_proto` binary from a rule before, which makes me think that we're doing something wrong.

Thank you for adding your workaround.

**Comment by gregmagolan** [comment]
This has been solved in rules_js (https://github.com/aspect-build/rules_js) where you can run a js_binary from an sh_test or a genrule.

**Comment by loeffel-io** [comment]
+1

**Comment by loeffel-io** [comment]
thanks @aptenodytes-forsteri 
your workaround works great - this should be merged

**Comment by JeffreyFalgout** [comment]
I ran into this issue and the fix I found was kind of hacky:

Instead of running the nodejs_binary script directly, do `bash -c "source \"${nodejs_binary_script}\"" "$0" "${additional_args[@]}"

the script was failing because it was inspecting `$0`, and `$0` changes if you invoke the shell script directly. With `bash -c`, you can set `$0` to be the same as the source script's
