### ISSUE TITLE
Documentation at https://www.npmjs.com/package/@bazel/typescript/v/0.32.0 is out of date

### ISSUE THREAD

**Issue by Katee** [bazelbuild/rules_nodejs#3511]
The documentation at https://www.npmjs.com/package/@bazel/typescript/v/0.32.0 mentions a few things that are not longer used:

* `ts_setup_workspace` is mentioned. It looks like this was removed with [2.0.0-rc.3 (2020-07-17)](https://github.com/bazelbuild/rules_nodejs/blob/c962f12e06d99230f17d82a732958f3c00c9438e/CHANGELOG.md#200-rc3-2020-07-17)
* `ts_devserver` is mentioned. It looks like this was moved to concatjs in [3.0.0-rc.0 (2020-12-11)](https://github.com/bazelbuild/rules_nodejs/blob/c962f12e06d99230f17d82a732958f3c00c9438e/CHANGELOG.md#300-rc0-2020-12-11)

Possibly other items I'm not aware of.

`ts_setup_workspace` is also mentioned at https://github.com/bazelbuild/rules_nodejs/wiki/scratch

**Comment by mattem** [comment]
That's a versioned URL, for the 0.32.0 package. 
The latest version (https://www.npmjs.com/package/@bazel/typescript) seems to have the correct documentation? 

I think scratch is just that, a scratch pad. I guess we could remove it as it's ~3 years old.

**Comment by Katee** [comment]
I am so sorry. I had been searching for instructions on how to use an absolute path for `ts_project` imports which led me to the ["Writing TypeScript code for Bazel"](https://www.npmjs.com/package/@bazel/typescript/v/0.32.0#user-content-writing-typescript-code-for-bazel) section of that very outdated version. I did not realize that the "Last publish" part of the sidebar on npmjs.com does not refer to the version on is currently looking at.
