### ISSUE TITLE
Bazel@HEAD CI failing with rules_nodejs

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/rules_nodejs#3537]
Related to breaking Bazel change https://github.com/bazelbuild/continuous-integration/issues/1404

Likely because of this repository's dependency on `bazel_toolchains` and `rbe_autoconfig`. May need a fix similar to https://github.com/bazelbuild/rules_proto/pull/134/files for rules_proto

Example failure: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2590#0182aed0-9827-4753-a8b9-988b24c5a354

**Comment by alexeagle** [comment]
Hmm, I thought I had fixed this in https://github.com/bazelbuild/rules_nodejs/pull/2536 :/
