### ISSUE TITLE
How to remove all extra files in esbuild?

### ISSUE THREAD

**Issue by rezass** [bazelbuild/rules_nodejs#3549]
Hi all,

Right now esbuild in Bazel creates lots of extra files to launch the output file. However, if the bundled file is only to be used as a js file on the client-side, there is no need for such files. Is there a way to prevent the creation of such files in esbuild?

![image](https://user-images.githubusercontent.com/8567731/190132535-b52c9247-f0be-4d6d-a175-0b264a519239.png)

Best,
Reza

**Comment by alexeagle** [comment]
No, these other files are just outputs of the rule that you can ignore. If they're getting in your way, it's likely that you're trying to bundle up files by reading bazel-bin yourself. Instead, if you let a Bazel rule like `pkg_tar` do the packaging, it will only collect its declared inputs, and you won't care what other intermediate files exist in bazel-bin.
