### ISSUE TITLE
cmd.exe node-gyp-build - The system cannot find the path specified.

### ISSUE THREAD

**Issue by fnbk** [bazelbuild/rules_nodejs#3575]
# 🐞 bug report

### Affected Rule

npm_install()

### Is this a regression?

no

### Description

**Given** `@parcel\watcher` as a dependency
**When** Executing `<...>/nodejs_windows_amd64/bin/npm.cmd ci`
**Then** the error message `The system cannot find the path specified.` is thrown

The reason is an invalid path in the PATH variable: `C:\\Users\\flori\\_bazel_flori\\lteuwioz\\external\\nodejs_windows_amd64\\bin\\;` **(notice the trailing slashes!)** 

Which part of the software is adding `<...>\\nodejs_windows_amd64\\bin\\;` to the PATH variable?

## 🔬 Minimal Reproduction

package.json
```
{
  "name": "hello-world",
  "dependencies": {
    "@parcel/watcher": "2.0.5"
  }
}
```

WORKSPACE.bazel
```
npm_install(
    name = "npm",
    package_json = "//:package.json",
    package_lock_json = "//:package-lock.json",
    data = [],
)
```

**more details:** https://github.com/fnbk/bazel-build-failure

## 🔥 Exception or Error

<pre><code>
$ C:/users/flori/_bazel_flori/lteuwioz/external/nodejs_windows_amd64/bin/npm.cmd ci

npm ERR! code 1
npm ERR! path C:\repos\fnbk\bazel-build-failure\node_modules\@parcel\watcher
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp-build
npm ERR! The system cannot find the path specified.
</code></pre>

<pre><code>
$ bazel build //:all --verbose_failures
...
43 timing reifyNode:node_modules/node-gyp-build Completed in 56ms
44 timing reifyNode:node_modules/node-addon-api Completed in 67ms
45 timing reifyNode:node_modules/@parcel/watcher Completed in 158ms
46 timing reify:unpack Completed in 158ms
47 timing reify:unretire Completed in 0ms
48 timing build:queue Completed in 1ms
49 timing build:link:node_modules/node-gyp-build Completed in 5ms
50 timing build:link Completed in 5ms
51 info run @parcel/watcher@2.0.5 install node_modules/@parcel/watcher node-gyp-build
52 info run @parcel/watcher@2.0.5 install { code: 1, signal: null }
53 timing reify:rollback:createSparse Completed in 11ms
54 timing reify:rollback:retireShallow Completed in 0ms
55 timing command:ci Completed in 227ms
56 verbose stack Error: command failed
56 verbose stack     at ChildProcess.<anonymous> (C:\Users\flori\_bazel_flori\lteuwioz\external\nodejs_windows_amd64\bin\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
56 verbose stack     at ChildProcess.emit (node:events:390:28)
56 verbose stack     at maybeClose (node:internal/child_process:1064:16)
56 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
57 verbose pkgid @parcel/watcher@2.0.5
58 verbose cwd C:\repos\fnbk\bazel-build-failure
59 verbose Windows_NT 10.0.22000
60 verbose argv "C:\\Users\\flori\\_bazel_flori\\lteuwioz\\external\\nodejs_windows_amd64\\bin\\nodejs\\node.exe" "C:\\Users\\flori\\_bazel_flori\\lteuwioz\\external\\nodejs_windows_amd64\\bin\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--scripts-prepend-node-path=false" "ci"
61 verbose node v16.13.2
62 verbose npm  v8.1.2
63 error code 1
64 error path C:\repos\fnbk\bazel-build-failure\node_modules\@parcel\watcher
65 error command failed
66 error command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp-build
67 error The system cannot find the path specified.
68 verbose exit 1
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Windows 11
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
5.3.1
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
5.7.0
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
I believe we do this path manipulation to ensure that if a NodeJS program spawns a `node.exe` subprocess, it will use the hermetic bazel-managed Node interpreter and not some other one on the machine. Can you fix it just by trimming the trailing slash rather than by removing that altogether?
