### ISSUE TITLE
Support Rollup v3

### ISSUE THREAD

**Issue by sgrishchenko** [bazelbuild/rules_nodejs#3577]
# 🚀 feature request

### Relevant Rules
`npm_install`

### Description

 Package `@bazel/rollup` does not support Rollup v3 according to it's peer dependencies.

### Describe the solution you'd like

 Check migration guide for Rollup v3 and upgrade peer dependencies for `@bazel/rollup`.

### Describe alternatives you've considered

 It is pretty simple task so there is no lots of alternatives here.

**Comment by alexeagle** [comment]
As mentioned in the README, this repo is in maintenance mode now. We'd accept a PR though.
