### ISSUE TITLE
Documentation pages are too simplistic

### ISSUE THREAD

**Issue by gonzojive** [bazelbuild/rules_nodejs#3587]
### Description

I have trouble using the documentation pages such as [this one](https://bazelbuild.github.io/rules_nodejs/Built-ins.html).

- There is no table of contents within a page
- There is no indication of which page I'm viewing relative to other pages. Once I click a link, I must use the back button.

### Describe the solution you'd like

- A menu on the left indicating which page I'm looking at and how it fits into the overall docs.
- Table of contents
- Something more like godoc.org package descriptions.

### Describe alternatives you've considered

none

**Comment by alexeagle** [comment]
I'd recommend using https://docs.aspect.build

We used to have rules_nodejs point users there, but were told to stop after https://github.com/bazelbuild/rules_nodejs/issues/2780

(Also, note per the root README.md that this project isn't maintained much anymore, so feature requests aren't likely to happen)
