### ISSUE TITLE
Add descriptive comment to launcher.sh

### ISSUE THREAD

**Issue by reddaly** [bazelbuild/rules_nodejs#3594]
Sometimes a rules_nodejs-related build target will fail with a cryptic error. The debugging process begins by re-running `bazel build` with `--sandbox_debug`. Often, the script being executed is a generated shell script that seems to be based on [`internal/node/launcher.sh`](https://github.com/bazelbuild/rules_nodejs/blob/stable/internal/node/launcher.sh).

This file is a byzantine shell script with no comment explaining what it does at the top of the file. The FR is for adding a comment at the top to explain its purpose and where to look when encountering the script while debugging.

**Comment by alexeagle** [comment]
Hey @reddaly nice to run into you again.

rules_nodejs isn't maintained anymore, other than the "core" module in the /nodejs subfolder. If someone had time, we'd make it more clear by moving the current `stable` branch to a `5.x` branch and cut a 6.0 with everything else removed...

Probably whatever problem prompted you to debug into the launcher in the first place, is better resolved by working with rules_js, unless there's some reason that migration doesn't work for you. In fact, it has a similar launcher, which is generated but here's a sample of the generated output: https://github.com/aspect-build/rules_js/blob/main/js/private/test/shellcheck_launcher.sh
That one would benefit from better documentation as well.

**Comment by reddaly** [comment]
I hear you on rules_nodejs being deprecated. If the rules_js version is updated, I can update the comment here and submit a PR.

--

Regarding migrating to rules_js, that is the plan, but we're busy :). Having a public example of a rules_ts Angular app with protos would help us move over more efficiently. https://github.com/aspect-build/rules_ts/issues/231
