### ISSUE TITLE
Flag --incompatible_config_setting_private_default_visibility will break rules_nodejs in Bazel 7.0

### ISSUE THREAD

**Issue by keertk** [bazelbuild/rules_nodejs#3603]
Incompatible flag `--incompatible_config_setting_private_default_visibility` will be enabled by default in the next major release (Bazel 7.0), thus breaking rules_nodejs. Please migrate to fix this and unblock the flip of this flag.

The flag is documented here: https://github.com/bazelbuild/bazel/issues/12933.

Please check the following CI builds for build and test results:

- [MacOS, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a208-5a03-4918-80d8-75946af95d75)
- [MacOS, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a208-5a05-4e75-b7e6-74f36f239712)
- [MacOS, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a208-5a08-463f-aa4c-579f71e7efb3)
- [RBE (Ubuntu 16.04, OpenJDK 8)](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a208-5a15-491f-aa11-c7c2f2d70e8f)
- [Ubuntu 18.04, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a208-59f8-4271-93ab-d1d071136539)
- [Ubuntu 18.04, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a208-59fb-4064-b861-fd54fdf338b4)
- [Ubuntu 18.04, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a208-59fd-46e1-8e19-4c296acb10ad)
- [Ubuntu 18.04, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a208-5a00-45d3-8b45-83b816c52307)
- [Windows, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a208-5a0b-4db3-983f-4b3a77f5a211)
- [Windows, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a208-5a10-4d72-b720-ebb0f013f737)
- [Windows, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a208-5a13-4efd-b396-ff2dfc2d14b6)

Never heard of incompatible flags before? We have [documentation](https://docs.bazel.build/versions/master/backward-compatibility.html) that explains everything.
If you have any questions, please file an issue in https://github.com/bazelbuild/continuous-integration.

**Comment by sgowroji** [comment]
We are closing this issue as we can see no errors in the CI https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1536#0188747c-5ad8-4e0d-a2c9-cc845ff4b058
