### ISSUE TITLE
Flag --incompatible_disable_starlark_host_transitions will break rules_nodejs in Bazel 7.0

### ISSUE THREAD

**Issue by keertk** [bazelbuild/rules_nodejs#3613]
Incompatible flag `--incompatible_disable_starlark_host_transitions` will be enabled by default in the next major release (Bazel 7.0), thus breaking rules_nodejs. Please migrate to fix this and unblock the flip of this flag.

The flag is documented here: [bazelbuild/bazel#17032](https://github.com/bazelbuild/bazel/issues/17032).

Please check the following CI builds for build and test results:

- [MacOS OpenJDK11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-cfd1-4a5d-97d1-19169d9a9e82)
- [MacOS OpenJDK11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-cfd4-4f73-8f48-0ffd071cca04)
- [MacOS OpenJDK11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-cfd7-4e9d-9243-220936d8eba2)
- [Ubuntu 16.04 OpenJDK 8](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-cfe7-4cc0-8eb9-829a1ea9d775)
- [Ubuntu 18.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-cfc5-4c8b-b7c4-48232e47fa5b)
- [Ubuntu 18.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-cfc8-4e9f-9d78-ac6a1872d716)
- [Ubuntu 18.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-cfcb-4166-a9e1-6f96475472dc)
- [Ubuntu 18.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-cfce-465d-bcfe-55c87cb58c0e)
- [Windows OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-cfdb-421b-a189-dd7654175852)
- [Windows OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-cfe1-499d-b57f-46461b00e890)
- [Windows OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-cfe4-471d-8309-02cc6d8a78d6)
- [Windows OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-cfde-48e0-8e58-dffd268836af)

Never heard of incompatible flags before? We have [documentation](https://docs.bazel.build/versions/master/backward-compatibility.html) that explains everything.
If you have any questions, please file an issue in https://github.com/bazelbuild/continuous-integration.

**Comment by sgowroji** [comment]
Hi Team, Gentle ping , Can you share any significant update on this issue. Thanks!

**Comment by sgowroji** [comment]
This is not yet fixed. Please update!
