### ISSUE TITLE
[Suggestion] adding support for npm_run / yarn_run

### ISSUE THREAD

**Issue by UlysseM** [bazelbuild/rules_nodejs#362]
Hi,

I mentioned during the bazelcon the usecase of porting existing package.json workflow to bazel, when it's necessary to hook output files into the bazel pipeline, without spending much time on maintaining or refactoring old legacy code.

Our web team is used to npm scripts that produce some artifacts when running "npm run build", and test things using "npm run test".

While we used genrule / sh_test to invoke a shell scripts that imports node and npm into $PATH, before running the command, I think it would be beneficial to have it included by default, to ease the migration with some team.

```
npm_run(
    name = "artifacts",
    srcs = glob(["srcs/**/*"]) + [ "package.json", "bower.js", "whatever.js"],
    data = "@something//:node_modules",
    cmd = "build",
    outs = [ "dist/js/output.js", "dist/css/output.css")],
)
```

Would be the same as running:

```
genrule (
    ...
    cmd = " export PATH=path with node and npm:$$PATH && npm run build",
    outs = [...],
)
```

Additionally, there could be another rule such as npm_run_test and yarn_run_test that would be a bazel test rule, and don't take the input as parameter.

**Comment by alexeagle** [comment]
I think `generate_build_files.sh` could do this by taking every `script` from your `package.json` and generate a target to run it, similar to how we generate a target that does the `npm install`.

**Comment by UlysseM** [comment]
With this method, would we be able to select some "output files" when building the target?

Also, if the target are auto-generated, what would happen if someone runs `bazel test //my_js_package/...` ? Would everything listed in "script" be executed? Some scripts are actually creating an http server that listen to code change, so it would be pretty bad to include these.

**Comment by alexeagle** [comment]
These would be binary (executable) targets, not tests, so they'd only be executed if addressed specifically with `bazel build`.
I'm not sure what output files you would select? The npm script would simply run in the cwd.

**Comment by Globegitter** [comment]
@UlysseM A little bit off topic, but would you be happy to share your way of running jest? We are using jest as well and running it as a `nodejs_test` with a forked jest to fix the symlink issue. The setup is not ideal yet but it does work. Would be curios to hear about other people's approaches.

**Comment by UlysseM** [comment]
@Globegitter Sure, here it is. It's a bit dirty as I played around with it until it worked. The solution involved copying the source file in a new directory.

The sh_test requires two args:
- the first argument being the files/directory that will need to be copied over (which are also listed in data)
- the second is the command that will run within a sandboxed directory. As you can see, I'm running two different tests in the same command (to save on the time it takes to setup the test by copying the files)

Note that the path to _@nodejs//:node/bin/node_ was updated to _@nodejs//:bin/nodejs/bin/node_ from 0.10

```
sh_test(
    name = "test",
    # size mediums adds a 5 minute timeout.
    size = "medium",
    srcs = ["//:bazel-build/node_test_hook.sh"],
    args = [
        # first argument = which file needs to be copied over.
        "{src,package.json,.babelrc,jest,tsconfig.json}",
        # run the following...
        "../external/mypackage_yarn/node_modules/jest/bin/jest.js -c jest/config.js &&" +
        " NODE_ENV=testing ../external/mypackage_yarn/node_modules/mocha/bin/mocha --compilers js:babel-register --timeout 120000 ./src/server/routes_tests",
    ],
    data = glob(["src/**/*"]) + [
        "package.json",
        "jest/config.js",
        ".babelrc",
        "tsconfig.json",
        "@mypackage_yarn//:node_modules",
        "@nodejs//:node/bin/node",
    ],
)
```

and here is the bazel-build/node_test_hook.sh
```
#!/bin/bash                                                                                                                                                                                                                                   

# This script is intended to run javascript unit tests.                                                                                                                                                                                       
# It will:                                                                                                                                                                                                                                    
#  - set the PATH for node (if @nodejs//:node/bin/node is added to the 'data')                                                                                                                                                                
#  - set the NODE_PATH to point to all @***_npm//:node_modules                                                                                                                                                                                
#  - copy the files specified in the first argument into a directory and cd into that directory                                                                                                                                               
#  - run the remaining of the argument using 'bash -c' $*                                                                                                                                                                                     
#                                                                                                                                                                                                                                             
# Notes:                                                                                                                                                                                                                                      
# If you want to copy the content of the directory "src" as well as package.json, you need to pass {src,package.json} as first argument.                                                                                                      
# If you need to run a script that is inside a node_modules passed to this program, simply run:                                                                                                                                               
# ../external/***_npm/node_modules/path/to/my/bin (replace *** by the name of your imported module)                                                                                                                                           

export PATH=`pwd`/external/nodejs/node/bin:$PATH
# add each node_modules to the NODE_PATH list.                                                                                                                                                                                                
export NODE_PATH=$(for modPath in external/*/node_modules; do echo `pwd`/$modPath; done | paste -sd ":" -)

# the CURRENT_DIRECTORY extract the directory of the BUILD.bazel file.                                                                                                                                                                        
CURRENT_DIRECTORY=`echo $TEST_TARGET | cut -d: -f1 | cut -c 3-`

# we are copying the files specified in $1 to the temp directory, and cd-ing into it.                                                                                                                                                         
mkdir temp
bash -c "cp -rL $CURRENT_DIRECTORY/$1 temp"
cd temp

shift
bash -c "$*"
```

**Comment by Globegitter** [comment]
Thanks for sharing that @UlysseM  so you are basically just copying all files from within a bazel invocation to get around the symlink issue with jest. How does performance look for you when doing that? And you also do not have a nice watch-mode for that, right?

**Comment by UlysseM** [comment]
I think most of the performance impact in my scenario comes from importing @myyarn//:node_modules (especially since bazel is running inside a linux docker container on a mac in our case).
The copy operation is fairly fast.

As for watch, I don't think it would be compatible as it only copies once. Unless you want to watch yourself the work directory and copy the change to the tmpdir where the jest watcher works. Since the watch feature is designed for devs anyway, I'd suggest sticking to the 'npm/yarn' command, and using only bazel for builds / ci?

The overall suggestion I'm advocating for is to allow bazel to run scripts that provide the artifacts needed for other bazel rules, as well as allowing test scripts.
It means that the original 'script' would still be callable by yarn / npm.

**Comment by t-rad679** [comment]
@alexeagle 

Hey! Could you describe in more detail how to use `generate_build_file.js` to generate BUILD rules for the scripts in package.json? It doesn't seem to do so on the run of that file triggered by the `yarn_install` rule.

**Comment by alexeagle** [comment]
That's a proposal for an enhancement, where `generate_build_files.js` could look through your "first-party" packages in your repo where you declare your own packages, their dependencies, and scripts. (Another possibility we've discussed is to use Gazelle to generate these build files)

Right now we only generate BUILD files for third-party packages which were installed by your package manager, and only generate targets to reference the `bin` entries or use those packages as dependencies.

**Comment by Toxicable** [comment]
Im not convinced turning the scripts of a package.json into targets is a good idea.  
It's commong in the npm world to have scripts that use a variety of deps such as bash, cmd, npm packages and various system packages.
One of the scripts in our repository is this
`barrelsby --delete --singleQuotes --location all --exclude '.+\\.(spec|d)\\.ts$' -d ./libs/ && rm ./libs/index.ts ./libs/server/index.ts ./libs/browser/index.ts ./libs/common/index.ts `

Which uses `barrelsby` from npm and `rm` from bash, I find it difficult how you'd express these dependancies in a bazel rule.

I understand it would make for an easier migration, but I feel users would never leave this feature and suffer due to performance because of it.
