### ISSUE TITLE
[Bug]: nodejs_binary doesn't set up its node_modules hermetically

### ISSUE THREAD

**Issue by JeffreyFalgout** [bazelbuild/rules_nodejs#3624]
### What happened?

https://github.com/JeffreyFalgout/playground/commit/7812bd97674bf647df8a91a363f234e271e442fc

If I run a nodejs_binary, it doesn't seem to have the right node_modules setup

```
$ bazel run :eslint_sh -- --fix --ext js ${PWD}/foo.js            
...
Oops! Something went wrong! :(

ESLint: 8.22.0

ESLint couldn't find the config "google" to extend from. Please check that the name of the config is correct.

The config "google" was referenced from the config file in "/usr/local/google/home/jfalgout/git/playground/rules_nodejs/NODE_PATH/.eslintrc.yml".

If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.
```

but if I invoke the nodejs_binary shell script with a different `NODE_PATH`, everything works:

```
$ cat eslint_wrapper.sh
...
eslint="${PWD}/$1"
shift

# Call eslint with a $0 it can use.
NODE_PATH="${PWD}/external/npm/node_modules" bash -c "source \"${eslint}\"" "$0" "$@"

$ bazel run //:eslint_sh -- --fix --ext js "${PWD}/foo.js"
(works just fine)
```

### Version

Development (host) and target OS/architectures:

```
$ uname -a
Linux <host> 5.19.11-1rodete1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1rodete1 (2022-10-31) x86_64 GNU/Linux
```

Output of `bazel --version`: 6.0.0

Version of rules_nodejs, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: 5.8.0

node 16.13.2 (although the problem reproduces even if I remove that specific version)

Language(s) and/or frameworks involved: 

### How to reproduce

```shell
Check out and run the commands from https://github.com/JeffreyFalgout/playground/commit/7812bd97674bf647df8a91a363f234e271e442fc
```

**Comment by gregmagolan** [comment]
rules_nodejs doesn't have any active maintainers currently so your issue is not likely to be addressed. I recommend using [rules_js](https://docs.aspect.build/rules/aspect_rules_js) instead which includes a complete re-write of the linker that should solve this problem.

**Comment by JeffreyFalgout** [comment]
> I recommend using [rules_js](https://docs.aspect.build/rules/aspect_rules_js) instead which includes a complete re-write of the linker that should solve this problem.

I was just about to ask that. I'll give it a shot and circle back :)
