### ISSUE TITLE
[Bug]: Why bazel run doesn't launch on windows,/bin/bash: C:/zhuomian/jancsiwebspace/fhbfwior/execroot/jancsi_web_space/bazel-out/x64_windows-fastbuild/bin/LicenseWebManager/start.sh: No such file or directory

### ISSUE THREAD

**Issue by zhengdechang** [bazelbuild/rules_nodejs#3669]
### What happened?

Why bazel run doesn't launch on windows, No such file or directory,but ctrl click ,the file is exist

![image](https://github.com/bazelbuild/rules_nodejs/assets/77528948/ff035bca-7369-4dc7-9ebd-bb7c7510b0f0)

### Version

Development (host) and target OS/architectures: windows

Output of `bazel --version`: 6.0.0

Version of rules_nodejs, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: rules_nodejs-5.8.0

Language(s) and/or frameworks involved:

### How to reproduce

```shell
windows
```

**Comment by alexeagle** [comment]
I have no idea what LicenseWebManager is, that's not provided by rules_nodejs. I'd suggest tracking down where that comes from.

**Comment by alexeagle** [comment]
okay, this doesn't look like a bug in rules_nodejs then, sorry. You can look for user support on slack.bazel.build.
