### ISSUE TITLE
[FR]: Can we backport updated NodeJS versions to v5?

### ISSUE THREAD

**Issue by sharmilajesupaul** [bazelbuild/rules_nodejs#3677]
### What is the current behavior?

I have to update to a new major version v6.0.0 with breaking changes to use [any Node version past v18.15](https://github.com/bazelbuild/rules_nodejs/blob/5.8.3/nodejs/private/node_versions.bzl).

I want to use the next minor version up, `18.16.1`, which should be compatible with v5 of rules_nodejs, I think?

### Describe the feature

It would be great if we could backport compatible Node versions to latest v5 since updating our monorepo to use v6 is a non-trivial task.

**Comment by alexeagle** [comment]
Done, I cut another 5.x release with the updated node versions.
