### ISSUE TITLE
Distribute these rules as a zip file rather than fetch the repo contents

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#368]
A couple reasons:
- we can make the distro smaller (no need to distribute examples for instance)
- the sha256 can be stable (right now it depends on the OS that github runs, which computes the hash when source archive is requested)
- we'll be able to make the vendored node/yarn example more realistic by checking in node, npm, and yarn in our repo. if we did that now, it would make the http_archive for rules_nodejs huge.

**Comment by gregmagolan** [comment]
This was done in #526. We now ship a .tar.gz archive with each release built with the Bazel pkg_tar built-in rule.
