### ISSUE TITLE
[Bug]: `npm_install` modifying the source tree during the build is an antipattern

### ISSUE THREAD

**Issue by joeleba** [bazelbuild/rules_nodejs#3693]
### What happened?

tl,dr: I think modifying the source dir during the build is an antipattern.

# Background

I ran into an issue while trying to build [bazelbuild/buildtools](https://github.com/bazelbuild/buildtools/) with `--experimental_merged_skyframe_analysis_and_execution` (context: Project Skymeld  https://github.com/bazelbuild/bazel/issues/14057). Some actions were reporting missing inputs from the `node_modules` directory.

Without going into too much details, I managed to figure out the issue: compared to the regular version of blaze, Skymeld clears the syscall cache at a different point in time.

Take the following example:

```
WORKSPACE
BUILD
foo/
  a.in
  b.in
```

where `WORKSPACE` contains an instance of `npm_install`.

Assume that there are actions that refer to `node_modules`. When doing `bazel build //foo/...` with bazel at HEAD, this is what happens (chronological order):

| Phase     | What happens                                                                       | State of syscall cache (readdir)                                  |
|-----------|------------------------------------------------------------------------------------|---------------------------------------------------------|
| Loading   | `npm_install` in the `WORKSPACE` file is evaluated and `node_modules` is generated | `{ foo -> [a.in, b.in]}`                                |
| Analysis  | Prepare the actions                                                                | cleared at the end of the analysis phase to save memory |
| Execution | Execute the actions. Will refer to the syscall cache to get the file states.        | `{ foo -> [a.in, b.in, node_modules] }`                 |

The syscall cache is extra-Skyframe and generally assumes that the source doesn't change during the build ([code](https://github.com/bazelbuild/bazel/blob/2067a8b96f624ab5177f3120f802a1255de01ce9/src/main/java/com/google/devtools/build/lib/skyframe/DirectoryListingStateFunction.java#L60-L66)). This `node_modules` directory is generated in the source dir and hence isn't considered "external" either.

So what happens if we *don't* clear the syscall cache after the analysis phase? One would expect a memory regression, but in this case, it's worse: we'll start seeing missing input errors:

| Phase     | What happens                                                                       | State of syscall cache (readdir)                                  |
|-----------|------------------------------------------------------------------------------------|---------------------------------------------------------|
| Loading   | `npm_install` in the `WORKSPACE` file is evaluated and `node_modules` is generated | `{ foo -> [a.in, b.in]}`                                |
| Analysis  | Prepare the actions                                                                | *No* cache clearance |
| Execution | Execute the actions. Will refer to the syscall cache to get the file states **and reports that there's no `node_modules` directory**        | `{ foo -> [a.in, b.in] }`                 |

Disabling the cache clearance: https://github.com/bazelbuild/bazel/commit/54b4c391533399c62f64336ad84701b19390c129

# Proposal

The syscall cache was there only for performance reason, but it accidentally tolerated this behavior. This will not be the case when we switch over to Skymeld mode, because then the syscall cache clearance happens at a different time. 

IMO we have 2 options to move forward:

1. Clear the syscall cache once after the Loading phase, or
2. Reaffirm that bazel rules shouldn't modify the source dir _during_ the build. This essentially means that we revert https://github.com/bazelbuild/rules_nodejs/issues/63.

I believe that (1) is just once more sweeping this problem under the rug and isn't a desirable option, not to mention the potential regression from clearing the syscall cache before the analysis work.

WDYT?

### Version

Development (host) and target OS/architectures: Linux

Output of `bazel --version`: development version

Version of rules_nodejs, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: 4.0.0

Language(s) and/or frameworks involved:

### How to reproduce

```shell
Build bazel from this branch: https://github.com/joeleba/bazel/tree/npm_install_repro


$ cd /tmp
$ git clone git@github.com:joeleba/bazel.git
$ cd bazel
$ bazel build //src:bazel && cp bazel-bin/src/bazel /tmp/bazel -f
```

Clone `bazelbuild/buildtools` and build `...`:

```
$ cd /tmp
$ git clone git@github.com:bazelbuild/buildtools.git`
$ cd buildtools
$ /tmp/bazel build //...
```
```


### Any other information?

_No response_

**Comment by joeleba** [comment]
cc @meisterT @lberki @alexeagle

**Comment by joeleba** [comment]
> @joeleba , how does this exactly cause trouble? Disregarding the inherent ugliness of this, this would only be a problem if the build touched the node_modules/ directory or called readdir() on the top-level directory of the workspace.

In `bazelbuild/buildtools`, there's a [`tsc` target](https://github.com/bazelbuild/buildtools/blob/master/buildozer/npm/BUILD.bazel#L11) that contains a middleman action that refers to files under `node_modules`. Here's a snippet of the failure: 

```
...
ERROR: /usr/local/google/home/leba/.cache/bazel/_bazel_leba/2d48da7e351519dedcec3731f196c474/external/buildozer_npm_deps/typescript/bin/BUILD.bazel:9:14: Middleman _middlemen/external_Sbuildozer_Unpm_Udeps_Stypescript_Sbin_Stsc.sh-runfiles failed: missing input file '@buildozer_npm_deps//:node_modules/typescript/loc/lcl/TRK/TypeScriptLanguageService/Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll.lcl'
ERROR: /usr/local/google/home/leba/.cache/bazel/_bazel_leba/2d48da7e351519dedcec3731f196c474/external/buildozer_npm_deps/typescript/bin/BUILD.bazel:9:14: Middleman _middlemen/external_Sbuildozer_Unpm_Udeps_Stypescript_Sbin_Stsc.sh-runfiles failed: missing input file '@buildozer_npm_deps//:node_modules/typescript/loc/lcl/TRK/TypeScriptTasks/TypeScript.Tasks.dll.lcl'
ERROR: /usr/local/google/home/leba/.cache/bazel/_bazel_leba/2d48da7e351519dedcec3731f196c474/external/buildozer_npm_deps/typescript/bin/BUILD.bazel:9:14: Middleman _middlemen/external_Sbuildozer_Unpm_Udeps_Stypescript_Sbin_Stsc.sh-runfiles failed: missing input file '@buildozer_npm_deps//:node_modules/typescript/package.json'
ERROR: /usr/local/google/home/leba/.cache/bazel/_bazel_leba/2d48da7e351519dedcec3731f196c474/external/buildozer_npm_deps/typescript/bin/BUILD.bazel:9:14: Middleman _middlemen/external_Sbuildozer_Unpm_Udeps_Stypescript_Sbin_Stsc.sh-runfiles failed: 169 input file(s) do not exist
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /usr/local/google/home/leba/.cache/bazel/_bazel_leba/2d48da7e351519dedcec3731f196c474/external/buildozer_npm_deps/typescript/bin/BUILD.bazel:9:14 Middleman _middlemen/external_Sbuildozer_Unpm_Udeps_Stypescript_Sbin_Stsc.sh-runfiles failed: 169 input file(s) do not exist
INFO: Elapsed time: 15.659s, Critical Path: 0.78s
INFO: 132 processes: 115 internal, 17 local.
ERROR: Build did NOT complete successfully
```

Since you mentioned the possibility of adding stuff to MODULE.bazel: cc @meteorcloudy

**Comment by meteorcloudy** [comment]
> Since you mentioned the possibility of adding stuff to MODULE.bazel

I think I mentioned `managed_directories` isn't available in Bzlmod, I don't think Bzlmod can actually help with this issue.

**Comment by lberki** [comment]
`managed_directories` isn't a feature of Bazel anymore :)

But if we want to add a `.bazelignore` analogue, one would have to add that extra symbol.

**Comment by joeleba** [comment]
> Since you mentioned the possibility of adding stuff to MODULE.bazel: cc @meteorcloudy

FWIW, "you" here meant @lberki.

**Comment by joeleba** [comment]
From reading the [doc](https://github.com/aspect-build/rules_js/tree/main/docs#link-the-node_modules), we don't seem to have this problem with `rules_js` because the `node_modules` dir isn't under the source tree.

@alexeagle could you please confirm?

**Comment by joeleba** [comment]
cc @gregmagolan

**Comment by alexeagle** [comment]
Hey sorry we never replied @joeleba - that's correct that rules_js writes only to the output tree. rules_nodejs 6.0.0 fixed this, in the sense that this package manager code no longer exists, the scope is now only to provide a nodejs toolchain.

**Comment by jin** [comment]
I found this issue from https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/buildtool/BuildTool.java;l=414-415;drc=9bf989f6c4f8fb4b463bee07cce7b6f04df8d6e0. @joeleba @alexeagle any idea if it's still needed or can we remove the syscall cache clearing code?
