### ISSUE TITLE
Errors encountered resolving select() keys for //:using_headers_test with Bazel@HEAD

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_nodejs#3702]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3413#018b6494-6644-4a1a-bd98-927e1e1ec4be

Platform : rules_nodejs (ubuntu1804-smoke on :ubuntu: 18.04 LTS (OpenJDK 11, gcc 7.5.0)), rules_nodejs (windows-smoke on :windows: (OpenJDK 11, VS2019)), rules_nodejs (rbe_ubuntu1604-smoke on RBE :ubuntu: 16.04 LTS (OpenJDK 8, gcc 5.4.0))

Logs:
```ERROR: no such package '@[unknown repo 'platforms' requested from @]//os': The repository '@[unknown repo 'platforms' requested from @]' could not be resolved: No repository visible as '@platforms' from main repository
(02:21:16) ERROR: /var/lib/buildkite-agent/builds/bk-docker-zl39/bazel-downstream-projects/rules_nodejs/e2e/smoke/BUILD.bazel:280:10: errors encountered resolving select() keys for //:using_headers_test
(02:21:16) ERROR: Analysis of target '//:using_headers_test' failed; build aborted
```

Steps:
```
git clone -v https://github.com/bazelbuild/rules_nodejs.git && cd e2e/smoke
git reset 00f8569f3c148c35fec2edb73dc3998d2da25db7 --hard
export USE_BAZEL_VERSION=6c02329b1e1c549e916d5b2c77b60fbdd89a5b59
bazel build //...
```

Culprit : [30d033cd7e2153e8b8d7eb034a5323053192ecaa](https://github.com/bazelbuild/bazel/commit/30d033cd7e2153e8b8d7eb034a5323053192ecaa)

CC Greenteam @meteorcloudy

**Comment by sgowroji** [comment]
Hi @alexeagle, Can you have a look at the above issue. Thanks!

**Comment by Wyverald** [comment]
Looks like some missing bazel_deps due to --enable_bzlmod being flipped.

**Comment by sgowroji** [comment]
Above failure is not shown for rules\_nodejs CI. Closing this issue now.
