### ISSUE TITLE
[FR]: rules_nodejs 5.x release line stopped becoming node version updates

### ISSUE THREAD

**Issue by davido** [bazelbuild/rules_nodejs#3703]
### What is the current behavior?

Gerrit Code Review [project](https://gerrit.googlesource.com/gerrit) is still using the latest `rules_nodejs` 5.8.4 distribution.

We would still like to use the latest and greatest node version, e.g. we would like to say just that:

```python
node_repositories(
    node_version = "20.9.0",
)
```

### Describe the feature

Is there a better way, than to patch in place outdated `node_versions.bzl? 

WORKSPACE

```python
http_archive(
    name = "rules_nodejs",
    patch_args = ["-p1"],
    patches = ["//tools:rules_nodejs-5.8.4-node_versions_patch.bzl"],
    sha256 = "8fc8e300cb67b89ceebd5b8ba6896ff273c84f6099fc88d23f24e7102319d8fd",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/5.8.4/rules_nodejs-core-5.8.4.tar.gz"],
)
```

See this CL: [1] for the reference.

[1] https://gerrit-review.googlesource.com/c/gerrit/+/392716

**Comment by alexeagle** [comment]
We don't have an intent to continue maintaining the 5.x branch, we just have automation for HEAD and cut releases from there. Can you upgrade to 6.0?

**Comment by davido** [comment]
> Can you upgrade to 6.0?

Thanks, we will try to update to `rules_nodejs` 6.x or right away to `rules_js`.
