### ISSUE TITLE
BuildFileNotFoundException: no such package '@@[unknown repo 'buildkite_config' requested from @@]//config': The repository '@@[unknown repo 'buildkite_config' requested from @@]' could not be resolved: No repository visible as '@buildkite_config' from main repository


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_nodejs#3713]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3599#018d1aba-e116-47ac-bd22-d9b2ca73bcc5

 Platform: Ubuntu

 Logs: 
```
(04:01:57) ERROR: /var/lib/buildkite-agent/builds/bk-docker-w343/bazel-org-repo-root/rules_nodejs/e2e/smoke/BUILD.bazel:156:8: com.google.devtools.build.lib.packages.BuildFileNotFoundException: no such package '@@[unknown repo 'buildkite_config' requested from @@]//config': The repository '@@[unknown repo 'buildkite_config' requested from @@]' could not be resolved: No repository visible as '@buildkite_config' from main repository
(04:01:57) ERROR: Analysis of target '//:require_acorn' failed; build aborted
```

Bzlmod is enabled by default at HEAD, Requires a fix in the configuration.

Culprit: https://github.com/bazelbuild/bazel/commit/30d033cd7e2153e8b8d7eb034a5323053192ecaa

Steps:
```
git clone -v https://github.com/bazelbuild/rules_nodejs.git 
git reset 9898ac17be19f7a4a268ba7123e969bcc6f693b6 --hard
export USE_BAZEL_VERSION=3e7052824b54158d72e4b07d6330aa41a9857707
cd e2e/smoke
bazel build //... 
```

 CC Greenteam @meteorcloudy

**Comment by sgowroji** [comment]
CC @alexeagle @gregmagolan

**Comment by alexeagle** [comment]
`buildkite_config` doesn't seem like anything in rules_nodejs. Is this something now expected by the Bazel CI?

**Comment by sgowroji** [comment]
@meteorcloudy Can you please guide on the above comments. Thanks

**Comment by meteorcloudy** [comment]
Yes, it's required by Bazel CI to run with RBE. It's defined in one of the smoke test:
https://github.com/bazelbuild/rules_nodejs/blob/9898ac17be19f7a4a268ba7123e969bcc6f693b6/e2e/smoke/WORKSPACE.bazel#L57-L62

However,  in the downstream pipeline, Bzlmod is enabled at HEAD and there is a WORKSPACE.bzlmod file there.
So moving the definition to MODULE.bazel or WORKSPACE.bzlmod could solve this problem.

**Comment by sgowroji** [comment]
Hi @alexeagle, Any update on the above failures ?

**Comment by sgowroji** [comment]
Hi @alexeagle, Above CI is still failing in Downstream, We will be moving it to Disabled CI pipelines until this issue gets fixed. Thanks!

**Comment by sgowroji** [comment]
CI is Green now in [Disabled Pipeline](https://buildkite.com/bazel/bazel-at-head-plus-disabled/builds/2001). Closing this issue now and enabling the [rules\_nodejs](https://github.com/bazelbuild/continuous-integration/pull/1939) in downstream CI
