### ISSUE TITLE
Vue introduces Element-Plus to report error

### ISSUE THREAD

**Issue by liushuai05** [bazelbuild/rules_nodejs#3718]
When I adopted the time of introducing element-plus in the sample vue folder, I encountered the following error:
```
  VITE v3.2.8  ready in 1887 ms

  ➜  Local:   http://127.0.0.1:5173/
  ➜  Network: use --host to expose
✘ [ERROR] Could not resolve "@vue/shared"

    ../../../../node_modules/.aspect_rules_js/element-plus@2.5.6_vue_3.2.45/node_modules/element-plus/es/components/autocomplete/src/autocomplete.mjs:1:41:
      1 │ import { NOOP, isString, isObject } from '@vue/shared';
        ╵                                          ~~~~~~~~~~~~~

  You can mark the path "@vue/shared" as external to exclude it from
  the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@vue/shared"

    ../../../../node_modules/.aspect_rules_js/element-plus@2.5.6_vue_3.2.45/node_modules/element-plus/es/components/calendar/src/calendar.mjs:3:32:
      3 │ import { isArray, isDate } from '@vue/shared';
        ╵                                 ~~~~~~~~~~~~~

  You can mark the path "@vue/shared" as external to exclude it from
  the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@vue/shared"

    ../../../../node_modules/.aspect_rules_js/element-plus@2.5.6_vue_3.2.45/node_modules/element-plus/es/components/input/src/input.mjs:1:25:
      1 │ import { isString } from '@vue/shared';
        ╵                          ~~~~~~~~~~~~~

  You can mark the path "@vue/shared" as external to exclude it from
  the bundle, which will remove this error.

......

```
The details of log are as follows:
[txt.log](https://github.com/bazelbuild/rules_nodejs/files/14382729/txt.log)

i used pnpm i@vue /shared --workspace-root and yarn add@vue /shared neither worked and added the package to BUILD.bazel in the vue folder as well

![image](https://github.com/bazelbuild/rules_nodejs/assets/26994692/771c00d2-d6ef-4a25-aa05-ee1c7538222e)

Hope to get help from veterans.
Thank you very much.

**Comment by jbedard** [comment]
It appears as if you're using https://github.com/aspect-build/rules_js, this repo is primarily only the nodejs toolchain which doesn't seem related to your issue.

My first _guess_ would be a missing dependency declaration in your BUILDs, but I'd need more info such as a repo demonstrating the issue. If you can create a repo to reproduce the issue please open an issue at https://github.com/aspect-build/rules_js
