### ISSUE TITLE
[FR]: Support .nvmrc file in BZLMOD

### ISSUE THREAD

**Issue by BillyBlaze** [bazelbuild/rules_nodejs#3721]
### What is the current behavior?

I am currently migrating from the WORKSPACE file to BZLMOD. In the previous version we could register the toolchain to look for the `.nvmrc` file, such as:

```
nodejs_register_toolchains(
    name = "nodejs",
    use_nvmrc = "//:.nvmrc",
)
```

however in BZLMOD we can only provide the version hardcoded:
```
node = use_extension("@rules_nodejs//nodejs:extensions.bzl", "node")
node.toolchain(node_version = "20.8.0")
```

can we get the new toolchain to also include the `.nvmrc` file?

### Describe the feature

Currently we have a single source of truth that manages the node version in our mono-repo. Without this feature the danger is that people will work locally with a different version than `rules_nodejs` are using. Reading the version from this file will make sure that CI and locally are more closely intertwined.

**Comment by BillyBlaze** [comment]
please dont close 😄

**Comment by setoelkahfi** [comment]
@BillyBlaze  This seems to be working fine for me:
```bazel
bazel_dep(name = "rules_nodejs", version = "6.1.1")
node = use_extension("@rules_nodejs//nodejs:extensions.bzl", "node")
node.toolchain(node_version_from_nvmrc = "//:.nvmrc")
```

[See](https://github.com/bazelbuild/rules_nodejs/blob/4c373209b058d46f2a5f9ab9f8abf11b161ae459/nodejs/extensions.bzl#L51).

**Comment by BillyBlaze** [comment]
@setoelkahfi thank you for the feedback! I didn't notice that this was introduced after my issue. Would've been great that that the closed this issue with a fixed status!
