### ISSUE TITLE
Missing documentation for APIs in @build_bazel_rules_nodejs

### ISSUE THREAD

**Issue by nattySP** [bazelbuild/rules_nodejs#3764]
### What happened?

I understand that @build_bazel_rules_nodejs is deprecated; however, we haven't been able to prioritize migration to rules_js, so we are still using yarn_install.  I was trying to reference the documentation for yarn_install, which I know existed at one point, but now I can't find it anywhere. Is this user error? Or are the old API docs no longer hosted anywhere. Thank you in advance for your help.

### Version

@build_bazel_rules_nodejs

**Comment by gregmagolan** [comment]
The docs you're looking for are in the `/docs` folder on the `5.x` branch of this repository:

https://github.com/bazelbuild/rules_nodejs/tree/5.x/docs

For `yarn_install` in particular: https://github.com/bazelbuild/rules_nodejs/blob/5.x/docs/Built-ins.md#yarn_install

**Comment by gregmagolan** [comment]
Btw, Aspect has helped quite a few companies with their Bazel setups including rules_js migrations for when you prioritize that work. Please feel free to reach out: https://www.aspect.build/services.
