### ISSUE TITLE
Don't use glob() in fine-grained npm deps filegroups

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/rules_nodejs#391]
To improve build times, npm fine-grained deps should enumerate files within npm packages instead of using glob() in the build targtes

/cc @alexeagle @filipesilva

**Comment by Toxicable** [comment]
Pretty sure this was fixed awhile ago.
I don't see any `glob` in https://github.com/bazelbuild/rules_nodejs/blob/master/internal/npm_install/generate_build_file.js#L818

**Comment by gregmagolan** [comment]
Yes. We fixed this a little while ago. 🎉  Thanks.
