### ISSUE TITLE
Rename jasmine_node_test to nodejs_jasmine_test

### ISSUE THREAD

**Issue by haikalpribadi** [bazelbuild/rules_nodejs#394]
Hi, as we can see, the naming convention for the rules in rules_nodejs starts with `nodejs_<...>` (such as `nodejs_binary` and `nodejs_test`. However, `jasmine_node_test` breaks this convention. Before rule names starts getting messier, can we rename `jasmine_node_test` to `nodejs_jasmine_test` to maintain consistency?

**Comment by haikalpribadi** [comment]
We can make a PR for this if the @bazelbuild team thinks it makes sense. cc: @vmax

**Comment by alexeagle** [comment]
Actually we discussed last week in the context of https://github.com/bazelbuild/rules_nodejs/issues/168 that this rule shouldn't have `jasmine` in the name. We don't expose which test runner is used, and this rule could be used to run most node unit tests.

So I think the new name should be `nodejs_unit_test`
/cc @vikerman

We're happy to take a PR for that. The tricky bit will be how to roll this out without breaking users. Probably needs to be available under both names during a transition period of several releases.

**Comment by haikalpribadi** [comment]
Well, I would love just see one test rule, such as `nodejs_unit_test`. However, from what I understand is that there are 3 unit test framework that people use for NodeJS. At @graknlabs we use Jest. So we're (@vmax) also making a PR to add `nodejs_jest_test`. So that means we can just have Jasmine to be the default `nodejs_unit_test`, unless it becomes a higher level rule to wrap all 3 test framework (or any others) and have it accept an argument to select the framework to use. What do you think @alexeagle ?

**Comment by alexeagle** [comment]
Actually this one is named "jasmine_node_test" to match the rule we use internally at Google, so I don't think it's worth renaming it. I do agree that we should have `mocha_test` and `jest_test` rules.
