### ISSUE TITLE
bazel-managed fine grained deps causes lots of time spent eval'ing globs

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#397]
The generated BUILD files use `glob` to gather the input files for each npm package. This is expensive to evaluate in Bazel, and happens at every build execution. Since we can list the contents on disk at the time we generate the BUILD file, we should list individual files in the generated BUILD.

**Comment by gregmagolan** [comment]
Will be resolved when https://github.com/bazelbuild/rules_nodejs/pull/405 lands

**Comment by alexeagle** [comment]
#405 is merged and released.
