### ISSUE TITLE
Remove limitation on single node_modules dependency

### ISSUE THREAD

**Issue by an-kumar** [bazelbuild/rules_nodejs#399]
We can remove the single node_modules limitation by using js_library rather than filegroup in the generates build file, and then simply letting the module resolution override find the module. Are you guys interested in this? It would really help some things, such as being able to develop rules that have their own, encapsulated yarn dependencies, while letting consumers add additional dependencies on top (this came up as a limitation in the development of babel_library).

**Comment by Globegitter** [comment]
@an-kumar The idea is now to have the dependencies as its own npm package - you can see the changes updated in the PR: https://github.com/bazelbuild/rules_nodejs/pull/217, speaking of which could you accept the CLA there?

That aside it still is imo a very interesting proposition :)

**Comment by alexeagle** [comment]
I think this is now covered by our proposal in https://github.com/bazelbuild/rules_nodejs/issues/2121
(we want to discard the "module resolution override" but our linker should be able to set this up
