### ISSUE TITLE
Why is yarn_install preferred over npm_install?

### ISSUE THREAD

**Issue by haikalpribadi** [bazelbuild/rules_nodejs#403]
Hi @gregmagolan and @alexeagle,

In the [README.md#182](https://github.com/bazelbuild/rules_nodejs/blame/master/README.md#L182) you wrote that `yarn_install` is preferred over `npm_install`. Why is that? 

We're migrating our repo to Bazel right now and we have some packages built with Yarn, and some with NPM. We want to just pick one, and we're currently siding with NPM, but we can choose Yarn instead if there are strong benefits on why Bazel prefers Yarn.

Thank you!

**Comment by gregmagolan** [comment]
I believe the main reason is performance. The yarn_install rule will use the global yarn cache by default which makes subsequent yarn installs faster as they can fetch packages from the local cache.  The option is `use_global_yarn_cache` on `yarn_install` which defaults to True. That being said, all our tests are run on both `npm_install` and `yarn_install` and both should work in all cases.

**Comment by alexeagle** [comment]
Another reason is that yarn's lockfile semantics and correctness are a bit better than NPMs.

**Comment by gregmagolan** [comment]
Also this: https://github.com/bazelbuild/rules_nodejs/issues/416
