### ISSUE TITLE
Node launcher does not handle quoted arguments

### ISSUE THREAD

**Issue by devversion** [bazelbuild/rules_nodejs#404]
Considering that we have a `nodejs_binary` that I want to run through Bazel (e.g. `bazel run` or through a `genrule`).

Now if my NodeJS script accepts a lot of CLI arguments which I need to group into a single argument in favor of making it work on Windows (there is an argument limit on windows)

```bash
  C:/Program Files/Git/usr/bin/bash.exe bazel-out/x64_windows-fastbuild/genfiles/src/material-examples/example-module.genrule_script.sh
The command line is too long.

```

So, instead of passing the arguments as individual ones, I now group them into one argument in order to work around this issue:

```bash
 $(location //tools/example-module:bin) --sourceFiles $(SRCS) --outputFile=$@
 # Changed to -->
 $(location //tools/example-module:bin) --sourceFiles "$(SRCS)" --outputFile=$@
```

Now, the `command line is too long` error is gone and it actually runs the `:bin` target which is a `nodejs_binary`. Unfortunately this script (the actual `node_launcher.sh) doesn't work either.

```bash
  C:/Program Files/Git/usr/bin/bash.exe bazel-out/x64_windows-fastbuild/genfiles/src/material-examples/example-module.genrule_script.sh
/usr/bin/bash: -c: line 0: unexpected EOF while looking for matching `"'
/usr/bin/bash: -c: line 1: syntax error: unexpected end of file

```

The `$(SRCS)` resolves into multiple source files (retrieved through a Bazel `glob`). I'm assuming that the `node_launcher.sh` script **somehow expects the arguments to not include any quote.**

**Comment by alexeagle** [comment]
maybe related to https://github.com/bazelbuild/bazel/issues/4778 ?
argument parsing on Windows is a mess

**Comment by DevVersion** [comment]
@alexeagle Based on my understanding it's caused by 

https://github.com/bazelbuild/rules_nodejs/blob/997f2a1d5b531cb8331c8760600ced1853636f23/internal/node/node_launcher.sh#L124

Where it wraps all passed arguments (`$@`) as a single argument. I can have a look into making this better. We should just concat the arguments, rather than wrapping them into a single argument.

**Comment by DevVersion** [comment]
I see how it could be caused by the max length restriction of arguments on Windows, but usually it throws an explicit exception in case the argument limit has been exceeded. I will dig more into it.
