### ISSUE TITLE
Update README to explain why yarn_install is preferred over npm_install

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/rules_nodejs#411]
User asked a question here: https://github.com/bazelbuild/rules_nodejs/issues/403

**Comment by alexeagle** [comment]
fixed in 997f2a1

**Comment by rohansingh** [comment]
FYI, I'm running into the same peer dependency hoisting issue with Yarn. Not a huge problem since it can be worked around, but I don't think the docs are accurate in that regard.
