### ISSUE TITLE
fine grained deps and catch-all deps broken in latest master

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/rules_nodejs#428]
It seems that commit: https://github.com/bazelbuild/rules_nodejs/commit/b5e0774852d2f30d91fc2442c3316e907c51b92b broke something that now we are getting errors like:

```
(14:20:38) ERROR: /home/markus/.cache/bazel/_bazel_markus/c83dd5dc66625baf386a59b750f50a10/external/yarn/BUILD.bazel:20:1: Target '@yarn//:node_modules/.bin/acorn' contains an error and its package is in error and referenced by '@yarn//:node_modules'

(14:28:11) ERROR: /home/markus/.cache/bazel/_bazel_markus/c83dd5dc66625baf386a59b750f50a10/external/yarn/BUILD.bazel:20:1: no such target '@yarn//:node_modules/.bin/url-loader/node_modules/.bin/mime': target 'node_modules/.bin/url-loader/node_modules/.bin/mime' not declared in package ''; however, a source file of this name exists.  (Perhaps add 'exports_files(["node_modules/.bin/url-loader/node_modules/.bin/mime"])' to /BUILD?) defined by /home/markus/.cache/bazel/_bazel_markus/c83dd5dc66625baf386a59b750f50a10/external/yarn/BUILD.bazel and referenced by '@yarn//:node_modules'
```

no matter if I use the `:node_modules` target or fine grained deps. Switch one commit back, to release 0.16.1 fixes fine grained deps but the catch-all `node_modules` target is still broken with basically the same errors.

Just been playing around a bit and removing the line https://github.com/bazelbuild/rules_nodejs/blob/master/internal/npm_install/generate_build_file.js#L114 fixes the catch-all `node_modules` target.

**Comment by gregmagolan** [comment]
Thanks @Globegitter! Something is up with the symlinks in the `.bin` folder for some npm packages it looks like to me. I'll look for a principled fix today.

**Comment by Globegitter** [comment]
no worries and thanks for looking into this @gregmagolan. If you need any more information or a reproduction case I am happy to provide one.

**Comment by gregmagolan** [comment]
@Globegitter Which OS are you building with? A repro case would be helpful. I haven't been able to reproduce it locally yet.

**Comment by Globegitter** [comment]
This is on Ubuntu 18.04 - let me put something up today.

**Comment by gregmagolan** [comment]
This looks related: https://github.com/bazelbuild/rules_nodejs/issues/438

**Comment by gregmagolan** [comment]
@Globegitter Thanks for the repro. On vacation this week but will have a some time to take a look tonight.
