### ISSUE TITLE
Multiple Node versions in a single workspace

### ISSUE THREAD

**Issue by rohansingh** [bazelbuild/rules_nodejs#434]
Right now, `node_repositories` always creates a single `_nodejs_repo` with the name `nodejs`. Is there any particular reason that it doesn't accept a `name` parameter to allow creating multiple `_nodejs_repo` instances?

This would allow having multiple Node versions (say, 8.x and 10.x) in a single project, which is a real-life use case for me.

If this isn't an active design choice or constraint, I'd be happy to work on a PR. It looks like `@nodejs` is only explicitly referenced in a few places, so it should be straightforward to allow overriding it.

**Comment by rohansingh** [comment]
Note that this is different from #167 and #183, which seem to be about being able to configure a Node version. That's something we can do now, but I'd like to be able to use different versions for different targets.

**Comment by gregmagolan** [comment]
Having multiple nodejs versions in a single workspace sounds like a useful feature however we are looking at updating the nodejs rules to use Bazel toolchains for node (https://docs.bazel.build/versions/master/toolchains.html) to support cross-platform remote bazel execution. For example, if you are building on OSX you can still execute actions on GCP (https://blog.bazel.build/2018/10/05/remote-build-execution.html).

Looking at the current code it looks like this shouldn't be too hard to achieve what you'd like at the moment and would be happy to accept a PR if you want to take a shot at it.

We'll be updating to Bazel toolchains for before 1.0 most likely which would invalidate the work but hopefully toolchains will make it easier to achieve this.

**Comment by rohansingh** [comment]
@gregmagolan Do you have a rough idea of the timeline for migrating to toolchains?

If it's later than Q1 then I'll take a look at a PR. Otherwise I'm happy to wait.

**Comment by Toxicable** [comment]
https://github.com/bazelbuild/rules_nodejs/pull/645
tool chain support PR
