### ISSUE TITLE
rollup_bundle in external repository

### ISSUE THREAD

**Issue by mtsgrd** [bazelbuild/rules_nodejs#442]
I'm trying to build a rollup_bundle defined in an external repository. The problem I run into is that the entry point is assumed to be in the user workspace, rather than in the workspace of the target.

When testing out some potential solutions I noticed the following comments in [rollup.config.js](https://github.com/bazelbuild/rules_nodejs/blob/ee218e2a98b9f09ba07cecac8496a5918c47bc5d/internal/rollup/rollup.config.js#L64-L70):

```
  // process.cwd() is the execroot and ends up looking something like
  // /.../2c2a834fcea131eff2d962ffe20e1c87/bazel-sandbox/872535243457386053/execroot/<workspace_name>
  // from that path to the es6 output is
  // <bin_dir_path>/<build_file_dirname>/<label_name>.es6 from there, sources
  // from the user's workspace are under <user_workspace_name>/<path_to_source>
  // and sources from external workspaces are under
  // <external_workspace_name>/<path_to_source>
```

However, to me it looks like sources from the user's workspace are located under `<label_name>.es6` and external sources are found under `<label_name>.es6/external/<external_workspace_name>`. Am I missing something or is this comment out-of-date or inaccurate?

**Comment by gregmagolan** [comment]
Yes. It looks like that comment wrong. I'll fix it up. Thanks for pointing that out.

Can you provide a minimal repro for the rollup_bundle in an external workspace issue?

**Comment by alexeagle** [comment]
We should check if this is reproducible in the new rollup_bundle rule - we dropped a ton of starlark code so I would guess the bug didn't come along with us.
