### ISSUE TITLE
rollup --silent silences build failure errors

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/rules_nodejs#447]
In rollup_bundle rule, --silence is passed to make rollup quiet:

https://github.com/bazelbuild/rules_nodejs/blob/c19ce368f9a06cfc3f529540ab009c6c390e6cd7/internal/rollup/rollup_bundle.bzl#L166-L168

However, rollup is a lovely tool, which populates errors with `onwarn` as well. When `--silent` is specified a build will succeed even if there an error:

> [!] Error: 'render' is not exported by '../../../../../execroot/ws/bazel-out/darwin-fastbuild/bin/src/bundle.es6/external/npm/node_modules/react-dom/index.js'
> Error: 'render' is not exported by '../../../../../execroot/ws/bazel-out/darwin-fastbuild/bin/src/bundle.es6/external/npm/node_modules/react-dom/index.js'
>     at Object.onwarn (/private/var/tmp/_bazel_xiaoyi/2258f168242f85dcc9f2c0d3e9d2258a/execroot/ws/bazel-out/darwin-fastbuild/bin/src/_bundle.rollup.conf.js:138:11)
>     at Object.onwarn (/private/var/tmp/_bazel_xiaoyi/2258f168242f85dcc9f2c0d3e9d2258a/sandbox/darwin-sandbox/1/execroot/ws/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/rollup/rollup.runfiles/build_bazel_rules_nodejs_rollup_deps/node_modules/rollup/bin/rollup:413:50)
>     at Graph.onwarn (/private/var/tmp/_bazel_xiaoyi/2258f168242f85dcc9f2c0d3e9d2258a/sandbox/darwin-sandbox/1/execroot/ws/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/rollup/rollup.runfiles/build_bazel_rules_nodejs_rollup_deps/node_modules/rollup/dist/rollup.js:22136:50)
>     at Graph.warn (/private/var/tmp/_bazel_xiaoyi/2258f168242f85dcc9f2c0d3e9d2258a/sandbox/darwin-sandbox/1/execroot/ws/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/rollup/rollup.runfiles/build_bazel_rules_nodejs_rollup_deps/node_modules/rollup/dist/rollup.js:21884:14)
>     at Module.warn (/private/var/tmp/_bazel_xiaoyi/2258f168242f85dcc9f2c0d3e9d2258a/sandbox/darwin-sandbox/1/execroot/ws/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/rollup/rollup.runfiles/build_bazel_rules_nodejs_rollup_deps/node_modules/rollup/dist/rollup.js:13515:20)
>     at MemberExpression$$1.resolveNamespaceVariables (/private/var/tmp/_bazel_xiaoyi/2258f168242f85dcc9f2c0d3e9d2258a/sandbox/darwin-sandbox/1/execroot/ws/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/rollup/rollup.runfiles/build_bazel_rules_nodejs_rollup_deps/node_modules/rollup/dist/rollup.js:11374:26)
>     at MemberExpression$$1.bind (/private/var/tmp/_bazel_xiaoyi/2258f168242f85dcc9f2c0d3e9d2258a/sandbox/darwin-sandbox/1/execroot/ws/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/rollup/rollup.runfiles/build_bazel_rules_nodejs_rollup_deps/node_modules/rollup/dist/rollup.js:11229:41)
>     at CallExpression.NodeBase.bind (/private/var/tmp/_bazel_xiaoyi/2258f168242f85dcc9f2c0d3e9d2258a/sandbox/darwin-sandbox/1/execroot/ws/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/rollup/rollup.runfiles/build_bazel_rules_nodejs_rollup_deps/node_modules/rollup/dist/rollup.js:9161:23)
>     at CallExpression.bind (/private/var/tmp/_bazel_xiaoyi/2258f168242f85dcc9f2c0d3e9d2258a/sandbox/darwin-sandbox/1/execroot/ws/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/rollup/rollup.runfiles/build_bazel_rules_nodejs_rollup_deps/node_modules/rollup/dist/rollup.js:10219:31)
>     at ExpressionStatement$$1.NodeBase.bind (/private/var/tmp/_bazel_xiaoyi/2258f168242f85dcc9f2c0d3e9d2258a/sandbox/darwin-sandbox/1/execroot/ws/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/rollup/rollup.runfiles/build_bazel_rules_nodejs_rollup_deps/node_modules/rollup/dist/rollup.js:9161:23)

**Comment by alexeagle** [comment]
I think this is incorrect - in the rollup configuration we throw on warnings:

https://github.com/bazelbuild/rules_nodejs/blob/c19ce368f9a06cfc3f529540ab009c6c390e6cd7/internal/rollup/rollup.config.js#L161-L164

Can you supply a repro of a build which incorrectly passes?

**Comment by ashi009** [comment]
If the silent is set, no onwarn will be ever called.

I'll creat a small example to reproduce this.

Alex Eagle <notifications@github.com>于2018年12月5日 周三上午3:30写道：

**Comment by ashi009** [comment]
Reproduced with:

https://github.com/ashi009/rules_nodejs/commit/42afa76c33ebf8e50f42fa0d013144907fe916ac

```shell
$ bazel build examples/bad_rollup:all
INFO: Analysed target //examples/bad_rollup:bundle (1 packages loaded, 3 targets configured).
INFO: Found 1 target...
Target //examples/bad_rollup:bundle up-to-date:
  /private/var/tmp/_bazel_xiaoyi/eda969fcf9c5b50bcd69eeb4b316e301/execroot/build_bazel_rules_nodejs/bazel-out/darwin-fastbuild/bin/examples/bad_rollup/bundle.min.js
  /private/var/tmp/_bazel_xiaoyi/eda969fcf9c5b50bcd69eeb4b316e301/execroot/build_bazel_rules_nodejs/bazel-out/darwin-fastbuild/bin/examples/bad_rollup/bundle.min.js.map
INFO: Elapsed time: 6.956s, Critical Path: 6.70s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 2 processes: 2 darwin-sandbox.
INFO: Build completed successfully, 4 total actions
```

with output:

```js
!function(){"use strict";(void 0)("123")}();
```

**Comment by ashi009** [comment]
This bug has been filed with rollup as well: https://github.com/rollup/rollup/issues/2582

**Comment by alexeagle** [comment]
Thanks for filing the issue with rollup itself - since the bug can be reproduced there, it seems like there's nothing for us to change in rules_nodejs? We already react to the `onwarn` hook so if rollup were calling it, we would do the right thing?

**Comment by ashi009** [comment]
My point stands.  onwarn will NEVER be called as long as --silent is present.  If it's not being called, there is nothing to react on.  Hence, the --silent flag should be removed.

**Comment by ashi009** [comment]
@alexeagle ping?

**Comment by mgechev** [comment]
@ashi009 sorry for the delay. I'll look at this today.
