### ISSUE TITLE
bazel run @yarn//:yarn -- add -dev @bazel/typescript - returns Missing list of pkgs to add

### ISSUE THREAD

**Issue by jlhart** [bazelbuild/rules_nodejs#45]
While working through the Angular Bazel Example: https://github.com/alexeagle/angular-bazel-example, I ran into the following issue.

**Getting an error when running the following:**
`$ bazel run @yarn//:yarn -- add -dev @bazel/typescript`

 **- returns -**

```
INFO: Found 1 target...
Target @yarn//:yarn up-to-date:
  /private/var/tmp/_bazel_jlhart/4d66c7e7add1c81f2c0e9cd3fac1ef83/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/bin/external/yarn/yarn
INFO: Elapsed time: 7.538s, Critical Path: 0.00s

INFO: Running command line: /private/var/tmp/_bazel_jlhart/4d66c7e7add1c81f2c0e9cd3fac1ef83/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/bin/external/yarn/yarn add -dev @bazel/typescript
yarn add v0.22.0
error Missing list of packages to add to your project.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
ERROR: Non-zero return code '1' from command: Process exited with status 1.

```
I was able to get around it by running:
`$ yarn`

I later saw in another post to use:
`$ bazel run @yarn//:yarn -- add -D @bazel/typescript`
which seems to work, but reporting out the error I received above per @alexeagle 

**FYI**
I ran `$ npm install @bazel/ibazel` but could not `$ ibazel build src` 
I finally figured out I had to `$ ./node_modules/.bin/ibazel build src` to get command to run.

**Comment by alexeagle** [comment]
yeah, `yarn add -dev` doesn't work, it needs to be `--dev` or `-D`.
I updated the gist again where I made that mistake.

**Comment by alexeagle** [comment]
Also added a note in the gist about installing ibazel on the $PATH. https://gist.github.com/alexeagle/86ef7edf04d5a953c96cbcc8ad51166f
