### ISSUE TITLE
Rollup emits garbage when using external 

### ISSUE THREAD

**Issue by appsforartists** [bazelbuild/rules_nodejs#450]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule:  `rollup_bundle` (and maybe `ts_library`)

### Description

When importing a function from a node module and using it as a named arg, TypeScript emits invalid syntax, and Rollup chokes on it:

```typescript
dedupe({ areEqual = deepEqual: deepEqual$1 } = {}) {
```

## 🔬 Minimal Reproduction

```typescript
// With just JS
import * as deepEqual from 'deep-equal';

export function dedupe ({ areEqual = deepEqual } = {}) {
  return areEqual(1, 1);
}
```

```typescript
// Or with explicit types:
import * as deepEqual from 'deep-equal';

export type EqualityCheck = (a: any, b: any) => boolean;

export type DedupeArgs = {
  areEqual?: EqualityCheck,
};

export interface WithDedupe {
  dedupe(kwargs?: DedupeArgs): boolean;
}

export class Test implements WithDedupe {
  dedupe({ areEqual = deepEqual } = {}) {
    return areEqual(1, 1);
  }
}

```
 (This issue was discovered in https://github.com/material-motion/material-motion-js/blob/4448ddf256703ded8b1a9621dcd8020cda087c93/packages/core/src/operators/dedupe.ts)

```python
# BUILD
package(
  default_visibility = ["//visibility:public"],
)
exports_files(["package.json"])

load("@build_bazel_rules_typescript//:defs.bzl", "ts_library")
load("@build_bazel_rules_nodejs//:defs.bzl", "rollup_bundle")

ts_library(
  name = "core",
  module_root = "src",
  srcs = glob(
    include = ["src/**/*.ts"],
    exclude = ["**/__tests__/*"],
  ),
  deps = [
    "@npm//@types",
    "@npm//deep-equal",
  ],
  tsconfig = "//:tsconfig.json",
)

rollup_bundle(
  name = "bundle",
  deps = [
    ":package",
    "@npm//@types",
    "@npm//deep-equal",
  ],
  entry_point = "packages/core/src/index",
)
```

## 🔥 Exception or Error

<pre><code>
error TS1005: ',' expected
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS v10.13.6
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
INFO: Invocation ID: 39e5fcfc-211f-450b-9e5f-918df6c12c9f
Build label: 0.20.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Nov 30 14:38:25 2018 (1543588705)
Build timestamp: 1543588705
Build timestamp as int: 1543588705
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>
git_repository(
  name = "bazel_skylib",
  remote = "https://github.com/bazelbuild/bazel-skylib.git",
  tag = "0.6.0",
)

git_repository(
  name = "bazel_gazelle",
  remote = "https://github.com/bazelbuild/bazel-gazelle.git",
  tag = "0.14.0",
)

git_repository(
  name = "io_bazel_rules_go",
  remote = "https://github.com/bazelbuild/rules_go.git",
  tag = "0.15.1",
)

git_repository(
  name = "io_bazel_rules_webtesting",
  remote = "https://github.com/bazelbuild/rules_webtesting.git",
  tag = "0.2.1",
)

git_repository(
  name = "build_bazel_rules_nodejs",
  remote = "https://github.com/bazelbuild/rules_nodejs.git",
  tag = "0.16.2",
)

git_repository(
  name = "build_bazel_rules_typescript",
  remote = "https://github.com/bazelbuild/rules_typescript.git",
  tag = "0.21.0",
)
  </code>
</pre>

**Anything else relevant?**

When I build just the `ts_library` of the reproduction, I see this error:

```
packages/core/src/index.ts:14:10 - error TS4071: Parameter '{ areEqual = deepEqual }' of public method from exported class has or is using name 'DeepEqualOptions' from external module "bazel_test/external/npm/node_modules/@types/deep-equal/index" but cannot be named.
```

When I build `material-motion`'s `ts_library`, I don't see any build errors.  In both cases, `rollup_bundle` builds `:bundle.es6.js` just fine, but chokes on `:bundle`.

**Comment by appsforartists** [comment]
I can work around this issue by delegating to a top-level function, which calls the imported function:

```typescript
import * as deepEqual from 'deep-equal';

function checkWithDeepEqual(a: any, b: any): boolean {
  const check: (a: any, b: any) => boolean = deepEqual;
  return check(a, b);
}

//…
    dedupe({ areEqual = checkWithDeepEqual } = {}) //…
```

**Comment by alexeagle** [comment]
we no longer have built-in downleveling in the new `rollup_bundle` rule, so this is resolved (in the sense that hopefully babel does the right thing, but the problem has moved into user-space)
