### ISSUE TITLE
Jasmine test files should be flexible.

### ISSUE THREAD

**Issue by cnishina** [bazelbuild/rules_nodejs#451]
# 🚀 feature request

Jasmine test file names should be more flexible suffix. I have files that are `*.spec-unit.js` and `*.spec-int.js` that do not work with the bazel build rule because of this filter: https://github.com/bazelbuild/rules_nodejs/blob/master/internal/jasmine_node_test/jasmine_runner.js#L36

My "fix" was to rename my file to end with `*.spec.js`. 

I can come up with a PR with a fix / tests if this makes sense.

**Comment by cnishina** [comment]
(also the rocket emoji is cool...I might have to borrow this)

**Comment by mgechev** [comment]
Makes sense to me. // cc @alexeagle

**Comment by gregmagolan** [comment]
Agree. The current approach is too rigid. The same applies to the karma test rule in rules_typescript and protractor test rule in angular/angular. It could definitely be improved.

**Comment by cnishina** [comment]
Cool. I'll try to get a PR going this week.

**Comment by cnishina** [comment]
Just want a little more discussion on this before I send in my PR.

### Question 1: The character before spec.js or test.js

Looking at the regex, the file must end with `spec.js` with a previous value character that is not alphanumeric. So this means that `some/path/to/test.js` and `some/path/to/spec.js` is are considered tests. Is this the intent?

### Question 2: What should the test suffix look like?

For my "fix", I plan to change the regex to look something like  `(spec|test)((-|_|\.)[a-zA-Z0-9]|)\.js`. So the following file endings would be considered tests:

*spec.fo0.js
*spec-fo0.js
*spec_fo0.js
*spec.js

Is this too limiting to just expect dashes, underscores, and periods? Or is this sound okay?

**Comment by alexeagle** [comment]
I think we might want to expose the regex as an attribute on the rule, so we don't need to correctly anticipate everyone's needs

**Comment by alexeagle** [comment]
let's do this in #513 - we should just be like google3 where `srcs` is specs (and you can have a ts_library target appear in `srcs`)
