### ISSUE TITLE
ESM support in rollup_bundle

### ISSUE THREAD

**Issue by appsforartists** [bazelbuild/rules_nodejs#454]
_Splitting this out from #374, which addressed Common JS._

I would like a browser-compatible ESM/ES6 target for `rollup_bundle`.  I want to be able to write this code:

```typescript
// types.ts
export type ReturnsBoolean: () => boolean;

// yup.ts
import { ReturnsBoolean } from './types';
export const yup: ReturnsBoolean = () => true;

// nope.ts
import { ReturnsBoolean } from './types';
export const nope: ReturnsBoolean = () => false;

// index.ts
export { yup } from './yup';
export { nope } from './nope';
```

and be able to pull this bundle from Rollup:

```typescript
// bundle.js
export const yup = () => true
export const nope = () => false;
```

Perhaps the target should be `:bundle.esm.js`?

Seems to me that downleveling JS versions should be handled by a separate rule (e.g. Closure Compiler), rather than this one.  Can we have a bundle that passes through evergreen JS unconverted, but bundles a `ts_library` into one big ES module?

**Comment by alexeagle** [comment]
Fixed in #580
