### ISSUE TITLE
Control over whether external modules get bundled in rollup_bundle

### ISSUE THREAD

**Issue by appsforartists** [bazelbuild/rules_nodejs#455]
# 🚀 feature request

### Relevant Rules

`rollup_bundle`

### Description

How does an author control what gets inlined and what gets `import`ed when using `rollup_bundle`?

For instance, if I'm building a library for NPM, I probably want to `import` my dependencies, so those libraries are only included once in the final application bundle, even if other libraries use them.

However, if I'm building a final application bundle, or if I'm bundling my library for places like Codepen, I'd want all `import` statements replaced with inline code.

### Describe the solution you'd like

Perhaps the `rollup_bundle` rule should have a `replace_imports` flag that controls whether the `resolve` plugin gets used in `rollup.config.js`.

### Describe alternatives you've considered

`rollup.config.js` has an [`external`](https://rollupjs.org/guide/en#big-list-of-options) field, which lists the individual packages you would like imported.  `rollup_bundle` could have that field and pass it through.

**Comment by alexeagle** [comment]
New rollup_bundle rule lets you do anything rollup can do.
