### ISSUE TITLE
Can't build nodejs_image rule on Windows

### ISSUE THREAD

**Issue by rysteboe** [bazelbuild/rules_nodejs#491]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule:  
`nodejs_image`

### Is this a regression?

I don't know.

### Description

A basic nodejs docker image project builds fine on Linux, but does not on Windows.  Repo link - https://github.com/rysteboe/bazel-testing.  I originally opened a bug here - https://github.com/bazelbuild/rules_docker/issues/643.  

## 🔬 Minimal Reproduction

https://github.com/rysteboe/bazel-testing

## 🔥 Exception or Error

<pre><code>
$ bazel build ...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 16141057-cea0-408c-80e3-0cc9dc5c9b86
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
INFO: Rule 'build_bazel_rules_nodejs' modified arguments {"commit": "ee6f2e3ff1d5806ae864d31d28a7daa99057770f", "shallow_since": "1542735594 -0800"} and dropped ["tag"]
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
INFO: Rule 'bazel_skylib' modified arguments {"commit": "f83cb8dd6f5658bc574ccd873e25197055265d1c", "shallow_since": "1543273402 -0500"} and dropped ["tag"]
Loading: 0 packages loaded
Analyzing: 5 targets (2 packages loaded, 0 targets configured)
Analyzing: 5 targets (13 packages loaded, 3367 targets configured)
Analyzing: 5 targets (28 packages loaded, 3458 targets configured)
INFO: Analysed 5 targets (32 packages loaded, 3575 targets configured).
INFO: Found 5 targets...
[0 / 10] [-----] BazelWorkspaceStatusAction stable-status.txt
ERROR: C:/git/bazel-testing/src/BUILD:12:1: ImageLayer src/testapp-layer.tar failed (Exit 1)
Traceback (most recent call last):
  File "c:\users\rysteboe\appdata\local\temp\Bazel.runfiles_1u9p5p\runfiles\io_bazel_rules_docker\container\build_tar.py", line 423, in <module>
    main(FLAGS(sys.argv))
  File "c:\users\rysteboe\appdata\local\temp\Bazel.runfiles_1u9p5p\runfiles\io_bazel_rules_docker\container\build_tar.py", line 406, in main
    output.add_file(inf, tof, **file_attributes(tof))
  File "c:\users\rysteboe\appdata\local\temp\Bazel.runfiles_1u9p5p\runfiles\io_bazel_rules_docker\container\build_tar.py", line 159, in add_file
    gname=names[1])
  File "c:\users\rysteboe\appdata\local\temp\Bazel.runfiles_1u9p5p\runfiles\bazel_tools\tools\build_defs\pkg\archive.py", line 281, in add_file
    with open(file_content, 'rb') as f:
IOError: [Errno 2] No such file or directory: 'external/nodejs/bin/nodejs/node_modules/npm/test/npm_cache/_cacache/content-v2/sha512/32/c8/6992ba4671408a292bb3f2fae4cd10416dcedb6a214c169054af6bcc792b6ea56f7245333357cc59e4f84660380604b5ff338258ad46973218d864799b5e'
INFO: Elapsed time: 32.788s, Critical Path: 3.51s
INFO: 6 processes: 6 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
</code></pre>

## 🌍  Your Environment

**Operating System:**

Works on 4.18.10 Debian based distro.  Does not work on fully updated Windows 10.

**Output of `bazel version`:**

On Linux:
```
rysteboe@rysteboe:~/code/bazel-testing (master) $ bazel version
INFO: Invocation ID: 90180a26-47ec-4ad3-acca-ed2ace6c3043
Build label: 0.21.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Dec 19 12:58:44 2018 (1545224324)
Build timestamp: 1545224324
Build timestamp as int: 1545224324
```

On Windows:

```
$ bazel version
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 1f794efa-5a63-4356-ab82-6dec8ca7aa50
Build label: 0.21.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Dec 19 12:58:16 2018 (1545224296)
Build timestamp: 1545224296
Build timestamp as int: 1545224296
```

**Rules version (SHA):**

<pre>
  <code>
git_repository(
    name = "build_bazel_rules_nodejs",
    remote = "https://github.com/bazelbuild/rules_nodejs.git",
    tag = "0.16.2",
)
  </code>
</pre>

**Anything else relevant?**

**Comment by filipesilva** [comment]
Heya @rysteboe,

I'm trying to run your repo locally but running into some errors:
```
D:\sandbox\bazel-testing>bazel build ...
INFO: Invocation ID: 2c3e0591-8329-4cc3-8d18-0a85cf5572be
INFO: Rule 'build_bazel_rules_nodejs' modified arguments {"commit": "ee6f2e3ff1d5806ae864d31d28a7daa99057770f", "shallow_since": "1542735594 -0800"} and dropped ["tag"]
INFO: Rule 'bazel_skylib' modified arguments {"commit": "f83cb8dd6f5658bc574ccd873e25197055265d1c", "shallow_since": "1543273402 -0500"} and dropped ["tag"]
ERROR: Analysis of target '//src:testapp.0' failed; build aborted: no such package '@nodejs_image_base//image': Pull command failed: F0111 08:46:55.565000   20392 __main__.py:133] Error pulling and saving image gcr.io/google-appengine/debian9@sha256:741d18b41622814ae6eab29b0679dd45318437998213a5cb5532003846b435e1: executable not found: docker-credential-gcloud
 (C:/Python27/python.exe C:/users/kamik/_bazel_kamik/ic27e6e7/external/puller/file/downloaded --directory C:/users/kamik/_bazel_kamik/ic27e6e7/external/nodejs_image_base/image --os linux --os-version  --os-features  --architecture amd64 --variant  --features  --name gcr.io/google-appengine/debian9@sha256:741d18b41622814ae6eab29b0679dd45318437998213a5cb5532003846b435e1)
INFO: Elapsed time: 41.947s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (28 packages loaded, 241 targets configured)
    Fetching @npm; Restarting. 22s
    Fetching @nodejs_image_base; fetching 18s
```

The important bit seems to be:
```
Error pulling and saving image gcr.io/google-appengine/debian9@sha256:741d18b41622814ae6eab29b0679dd45318437998213a5cb5532003846b435e1: executable not found: docker-credential-gcloud
```

I happen to have `gcloud` and had run `gcloud auth configure-docker` as described in https://github.com/bazelbuild/rules_docker#authentication (we're experimenting with a docker based windows CI for Bazel at https://github.com/angular/angular/pull/27205 so I needed to connect to it). 

When I re-run the docker configure command it shows a couple of warnings about Docker and the credential helper not being on the path, but also that the helpers are already configured. As far as I can tell both docker and the helper are on the path, and I've been able to connect to a private gcloud registry in the last week. 

I also had the same message when configuring a windows VM on gcloud, so I'm guessing it's a path recognition bug in the `gcloud` tools.

```
D:\sandbox\bazel-testing>gcloud auth configure-docker
WARNING: `docker-credential-gcloud` not in system PATH.
gcloud's Docker credential helper can be configured but it will not work until this is corrected.
WARNING: `docker` not in system PATH.
`docker` and `docker-credential-gcloud` need to be in the same PATH in order to work correctly together.
gcloud's Docker credential helper can be configured but it will not work until this is corrected.
gcloud credential helpers already registered correctly.

D:\sandbox\bazel-testing>where docker-credential-gcloud
C:\Users\kamik\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\docker-credential-gcloud.cmd

D:\sandbox\bazel-testing>where docker
C:\Program Files\Docker\Docker\Resources\bin\docker.exe
```

Can you offer me some guidance as to how I can get to the error message you are seeing? Perhaps there's some extra config I am not seeing for `rules_docker`.

Going solely from the trace in your logs, it looks like the build errors out when adding a file to the docker layer:
- Error: `IOError: [Errno 2] No such file or directory: 'external/nodejs/bin/nodejs/node_modules/npm/test/npm_cache/_cacache/content-v2/sha512/32/c8/6992ba4671408a292bb3f2fae4cd10416dcedb6a214c169054af6bcc792b6ea56f7245333357cc59e4f84660380604b5ff338258ad46973218d864799b5e'`
- File is added in https://github.com/bazelbuild/rules_docker/blob/1e4ac0fd141652ce9032cf6ce1a571b46187cf07/container/build_tar.py#L139-L146

This file seems to load a manifest and add files to a docker layer. If I had to bet, somewhere in rules_nodejs we have either a bad path or a missing file that eventually gets picked up by rules_docker. But I can't debug further since I can't get the image to be pulled and that stops the build.

**Comment by meteorcloudy** [comment]
Hmm, the build succeeded on my machine.
```
pcloudy@pcloudy0-w MSYS ~/workspace/others_test/bazel-testing
$ bazel version
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
C:\Users\pcloudy/.bazelrc
INFO: Invocation ID: 796a532d-2ff0-4ab7-9a34-d1cb56b1096e
Build label: 0.21.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Dec 19 12:58:16 2018 (1545224296)
Build timestamp: 1545224296
Build timestamp as int: 1545224296

pcloudy@pcloudy0-w MSYS ~/workspace/others_test/bazel-testing
$ bazel build //src:testapp
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
C:\Users\pcloudy/.bazelrc
INFO: Invocation ID: bb045fc9-39a1-4e81-9768-b4d7dedaed3e
INFO: Reading 'startup' options from c:\users\pcloudy\.bazelrc: --output_user_root=C:/src/tmp
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=320
INFO: Options provided by the client:
  'build' options: --python_path=C:/python_27_amd64/files/python.exe
INFO: Reading rc options for 'build' from c:\users\pcloudy\.bazelrc:
  'build' options: --curses=yes --color=yes --verbose_failures --announce_rc
INFO: Analysed target //src:testapp (31 packages loaded, 3576 targets configured).
INFO: Found 1 target...
Target //src:testapp up-to-date:
  C:/src/tmp/qbnoydju/execroot/bazel_testing/bazel-out/x64_windows-fastbuild/bin/src/testapp-layer.tar
INFO: Elapsed time: 7.038s, Critical Path: 5.01s
INFO: 16 processes: 16 local.
INFO: Build completed successfully, 45 total actions

pcloudy@pcloudy0-w MSYS ~/workspace/others_test/bazel-testing
$ bazel build ...
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
C:\Users\pcloudy/.bazelrc
INFO: Invocation ID: deb840de-af43-459b-843d-8487b6642474
INFO: Reading 'startup' options from c:\users\pcloudy\.bazelrc: --output_user_root=C:/src/tmp
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=320
INFO: Options provided by the client:
  'build' options: --python_path=C:/python_27_amd64/files/python.exe
INFO: Reading rc options for 'build' from c:\users\pcloudy\.bazelrc:
  'build' options: --curses=yes --color=yes --verbose_failures --announce_rc
INFO: Analysed 5 targets (1 packages loaded, 0 targets configured).
INFO: Found 5 targets...
INFO: Elapsed time: 1.602s, Critical Path: 0.27s
INFO: 2 processes: 2 local.
INFO: Build completed successfully, 11 total actions

pcloudy@pcloudy0-w MSYS ~/workspace/others_test/bazel-testing
```

@filipesilva I don't have `docker-credential-gcloud` installed, but I didn't get the error...

**Comment by filipesilva** [comment]
Well that's interesting... not only didn't you get the ` executable not found: docker-credential-gcloud` credential error, you didn't even get the original `No such file or directory` error.

Thanks for trying it! The plot thickens...

I can image the `No such file or directory` error being related to some race condition though. The missing file (`external/nodejs/bin/nodejs/node_modules/npm/test/npm_cache/_cacache/content-v2/sha512/32/c8/6992ba4671408a292bb3f2fae4cd10416dcedb6a214c169054af6bcc792b6ea56f7245333357cc59e4f84660380604b5ff338258ad46973218d864799b5e
`) is part of npms cache proper. It might be there at one point and gone on the other.

**Comment by meteorcloudy** [comment]
@rysteboe What is your output base? You can find out by `bazel info output_base`
It could be `<output_base> + external/nodejs/bin/nodejs/node_modules/npm/test/npm_cache/_cacache/content-v2/sha512/32/c8/6992ba4671408a292bb3f2fae4cd10416dcedb6a214c169054af6bcc792b6ea56f7245333357cc59e4f84660380604b5ff338258ad46973218d864799b5e` exceeded the path limit on Windows (260 characters).

**Comment by meteorcloudy** [comment]
On my machine the full path is `c:/src/tmp/qbnoydju/external/nodejs/bin/nodejs/node_modules/npm/test/npm_cache/_cacache/content-v2/sha512/32/c8/6992ba4671408a292bb3f2fae4cd10416dcedb6a214c169054af6bcc792b6ea56f7245333357cc59e4f84660380604b5ff338258ad46973218d864799b5e`, which is 235 character, I guess that's why I didn't get the problem.

**Comment by filipesilva** [comment]
On mine it is `C:/users/kamik/_bazel_kamik/ic27e6e7`. So that plus the path is 254, which should not be a problem under that hypothesis.

**Comment by meteorcloudy** [comment]
@filipesilva So you didn't get the `No such file or directory` error, right?

**Comment by filipesilva** [comment]
I never got to that point since my build failed with `executable not found: docker-credential-gcloud`.

**Comment by meteorcloudy** [comment]
I see, I have no idea about the `docker-credential-gcloud` issue, @rysteboe can you help with this?

**Comment by rysteboe** [comment]
```
$ bazel info output_base
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 2dfb83d3-74a0-4e75-8497-0ec9948b5b6a
C:/users/rysteboe/_bazel_rysteboe/bav76du7
```

That path would put me at precisely 260 characters (going by @filipesilva's math and our relative bases).  

I'm not sure about the `docker-credential-gcloud` bit.  I've never seen that issue.  Is one of gcloud under your user PATH and the other under system?  I don't know a ton about Windows dev, I only use it under protest right now :).

**Comment by meteorcloudy** [comment]
@rysteboe Does using a shorter output base fix the `No such file or directory` error? 
Try `bazel --output_user_root=c:/tmp build ...`

**Comment by rysteboe** [comment]
Well, funnily enough, that now gives me the same error @filipesilva was getting.  If I go back to running `bazel build ...`, I get the original error, though.  I believe then that you're correct and it's a path length issue (and that I now get to figure out what's going on with the docker credentials).

**Comment by filipesilva** [comment]
@meteorcloudy is there guidance from Bazel about the windows path length limit? The official [Windows API document](https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file#maximum-path-length-limitation) mentions and "extended-length path for a maximum total path length of 32,767 characters".

**Comment by meteorcloudy** [comment]
In Python 2, to use the extended-length path, you have to add a `\\?\` prefix to the absolute path. See https://stackoverflow.com/questions/1365797/python-long-filename-support-broken-in-windows

In Python3, you don't have to do that. But looks like the python scripts used in this rule doesn't run with Python 3 yet.

**Comment by laszlocsomor** [comment]
This seems to work for me now, even with Bazel 0.21.0.
We have a matching bug open for Bazel: https://github.com/bazelbuild/bazel/issues/7082

Can we close these bugs?

**Comment by laszlocsomor** [comment]
Ping

**Comment by filipesilva** [comment]
I wasn't able to verify the original error at the time because of the gcloud thing. @rysteboe can you try to reproduce again?

**Comment by alexeagle** [comment]
Seems this isn't reproducible and went stale, closing.
