### ISSUE TITLE
Report progress of yarn_install & npm_install with new repository_ctx.report_progress() API

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/rules_nodejs#498]
repository_ctx.report_progress() added in Bazel 0.21.0: https://docs.bazel.build/versions/0.21.0/skylark/lib/repository_ctx.html#report_progress

This will be a breaking change as it will mean checking for a minimum version of Bazel 0.21.0 in downstream projects. Maybe add a `nodejs_setup_workspace()` function that calls `check_bazel_version("0.21.0")` that is to be called in downstream WORKSPACES?

//cc @alexeagle 

Reference: https://github.com/bazelbuild/rules_nodejs/pull/493#issuecomment-453237790

**Comment by alexeagle** [comment]
Can't `node_repositories` check for the version first? why add a new function for users to call?

**Comment by alexeagle** [comment]
yeah node_repositories already has check_bazel_version. I'll pick this one up
