### ISSUE TITLE
Trouble with finding a dependency

### ISSUE THREAD

**Issue by rysteboe** [bazelbuild/rules_nodejs#500]
# 🐞 bug report

### Affected Rule

`nodejs_binary`

### Is this a regression?

 I don't know.

### Description

Bazel isn't picking up a particular dependency.  I don't know if it's a problem with my code or a problem with Bazel (it's probably a problem with my code).  

## 🔬 Minimal Reproduction

https://github.com/rysteboe/bazel-testing

Command - `bazel run //src:testapp`

## 🔥 Exception or Error

<pre><code>
[Tue Jan 15 2019 15:29:54 GMT-0500 (Eastern Standard Time)] ERROR Cannot load adapter slack - Error: //src:testapp_bin cannot find module 'hubot-slack' required by '/usr/local/google/home/rysteboe/.cache/bazel/_bazel_rysteboe/d151203673b1f0feda017d408013da70/execroot/bazel_testing/bazel-out/k8-fastbuild/bin/src/testapp.runfiles/npm/node_modules/hubot/src/robot.js'
  looked in:
    built-in, relative, absolute, nested node_modules - Error: Cannot find module 'hubot-slack'
    runfiles - Error: Cannot find module '/usr/local/google/home/rysteboe/.cache/bazel/_bazel_rysteboe/d151203673b1f0feda017d408013da70/execroot/bazel_testing/bazel-out/k8-fastbuild/bin/src/testapp.runfiles/hubot-slack'
    npm/node_modules - Error: Cannot find module '/usr/local/google/home/rysteboe/.cache/bazel/_bazel_rysteboe/d151203673b1f0feda017d408013da70/execroot/bazel_testing/bazel-out/k8-fastbuild/bin/src/testapp.runfiles/npm/node_modules/hubot-slack'
    node_modules attribute (npm/node_modules) - Error: Cannot find module '/usr/local/google/home/rysteboe/.cache/bazel/_bazel_rysteboe/d151203673b1f0feda017d408013da70/execroot/bazel_testing/bazel-out/k8-fastbuild/bin/src/testapp.runfiles/npm/node_modules/hubot-slack'
</code></pre>

## 🌍  Your Environment

**Operating System:**

4.18.0 Debian based distro.  

**Output of `bazel version`:**

<pre>
  <code>
INFO: Invocation ID: fd2d58ab-d996-480a-bc5d-62122ed43dc1
Build label: 0.21.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Dec 19 12:58:44 2018 (1545224324)
Build timestamp: 1545224324
Build timestamp as int: 1545224324
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "aed1c249d4ec8f703edddf35cbe9dfaca0b5f5ea6e4cd9e83e99f3b0d1136c3d",
    strip_prefix = "rules_docker-0.7.0",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.7.0.tar.gz"],
)

git_repository(
    name = "build_bazel_rules_nodejs",
    remote = "https://github.com/bazelbuild/rules_nodejs.git",
    tag = "0.16.5",
)
  </code>
</pre>

**Anything else relevant?**

**Comment by aiuto** [comment]
Can you share your WORKSPACE file?

**Comment by alexeagle** [comment]
Sorry, I started investigating this a few days ago but was on a mobile. Now I'm on a plane and can't download the large node_modules you checked into the example project.

What is the text `Cannot load adapter slack` coming from? Does something call node.js to execute code that was compiled by Bazel? I didn't see anything wrong in your sources from a couple minutes of looking, but there might be a separate nodejs process started by some tool.

**Comment by rysteboe** [comment]
@aiuto It's in the repo - https://github.com/rysteboe/bazel-testing/blob/master/WORKSPACE

@alexeagle - That's the error that is given when the slack module can't be found.  At least I'm pretty sure?  I really don't write much node code.  If it's helpful, I'll create a second project (probably tomorrow, have some personal stuff going on today) that contains a stripped down version of this same app that doesn't use Bazel.

**Comment by rysteboe** [comment]
Sorry for forgetting to respond here.  I did some more investigating a couple of days ago, and this may be unrelated to Bazel.  I'm going to close this out until I get a chance to verify that next week.
