### ISSUE TITLE
native git_repository rule is deprecated

### ISSUE THREAD

**Issue by filipesilva** [bazelbuild/rules_nodejs#510]
When using Bazel 0.21 and following https://github.com/bazelbuild/rules_nodejs#installation, the following error will be displayed:

```
ERROR: error loading package '': Encountered error while reading extension file 'package.bzl': no such package '@build_bazel_rules_nodejs//': The native git_repository rule is deprecated. load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository") for a replacement.
```

**Comment by Toxicable** [comment]
Looks like this is fixed
import statement here
https://github.com/bazelbuild/rules_nodejs/blob/b366e0e0ca6deb03040aa97791ca7fcb8a036d6b/packages/typescript/WORKSPACE#L3

**Comment by kylecordes** [comment]
@alexeagle BTW I love all the deprecation warnings from Buildifier, have been updating code as fast as I see it.
