### ISSUE TITLE
Setting up out-of-workspace Bazel-managed dependencies

### ISSUE THREAD

**Issue by jmsdncn** [bazelbuild/rules_nodejs#514]
I am having trouble getting a brand new project set up with out-of-workspace Bazel-managed dependencies.  As near as I can tell, the only difference between setting up in-workspace and out-of-workspace Bazel-managed dependencies is whether or not the `package_json` parameter is specified when calling `node_repositories()` in my `WORKSPACE`.  Everything seems to work properly with in-workspace dependencies (where `node_repositories(package_json = ["//:package.json"])` is used): I have a Gist demoing that [here](https://gist.github.com/jmsdncn/04b01e349f058e4748af8f2189e40709).

However, when I remove that parameter, as [documented on `node_repositories()`](https://github.com/bazelbuild/rules_nodejs/blob/c200d2906b8ee54e116b22aa637de95a266b3cbc/internal/node/node_repositories.bzl#L513), the `@npm` repository is never created and `bazel run @nodejs//:yarn` turns into a no-op, seemingly making it impossible to actually download dependencies.  A Gist demoing this is [here](https://gist.github.com/jmsdncn/504b2fde492df4aff65747ceccd75354).

One thing that stands out to me is that `bazel run @nodejs//:yarn` executes the script `<bazel-root>/external/nodejs/bin/yarn_node_repositories`, which, in the in-workspace setup, ends with the lines:

```
echo Running yarn --cwd "/home/jd/pg/bazel-nodejs-demo" "$@"
"$SCRIPT_DIR/node" "$SCRIPT_DIR/yarnpkg/bin/yarn.js" --cwd "/home/jd/pg/bazel-nodejs-demo" "$@"
```

In the out-of-workspace setup, these two lines are missing, and as a result, the script is a no-op (it never actually runs `yarn`).  The `<bazel-root/external/nodejs/bin/yarn` script does run `yarn`, but I can't figure out the Bazel incantation to execute that script instead.

**Comment by alexeagle** [comment]
Sorry this never got a reply! I'm guessing it's obsolete now, if not please open a new issue.
I'm not sure what you mean by "out-of-workspace" and "in-workspace" - we don't use those terms in the docs anywhere.
If bazel manages the dependencies, you need to use an `npm_install` or `yarn_install` rule to invoke the package manager.
