### ISSUE TITLE
error with generate_build_file after 0.16.6 upgrade

### ISSUE THREAD

**Issue by Toxicable** [bazelbuild/rules_nodejs#522]
# 🐞 bug report

### Affected Rule
looks like `yarn_install`

### Is this a regression?
Yes, worked fine on 0.16.5

## 🔥 Exception or Error
<pre><code>STDERR:
fs.js:115
    throw err;
    ^
Error: ENOENT: no such file or directory, unlink 'node_modules/inquirer/node_modules/rxjs/src/BUILD.bazel'
    at Object.unlinkSync (fs.js:949:3)
    at pkg._files.pkg._files.filter.file (/home/f.wiles/.cache/bazel/_bazel_f.wiles/80a5e956c9d02d1550a20ced5bc75f3d/external/npm/generate_build_file.js:433:10)</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>$lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>INFO: Invocation ID: dab40f53-da4b-4763-b6c8-8bd7f4e2272a
Build label: 0.21.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Dec 19 12:58:44 2018 (1545224324)
Build timestamp: 1545224324
Build timestamp as int: 1545224324  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>

  </code>
</pre>

**Anything else relevant?**

**Comment by gregmagolan** [comment]
I don't have a reproduction but I suspect it has to do with a broken symlink in the nested node_modules folder. Can you try using this commit of rules_nodejs? If that doesn't fix it then I'll try to reproduce.

```
http_archive(
    name = "build_bazel_rules_nodejs",
    urls = ["https://github.com/gregmagolan/rules_nodejs/archive/5fbd76f11823507e42e949622d56d9635f0ffc21.zip"],
    strip_prefix = "rules_nodejs-5fbd76f11823507e42e949622d56d9635f0ffc21",
)
```

**Comment by Toxicable** [comment]
Same error but different root cause
your hash:
```
Error: ENOENT: no such file or directory, lstat 'node_modules/inquirer/node_modules/rxjs/src/BUILD.bazel'
```
with 0.16.6
```
Error: ENOENT: no such file or directory, unlink 'node_modules/inquirer/node_modules/rxjs/src/BUILD.bazel'
```

**Comment by gregmagolan** [comment]
Thanks. One more thing to try if you don't mind. This should fix it:

```
http_archive(
    name = "build_bazel_rules_nodejs",
    urls = ["https://github.com/gregmagolan/rules_nodejs/archive/c66b1d3dd619fad4365851762a6b3b3115101e4d.zip"],
    strip_prefix = "rules_nodejs-c66b1d3dd619fad4365851762a6b3b3115101e4d",
)
```

Although I'll still want to find a reproduction to figure out why that file is no longer there.

**Comment by Toxicable** [comment]
Looks like that solved that issue but now we're getting:
```
ERROR: /home/f.wiles/.cache/bazel/_bazel_f.wiles/.../external/npm/node_modules/rxjs/BUILD.bazel:200:1: Target '@npm//node_modules/rxjs:webSocket/index.js'
 contains an error and its package is in error and referenced by '@npm//node_modules/rxjs:rxjs__files'
ERROR: /home/f.wiles/.cache/bazel/_bazel_f.wiles/.../external/npm/node_modules/rxjs/BUILD.bazel:200:1: Target '@npm//node_modules/rxjs:webSocket/package.j
son' contains an error and its package is in error and referenced by '@npm//node_modules/rxjs:rxjs__files'
...
```

**Comment by gregmagolan** [comment]
@Toxicable, this should fix it https://github.com/bazelbuild/rules_nodejs/pull/523. 

Can you verify on your end with:

```
http_archive(
    name = "build_bazel_rules_nodejs",
    urls = ["https://github.com/gregmagolan/rules_nodejs/archive/16b0f8386d30b77179d81ee2372ff6b96311490f.zip"],
    strip_prefix = "rules_nodejs-16b0f8386d30b77179d81ee2372ff6b96311490f",
)
```

Thanks!

**Comment by Toxicable** [comment]
Yup that's fixed it, thanks @gregmagolan
