### ISSUE TITLE
Multiple yarn_installs

### ISSUE THREAD

**Issue by solomatov** [bazelbuild/rules_nodejs#549]
# 🐞 bug report
### Affected Rule
yarn_install

### Description
I want to have multiple yarn_installs in my workspace. I have 

```
yarn_install(
  name = "npm_1",
  ..
)

yarn_install(
  name = "npm_2",
  ..
)
```
When I take a look the output directory, there're no such things in external dir, only npm

**Comment by Globegitter** [comment]
That should work just fine, do you have an example repository?

**Comment by solomatov** [comment]
No, I don't. I can create one.

**Comment by solomatov** [comment]
Here's the repo where you can reproduce everything: https://github.com/solomatov/bazel-nodejs-bug-repo

**Comment by alexeagle** [comment]
the error `Not a regular file:/bazel-nodejs-bug-repo/b/package.json` indicates that this file doesn't exist.
```
$ ls b
package..json  yarn.lock
```
you can see the file is called `package..json` (two dots)

**Comment by solomatov** [comment]
My bad. Sorry for this.

I fixed it and still have problems:

BUILD.bazel:14:1: no such package '@npm2//react': Traceback (most recent call last):
Could not find peer dependency 'typescript' of 'tsutils'
 and referenced by '//:b'
ERROR: Analysis of target '//:b' failed; build aborted: no such package '@npm2//react': Traceback (most recent call last):

**Comment by gregmagolan** [comment]
@solomatov The issue as far as I can tell is that you're missing the  `"typescript": "3.3.3"` dependency in `/b/package.json`. This deps is required as @bazel/typescript doesn't depend on it directly. This is intentional since @bazel/typescript works with multiple version of typescript.
That should fix your problem but please re-open this issue if it doesn't.

**Comment by solomatov** [comment]
@gregmagolan Thank you very much for your help!
