### ISSUE TITLE
[ts_proto_library] - Editor support 

### ISSUE THREAD

**Issue by Toxicable** [bazelbuild/rules_nodejs#561]
# 🚀 feature request

### Relevant Rules
`ts_proto_library`

### Description
Currently `ts_proto_library` produces `.js` generated code and `.d.ts` files to match those, which works well from the perspective of the compiler but for devs it makes for a bad experience since your editor will highlight those imports as errors because you're importing files which don't exist at dev time. This means you loose all type support for any of the apis and interfaces used from your proto files

### Describe the solution you'd like
`ts_proto_library` should generate `.d.ts` files into your source directory instead of output so they can be used at dev time.

### Describe alternatives you've considered
An alternative would be to manually write interfaces to match the proto files you've written, but then whats the point of using it in the first place?

**Comment by thesayyn** [comment]
I agree with @Toxicable 
I think we can write a tsserver plugin to provide type information about proto files
