### ISSUE TITLE
[ts_proto_library] - Does not support Nodejs

### ISSUE THREAD

**Issue by Toxicable** [bazelbuild/rules_nodejs#562]
# 🐞 bug report

### Affected Rule
ts_proto_library

### Is this a regression?
Nope

### Description
The module format of the code generated is not usable in a Nodejs environment due to it being AMD module format, where as Nodejs expects CommonJS.

From looking at the docs: https://github.com/dcodeIO/ProtoBuf.js/#pbts-for-typescript
They don't appear to support different modules so either a preprocessing step to change the module format is required to changing the protobufjs lib itself to support other module code generation.

## 🔬 Minimal Reproduction
https://github.com/angular/universal/pull/1003

## 🔥 Exception or Error
Error: `ReferenceError: define is not defined`

This is the generated code: 
<pre><code>define('nguniversal/modules/grpc-engine/src/engine_proto_ts', ["protobufjs/minimal"], function($protobuf) {
    "use strict"'
    var $Reader = $protobuf.Reader, $Writer = $protobuf.Writer, $util = $protobuf.util;</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>Mac OS X</code>
</pre>

**Output of `bazel version`:**

<pre><code>Build label: 0.20.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Dec 19 01:10:31 2018 (1545181831)
Build timestamp: 1545181831
Build timestamp as int: 1545181831</code></pre>

**Rules version (SHA):**

<pre>
  <code>

  </code>
</pre>

**Anything else relevant?**

**Comment by qzmfranklin** [comment]
There is a simple fix to this issue.

You just need to tweak the following line in `ts_proto_library.bzl`:

```bzl
def _run_pbjs(actions, executable, output_name, proto_files, suffix = '.js',
              wrap = 'amd', amd_name = ''):
```

Change `amd` to `default` and it will work.

I am thinking of upstreaming my changes here. Just have not got enough priorities yet. If it works for you and there is a strong interest, please feel free to bring up a PR.

**Comment by qzmfranklin** [comment]
FYI, our team has been using this trick for a few months and it served us well.

**Comment by KingDarBoja** [comment]
Just to update, the `ts_proto_library` has been moved on PR #1159. 

New path to [ts_proto_library.bzl](https://github.com/bazelbuild/rules_nodejs/blob/master/packages/labs/src/protobufjs/ts_proto_library.bzl).

Cheers!
