### ISSUE TITLE
generate_build_files: create Bazel dependency for "dynamic" npm dependency

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#569]
Here's the repro:
https://github.com/alexeagle/repro_ts398/commits/master

from https://github.com/bazelbuild/rules_typescript/pull/398

**Comment by gregmagolan** [comment]
@alexeagle does your `dynamic_deps` in npm_install / yarn_install resolve this?

**Comment by alexeagle** [comment]
yes, thanks, this is done and documented
