### ISSUE TITLE
feature request: support using this rule in its source format

### ISSUE THREAD

**Issue by qzmfranklin** [bazelbuild/rules_nodejs#571]
What I want:

Git add this repo as a submodule in my repo, say, under `third_party/rules_typescript`.

Add a line in `WORKSPACE`:
```
local_repository(path='third_party/rules_typescript')
```

And it should just work.

But right now this is impossible. Something in this repo (or its dependencies) would break if I do that. I have been forced to use this rule via `yarn add @bazel/typescript`, which has a few undesirable consequences:

1. relying on running `yarn/npm` from the command line breaks the hermetcity of the build
2. `bazel` cannot run at all until `yarn` is finished, which prevents the use of `yarn_install/npm_install` (defined and recommended in rules_nodejs)
3. if I ever need to make a change to the source code of rules_typescript (for example, to make the ts_proto_library generate modules in commonjs format rather than amd format), I would have to patch the file under `node_modules/@bazel/typescript` *after* `yarn/npm` is run. This is just, ..., outrageous.

Given the above use cases, I'd like to request a feature to support using this bazel rule in its source format on top of as published artifact.

**Comment by mattem** [comment]
Added example in #2056 for using rules_nodejs from source
