### ISSUE TITLE
HMR/hot module reload support

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/rules_nodejs#581]
# 🚀 feature request

### Relevant Rules

`ts_devserver`, `webpack_bundle` and `rollup_bundle`, possibly also `http_server` and `history_server`

### Description

It seems to becoming more and more standard to have hmr/hot module reload support for the dev workflow rather than livereload. The benefit here being that the page does not have to be fully reloaded which in itself usually already safes time but it also allows for deeper integration with the js frameworks being used to e.g. keep the state of components on reload further allowing for a 'nicer' development experience.

### Describe the solution you'd like

I have investigated a little bit into this and there are existing solutions with one of the most popular being from webpack, but I have not really evaluated if that binds one to use webpack or if it is possible to use this as a standalone server and plug in any kind of pre-existing build pipeline. Other than that I have just found smaller projects but again I have not done a fully considered evaluation for possible solutions for this.

### Describe alternatives you've considered

The workaround we are currently making use of and I have seen some other people also make use of, is just create a `nodejs_binary` which calls e.g. the webpack cli which then handles the whole bundling as well as serving via hmr itself, which works well enough but leaves out any kind of real bazel integration and misses out e.g. on bazel caching and also can lead to some issues since now we are watching the symlinks created in the runfiles tree.

**Comment by wimzyLive** [comment]
+1 for this feature request

**Comment by eordano** [comment]
+1 -- I'd look into webpack's live reloading protocol and try to emulate what it does:
https://github.com/webpack/webpack/tree/master/hot
