### ISSUE TITLE
yarn_install logs to stdout, breaks bazel query

### ISSUE THREAD

**Issue by JaredNeil** [bazelbuild/rules_nodejs#583]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: `yarn_install`

### Is this a regression?

No

### Description

The `yarn_install` repository action outputs logging info to stdout when `quiet=False`.
This breaks using the output from a `bazel query` command if the workspace actions have not run already.

## 🔬 Minimal Reproduction

1. Checkout master (currently 5c5d52fd) on https://github.com/angular/angular-bazel-example
2. Run the following commands:
```
bazel clean --expunge
T1=$(bazel query 'kind(ng_module, //...)')
echo $T1
T2=$(bazel query 'kind(ng_module, //...)')
echo $T2
```
3. Note that the yarn install logging appears in the output of the first query (`T1`).

## Example
```
~/code/angular-bazel-example$ bazel clean --expunge
INFO: Invocation ID: a331d265-45ea-4cc1-9715-df1401ba35d6
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
~/code/angular-bazel-example$ T1=$(bazel query 'kind(ng_module, //...)')
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 97bde3aa-cd64-487d-93dc-2c4c02b1b084
INFO: SHA256 (https://github.com/bazelbuild/bazel-skylib/archive/d7c5518fa061ae18a20d00b14082705d3d2d885d.zip) = bb6f842f7f9ac9d4e5ef9092ba44a8d76520978d0ff3f730f26d7f8aa9343e5d
INFO: SHA256 (https://github.com/bazelbuild/rules_go/releases/download/0.16.3/rules_go-0.16.3.tar.gz) = b7a62250a3a73277ade0ce306d22f122365b513f5402222403e507f2f997d421
Loading: 17 packages loaded
~/code/angular-bazel-example$ echo $T1
yarn install v1.12.1 [1/4] Resolving packages... [2/4] Fetching packages... [3/4] Linking dependencies... [4/4] Building fresh packages... Done in 0.37s. //src:src //src/todos:todos //src/hello-world:hello-world //src/material:material
~/code/angular-bazel-example$ T2=$(bazel query 'kind(ng_module, //...)')
INFO: Invocation ID: daeb26a7-5d68-4657-ada7-b3c94b5239fd
Loading: 0 packages loaded
~/code/angular-bazel-example$ echo $T2
//src:src //src/todos:todos //src/hello-world:hello-world //src/material:material
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>
1f6d878a9ea3a095291f66e3d1a0f6b4641f5159
  </code>
</pre>

**Anything else relevant?**

Workaround is to use the `quiet` option, but then you don't see the install at all.

**Comment by Globegitter** [comment]
Yep I can verify that, but I can not think of a nicer workaround myself and I wonder if rules_nodejs can even do anything real about it or if this should get escalated to bazel itself. For background, the quiet option is one that bazel provides for executing commands in workspace rules, so any workspace rule that would set `quiet` to `False` would be affected by this issue.

One thing that does make things a bit better if you use rules_nodejs version after `44ffc554ad7c7f83827eb41d83e41028cf669c5f` and still have `quiet=False` then you will get a better progress message provided by bazel itself.

**Comment by alexeagle** [comment]
I agree that this is a Bazel issue, repository rules log to stdout so you can't assume you'll get only bazel query output when redirecting the output of bazel query. Not sure what they could do to fix it, aside from make the bazel query do the install and then fail with a prompt that you have to run it again, or write all repository rule logging to stderr.
Could one of you file it upstream?

**Comment by alexeagle** [comment]
Lets follow up on https://github.com/bazelbuild/bazel/issues/8077 - I don't think there's anything we can do to fix it here.
