### ISSUE TITLE
rollup example should be consistent with program example

### ISSUE THREAD

**Issue by mattmoor** [bazelbuild/rules_nodejs#59]
It is confusing that `program` has a `WORKPACE`, but `rollup` does not.

Can you make the rollup example self-contained / consistent?

I was able to do this by:
1. copy `WORKSPACE` from `program`.
1. rewrite `BUILD` to drop `example/rollup/` before `foo.js`.
1. rewrite `rollup.bzl` to replace `//example/rollup` with `//:rollup`

**Comment by alexeagle** [comment]
yes, with the caveat that I think I should still have one example that is in the same workspace with the rules, because there is some code that only breaks for intra-workspace references, and I desperately need the test coverage.
