### ISSUE TITLE
karma_web_test get a broken io pipe under ibazel after first run

### ISSUE THREAD

**Issue by Toxicable** [bazelbuild/rules_nodejs#606]
# 🐞 bug report

### Affected Rule
`karma_web_test`

### Is this a regression?
Not sure
### Description
After running karma_web_test for the first time the connect breaks `@bazel/ibazel@0.9.1`
## 🔬 Minimal Reproduction
https://github.com/Toxicable/bazel_web_test_bugs

## 🔥 Exception or Error

<pre><code>INFO: Found 1 target...
[0 / 2] [-----] BazelWorkspaceStatusAction stable-status.txt
Target //tests/broken-pipe:testing_karma up-to-date:
  dist/bin/tests/broken-pipe/testing_karma
INFO: Elapsed time: 0.472s, Critical Path: 0.07s
INFO: 0 processes.
INFO: Build completed successfully, 2 total actions
INFO: Build completed successfully, 2 total actions
Starting...exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //tests/broken-pipe:testing_karma
-----------------------------------------------------------------------------
Karma version: 4.0.1
No browsers configured. Configuring Karma to use system Chrome.
08 03 2019 21:46:21.340:WARN [karma]: No captured browser, open http://localhost:9876/
08 03 2019 21:46:21.344:INFO [karma-server]: Karma v4.0.1 server started at http://0.0.0.0:9876/
08 03 2019 21:46:21.344:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
08 03 2019 21:46:21.348:INFO [launcher]: Starting browser Chrome
08 03 2019 21:46:22.121:INFO [Chrome 72.0.3626 (Linux 0.0.0)]: Connected on socket S6p70Oh1f__J-j88AAAA with id 7790509
Chrome 72.0.3626 (Linux 0.0.0): Executed 1 of 1 SUCCESS (0.004 secs / 0.001 secs)
TOTAL: 1 SUCCESS
ibazel failed to stop karma after 5s; probably a bug</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre> <code>ubuntu 16.04</code></pre>

**Output of `bazel version`:**

<pre><code>Build label: 0.23.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Feb 26 17:42:16 2019 (1551202936)
Build timestamp: 1551202936
Build timestamp as int: 1551202936</code></pre>

**Rules version (SHA):**

<pre><code>RULES_NODEJS_VERSION="0.27.1"
RULES_NODEJS_VERSION_SHA256="5c86b055c57e15bf32d9009a15bcd6d8e190c41b1ff2fb18037b75e0012e4e7c"
@bazel/typescript@0.27.1
@bazel/ibazel@0.9.1</code></pre>

**Comment by Globegitter** [comment]
Just for completeness, are you running `ibazel test` or `ibazel run` as I have noticed inconsistent behaviour between the two in my experience. See https://github.com/bazelbuild/bazel-watcher/issues/184

**Comment by Toxicable** [comment]
This one is with `npx ibazel run tests/broken-pipe:testing_karma`

**Comment by alexeagle** [comment]
can you still reproduce?
