### ISSUE TITLE
repository rule for node_modules

### ISSUE THREAD

**Issue by mattmoor** [bazelbuild/rules_nodejs#63]
Currently these rules support accessing `node_modules` from some place instantiated within the source tree.  This is consistent with Node.js user expectations and makes sense to offer users as an option.

However, requiring `node_modules` within the source tree is inconsistent with the way just about all other Bazel tools leverage `WORKSPACE`, which enables a user to effectively clone the repo and `bazel {build,test} ...` with no additional setup.

Essentially, we offer a Node.js idiomatic option, but not a Bazel idiomatic option.

I would like to propose one small addition to this repository, which is to offer a mechanism by which users can choose to instantiate the `:node_modules` `filegroup` during `WORKSPACE` evaluation.

The idea would be that users could still opt to use today's approach, where they instantiate `node_modules` outside of `WORKSPACE`, then expose and reference it via:
```python
=== BUILD ===
# Expose
filegroup(name = "node_modules", srcs = glob(["node_modules/**/*"]))

# Reference
nodejs_binary(
    name = "bar",
    node_modules = "//:node_modules",
    ...
)
```

Alternately users could write:
```python
=== WORKSPACE ===
# Expose (or yarn_install)
npm_install(
    name = "foo",
    packages = ":package.json",  # Or the lock-file
)

=== BUILD ===
# Reference
nodejs_binary(
    name = "bar",
    node_modules = "@foo//:node_modules",
    ...
)
```

I have a working prototype of this [here](https://github.com/mattmoor/rules_nodejs-1/blob/express-example/examples/express/BUILD.bazel#L5) that I've validated with my `express` "hello world" app.  I believe beyond the new rule definitions I only needed one small change to `internal/node.bzl`.

If you'd be receptive to adding this as an option, I'd be receptive to trying to clean it up and get it upstreamed.  WDYT?

@jonjohnsonjr @davidstanke @pubref @samertm FYI

**Comment by alexeagle** [comment]
This landed a while ago
