### ISSUE TITLE
RUNFILES env var not always correctly set in case of shell wrapper

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/rules_nodejs#635]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: nodejs_binary

### Is this a regression?

 No

### Description

I ran into another bug in regards to the runfiles discovery when the `nodejs_binary` is used in a shell-wrapper and this time it is in regards to the node module discovery. I have a full repro-case which will probably explain the issue better, but I am talking about these lines of code: https://github.com/bazelbuild/rules_nodejs/blob/master/internal/node/node_launcher.sh#L81-L103

If bazel has created the runfiles of the `nodejs_binary` (i.e. one ran bazel build on that target) and then one runs the wrapper shell target via `bazel run`, then the `ǹode_launcher.sh` sets `RUNFILES` to the runfiles of the underlying binary rather then to the ones of the wrapper script. This itself already can cause bugs, because if I add new dependencies and then just `bazel run` the wrapper target those will be missing in the runfiles of the underlying target. But also the behaviour is inconsistent because if I never did `bazel build/run` of the underlying target, then `node_launcher.sh` finds the correct runfiles. Again might be easier to see when running the reproduction case.

## 🔬 Minimal Reproduction

Clone https://github.com/globegitter/rules_nodejs_sh_wrapper_repro and follow the steps described here: https://github.com/globegitter/rules_nodejs_sh_wrapper_repro#issue-2

## 🔥 Exception or Error

<pre><code>
Error: //app:app.binary_bin cannot find module 'five' required by ....
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
elementary OS 5.0 Juno (Ubuntu 18.04)
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
0.24.0
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>
ff9042a67febb52eae5ad0392a12300b4a394031
  </code>
</pre>

**Anything else relevant?**
Seems I can workaround the issue by setting the `TEST_SRCDIR` env var but have not verified that yet.

**Comment by Globegitter** [comment]
Just as an update, the workaround we are making use of now is setting `TEST_SRCDIR=$(pwd)/..` in the shell wrapper and that does mitigate the issue but a proper fix would be good.

**Comment by alexeagle** [comment]
Let's use this to track removing the shell wrappers altogether.

**Comment by alexeagle** [comment]
fixed by #1078
