### ISSUE TITLE
Examples don't stand alone

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#707]
The examples should help our users understand how to use the rules.

If you check out the repo and e.g.
`cd examples/parcel && bazel build :bundle`
this should just work but instead we link against locally generated artifacts so you get an error

```
ERROR: error loading package '': Encountered error while reading extension file 'defs.bzl': no such package '@build_bazel_rules_nodejs//': /private/var/tmp/_bazel_alexeagle/8c826fbdf9c3ae43118c5cd5c0f0d9a0/external/build_bazel_rules_nodejs must be an existing directory
```

**Comment by gregmagolan** [comment]
You think we should just change these to use the last released versions and make sure all assertions in examples as handled by e2e tests?

**Comment by alexeagle** [comment]
a few options -
1) example works against last released and we also test it with head
2) example builds against source rather than release, is a little less robust for doing testing, assumes we can make the same code work against both
3) we teach Bazel how to build from source as a dependency, maybe the bazel-integration-test thing lets us have a build step that is a dep of a repository rule

**Comment by gregmagolan** [comment]
1. is decent; we can have the examples point to the latest released versions (release script would have to update these) and have them stand on their own but for testing against head locally & in CI make a copy of them and modify the package.json & WORKSPACE to point to the generated npm packages as they do now.
2. not great as no one downstream will be building nodejs packages from source so leads to the same problem
3. probably the best way to go for e2e tests but for examples would lead to the same problem of the example code not being portable without changes

**Comment by gregmagolan** [comment]
Done. Examples now stand-alone. WORKSPACE file points to the last release & package.json is set to "latest" for @bazel/foobar packages. `bazel_integration_test` is used to test against head from the root workspace.
