### ISSUE TITLE
Update to stardoc

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/rules_nodejs#715]
We're still using `skylark_doc` to generate some of the documentation here:

```
skylark_doc(
    name = "docs",
    srcs = [
        "//internal/common:check_bazel_version.bzl",
        "//internal/history-server:history_server.bzl",
        "//internal/http-server:http_server.bzl",
        "//internal/jasmine_node_test:jasmine_node_test.bzl",
        "//internal/node:node.bzl",
        "//internal/node:node_repositories.bzl",
        "//internal/npm_install:npm_install.bzl",
        "//internal/npm_package:npm_package.bzl",
        "//internal/rollup:rollup_bundle.bzl",
    ],
    format = "html",
    site_root = "/rules_nodejs",
    strip_prefix = "internal/",
    # This rule depends on building protoc which is annoying and slow
    # we only need to build it when we cut a release.
    tags = ["manual"],
)
```

and in a few other spots.

With Bazel 0.24.1 `repository_rule` now supports the `doc` attribute which was blocking this upgrade.

With the update to skydoc we can also re-enable the `no-effect` buildifier check since it will fix this issue with using the `doc` attribute in `repository_rule` and `rule` which is currently blocked by this issue https://github.com/bazelbuild/buildtools/issues/471#issuecomment-485283200, which should be fixed by updating to skydoc https://github.com/bazelbuild/buildtools/issues/471#issuecomment-485487629

**Comment by alexeagle** [comment]
was fixed in https://github.com/bazelbuild/rules_nodejs/commit/778c32ca043bf1e0bf95bb48712fc2bf8d4377aa
