### ISSUE TITLE
web_package and ts_devserver use different root paths

### ISSUE THREAD

**Issue by jbedard** [bazelbuild/rules_nodejs#728]
### Affected Rule
ts_devserver, web_package

### Description

`ts_devserver` and `web_package` treat bazel-out/genfiles differently.

`ts_devserver` strips all references to bazel-out/genfiles and treats bazel-out/genfiles/src-root the same. `web_package` does not strip bazel-out/genfiles

### Minimal Reproduction

(coming soon, if necessary)

**Anything else relevant?**

`ts_devserver` and `web_package` would preferably share the same logic for this

**Comment by alexeagle** [comment]
what would the `additional_root_paths` look like? I wouldn't expect a user needs to configure tools to resolve from all three roots, that should be built-in (meaning `bazel-bin/src/foo`, `bazel-genfiles/src/foo`, and `src/foo` should all be addressed the same way)

**Comment by jbedard** [comment]
Ideally (correct me if I'm wrong...):
1) `bazel-*` would never show up in a url
2) URLs for for the same resources would be the same in `ts_devserver` and `web_package`
3) you can use `additional_root_paths` to (consistently) strip other paths

Right now:
* `ts_devserver` swaps `/bazel-out/darwin-fastbuild/bin` with `/{workspace}`, where `web_package` does not
* `web_package` strips the path to the BUILD target, `ts_devserver` does for some but not others (not those in `bazel-*`?)

I guess I tried achieving this by manually setting `additional_root_paths` to contain the `bazel-out` dir, where it should just happen automatically?

(then I got confused and assumed the inconsistency was because of inconsistent var support, which might be completely wrong...)

**Comment by jbedard** [comment]
I think this can be resolved by just adjusting https://github.com/bazelbuild/rules_nodejs/blob/0.28.0/internal/web_package/web_package.bzl#L77-L81 - and maybe share that logic with `ts_devserver`...

**Comment by jbedard** [comment]
I've updated the issue description.
