### ISSUE TITLE
Transitive dep loading of non-js files

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/rules_nodejs#729]
### Affected Rule
The issue is caused by the rule: `nodejs_binary`

### Is this a regression?

 No

### Description

As an effort to get us closer to a bazel ideal for our js setup I created a `js_library` to ease migration to eventually get `vue_component`, `babel_library` or eventually even `ts_library` support in. Feature-wise the only two things it supports is the `module_name`/`module_root` feature as well as adding support for transitive dependency loading for the use of `nodejs_binary`. This works perfectly when a `js_library` depends on another `js_library`, but fails when a `js_library` depends on a soruce file, like for example an `.svg` file or a `.proto` file. For importing the svg file we currently use some webpack config, not sure tbh, but both can probably be transformed into something like `svg_to_vue` and a `proto_to_js`/`js_proto_library` rule to get this "bazel native" but also to get transitive loading support.

To be honest, I am also happy to let this get closed if this does not aid other people's migration process also as there are workarounds for that, either by just adding those files directly for the top-level `nodejs_binary` or by creating some no-op rule which  makes these files available under `target.typescript.es5_sources`.

If this was to get accepted as a feature, what would be nice if this could be configured by the top-level `nodejs_binary`, so we could have something like:

```
nodejs_binary(
  name = "bin",
  ...
  transitive_data_extension = "*",
)
```

This works by utilising parameterised aspects, but it does have the limitation that this only supports simple strings at the moment and one has to provide all allowed values statically, e.g.

```
sources_aspect = aspect(
    _sources_aspect_impl,
    attr_aspects = ["deps"],
    attrs = {
        'transitive_data_extension' : attr.string(values = ["*", ".js"]),
    },
)
```

EDIT: Another solution could be to just look for a special tag in the rule, then one could really allow on a fine-grained level which files to include by just utilising a `filegroup`.

## 🔬 Minimal Reproduction

I am happy to provide a repro if needed but the code causing this behaviour is https://github.com/bazelbuild/rules_nodejs/blob/master/internal/common/sources_aspect.bzl#L41 and would be very straight forward to fix but not sure if that makes the most sense.

But a  simple BUILD file to illustrate the issue:

```
js_library(
  name = "file",
  srcs = ["file.js"], // this js file has a line like `import icon from './icon.svg'¸
  deps = ["icon.svg"],
)

nodejs_binary(
  name = "bin",
  data = [
    ":file",
  ],
 ...
)
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Elementary OS 5 (Ubuntu 18.04)
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
0.25.0rc3
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>
11271418a6bbd2529170270a7e61dcc5167bb16d
  </code>
</pre>

**Anything else relevant?**

No

**Comment by Globegitter** [comment]
Had some time and worked around this issue by creating a `js_import` rule, see: https://github.com/ecosia/bazel_rules_nodejs_contrib#js_import

**Comment by ewianda** [comment]
Given that https://github.com/ecosia/bazel_rules_nodejs_contrib#js_import is now archived, how can this be solved currently.
