### ISSUE TITLE
rollup_bundle fails at downleveling javascript

### ISSUE THREAD

**Issue by rerion** [bazelbuild/rules_nodejs#737]
Edit: it looks like PR is already on its way. -> https://github.com/bazelbuild/rules_nodejs/pull/736

# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 
rollup_bundle, i guess

### Is this a regression?

 no idea

### Description

rollup_bundle uses typecript for 'downleveling' to es5.
This causes errors with declarations, using lib.d.ts apis newer than es5.
related code:
https://github.com/bazelbuild/rules_nodejs/blob/master/internal/rollup/rollup_bundle.bzl#L225-L238

## 🔬 Minimal Reproduction

try to build new angular app @ 8.0.0-rc.2

## 🔥 Exception or Error

<pre><code>

$ npx bazel build --verbose_failures src:prodapp
INFO: Analysed target //src:prodapp (514 packages loaded, 20866 targets configured).
INFO: Found 1 target...
ERROR: C:/users/rerion/ideaprojects/house-of-r/ng-mui/src/BUILD.bazel:39:1: Downleveling JavaScript to ES5 src/bundle.js [typescript] failed (Exit 2): tsc.exe failed: error executing command
  cd C:/users/rerion/_bazel_rerion/7dlzpl6z/execroot/project
bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/rollup/tsc.exe --target es5 --allowJS bazel-out/x64_windows-fastbuild/bin/src/bundle.es2015.js --outFile bazel-out/x64_windows-fastbuild/bin/src/bundle.js
Execution platform: @bazel_tools//platforms:host_platform
../../../../ideaprojects/house-of-r/ng-mui/node_modules/@types/selenium-webdriver/http.d.ts(24,14): error TS2583: Cannot find name 'Map'. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.
../../../../ideaprojects/house-of-r/ng-mui/node_modules/@types/selenium-webdriver/http.d.ts(48,14): error TS2583: Cannot find name 'Map'. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.
../../../../ideaprojects/house-of-r/ng-mui/node_modules/@types/selenium-webdriver/remote.d.ts(139,29): error TS2583: Cannot find name 'Map'. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.
Target //src:prodapp failed to build
INFO: Elapsed time: 20.872s, Critical Path: 15.21s
INFO: 4 processes: 3 local, 1 worker.
FAILED: Build did NOT complete successfully

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
win10
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 0.24.1
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Apr 2 16:30:30 2019 (1554222630)
Build timestamp: 1554222630
Build timestamp as int: 1554222630
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>
RULES_NODEJS_VERSION = "0.28.0"
RULES_NODEJS_SHA256 = "4c702ffeeab2d24dd4101601b6d27cf582d2e0d4cdc3abefddd4834664669b6b"
  </code>
</pre>

**Anything else relevant?**

You can probably add '--skipLibCheck' to arguments in `_run_tsc`, since it's just for js => js transpilation.
Related angular issue: https://github.com/angular/angular/issues/30256

**Comment by gregmagolan** [comment]
Resolved by #736. Release to be cut shortly.
