### ISSUE TITLE
node_sources in aspect is misnamed

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#76]
We also use these from other repositories to load sources for the browser.

**Comment by gregmagolan** [comment]
I've cleaned this up in https://github.com/bazelbuild/rules_nodejs/pull/1040 as part of https://github.com/bazelbuild/rules_nodejs/issues/57

**Comment by gregmagolan** [comment]
Resolved with https://github.com/bazelbuild/rules_nodejs/pull/1215
