### ISSUE TITLE
karma_web_test should resolve .umd.js.map files

### ISSUE THREAD

**Issue by Toxicable** [bazelbuild/rules_nodejs#764]
# 🚀 feature request

### Relevant Rules
`karma_web_test`

### Describe the solution you'd like
*.umd.js.map files should be automatiically resolved by `karma_web_test`

### Describe alternatives you've considered
manually ading them

**Comment by gregmagolan** [comment]
The change needed is https://github.com/bazelbuild/rules_nodejs/blob/master/internal/npm_install/generate_build_file.js#L750. Just need to add `.umd.js.map` to the array.
