### ISSUE TITLE
nodejs_binary change directory before executing node (or make launcher_template public)

### ISSUE THREAD

**Issue by freythgs** [bazelbuild/rules_nodejs#797]
### Description

I am the using _nodejs_binary_ rule to execute the "react-scripts" of reactjs and in general that is working out well. Unfortunately one react app resides in a sub directory of aWORKSPACE and then things fall apart (No //public:index.html //src:index.js). The reason is that the script gets executed from the root of the WORKSPACE (in its sanbox).

### Describe the solution you'd like

I would like to be able to configure the relative working directory of where the node binary is being executed. This could be the introduction of an "app_directory" ("execution_directory") attribute defaulting to "./". The directory would be changed before executing node. E.g. like in the below example.

```
nodejs_binary(
      name = "react_scripts",
      data = [
          "@npm//react-scripts",
          ":package.json",
      ],
      entry_point = "react-scripts/bin/react-scripts.js",
      app_directory = "frontend-subdir",
 )
```

### Describe alternatives you've considered

I have considered multiple repositories and workspaces. Another alternative is to make the _launcher_template public and have a way to pass my arguments into it.

**Comment by Globegitter** [comment]
You could also wrap things into a `sh_binary` which cds into that dir before `exec`ing the node script. And then wrap it into a macro that takes an `app_directory` arg.

**Comment by freythgs** [comment]
I ended up writing a custom webpack config (instead of the create react app scripts) and have no need for the above.
