### ISSUE TITLE
move precommit to husky hook

### ISSUE THREAD

**Issue by santoshyadav198613** [bazelbuild/rules_nodejs#813]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
On windows when you do commit , you get warning as precommit is deprecated

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>

  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>

  </code>
</pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
No need for issue for this. Thanks.
