### ISSUE TITLE
npm_install doesn't use lockfile

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#82]
This caused https://github.com/bazelbuild/rules_typescript/issues/117

We should reject executions of npm_install  that have floating, non-pinned versions, as it leads to non-hermetic behavior.

**Comment by gregmagolan** [comment]
https://github.com/bazelbuild/rules_nodejs/pull/106 adds yarn_install which can accept a yarn.lock file.

**Comment by gregmagolan** [comment]
> @gregmagolan does that mean if you keep using npm, you'll have floating deps? Meaning we won't fix this?

I added the ability a package_lock_json attribute to the npm_install rule in #106. This should make it deterministic but I'm not too familiar with npm locks files or the non-hermetic behavior observed with npm.

**Comment by alexeagle** [comment]
okay cool, we should fix the determinism too but that's not this issue.

We should update our rules that use `npm_install` to include `package-lock.json`...

**Comment by gregmagolan** [comment]
`package_lock_json` attribute added in https://github.com/bazelbuild/rules_nodejs/pull/106 which resolves this
