### ISSUE TITLE
stop putting node_modules in runfiles

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#824]
I've been trying to make Bazel faster on my slow Mac at home, where runfiles creation takes minutes for real-sized projects.
But lots of things are broken. For example, in angular-bazel-example the `bazel run //src:prodserver` brings up a server that just 404s everything because it looks in runfiles.

**Comment by alexeagle** [comment]
Actually it seems that the performance fix is not to embed node_modules in the runfiles at all ("static linked") but include them in the execution of the program ("dynamic linked").

**Comment by Toxicable** [comment]
Testing out some cache performance on our repository and with a fully populated cache it still takes 2 minutes to do a full test:
```
bazel build ...
bazel clean --async
bazel build ...
```
Result:
```
INFO: Elapsed time: 117.977s, Critical Path: 23.53s
INFO: 229 processes: 207 remote cache hit, 22 linux-sandbox.
INFO: Build completed successfully, 1388 total actions
```
My `.bazelrc` has these, along with other non relevent entries
```
build --disk_cache=~/.cache/bazel-disk-cache
build --verbose_explanations --explain=./tmp/explain.log
```
2 minutes isn't terrible but just looking at the logs most of the time is spent `Creating runfiles tree`
Which must be the result from having `node_modules` in the runfiles, meaning actioning this could give us some really big perf gains

**Comment by alexeagle** [comment]
The resolution here is going to be using runfiles for its intended purpose, but represent node modules as TreeArtifacts.

**Comment by gregmagolan** [comment]
No longer in scope for rules_nodejs which only supplies the Node.js toolchain as of [v6.0.0](https://github.com/bazelbuild/rules_nodejs/releases/tag/v6.0.0-beta0).

Downstream canonical JavaScript + Node.js ruleset is now https://github.com/aspect-build/rules_js.
