### ISSUE TITLE
VSCcode switches to inferred tsconfig after bazel build

### ISSUE THREAD

**Issue by kellycampbell** [bazelbuild/rules_nodejs#828]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: `ts_library` possibly. It's also possible this is a bug in vscode's tsserver.

### Description

When using vscode with a bazel workspace that is using typescript and a tsconfig.json, absolute imports are not found. However, they are found before bazel build is run.

## 🔬 Minimal Reproduction

1. Open this repo in vscode (1.34 and 1.35 both show the problem):

https://github.com/kellycampbell/example-bazel-proto-ts 

commit `62650a50452e720d2c39fc5097bc1562626b422f`

2. Optional: run `yarn install` on the repo to populate the node_modules

3. Open the file `src/hello.ts` and after TS tooling setup is complete look at the state of the imports.

```
import { Foo } from 'example_ts/test/foo';
import { HelloMessage } from 'example_ts/protos/hello_pb';
```
The `Foo` import should be ok, the `HelloMessage` import should be red.

If you didn't do step 2, then the `google-protobuf` import will also be red.

4. Run `bazel build protos:hello_proto_ts`

Now the `HelloMessage` import should be ok

5. Run `bazel build src:hello`

(hello.ts is expected to have two compilation errors. I left these in to show when type checking is working or not.)

Note that the absolute workspace imports in the hello.ts file are now both red in vscode.

## 🔥 Exception or Error

I used the tsserver logging at verbose level to see what is happening during the above steps.

To enable tsserver logging: File -> Preferences, search for `tsserver:log` and set to `verbose`, then run the `Open TSServer log file` comand to view.

Part of my log file is posted here: https://gist.github.com/kellycampbell/e855bc55017be4ecaaf5fe1d313438e0

The bit that is interesting is it switches to using an `inferredProject` instead of my `tsconfig.json` when the bazel build is run. I can't tell why it decides to switch.

```
Info 476  [20:3:49.649] Finishing updateGraphWorker: Project: /dev/null/inferredProject1* Version: 1 structureChanged: true Elapsed: 618ms
Info 477  [20:3:49.649] Project '/dev/null/inferredProject1*' (Inferred) 
```

## 🌍  Your Environment

**Operating System:**

`linux mint 19.1`

**Output of `bazel version`:**

```
Build label: 0.26.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue May 28 08:35:14 2019 (1559032514)
Build timestamp: 1559032514
Build timestamp as int: 1559032514
```

**Rules version (SHA):**

```
rules_nodejs_version = "0.30.2"
http_archive(
    name = "build_bazel_rules_nodejs",
    url = "https://github.com/bazelbuild/rules_nodejs/releases/download/{}/rules_nodejs-{}.tar.gz".format(rules_nodejs_version, rules_nodejs_version),
    sha256 = "bc180118b9e1c7f2b74dc76a8f798d706fe9fc53470ef9296728267b4cd29441",
)
```

**VS Code version**

1.34 and 1.35

**Typescript version**

3.5.1

**Comment by alexeagle** [comment]
Hmm, my guess is that the `tsconfig` points to `bazel-out` which is a symlink, and during the build that symlink might be broken while the output directory is re-written?
Might be able to substantiate that by creating a non-bazel project where the tsconfig similarly points to a symlink to a directory where a needed `.d.ts` file lives.

**Comment by kellycampbell** [comment]
@alexeagle I figured out that it is one of the bazel symlinks, but the problem isn't what you thought.

It's caused by the symlink that links the whole project:

```
bazel-example-bazel-proto-ts -> /home/kellyc/.cache/bazel/_bazel_kellyc/760681156e903476ddc0c7149ff89950/execroot/example_ts
```

I think it's because the same files exist in two places within the ts project. If I remove that symlink, the editor goes back to successful on the imports. I'm investigating workarounds.

**Comment by Toxicable** [comment]
We use module imports and havn't had any issues with code navigation
For example: we have a common lib called `@workspace/common`
Then you just set the paths in your tsconfig correctly and you can import `import {whatever} from '@workspace/common'` without a problem

**Comment by kellycampbell** [comment]
Simple workaround is to just exclude the bazel-{workspace} dir in tsconfig.json:

```
   "exclude": { "bazel-workspace-name" }
```

**Comment by alexeagle** [comment]
We typically recommend setting `--symlink_prefix=dist/` in `.bazelrc` and ignoring the `dist/` folder in the editor.
(I mention it because I wonder if we could do something globally to prevent users hitting this issue, maybe I should add that exclude line to our generated files in `@bazel/create`)

**Comment by kellycampbell** [comment]
I don't see that symlink prefix thing in the readme. I haven't really used @bazel/create much yet because we have a project that pre-dates it, but that sounds like a good place to add the exclude. I did compare against a newly generated project from it when trying to debug this and probably would have seen it then.

**Comment by kellycampbell** [comment]
Another thought on the above: we actually don't want to ignore all the `bazel-` symlinks because we are using protoc generated js and ts. Our tsconfig mappings look like this now:

```
        "baseUrl": ".",
        "paths": {
            "stratis3/*": [
                "*",
                "bazel-genfiles/*",
                "bazel-bin/*"
            ]
        }
    },
    "exclude": [
        "bazel-stratis3",
        "bazel-out",
        "bazel-testlogs"
    ]
```

I added bazel-out and testlogs to the exclude just to decrease the surface area that the editor/tsserver watch.
