### ISSUE TITLE
ts_auto_deps will traverse up node_modules directory when -recursive is used

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/rules_nodejs#856]
A few solutions I can think of with increasing complexity:

* ignore the `node_modules` directory as a special case
* accept an argument that lists folders to whitelist or blacklist
* parse `.tsautodepsignore` files to determine which folders to blacklist

**Comment by mattem** [comment]
Can close as ts_auto_deps was removed from the repo?
