### ISSUE TITLE
Option to serve and include non-js files w/ ts_web_test_rule

### ISSUE THREAD

**Issue by devversion** [bazelbuild/rules_nodejs#858]
Currently the `ts_web_test_rule` uses an internal Karma configuration that only `includes` files which have been templated with `TMPL_bootstrap_files` and `TMPL_user_files`.

This means that there is no way for developers to specify **Non-JS** files which should be included by Karma. This is because:

```bzl
        "srcs": attr.label_list(
            doc = "JavaScript source files",
            allow_files = [".js"],       // Locks `TMPL_user_files` to JS only
        ),  

        "bootstrap": attr.label_list(
            allow_files = [".js"],      // Locks `TMPL_bootstrap_files` to JS only
        ),
```

There should be some way for people to include a CSS file through the rule configuration. This is necessary because some test suites depend on external CSS that needs to be served **and** included.

**Included** means that Karma automatically creates a `<link rel="stylesheet"` for such assets. Meaning that those are available without additional logic for loading them through JavaScript.

See here: https://github.com/karma-runner/karma/blob/c311ac00cef4a957f889ed613238793c0ffa95a2/lib/middleware/karma.js#L198

cc. @alexeagle

**Comment by Splaktar** [comment]
I believe that this is still an issue.

**Comment by gregmagolan** [comment]
No longer in scope for rules_nodejs
