### ISSUE TITLE
Make rules_nodejs work with Python 3

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/rules_nodejs#86]
ci.bazel.build uses Python 3 now, hence rules_nodejs are no pass tests: https://ci.bazel.build/blue/rest/organizations/jenkins/pipelines/Global/pipelines/rules_nodejs/runs/182/nodes/19/log/?start=0

**Comment by dslomov** [comment]
Other resolution might be to use python3 on CI for rules_nodejs specifically.
cc @philwo, @laszlocsomor

**Comment by philwo** [comment]
Use Python3? Or Python2?

**Comment by dslomov** [comment]
oops

**Comment by laszlocsomor** [comment]
Sure, we can install python2 and add `--python_path=c:/python27/python.exe` to the bazel flags for this job, but ultimately `rules_nodejs` should fix their test.

**Comment by alexeagle** [comment]
Blocked on unrelated windows breakage
