### ISSUE TITLE
source map support in coverage reports

### ISSUE THREAD

**Issue by Toxicable** [bazelbuild/rules_nodejs#867]
# 🚀 feature request

### Relevant Rules
`jasmine_node_test`

### Description
We should still use `v8-coverage` to collect coverage reports without having to fork the process.
However, c8 and transitively v8-to-istanbul provide better reporting due to having source map support and more up to date istanbul deps.

**Comment by Toxicable** [comment]
This however is blocked on #823 
Since the source map lib needs to resolve the souce map back to the source file from the executed file.

Also blocked on and https://github.com/istanbuljs/v8-to-istanbul/issues/31

**Comment by Toxicable** [comment]
Aside from the blocking issues it's minor changes needed on our side so just going to  document that here for now:

```
        const Report = require('c8/lib/report');
        fs.mkdirpSync(path.join(covDir, 'tmp'));
        // we have to write it in a top level result object since thats what the lib expecets
        fs.writeFileSync(path.join(covDir, 'tmp', 'coverage-final.json'), JSON.stringify({result: sourceCoverge}));

        const report = Report({
          reportsDirectory: covDir,
          tempDirectory: path.join(covDir, 'tmp'),
          reporter: ['text', 'text-summary', 'html'],
          exclude: ['**/node_modules/**'],
        });
```

**Comment by Toxicable** [comment]
I think the best way to handle this would be to add a `coverage` flag to `nodejs_binary` which would then internally set the `NODE_V8_COVERAGE` to a dir where the collection will be written.
We need to do this at a `nodejs_binary` level so that we don't have to use the `inspector` api and so that we don't have to use a fork later on.

We'll still need to handle the reporting at the end of `jasmine_node_test`.

However, if we switched to `c8` for reporting and transitively `v8-to-istanbul` we'd need the source maps situation to be fixed, since they are unable to resolve our source files in the current setup.
As mentioned above.
Which is the same issue here: https://github.com/bazelbuild/rules_nodejs/issues/823

**Comment by thesayyn** [comment]
Hello @Toxicable  is there any update on this

**Comment by Toxicable** [comment]
@thesayyn Yeah so I know what needs to be done to make this change
However due to #823 the result will be broken since our source maps don't map back to sources correctly and after talking with @alexeagle I don't know if there is actually a solution to that problem.

So untill we figure out source maps properly, this is blocked

**Comment by sjoerdvisscher** [comment]
Hi, @Toxicable, the issues you point to here are now closed. Does this mean this issue has a chance to progress?

**Comment by sjoerdvisscher** [comment]
I have working TS coverage now with two patches:

1. https://github.com/istanbuljs/v8-to-istanbul/pull/115 (This prevents c8 from reading from the invalid source location)
2. patching `lcov_merger-js` to replace `SF:../../../` with `SF:` in `lcov.info`
