### ISSUE TITLE
Webhook for source.developers.google.com needed?

### ISSUE THREAD

**Issue by philwo** [bazelbuild/rules_nodejs#87]
Hi,

this repo has a webhook installed for:
https://source.developers.google.com/webhook/github

Is this still needed and for what? I can't see rules_nodejs listed on source.bazel.build, nor on source.developers.google.com.

(I'm just trying to clean up our webhook / integration structure for the bazelbuild org and repos a bit.)

Cheers,
Philipp

**Comment by alexeagle** [comment]
Hey @philwo ,
I don't know why that's there. I probably experimented with some google cloud service like the test results UI? I started following instructions a few months ago and then ran out of time. It's okay with me if you remove it.

**Comment by philwo** [comment]
Thanks - I've removed it for now. Feel free to add it back whenever necessary :)
