### ISSUE TITLE
jasmine_node_test: invalid repository name '@bazel/jasmine/src/jasmine_runner.js'

### ISSUE THREAD

**Issue by fejta** [bazelbuild/rules_nodejs#886]
# 🐞 bug report

### Affected Rule

jasmine_node_test

### Is this a regression?

Yes, worked on 0.30.2

## 🔬 Minimal Reproduction
```
git clone https://github.com/fejta/test-infra.git 
git checkout -b origin/demo
bazel test //gopherage/cmd/html/static/...
```

target: https://github.com/fejta/test-infra/blob/demo/gopherage/cmd/html/static/BUILD.bazel#L21-L29
WORKSPACE: https://github.com/fejta/test-infra/blob/demo/WORKSPACE#L155-L177
packages: https://github.com/fejta/test-infra/blob/demo/package.json

## 🔥 Exception or Error

```
ERROR: /usr/local/google/home/fejta/src/gh/test-infra/gopherage/cmd/html/static/BUILD.bazel:21:1: //gopherage/cmd/html/static:utils_test: invalid label '@bazel/jasmine/src/jasmine_runner.js' in attribute 'entry_point' in 'nodejs_test' rule: invalid repository name '@bazel/jasmine/src/jasmine_runner.js': workspace names may contain only A-Z, a-z, 0-9, '-', '_' and '.'
ERROR: /usr/local/google/home/fejta/src/gh/test-infra/gopherage/cmd/html/static/BUILD.bazel:21:1: //gopherage/cmd/html/static:utils_test: missing value for mandatory attribute 'entry_point' in 'nodejs_test' rule
```
Seems to come from here: https://github.com/bazelbuild/rules_nodejs/blob/master/packages/jasmine/src/jasmine_node_test.bzl#L33

## 🌍  Your Environment

**Operating System:**

Linux

**Output of `bazel version`:**

`0.27.0`

**Rules version (SHA):**

`6d4edbf28ff6720aedf5f97f9b9a7679401bf7fca9d14a0fff80f644a99992b4`

**Anything else relevant?**

package.json has
* @bazel/bazel: 0.27.0
* @bazel/jasmine: 0.32.2
* @bazel/typescript: 0.32.2

**Comment by fejta** [comment]
Appears that `rm -rf node_modules && bazel clean --expunge` resolves the issue

**Comment by alexeagle** [comment]
yes, sorry, the update to 0.32.2 requires cleaning the node_modules since we changed how we lay out the BUILD files in there.
It's mentioned in Breaking Changes in https://github.com/bazelbuild/rules_nodejs/releases/tag/0.32.2 so I don't think there's anything else to do here.
