### ISSUE TITLE
Add LESS/Stylus preprocessor support

### ISSUE THREAD

**Issue by alan-agius4** [bazelbuild/rules_nodejs#887]
# 🚀 feature request

Angular CLI supports SASS, Stylus and Less as Css processors.

For feature partity, Bazel version of the CLI should as well but before that we need to create Bazel rules for various processors.

**Comment by alexeagle** [comment]
Bazel rule for stylus is in https://github.com/bazelbuild/rules_nodejs/pull/908

could use some help to validate this against some real-world usage.

**Comment by alexeagle** [comment]
Stylus and LESS have both landed.
Still some work remaining in the `@angular/bazel` package to add them to the builder's generated BUILD file.
