### ISSUE TITLE
Use the newly added dependency pruning

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/rules_nodejs#890]
Bazel 0.27 has finally allowed Starlark access to dependency pruning, a feature that has previously been reserved only for native rules.

bazelbuild/bazel@5736381

Implement unused_inputs_list for Rollup bundling, thereby improving cache hits.

**Comment by Globegitter** [comment]
@pauldraper the link above is leading to a 404 for me.

**Comment by pauldraper** [comment]
@Globegitter I think Github had some hiccup and double-filed this issue.

#968 is the correct one.
