### ISSUE TITLE
@bazel/karma - selenium-webdriverv4 alpha dependency breaks BUILD

### ISSUE THREAD

**Issue by jerome-nelson** [bazelbuild/rules_nodejs#900]
# 🐞 bug report

### Affected Rule
`node_repositories()` rule

### Is this a regression?
Yes but this is due to a non-bazel package which we depend on. `selenium-webdriver`

### Description

Currently when attempting to build using `@bazel/karma:0.29.0` `selenium-webdriver:4.0.0-alpha.1` prevents BUILD due to node dependency being `10.13.0`.

`selenium-webdriver:4.0.0-alpha.1` requires 10.15.0 minimum now 

NOTE: This dependency is from the `karma/sauce-launcher` which `@bazel/karma` uses.

## 🔥 Exception or Error

<pre><code>
(error selenium-webdriver@4.0.0-alpha.4: The engine "node" is incompatible with this module. Expected version ">= 10.15.0". Got "10.13.0"
error Found incompatible module
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
    Windows 10 / Yarn
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 0.26.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue May 28 08:36:37 2019 (1559032597)
Build timestamp: 1559032597
Build timestamp as int: 1559032597
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>
    1db950bbd27fb2581866e307c0130983471d4c3cd49c46063a2503ca7b6770a4
  </code>
</pre>

**Comment by alexeagle** [comment]
I don't think this is a bug - the version of node is controlled by the user in the call to `node_repositories`.

**Comment by SiddAjmera** [comment]
I'm actually getting the same error even though I tried running it with Node V10.16 and Node V12.11.1

**Comment by gregmagolan** [comment]
It looks like you're on a old version of rules_nodejs that uses node 10 by default. The version of node used is controlled by the rules so the version you have installed locally doesn't matter. I'd recommend upgrading to the latest version of rules_nodejs and Bazel 2.0.0 and you'll get node 12 by default. If that is not possible, you can specify the version of node to use in the node_repository() function in your WORKSPACE.

**Comment by SiddAjmera** [comment]
That helped :) Thanks a lot @gregmagolan 💯 

I triggered `node_repository` with these:

`node_repositories(
    node_repositories = {"12.11.1-windows_amd64": ("node-v12.11.1-win-x64.zip", "node-v12.11.1-win-x64", "0bab4473cd2ba03511b8859ddf2202bb012d5c541f9d57b555a5bbbf101fcb35")},
    node_version = "12.11.1",
)`

And it got rid of the error. I'm getting this error now. But I'm sure it has nothing to do with `rules_nodejs`:

![image](https://user-images.githubusercontent.com/5053266/73657882-4c512f00-46e7-11ea-8885-0f7d0bc508a4.png)
