### ISSUE TITLE
Land worker mode for rules_sass

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#907]
Natalie would rather have an `@bazel/worker` npm package which provides the `worker.ts` code and vendor the worker_protocol.proto

**Comment by alexeagle** [comment]
See https://github.com/bazelbuild/bazel/issues/3155 where we decided to just vendor a copy of the worker_protocol.proto

**Comment by fenghaolw** [comment]
https://github.com/bazelbuild/rules_sass/pull/93 is the PR to rules_sass that enables worker.

This issue is a blocker since we want to make a reusable package and then we can make rules_sass to use that.

**Comment by fenghaolw** [comment]
Decision: use genrule to copy the worker.js and proto over to a new package.

Pros:
- We still have a single source of truth
- No need to change the release scripts

**Comment by fenghaolw** [comment]
Landed!

https://github.com/bazelbuild/rules_sass/pull/93
