### ISSUE TITLE
Impossible to build AngularJS?

### ISSUE THREAD

**Issue by herman-rogers** [bazelbuild/rules_nodejs#923]
# 🐞 bug report

Cannot build AngularJS project (build in javascript not typescript).

### Affected Rule

 The issue is caused by the rule: rollup_bundle, ng_module, nodejs_binary, etc.

### Is this a regression?

No

### Description

Not sure if this is just officially not going to be supported but the main issue I'm having is that it seems impossible to build a AngularJS app.

My situation is I have a couple of AngularJS apps written before a time typescript was a thing - so I need to compile javascript files. At first I thought this would be supported but it doesn't seem that ng_module supports .js files at all (it seems to only accept .ts). So, ok, bizarre that js itself isn't supported so I attempted several different approaches ("nodejs_binary", "npm_package", etc, etc).

I finally landed on rollup_bundle which actually seemed to compile all the Javascript files and everything was going well until I got to the AngularJS html files - which it can't compile as there doesn't seem to be anyway to import this for it to be bundled an useful.

Am I barking up the wrong tree? Should I just swap over to webpack or something else that has more support for legacy? Only reason I ask is that we're re-arching our entire frontend and we need a graceful way to use our massive AngularJS codebase while also being able to move forward in a mono-repo with Angular8 (i.e. get unstuck and away from AngularJS). I don't want to take us down a path where we're stuck upgrading each little AngularJS module to typescript and Angular 8 just to use bazel :/.

Any path forward for us people stuck on AngularJS?

## 🔬 Minimal Reproduction

Build any AngularJS project with javascript files instead of typescript - I assume.

## 🔥 Exception or Error

`Could not resolve import './template.html'`
`Expected (.ts)`
etc.

**Comment by Toxicable** [comment]
`ng_module` is for the Angular compiler, not AngularJS, it's not designed to work with AngularJS at all.
`ts_library` will work to compile any TS.

`rollup_bundle` also works to bundle any JS, however, this does not include .html, you must use another way to get your html there since using `import ...` is for JS not html

**Comment by herman-rogers** [comment]
Ok - so this took me some time. Because of our legacy costs I initially had to throw away the Bazel integration in our mono repo and go full webpack support. Once I knew our app (new angular 8 and old AngularJS) things were playing nicely together (thanks to single-spa) we then reintegrated Bazel into our app.

Long story short, we had to abandon anything the angular team produced for bazel tooling - they simple didn't work with AngularJS. Instead we went down the route of using nodejs rules provided via Bazel and this is what got working for us.

```bash
filegroup(
    name = "src_files",
    srcs = glob([
        # your app sources, configs, etc.
    ]),
)

# This is the main webpack bundle, all this does is run webpack with a specified config
# make sure to import any loaders that you need
nodejs_binary(
    name = "webpack",
    entry_point = "@npm//node_modules/webpack:bin/webpack.js",
    data = [
        ":src_files",
        # Webpack dependencies
        "@npm//webpack",
        "@npm//webpack-cli",
        # App NPM dependencies
        "@npm//@angular/core",
        "@npm//@angular/platform-browser",
        "@npm//@angular/router",
        #...etc
        # You can also import other bazel projects / srcs you have here
        "//example/project:legacy"
    ],
    templated_args = [
        "--node_options=--preserve-symlinks",
        "--config /<root>/<app>/webpack.config.ts",
    ],
)

# This is just webpack-dev-server which basically takes the place of ts_devserver.
# All this is doing is running the binary for webpack-dev-server then using the webpack bundle
nodejs_binary(
    name = "devserver",
    entry_point = "@npm//node_modules/webpack-dev-server:bin/webpack-dev-server.js",
    data = [
        ":webpack",
        "@npm//webpack-dev-server",
    ],
    templated_args = [
        "--node_options=--preserve-symlinks",
        "--config /<root>/<app>/webpack.config.ts",
    ],
)
```

This will allow you to use a hybrid angular 8 + AngularJS app or a pure AngularJS app within a project / monorepo that utilizes Bazel. Ultimately any new apps you spin up can be 100% Bazel using the tooling provided by the angular team (ng_module / ts_devserver / etc).
