### ISSUE TITLE
Angular package format detection doesn't work for Ivy-only packages

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#927]
```
"dependencies": {
"@angular/core": "angular/core-builds#master-ivy-aot",
}
```
doesn't contain metadata.json files so our detection logic here
https://github.com/bazelbuild/rules_nodejs/blob/818cfb2291a8fa9f683d16e8dcc24af7b0eb2870/internal/npm_install/generate_build_file.js#L695-L707
fails

**Comment by kyliau** [comment]
context: https://github.com/angular/core-builds/tree/master-ivy-aot
It looks like there is no "special" file here that we could use to detect APF.
Idea: for snapshots, we could include a magic file in repo to indicate angular package format.

**Comment by kyliau** [comment]
For third party packages published to npm we recommend running ngcc and bundling metadata.json so that wouldn't be a problem in the short term.

**Comment by alexeagle** [comment]
Nope, metadata.json is a View-Engine-specific artifact.

**Comment by codebreach** [comment]
Is `rules_nodejs` compatible with IVY?

Sorry I couldn't find any information elsewhere.

The `angular/components` and `angular/angular` repos seem to use `angular/bazel` with their own internal rules but `angular/bazel` is deprecated so just wanted to understand what is the correct way of doing this now?

FWIW, I have been trying to port our app using Ivy to bazel following the example here and I am getting weird errors relating to certain custom elements not being defined (they are). 

```
 error TS-998001: [ngtsc] 'sdk-label' is not a known element:
1. If 'sdk-label' is an Angular component, then verify that it is part of this module.
2. If 'sdk-label' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

3     <sdk-label [label]="label" [isRequired]="required"></sdk-label>
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  projects/draftkit/src/lib/input-field/input-with-label/input-with-label.component.ts:12:16
    12   templateUrl: "./input-with-label.component.html",
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component InputWithLabelComponent.
```

`sdk-label` is correctly defined and exported from a different `NgModule` which is in the `deps` of this `NgModule`

Is there a workaround for using IVY + Bazel while the examples here are updated?

**Comment by codebreach** [comment]
As per conversation on slack-

https://bazelbuild.slack.com/archives/CSACXKUBE/p1603786805015600

this was solved by adding `"postinstall": "ngcc",` to `scripts` in `package.json`

see https://github.com/bazelbuild/rules_nodejs/blob/stable/examples/angular/package.json#L76

**Comment by KrauseStefan** [comment]
I just hit this issue with a component only compiled to ivy from another team.

There has been little activity on this issue for almost a year now, are there any plans for addressing this issue?

The current workaround seems to be putting an `ANGULAR_PACKAGE` file in the 3rd-party dependency, is a more solid solution planned?

For any one else finding this thread my workaround is adding the `ANGULAR_PACKAGE` using the npm `postinstall` hook.
``` sh
    "postinstall": "echo '' > ./node_modules/@org/package/ANGULAR_PACKAGE;  ngcc",
```
