### ISSUE TITLE
BREAKING CHANGES for 1.0.0

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/rules_nodejs#934]
rules_nodejs is approaching 1.0 around September and we'd like to make all of our big breaking changes before then if possible. This is a tracking issue for the breaking changes that are likely coming.

Here is my initial list:
* remove `defs.bzl` from packages since `index.bzl` is preferred
* remove deprecated preserve_symlinks option
* remove jasmine_node_test from build_bazel_rules_nodejs (DONE https://github.com/bazelbuild/rules_nodejs/pull/940)
* remove deprecated internal/collect_es6_sources.bzl
* remove deprecated internal/node.bzl
* consistent naming of dependencies() functions. Rename functions such as `rules_foo_dependencies` -> `npm_bazel_foo_dependencies`

Please comment or add to this list.

//cc @alexeagle @Toxicable @Globegitter @kyliau @filipesilva @alan-agius4 @jbedard

**Comment by gregmagolan** [comment]
* move rollup into /packages/rollup and publish @bazel/rollup package
* jasmine attributes cleanup: https://github.com/bazelbuild/rules_nodejs/issues/513

**Comment by jbedard** [comment]
* move terser/minification out of rollup into own rule+package
* replace rollup `OutputGroup` api with new provider api

**Comment by alexeagle** [comment]
What's the difference between using a tracking issue versus a milestone? I think we already have the latter

**Comment by gregmagolan** [comment]
> What's the difference between using a tracking issue versus a milestone? I think we already have the latter

I think it would be a bit much to create an issue for every item so wanted a place to put this list and to get input into what other breaking changes we should make before 1.0. I'll attach the issue to the 1.0 milestone :)

**Comment by Globegitter** [comment]
It would be nice to get a proper Provider based API. 

In relation to that it will also be interesting to see if https://github.com/bazelbuild/bazel/issues/7347 gets flipped for Bazel 1.0.

**Comment by alexeagle** [comment]
- change the working directory of all nodejs_binary to the directory containing the entry script
- move custom module resolution logic to the FS layer and propagate to subprocesses

**Comment by alexeagle** [comment]
- rename `ts_devserver#static_files` to `assets` to match web_package

**Comment by alexeagle** [comment]
- drop support for Node 10 as soon as Node 12 is LTS

**Comment by alexeagle** [comment]
let's get this list into individual issues in the 1.0 milestone

**Comment by alexeagle** [comment]
- Bash wrappers for nodejs_binary and nodejs_library removed - means users won't have the "_bin" suffix

**Comment by alexeagle** [comment]
I've migrated everything here into issues in the 1.0 milestone.
