### ISSUE TITLE
rollup_bundle should accept .js inputs as srcs

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#94]
The Bazel idiom is that files should be listed in srcs[] while other rules are listed in deps[].

I'd expect rollup_bundle's attributes to be
```
        "srcs": attr.label_list(allow_files = [".js"]),
        "deps": attr.label_list(),
```

/cc @gregmagolan

**Comment by gregmagolan** [comment]
Closed with https://github.com/bazelbuild/rules_nodejs/pull/92/commits/e0c13a719c25ce547840b0c993c1591cdadd6856
