### ISSUE TITLE
nodejs_binary expands to untagged target, regardless of tags on rule

### ISSUE THREAD

**Issue by jwillebrands** [bazelbuild/rules_nodejs#953]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: nodejs_binary_macro

And thereby present in everything that uses it. We ran across it on our history_server target. 

### Is this a regression?
Don't think so.

### Description
The nodejs_binary_macro expands to a nodejs_binary and an sh_binary wrapper script. Tags are propagated to the sh_binary, not to the nodejs_binary, nor is it tagged 'manual'. As a result, it will be matched by target wildcards.

I'm not sure if this is intended. Our CI setup is currently very simple building and testing '//...'. We have a bunch of targets tagged as manual, including our history_server. However, because the history_server is a macro that uses nodejs_binary_macro, we end up with the untagged nodejs_binary that ends up being built, along with its dependencies.

The simple solution would be to tag the generated nodejs_binary manual as well. A similar change has been applied to nodejs_test_macro in #212. If the behaviour is intended, what is the rationale behind it?

## 🔬 Minimal Reproduction
https://github.com/jwillebrands/node_binary_tag

Obviously a very silly example, but it demonstrates the issue. The output of bazel query --output=build is the following:
```
# /home/jwillebrands/projects/node_binary_tag/BUILD.bazel:27:1
sh_test(
  name = "test",
  tags = ["manual"],
  generator_name = "test",
  generator_function = "nodejs_test_macro",
  generator_location = "/home/jwillebrands/projects/node_binary_tag/BUILD.bazel:27",
  data = ["//:test_bin"],
  srcs = ["//:test_bin.sh"],
  args = [],
)

# /home/jwillebrands/projects/node_binary_tag/BUILD.bazel:27:1
nodejs_test(
  name = "test_bin",
  tags = ["manual"],
  generator_name = "test",
  generator_function = "nodejs_test_macro",
  generator_location = "/home/jwillebrands/projects/node_binary_tag/BUILD.bazel:27",
  testonly = True,
  data = ["//:test-data-generator", "@bazel_tools//tools/bash/runfiles:runfiles"],
  entry_point = "//:test.js",
)

# /home/jwillebrands/projects/node_binary_tag/BUILD.bazel:20:1
genrule(
  name = "test-data-generator",
  tags = ["manual"],
  outs = ["//:testdata.json"],
  cmd = "echo '[0, 1, 1, 2, 3, 5, 8]' > $@",
)

# /home/jwillebrands/projects/node_binary_tag/BUILD.bazel:13:1
sh_binary(
  name = "bin",
  tags = ["manual"],
  generator_name = "bin",
  generator_function = "nodejs_binary_macro",
  generator_location = "/home/jwillebrands/projects/node_binary_tag/BUILD.bazel:13",
  testonly = False,
  data = ["//:bin_bin"],
  srcs = ["//:bin_bin.sh"],
  args = [],
)

# /home/jwillebrands/projects/node_binary_tag/BUILD.bazel:13:1
nodejs_binary(
  name = "bin_bin",
  visibility = ["//visibility:private"],
  generator_name = "bin",
  generator_function = "nodejs_binary_macro",
  generator_location = "/home/jwillebrands/projects/node_binary_tag/BUILD.bazel:13",
  testonly = False,
  data = ["//:expensive-data-generator", "@bazel_tools//tools/bash/runfiles:runfiles"],
  entry_point = "//:index.js",
)

# /home/jwillebrands/projects/node_binary_tag/BUILD.bazel:6:1
genrule(
  name = "expensive-data-generator",
  tags = ["manual"],
  outs = ["//:data.json"],
  cmd = "echo '[0, 1, 1, 2, 3, 5, 8]' > $@",
)
```
Note that absence of any tags on the bin_bin nodejs_binary target.
This results in the following build log:
```
Build options: --experimental_allow_incremental_repository_updates --symlink_prefix=dist/ --incompatible_strict_action_env --repository_cache=/home/jwillebrands/.bazel_cache/ --explain=log --verbose_explanations
Executing action 'BazelWorkspaceStatusAction stable-status.txt': unconditional execution is requested.
Executing action 'Creating source manifest for //:bin_bin': no entry in the cache (action is new).
Executing action 'Executing genrule //:expensive-data-generator': no entry in the cache (action is new).
Executing action 'Expanding template bin_bin.sh': no entry in the cache (action is new).
Executing action 'Expanding template bin_bin_loader.js': no entry in the cache (action is new).
Executing action 'Creating runfiles tree bazel-out/k8-fastbuild/bin/bin_bin.sh.runfiles': no entry in the cache (action is new).
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 18.04
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 0.28.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 19 15:19:51 2019 (1563549591)
Build timestamp: 1563549591
Build timestamp as int: 1563549591
Done in 7.68s.
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "7c4a690268be97c96f04d505224ec4cb1ae53c2c2b68be495c9bd2634296a5cd",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/0.34.0/rules_nodejs-0.34.0.tar.gz"],
)
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
I will try again to just remove the need for this macro. It was load-bearing on Windows but I think there is a better way to get an .exe or .cmd to launch the node process.

**Comment by alexeagle** [comment]
#1078 removes the wrappers
