### ISSUE TITLE
Use the newly added dependency pruning

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/rules_nodejs#968]
Bazel 0.27 has finally allowed Starlark access to dependency pruning, a feature that has previously been reserved only for native rules.

https://github.com/bazelbuild/bazel/commit/57363813d3c72129c61c35a2b03c3033b62cb49d

Implement `unused_inputs_list` for TypeScript compilation, thereby improving cache hits.

**Comment by pauldraper** [comment]
Correct. The requirement of `unused_inputs_list` is this:

> The content of this file (generally one of the outputs of the action) corresponds to the list of input files that were not used during the whole action execution. Any change in those files must not affect in any way the outputs of the action.

TypeScript mostly fits that requirement.

Ambient declarations present a problem however. Not sure if it's a fixable one or not.

**Comment by DavidANeil** [comment]
Currently we pass all transitive dependencies into the typescript compiler, and it reads them all.
This is a performance issue, so I (and, I believe, Evan Martin) am looking into ways to get `ts_library` to not need everything passed in through the `files` config.

Once that is done, we can look more into getting this working.
