### ISSUE TITLE
Allow import paths to be workspace-relative

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#969]
In https://github.com/bazelbuild/rules_typescript/issues/77 we let you
`import {} from 'my_wksp/src/some_file'`

but in some existing codebases there's an assumption that TypeScript is configured such that you can

`import {} from 'src/some_file'`

rather than require these applications to change all their imports, maybe we could allow the ts_library rule to be configured to work.

**Comment by alexeagle** [comment]
also worth noting what other rulesets do regarding default monorepo pathing

**Comment by gregmagolan** [comment]
No longer in scope for rules_nodejs which only supplies the Node.js toolchain as of [v6.0.0](https://github.com/bazelbuild/rules_nodejs/releases/tag/v6.0.0-beta0).

Downstream canonical JavaScript + Node.js ruleset is now https://github.com/aspect-build/rules_js.
