### ISSUE TITLE
Module resolution failing at runtime with module_name

### ISSUE THREAD

**Issue by pierreis** [bazelbuild/rules_nodejs#973]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: **ts_library**

### Is this a regression?

 Not sure

### Description

`module_path` prevents cross-module imports at runtime, although compilation works.

## 🔬 Minimal Reproduction

Project organization is:

```
base
  - src
    - index.ts
  - test
    - index.test.ts
  - BUILD.bazel
```

`BUILD.bazel` contains:

```
ts_library(
    name = "mylib",
    srcs = glob(["src/*.ts"]),
    module_name = "mylib",
    module_root = "src",
    deps = ["@npm//@types"],
)

ts_library(
    name = "mylib",
    srcs = glob(["test/*.ts"]),
    deps = ["@npm//@types", ":mylib"],
    module_name = "mylib-test",
    module_root = "test",
)

 jasmine_node_test(
    name = "mylib-test-binary",
    srcs = ["mylib-test"],
    deps = ["@npm//jasmine", "@npm//source-map-support"],
)
```

From the test files, I am trying to import the test files as `import { foo } from 'mylib'` or `import { foo } from '../src/index'`. Both version succeed at compile time, but fail at runtime.

If I get rid of the `module_name`, this fixes the issue, but requires me to import as `mylib/src`, which is not ideal either.

## 🔥 Exception or Error

```
INFO: From Testing //mylib:mylib-test-binary:
==================== Test output for //mylib:mylib-test-binary:
Failed to findPath for /private/var/tmp/_bazel_pmatri/02866ad850c0833f557d8ebd612bb4f6/sandbox/darwin-sandbox/1/execroot/mylib/bazel-out/darwin-fastbuild/bin/mylib/mylib-test-binary.sh.runfiles/test/mylib/src/src/index
Error: No file mylib/src/index found in module root test/mylib/src/src/index
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
OSX 10.14.2
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
$ bazel version
INFO: Invocation ID: 1ce0a52c-405b-4f8b-b1b8-314d6398bf6d
Build label: 0.20.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Nov 30 20:40:12 2018 (1543610412)
Build timestamp: 1543610412
Build timestamp as int: 1543610412
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>
0.22.1 (a1970bac0b866d431b179d299d747ef05bfb42e3)
  </code>
</pre>

**Comment by alexeagle** [comment]
Interesting, the same problem of repeated `src/src` segments was reported in https://github.com/bazelbuild/rules_nodejs/issues/834 but not fixed

**Comment by alexeagle** [comment]
looking in dist/bin/base/test/index_spec.js we see `require("mylib/src/index");` which is wrong, `mylib` is rooted in the `base/src` directory so it should be `require("mylib/index")

This file is produced by the TypeScript compiler. The sources for that are in another repo - here's the spot where we handle naming the index file:
https://github.com/bazelbuild/rules_typescript/blob/master/internal/tsc_wrapped/compiler_host.ts#L346

that is missing the moduleRoot as a prefix
