### ISSUE TITLE
npm_install is non-deterministic

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#98]
Thanks to @buchgr for debugging this.

The npm_install rule runs `npm install` and the resulting package.json file is not stable:
```
buchgr@buchgr0:~/code$ diff package1.json package2.json 
5c5
<   "_integrity": "sha1-2oEVQQzCps14cUVRrJKkLd4mdnY=",
---
>   "_integrity": "sha1-R2/vTKo8o0qUVsI0pBPoRMV9gcc=",
```

Since the value is different, it's not sufficient to just sort the keys.

As a result, all actions that rely on this toolchain get cache misses since the input doesn't have a stable hash.

**Comment by pcj** [comment]
A bit surprised you're using npm here.  

I struggled with non-determinism issues with npm in `rules_node` for a while and ultimately ditched npm altogether for yarn.  The problems included npm adding fields that are themselves non-deterministic like you're seeing above (requiring stripping certain "blacklisted" fields), and even weird "flaky" problems where the package *contents* were occasionally different (i.e., sometimes I'd get a tarball back  where the hash was unexpected, only to find an extra README file in there).

**Comment by alexeagle** [comment]
Changing to Yarn is totally an option. It's only npm because the
contributor who added the feature did it that way, and I wasn't aware of
the determinism issues.
Thanks Paul!

**Comment by gregmagolan** [comment]
https://github.com/bazelbuild/rules_nodejs/pull/106 adds yarn_install which can accept a yarn.lock file

**Comment by alexeagle** [comment]
@gregmagolan I think this is fixed?

**Comment by gregmagolan** [comment]
> @gregmagolan I think this is fixed?

Yes. npm_install should now be deterministic. I'll verify and add something to CI to check for both npm_install and yarn_install.
