### ISSUE TITLE
How can I use .js/.d.ts files generated with custom rule as a dependency in ts_library?

### ISSUE THREAD

**Issue by mikberg** [bazelbuild/rules_nodejs#986]
I have a custom rule which creates gRPC stubs and declarations using [grpc_tools_node_protoc_ts](https://github.com/agreatfool/grpc_tools_node_protoc_ts). The rule produces `.js` and `.d.ts` files, and I would like to use these in a different Typescript library.

Doing this naively, I end up with an error:

```
Dependencies must be ts_library, ts_declaration, or JavaScript library rules (js_library, pinto_library, etc, but also proto_library and some others).
```

I've fooled around with having my rule return a struct inspired by the `ts_library` rule and by `compile_ts`, but can't make it work.

Is this use case supported? Are there any examples of using these rules in this way?

**Comment by alexeagle** [comment]
Update, there is now a `DeclarationInfo` provider that TypeScript creates, still need to make it accept that in the inputs.

**Comment by sgammon** [comment]
@alexeagle related to the new `DeclarationInfo`, i'm now getting an error with `@bazel/typescript` at `1.2.0` (latest rn), with bazel `2.0.0`

```
/.../bin/bazelisk build //java/... //proto/... //js/...
ERROR: /.../BUILD.bazel:28:1: in ts_library rule //js/...:state: 
Traceback (most recent call last):
	File "/Volumes/PITBULL/Vault/.../js/gust/....bazel", line 28
		ts_library(name = 'state')
	File "/private/.../external/npm_bazel_typescript/internal/build_defs.bzl", line 265, in _ts_library_impl
		compile_ts(ctx, <4 more arguments>)
	File "/private/.../external/npm_bazel_typescript/internal/common/compilation.bzl", line 282, in compile_ts
		_collect_dep_declarations(ctx, <1 more arguments>)
	File "/private/.../external/npm_bazel_typescript/internal/common/compilation.bzl", line 122, in _collect_dep_declarations
		DeclarationInfo(<3 more arguments>)
unexpected keyword 'type_blacklisted_declarations' in call to DeclarationInfo(*, declarations = ?, transitive_declarations = ?)
```

am i mismatching versions somewhere, or is this a known issue?

**Comment by marcus-sa** [comment]
@sgammon I'm getting the same issue.

**Comment by loudmouth** [comment]
@marcus-sa did you revert `@bazel/typescript` to `1.1.0` or `bazel` itself?

**Comment by marcus-sa** [comment]
@loudmouth I reverted `@bazel/typescript` back to `1.1.0`

**Comment by KrauseStefan** [comment]
For those still waiting for this, the `node_module_library` can be modified to allow loading any set of d.ts and js files, remove the `NpmPackageInfo` provider and anything else npm related.
You might also want to replace `DeclarationInfo` with `provide_declarations` to be compatible with the documented best practice.
Although you would still get the error mentioned by @sgammon, just sync backup with `NpmPackageInfo` and you should be good.

We are currently using that approach until official support arrives.

I see there is an internal `js_library` will this eventually be able to be used instead and if so what is the progress?

https://github.com/bazelbuild/rules_nodejs/blob/master/internal/npm_install/node_module_library.bzl

**Comment by pierreis** [comment]
I do still have this issue, with a few more problems along the way.
I could use `declaration_info` to make TypeScript accept the `.js` / `.d.ts`.

One big remaining issue, that may or may not be linked to this issue, is to understand how files are mapped by `rules_nodejs`. I am dealing with generated gRPC / Profobuf files, and the rules do export the generated files in a subfolder:

```service/proto/address.proto -> service/proto/proto_gen/service/proto/address_pb.{js, d.ts}```

Say that I want to load that file from `service/server.ts`, I want to be able to `import "./proto/address_pb"`. This fails with module not found. Loading the file as `./proto_gen/service/proto/address_pb` works. In short, what is the mechanism I can use to remap files to the pay they do belong to?

**Comment by loudmouth** [comment]
With rules_nodejs 1.0.2 and bazel version 2.1.1 I was able to create a ts_library type in the following way. Also, [see my comment which has a zip of some examples in this issue](https://github.com/rules-proto-grpc/rules_proto_grpc/issues/47#issuecomment-672654397)
```
def _ts_grpc_library(ctx):
    direct_sources = []
    proto_paths = []

    es5_outputs = []
    ts_outputs = []

    # Build output file paths dynamically
    for d in ctx.attr.deps:
        for f in d[ProtoInfo].transitive_sources.to_list():
            # Hack hack away!
            proto_paths += [f.dirname.replace("/google/protobuf", "")]

        for f in d[ProtoInfo].direct_sources:
            basename = f.basename
            if basename.endswith(".proto"):
                direct_sources += [f.path]
                basename = basename[:-6]

            ts_outputs += [ctx.actions.declare_file(basename + "_grpc_pb.d.ts")]
            ts_outputs += [ctx.actions.declare_file(basename + "_pb.d.ts")]
            es5_outputs += [ctx.actions.declare_file(basename + "_grpc_pb.js")]
            es5_outputs += [ctx.actions.declare_file(basename + "_pb.js")]

    inputs = []
    for d in ctx.attr.deps:
        inputs += d[ProtoInfo].transitive_sources.to_list()

    commands = []

    commands += [ctx.executable.ts_compiler.path + " " + " ".join([
        "--ts_out=service=true:.",
        "--proto_path=.",
        " ".join(["--proto_path=%s" % p for p in proto_paths]),
        " ".join(direct_sources),
    ])]

    commands += [ctx.executable.js_compiler.path + " " + " ".join([
        "--js_out=import_style=commonjs,binary:.",
        "--grpc_out=.",
        "--proto_path=.",
        " ".join(["--proto_path=%s" % p for p in proto_paths]),
        " ".join(direct_sources),
    ])]

    for o in ts_outputs + es5_outputs:
        commands += ["cp %s %s" % (o.short_path, o.path)]

    ts_sources = depset(ts_outputs)
    es5_sources = depset(es5_outputs)

    files_depsets = []
    files_depsets.extend([ts_sources])
    files_depsets.extend([es5_sources])

    command = " && ".join(commands)

    ctx.actions.run_shell(
        command = command,
        inputs = inputs,
        outputs = ts_outputs + es5_outputs,
        tools = [ctx.executable.ts_compiler, ctx.executable.js_compiler],
    )

    declarations = ts_sources
    es5_sources = es5_sources
    es6_sources = depset()

    # buildifier: disable=rule-impl-return
    return struct(
        providers = [
            DefaultInfo(files = declarations),
            DeclarationInfo(
                declarations = declarations,
                transitive_declarations = declarations,
                # type_blacklisted_declarations = depset([]),
            ),
            JSNamedModuleInfo(
                direct_sources = es5_sources,
                sources = es5_sources,
            ),
            JSEcmaScriptModuleInfo(
                direct_sources = es6_sources,
                sources = es6_sources,
            ),
        ],
        typescript = struct(
            declarations = declarations,
            transitive_declarations = declarations,
            type_blacklisted_declarations = depset(),
            es5_sources = es5_sources,
            es6_sources = es6_sources,
            transitive_es5_sources = es5_sources,
            transitive_es6_sources = es6_sources,
        ),
    )
```
