### ISSUE TITLE
ts_web_test: use headless chrome when not debugging

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#990]
in google3 we use headless chrome
via https://github.com/karma-runner/karma-chrome-launcher#headless-chromium-with-puppeteer

when the user does `ibazel run :my_web_test`
because ibazel is the reporter.

When run with `bazel test` or `ibazel test`, then we do open the window, assuming that users are running the test only once so they would like to debug.

/cc @vikerman

**Comment by KrauseStefan** [comment]
This is not fixed and is still an issue for windows
