### ISSUE TITLE
Consider adding tslib to ts_devserver's default deps

### ISSUE THREAD

**Issue by appsforartists** [bazelbuild/rules_nodejs#994]
I have a `BUILD` that looks like this:

```python
ts_library(
  name = "playground",
  module_name = "dgitize-playground",
  module_root = "src",
  srcs = glob(
    include = ["src/**/*.ts", "src/**/*.tsx"],
    exclude = ["**/__tests__/*"],
  ),
  deps = ["//packages/core"],
  tsconfig = "//:tsconfig.json",
)

ts_devserver(
  name = "devserver",
  deps = [
    "//:node_modules/react/umd/react.development.js",
    "//:node_modules/react-dom/umd/react-dom.development.js",
    "//:node_modules/jsxstyle/jsxstyle.amd.js",
    "//:node_modules/jsxstyle-utils/jsxstyle-utils.amd.js",
    ":playground",
  ],
  entry_module = 'dgitize_root/packages/playground/src/index',
  serving_path = "/dist/bundle.js",
  static_files = ["site/index.html"],
)
```

`:core` uses argument destructuring, so TypeScript required that I install `tslib`.  Then, the JS served by `ts_devserver` complained that I didn't import `tslib`.  I was able to resolve that by adding this `dep` to `ts_devserver`:
```python
"//:node_modules/tslib/tslib.js",
```

Is including `tslib` something `ts_devserver` should do automatically?

**Comment by taymonbeal** [comment]
In google3, tslib is an implicit dep of every `ts_library`. Open source Angular sort of emulates this by wrapping `ts_library` in a Starlark macro. Is there any reason why open source `ts_library` shouldn't just do this?
