### ISSUE TITLE
ts_library is too restrictive: can't set target (duplicate of #122)

### ISSUE THREAD

**Issue by eordano** [bazelbuild/rules_nodejs#996]
### Description

Observations:

- It would be helpful if you could point me to where can I read to understand the design decisions around not allowing users of `ts_library` to set the `target` of their library, being this one of the most important Typescript compiler settings.
- I hope that this material could also explain the concepts of "prod" vs "dev" environment -- my first impression was that this is too opinionated, and it's pretty painful (at least for a bazel noob like myself) to new user to set up other environments
- The best workaround I found, without forking the bazel rules is to use `devmodeTargetOverride` -- but this breaks my tsconfig linting.
- I spotted some inconsistency with the configuration of values being picked up between the BUILD and the tsconfig file: if I understand correctly, `tsconfig.json` settings are less preferable than `BUILD` files, but `devmodeTargetOverride` is a tsconfig parameter (I think it should be a BUILD parameter), while `path`, `target`, and other variables from the tsconfig are ignored/rejected..

### Asks:

Would it be too hard to have a sensible default (`es5`) and allowing the value to be set by as a rule argument/the original tsconfig?

I see a couple of alternatives:

- Add a `overrideTarget` (true by default) that triggers the current (prod/dev) behavior of selecting the `target`, for compatibility with all the current BUILD files. If this is set to false, the compilation target on the `tsconfig.json` is respected.
- Add a `compilationTarget` setting that overrides the `target`. This would offer the same functionality than `devmodeTargetOverride` (see [tsc_wrapped#316]), but it looks less "hackish" (what if my production build chain uses this?) 

Thanks!

[tsc_wrapped#316]: https://github.com/bazelbuild/rules_typescript/blob/8d8d398caf7d77620e66502adc51cc1a83def0f6/internal/tsc_wrapped/tsconfig.ts#L316

**Comment by alexeagle** [comment]
Current plan is to add a third JS flavor output by ts_library that honors nearly all your tsconfig settings (not outDir, rootDir, and such)

**Comment by eordano** [comment]
I think this is now much better addressed in the documentation. Thank you for the awesome work you've been putting in lately!
