### ISSUE TITLE
install_bazel_dependencies() equivalent for local npm packages

### ISSUE THREAD

**Issue by ramblehead** [bazelbuild/rules_nodejs#998]
Thank you open-sourcing bazel and node/typescript rules!

# Subj. backstory

We are working on an embedded web server for devices' remote control. The server back-end is mostly written in C++ using Wt library. Originally, we used cmake for building. About, six months ago the project compilation duration grew up to 10 minutes. At around the same time we decided to try bazel. Bazel brought down compilation duration to 5 min straight after initial setup. Then we discovered how well bazel allows splitting projects into independent repositories and the possibility of remote builds. So, we made a switch from cmake to bazel and quite happy with that decision.

More recently we added ```node```, ```typescript```, and ```react``` to our toolchain.

I tried to use ```bazel``` to build ```typescript``` parts of the project – both front-end and back-end. That is when I discovered ```rules_nodejs```.

# Initial ```rules_nodejs``` usage results

Front-end bit worked out-of-the box, while back-end had some issues:
* Produced code was in ```es5``` or ```ed2015```, while we needed ```es2018``` (due to some libraries requirements).
* Produced modules were ```UMD```, while we needed ```requirejs``` (the code should only work on node at server-side).

# Attempts to patch rules_nodejs and rules_typescript to produce es2018 and requirejs

https://github.com/ramblehead/bazel-rules-typescript/tree/rh_overrides
https://github.com/ramblehead/bazel-rules-nodejs/tree/rh_overrides

The above links are the forks from the original bazelbuild projects (see ```rh_overrides``` git branch) which allow the following rule to work as expected:

```python
ts_library(
  name = "castle",
  srcs = glob(["server/**/*.ts"]),
  runtime = "nodejs",
  rh_target_override = "es2018",
  rh_module_override = "commonjs",
  deps = [
    "@npm//koa",
    "@npm//@types/koa",
    "@npm//apollo-server-koa",
    "@npm//type-graphql",
    "@npm//arangojs",
  ],
)
```
A tiny working project which uses the rule above is located at the following link:
https://github.com/artizanya/castle-bazel

I understand that NodeJS rules are still at a beta stage and there might be breaking changes. However, the results of the initial experiments were promising and I thought to try adopting nodejs and typescript rules for bazel. While working on the above ```castle-bazel``` project I came across two related questions which felt appropriate for the github issues.

# Questions

* When working with locally built ```rules_nodejs``` npm packages (e.g. ```release/npm_bazel_typescript```), there is only one way I could find to import them into dependant project: use auto-generated ```install_bazel_dependencies()``` from ```yarn_install``` and modify ```package.json``` to refer to the local repository (e.g. ```file:.meta/bazel-rules-nodejs/release/npm_bazel_typescript```). Is it possible to ```*install_bazel_npm_package()*``` directly from a local npm package directory (e.g. ```release/npm_bazel_typescript```) bypassing ```package.json/yarn.lock``` stage?

* The ```scripts/build_all.sh``` were recently removed from the source tree. What is the right way at the moment to build ```rules_nodejs``` from source?

**Comment by Toxicable** [comment]
>Produced code was in es5 or ed2015, while we needed es2018 (due to some libraries requirements).

For nodejs_binary you use use `devmodeTargetOverride` to specify a target override.

>Produced modules were UMD, while we needed requirejs (the code should only work on node at server-side).

The module at runtime shouldn't matter for any lib when using nodejs as a runtime

---

Relating to your attempts to patch rules_nodejs, I don't think introducing a per `ts_library` solution is a good idea since the application runs with many different ts_library's output and they should all be the same 

@alexeagle is working on another design around how the ts target is handled
https://github.com/bazelbuild/rules_nodejs/issues/985#issuecomment-520155254

Related https://github.com/bazelbuild/rules_nodejs/issues/996

**Comment by ramblehead** [comment]
@Toxicable thank you for the devmodeTargetOverride hint.

I agree on your points regarding UMD and per ts_library patch (although, UMD introduces additional indirection which could be shaved by Occam's razor).

My rh_target and rh_module overrides are essentially a monkey patch which lets us get started with rules_nodejs before it is out of beta.

Being able to patch the source code, build it and use the modified version locally is necessary to work around temporary issues as they arise, before the proper solution is released. That is the reason for the questions in my original issue - *correct building procedure* and the *most direct way to use the locally built packages*.

**Comment by Globegitter** [comment]
Maybe you can somehow get it to work with a `local_repository` but have not tried it myself yet. You could also ask on Slack, sometimes one can get responses there quicket.

**Comment by alexeagle** [comment]
https://github.com/bazelbuild/rules_nodejs/blob/master/docs/index.md#patching-the-built-in-release is newly added and documents how to apply your patch without having to build rules_nodejs from source.

Do you still need a patch though, now that you have a way to control the typescript `--target` ?

This is another good reminder that users should be able to select their own TS output as the default outputs.

**Comment by ramblehead** [comment]
Thank you all for the replies! Here is our update on the state of Subj. and related target/module override discussion.

# Repository location management

With repository location (remote/local/upstream/etc.) management we are now using a small ```select_repository()``` helper macro:

```python
# Somewhere in WORKSPACE file

git_repository(
  name = "rh_bazel_utils",
  remote = "https://github.com/ramblehead/bazel-utils.git",
  commit = "456cef0e8af31c0fd98645381c14f2338b748226",
  shallow_since = "1565016199 +0100",
)

load("@rh_bazel_utils//:index.bzl", "select_repository")

select_repository(
  key = "local",
  name = "build_bazel_rules_typescript",
  repositories = {
    # This selection does not work yet - need to learn how to apply patches:
    # https://github.com/bazelbuild/rules_nodejs/issues/998#issuecomment-521317102
    "default": {
      "rule": git_repository,
      "kwargs": {
        "remote": "http://github.com/bazelbuild/rules_typescript.git",
        # tag = "0.34.0",
        "commit": "a390e0a4b02baa93895ea9139fa13105d11258bd",
        "shallow_since": "1563926047 -0700",
      },
    },
    "local": {
      "rule": local_repository,
      "kwargs": {
        "path": "../bazel-rules-typescript",
      },
    },
  },
)
```

Commenting-out ```key``` parameter would select ```“default”``` repository. Adding repository ```key``` would select the chosen repository and would print a debug message to the console.
 
The following ```load()``` would prefer ```“local”``` over ```“default”``` as the default repository (i.e. when ```"key"``` parameter is omitted):

```python
load("@rh_bazel_utils//:index.bzl", select_repository = “select_repository_local”)
```

# rh_target and rh_module overrides

I further refactored the previous patch ([rules-nodejs](https://github.com/ramblehead/bazel-rules-nodejs/tree/03ab38ad3c9c2fc5b832eb3877b7224c5cf1905d) and [rules-typescript](https://github.com/ramblehead/bazel-rules-typescript/tree/260b58a7dcb61b96f7b2a49d298bd9fb31bffefa)) to use Bazel’s “[build_setting](https://docs.bazel.build/versions/master/skylark/config.html#starlark-build-configurations)” rules. A usage example (from [castle-bazel](https://github.com/artizanya/castle-bazel/tree/fb94fb2785956b211c8c17946816c9aae28ed469)):

```python
# In BUILD file

load(
  "@npm_bazel_typescript//:index.bzl",
  "rh_target",
  "rh_module"
)

rh_target(
  name = "rh_target_override",
  build_setting_default = "es2018",
)

rh_module(
  name = "rh_module_override",
  build_setting_default = "commonjs",
)

# The following commented load() should fail!
# So it is impossible to accidentally load "ts_library"
# from "@npm_bazel_typescript//:index.bzl":
#
# load("@npm_bazel_typescript//:index.bzl", "ts_library") # <-- WILL FAIL!

load(":ts_library.bzl", "ts_library")

ts_library(
  name = "castle",
  srcs = glob(["server/**/*.ts"]),
  deps = [
    "@npm//koa",
    "@npm//@types/koa",
    "@npm//apollo-server-koa",
    "@npm//type-graphql",
    "@npm//arangojs",
  ],
)
```

```python
# ts_library.bzl file content. This file is located next to BUILD file.

load("@npm_bazel_typescript//:index.bzl", _ts_library = "ts_library")

def ts_library(**kwargs):
  _ts_library(
    runtime = "nodejs",
    rh_target_override = ":rh_target_override",
    rh_module_override = ":rh_module_override",
    **kwargs)
```

With this approach, it should be impossible to forget to specify target and module or to accidentally use unpatched version of ```ts_library()```. It should also be difficult set different target and module in different ```ts_library()``` calls by mistake.

In the future, when ```rh_target``` and ```rh_module``` are no longer required, we would only need to change one file: ```ts_library.bzl```.

# install_bazel_dependencies

We ended-up using ```install_bazel_dependencies()``` from ```yarn_install``` as it is feels simpler than alternative solutions. However, one should remember to do ```bazel clean --expunge``` in repositories with local npm dependencies (e.g. ```"file:/path/to/nodejs/package"```) in ```package.json```. It seems that doing just ```bazel clean``` would keep a previously installed package version in the cache.
```npm``` also does not make it simple to switch between remote and local repositories - but that is a common problem with npm packages.

# Build rules_nodejs from source

We are still looking for the best way to build locally from source during code reviews and patching.

@alexeagle thank you for the "patching-the-built-in-release" reference. I will try to use this approach. It would be great if developers requiring patched bazel rules would not need to build them locally and we would not need to roll our patched release!

Would it possible to pull ```"//path/to/my.patch"``` (in ```http_archive``` call) from git as well? E.g. defining ```"//path/to/my.patch"``` label with ```git_repository``` in ```WORKSPACE``` file?

**Comment by alexeagle** [comment]
yes, `git_repository` supports `patches` as well.

**Comment by ramblehead** [comment]
The following is what we are currently using as a solution to this issue:

Both ```build_bazel_rules_nodejs``` and ```npm_bazel_typescript``` __releases__ with "rh_overrides" are pushed to their own git branches:

* https://github.com/ramblehead/bazel-rules-nodejs/tree/build_bazel_rules_nodejs-0.36.0-rh_overrides
* https://github.com/ramblehead/bazel-rules-nodejs/tree/npm_bazel_typescript-0.36.0-rh_overrides

Then Bazel ```WORKSPACE``` can refer to patched ```build_bazel_rules_nodejs``` and NPM ```package.json``` can refer to ```npm_bazel_typescript``` as ```@bazel/typescript``` - both straight from github without the need for building locally or publishing to npm. Thus, eliminating the need for Subj.

Then, our ```tsconfig.json``` is placed into a separate Bazel repository called ```rh-ts-library```. Additionally to ```tsconfig.json```, ```rh-ts-library``` repository has ```index.bzl``` file with the following content:

```python
load("@npm_bazel_typescript//:index.bzl", _ts_library = "ts_library")

load(
  "@npm_bazel_typescript//:index.bzl",
  "rh_target",
  "rh_module",
)

def ts_library(tsconfig = None, **kwargs):
  if "rh_target_override" not in native.existing_rules():
    rh_target(
      name = "rh_target_override",
      build_setting_default = "es2018",
    )

  if "rh_module_override" not in native.existing_rules():
    rh_module(
      name = "rh_module_override",
      build_setting_default = "commonjs",
    )

  if not tsconfig:
    tsconfig = "@rh_ts_library//:tsconfig.json"

  _ts_library(
    runtime = "nodejs",
    rh_target_override = ":rh_target_override",
    rh_module_override = ":rh_module_override",
    tsconfig = tsconfig,
    **kwargs)
```
Then, Bazel BUILD file which is using patched ```ts_library``` can do something like the following:
```python
load("@rh_ts_library//:index.bzl", "ts_library")

ts_library(
  name = "castle",
  module_name = "@artizanya/castle",
  srcs = [
    "run.ts",
  ] + glob(
    ["server/**/*.ts"],
  ),
  deps = [
    "@npm//@types/node",
    "@npm//koa",
    "@npm//@types/koa",
    "@npm//apollo-server-koa",
    "@npm//type-graphql",
    "@npm//arangojs",
  ],
)
```

```load("@rh_ts_library//:index.bzl", "ts_library")``` line makes sure that all ```ts_library()``` calls are done against the same target, module type and "tsconfig.json".

Such arrangement resolves this issue and we hope that to should allow us an easy transition to native ```ts_library()``` once it supports target and module overloads.

Thank you for help and for Bazel and for rules_nodejs! :)

**Comment by alexeagle** [comment]
okay sounds good then
